substrate/bft/src/generic/tests.rs
(and makes the timeout mechanism used in tests more correct in the meantime)
=> add BFT-with-startup-delay test

.travis.yml, polkadot/service/src/lib.rs, substrate/client/src/client.rs, substrate/network/src/protocol.rs, substrate/network/src/service.rs, substrate/network/src/sync.rs, substrate/network/src/test/mod.rs
=> Fixed block proagation after import and import notifications

substrate/executor/src/sandbox.rs, substrate/executor/src/wasm_executor.rs
This changes allows the execution of the start function (if any).
=> Sandbox: run start function.

substrate/client/src/client.rs, substrate/network/src/consensus.rs, substrate/network/src/protocol.rs
=> Backport of #191

substrate/bft/src/generic/mod.rs
Also now processes messages after each imported.
Should be fine, it just puts the entire responsibility of DoS mitigation onto the stream implementation itself. Using Aardvark techniques should be good enough in that respect.
=> store all future messages in BFT

build.sh, ci/publish-wasm.sh, ci/script.sh, common.sh, demo/runtime/wasm/build.sh, init.sh, polkadot/parachain/test-chains/basic_add/build.sh, polkadot/parachain/test-chains/build.sh, polkadot/runtime/wasm/build.sh, substrate/executor/wasm/build.sh, substrate/test-runtime/wasm/build.sh, update-genesis.sh
Refer to https://github.com/dylanaraps/pure-bash-bible#shebang
=> Use #!/usr/bin/env bash instead of #!/bin/bash

polkadot/cli/src/lib.rs, polkadot/service/src/components.rs, polkadot/service/src/lib.rs, substrate/ed25519/src/lib.rs
=> Gav display addrs

Cargo.lock, polkadot/cli/src/chain_spec.rs, polkadot/cli/src/cli.yml, polkadot/cli/src/lib.rs, polkadot/service/src/chain_spec.rs
- Rename poc-2 to staging
- Make telemetry default for global chains
=> PoC-2 tweaks

Cargo.lock, demo/executor/Cargo.toml, demo/executor/src/lib.rs, polkadot/cli/src/cli.yml, polkadot/cli/src/lib.rs, polkadot/service/src/components.rs, polkadot/service/src/config.rs, polkadot/service/src/lib.rs, substrate/client/db/src/lib.rs, substrate/client/src/block_builder.rs, substrate/client/src/call_executor.rs, substrate/client/src/client.rs, substrate/client/src/genesis.rs, substrate/client/src/light/call_executor.rs, substrate/client/src/light/mod.rs, substrate/executor/src/error.rs, substrate/executor/src/lib.rs, substrate/executor/src/native_executor.rs, substrate/executor/src/sandbox.rs, substrate/executor/src/wasm_executor.rs, substrate/runtime/consensus/src/lib.rs, substrate/state-machine/src/lib.rs
New `--execution` CLI parameter.
Closes #298
=> Dual execution

substrate/network-libp2p/src/service.rs
* Prints the full node address at startup, so that it can easily be copy-pasted.
* Prints on `info!` whenever we discover a new external address.
* Improves the error message on public key mismatch error.
=> Better reporting in libp2p

Cargo.toml
This minor change adds Badges to Cargo.toml
=> Add badges

polkadot/network/src/lib.rs, substrate/network/src/consensus_gossip.rs
A temporary measure until we get a more stable network.
=> Gossip through all peers.

README.md, polkadot/cli/src/lib.rs, polkadot/transaction-pool/src/lib.rs, substrate/primitives/src/hexdisplay.rs, substrate/telemetry/src/lib.rs
- Make telemetry less susceptible to flakey wifi
- Update readme
- Staging shouldn't autoconnect to telemetry
- Don't try to output more than 1KB of hex to Display
- Better logging of transactions
=> Various small v0.2 improvements

Cargo.lock, Cargo.toml, polkadot/cli/Cargo.toml, polkadot/cli/src/lib.rs, polkadot/cli/src/panic_hook.rs
Stops the process if any thread panics.
=> Panic hook

substrate/network/src/protocol.rs, substrate/telemetry/src/lib.rs
=> Fix telemetry

polkadot/network/src/lib.rs, polkadot/network/src/tests.rs, substrate/network-libp2p/src/network_state.rs, substrate/network-libp2p/src/service.rs, substrate/network-libp2p/src/traits.rs, substrate/network-libp2p/tests/tests.rs, substrate/network/src/blocks.rs, substrate/network/src/consensus_gossip.rs, substrate/network/src/import_queue.rs, substrate/network/src/io.rs, substrate/network/src/lib.rs, substrate/network/src/on_demand.rs, substrate/network/src/protocol.rs, substrate/network/src/service.rs, substrate/network/src/specialization.rs, substrate/network/src/sync.rs, substrate/network/src/test/mod.rs
The low-level ping is flakey. Don't drop the peer due to low-level ping failure unless there are no functional protocols running with the peer.
=> Style fixes

substrate/state-db/src/lib.rs, substrate/state-db/src/unfinalized.rs
=> Keep last finalized overlay in memory until DB commit

substrate/keystore/src/lib.rs, substrate/service/src/lib.rs
=> Fix the --key generation

polkadot/consensus/src/service.rs, polkadot/consensus/src/shared_table/mod.rs
=> fix some formatting grumbles

Cargo.lock, substrate/bft/src/lib.rs
forward-port of #582 (substrate changes only)
=> [forward port] continue rounds

Cargo.lock, polkadot/consensus/src/service.rs, substrate/bft/src/lib.rs
...this will occur if the block produced by BFT is bad, and then nodes will continue with the BFT process as if the committed bad block were simply triggered a round advancement.
=> Continue from next round when re-building on same block

Cargo.lock, substrate/rpc/Cargo.toml, substrate/rpc/src/chain/mod.rs, substrate/rpc/src/chain/tests.rs, substrate/rpc/src/lib.rs, substrate/runtime/version/src/lib.rs
=> RPC for returning the runtime version

substrate/network-libp2p/src/service.rs
Same as #652 but backported to v0.2.
=> Backport: Fix warnings in networking

README.adoc
Reverts paritytech/substrate#631
=> Revert "fix wasm executor compile error"

substrate/network-libp2p/src/service.rs
Before:
```
$ touch 
$ cargo check -p substrate-network-libp2p
Finished dev [unoptimized + debuginfo] target(s) in 4m 38s
$ cargo build -p substrate-network-libp2p
Finished dev [unoptimized + debuginfo] target(s) in 8m 42s
```
After:
```
$ cargo check -p substrate-network-libp2p
Finished dev [unoptimized + debuginfo] target(s) in 1.85s
$ cargo build -p substrate-network-libp2p
Finished dev [unoptimized + debuginfo] target(s) in 36.97s
```
CI runs in 12 minutes instead of 27
=> Speedup compilation of substrate-network-libp2p

Cargo.lock, substrate/network-libp2p/Cargo.toml, substrate/network-libp2p/src/network_state.rs, substrate/network-libp2p/src/service.rs, substrate/network-libp2p/src/topology.rs
Backport of #688 (not reviewed yet) to the branch v0.2.
=> Improvements to the Kademlia system

Cargo.lock, substrate/runtime-support/Cargo.toml, substrate/runtime-support/src/event.rs, substrate/runtime-support/src/lib.rs
=> Implement json metadata for outer events

substrate/network-libp2p/src/service.rs
- The Kademlia kbuckets (which is where we pick elements to return from a Kademlia query) will now only contain the bootstrap nodes and the nodes which we successfully connected to with substrate. In other words, only substrate nodes should now be reported.
- If failed to upgrade to substrate with a node, we disconnect from it and it loses reputation.
- The loop for connection to new peers was accidentally 5 seconds instead of 1.
Once deployed (in particular to the bootnodes), this should help solve the connectivity.
=> Try to remove IPFS nodes from DHT

srml/staking/src/lib.rs
=> SRML: fix OOB in srml_staking new_era.

core/primitives/src/hasher.rs, core/primitives/src/uint.rs
This makes it possible to have fields in Header/Block that is `U256`.
=> Implement codec for U256

core/client/src/client.rs, core/client/src/error.rs
(removed errors that are not used by the code)
=> Cleanup client errors

core/executor/src/sandbox.rs, core/sr-primitives/src/lib.rs, node/runtime/src/lib.rs
Progress on: https://github.com/paritytech/substrate/issues/715
=> Bkchr impl macros scope

core/primitives/src/authority_id.rs
=> SS58 addresses in BFT

core/client/db/src/lib.rs, core/client/db/src/utils.rs, core/client/src/backend.rs, core/client/src/in_mem.rs, core/client/src/light/backend.rs
To be used by consensus engine.
=> Auxiliary data storage in client backend

srml/session/src/lib.rs, srml/timestamp/src/lib.rs
=> Updating Moment to support Mul/Div with BlockNumber

srml/session/src/lib.rs, srml/timestamp/src/lib.rs
=> Add missing `As` imports.

core/network-libp2p/src/custom_proto.rs
This removes the packet ID system from the networking, thereby removing one byte of data from every packet.
This is a breaking change to the network, so validators should all be updated together.
=> Remove the packet ID system

core/network/src/service.rs
=> fix one typo

Cargo.lock, core/sr-primitives/Cargo.toml, core/test-runtime/wasm/Cargo.lock, node/runtime/wasm/Cargo.lock, node/runtime/wasm/Cargo.toml
=> Use the upstream version of integer-sqrt.

srml/contract/COMPLEXITY.md
- Add specification of revert
- Account for "drain to death" situations: when account is deleted all its storage entries is purged, which takes time proportional to the number of them.
=> Refine Complexity.md

core/telemetry/src/lib.rs
i was seeing an issue where a `telemetry!` call in `TelemetryConfig.on_connect` would fail silently. 
this seems to be due to initiating the websocket connection in [`TelemetryWriter::new`](https://github.com/paritytech/substrate/blob/79fffa2de3db288700da97e35cd7040cd685f7a2/core/telemetry/src/lib.rs#L128) which is called [before](https://github.com/paritytech/substrate/blob/79fffa2de3db288700da97e35cd7040cd685f7a2/core/telemetry/src/lib.rs#L60) the `slog::set_global_logger` [call](https://github.com/paritytech/substrate/blob/79fffa2de3db288700da97e35cd7040cd685f7a2/core/telemetry/src/lib.rs#L65).
this isn't an issue with >10ms latency between the node and the server, but was an issue for local testing.
=> telemetry: wait for logger setup before making connection

Cargo.lock, core/network-libp2p/Cargo.toml, core/network-libp2p/src/custom_proto.rs, core/network-libp2p/src/node_handler.rs, core/network-libp2p/src/service_task.rs, core/network-libp2p/src/swarm.rs, core/network-libp2p/src/transport.rs
Allows testing #931 before merging it.
=> Backport #931 to bbq-birch

core/network/src/import_queue.rs
The problem was that:
1. import thread's stop check was performed prior setting it in the `stop` function,
2. stop notification was performed prior import thread listening to the signal,
the fix is to perform signalling and setting the stop flag under the same mutex that is used for waiting on signal, which is typical way for condvar usage anyway.
=> Fix race in import queue stopping

core/sr-primitives/src/generic/unchecked_extrinsic.rs, srml/support/src/dispatch.rs
=> Fix extrinsic impl

srml/contract/src/gas.rs
This fixes another instance of overflow while manipulating balances.
=> Fix overflow in srml-contract

Cargo.lock, substrate/rpc/Cargo.toml
This PR is required for building on our [Hydra](https://hydra.aira.life/jobset/aira/polkadot), please read issue at paritytech/substrate#549.
=> Removed duplicate source, fix paritytech/substrate#549

CODE_OF_CONDUCT.adoc, CONTRIBUTING.adoc
- docs: fix link in code of conduct
- docs: fix typo in contrib guidelines
=> docs: typo and formatting fixes in code of conduct and contributors guidelines

Cargo.lock, README.adoc, core/client/Cargo.toml, core/client/db/Cargo.toml
Progress on: https://github.com/paritytech/substrate/issues/448
=> Update `rocksdb` to try minimizing memory leaks

subkey/src/cli.yml, subkey/src/main.rs, subkey/src/vanity.rs
Also minor improvements in subkey as the commit messages say
=> Add simple keygen command to subkey

core/cli/src/lib.rs, core/cli/src/params.rs, core/service/src/components.rs, core/service/src/config.rs, core/service/test/src/lib.rs
=> Add cli param to limit database cache size

core/client/db/src/light.rs, core/client/src/in_mem.rs, core/client/src/light/backend.rs, core/client/src/light/blockchain.rs
=> AuxStore on light clients

srml/contract/COMPLEXITY.md, srml/contract/src/tests.rs, srml/contract/src/vm/mod.rs
Minor follow up for #1255 
cc @Robbepop
=> srml-contract: caller follow-up

Cargo.lock, core/executor/Cargo.toml, core/sr-sandbox/Cargo.toml, node/executor/Cargo.toml, srml/contract/Cargo.toml
If there were any test build problems with Windows this should fix them.
=> Update wabt to 0.7

Cargo.lock, core/client/src/client.rs, core/consensus/aura/Cargo.toml, core/consensus/aura/src/lib.rs, core/consensus/common/Cargo.toml, core/consensus/common/src/error.rs, core/consensus/common/src/import_queue.rs, core/consensus/common/src/lib.rs, core/finality-grandpa/src/lib.rs, core/finality-grandpa/src/tests.rs, core/network/src/chain.rs, core/network/src/lib.rs, core/network/src/protocol.rs, core/network/src/service.rs, core/network/src/sync.rs, core/network/src/test/block_import.rs, core/network/src/test/mod.rs, core/service/src/chain_ops.rs, core/service/src/components.rs, core/test-client/src/client_ext.rs
=> Move import queue out of network

Cargo.lock, core/cli/src/informant.rs, core/service/Cargo.toml, core/service/src/lib.rs
(also removed unnecessary dependency from `substrate-service`)
=> log on reorganization

srml/staking/src/lib.rs, srml/staking/src/tests.rs
Calculate total slash at once and avoid depositing events on intermediary slashes. Also fixes a bug on next slash overflow.
=> Improve offline slashing calculation

core/cli/src/informant.rs
Closes #1316 
Only on the interval, not on notifications (since these might come often or while syncing, and to avoid flood).
Also adds `finalized_height` and `finalized_hash` telemetry items. CC https://github.com/paritytech/substrate-telemetry/issues/95
=> informant: display finalized height and hash

core/sr-primitives/src/lib.rs, node/primitives/src/lib.rs
=> Ensure opaque extr serialise is same as transparent

core/sr-primitives/src/lib.rs, node/primitives/src/lib.rs
=> Fix serialization of extrinsics.

.gitlab-ci.yml
add steps to the gitlab ci for uploading the crate docs to a aws bucket.
=> [CI] Publish rustdoc

core/sr-io/without_std.rs
=> Get rid of memcpy in to_vec()

core/sr-primitives/src/lib.rs, srml/support/src/event.rs, srml/support/src/origin.rs, srml/support/src/runtime.rs
Related to https://github.com/paritytech/substrate/issues/1288
=> Documentation for the macros that define a Runtime and associated types.

core/consensus/aura/Cargo.toml, core/consensus/aura/primitives/Cargo.toml, core/consensus/aura/primitives/src/lib.rs, core/consensus/aura/src/lib.rs, core/consensus/aura/src/slots.rs, core/consensus/common/Cargo.toml, core/consensus/common/src/block_import.rs, core/consensus/common/src/error.rs, core/consensus/common/src/evaluation.rs, core/consensus/common/src/import_queue.rs, core/consensus/common/src/lib.rs, core/consensus/rhd/Cargo.toml, core/consensus/rhd/src/error.rs, core/consensus/rhd/src/lib.rs
=> Migrate consensus (common, aura-primitives, aura, rhd) to 2018 edition

core/finality-grandpa/src/communication.rs, core/network/src/protocol.rs, core/network/src/sync.rs, core/network/src/test/mod.rs, core/network/src/test/sync.rs
=> Download unknown but announced forks

core/client/src/light/backend.rs, core/client/src/light/blockchain.rs
similar issue for full clients is fixed in #1616
=> Fixed aux modifications on light client

core/network-libp2p/src/service_task.rs
=> Print the local node address again

srml/support/Cargo.toml, srml/support/src/dispatch.rs, srml/support/src/double_map.rs, srml/support/src/event.rs, srml/support/src/hashable.rs, srml/support/src/inherent.rs, srml/support/src/lib.rs, srml/support/src/metadata.rs, srml/support/src/storage/generator.rs, srml/support/src/storage/mod.rs
=> Migrate srml-support to the 2018 edition

core/cli/src/params.rs, core/client/src/genesis.rs, core/client/src/light/call_executor.rs, core/client/src/light/fetcher.rs, core/executor/src/native_executor.rs, core/service/src/config.rs, core/service/src/lib.rs, core/service/test/src/lib.rs, core/test-client/src/lib.rs, node/executor/src/lib.rs
Closes #1406. See the issue for the discussion.
=> Rename and use --max-heap-pages parameter

srml/indices/Cargo.toml, srml/indices/src/address.rs, srml/indices/src/lib.rs, srml/indices/src/mock.rs, srml/indices/src/tests.rs
=> Indices maintenance

core/network-libp2p/src/custom_proto/behaviour.rs, core/network-libp2p/src/custom_proto/handler.rs
=> Backport #1723

core/network-libp2p/src/custom_proto/behaviour.rs, core/network-libp2p/src/custom_proto/handler.rs
=> Reduce the spam from network misbehaviours

core/finality-grandpa/src/import.rs, core/finality-grandpa/src/tests.rs
When re-importing a change block the authority change check would fail (since the change had already been imported), instead we early exit if the block is already in our local chain.
=> grandpa: fix reimport of change blocks

scripts/gitlab/check_runtime.sh
- If there are no changes to runtime code, exit ok; otherwise:
- If spec_version has changed, then:
- Exit ok if the runtime is rebuilt, fail otherwise.
- If impl_version has changed, then exit ok.
- If neither version has changed, fail.
=> Add more naunce to the runtime CI agent

core/network/src/protocol.rs, core/network/src/service.rs, core/network/src/sync.rs, core/network/src/test/mod.rs, core/network/src/test/sync.rs
=> Remove blocking operations in SyncOracle implementation

core/consensus/common/src/import_queue.rs, core/network/src/protocol.rs, core/network/src/service.rs, core/network/src/test/mod.rs
=> Use bounded channels for network -> sync -> import

core/finality-grandpa/src/lib.rs, core/finality-grandpa/src/tests.rs, core/network/src/consensus_gossip.rs, core/network/src/test/mod.rs
=> Backport of gossip improvements to v0.10

core/network-libp2p/src/lib.rs, core/network-libp2p/src/service_task.rs
Addresses the remaining comments in #1884
=> Address review comments in #1884

core/network-libp2p/src/service_task.rs
Right now it is possible to do `--bootnodes 192.168.1.12:30333` to treat the given IP:PORT combination as a bootstrap node. This is vulnerable to man-in-the-middle attacks, because you have no way to be sure that the node you reach is actually the bootstrap node that you expect.
This removes this feature. Only `--bootnodes /ip4/192.168.1.12/tcp/30333/p2p/Qm...` will now be accepted.
=> Remove dialing without a PeerId

core/service/src/chain_spec.rs, core/sr-primitives/src/lib.rs, node/cli/src/chain_spec.rs, node/executor/src/lib.rs, srml/staking/src/lib.rs, srml/staking/src/mock.rs, srml/support/procedural/src/storage/transformation.rs, srml/support/src/runtime.rs
Fixes: https://github.com/paritytech/substrate/issues/1967
=>  Make use of `assimilate_storage` for `GenesisConfig` 

core/consensus/common/src/block_import.rs, core/consensus/common/src/import_queue.rs, core/finality-grandpa/src/import.rs, core/finality-grandpa/src/lib.rs, core/finality-grandpa/src/tests.rs, core/network/src/test/block_import.rs
=> Import blocks with bad justification

core/finality-grandpa/src/tests.rs
test are not compiling at the moment
=> fix grandpa test

Cargo.lock, core/sr-io/Cargo.toml, core/sr-io/with_std.rs
=> Update environmental version

node-template/runtime/src/template.rs
Updated the link to the example module to be from the master branch.
=> Updated link for example module in template

Cargo.lock, README.adoc, core/cli/Cargo.toml, core/cli/src/lib.rs, core/cli/src/params.rs, core/keyring/Cargo.toml, core/keyring/src/ed25519.rs
So, `--alice` will give you a node with `--key //Alice --name Alice`.
=>  Expose keyring accounts in CLI

core/finality-grandpa/src/aux_schema.rs
=> Fix grandpa aux schema migration

core/network-libp2p/src/custom_proto/behaviour.rs, core/network-libp2p/src/custom_proto/handler.rs
There is currently a deadline for when the Substrate protocol handler is in "initialization mode" (which means waiting for the main thread to either enable or disable this handler). If the handler is initializing for more than 5 seconds, which means that the main thread has some locking contention issue, an error is printed.
However, right now the `CustomProtoHandler` is created whenever we start dialing a node. Once the connection is established, we start polling it. Consequently, the time it takes for dialing is subtracted from these 5 seconds.
This PR modifies that to start the timer only once the connection has been established.
This is done by adding an intermediary struct (`CustomProtoHandlerProto`) that exists before the connection is established, and that is later turned into an …
=> Start the handler init timer only when the connection is established

core/network-libp2p/src/custom_proto/handler.rs
The obvious change after #2041 is to keep the remote `PeerId` and show it in the logs.
This wasn't done before because we didn't have access to it.
=> Show the remote PeerId in the handler's logs

core/network/src/protocol.rs, core/network/src/sync.rs
=> Keep peer info up to date

.gitlab-ci.yml, scripts/kubernetes/Chart.yaml, scripts/kubernetes/templates/poddisruptionbudget.yaml, scripts/kubernetes/templates/secrets.yaml, scripts/kubernetes/templates/service.yaml, scripts/kubernetes/templates/serviceaccount.yaml, scripts/kubernetes/templates/statefulset.yaml, scripts/kubernetes/values.yaml
- update of helm chart adapting the needs for the testnet
- change ci job names to make them system independent
- align ci to polkadot pipelines
=> Ci update names and chart

core/peerset/src/lib.rs
Right now the dummy peerset manager doesn't differentiate incoming from outgoing connections. Instead of I incoming slots and O outgoing slots, it just uses I+O slots.
This is problematic, because once the peerset manager learns about more than I+O nodes, it will just fill all the slots with connection attempts, and any incoming connection will be refused due to lack of slots.
This PR fixes it by adding a difference again.
=> Properly distinguish in/out connections in the PSM

core/network-libp2p/src/custom_proto/behaviour.rs
If we notice that the ban has expired, we should directly connect instead of going through a phase where we put ourselves in "pending" mode.
=> Directly connect if notice that ban has expired

core/cli/src/lib.rs, core/cli/src/params.rs, core/service/src/config.rs, core/service/test/src/lib.rs, node/cli/src/service.rs
=> core: cli flag to disable grandpa

srml/balances/src/lib.rs, srml/support/src/traits.rs
I found some typo, so fixed them. :)
=> fixed some typo

srml/sudo/src/lib.rs
Initial draft of the Sudo documentation. Expecting feedback and edits before it gets merged in.
=> Add documentation to the Sudo module

core/consensus/aura/src/lib.rs
Eliminate an unnecessary clone.
=> Remove an unnecessary clone in aura

node/runtime/src/lib.rs, srml/staking/src/phragmen.rs, srml/staking/src/tests.rs
- Small patch for recent staking issues in test-net.
=> Fix Staking Accuracy issues.

core/consensus/aura/src/lib.rs, node-template/src/service.rs, node/cli/src/service.rs
#2176 but based on v1.0 branch
=> [v1.0] aura API defaults to rejecting old seals

node/runtime/src/lib.rs, srml/balances/src/lib.rs
=> ensure imbalances are properly accounted for

scripts/docker/Dockerfile
fix docker image for debian:stretch build (https://github.com/paritytech/substrate/pull/2122)
=> ci: fix dockerfile for debian build

node-template/Cargo.toml
I believe this improves https://github.com/paritytech/substrate-up/issues/18
=> update name and authors to placeholder text for node-template

node-template/runtime/Cargo.toml, node-template/runtime/wasm/Cargo.toml
Missed those two files
Closes https://github.com/paritytech/substrate-up/issues/18
=> update authers for rest of the node-template cargo.toml files

srml/support/src/dispatch.rs, srml/timestamp/src/lib.rs
Backport of: https://github.com/paritytech/substrate/pull/2236
=> Throw a compile error for `on_finalise` and `on_initialise`

core/cli/src/lib.rs
=> handle not found error in purge-chain

core/cli/src/lib.rs
Ref: https://github.com/paritytech/substrate/pull/2274
=> Backport cli purge fix

core/sr-io/without_std.rs, core/state-machine/src/ext.rs
fix for #2284  (on obvious change and also adding commited for choice of child).
=> Fix for miscalculation of storage root

node/runtime/src/lib.rs, srml/contract/src/account_db.rs
obviously we need some more test, but this should be done in another issue
=> Fix contract child usage

srml/aura/src/lib.rs, srml/balances/src/lib.rs, srml/consensus/src/lib.rs, srml/contract/src/lib.rs, srml/staking/src/lib.rs, srml/sudo/src/lib.rs, srml/system/src/lib.rs, srml/timestamp/src/lib.rs
Common opener and cleanup. Sudo example compiles.
Todo: Make all examples compile.
=> Make existing docs more consistent

core/network-libp2p/src/behaviour.rs, core/network-libp2p/src/custom_proto/behaviour.rs, core/network-libp2p/src/custom_proto/handler.rs
to make the crate more testable
=> substrate-network-libp2p uses tokio_timer::clock::Clock

node-template/runtime/Cargo.toml
Fixes: https://github.com/paritytech/substrate/issues/2305
=> Make correct feature selection in node-template Cargo.toml

Cargo.lock, core/cli/src/informant.rs, core/network-libp2p/Cargo.toml, core/network-libp2p/src/lib.rs, core/service/Cargo.toml, core/telemetry/Cargo.toml
=> Telemetry - change NetworkState from string to json

core/test-runtime/Cargo.toml
=> Fix test build error in std mode

core/network-libp2p/src/lib.rs, core/network/src/lib.rs
=> Add warnings about breaking changes in network

srml/support/procedural/src/lib.rs, srml/support/src/hashable.rs
=> decl_storage doc

srml/treasury/src/lib.rs
Draft writeup of Treasury module. 
Not ready for final review. 
Review courtesy @shawntabrizi
=> Documentation: Treasury module

Cargo.lock, core/primitives/src/crypto.rs, subkey/Cargo.toml, subkey/src/cli.yml, subkey/src/main.rs
* First effort
* Fix for encoding
* !fixed subkey xfer creation (still brittle because of double-hardcoded genesis_hash (#2221)
* CLI genesis hash
* Add test
* Slightly nicer text
* Fix Elm hash
* Update lock file
=> Subkey can construct and sign transfer txs (#2109)

node-template/scripts/build.sh, scripts/node-template-release/src/main.rs
Backport of: https://github.com/paritytech/substrate/pull/2375
=> Backport fix node template release script

Cargo.lock, srml/support/procedural/Cargo.toml, srml/support/procedural/src/storage/mod.rs, srml/support/procedural/src/storage/transformation.rs, srml/support/procedural/tools/src/lib.rs, srml/support/procedural/tools/src/syn_ext.rs
backport https://github.com/paritytech/substrate/pull/2383
=> backport remove procedural keyword

README.adoc
Adding much more details to installing on Windows as it is still the most common pain point to get started and set up.
=> More detailed instructions for Windows Setup

core/network/src/service.rs
Simplifies the network background thread logic by merging the two futures into one.
Shouldn't change any logic.
=> Simplify the network background thread future

.gitlab-ci.yml
Continuation of #2412 
cc @gabreal
=> Try run check-web-wasm for PRs

srml/support/src/event.rs, srml/support/src/runtime.rs
Combing through macros and found some spelling stuff.
=> Macro spell fixes

core/network-libp2p/src/custom_proto/handler.rs
It was initially written with multiple protocols in mind, but then support for multiple protocols has been removed.
=> Simplify the code of connection_keep_alive

core/finality-grandpa/src/communication/gossip.rs, core/network/src/consensus_gossip.rs
Closes #2396, closes #2335 , closes #2395
=> Fix grandpa issue for InvalidViewChanges

node/runtime/src/lib.rs, srml/contract/src/account_db.rs, srml/contract/src/exec.rs, srml/contract/src/tests.rs
=> Default rent allowance to max_value

README.adoc
=> Quick spell check to readme

node/runtime/src/lib.rs, srml/contract/src/rent.rs, srml/contract/src/tests.rs
hmm how do we forget to check this.
=> actually update deduct_block when paying rent

core/primitives/src/changes_trie.rs, node/runtime/src/lib.rs
Closes #2452 
Covered by existing test https://github.com/paritytech/substrate/blob/449d5e406f0dc9e2e77a0199a2d7079cdaf999ad/core/primitives/src/changes_trie.rs#L143-L148
=>  Use saturating_pow for max digest interval 

core/primitives/benches/benches.rs, core/primitives/src/ed25519.rs
=> Add some benchmarks for ed25519 in substrate_primitives

PULL_REQUEST_TEMPLATE.md
This PR add a simple PR template that mentions a few points that the PR creator might want to check / update in the PR before publishing. 
I believe that there is a large room for improvements, but let's start with this.
=> Add a simple PR template

srml/support/src/lib.rs
maybe we could want to make example compiling. But well I'm not sure if worth the cumbersome.
=> add brief doc to some macro

core/peerset/src/peersstate.rs
If we disconnect a reserved node we shouldn't decrease the number of occupied slots.
cc @gavofyork
=> Reserved peers don't occupy slots

srml/support/src/lib.rs, srml/support/src/traits.rs
Also fix an accidental hard-coded dependency in support.
=> Introduce the `Get` trait and type_parameter.

core/cli/src/informant.rs
=> Prevent divide by zero panic with checked_div

.gitlab-ci.yml, scripts/docker/Dockerfile
- Rebase the Dockerfile from master
- stretch-based
- Bump libssl version
- add test
=> dockerfile update

srml/treasury/src/lib.rs
Follow up to https://github.com/paritytech/substrate/pull/2548#discussion_r283722940 
Related: https://github.com/paritytech/substrate/issues/2579
Test to demonstrate the behavior of `on_dilution`. A fix to 2579 should also update this test.
=> Add quantization test for on_dilution

Cargo.lock
https://github.com/libp2p/rust-libp2p/pull/1127
=> Libp2p v0.7.1 backport

Cargo.lock
https://github.com/libp2p/rust-libp2p/pull/1127
=> Libp2p 0.7.1

.gitlab-ci.yml, scripts/docker/Dockerfile
- little optimization
- metadata
=> Dockerfile optimization

.gitlab-ci.yml, scripts/flamingfir-deploy.sh
Scripts to deploy a binary from the master branch to the flaming fir network via four manual deployments.
=> Flaming fir deployment scripts

node/runtime/src/lib.rs, srml/contract/src/lib.rs
I don't know if v1.0 status but, maybe cool to add it as well
=> backport increase block gas limit

Cargo.lock, core/cli/src/lib.rs, core/consensus/common/Cargo.toml, core/network-libp2p/Cargo.toml, core/network-libp2p/src/config.rs, core/network-libp2p/src/custom_proto/handler.rs, core/peerset/Cargo.toml
Updates from libp2p 0.7 to libp2p 0.8.
=> Update to libp2p 0.8

core/consensus/babe/src/lib.rs, core/finality-grandpa/src/lib.rs
Reverts paritytech/substrate#2627
=> Revert "Allow warnings"

node-template/runtime/wasm/build.sh
See: https://github.com/paritytech/substrate/pull/2643
=> Backport: Update build script to create a table for the runtime

node/runtime/src/lib.rs, srml/contract/src/lib.rs
https://github.com/paritytech/substrate/commit/fc836ada049f7e3bafca5414738bb14a027d1937
=> Backport: Make contract dispatchables public

core/peerset/src/lib.rs
Right now, we don't connect to nodes whose reputation is equal to `i32::min_value()`.
But since reputations regress towards 0 over time, this doesn't really make sense. As soon as the node is reported, its reputation increases and we connect to it again.
This PR, instead of using `i32::min_value()`, adds a threshold which is currently 82% of `i32::min_value()`. Nodes under that threshold don't get connected to, and also get refused when a connection is incoming.
I chose 82% because it currently takes 10 seconds for a node at `i32::min_value()` to go over the threshold again. In other words, a ban lasts 10 seconds.
=> Make peerset ban nodes under a reputation

.gitlab-ci.yml
- all docker jobs now show `rustup show` and `rustc --version`
- some prettiness
=> show rust versions

core/cli/src/lib.rs
=> Pass through custom authority key with --dev

core/network/src/on_demand.rs, core/network/src/protocol.rs
Will give more flexibility on the actual network message to send.
=> Split the send_request method in multiple requests

srml/support/procedural/src/storage/transformation.rs, srml/support/test/tests/final_keys.rs
backport https://github.com/paritytech/substrate/pull/2585
=> Backport correct serde bound for genesis config

node-template/runtime/src/lib.rs, srml/council/src/voting.rs, srml/democracy/src/lib.rs
=> Backport Language adjustment: Referendums -> Referenda #2545

.gitlab-ci.yml
Fixes: https://github.com/substrate-developer-hub/docs/issues/88
=> Generate docs for all workspace crates

README.adoc
Backport of https://github.com/paritytech/substrate/pull/new/joshy-backport-2754
=> Fix typo Substate -> Substrate 

Cargo.lock, core/network-libp2p/Cargo.toml, core/network-libp2p/src/transport.rs
=> Update to libp2p 0.9.1

.gitlab-ci.yml
https://github.com/paritytech/substrate/issues/2735
=> subkey build, cargo audit

.gitlab-ci.yml
=> fix linux-test-stable-int

core/basic-authorship/src/basic_authorship.rs, core/consensus/babe/primitives/Cargo.toml, core/consensus/babe/primitives/src/lib.rs, core/consensus/babe/src/lib.rs, core/finality-grandpa/src/authorities.rs, core/finality-grandpa/src/light_import.rs, core/finality-grandpa/src/tests.rs, core/network/Cargo.toml, core/network/src/test/mod.rs, core/test-runtime/wasm/Cargo.lock, node-template/runtime/src/lib.rs, node-template/runtime/wasm/Cargo.lock, node-template/src/chain_spec.rs, node/cli/src/service.rs, node/executor/src/lib.rs
=> Get tests to build in gav-new-sessions

.gitlab-ci.yml
checks https://github.com/paritytech/substrate/issues/2859
=> Cargo check benches

core/client/db/src/lib.rs, core/network/src/protocol/sync.rs
=> fix(compile warn): &mut Trait -> dyn &mut Trait

srml/support/src/metadata.rs
Fixes: https://github.com/paritytech/substrate/issues/2875
CC: @jacogr
=> Expose `srml-system` in metadata as well

core/network/src/lib.rs
I don't really know who to ask for a review.
=> Add documentation at the root of substrate-network

Cargo.lock, core/consensus/common/Cargo.toml, core/network/Cargo.toml, core/network/src/behaviour.rs, core/network/src/custom_proto/behaviour.rs, core/network/src/custom_proto/tests.rs, core/network/src/debug_info.rs, core/network/src/discovery.rs, core/network/src/protocol_behaviour.rs, core/peerset/Cargo.toml, core/telemetry/Cargo.toml, core/test-runtime/wasm/Cargo.lock, node-template/runtime/wasm/Cargo.lock, node/runtime/wasm/Cargo.lock
Updates libp2p to version 0.10.0.
=> Update to libp2p 0.10

core/rpc-servers/src/lib.rs
This enables `Host` header validation when listening on `localhost`. Validation is disabled in case we want to expose the node to the outside world.
As a consequence accessing `127.0.0.1:9933` would work, same as `localhost:9933`, but not `<yourlocalhostname>:9933`.
=> Enable hosts filtering.

core/service/src/lib.rs
Fixes: https://github.com/paritytech/substrate/issues/2991
=> Adds a `SpawnTaskHandle` to core service

scripts/gitlab/check_runtime.sh
Per discussion in the substrate riot channel.
=> Don't label PR's with gotissues.

srml/staking/src/tests.rs
related https://github.com/paritytech/substrate/pull/2995
=> Fix test of staking without equalize feature

node/runtime/src/lib.rs, srml/contracts/src/lib.rs, srml/contracts/src/wasm/prepare.rs
=> srml-contract: Validate that modules do not declare oversized tables.

srml/session/src/lib.rs
This is quite more idiomatic substrate :D
=> Implement `SelectInitialValidators` for `()`

core/service/src/chain_ops.rs
Error caused by importing a block from a file would cause the CLI to hang.
=> Fixed block import command error handling

core/network/src/discovery.rs
Everyone complains about these `Libp2p => Random Kademlia query has yielded empty results` warnings all the time.
There are two possible reasons for this warning to show up:
- There's a bug in Kademlia (which is what this warning is originally supposed to detect).
- We can't reach any node of the network, probably because we're offline.
Let's hide this warning in the second situation.
=> Hide the Kademlia warnings when offline

Cargo.lock, core/network/src/custom_proto/behaviour.rs, core/peerset/Cargo.toml, core/peerset/src/lib.rs, core/peerset/tests/fuzz.rs, core/service/src/lib.rs
cc #3103 
Not much to say. 1:1 translation.
=> Switch the peerset to new futures

.gitlab-ci.yml
Builds and publishes `Subkey`.
=> WIP: Subkey release.

node/runtime/src/lib.rs, srml/collective/src/lib.rs
Some structs were lacking default instance, this is now tested and fixed.
cc @JoshOrndorff
=> fix and test default instance for collective

core/offchain/src/api.rs
Implements timestamp API for off-chain workers.
=> Timestamp off-chain API

core/service/src/lib.rs
Log a warning if polling the network takes more than 50ms.
In practice, on my machine it takes on average 1-3ms and sometimes up to 6-8ms (and also sometimes only 2-3µs). I think that 50ms should be a reasonable limit to show a warning.
=> Add a warning if network is too slow

core/offchain/src/api.rs
Implements the `sleep_until` API for off-chain workers.
=> sleep_until off-chain API

.gitlab-ci.yml, README.adoc, core/consensus/babe/src/tests.rs, srml/system/benches/bench.rs
Fixes: https://github.com/paritytech/substrate/issues/3179
=> Bkchr check all benches

node/runtime/src/lib.rs, srml/generic-asset/src/lib.rs, srml/im-online/src/lib.rs, srml/session/src/lib.rs, srml/support/procedural/src/lib.rs, srml/support/procedural/src/storage/impls.rs, srml/support/procedural/src/storage/transformation.rs, srml/support/src/double_map.rs, srml/support/src/lib.rs, srml/support/src/storage/mod.rs, srml/support/src/storage/unhashed/generator.rs, srml/support/src/storage/unhashed/mod.rs, srml/support/test/tests/final_keys.rs, srml/support/test/tests/instance.rs
Should fix: https://github.com/paritytech/substrate/issues/3148
=> Switch `srml-session` keys to `decl_storage!`

core/cli/src/informant/display.rs
Follow-up of https://github.com/paritytech/substrate/pull/3194#discussion_r306940063
=> Really fix #2652 this time

core/executor/src/allocator.rs
=> Include padding in heap size calculation

.gitlab-ci.yml
- Fixes debug flags from https://github.com/paritytech/substrate/pull/3183#pullrequestreview-266947170
- introduces the template for publishing dockers
=> Fixed debug flags

core/test-runtime/wasm/Cargo.lock, node-template/runtime/wasm/Cargo.lock, node/runtime/wasm/Cargo.lock
Fix https://github.com/substrate-developer-hub/substrate-package/issues/9
=> Update v1.0 runtime dependency for node-template, node and test-runtime

node/runtime/src/lib.rs
Staking should be register to get events for note_author and uncle referenced
=> Staking need to get events

Cargo.lock, core/consensus/common/primitives/Cargo.toml, core/network/src/custom_proto/behaviour.rs, core/network/src/custom_proto/handler.rs, core/network/src/custom_proto/upgrade.rs
Relates to https://github.com/paritytech/substrate/pull/3214.
=> core/network: Fix bad import %s/runtime_primitives/sr_primitives/

core/client/src/lib.rs
Add some basic documentation to provide an overview of what the `Client` is.
=> Add some documentation for the client

core/consensus/slots/src/lib.rs
The loop that tries to recover after panics and errors in `on_slot` is not correct since it tries to call `poll` on `TryForEeach` multiple times which leads to a panic bc some `Select` inside futures is polled twice.
After some discussions with @tomaka it was decided to remove the catching logic at all.
=> Slots should not try to catch panics.

core/client/src/in_mem.rs, core/client/src/lib.rs
=> Mention that in_mem::Backend doesn't work

Cargo.lock, srml/support/procedural/src/storage/impls.rs, srml/support/src/lib.rs
Fixes: https://github.com/paritytech/substrate/issues/3318
=> Fix `linked_map` in `decl_storage!` for option values

core/cli/src/lib.rs, core/keystore/src/lib.rs, core/primitives/src/testing.rs, core/primitives/src/traits.rs, core/rpc/src/author/mod.rs, core/rpc/src/author/tests.rs
- Fix a bug in keystore
- Add tests to keystore and rpc author
- Use primitives::testing::KeyStore in rpc author tests
=> More tests and some cleanup

node/runtime/src/lib.rs, srml/metadata/src/lib.rs, srml/support/procedural/src/storage/transformation.rs, srml/support/src/dispatch.rs
Supersedes: https://github.com/paritytech/substrate/pull/3329
=> Make `DefaultByte` implement `Send + Sync`

core/sr-primitives/src/traits.rs
This trait works just like `Verify` except on `AppKey` types. I'd like for it all just to be `Verify`, but Rust's trait rules concerning upstream changes mean it can't happen. This is a simple
workaround needed for modules using the new `app_crypto` types to use `Verify` automatically based upon their inner crypto.
=> Introduce AppVerify

Cargo.lock, core/consensus/aura/Cargo.toml, core/consensus/aura/src/lib.rs, node-template/src/service.rs
Closes: https://github.com/paritytech/substrate/issues/3330
=> Switch AuRa to dynamic keystore lookup

Cargo.lock, core/executor/src/wasm_executor.rs, core/sr-io/with_std.rs, node/runtime/src/lib.rs
Closes https://github.com/paritytech/polkadot/issues/385
=> Do not call externalities without `Ext` being set

core/finality-grandpa/src/lib.rs
The `SharedVoterSetState` is a `Arc<Mutex<_>>` and as the name implies it's meant to be shared. When applying an authority change, instead of mutating the `SharedVoterSetState` we were recreating a new one for the voter. This broke the catch-up replies, as the network only had access to old voter set states which did not include the latest completed rounds.
=> grandpa: don't recreate SharedVoterSetState

node/runtime/src/lib.rs
=> pay out slashes to the treasury

core/finality-grandpa/src/communication/gossip.rs
GRANDPA allows a node that is in a lower round to issue a catch-up request for a given round. When we're close to a set change there is potentially a race where the peer sends us a catch up request before it observed that we had transitioned to a new set, in this case since this could have been an honest mistake we want to reduce the cost of this request. We were only checking that the request was for a different set id than ours, but we need to make sure that the request is for the previous set id in order for it to be an honest out of scope request.
=> grandpa: validate honest out of scope catch ups are for the previous set

scripts/node-template-release/src/main.rs
Fixes: https://github.com/paritytech/substrate/issues/3478
=> Make `node-template-release` create a workspace

CODEOWNERS
Continuation of https://github.com/paritytech/substrate/pull/3371
Some people agreed to participate in this experiment, namely:
- @andresilva
- @tomusdrw
- @Robbepop
- @thiolliere 
- @jimpo
- @kianenigma 
- @DemiMarie-parity 
Feel free to ask here or edit the file if you are down to be notified if some parts of the codebase are changed.
=> Codeowners, pt.2 

srml/staking/src/lib.rs
https://github.com/paritytech/substrate/issues/3521#issuecomment-528433354
=> Remove dead code in Staking

core/executor/src/lib.rs, core/executor/src/native_executor.rs, core/executor/src/wasm_executor.rs, core/executor/src/wasm_utils.rs, core/state-machine/src/lib.rs
The docs currently mention some really archaic stuff like wasm contracts. This PR updates the docs for the current state.
=> Update docs for the wasm executor crate

CONTRIBUTING.adoc, PULL_REQUEST_TEMPLATE.md
Subsection to remind everyone about updating polkadot PRs, too.
=> Add section regarding polkadot PRs.

node/runtime/Cargo.toml, node/runtime/src/lib.rs, srml/staking/src/inflation.rs, srml/staking/src/lib.rs, srml/staking/src/mock.rs, srml/staking/src/tests.rs
Subsumes #3590 and the older bits of #3584.
Fixes #3575
Also includes runtime version bump.
=> Fixes NPoS reward, along with tests, cleanups & docs corrections

core/finality-grandpa/src/communication/mod.rs, core/finality-grandpa/src/communication/periodic.rs
The GRANDPA networking layer includes a background worker that periodically rebroadcasts the last neighbor packet that was sent. Unfortunately we weren't using this worker and were instead sending neighbor packets directly through service (which meant they weren't periodically rebroadcast in case of a stall).
=> grandpa: use periodic neighbor packet sender

Cargo.lock, core/sr-primitives/Cargo.toml, core/sr-primitives/src/traits.rs, srml/authorship/Cargo.toml, srml/authorship/src/lib.rs, srml/finality-tracker/Cargo.toml, srml/finality-tracker/src/lib.rs, srml/session/Cargo.toml, srml/session/src/lib.rs, srml/support/Cargo.toml, srml/support/src/lib.rs, srml/support/src/traits.rs, srml/system/Cargo.toml, srml/system/src/lib.rs, srml/timestamp/Cargo.toml, srml/timestamp/src/lib.rs
Fixes: https://github.com/paritytech/substrate/issues/3152
=> Switch to new proc-macro crate for implementing traits for tuples

core/offchain/Cargo.toml, core/sr-primitives/src/testing.rs
just makes some testing easier + neede in https://github.com/gnunicorn/substrate-offchain-cb/pull/4
=> From<UintAuthority> for u64

node/runtime/src/lib.rs, srml/assets/src/lib.rs, srml/aura/src/lib.rs, srml/authority-discovery/src/lib.rs, srml/authorship/src/lib.rs, srml/babe/src/lib.rs, srml/balances/src/lib.rs, srml/collective/src/lib.rs, srml/contracts/src/lib.rs, srml/democracy/src/lib.rs, srml/elections-phragmen/src/lib.rs, srml/elections/src/lib.rs, srml/example/src/lib.rs, srml/finality-tracker/src/lib.rs, srml/grandpa/src/lib.rs, srml/im-online/src/lib.rs, srml/indices/src/lib.rs, srml/membership/src/lib.rs, srml/offences/src/lib.rs, srml/session/src/historical.rs, srml/session/src/lib.rs, srml/staking/src/lib.rs, srml/support/procedural/src/storage/transformation.rs, srml/support/test/tests/final_keys.rs, srml/system/src/lib.rs, srml/timestamp/src/lib.rs, srml/treasury/src/lib.rs
=> Change `decl_storage!` to import the storage traits automatically

core/network/src/protocol/sync.rs
Context: https://github.com/paritytech/substrate/pull/3663#issuecomment-534552488.
=> Remove `debug_assert!`ion.

srml/support/procedural/src/lib.rs, srml/support/src/storage/generator/mod.rs
and export `Linkage` which can very well used by someone writing an RPC client.
=> Document how to get head of linked map.

core/offchain/src/api.rs
=> Random seed API for offchain workers

core/executor/src/wasm_executor.rs, core/offchain/src/testing.rs
Fixes: https://github.com/paritytech/substrate/issues/3704
=> Make `TestOffchainExt` panic on unknown requests

core/sr-io/Cargo.toml
Hey, @brenzi, does it look ok? Feel free to add something
=> Comment the features used for SGX builds.

core/client/src/call_executor.rs, core/client/src/client.rs, core/client/src/light/call_executor.rs, core/client/src/runtime_api.rs, core/executor/src/native_executor.rs, core/primitives/src/traits.rs, core/sr-api-macros/src/decl_runtime_apis.rs, core/sr-api-macros/src/impl_runtime_apis.rs, core/sr-api-macros/tests/runtime_calls.rs, core/state-machine/src/lib.rs
This adds the SCALE error description to the error when the conversion
between native and runtime failed.
=> Give more information why conversion between native and runtime failed

node/runtime/src/lib.rs, srml/elections-phragmen/src/lib.rs, srml/elections/src/lib.rs, srml/scored-pool/src/lib.rs
fix a warning and use compact for balance type
=> Minor fixes

core/consensus/pow/src/lib.rs
```diff
-	/// Mine a seal that satisfy the given difficulty.
+	/// Mine a seal that satisfies the given difficulty.
```
=> Minor typo in PoW comment

core/test-runtime/src/lib.rs, node-template/runtime/src/lib.rs, node/runtime/src/lib.rs, srml/babe/src/lib.rs, srml/babe/src/mock.rs
=> decouple BABE from session

core/cli/src/lib.rs
I'm just trying to satisfy my OCD.
=> Make the purge-chain prompt a little nicer

README.adoc
The command line setup did not work for me. This adds instructions and images on how to do it through the UI.
=> Alternative sysvar setup for Windows

core/network/src/protocol/consensus_gossip.rs
`messages_for` should set sender when sending `TopicNotification` for kept messages (if available)
=> gossip: save sender for kept messages

core/consensus/babe/src/lib.rs, core/consensus/babe/src/tests.rs
Slot numbers are strictly increasing, this PR adds a verification for this invariant against the parent block when importing.
=> babe: verify slots are strictly increasing

node/cli/src/chain_spec.rs
We have two different chain specs staging and testnet which are rather similar. I've made slight changes to the testnet genesis so that we can reuse that code when defining staging chain spec (used in flaming fir and under `--chain staging`).
=> node: re-use testnet genesis spec for staging testnet

core/state-db/src/lib.rs
=> Error message when changing pruning mode

Cargo.lock, Cargo.toml, node/runtime/Cargo.toml, node/runtime/src/lib.rs, srml/nicks/Cargo.toml, srml/nicks/src/lib.rs
Simple "nicknames" module for attaching names to accounts.
=> runtime: Account nicknames

node/runtime/src/lib.rs, srml/nicks/src/lib.rs
=> runtime: Add ability to force a name change

Cargo.lock, core/transaction-pool/graph/Cargo.toml, core/transaction-pool/graph/benches/basics.rs, core/transaction-pool/graph/src/pool.rs
```
cargo bench -p substrate-transaction-graph
```
=> Basic extrinsic pool benchmarks

.gitlab-ci.yml
=> Fix TODO for the WASM CI build of rpc-servers

core/client/db/src/lib.rs, core/client/src/client.rs, core/consensus/common/src/block_import.rs, core/consensus/common/src/import_queue.rs, core/finality-grandpa/src/light_import.rs, core/finality-grandpa/src/tests.rs, core/network/src/protocol/sync.rs, core/network/src/test/block_import.rs, core/network/src/test/mod.rs, core/network/src/test/sync.rs, core/test-client/src/lib.rs
Reverts paritytech/substrate#3942
=> Revert "Header-only sync for old forks"

Cargo.lock, node/cli/Cargo.toml, node/runtime/Cargo.toml
This file was real mess, just changed order and upgrade some libraries
should not break anything :-)
=> clean node/cli/Cargo.toml

core/finality-grandpa/src/import.rs
Removes superfluous search for authority set change block at startup if it is already known.
=> Don't search for authority search block if delay is zero

Cargo.lock, core/client/db/Cargo.toml, core/client/db/src/storage_cache.rs
along with some extra test cases
=> Randomized tests on storage cache

paint/balances/src/lib.rs
=> Document that no balance can be strictly between 0 and EXISTENTIAL_DEPOSIT

client/service/src/status_sinks.rs
This makes the test less covering, but at least it will pass CI.
=> Fix the status-sinks tests, hopefully

client/finality-grandpa/src/environment.rs
Reverts paritytech/substrate#4150
Test failure.
=> Revert "grandpa: voting rules shouldn't restrict past round base"

client/transaction-pool/graph/src/pool.rs
A more detailed explanation on what consumers should do with the stream.
=> Better docs for TxPool::import_notification_stream

client/service/src/lib.rs
Previously, it didn't detect panics or silent termination.
=> Make spawn_essential_task more strict

Cargo.lock, primitives/state-machine/Cargo.toml, primitives/trie/Cargo.toml, primitives/trie/src/lib.rs, primitives/trie/src/node_codec.rs, test/utils/runtime/Cargo.toml
This PR just rollback #4144 until the reason for synching issue is fixed.
=> revert trie db to 0.15

Cargo.lock, bin/node-template/Cargo.toml, client/Cargo.toml, client/api/Cargo.toml, client/api/src/error.rs, client/authority-discovery/Cargo.toml, client/cli/Cargo.toml, client/cli/src/error.rs, client/consensus/aura/Cargo.toml, client/consensus/babe/Cargo.toml, client/consensus/pow/Cargo.toml, client/executor/Cargo.toml, client/executor/src/error.rs, client/grafana-data-source/Cargo.toml, client/keystore/Cargo.toml, client/network/Cargo.toml, client/rpc/api/Cargo.toml, client/rpc/api/src/author/error.rs, client/service/Cargo.toml, client/transaction-pool/Cargo.toml, client/transaction-pool/graph/Cargo.toml, client/transaction-pool/src/error.rs, primitives/consensus/common/Cargo.toml, primitives/consensus/common/src/error.rs, primitives/inherents/Cargo.toml, primitives/inherents/src/lib.rs, primitives/keyring/Cargo.toml, primitives/keyring/src/ed25519.rs, primitives/keyring/src/sr25519.rs
Update some dependencies:
- derive_more 0.15 -> 0.99
- strum 0.15 -> 0.16
- slog_derive 0.1 -> 0.2
=> Update some dependencies

client/grafana-data-source/src/lib.rs, client/grafana-data-source/test/src/main.rs, client/service/src/builder.rs, client/tracing/src/lib.rs
This separate traces sent to Grafana by module::function, previously was only by module.
=> Separate traces sent to grafana by module::function

frame/staking/src/lib.rs
=> fix ligature glitch in frame/staking/src/lib.rs

Cargo.lock, client/grafana-data-source/Cargo.toml, client/grafana-data-source/src/server.rs, client/service/src/lib.rs
Closes https://github.com/paritytech/substrate/issues/4233
=> Handle Grafana server bind errors gracefuly.

bin/node/runtime/src/lib.rs, frame/support/src/lib.rs, frame/support/src/storage/generator/double_map.rs, frame/support/src/storage/mod.rs, frame/support/test/tests/decl_storage.rs
superseed #3749
Closes #3741
done on top of #3749 done by @rockbmb 
* fix tests
* improve a bit some namings
=> Add `swap` and `decode_len` to `DoubleMap` finishing #3749

frame/elections-phragmen/src/lib.rs
=> Fix phragmen elections

client/finality-grandpa/src/communication/gossip.rs, client/finality-grandpa/src/communication/mod.rs, client/finality-grandpa/src/communication/tests.rs, client/network/src/legacy_proto/behaviour.rs, client/network/src/lib.rs, client/network/src/protocol.rs, client/network/src/protocol/consensus_gossip.rs, client/network/src/protocol/light_dispatch.rs, client/network/src/protocol/sync.rs, client/network/src/service.rs, client/network/src/test/mod.rs, client/peerset/src/lib.rs, client/peerset/tests/fuzz.rs, client/service/src/lib.rs
Added an identifier to each possible reputation change to improve diagnostics of reputation changes/disconnects.
=> Reputation changes require reason

.maintain/rename-crates-for-2.0.sh, Cargo.lock, bin/node-template/Cargo.toml, bin/node/cli/Cargo.toml, client/finality-grandpa/Cargo.toml, client/service/Cargo.toml, frame/grandpa/Cargo.toml, frame/grandpa/src/lib.rs, frame/grandpa/src/mock.rs, primitives/finality-grandpa/Cargo.toml
=> Typo granpda -> grandpa

client/authority-discovery/src/lib.rs
`interval_at_is_queuing_ticks` test shows to be [flaky](https://gitlab.parity.io/parity/substrate/-/jobs/322417). This commit
increases the time margins while also reducing the amount of necessary
time ticks.
In case the test is still flaky on our CI system after this patch, I think we
should remove it.
=> client/authority-discovery: Increase margins for interval test

Cargo.lock, client/api/Cargo.toml
=> remove unnecessary block-builder dependency

frame/identity/src/lib.rs
Was reviewing this pallet and came across a few typos.
=> Fix typos in identity pallet docs

frame/democracy/src/lib.rs
Right now, referendums can only begin if they end after the latest-ended existing referendum. This basically means that fast-tracking cannot work unless there is not an existing referendum happening.
This PR relaxes that constraint.
=> Allow referendums to begin out of order

.maintain/rename-crates-for-2.0.sh
=> Adding in-between variants of crate names to rename script

client/consensus/babe/src/lib.rs
=> docs: fix link to babe

frame/system/src/offchain.rs, primitives/runtime/src/traits.rs
I was reading this code for some other work and spotted a few docs typos.
=> Minor typos in traits docs

client/consensus/babe/src/lib.rs, frame/membership/src/lib.rs, frame/nicks/src/lib.rs, frame/scored-pool/src/lib.rs, frame/scored-pool/src/tests.rs, frame/session/src/lib.rs, frame/staking/src/lib.rs, frame/treasury/src/lib.rs
=> Migrate membership, nicks, scored-pool and session to decl_error

frame/treasury/src/lib.rs
=> Add ProposalRejected event to Treasury

frame/balances/src/lib.rs, frame/democracy/src/lib.rs, frame/generic-asset/src/lib.rs, frame/generic-asset/src/tests.rs, frame/identity/src/lib.rs, frame/im-online/src/lib.rs, frame/nicks/src/lib.rs, frame/scored-pool/src/tests.rs
=> Migrate generic-asset, identity and im-online to decl_error

frame/identity/src/lib.rs, primitives/runtime/src/traits.rs
=> Twitter field for IdentityInfo (in a back-compat way)

frame/authorship/src/lib.rs, frame/contracts/src/lib.rs, frame/elections-phragmen/src/lib.rs, frame/elections/src/lib.rs, frame/elections/src/tests.rs, frame/generic-asset/src/lib.rs
=> Migrate election-phragmen, election contracts and authorship to decl_error

primitives/application-crypto/src/traits.rs, primitives/runtime/src/traits.rs
=> Minor ligature fix

docs/CODEOWNERS
=> Remove jimpo from CODEOWNERS

frame/staking/src/tests.rs
Minor follow up to #4374 
CC @marcio-diaz
=> Add an extra test to check rebond is a FIFO

docs/CODEOWNERS
Fix some paths in CODEOWNERS that was broken after shuffling directories around.
=> Fix some entries in CODEOWNERS

frame/elections-phragmen/src/lib.rs
=> Fix tests in phragmen-election

client/db/src/light.rs
=> Avoid one timer in light strorage for Wasm

frame/support/test/tests/construct_runtime_ui/default_module_invalid_arg.rs, frame/support/test/tests/construct_runtime_ui/default_module_invalid_arg.stderr, frame/support/test/tests/construct_runtime_ui/invalid_module_entry.rs, frame/support/test/tests/construct_runtime_ui/invalid_module_entry.stderr
https://github.com/paritytech/substrate/pull/4520
=> Add test files I forgot to commit with #4520

Cargo.lock, client/finality-grandpa/Cargo.toml
Includes two fixes for finality:
- https://github.com/paritytech/finality-grandpa/pull/107
- https://github.com/paritytech/finality-grandpa/pull/105
=> grandpa: bump finality-grandpa crate to v0.10.3

Cargo.lock
=> Update soketto to v0.3.2

frame/system/src/lib.rs
Closes: https://github.com/paritytech/substrate/issues/4704
=> Deposit event on `frame-system::set_code`

.maintain/gitlab/check_runtime.sh
Changes in #3872 rendered the check_runtime check disfunctional (like #4722 and #4721).
This pr will fix it and also make the output of the check more readable.
=> ci: fix runtime version check

client/basic-authorship/src/basic_authorship.rs, client/cli/src/params.rs, client/transaction-pool/graph/src/validated_pool.rs
Also improve logging in authorship/txpool
=> Increase transaction pool default limits

Cargo.lock, client/authority-discovery/Cargo.toml
Should keep cargo-audit job happy finally
=> Update prost-build dependency

Cargo.lock, bin/node/cli/src/chain_spec.rs, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs, bin/node/testing/src/genesis.rs, frame/balances/src/lib.rs
Also,
- introduce vesting to node; and
- debug message for upgrades.
=> Don't attempt to upgrade balances module on chain start

Cargo.lock, primitives/arithmetic/fuzzer/Cargo.lock
This will hopefully reduce merge conflicts in the future.
=> Switch to the new lockfile format

frame/support/src/dispatch.rs, frame/support/src/traits.rs
Trait to get function name and pallet name for the extrinsic calls.
=> Added GetCallMetadata for extrinsic calls.

primitives/consensus/common/src/block_import.rs
Make sure when returning values in `take_intermediate`, the value does not get lost, but inserted back to the hashmap.
=> Avoid losing values in intermediate take

client/transaction-pool/graph/src/pool.rs
@marcio-diaz reported that it might be slow for his use cases
=> Join verifications in batch async/await verification 

bin/node/cli/src/chain_spec.rs
Fixes: https://github.com/paritytech/substrate/issues/4899
=> Fix chain-spec and make sure it does not breaks again

bin/node/runtime/src/lib.rs, frame/evm/src/lib.rs
Refactor some duplication in call/create/create2.
=> pallet-evm: refactor duplicate code in call/create/create2

primitives/transaction-pool/src/pool.rs
Extra docs and removal of serde rename as a follow up for #4740, also see #4438
=> Remove rename for finalized event and add some docs.

bin/node/testing/benches/import.rs
=> Update import benchmark parameters 

client/chain-spec/src/chain_spec.rs
Related https://github.com/paritytech/cumulus/issues/44
=> Make GenesisSource thread-safe

Cargo.lock, bin/utils/subkey/Cargo.toml, frame/support/Cargo.toml, primitives/core/Cargo.toml
=> Use a single version of once_cell

client/finality-grandpa/src/lib.rs, client/finality-grandpa/src/observer.rs, client/network/src/protocol/specialization.rs, utils/wasm-builder-runner/src/lib.rs
=> [In Progress] Remove deprecated api

bin/node/testing/benches/import.rs
This shows non-linearity per block size of wasm block execution for now:
`$ cargo bench -p node-testing wasm_size_import`
=> Wasm import benchmark per block size 

bin/node/testing/benches/import.rs
- remove wasm size benchmark for a while until figured how to skip setup
- reduce iterations
=> Speedup import benchmark

utils/wasm-builder/src/wasm_project.rs
Up to now `wasm-builder` iterated over all packages that were not part
of the wasm workspace and added the files to the `rerun-if-changed`
list. However, this included to many files and resulted in needless
re-compilations in `Cumulus` for example.
=> Make `wasm-builder` select dependencies more sensitive

Cargo.lock, client/service/Cargo.toml
=> Update sysinfo version to 0.11

Cargo.lock, client/cli/Cargo.toml, client/db/Cargo.toml, client/informant/Cargo.toml, client/service/Cargo.toml, client/state-db/Cargo.toml, client/transaction-pool/Cargo.toml, client/transaction-pool/graph/Cargo.toml, primitives/core/Cargo.toml, primitives/runtime/Cargo.toml, primitives/test-primitives/Cargo.toml, test-utils/runtime/Cargo.toml
=> Update parity-common dependencies

docs/CODEOWNERS
Those were my areas of contribution last weeks and will continue to be
=> Update CODEOWNERS: add myself to some areas

bin/node/cli/res/flaming-fir.json
Fork flaming fir after latest master upgrade.
=> Fork flaming fir

Cargo.lock, client/service/Cargo.toml
=> Update sysinfo to fix compilation on Windows

frame/contracts/src/exec.rs
=> Rename ExecutionContext::parent to caller

Cargo.lock, primitives/trie/Cargo.toml, test-utils/runtime/Cargo.toml
Part of https://github.com/paritytech/polkadot/issues/922.
=> deduplicate parity-util-mem

Cargo.lock
See https://github.com/paritytech/yamux/blob/develop/CHANGELOG.md#045 for details.
=> Update yamux to version 0.4.5

client/network/src/service.rs
Currently when we connect to a bootnode and it returns a different peer
id, than the one we provided, we disconnect silently. This pr changes
the behavior to printing an error when a bootnode returns a different
peer id than the provided one.
I know that api-wise this is shit (matching on a `String). I'm open to create a pr for `libp2p` that requires some extra trait for the boxed error to improve this pr.
=> Show an error when we connect to a bootnode with a different peer id

client/network/src/lib.rs
No code has been touched in the making of this PR.
I'm asking for a review from multiple people, but not everyone has to review.
I'm pretty sure that what I wrote is exact, but maybe not explained properly, and the review is about improving the phrasing and finding mistakes.
=> Improve sc-network's documentation for network protocols

client/consensus/pow/src/lib.rs, primitives/arithmetic/fuzzer/src/per_thing_rational.rs
=> Change the difficulty parameter of PowAlgorithm::difficulty function to Hash

primitives/arithmetic/src/per_things.rs
Partly addresses https://github.com/paritytech/substrate/issues/5462
To support `Compact` we need some changes in scale-codec before.
=> Check that `PerThing` valid on decode

Cargo.lock, bin/node/rpc-client/Cargo.toml, client/consensus/babe/rpc/Cargo.toml, client/rpc-api/Cargo.toml, frame/contracts/rpc/Cargo.toml, frame/transaction-payment/rpc/Cargo.toml, utils/frame/rpc/support/Cargo.toml, utils/frame/rpc/system/Cargo.toml
Does not seems to be used (or is it?)
=> Remove ws feature from json client

client/basic-authorship/src/basic_authorship.rs
This pr ensures that we don't panic because of a deadline that is
already reached in basic authorship. This is mainly useful for debug
builds, as release builds normally don't have debug assertions enabled.
Fixes: https://github.com/paritytech/substrate/issues/4949
=> Use saturating sub in basic authorship

.gitlab-ci.yml
Prepopulates `CARGO_HOME` cache
If there is no directory for this `$CI_COMMIT_REF_NAME/$CI_JOB_NAME`
create such directory and
copy recursively all the files from the newest dir which has `$CI_JOB_NAME`, if it exists.
=> prepopulate CARGO_HOME caches

docs/CODEOWNERS
Please add me to review manually from now on :)
=> Remove myself from txpool code owning.

bin/node/cli/Cargo.toml, bin/node/cli/src/cli.rs, bin/node/cli/src/command.rs
=> Hide benchmarking CLI behind the feature flag

Cargo.lock, client/db/Cargo.toml
Recursive git dependency is causing CI issues
=> Removed subdb dependency

frame/transaction-payment/src/lib.rs
Weight refund was not properly working when an adjustment factor != 0 is active. It always refunded the unadjusted weight fee when it should be refunding the adjusted one as this is the one that was deduced from the transactor.
This also adds a test that checks the refund under an adjustment factor of 0.5.
The new `compute_weight_fee` function that takes the adjustment into account is public because we will be needing it for the contracts module to implement `ext_gas_price` in the future where gas and weight are unified.
It also moves the public fee calculation functions to the `Module` where it can be easily used by other pallets. Using the `ChargeTransactionPayment` signed extension adds inconvenient bounds to the `Trait` when other modules try to use it.
=> Fix weight refund to use proper adjustment factor

Cargo.lock, bin/utils/subkey/Cargo.toml, client/authority-discovery/Cargo.toml, client/network-gossip/Cargo.toml, client/network/Cargo.toml, client/network/test/Cargo.toml, client/peerset/Cargo.toml, client/telemetry/Cargo.toml, primitives/consensus/common/Cargo.toml
Fix #5684
Probably also #5594, but let's confirm that first.
=> Force libp2p 0.18.1

docs/CODEOWNERS
The new github notification interface fits my workflow completely now.
=> Update codeowners: removing thiolliere.

Cargo.lock, bin/node/bench/Cargo.toml, bin/node/bench/src/core.rs, bin/node/bench/src/import.rs, bin/node/bench/src/main.rs, primitives/io/src/batch_verifier.rs
also some minor improvements along the way
=> Full block import benchmark

bin/node/cli/browser-demo/README.md
=> Fix error in browser demo readme

primitives/io/src/batch_verifier.rs
Should fix at least one of the issues reported in  https://github.com/paritytech/kusama-issues/issues/6
=> Fixed race in batch signature verification

client/cli/src/config.rs, client/cli/src/params/import_params.rs
=> Fix remaining issues with unsafe_pruning

client/consensus/slots/src/aux_schema.rs
The code in this method is still not entirely correct since it assumes that slots will always be visited sequentially (which isn't necessarily true in the presence of forks), will rewrite it in a follow-up PR.
=> babe: fix overflow in check_equivocation

primitives/arithmetic/src/fixed64.rs
Fixes: https://github.com/paritytech/substrate/issues/5837
=> We should panic on division by zero

bin/node/bench/src/import.rs, bin/node/bench/src/main.rs
`cargo run --release -p node-bench -- ::node::import::wasm::sr25519::empty`
=> Empty block import benchmark

bin/node/runtime/src/lib.rs, frame/elections-phragmen/Cargo.toml, frame/elections-phragmen/src/benchmarking.rs
This PR attempts to get phragmen benchmarks #5845  to a point I am happy to approve :)
=> Help finish phragmen benchmarks

client/service/src/lib.rs
This would help a bit for debugging when something fails.
=> Improve error message when essential task failed

Cargo.lock, client/executor/src/integration_tests/mod.rs, client/executor/wasmtime/Cargo.toml, client/executor/wasmtime/src/host.rs, client/executor/wasmtime/src/imports.rs, client/executor/wasmtime/src/instance_wrapper.rs, client/executor/wasmtime/src/instance_wrapper/globals_snapshot.rs, client/executor/wasmtime/src/runtime.rs
This reverts commit c4285c95ff862a6233abea2902d69aed84b818df.
=> Revert "Update wasmtime (#5822)"

client/network/src/behaviour.rs
Since Vec::remove(0) always does memcpy
=> Change to Vec to VecDeque in network behaviour 

bin/node/bench/src/import.rs, bin/node/bench/src/main.rs, bin/node/testing/src/bench.rs
This will allow to bench paritydb along with rocksdb
=> Add database type for import benchmarks

client/service/src/client/client.rs
Instead of informing the telemetry about each block that is finalized,
we only need to send the last finalized block. This removes log spam on
initial sync.
=> Only send last finalized block to telemetry

Cargo.lock, client/executor/src/integration_tests/mod.rs, client/executor/wasmtime/Cargo.toml
Brings in this commit: https://github.com/paritytech/wasmtime/commit/766b408fd078926b81b5ae7be3aa8f383d4cc5f5
Also fixed bogus test
=> Fix parallel code execution in wasmtime

bin/node/bench/src/core.rs
=> Increase precision of benchmarking results summary

frame/assets/src/lib.rs, frame/babe/src/lib.rs, frame/contracts/src/lib.rs, frame/democracy/src/lib.rs, frame/elections-phragmen/src/lib.rs, frame/elections/src/lib.rs, frame/generic-asset/src/lib.rs, frame/grandpa/src/lib.rs, frame/identity/src/lib.rs
to help with future security auditing.
=> Add notes about safe uses of twox

client/db/src/bench.rs, client/db/src/lib.rs, client/db/src/storage_cache.rs, client/service/src/client/light/backend.rs, primitives/state-machine/src/backend.rs, primitives/state-machine/src/proving_backend.rs, primitives/state-machine/src/trie_backend.rs
Related to #6108 
no cow version (if the reason for cow was the horrible rustc lifetime thing around full storage root).
About the bench, I think even if there is no visible change, I am happy not having the clone.
=> No cow version

primitives/runtime/src/offchain/storage_lock.rs
Addresses the last review comment in #6010 which was left after merging.
=> [insignificant] remove doc hidden on private item

client/network/src/service.rs, client/service/test/src/lib.rs
This is still https://github.com/paritytech/substrate/issues/6033 that wasn't actually fully fixed.
I'd strongly advocate for rewriting these tests at some point.
=> Fix service tests not calling update_chain

frame/atomic-swap/src/lib.rs
Docs re https://github.com/paritytech/substrate/pull/6349
=> Simple Docs for Atomic Swap Pallet

frame/collective/src/lib.rs
This PR updates the collective events docs to be consistent with changes made recently for weights.
=> fix pallet-collective events docs

bin/node/runtime/src/lib.rs, frame/membership/src/lib.rs
Closes #6041
A follow up could be remove members from pallet-collective. But I will leave it to keep this simple.
https://github.com/paritytech/substrate/blob/9169d2ecd5a6cc8682d4b18e75033e919f09bb33/frame/collective/src/lib.rs#L141
=> Implement Contains for pallet-membership

Cargo.lock, frame/support/Cargo.toml, frame/transaction-payment/Cargo.toml, primitives/state-machine/Cargo.toml
polkadot-companion: https://github.com/paritytech/polkadot/pull/1367
=> Fix ui tests in CI

bin/node-template/README.md, bin/node-template/node/Cargo.toml, bin/node-template/pallets/template/src/lib.rs
Better description in node/Cargo.toml
Example dispatchables should have non-zero weights
Changes to README to bring in line with current DevHub Node Template
=> Node template love

Cargo.lock, client/network/Cargo.toml, client/service/Cargo.toml
Some small things I've noticed while working on other changes.
=> Deduplicate some dependencies

Cargo.lock, bin/node/bench/src/main.rs, client/cli/Cargo.toml, client/cli/src/config.rs, client/cli/src/error.rs, client/cli/src/lib.rs, client/cli/src/params/shared_params.rs
This reverts commit 802a0d0b0ade796a3b2d4663212518315923fe8a.
polkadot-companion: https://github.com/paritytech/polkadot/pull/1389
=> Revert "Add log rotation (#6564)"

Cargo.lock, client/cli/src/lib.rs, client/executor/wasmtime/Cargo.toml
Switching back to released version.
=> Switching from git back to released versions for wasmtime, fix cargo-unleash

client/consensus/pow/src/lib.rs
Simply adds a log line to notify miners about found blocks
=> Add "✅ Successfully mined block" log message

frame/evm/src/lib.rs
fixes https://github.com/paritytech/substrate/issues/6816
=> pallet-evm: move gas price check to execute_evm

frame/staking/fuzzer/src/submit_solution.rs
Error strings changed in a previous PR.
=> Fix staking fuzzer.

client/db/src/bench.rs
wipe didn't reset child key tracker, this PR fix it and add a test.
=> Fix benchmark database wipe for child tries.

bin/node/cli/browser-demo/build.sh
=> Change browser-demo build.sh to use python 3 again

frame/sudo/README.md
Old link was broken, and I put a new one.
=> Fix broken link to democracy pallet.

primitives/runtime/src/transaction_validity.rs
=> Typo in error text

bin/node/runtime/src/lib.rs, bin/node/runtime/src/weights/mod.rs, bin/node/runtime/src/weights/pallet_indices.rs, frame/indices/src/benchmarking.rs, frame/indices/src/default_weights.rs, frame/indices/src/lib.rs
This PR introduces the auto-generated WeightInfo struct to the Indices pallet and updates the extrinsics to depend on this weight.
=> WeightInfo for Pallet Indices

frame/scheduler/src/benchmarking.rs
link the todo to the corresponding issue: https://github.com/paritytech/substrate/issues/7141
=> Link todo to issue

primitives/core/src/sr25519.rs
=> Fix warning in full-crypto build

primitives/consensus/common/src/import_queue.rs, primitives/consensus/common/src/import_queue/basic_queue.rs, primitives/consensus/common/src/metrics.rs
Adds more metrics to the import queue in order to get more details about today's incident.
=> Add more metrics to the import queue

bin/node/cli/src/browser.rs, client/cli/src/runner.rs, client/network/src/service.rs
Some insubstantial clean up of CLI output performed by Gav on rococo-branch
=> Tidy some CLI stuff.

primitives/core/src/crypto.rs, ss58-registry.json
Hello,
This PR adds a new ss58 address 19 for GeekCash network.
Thank you!
=> GeekCash reserve SS58 address id 19

.maintain/frame-weight-template.hbs, frame/democracy/src/weights.rs, frame/system/src/weights.rs, utils/frame/benchmarking-cli/src/template.hbs
As far as I see this is working
=> Fix benchmarks template whitespaces

frame/support/src/error.rs, frame/support/test/tests/instance.rs
Follow up to #7324 by @bkchr .
=> Allow multiple bounds to be specified at decl_error!

client/cli/src/error.rs
Minor hickup of #7446 
polkadot companion: https://github.com/paritytech/polkadot/pull/1871
=> add Sync + Send + 'static to Box<dyn Error> bound

docs/CODEOWNERS
@pepyakin moved on to other tasks.
=> Transfer code ownership of /frame/contracts/

.gitlab-ci.yml
Updating tag name from parity-chaos to parity-simnet.
Please merge after all checks passed.
=> Update CI chaos tag to simnet

frame/name-service/src/tests.rs
Unit tests for `pallet-name-service`
cc @shawntabrizi
=> Pallet-name-service tests

.github/allowed-actions.js, .github/workflows/md-link-check.yml, .github/workflows/mlc_config.json
- pinned a [new](https://github.com/gaurav-nelson/github-action-markdown-link-check/pull/86) version of action
- fixed an issue with `%20` URLencoded in action's dependency
- reverted ignoring the `%20` pattern
=> Update md link checker

primitives/arithmetic/Cargo.toml
optimize cargo sp-debug-derive path
=> optimize arithmetic cargo path

primitives/api/Cargo.toml, primitives/api/test/Cargo.toml, primitives/application-crypto/Cargo.toml, primitives/consensus/common/Cargo.toml, primitives/io/Cargo.toml, primitives/npos-elections/Cargo.toml, primitives/runtime-interface/test/Cargo.toml, primitives/runtime/Cargo.toml
Now delete all  primitives in Cargo.toml
=> delete primitives in Cargo in primitives

client/basic-authorship/Cargo.toml, client/consensus/aura/Cargo.toml, client/finality-grandpa/Cargo.toml, client/network/test/Cargo.toml, client/offchain/Cargo.toml, client/rpc/Cargo.toml
=> delete client in Cargo in client

frame/elections-phragmen/src/lib.rs
An insubstantial check that was overlooked.
=> prevent too many genesis council members

frame/contracts/src/rent.rs, frame/contracts/src/tests.rs
With the introduction of storage transactions it is no longer necessary to put the delta keys pack to the restorer contract on failure. This is because the error will trigger the current's contract storage transaction to rollback anyways. Please note that restoration can only be triggered from within a contract so we know that there is a transaction ongoing.
This also extends the existing restorations tests to also explicitly check whether the delta keys is still there after a failed restoration
=> contracts: No longer put delta keys back after a failed restoration

docs/Structure.adoc
now Cargo in client path
name = "sc-*"
=> update substrate to sc in docs

frame/support/src/storage/generator/double_map.rs, frame/support/src/storage/generator/map.rs, frame/support/src/storage/mod.rs, frame/support/src/storage/types/double_map.rs, frame/support/src/storage/types/map.rs
Fixes: https://github.com/paritytech/substrate/issues/7770
=> Adds `try_get` for `StorageMap` and `StorageDoubleMap`

frame/support/src/weights.rs
update weight_are_correct test
change x2 to  x^2
=> Feat support weight test

primitives/keystore/src/lib.rs, primitives/keystore/src/vrf.rs
=> Feat sp keystore

bin/node/runtime/src/lib.rs, frame/contracts/src/benchmarking/mod.rs, frame/contracts/src/lib.rs, frame/contracts/src/rent.rs, frame/contracts/src/storage.rs, frame/contracts/src/tests.rs
Fixes #7529
Check out the linked issue for a description.
=> contracts: Add configurable per-storage item cost

client/cli/src/lib.rs
With the switch to tracing we did not set the `max_log_level` anymore.
This resulted in a performance degradation as logging did not early
exited and thus, `trace` logs were at least resolved every time.
This pr fixes it by ensuring that we set the correct max log level.
Fixes: https://github.com/paritytech/substrate/issues/7800
=> Fix max log level

primitives/core/src/crypto.rs, ss58-registry.json
Adding a key prefix(29) for Dhiway CORD Network.
=> Add ss58 version prefix for CORD (from Dhiway)

.maintain/monitoring/grafana-dashboards/substrate-networking.json, .maintain/monitoring/grafana-dashboards/substrate-service-tasks.json
Updates the dashboards in the repository to the latest versions that Parity uses.
=> Update the Grafana dashboards

frame/support/procedural/src/construct_runtime/mod.rs, frame/support/procedural/src/construct_runtime/parse.rs, frame/support/procedural/src/pallet/expand/call.rs, frame/support/procedural/src/pallet/parse/call.rs, frame/support/procedural/src/pallet/parse/config.rs, frame/support/procedural/src/pallet/parse/event.rs, frame/support/procedural/src/pallet/parse/extra_constants.rs, frame/support/procedural/src/pallet/parse/helper.rs, frame/support/procedural/src/pallet/parse/mod.rs, frame/support/procedural/src/pallet/parse/origin.rs, frame/support/procedural/src/pallet/parse/storage.rs, frame/support/procedural/src/pallet/parse/type_value.rs, frame/support/procedural/src/pallet_version.rs, frame/support/procedural/src/storage/print_pallet_upgrade.rs
optimize frame suppert procedural
fix clippy warning
=> Feat suppert procedural

ss58-registry.json
Update ss58 registry for Robonomics: displayName, symbols, decimals, website
=> Update ss58 registry for Robonomics

client/network/src/transport.rs
I didn't realize that we forgot to do that!
This should remove some artificial delays.
=> Disable Nagle algorithm

docs/CONTRIBUTING.adoc
- Fixing Link
- Clarify that no-force-push applies to Pull Requests, too.
=> Minor contributor docs update

frame/support/src/lib.rs
Found this very minor typo when browsing the docs.
=> Very minor typo in the docs

bin/node/cli/src/command.rs
=> Refuse to start substrate without providing an explicit chain

primitives/consensus/common/src/import_queue/basic_queue.rs
This is some smaller change to rewrite the async code in `BasicQueue`. I
require this for some other pr I'm working on ;)
=> Rewrite the async code in `BasicQueue`

bin/node-template/node/src/service.rs, bin/node/bench/src/txpool.rs, bin/node/cli/src/service.rs, client/basic-authorship/src/basic_authorship.rs, client/basic-authorship/src/lib.rs, client/consensus/manual-seal/src/lib.rs, client/offchain/src/lib.rs, client/rpc-api/src/author/error.rs, client/rpc/src/author/tests.rs, client/service/src/lib.rs, client/transaction-pool/graph/benches/basics.rs, client/transaction-pool/graph/src/lib.rs, client/transaction-pool/graph/src/pool.rs, client/transaction-pool/graph/src/validated_pool.rs, client/transaction-pool/src/lib.rs, client/transaction-pool/src/revalidation.rs, client/transaction-pool/src/testing/pool.rs, primitives/transaction-pool/src/error.rs, utils/frame/rpc/system/src/lib.rs
Fixes #8045.
polkadot companion: https://github.com/paritytech/polkadot/pull/2385
=> transaction-pool: drop unpropagable txs if local node cant author blocks

Cargo.lock, client/chain-spec/Cargo.toml, frame/authorship/Cargo.toml, frame/session/Cargo.toml, frame/session/src/lib.rs, frame/support/Cargo.toml, frame/system/Cargo.toml, frame/timestamp/Cargo.toml, frame/treasury/Cargo.toml, primitives/runtime-interface/Cargo.toml, primitives/runtime/Cargo.toml, primitives/timestamp/Cargo.toml, primitives/wasm-interface/Cargo.toml
Switches to the latest version everywhere now, as I fixed the problems
in the crate ;)
=> Switch to latest `impl-trait-for-tuples`

primitives/core/src/crypto.rs, ss58-registry.json
This is a trivial PR for reserve 66 SS58 address for Crust Network.
=> Add Crust Network SS58 Address

Cargo.lock, bin/node/browser-testing/Cargo.toml
=> Unbreak browser test CI

bin/node/cli/src/service.rs, client/authority-discovery/src/worker.rs, client/authority-discovery/src/worker/tests.rs, client/consensus/aura/src/lib.rs, client/consensus/babe/src/authorship.rs, client/consensus/babe/src/lib.rs, client/keystore/src/lib.rs, client/keystore/src/local.rs, primitives/finality-grandpa/src/lib.rs, primitives/io/src/lib.rs, primitives/keystore/src/lib.rs, primitives/keystore/src/testing.rs
polkadot companion: https://github.com/paritytech/polkadot/pull/2492
=> Make keystore return `None` when a key doesn't exist

primitives/core/src/crypto.rs
This PR make Regex in Ss58Codec and secret phrase parser static.
Related #8117
Please review @arkpar
=> Make Regex in ss58codec and secret phrase crypto static (#8117)

client/network/src/transactions.rs
Want to debug https://github.com/paritytech/substrate/issues/8171
=> Add some debug_asserts for #8171

Cargo.lock, utils/frame/remote-externalities/Cargo.toml, utils/frame/remote-externalities/src/lib.rs
=> update jsonrpsee to remove `allow(dead_code)`

client/consensus/babe/src/authorship.rs
=> Simplify client/consensus/babe/src/authorship.rs a bit

frame/collective/README.md, frame/contracts/src/lib.rs
=> doc(frame): [nitpicks]

frame/aura/src/lib.rs, frame/contracts/src/lib.rs, frame/democracy/src/lib.rs, frame/elections-phragmen/src/lib.rs, frame/identity/src/lib.rs, frame/im-online/src/lib.rs, frame/multisig/src/lib.rs, frame/nicks/src/lib.rs, frame/proxy/src/lib.rs, frame/randomness-collective-flip/src/lib.rs, frame/recovery/src/lib.rs, frame/scheduler/src/lib.rs, frame/scored-pool/src/lib.rs, frame/session/src/lib.rs, frame/society/src/lib.rs, frame/staking/src/lib.rs, frame/sudo/src/lib.rs, frame/timestamp/src/lib.rs, frame/treasury/src/lib.rs, frame/utility/src/lib.rs, frame/vesting/src/lib.rs
Fix https://github.com/paritytech/substrate/issues/8426
=> Improve doc

bin/node/runtime/src/lib.rs, frame/society/src/lib.rs, frame/society/src/mock.rs
Polkadot Companion: https://github.com/paritytech/polkadot/pull/2686
=> Make candidate intake in society configurable

client/network/src/service.rs
=> Fix &mut self -> &self in add_known_address

frame/support/test/tests/construct_runtime_ui/missing_system_module.stderr, frame/support/test/tests/derive_no_bound_ui/eq.stderr, frame/support/test/tests/pallet_ui/hooks_invalid_item.stderr
Requires: https://github.com/paritytech/scripts/pull/281
=> Prepare UI tests for Rust 1.51 & new CI image

.gitlab-ci.yml
This PR resolves paritytech/ci_cd#103 with following changes:
* adds relevant `cargo-check-try-runtime` job
=> Add `check --features try-runtime` CI job

.github/workflows/monthly-tag.yml, .maintain/gitlab/generate_changelog.sh
GITHUB_TOKEN needs to be explicitly referenced in env... it's been a while
=> Fix monthly tags #2

frame/balances/src/benchmarking.rs, frame/balances/src/tests.rs, frame/balances/src/tests_local.rs, frame/balances/src/tests_reentrancy.rs, frame/bounties/src/tests.rs, frame/contracts/src/wasm/mod.rs, frame/election-provider-multi-phase/src/benchmarking.rs, frame/election-provider-multi-phase/src/lib.rs, frame/executive/src/lib.rs, frame/recovery/src/lib.rs, frame/society/src/lib.rs, frame/staking/src/tests.rs, frame/tips/src/benchmarking.rs, frame/treasury/src/lib.rs
=> Add more asserts and debug_asserts

frame/support/procedural/src/default_no_bound.rs, frame/support/procedural/src/lib.rs, frame/support/src/lib.rs, frame/support/test/tests/derive_no_bound.rs, frame/support/test/tests/derive_no_bound_ui/default.rs, frame/support/test/tests/derive_no_bound_ui/default.stderr
Will help a bit for cases like as in: https://github.com/paritytech/substrate/pull/8197/files#
=> Add DefaultNoBound

frame/democracy/src/tests.rs, frame/elections-phragmen/src/lib.rs, frame/membership/src/lib.rs, frame/support/src/lib.rs, frame/support/src/traits.rs, frame/support/src/traits/members.rs, frame/system/src/lib.rs, frame/tips/src/lib.rs, frame/tips/src/tests.rs
Polkadot companion: https://github.com/paritytech/polkadot/pull/2873
=> Purify `Contains`, add `IsInVec`, `All` and `SortedMembers`

shell.nix
Update rust nightly and remove cmake dependency.
=> build: update shell.nix

client/authority-discovery/src/worker.rs
Fix https://github.com/paritytech/substrate/issues/8617
This PR moves the check for duplicates (introduced in https://github.com/paritytech/substrate/pull/8575) before the metrics counting the number of publications are updated.
=> Increase metric only if actually publishing

frame/support/src/lib.rs, frame/support/src/storage/bounded_vec.rs, primitives/externalities/src/lib.rs
fix some doc link, and make a dyn usage explicit
=> Fix doc and dyn usage

frame/staking/src/slashing.rs
=> Update dead link in comment

frame/support/test/tests/pallet.rs
checks that store trait is expanded correctly
=> add test for pallet store trait

primitives/arithmetic/src/biguint.rs
This PR derives Encode and Decode for BigUint.
=> derive Encode and Decode for BigUint

frame/collective/src/lib.rs
closes https://github.com/paritytech/substrate/issues/8757
=> Fix Spelling in Colletive

Cargo.lock, client/rpc-api/src/system/error.rs, client/rpc/Cargo.toml, client/rpc/src/system/mod.rs, client/service/src/builder.rs
=> [rpc]: implement system API

client/network/src/protocol/sync.rs
This PR fixes an issue with announced blocks being accumulated in `fork_targets` while doing a full sync. Each entry in `fork_target` is periodically checked with an expensive DB query, which slows down the full sync over time.  
There are two changes:
1. We don't add fork targets until full sync is complete, as they won't be downloaded anyway.
2. When peer disconnects we make sure to cleanup fork targets that are not advertised by other peer. 
This ensures that  `fork_targets` won't be building up over time and also prevents an attack that floods with invalid targets.
=> Maintain fork_targets

client/rpc/src/chain/mod.rs, client/rpc/src/state/mod.rs, client/service/src/builder.rs
=> [rpc] regard when param.one() failed as no params. 

client/network/src/service.rs
There might be a bug here. This PR adds some more debug assertions in order to try catch it.
=> Add more debug_assert to networking

client/network/src/protocol/notifications/behaviour.rs
I'm debugging some parachain issue, and this little change would have been useful :sweat_smile:
=> Small improvement to network log line

frame/support/src/traits/tokens/misc.rs
Fixes [#167](https://github.com/paritytech/subport/issues/167)
=> Add Debug to token traits `AssetId` and `Balance`

primitives/core/src/lib.rs, primitives/keystore/src/lib.rs
=> Fix doc for CryptoStore::ecdsa_sign_prehashed()

primitives/state-machine/src/testing.rs
Implements `ExternalitiesExt` trait For `TestExternalities` contained in state-machine primitive. So, that we can use simplified api to register, deregister or reference an extension in tests.
=> Add ExternalitiesExt for TestExternalities

.maintain/node-template-release.sh, utils/frame/try-runtime/cli/Cargo.toml
- Fix an issue with `cargo_unleash`, but does not fix it completely.
- Fix `cargo build` job which was failing on master
=> Fix build job

frame/transaction-storage/src/mock.rs
This fixes test breakage introduced in #8624
=> Fixed build for some tests

Cargo.lock, client/service/Cargo.toml, client/service/src/builder.rs, client/service/src/lib.rs
To make it easier to add the `HttpServer` in the future
=> jsonrpsee use facade crate

frame/balances/src/tests.rs, frame/support/src/traits/tokens/currency/reservable.rs
fix unreserve_all_named and add some tests
=> fix unreserve_all_named

frame/support/procedural/src/pallet/expand/event.rs
Solves #9052 
request review from @thiolliere
=> Make pallet::event respect clippy

frame/authorship/src/lib.rs
As reviewing the pallet yesterday, I have found some nitpicks that I
fixed.
=> pallet-authorship: Fixing some nitpicks

frame/staking/src/lib.rs
=> fix ordering of `get_npos_voters` weight arguments

Cargo.lock, utils/frame/remote-externalities/Cargo.toml
=> fix build for jsonrpsee http client

Cargo.lock, bin/node/cli/src/service.rs, client/rpc-api/src/chain/error.rs, client/rpc-api/src/state/error.rs, client/rpc/Cargo.toml, client/rpc/src/chain/chain_full.rs, client/rpc/src/chain/chain_light.rs, client/rpc/src/chain/helpers.rs, client/rpc/src/chain/mod.rs, client/rpc/src/state/mod.rs, client/rpc/src/state/state_full.rs, client/rpc/src/state/state_light.rs, client/service/src/builder.rs, client/service/src/lib.rs, test-utils/test-runner/src/node.rs
=> [rpc]: port light client subscriptions

Cargo.lock, client/service/src/lib.rs
=> feat: add http server

client/rpc/src/chain/mod.rs, client/rpc/src/state/mod.rs
=> add aliases to match the old RPC API

frame/uniques/src/lib.rs
=> Fixed typo in comment

primitives/runtime/src/random_number_generator.rs
Fix for #7444 and a note to prefer `rand_chacha` crate.
=> Fix to support u32::MAX

client/rpc/src/system/mod.rs
Fix rpc names for the System RPCs 
Add doc strings back 
Add missing system_reservedPeers RPC
=> Fix rpc names for the System RPCs

Cargo.lock, bin/node/cli/Cargo.toml, bin/node/cli/src/service.rs, bin/node/rpc/Cargo.toml, bin/node/rpc/src/lib.rs, frame/contracts/rpc/Cargo.toml, frame/contracts/rpc/src/lib.rs
=> Add contracts RPC

bin/node/cli/src/browser.rs, bin/node/cli/src/chain_spec.rs, bin/node/cli/src/service.rs, client/service/src/builder.rs, client/service/src/lib.rs, test-utils/client/src/lib.rs, test-utils/test-runner/src/node.rs, utils/browser/src/lib.rs
=> Remove RpcHandlers and associated machinery

frame/authority-discovery/src/lib.rs
=> Authority_discovery: expose assimilate_storage with GenesisBuild

.github/stale.yml
Let's activate [the stale bot](https://github.com/paritytech/parity-processbot/issues/216#issuecomment-870841449)!
[ci skip]
=> [ci] Activate stale bot

frame/election-provider-multi-phase/src/lib.rs
=> make submit_unsigned into DispatchClass::Operational

client/rpc/src/state/mod.rs
Implement missing state RPCs.
Closes https://github.com/paritytech/jsonrpsee/issues/411
=> impl state_getChildReadProof and childstate_getKeysPaged

Cargo.lock, utils/frame/remote-externalities/Cargo.toml, utils/frame/remote-externalities/src/lib.rs, utils/frame/remote-externalities/src/rpc_api.rs
=> Upgrade remote-externalities to use jsonrpsee v0.3

client/executor/common/src/runtime_blob/globals_snapshot.rs, client/executor/wasmtime/src/runtime.rs, client/network/src/config.rs, client/network/src/light_client_requests/handler.rs, client/network/src/light_client_requests/sender.rs, frame/contracts/rpc/runtime-api/src/lib.rs, frame/election-provider-multi-phase/src/lib.rs, frame/elections-phragmen/src/lib.rs, frame/elections/src/lib.rs, frame/scheduler/src/lib.rs, frame/session/src/lib.rs, frame/staking/src/lib.rs, test-utils/test-runner/src/client.rs
Fix some invalid link in doc, there is still some though.
=> Fix invalid link in doc

frame/treasury/Cargo.toml, frame/treasury/src/lib.rs
=> Generate storage info for treasury pallet

frame/assets/src/lib.rs, frame/atomic-swap/src/lib.rs, frame/authorship/src/lib.rs, frame/balances/src/lib.rs, frame/democracy/src/lib.rs, frame/election-provider-multi-phase/src/lib.rs, frame/gilt/src/lib.rs, frame/im-online/src/lib.rs, frame/lottery/src/lib.rs, frame/scheduler/src/lib.rs, frame/scored-pool/src/lib.rs, frame/treasury/src/lib.rs, frame/uniques/src/lib.rs
=> Add missing #[pallet::constant] annotations to pallets

.gitlab-ci.yml
Docs publishing was broken for quite a while, this fixes it.
If everything works well, I'll remove the `allow_failure` in the next PR.
=> CI: fix docs pub

frame/executive/src/lib.rs
When the `Executive` was used through the `ExecuteBlock` trait, the
custom on runtime upgrade wasn't called. This happened because we forgot
to forward the type and it instead used default type `()` that doesn't
do anything. This pr fixes it by forwarding the type and also adds a
regression test.
=> Fix custom on runtime upgrade not being called

primitives/arithmetic/src/traits.rs
so we can use checked_rem on BlockNumber and other types
=> add CheckedRem

frame/proxy/src/lib.rs
=> Simplify returnvalue creation

bin/node-template/node/src/command.rs, bin/node/executor/benches/bench.rs, bin/node/executor/tests/common.rs, bin/node/runtime/src/lib.rs, client/cli/src/commands/run_cmd.rs, client/consensus/aura/src/lib.rs, client/consensus/babe/src/lib.rs, client/db/src/changes_tries_storage.rs, client/db/src/light.rs, client/executor/runtime-test/src/lib.rs, client/finality-grandpa/src/lib.rs, client/network/src/discovery.rs, client/network/src/request_responses.rs, client/service/src/client/client.rs, frame/staking/reward-curve/src/lib.rs, primitives/npos-elections/src/balancing.rs, primitives/runtime-interface/test-wasm-deprecated/src/lib.rs, test-utils/runtime/src/lib.rs
Only whitespace changes.
Flicked on format_strings in the rustfmt config and took the reformats that seemed helpful.
(auto format_strings stays off)
=> post rustfmt whitespace fixup

client/cli/src/params/network_params.rs
=> More readable CLI help for --sync option

frame/support/src/traits/tokens/nonfungibles.rs, frame/uniques/src/functions.rs, frame/uniques/src/impl_nonfungibles.rs, frame/uniques/src/lib.rs
Closes #9419
Please let me know if this has any testing, benchmarking, or documentation implications that I missed.
=> Add nonfungibles::Create Trait & Implement for Uniques

primitives/authorship/src/lib.rs, primitives/npos-elections/src/assignments.rs, utils/prometheus/src/lib.rs
Less warnings means less noise.
=> Removing wasm unused import warnings

Cargo.lock, bin/node/cli/Cargo.toml, bin/node/cli/src/service.rs, client/network/src/block_request_handler.rs, frame/transaction-storage/README.md, primitives/transaction-storage-proof/src/lib.rs
* Enables storage chain inherent for the substrate node. This is compatible with existing chains.
* Storage chain deployment guide
* Additional fixes
=> Storage chain fixes + guide

Cargo.lock, Cargo.toml, client/offchain/Cargo.toml, client/offchain/src/api/http.rs, test-utils/Cargo.toml, utils/prometheus/Cargo.toml, utils/prometheus/src/lib.rs, utils/prometheus/src/networking.rs
Fixes: https://github.com/paritytech/substrate/issues/8074
=> Upgrade hyper to 0.14.11

.gitlab-ci.yml
Resolves https://github.com/paritytech/ci_cd/issues/179.
=> Run tests for the wasmer sandbox

client/db/src/bench.rs
=> Fix tracker repeat writes

Cargo.lock, client/tracing/Cargo.toml, client/tracing/src/logging/mod.rs
As we have removed the feature for now, we don't need this here as well.
=> Remove some browser leftovers

frame/election-provider-support/src/onchain.rs, frame/staking/src/pallet/impls.rs
Trivial syntax changes extracted from  #9507.
=> Small syntax changes for staking and elections code

client/network/src/service/tests.rs
=> Fix flaky test

.gitlab-ci.yml
Fix buildah login. Credentials user/password were swapped.
=> Fix buildah login

client/network/src/discovery.rs
=> Backports for 0.9.10

client/beefy/rpc/Cargo.toml
=> beefy-gadget-rpc: fix toml warnings

.gitlab-ci.yml
please don't forget to remove https://github.com/paritytech/polkadot/pull/3807/files#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7R18-R20
=> CI: undebug CI image

frame/support/src/traits/tokens.rs
Useful for writing generic code.
=> Expose trait Balance & AssetId

docs/CODEOWNERS
=> BEEFY code owner

frame/executive/src/lib.rs, frame/system/benches/bench.rs
Polkadot address: 15XuanNimo5951s3RjFTPX1AvYVnCwfr3SDhb3AV4fQF3LpK
=> Migrate the pallet macros of some tests and benches

primitives/core/src/crypto.rs, ss58-registry.json
Adds Polkadex's SS58 Prefix to registry
=> Add Polkadex to SS58 Registry

client/network/test/src/sync.rs
Fixes: https://github.com/paritytech/substrate/issues/9887
=> Fix flaky sync tests

Cargo.lock, client/cli/Cargo.toml, client/network/Cargo.toml, client/tracing/Cargo.toml, primitives/core/Cargo.toml
This updates a few of the easy-to-update deps mentioned in https://github.com/paritytech/ci_cd/issues/219, plus a few collateral ones
=> Update multiple dependencies

client/service/src/lib.rs
Looks like the code is missing a `return` here.
=> Fix transaction pool rejection

Cargo.lock, client/db/Cargo.toml
Fixes https://github.com/paritytech/polkadot/issues/4169
=> Bump parity-db

Cargo.lock, primitives/consensus/slots/Cargo.toml, primitives/consensus/slots/src/lib.rs
Add serde support for the `Slot` type as we'd like to use it directly in our RPC.
=> Add serde support for `Slot` type

client/keystore/src/local.rs
Fixes: https://github.com/paritytech/substrate/issues/9886
=> Keystore: Store files with permission 600 on unix

client/consensus/pow/src/lib.rs, client/executor/wasmtime/src/runtime.rs, client/telemetry/src/lib.rs, frame/bags-list/src/lib.rs, frame/bags-list/src/list/mod.rs, frame/beefy-mmr/primitives/src/lib.rs, frame/beefy-mmr/src/lib.rs, frame/benchmarking/src/lib.rs, frame/contracts/src/lib.rs, frame/election-provider-multi-phase/src/lib.rs, frame/election-provider-support/src/lib.rs, frame/election-provider-support/src/onchain.rs, frame/executive/src/lib.rs, frame/staking/src/pallet/mod.rs, frame/support/procedural/src/construct_runtime/mod.rs, frame/support/src/lib.rs, frame/support/src/storage/bounded_vec.rs, frame/support/src/storage/weak_bounded_vec.rs, frame/support/src/traits/misc.rs, frame/system/src/lib.rs, primitives/beefy/src/commitment.rs, primitives/npos-elections/solution-type/src/lib.rs, primitives/npos-elections/src/assignments.rs, primitives/sandbox/src/lib.rs, utils/frame/generate-bags/src/lib.rs
This fix some of the dead link.
But there is still some like in client/network which I don't really know how to solve. Also this is a bit a chicken egg problem, as long as we don't fix all error then we can't put it on CI, but as long as we don't put it on CI we keep adding some error.
After this PR I'll probably just remove all the dead link and open an issue linking to all the removal so people can fix them afterwards.
=> Fix some doc link

frame/contracts/src/storage.rs
some inner comment seems wrong to me, I tested with a debug assert and the stuff which it said to never happen actually happens.
cc @athei
=> fix inner comment

.gitlab-ci.yml
Fix changes made in https://github.com/paritytech/substrate/pull/10338
=> [ci] Fix publish-rustdoc job

client/api/src/backend.rs, client/consensus/common/src/block_import.rs
Some information I found useful from conversation on Matrix.
=> Minor documentation update for `AuxStore` and `BlockImportParams.auxiliary`

docs/CODEOWNERS
Remove myself as `BEEFY` code owner.  New code owner needs to be decided upon.
=> BEEFY update CODEOWNERS

docs/CODEOWNERS
Add myself as `beefy` code owner.
=> Beefy: update CODEOWNERS

.maintain/monitoring/grafana-dashboards/README_dashboard.md
Closes: https://github.com/paritytech/substrate/issues/10491
=> Fix link to grafana dashboard

client/network-gossip/src/bridge.rs, client/network-gossip/src/lib.rs
So that we could jump to the definition easily.
=> Use intra doc in network-gossip

Cargo.lock, client/beefy/rpc/Cargo.toml, client/beefy/rpc/src/lib.rs
Added tests for existing `beefy-gadget-rpc` code.
=> Add beefy-gadget-rpc tests

frame/system/src/lib.rs, frame/system/src/tests.rs
Fixes: https://github.com/paritytech/substrate/issues/10554
=> Fix Places where AccountId Uses Default

client/chain-spec/src/chain_spec.rs, client/service/src/client/call_executor.rs
Some clippy issues managed to get their way in after https://github.com/paritytech/substrate/pull/10570
This fixes that.
=> Fix Clippy

frame/support/src/storage/bounded_vec.rs
interestingly other bounded types already had it, this one was forgotten.
=> Add Ord implementation for BoundedVec

client/transaction-pool/README.md
Fixes some minor typos and syntax errors.
=> Minor syntax and typo edits for tx pool docs

.gitlab-ci.yml
Part of https://github.com/paritytech/ci_cd/issues/262
=> [ci] pipeline chores

frame/conviction-voting/src/conviction.rs, frame/conviction-voting/src/lib.rs, frame/conviction-voting/src/types.rs, frame/conviction-voting/src/vote.rs, frame/referenda/src/lib.rs, frame/referenda/src/mock.rs, frame/referenda/src/types.rs
=> MEL Fixes for Referenda and Conviction Voting

frame/election-provider-multi-phase/src/lib.rs, frame/election-provider-multi-phase/src/unsigned.rs, frame/elections-phragmen/src/lib.rs, frame/support/procedural/src/pallet/expand/error.rs, frame/support/src/error.rs, frame/support/test/tests/construct_runtime.rs, frame/support/test/tests/pallet.rs, frame/support/test/tests/pallet_instance.rs, primitives/runtime/src/lib.rs
Ran into this problem when adding a new variant. Seems that `TooManyConsumers` was also missing from when that was added.
=> Introduce ModuleError struct

.gitlab-ci.yml
=> [ci] fix publish-rustdocs

frame/election-provider-multi-phase/src/lib.rs
Just spelling corrections pertaining to pallet_election_provider_multi_phase.
=> Docs Corrections

frame/staking/src/pallet/mod.rs
See https://github.com/paritytech/substrate/pull/10670#discussion_r817236706
=> staking: Expose `MaxUnlockingChunks` in metadata as a const

.github/pr-custom-review.yml
This PR adds config file for GitHub Action [pr-custom-review](https://github.com/paritytech/pr-custom-review)
Needed to unblock https://github.com/paritytech/substrate/pull/10951 - see more details there
=> Add pr-custom-review config

frame/election-provider-support/src/lib.rs
Change set extracted from https://github.com/paritytech/substrate/pull/10694.
This PR:
- removes `TestDataProvider`, which is not useful because we require that the data provider for the staking pallet's election provider to be the staking pallet.
-  Modifies the `NoElection` election provider to be generic over the `DataProvider`. In all Polkadot use cases this will be the staking pallet.
=> election provider support: Update some test only types

frame/referenda/src/benchmarking.rs, frame/referenda/src/lib.rs, frame/referenda/src/mock.rs, frame/referenda/src/tests.rs, frame/referenda/src/types.rs, frame/support/src/traits/schedule.rs
Small improvements from: https://github.com/paritytech/substrate/pull/10195#pullrequestreview-902440914
=> Feedback from @XLC for Referenda Pallet

bin/node/runtime/src/lib.rs, frame/state-trie-migration/src/lib.rs
while writing the doc for this, I came across these two as potential improvements.
The doc can be found here: https://hackmd.io/JagpUd8tTjuKf9HQtpvHIQ
=> some additional utils for state-trie-migration

frame/support/src/storage/bounded_vec.rs, frame/support/src/storage/weak_bounded_vec.rs
Fixes: https://github.com/paritytech/substrate/issues/11145
=> frame-support: Rename tests to express what they are doing

.gitlab-ci.yml
Fixes `master` pipeline (publishing part)
=> [ci] Remove vault

.github/pr-custom-review.yml
Sorry, the key was wrong in https://github.com/paritytech/substrate/pull/11169
=> fix .github/pr-custom-review.yml

Cargo.lock, frame/identity/src/lib.rs, frame/identity/src/tests.rs, frame/identity/src/types.rs
Taken from https://github.com/paritytech/substrate/pull/11112 aims to reduce the size of the PR
=> add has_identity

Cargo.lock, bin/node/cli/Cargo.toml, bin/node/cli/tests/websocket_server.rs
=> Bump soketto to v0.7.1

.gitlab-ci.yml
PR changes coincident CI variables in use from project to group ones.
=> Change ci vars to use group one's

primitives/wasm-interface/src/wasmi_impl.rs
#11310. 
Fix error when enable feature = wasmi on no_std
=> import Vec when run on no_std for wasmi

frame/uniques/README.md
=> Uniques: fix typo in README.md

Cargo.lock, bin/node/runtime/src/lib.rs
Adding the concrete types for runtime.
MaxTextLength, PerByteFee, NameServiceResolver 
The constants might need to  be adjusted.
=> add conceret types for runtime

Cargo.lock, client/network/Cargo.toml
=> sc-network: update cid v0.6.0 => v0.8.4

bin/node/cli/tests/running_the_node_and_interrupt.rs, client/consensus/babe/src/lib.rs
There is an `Arc` reference cycle that causes a memory leak and prevents `Client` from being disposed correctly.
=> Break the Client reference cycle

frame/nomination-pools/src/lib.rs
A nit pick to https://github.com/paritytech/substrate/pull/11373
=> Only read storage after origin check

Cargo.lock, bin/node-template/node/Cargo.toml, bin/node/cli/Cargo.toml, bin/node/rpc/Cargo.toml, client/beefy/rpc/Cargo.toml, client/consensus/babe/rpc/Cargo.toml, client/consensus/manual-seal/Cargo.toml, client/finality-grandpa/rpc/Cargo.toml, client/rpc-api/Cargo.toml, client/rpc-servers/Cargo.toml, client/rpc-servers/src/lib.rs, client/rpc/Cargo.toml, client/service/Cargo.toml, client/sync-state-rpc/Cargo.toml, frame/contracts/rpc/Cargo.toml, frame/merkle-mountain-range/rpc/Cargo.toml, frame/transaction-payment/rpc/Cargo.toml, utils/frame/remote-externalities/Cargo.toml, utils/frame/rpc/state-trie-migration-rpc/Cargo.toml, utils/frame/rpc/support/Cargo.toml, utils/frame/rpc/system/Cargo.toml, utils/frame/try-runtime/cli/Cargo.toml
=> backport: jsonrpc http server: expose health endpoint (#11395)

Cargo.lock, utils/frame/benchmarking-cli/Cargo.toml, utils/frame/benchmarking-cli/src/machine/mod.rs
[prettytable-rs](https://github.com/phsym/prettytable-rs) doesn't seem to be maintained anymore, see https://github.com/rustsec/advisory-db/issues/1173 for details.
use `prettytable-rs`:
```
2022-05-17 12:03:14 Running machine benchmarks...    
2022-05-17 12:03:27 
+----------+----------------+--------------+--------------+-------------------+
| Category | Function       | Score        | Minimum      | Result            |
+----------+----------------+--------------+--------------+-------------------+
| CPU      | BLAKE2-256     | 1.37 GiB/s   | 1.00 GiB/s   | ✅ Pass (136.5 %) |
+----------+----------------+--------------+--------------+-------------------+
| CPU      | SR25519-Verify | 697.81 KiB/s | 666.00 KiB/s | ✅ Pass (104.8 %) | …
```
=> Migrate abandoned `prettytable-rs` to `comfy-table`

client/beefy/rpc/src/lib.rs, client/finality-grandpa/rpc/src/lib.rs, client/rpc/src/author/mod.rs, client/rpc/src/chain/chain_full.rs, client/rpc/src/state/state_full.rs
Was upgrading my node and noticed this strange pattern, doesn't seem to be necessary
=> Remove unnecessary RPC boxing

utils/fork-tree/src/lib.rs
As per title
Related to https://github.com/paritytech/substrate/pull/11476
=> Test for the fork-tree post-order DFS traversal requirement

utils/fork-tree/src/lib.rs
backport of https://github.com/paritytech/substrate/pull/11531
=> Fork-Tree import requires post-order DFS traversal (#11531)

client/cli/src/params/pruning_params.rs, client/state-db/src/lib.rs
Updated the docs of the pruning cli option.
Fixes https://github.com/paritytech/substrate/issues/11475
=> Fixed pruning docs

.gitlab-ci.yml
Supplements #11462 and finalizes the `rusty-cachier` integration.
=> Add `rusty-cachier notify` job

frame/treasury/src/benchmarking.rs
Changes:
- Ensure that the `Treasury::Spend` bench does not panic in case that `SpendOrigin` is set to `NeverEnsureOrigin`
=> Short circuit `Treasury::Spend` benchmark for `NeverEnsureOrigin`

frame/ranked-collective/src/tests.rs, frame/support/src/traits.rs, frame/support/src/traits/dispatch.rs, frame/support/src/traits/misc.rs, primitives/runtime/src/traits.rs
Also repot some code in `frame_support` which is basic and unrelated to Frame into `sp_runtime`.
=> Helper macro for `Morph` impls

frame/system/src/extensions/check_mortality.rs
closes: https://github.com/paritytech/substrate/issues/11571
=> make era public

client/cli/src/params/pruning_params.rs, client/db/src/lib.rs, client/network/test/src/lib.rs, client/service/src/config.rs
Learned the hard way that finality is implied here, this piece of documentation would have been helpful for me.
=> Improve docs on `--keep-blocks` CLI parameter and related data structures

frame/assets/src/lib.rs, frame/atomic-swap/src/lib.rs, frame/balances/src/lib.rs
Was good for testing but not needed anymore. @shawntabrizi
=> Remove storage `MaxValues` limits

frame/democracy/src/lib.rs, frame/democracy/src/tests/public_proposals.rs
Fixes https://github.com/paritytech/substrate/issues/11096
=> Added an event for cancel_proposal

client/basic-authorship/src/basic_authorship.rs, primitives/consensus/common/src/evaluation.rs
Maybe this check is useless, we could remove it ?
=> chore: reducing codec times

Cargo.lock, client/chain-spec/derive/Cargo.toml, client/tracing/proc-macro/Cargo.toml, frame/contracts/proc-macro/Cargo.toml, frame/election-provider-support/solution-type/Cargo.toml, frame/staking/reward-curve/Cargo.toml, frame/support/procedural/Cargo.toml, frame/support/procedural/tools/Cargo.toml, frame/support/procedural/tools/derive/Cargo.toml, frame/support/procedural/tools/src/syn_ext.rs, primitives/api/proc-macro/Cargo.toml, primitives/core/hashing/proc-macro/Cargo.toml, primitives/debug-derive/Cargo.toml, primitives/runtime-interface/proc-macro/Cargo.toml, primitives/version/proc-macro/Cargo.toml, test-utils/derive/Cargo.toml
Fixes: https://github.com/paritytech/substrate/issues/11706
polkadot companion: https://github.com/paritytech/polkadot/pull/5701
cumulus companion: https://github.com/paritytech/cumulus/pull/1388
=> Update syn and fix compilation

primitives/runtime/src/bounded/weak_bounded_vec.rs
Another trait implementation on these bounded types.
=> Implement Serialize/Deserialize on WeakBoundedVec

frame/support/src/weights.rs
=> Fix typo in weights.rs

Cargo.lock, bin/node/executor/Cargo.toml, bin/node/executor/tests/fees.rs, frame/system/src/lib.rs
backport https://github.com/paritytech/substrate/pull/11754 to release branch
polkadot companion branch: release-v0.9.25
=> backport #11754 to release branch

client/network/src/service.rs
This is a minor usability improvement that otherwise leads to confusing error messages.
Fixes #11709
=> Ignore boot and reserved nodes with peer ID the same as in local node itself

frame/assets/src/lib.rs
Closes: https://github.com/paritytech/substrate/issues/11870
=> pallet-assets: Update docs

frame/tips/src/lib.rs
=> Fixing conflict for PR 11596

frame/system/src/limits.rs
=> Fix typo in limits.rs

frame/nomination-pools/benchmarking/src/mock.rs, frame/nomination-pools/test-staking/src/mock.rs, frame/session/benchmarking/src/mock.rs, frame/staking/src/mock.rs, frame/staking/src/pallet/mod.rs
Reported by a student in the academy.
=> remove unused staking trait bound

frame/support/src/traits/tokens/misc.rs, frame/support/test/tests/pallet_ui/storage_info_unsatisfied.stderr, frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
Very simple PR that adds/derives `MaxEncodedLen` for token traits.
=> Add and implement MaxEncodedLen to token traits

client/rpc-servers/src/middleware.rs
=> fix(rpc middleware): fix `is_error` bug

bin/node-template/pallets/template/src/lib.rs, bin/node-template/pallets/template/src/mock.rs
=> nit improvements to pallet template

client/allocator/src/freeing_bump.rs, frame/democracy/src/benchmarking.rs, frame/identity/src/benchmarking.rs, frame/offences/benchmarking/src/lib.rs, frame/proxy/src/benchmarking.rs, scripts/ci/gitlab/pipeline/test.yml, utils/frame/benchmarking-cli/src/pallet/command.rs
Instead of waiting for benchmarks failing in Polkadot CI, we also can just test them in Substrate :P
=> Fix benchmarks and adds CI to test them

client/network/common/src/service.rs
=> Additional constraints for NotificationSender

primitives/trie/src/cache/mod.rs
Closes: https://github.com/paritytech/substrate/issues/12134
=> Fix flaky trie-db cache test

frame/uniques/src/lib.rs
Was reading through the code and noticed this minor inaccuracy in the docs.
=> Uniques: Small fix in docs

primitives/runtime/Cargo.toml
=> fix sp-weight std

frame/fast-unstake/src/lib.rs, frame/fast-unstake/src/types.rs
I am sorry is all I have to say.
=> export more types from fast-untsake 🤦‍♂️

frame/election-provider-multi-phase/src/lib.rs, frame/election-provider-multi-phase/src/mock.rs, frame/election-provider-support/src/lib.rs, frame/election-provider-support/src/onchain.rs, frame/staking/src/pallet/mod.rs
https://github.com/paritytech/substrate/pull/12436
=> Some prototyping on top of #12436

client/beefy/src/tests.rs
BEEFY block import test was not correctly filtering beefy justifications in tests. Also the invalid justif case was verifying for wrong block number.
This is a small PR to fix the test.
=> client/beefy: fix incorrect BEEFY justifications import test

frame/support/test/tests/pallet_ui/dev_mode_without_arg_max_encoded_len.stderr
Master is broken after https://github.com/paritytech/substrate/pull/12628
Hope this PR fixes this
=> Fix UI tests

bin/node-template/pallets/template/src/tests.rs
Add an example of how to test for events into the example pallet. Right now, the information is pretty hard to find without looking into pallet tests or finding some particular posts on the stackoverflow.
=> Add event testing example to pallet template

frame/support/test/tests/construct_runtime.rs, frame/support/test/tests/pallet_instance.rs
=> Remove hardcoded crate versions from tests

frame/scheduler/src/migration.rs
Follow up for https://github.com/paritytech/substrate/pull/12989 :man_facepalming:
=> Make migration public

bin/node/runtime/src/lib.rs
This brings the code up to present master.
=> add BenchmarkHelper for second instance

client/service/src/task_manager/mod.rs
Previously you would need to spend some time going into the code to figure out if a task is blocking or async. This change allows this determination directly from metrics.
=> Add task type label to task metrics

frame/society/src/lib.rs, frame/society/src/tests.rs
Fix #13275
Added event `SkepticsChosen` in society v1 pallet.
=> feat: add event SkepticsChosen event in society

client/rpc-spec-v2/src/transaction/error.rs
=> rpc-spec-v2/tx: Fix error typo

frame/ranked-collective/src/lib.rs
Cherry-picking the fix from the PR https://github.com/paritytech/substrate/pull/13297
=> Cherry-pick / benchmarks: EnsureRankedMember must add ranked members (#13297)

scripts/ci/gitlab/pipeline/publish.yml
CI fix `dockerhub-description` image name
=> CI fix `dockerhub-description` image name

scripts/ci/gitlab/pipeline/publish.yml
CI fix docker description publishing.
=> CI fix docker description publishing

.gitattributes, .gitlab-ci.yml, scripts/ci/gitlab/pipeline/build.yml, scripts/ci/gitlab/pipeline/check.yml, scripts/ci/gitlab/pipeline/publish.yml, scripts/ci/gitlab/pipeline/test.yml, scripts/ci/gitlab/pipeline/zombienet.yml, scripts/ci/gitlab/prettier.sh
As previously discussed in https://github.com/paritytech/ci_cd/issues/515
=> Automatically format ci pipeline specs with prettier

Cargo.lock, bin/node/bench/Cargo.toml, client/db/Cargo.toml, primitives/api/Cargo.toml, primitives/core/Cargo.toml, primitives/state-machine/Cargo.toml, primitives/trie/Cargo.toml, test-utils/runtime/Cargo.toml, utils/binary-merkle-tree/Cargo.toml, utils/frame/rpc/state-trie-migration-rpc/Cargo.toml
This PR update trie dependencies to latest.
=> update trie dependencies

.gitlab-ci.yml
for https://github.com/paritytech/ci_cd/issues/766
=> roll out new debian 11 ci image

.gitlab-ci.yml
Bump zombienet version, this version includes fixes for race condition like (https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2619486)
Thanks!
=> Bump zombienet version

frame/referenda/README.md
=> Update links in the Referenda Readme

client/service/src/client/client.rs
=> Backport of #14067 for release 0.9.42

Cargo.lock, bin/node/bench/Cargo.toml, client/db/Cargo.toml
polkadot companion: https://github.com/paritytech/polkadot/pull/7212
=> Bump `kvdb-rocksdb` to 0.19.0

.github/pr-custom-review.yml
Fixing indent after https://github.com/paritytech/substrate/pull/14122
=> Fix indent for pr-custom-review config

client/network/src/protocol_controller.rs
Add `SetId` logging where missing to simplify debugging.
=> [minor] Extend logging with `SetId` in `ProtocolController` where missing

client/keystore/Cargo.toml, primitives/application-crypto/Cargo.toml
=> Added missing BLS feature

client/offchain/src/api/http.rs
Update the log level for HTTP requests from off-chain worker
=> Update logging from error to trace

client/consensus/beefy/src/communication/gossip.rs, client/consensus/beefy/src/communication/request_response/incoming_requests_handler.rs, client/consensus/beefy/src/justification.rs, client/consensus/beefy/src/worker.rs, client/consensus/grandpa/src/communication/gossip.rs, client/consensus/grandpa/src/communication/mod.rs, client/consensus/grandpa/src/communication/periodic.rs, client/consensus/grandpa/src/justification.rs, client/consensus/grandpa/src/warp_proof.rs
Found them while looking over the code.
=> Do some cleanups

client/network/src/behaviour.rs, client/network/src/peer_info.rs, client/network/src/service.rs
Remove the need of updating `listen_addresses` and `external_addresses` on every single call to `NetworkWorker::next_action`.
This is very inefficient, as it involves creating new vectors from hashsets on every call, even if nothing changed in the address set. It turns out to be time consuming when testing in Versi, under a heavy load - about 5-8% of the total polkadot CPU utilisation.
Discussion about motivation here: https://github.com/libp2p/rust-libp2p/discussions/3840#discussioncomment-6575512
This is a tricky problem to solve, since this data needs to be accessible from a `NetworkService` instance, which does not have direct access to the `Swarm`.
- Changed the underlying data store from a `Vec` to a `HashSet`, as it's more efficient for inserts/removes (which is also what libp2p …
=> network: optimize update procedure for listen_addrs and external_addrs

primitives/crypto/ec-utils/Cargo.toml
A description is needed to publish to crates.io
=> Add description to sp-crypto-ec-utils

.maintain/frame-weight-template.hbs, utils/frame/benchmarking-cli/src/pallet/template.hbs
=> update weight file template

scripts/ci/gitlab/pipeline/test.yml
=> Add `--workspace` to clippy

README.md
=> update readme: archived repo
