paritytech/substrate

client/db/src/lib.rs, client/db/src/parity_db.rs, primitives/database/src/lib.rs, utils/frame/benchmarking-cli/src/storage/write.rs
Also adds a `sanitize_key` function to strip path-prefixes from the db-keys (for databases that
use prefixed keys such as rocksdb)
fixes #10998
=> Prevent possible rocksdb-corruption by running benchmark-storage

frame/election-provider-multi-phase/src/benchmarking.rs
Fix the regression introduced in https://github.com/paritytech/polkadot/pull/5097 in `election-provider-multi-phase`.
=> fix sibmit benchmark in election-multi-phase pallet

utils/frame/try-runtime/cli/src/lib.rs
```rust
.map(|(spec_name, spec_version)| (spec_name.to_lowercase(), spec_version))
{
Ok((name, version)) => {
// first, deal with spec name
if expected_spec_name == name {
if expected_spec_name.to_lowercase() == name {
```
If we turn the `spec_name` into lowercase. We should also make `expected_spec_name` lowercase. 
Our network's `spec_name` is uppercase. So the try runtime always fails here.
cc @kianenigma
=> Use Lowercase

primitives/std/src/lib.rs
This is a very useful trait.
We can use it directly under std ENV.
So, I hope we can expose the `ToOwned` type.
=> Expose `ToOwned`

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature.yaml
This introduces [template forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms), with a very strong call to action to use our stack exchange over filing issues for support. This can beset be experienced before a merge at the docs issues:
https://github.com/substrate-developer-hub/substrate-docs/issues/new/choose
All buttons lead to open a issue that has this to begin with:
---
If users want to bypass using the issue forms and get the typical empty text entry area they only need to hit the bottom left "open a blank issue" link (a bit hidden)
=> Add github issue form templates

frame/whitelist/Cargo.toml, frame/whitelist/src/benchmarking.rs, frame/whitelist/src/lib.rs
compilation error when compiling `pallet-whitelist` alone:
```
error[E0432]: unresolved import `sp_core::to_substrate_wasm_fn_return_value`
--> primitives/api/src/lib.rs:80:9
|
80 | pub use sp_core::to_substrate_wasm_fn_return_value;
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `to_substrate_wasm_fn_return_value` in the root
For more information about this error, try `rustc --explain E0432`.
error: could not compile `sp-api` due to previous error
```
Also adjusted some import ordering
=> pallet-whitelist: add sp-api/std to std feature to fix compile error

frame/support/src/traits/misc.rs
add `MaxEncodedLen` trait to `Time` trait, as in our [migration](https://github.com/open-web3-stack/open-runtime-module-library/blob/fecbe0197ac0c1380424d193a46289d3846cbf1d/oracle/src/lib.rs#L77) to removing `without_storage_info`, the `Time::Moment` need `MaxEncodedLen`.
also currently in pallet_timestamp, `Moment` already has `MaxEncodedLen` trait bound:
https://github.com/paritytech/substrate/blob/6506784c95c2b6ee1db19cdbfc8142e9c7a071dc/frame/timestamp/src/lib.rs#L126-L131
=> add `MaxEncodedLen` trait to Time::Moment

frame/support/procedural/src/pallet/expand/call.rs, frame/support/procedural/src/pallet/expand/error.rs, frame/support/procedural/src/pallet/expand/pallet_struct.rs, frame/support/procedural/src/pallet/expand/storage.rs, frame/support/test/Cargo.toml, frame/support/test/pallet/src/lib.rs, frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
Before this pr it was failing when compiling with `missing_docs`, because the macro was generating
functions etc without the appropriate docs. In the case of this pr it is mainly about hiding these
functions in the docs as they are internal api anyway.
=> pallet-macro: Ensure that building with `missing_docs` works

client/cli/src/commands/import_blocks_cmd.rs, client/service/src/chain_ops/import_blocks.rs
This fixes a bug with `import-blocks` reading the entire `stdin` before starting to import the
blocks. However, for huge files that uses quite a lot of memory. We can just read from `stdin` step
by step as we do it with a file. This ensures that we don't read the entire input at once into memory.
Fixes: https://github.com/paritytech/substrate/issues/11071
=> import-blocks: Do not read `stdin` to memory

client/network/src/block_request_handler.rs
This PR permits duplicate block requests from peers if the request is "small", defined as when only the block header and justification are requested. A separate, milder reputation penalty is issued for those duplicates. This prevents peers from being banned for (e.g.) duplicate ancestor search requests, which can occur if a peer has disconnected and reconnected. This is one of the solutions discussed in #10794.
Should resolve #10794.
=> Don't ban peers for small duplicate requests

Cargo.lock, client/db/Cargo.toml, client/db/src/parity_db.rs, client/db/src/utils.rs
This PR changes the way we rewrite metada when paritydb meta mismatch.
Changes to column configuration are written, but salt and db_version are kept the same.
This is a quick fix for https://github.com/paritytech/polkadot/issues/5168 but I guess things should evolve to be more manual in the future.
Polkadot companion: https://github.com/paritytech/polkadot/pull/5175
=> Do not upgrade db_version on metadata reading failure.

client/network/src/config.rs, client/service/src/builder.rs
Fixes: https://github.com/paritytech/polkadot/issues/5169
=> warp-sync: Return an error when trying to enable it for archive nodes.

frame/support/src/lib.rs, frame/support/src/storage/bounded_btree_map.rs, frame/support/src/storage/bounded_btree_set.rs, frame/support/src/storage/bounded_vec.rs, frame/support/src/storage/generator/double_map.rs, frame/support/src/storage/generator/map.rs, frame/support/src/storage/generator/nmap.rs, frame/support/src/storage/mod.rs, frame/support/src/storage/types/nmap.rs, frame/support/src/storage/weak_bounded_vec.rs
This PR does 2 things:
1. Fixes a bug with the `generate_storage_alias!` macro, where some of the syntaxes had the `key` and `hasher` in the wrong order in the underlying storage definition.
2. Chooses the more intuitive order of `(hasher, key)` for the macro definition, which lines up with the order of these same types in the underlying storage type definition.
Fortunately, the Rust type system prevents anyone from really messing up here.
=> Fix `generate_storage_alias!`

client/executor/benches/bench.rs, client/executor/src/wasm_runtime.rs, client/executor/wasmtime/src/runtime.rs, client/executor/wasmtime/src/tests.rs
polkadot companion: https://github.com/paritytech/polkadot/pull/5197
Fixes https://github.com/paritytech/polkadot/issues/5190
=> Add extra WASM heap pages when precompiling the runtime blob

frame/referenda/src/branch.rs, frame/referenda/src/lib.rs, frame/referenda/src/types.rs
related issue: #11056
polkadot address: 15XuanNimo5951s3RjFTPX1AvYVnCwfr3SDhb3AV4fQF3LpK
=> pallet-referenda: make the pallet instantiable

Cargo.lock, bin/node/cli/src/cli.rs, bin/node/cli/src/command.rs, utils/frame/benchmarking-cli/Cargo.toml, utils/frame/benchmarking-cli/src/block/bench.rs, utils/frame/benchmarking-cli/src/block/cmd.rs, utils/frame/benchmarking-cli/src/block/mod.rs, utils/frame/benchmarking-cli/src/lib.rs, utils/frame/benchmarking-cli/src/overhead/cmd.rs
Deja vu! The code that I originally wanted to use for #10977 is now put to better use.  
This command helps in gauging the precision or our benchmarking.  
It compares the time that it takes to execute a block to its consumed weight. Ideally they are the same.  
Example with a CPU intensive hand-crafted block where our benchmarking worked well:  
```rust
Block 2 with     2 tx used 102.39% of its weight ( 1,281,193,264 of 1,251,309,762  ns) - OVER WEIGHT!
```
Or some empty blocks where we over-estimate:
```rust
Block 1 with     1 tx used  65.03% of its weight (     4,464,209 of      6,864,645 ns)    
Block 2 with     1 tx used  65.15% of its weight (     4,472,344 of      6,864,645 ns)    
Block 3 with     1 tx used  64.27% of its weight (     4,492,493 of      6,989,645 ns)
```
There are …
=> Add `benchmark-block` command

frame/conviction-voting/src/conviction.rs, frame/conviction-voting/src/lib.rs, frame/conviction-voting/src/tests.rs, frame/conviction-voting/src/types.rs
related issue: #11056
polkadot address: 15XuanNimo5951s3RjFTPX1AvYVnCwfr3SDhb3AV4fQF3LpK
=> pallet-conviction-voting: make the pallet instantiable

frame/support/src/storage/mod.rs
`StorageDoubleMap` has no magically efficient storage removal operation compared to an iterator which will remove all the storage items in the double map.
Users are getting confused like here: https://substrate.stackexchange.com/questions/1280/complexity-of-storagedoublemapremove-prefix/1285#1285
=> Remove Misleading Sentence About `StorageDoubleMap`

frame/bags-list/src/benchmarks.rs, frame/nomination-pools/benchmarking/src/lib.rs, frame/nomination-pools/src/lib.rs, frame/nomination-pools/src/mock.rs, frame/nomination-pools/src/tests.rs, frame/support/src/traits/misc.rs
closes https://github.com/paritytech/substrate/issues/10903
=> `bond_extra` for nomination pools

bin/node/cli/tests/benchmark_storage_works.rs, utils/frame/benchmarking-cli/src/overhead/weights.hbs, utils/frame/benchmarking-cli/src/storage/weights.hbs
- The Polkadot spellcheck and fmt CI rejected my filled out templates, this should fix it.  
- Test that `benchmark-storage` works with the `--dev` runtime
=> Spellcheck HBS templates and add test

client/network/src/service/tests.rs
The test broke when the transaction pool synchronization appeared in the instantiated client.
Closes #8681
=> Unignore test

frame/election-provider-multi-phase/src/mock.rs, frame/election-provider-support/solution-type/src/single_page.rs, frame/election-provider-support/src/lib.rs, frame/election-provider-support/src/mock.rs, frame/election-provider-support/src/tests.rs, primitives/npos-elections/src/lib.rs
Fixes #11092 
when constructing `NposSolution` via `from_assignment`, check that the number of voters is less than the bound `MaxVoters` provided for the implementation of `MaxEncodedLen`.
@kianenigma 
Polkadot address: 131dPecTmpTC1p1ofemufqFBJo9vNbV7dkgN7vWwKnaSMkC4
=> Enforce `MaxEncodedLen` impl for `NposSolution`

Cargo.lock, client/db/Cargo.toml
Trivial update on the kvdb-rocksdb side, which is essentially just a build fix on openbsd/msvc targets.
=> Update kvdb-rocksdb to 0.15.2

frame/aura/src/lib.rs, frame/babe/src/lib.rs, frame/grandpa/src/lib.rs
FRAME system `deposit_log` takes a `DigestItem`, i.e. exactly the type we are passing in
=> Remove not required DigestItem conversion

frame/support/procedural/src/transactional.rs, frame/support/src/storage/mod.rs, frame/support/src/storage/transactional.rs
This fixes some nitpicks related to the transactional storage stuff from me. As everything was
merged too fast, here are some nitpicks from me. First, the entire functionality is moved into its
own file to have a clear separation. Secondly I changed the `set_transactional_level` to not take
`Layer` by reference. Besides that I have added some docs etc.
=> transactional: Fix some nitpicks

client/executor/wasmtime/src/runtime.rs
There is a spelling error in `substrate/client/executor/wasmtime/src/runtime.rs` file.
=> Fix a spelling error.

client/cli/src/arg_enums.rs
This pr changes all default execution strategies to `Wasm`. This is basically a deprecation of the
native runtime. While the native runtime isn't removed and can still be used, it will not be used
anymore by default.
This will also improve the usage for people who want to run random commits, which most often forget
to run with `--execution wasm`. Otherwise they often run into storage root mismatches because of
using the native runtime.
=> Change default execution strategies to `Wasm`

utils/fork-tree/src/lib.rs
Fork tree nodes below the fork-tree roots should not be finalized.
Previous code was preventing finalization of roots children descendants but was allowing finalization of root children.
=> Fix fork-tree descendent check

bin/node-template/node/src/command.rs, bin/node/cli/src/command.rs, client/consensus/babe/src/lib.rs, client/finality-grandpa/src/authorities.rs, client/finality-grandpa/src/lib.rs, client/finality-grandpa/src/tests.rs, client/network/test/src/lib.rs
Partially addresses https://github.com/paritytech/substrate/issues/10962
Implementation of revert method for GRANDPA consensus.
In practice, this procedure:
- Removes standard authority changes nodes that were announced after the revert point
- Removes forced authority changes elements that were announced after the revert point
- Resets the voting round state
=> Grandpa revert procedure

Cargo.lock, bin/node/cli/Cargo.toml, client/informant/src/display.rs, client/network/src/config.rs, client/network/src/lib.rs, client/peerset/src/lib.rs, client/peerset/src/peersstate.rs, utils/frame/remote-externalities/Cargo.toml, utils/frame/try-runtime/cli/Cargo.toml, utils/frame/try-runtime/cli/src/commands/follow_chain.rs
The main motivation behind this is to solve an issue in the staking miner, remove of duplicate versions.
As bonus I removed an unused dependency in `bin/node`
polkadot companion: https://github.com/paritytech/polkadot/pull/5264
=> chore: update jsonrpsee to `v0.10.1`

frame/transaction-payment/src/lib.rs, primitives/arithmetic/src/fixed_point.rs
fixes https://github.com/paritytech/substrate/issues/10572
=> relax input conditions of fixed::checked_from_integer

frame/support/src/storage/mod.rs, frame/support/src/storage/types/double_map.rs, frame/support/src/storage/types/map.rs, frame/support/src/storage/types/nmap.rs, primitives/io/src/lib.rs
These docs didn't mention how the removal works internally. This is important for the user to know
that calling such a method multiple times in the same block leads always to the same result.
=> Improve docs of `remove_all` and `remove_prefix`

client/executor/runtime-test/src/lib.rs, client/executor/src/integration_tests/mod.rs, primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs
Currently if the runtime calls into the host and the host panics we're left with no backtrace from within the runtime since the panic is only caught [here](https://github.com/paritytech/substrate/blob/78b1ad3c754514135bc0026407f7d2bf3bacae27/client/executor/src/native_executor.rs#L65) *after* the whole execution context is already dropped. (And the host functions [*can* panic](https://github.com/paritytech/substrate/issues/11132).)
This PR makes it so that we catch any panics on the FFI boundary between the runtime and the host, and turn that into a trap. This allows us to extract and print out the backtrace from within the runtime as part of the error message and see what exactly within the runtime called the host function which panicked.
This is done only for `wasmtime` since at this …
=> Catch panics on the FFI boundary between the runtime and the host for `wasmtime`

bin/node-template/node/src/command.rs, bin/node/cli/src/command.rs, client/finality-grandpa/src/lib.rs
Remove a couple of useless move instructions and a not required trait bound
=> Remove useless trait bound and `move` instructions

client/cli/src/arg_enums.rs, client/cli/src/commands/run_cmd.rs, client/cli/src/params/mod.rs, client/cli/src/params/network_params.rs, client/cli/src/params/node_key_params.rs, client/cli/src/params/offchain_worker_params.rs, client/cli/src/params/shared_params.rs, utils/frame/try-runtime/cli/src/lib.rs
Even though options values are internally converted to lowercase before being parsed, currently some CLI commands are shown in *CamelCase* while others in *kebab-case*.
This PR normalizes the format to (lower) *kebab-case* (e.g. "HelloWorld" => "hello-world").
Main motivations:
- project-wide coherence
- inline with how options are normally specified on other programs/tools found on Unix-like OSs
- faster to type (opinionated) :-)
---
Before
```
--execution <STRATEGY>
...
[possible values: Native, Wasm, Both, NativeElseWasm]
```
Now:
```
--execution <STRATEGY>
...
[possible values: native, wasm, both, native-else-wasm]
```
Before:
```
--scheme <SCHEME>
...
[possible values: Ed25510, Sr25519, Ecdsa]
```
Now:
```
--scheme <SCHEME>
...
[possible values: ed25510, sr25519, ecdsa]
```
Before …
=> Normalization of CLI options format (CamelCase => kebab-case)

frame/support/src/storage/bounded_vec.rs
Taken from https://github.com/paritytech/substrate/pull/11112 aims to reduce the size of the PR
=> add sort & try_append to bounded_vec

frame/staking/src/pallet/mod.rs
This PR is related to this [issue](https://github.com/paritytech/substrate/issues/11188). It updates the docs for the method [set_payee](https://github.com/paritytech/substrate/blob/994bb57b77b2845e9e1b48d8eb77c9160366d525/frame/staking/src/pallet/mod.rs#L1127) so that they reflect correctly when the changes from this function start to apply.
The same comment can also be found in the following methods : 
[validate](https://github.com/paritytech/substrate/blob/994bb57b77b2845e9e1b48d8eb77c9160366d525/frame/staking/src/pallet/mod.rs#L990) 
[nominate](https://github.com/paritytech/substrate/blob/994bb57b77b2845e9e1b48d8eb77c9160366d525/frame/staking/src/pallet/mod.rs#L1025) 
[chill](https://github.com/paritytech/substrate/blob/994bb57b77b2845e9e1b48d8eb77c9160366d525/frame/staking/src/pallet/ …
=> Updated docs for method `set_payee` & `set_controller`

Cargo.lock, client/api/src/client.rs, client/api/src/in_mem.rs, client/api/src/leaves.rs, client/consensus/babe/src/tests.rs, client/db/src/lib.rs, client/service/src/client/client.rs, client/service/test/src/client/mod.rs, primitives/blockchain/src/backend.rs, primitives/blockchain/src/header_metadata.rs
While looking into some problem on Versi where a collator seemed to be stuck. I found out that it
was not stuck but there was a huge gap between last finalized and best block. This lead to a lot
leaves and it was basically trapped inside some loop of reading block headers from the db to find
the stale heads. While looking into this I found out that `leaves` already supports the feature to
give us the stale heads relative easily. However, the semantics change a little bit. Instead of
returning all stale heads of blocks that are not reachable anymore after finalizing a block, we
currently only return heads with a number lower than the finalized block. This should be no problem,
because these other leaves that are stale will be returned later when a block gets finalized which
number is …
=> Finality notification: Optimize calculation of stale heads

.gitlab-ci.yml
The job `publish-docker-substrate` is currently broken because `build-linux-substrate` doesn't return version for this job. The PR fixes it. 
Tested in this PR: https://github.com/paritytech/substrate/pull/11214
Closes https://github.com/paritytech/ci_cd/issues/388
=> [ci] fix publish-docker-substrate job

client/cli/src/lib.rs
Otherwise, the compiler will complain if someone passes a type that
implements `CliConfiguration<DVC>` but `DVC` is not the default `()`.
=> Make the generic of CliConfiguration explicit

Cargo.lock, client/executor/wasmtime/Cargo.toml, frame/state-trie-migration/Cargo.toml, primitives/maybe-compressed-blob/Cargo.toml, primitives/runtime/Cargo.toml, primitives/wasm-interface/Cargo.toml, utils/frame/try-runtime/cli/Cargo.toml
I found nothing major in [release notes](https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md) that requires code changes,
`zstd` is used by `wasmtime-cache` internally and had to be updated to the same version.
polkadot companion: https://github.com/paritytech/polkadot/pull/5148
=> Update wasmtime to 0.35.3

frame/bounties/README.md, frame/bounties/src/lib.rs, frame/child-bounties/README.md, frame/child-bounties/src/lib.rs
Only comment changes, no logic impacted.
* Use uniform notion of parent and child, no "master" or "general" entity referenced.
* README updated to match comments.
=> Child bounties comments

bin/node/runtime/src/lib.rs, frame/election-provider-multi-phase/src/lib.rs, frame/election-provider-multi-phase/src/mock.rs, frame/election-provider-multi-phase/src/signed.rs, frame/election-provider-multi-phase/src/unsigned.rs
Fixes #11204 
As the issue describes, splitting `SolutionImprovementThresholds` into `BetterSignedThreshold` and `BetterUnsignedThreshold`.
Adding some tests to show case the difference.
@kianenigma 
##
Polkadot companion: paritytech/polkadot#5324
##
Polkadot address: 131dPecTmpTC1p1ofemufqFBJo9vNbV7dkgN7vWwKnaSMkC4
=> Split `SolutionImprovementThresholds` into two types

client/executor/common/src/sandbox.rs, client/executor/common/src/sandbox/wasmer_backend.rs, client/executor/common/src/sandbox/wasmi_backend.rs
This PR splits the `SandboxInstance::get_global_val` logic and moves it to corresponding backend modules.
Followup to #10563
=> Split `SandboxInstance::get_global_val` implementation per backend

client/beefy/src/gossip.rs, client/beefy/src/round.rs, client/beefy/src/worker.rs
Move gossip filter logging to level=trace because it's very spammy.
Move some debug-relevant logs from trace to debug.
=> adjust BEEFY client logging

client/api/src/client.rs, client/consensus/babe/src/lib.rs, client/consensus/babe/src/tests.rs
With the latest optimizations of the `FinalityNotification` generation, the aux data pruning started
to print a warning. The problem here was that we printed a warning and stopped the adding of blocks
to prune when we hit the `heigh_limit`. This is now wrong, as we could for example have two 512 long
forks and then we start finalizing one of them. The second fork head would be part of the stale
heads at some point (in the current implementation when we finalize second fork head number + 1),
but then we would actually need to go back into the past than `heigh_limit` (which was actually
last_finalized - 1). We now go back until we reach the canonical chain.
Also fixed some wrong comment that was added by be about the content of the `finalized` blocks in
the `FinalityNotification`.
Fixes one …
=> BABE: Fix aux data cleaning

frame/support/src/weights.rs
#10785 left me with impression that `ConstantMultiplier` implementation is too heavy for what is needed in that particular case, so I decided to apply small optimization to it and to `IdentityFee` to avoid going polynomial route since it is not necessary for those cases.
=> More efficient identity and multiplier weight to fee

client/api/src/client.rs, client/consensus/babe/src/lib.rs, client/consensus/babe/src/tests.rs
Backport of #11263 into the release branch `polkadot-v0.9.20`
With the latest optimizations of the `FinalityNotification` generation, the aux data pruning started
to print a warning. The problem here was that we printed a warning and stopped the adding of blocks
to prune when we hit the `heigh_limit`. This is now wrong, as we could for example have two 512 long
forks and then we start finalizing one of them. The second fork head would be part of the stale
heads at some point (in the current implementation when we finalize second fork head number + 1),
but then we would actually need to go back into the past than `heigh_limit` (which was actually
last_finalized - 1). We now go back until we reach the canonical chain.
Also fixed some wrong comment that was added by be about the content of …
=> BABE: Fix aux data cleaning (#11263)

Cargo.lock, client/tracing/Cargo.toml, client/tracing/src/logging/mod.rs
polkadot companion: https://github.com/paritytech/polkadot/pull/5393
This lowers the CPU overhead of our logging machinery when *any* `trace` log is enabled down to ~3% of what it is without any `trace` logs enabled.
The `tracing-log` crate has a bunch of relatively expensive filtering machinery which decides whether a given log should be printed out or not. This machinery has a fast path: if the current most verbose logging level is set to X then the logger can just reject every log which uses a more verbose level and skip the expensive checks.
For example, if we have set `RUST_LOG` to `foo=info,bar=warn` then the most verbose log level is `info`, so any `trace` logs can be quickly rejected because we know that a log *must* be at least `info` to be printable. Now, if we have set …
=> Turn on the logger's interest cache

Cargo.lock, client/executor/wasmi/Cargo.toml, fleet.toml
=> chore: remove unused scoped-tls

.gitlab-ci.yml, shell.nix, utils/frame/remote-externalities/src/lib.rs
The 2022-02-10 nightly can't build a dep we're pulling in:
There's a sig that returns `impl IntoIterator<Item = (&'static str, OsString)>` and an Option is being returned as the concrete implementation of the iterator but it's incorrectly not allowing a `?` in the method.
=> Updating shell.nix nightly

client/beefy/src/round.rs, client/beefy/src/tests.rs, client/beefy/src/worker.rs
BEEFY gadget should always use current validator set.
The gadget/client-voter was using previous' session validator set to sign the 1st block in the new session (to have chained validator set handoffs).
This is not necessary because:
1. BEEFY piggy-backs on GRANDPA and only works on canonical chain, so it need not concern itself with the validity of the block header (which contains digest with the new session's validator set). It can safely assume header is valid and simply use new validator set.
2. The BEEFY payload itself already contains a merkle root for the next validator set keys. So at the BEEFY-payload layer we already have a validated/trusted hand-off of authority.
BEEFY gadget should also buffer votes for blocks not yet finalized by GRANDPA.
Fixes …
=> BEEFY voter bugfixes

client/network/src/protocol.rs, client/network/src/service.rs
When passing reserved nodes only with a peer id it was failing with the `DuplicateBootnode` error.
Besides that there are some clean ups. We for example added the bootnodes twice to the `known_addresses`.
Closes: https://github.com/paritytech/substrate/issues/11345
=> sc-network: Do not return error on peer id only reserved nodes

.gitlab-ci.yml
Nightly pipelines use `paritytech/ci-linux:staging` image for ci in all jobs where the `CI_IMAGE` variable is used. In this PR I hardcoded `image:` for `cargo-check-nixos`
=> [ci] fix cargo-check-nixos for nightly pipeline

frame/bags-list/src/list/mod.rs, frame/staking/src/slashing.rs, frame/support/src/traits/misc.rs
I didn't do it quite delicately, but gets the job done for now. 
Open to an more flexible alternative, specially keeping `defensive!` flexible. 
take out of https://github.com/paritytech/substrate/pull/11013/files.
I changed one or two examples to demonstrate how it should be used.
=> allow defensive operations to take a proof

frame/contracts/src/benchmarking/mod.rs, frame/contracts/src/wasm/mod.rs, frame/contracts/src/wasm/runtime.rs
(_Needed for ink! 3.1 release_)
[ink#1242](https://github.com/paritytech/ink/pull/1242/) updates E2E tests to cover these functions, and should be merged into master right before the 3.1 ink release.
Hence this PR stabilizes them:
+ [`seal0`] `seal_contains_storage`
+ [`seal1`] `seal_set_storage`
=> [contracts] stabilize `seal_contains_storage`(v`seal0`) and `seal_set_storage` (v.`seal1`)

client/consensus/slots/src/slots.rs
This PR renames several related variables in `sc-consensus-slots` from `client` to `select_chain`, and the corresponding type parameter from `C` to `SC`.
This does not make any behavioral changes, it just corrects a bad name to prevent others from the confusion I faced today.
The trait bound applied was already `SelectChain` and only methods from this trait were used. So I'm pretty confident this is a correct rename. I don't know how the name `client` was originally chosen, but maybe it predates the introduction of the `SelectChain` trait?
=> sc-consensus-slots: rename `client` -> `select_chain`

.gitlab-ci.yml, Cargo.lock, scripts/ci/gitlab/pipeline/build.yml, scripts/ci/gitlab/pipeline/check.yml, scripts/ci/gitlab/pipeline/publish.yml, scripts/ci/gitlab/pipeline/test.yml
Attempt to divide `.gitlab-ci.yml` into several files. 
Part of https://github.com/paritytech/ci_cd/issues/325
=> [ci] Divide .gitlab-ci.yml into several files

Cargo.lock, bin/node-template/node/Cargo.toml, bin/node/cli/Cargo.toml, bin/node/rpc/Cargo.toml, client/beefy/rpc/Cargo.toml, client/consensus/babe/rpc/Cargo.toml, client/consensus/manual-seal/Cargo.toml, client/finality-grandpa/rpc/Cargo.toml, client/rpc-api/Cargo.toml, client/rpc-servers/Cargo.toml, client/rpc-servers/src/lib.rs, client/rpc/Cargo.toml, client/service/Cargo.toml, client/sync-state-rpc/Cargo.toml, frame/contracts/rpc/Cargo.toml, frame/merkle-mountain-range/rpc/Cargo.toml, frame/transaction-payment/rpc/Cargo.toml, utils/frame/remote-externalities/Cargo.toml, utils/frame/rpc/state-trie-migration-rpc/Cargo.toml, utils/frame/rpc/support/Cargo.toml, utils/frame/rpc/system/Cargo.toml, utils/frame/try-runtime/cli/Cargo.toml
Followup on https://github.com/paritytech/substrate/pull/8783 which adds the `HTTP health API` back.
polkadot companion: https://github.com/paritytech/polkadot/pull/5499
cumulus companion: https://github.com/paritytech/cumulus/pull/1253
=> jsonrpc http server: expose health endpoint

client/consensus/babe/src/tests.rs
This seems to be resolved: https://github.com/paritytech/substrate/issues/2532
=> Remove `#![allow(deprecated)]` that was fixed

bin/node/cli/tests/benchmark_machine_works.rs, client/sysinfo/src/sysinfo.rs, utils/frame/benchmarking-cli/src/machine/mod.rs
I ran the `benchmark machine` command some dozen times on the ref hardware and the `Blake2-256` seems to be the only failing one. It runs for only 100ms which is probably too short to get reproducible results.   
Changes:
- Increase benchmark durations
- Add arguments to control all durations
- Let `sc-sysinfo` return `f64` for more precision
- Add explicit default limits to `sc-sysinfo`
The benchmark worked 27 times in a row, then failed with 0.4% outside the tolerance for the disk benchmark. Should be good enough for now.
=> More `benchmark machine` args

frame/collective/src/lib.rs, frame/collective/src/tests.rs, frame/contracts/src/lib.rs, frame/contracts/src/migration.rs, frame/elections-phragmen/src/lib.rs, frame/grandpa/src/lib.rs, frame/membership/src/lib.rs, frame/session/src/historical/mod.rs, frame/session/src/lib.rs, frame/session/src/tests.rs, frame/support/src/lib.rs, frame/support/test/tests/pallet.rs, frame/tips/src/lib.rs, frame/tips/src/tests.rs, frame/vesting/src/lib.rs, frame/vesting/src/mock.rs
=> frame_support::pallet_prelude: reexport StorageVersion

Cargo.lock, bin/node/bench/Cargo.toml, bin/node/bench/src/tempdb.rs, bin/node/bench/src/trie.rs, client/authority-discovery/Cargo.toml, client/db/Cargo.toml, client/network-gossip/Cargo.toml, client/network/Cargo.toml, client/network/sync/Cargo.toml, client/offchain/Cargo.toml, client/offchain/src/api/http.rs
- update `hyper-rustls` to v0.23.0 (Close #11366)
- disable default-features of `derive_more` and `quickcheck`
=> Prune some duplicated dependencies in the dependency graph

client/network/sync/src/block_request_handler.rs
This PR is a small follow-up to #11084. That PR reduced the penalty for "small" block requests, such as requests performed as part of a common ancestor search, to avoid banning honest peers. However, that PR missed the fact that we would still return an error response on duplicate small requests. 
This leads to cases like:
1. Node A requests the header of block X
2. Node B responds successfully
(time passes)
3. Node A requests the header of block X (again)
4. Node B reduces A's reputation 
5. Node B returns an error for the request
6. Node A views the error as a refusal to fulfill the request
7. Node A bans B for refusing to fulfill its request
This PR makes it so we return a successful response on duplicate small block requests, preventing situations such as above.
=> Return a successful response on repeated small block request

client/sync-state-rpc/src/lib.rs
Backport of  #11437 
* fix: #11435
* address grumbles: better safe than sorry
polkadot companion branch: release-v0.9.22
=> fix: regression of `sync_state_genSyncSpec` #11435 (#11437)

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/test.yml
The PR adds DAG for jobs in the test stage. It optimises runner usage and doesn't affect the pipeline duration.
Close https://github.com/paritytech/ci_cd/issues/368
=> [ci] Adjust job order in pipeline test stage with Gitlab DAG

scripts/ci/gitlab/pipeline/build.yml
Related to https://github.com/paritytech/pipeline-scripts/issues/44
=> Disable check-dependent-cumulus

primitives/state-machine/src/trie_backend.rs, primitives/state-machine/src/trie_backend_essence.rs
Instead of iterating the entire state and collecting all keys that match the given prefix, we can
directly use the optimized prefix iterator.
=> trie: Optimize `keys` function

frame/staking/src/lib.rs
Currently, there is no 'non-hacky' way of getting the validator points per era. As users of the pallet-staking, we can have access to this information by using `EraRewardPoints` but since its fields are private we need to do some hacky shenanigans with encoding/decoding to be able to read it.
This pr makes it possible to get such information easier by making fields of the `EraRewardPoints` public.
=> Make fields of `EraRewardPoints` public

bin/node/runtime/src/lib.rs
Fixes some artefacts after the previous PR where we renamed `Class` to `Collection` and `Instance` to `Item`
=> Fix artifacts after Uniques renames

frame/contracts/fixtures/ecdsa_recover.wat, frame/contracts/src/benchmarking/mod.rs, frame/contracts/src/tests.rs, frame/contracts/src/wasm/mod.rs, frame/contracts/src/wasm/runtime.rs
Since *ink_waterfall* E2E tests were [added](https://github.com/paritytech/ink-waterfall/commit/f783b2149b5bf79484b1e236af8664fd3e02ebf1) (and being [diversified](https://github.com/paritytech/ink/pull/1268)) for
+ `seal_ecdsa_recover`
+ `seal_ecdsa_to_eth_address` 
we can now stabilize them
=> [contracts] Stabilize `seal_ecdsa_recover` and `seal_ecdsa_to_eth_address` functions

bin/node-template/node/src/rpc.rs, bin/node/rpc/src/lib.rs, client/beefy/rpc/src/lib.rs, client/consensus/babe/rpc/src/lib.rs, client/consensus/manual-seal/src/rpc.rs, client/finality-grandpa/rpc/src/lib.rs, client/rpc/src/state/mod.rs, client/sync-state-rpc/src/lib.rs, frame/contracts/rpc/src/lib.rs, frame/merkle-mountain-range/rpc/src/lib.rs, frame/transaction-payment/rpc/src/lib.rs, utils/frame/rpc/state-trie-migration-rpc/src/lib.rs, utils/frame/rpc/system/src/lib.rs
Different rpc api and impl naming is confusing, I'm not sure if I need to modify `sc-rpc` to be consistent, like
~~`Author` ==> `AuthorRpc`~~
~~`Chain` ==> `ChainRpc`~~
~~`System` ==> `SystemRpc`~~
~~`State` ==> `StateRpc`~~
~~`ChildState` ==> `ChildStateRpc`~~
~~`Offchain` ==> `OffchainRpc`~~
~~`Dev` ==> `DevRpc`~~
polkadot companion: https://github.com/paritytech/polkadot/pull/5569
=> Unify rpc api and implementation name

client/cli/src/params/network_params.rs
If `--validator` is passed we also listen on this address and as `--dev` is a shortcut for multiple
CLI args, including `--validator`, we should make it consistent.
Closes: https://github.com/paritytech/substrate/issues/11491
=> Make `--dev` listen by default on `/ip4/0.0.0.0/tcp/30333`

frame/state-trie-migration/src/lib.rs
This PR fixes the error:
```
2022-05-22 13:03:47 [0] 💸 generated 1 npos voters, 1 from validators and 0 nominators    
Error: Input("SignedMigrationNotAllowed")
```
=> Fix State Trie Migration Benchmarks

Cargo.lock, client/executor/wasmtime/Cargo.toml, client/executor/wasmtime/src/runtime.rs, client/executor/wasmtime/src/tests.rs
Instead of always using a hardcoded limit of 4096 pages when using the pooling instantiation strategy this PR makes it so that it is:
1) set to be equal to `max_memory_size` (for PVFs), 
2) set to the the maximum possible value (for the normal runtime); technically we could calculate exactly how much is necessary here and set it to exactly that value, but considering that we want to support dynamic heap growth in the future we'd have to set it higher than necessary anyway, so it's better to just go with the maximum value now and see whether it has any practical downsides (if it does we can just adjust it to a more "reasonable" maximum later)
Setting this to a higher value than necessary mostly only affects how much address space is reserved for the memfd internally allocated by `wasmtime` …
=> Adjust maximum memory pages hard limit for the pooling instantiation strategy

scripts/ci/gitlab/pipeline/build.yml
[pipeline-script](https://github.com/paritytech/pipeline-scripts/blob/b8942cb0cc19cf587e0a6019486b87894f955572/check_dependent_project.sh#L489) will be executed only for PR branches, otherwise it will fail. Adjusted `check-dependent-polkadot` rules to run this job only for PR's.
=> CI adjust job `check-dependent-polkadot` rules

client/consensus/babe/src/lib.rs, client/consensus/babe/src/tests.rs
This PR fix an error condition triggered when the last finalized block is equal to the best block.
Fail scenario can be easily reproduced by issuing a double revert from the CLI:
- 1st revert => to set the best block equal to last finalized
- 2nd revert => removes the weight of the last finalized block **<=== BAD**
This PR prevents removal of weight data of last finalized block
=> Fix Babe revert when last finalized block is a leaf

utils/fork-tree/src/lib.rs
Closes https://github.com/paritytech/polkadot/issues/5556
After a warp-sync, the error condition was triggered by the absence of the parent node of the first imported block.
To elaborate, some users of this method (i.e. consensus epoch changes tree) currently silently rely on a **POST-ORDER DFS** traversal of the tree.
If we are using instead a top-down traversal method then  the `is_descendent_of` closure, when used after a warp-sync, will end up querying the backend for a block (the one corresponding to the root) that is not present and thus will return a wrong result. 
In the last iterative implementation we started using a **pre-order** DFS instead, thus triggering the error condition.
This fairly strong assumption has been documented within the code with a **big fat warning**
=> Fix node lookup on fork-tree after a warp-sync

.github/allowed-actions.js, .github/workflows/mlc_config.json
Github no longer checks the allowed actions this way.
We can whitelist them in the [settings](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization) instead.
cc https://github.com/paritytech/ci_cd/issues/79
=> CI: github no longer checks whitelisted actions this way

utils/fork-tree/src/lib.rs
Follow up of https://github.com/paritytech/substrate/pull/11476
Has been observed that the ForkTree `import` requires a post-order DFS traversal.
This PR replaces the pre-order traversal that were introduced by https://github.com/paritytech/substrate/pull/11228
=> Fork-Tree import requires post-order DFS traversal

frame/contracts/README.md
dead _https://docs.rs/_ links replaced with alive _https://paritytech.github.io/_  ones
=> [contracts] Fix broken links in README.md

frame/support/src/storage/transactional.rs
with_transaction() function can not be used with explicit generic arguments because of this issue: https://github.com/rust-lang/rust/issues/83701
It seems inconvenient if one need to specify particular error type, for instance.
=> change impl FnOnce() to generic type + trait bound

frame/nomination-pools/src/lib.rs, frame/nomination-pools/src/tests.rs, frame/support/procedural/src/lib.rs, frame/support/src/dispatch.rs, frame/support/test/tests/storage_transaction.rs
Changes:
- Mark `#[transactional]` as deprecated since it is the default after #11431
- Clean up left over usage
- Update docs
=> Clean up `#[transactional]`

frame/collective/src/lib.rs, frame/society/src/lib.rs, frame/support/src/traits/dispatch.rs, frame/system/src/lib.rs, frame/treasury/src/tests.rs, primitives/runtime/src/traits.rs
Better to return an error than panic since otherwise origin-combinators like `EitherOf` cannot choose one over another.
Also introduce `MapSuccess` and `TryMapSuccess` for creating an derivative origin guards which change another's the success value.
=> Introduce `EnsureOrigin::try_successul_origin`

client/network/sync/src/lib.rs
When we still have a full import queue, we should still report that we are in major sync mode,
otherwise validators may will already start producing blocks.
Closes: https://github.com/paritytech/substrate/issues/11510
=> Sync: Improve major sync detection

bin/node-template/README.md
The lorri repository has moved from https://github.com/target/lorri to
https://github.com/nix-community/lorri.
=> Fix link in node-template README

frame/offences/src/lib.rs
This is a small PR that relaxes the requirements on the `IdentificationTuple` at the `pallet_offences`.
There seems to be no need for it, as the pallet checks just fine, and it's an issue for our implementation at Humanode as our `IdentificationTuple` doesn't implement `Ord`.
FYI @dmitrylavrenov
=> Do not require Ord for pallet_offences::Config::IdentificationTuple

scripts/ci/gitlab/pipeline/test.yml
I'm not sure why it's the only job that handles logs in case of failures in such way, we have a strong proof as per @gavofyork's comment on `#cicd:matrix.parity.io` that such behavior confuses people.
cc @TriplEight @alvicsam
=> Don't limit `test-linux-stable-int` job output

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/build.yml, scripts/ci/gitlab/pipeline/test.yml
* Supress `rusty-cachier` output for `rusty-cachier snapshot destroy` command to stop emitting stack traces in case of a graceful failure
* Don't hardcode `CARGO_TARGET_DIR` paths
* Adopt `test-deterministic-wasm` job for `rusty-cachier`
=> `rusty-cachier` pipeline impovements and fixes

frame/aura/src/lib.rs
Since some apis in grandpa such as `schedule_change` is `pub`.  And so is `babe`.
Should Aura export these apis such as `change_authorities`
=> aura: export change_authorities and initialize_authorities

frame/referenda/src/benchmarking.rs, frame/referenda/src/lib.rs, frame/referenda/src/mock.rs, frame/referenda/src/tests.rs, frame/support/procedural/src/construct_runtime/expand/call.rs
Also add a couple of helper functions for discovering which pallet is bloating the call size.
=> Reduce call size of Referenda pallet

client/transaction-pool/src/lib.rs
This is required to make a tx pool wrapper for some custom transaction validation, specifically
required to make a wrapper around the `LocalTransactionPool` implementation (https://github.com/subspace/subspace/blob/f54881a9b5/crates/subspace-service/src/pool.rs#L232-L269).
There probably is some other nicer way to make a tx pool wrapper but this can be the quickest one with minimal changes to make it possible.
Related: https://github.com/paritytech/substrate/discussions/11520
=> Expose ValidatedTransaction from transaction pool

frame/remark/src/lib.rs
=> Remove `#[pallet::without_storage_info]` for pallet-remark

frame/ranked-collective/src/lib.rs
Simple Max Encoded Len for Ranked Collective Pallet.
=> MEL for Ranked Collective

frame/support/src/storage/bounded_vec.rs
I was wondering why `BoundedSlice::try_from` was failing even though the number of items I was passing to it was exactly the maximum length, and it seems like there's an off-by-one bug here where it actually enforces `max - 1` instead of `max`. (The `Vec::try_from` works as expected, as illustrated by the test I've added.)
=> Fix one-by-off in `BoundedSlice::try_from`

frame/support/src/storage/bounded_btree_map.rs, frame/support/src/storage/bounded_btree_set.rs, frame/support/src/storage/bounded_vec.rs, frame/support/src/storage/weak_bounded_vec.rs
Per title, this PR implements `IntoIterator` for references of the bounded types, so that you can use the `for foo in &bar` or `for foo in &mut bar` syntax to iterate on references and mutable references of the elements.
=> Implement more IntoIter traits for bounded types

frame/membership/src/lib.rs
My first naive approach to remove `without_storage_info` from membership pallet. 
Part of #8629
Changes:
- Members are now stored in a BoundedVec and `MaxMembers` is enforced
- I think MaxMembers is currently 100, is that reasonable?
=> Remove `without_storage_info` for membership pallet

bin/utils/subkey/src/lib.rs, client/cli/src/commands/generate_node_key.rs, client/cli/src/commands/inspect_node_key.rs, client/cli/src/commands/key.rs
Closes https://github.com/paritytech/substrate/issues/11518
---
This PR wants to improve the user experience of `subkey` by expanding a bit the possibilities offered by Substrate's `InspectNodeKeyCmd` and `GenerateNodeKeyCmd`.
---
The command has been extended to allow the user to:
- write the output in binary format (added `--bin` flag). Default is hex string as before.
The command has been extended to allow the user to:
- read the input in binary format (added `--bin` flag). Default is hex string as before.
Now is also easier to parse the node key file under the `network` folder (when auto-generated at node startup, this is stored in raw binary format).
- the file input is now optional (as it is for key generation), if the file is not passed the key is read from stdin.
- some tolerance …
=> Improve inspection and generation of node keys

client/transaction-pool/api/src/lib.rs, client/transaction-pool/src/error.rs
This trivial change makes debugging experience so much nicer by turning this:
```
2022-06-10 04:44:12 (offchain call) Error submitting a transaction to the pool: Transaction pool error
```
Into this:
```
2022-06-10 04:44:12 (offchain call) Error submitting a transaction to the pool: Transaction pool error: Transaction cannot be propagated and the local node does not author blocks
```
=> Better transaction pool error

frame/aura/src/lib.rs
=> Use BoundedVec in aura pallet

frame/uniques/README.md
**Changes only in README**
I fix three links of the `pallet_uniques` readme. 
It seems that there's no such crate on docs.rs: https://docs.rs/releases/search?query=pallet+uniques
=> pallet uniques: fix broken docs link

primitives/runtime/src/bounded/bounded_btree_map.rs, primitives/runtime/src/bounded/bounded_btree_set.rs, primitives/runtime/src/bounded/bounded_vec.rs, primitives/runtime/src/bounded/weak_bounded_vec.rs
Surprised that this wasn't in yet.
=> Implement PartialOrd and Ord on BoundedSlice and WeakBoundedVec

primitives/runtime/src/bounded/bounded_btree_map.rs, primitives/runtime/src/bounded/bounded_btree_set.rs, primitives/runtime/src/bounded/bounded_vec.rs, primitives/runtime/src/bounded/weak_bounded_vec.rs
There is a lot of stupid happening witih these trait impls.
=> Properly implement Debug on bounded types

client/beefy/rpc/src/lib.rs, client/finality-grandpa/rpc/src/lib.rs
I have been able reproduce that these tests "sometimes" fails locally when running all the tests with nextest but I haven't found the root cause. Most likely some kind of race-condition but I haven't been able to determine the root cause.
My best guess is that the underlying stream was terminated somehow but not really familiar how those notifications work but ofc can be a jsonrpsee bug as well.
I propose that we remove these flaky tests mainly because these are already tested in the jsonrpc library itself and doesn't really test any specific logic in the RPC module.
=> remove flaky rpc subscription tests

frame/authorship/src/lib.rs
Part of https://github.com/paritytech/substrate/issues/8629
From what I can see the authorship pallet was already implicitly bounded since the maximum amount of uncles it accepts in `set_uncles` is bounded by the `MAX_UNCLES` constant, and the maximum number of generations for which it stores these uncles is specified by `Config::UncleGenerations`. So this PR should not change the behavior in any way and impose any additional limits which weren't previously there.
Marking as `D3-trivial` but feel free to change it if you think this needs an audit.
=> Remove `without_storage_info` for the authorship pallet

Cargo.lock, frame/collective/src/lib.rs, frame/conviction-voting/Cargo.toml, frame/conviction-voting/src/lib.rs, frame/conviction-voting/src/types.rs, frame/conviction-voting/src/vote.rs, frame/ranked-collective/src/lib.rs, frame/referenda/Cargo.toml, frame/referenda/src/lib.rs, frame/support/procedural/src/construct_runtime/expand/origin.rs, frame/support/src/dispatch.rs, frame/support/src/traits.rs, frame/support/src/traits/dispatch.rs, frame/support/src/traits/schedule.rs, frame/support/src/traits/voting.rs, frame/support/test/tests/construct_runtime.rs, frame/support/test/tests/instance.rs, frame/support/test/tests/origin.rs, frame/support/test/tests/pallet.rs, frame/support/test/tests/pallet_instance.rs, primitives/core/src/lib.rs, test-utils/runtime/src/lib.rs
This puts a `MaxEncodedLen` bound on `PalletsOrigin` trait and fixes Referenda and ConvictionVoting pallets.
polkadot companion: paritytech/polkadot#5671
cumulus companion: paritytech/cumulus#1363
=> MEL: Origin, Referenda, ConvictionVoting

frame/executive/src/lib.rs
I do not know wether compiler could optimize it, So I think we could reduce one more `encode` call manually.
=> chore: reduce uxt encode times

frame/support/procedural/src/storage_alias.rs, frame/support/test/tests/storage_alias_ui.rs, frame/support/test/tests/storage_alias_ui/checks_for_valid_storage_type.rs, frame/support/test/tests/storage_alias_ui/checks_for_valid_storage_type.stderr, frame/support/test/tests/storage_alias_ui/forbid_underscore_as_prefix.rs, frame/support/test/tests/storage_alias_ui/forbid_underscore_as_prefix.stderr, frame/support/test/tests/storage_alias_ui/prefix_must_be_an_ident.rs, frame/support/test/tests/storage_alias_ui/prefix_must_be_an_ident.stderr
Besides that it also adds some UI tests.
=> `storage-alias`: Check that prefix is not an underscore

scripts/ci/gitlab/pipeline/build.yml
The script executed by check-dependent-cumulus only works for PRs, as shown in https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/1630771#L87, which comes from https://github.com/paritytech/pipeline-scripts/blob/3ad10ddc0d985ef5326974a1143229c6429befab/check_dependent_project.sh#L443
=> check-dependent-cumulus should only be executed for PRs

client/beefy/src/worker.rs, client/network-gossip/src/bridge.rs
Fixes https://github.com/paritytech/substrate/issues/11604
This fixes a memory leak when the BEEFY gadget is turned on in the client, but the runtime doesn't actually use BEEFY.
See this comment here for details: https://github.com/paritytech/substrate/issues/11604#issuecomment-1158752943
Marking as `C3-medium` since it apparently affects a lot of parachains (assuming it's the same memory leak); feel free to change it if you disagree.
=> Pump the gossip engine while waiting for the BEEFY runtime pallet (memory leak fix)

frame/support/src/traits/misc.rs
This ensures that there isn't any extra data attached that isn't used.
=> WrapperOpaque: Use `decode_all` to decode from the `Vec<u8>`

bin/node/runtime/src/lib.rs
The `DeletionQueue` storage item housed by `pallet_contracts` was bounded to have `157977` items of 128 byte each. The size was chosen before storage needed to be bounded to be as large as possible. There is no reason for it to be that large. We just set it to 128 which allows us to have 128 contracts queued for deletion at any time in point. Please note that we assume that the deletion of a contract is a rare occasion anyways.
This reduces the max encoded length of the item from 19MiB to 16KiB.
=> contracts: Reduce size of deletion queue depth

client/consensus/epochs/src/lib.rs
Fixes #11526.
Before this PR the condition for checking whether a given epoch should be added to the gap or not was whether all currently imported epochs were genesis epochs. This is not correct since if we have a genesis epoch still in the tree with another epoch descending from it we also don't want to use the gap. The condition was changed such that as long as there's still one genesis epoch in the tree we will not use the gap.
This bug was very unlikely to be triggered as it required forks happening while having short epoch durations, such that finality wouldn't be fast enough to prune old genesis epochs from the tree. It surfaced on the zombienet tests where these conditions applied.
=> epochs: don't use gap when there's at least one genesis epoch imported

Cargo.lock, client/executor/wasmtime/Cargo.toml, client/executor/wasmtime/src/imports.rs, client/executor/wasmtime/src/runtime.rs, frame/state-trie-migration/Cargo.toml, primitives/maybe-compressed-blob/Cargo.toml, primitives/runtime/Cargo.toml, primitives/wasm-interface/Cargo.toml, utils/frame/try-runtime/cli/Cargo.toml
polkadot companion: https://github.com/paritytech/polkadot/pull/5707
This PR bumps `wasmtime`'s version to 0.37.0. 
It has some performance improvements. Up to 25% lower instantiation overhead:
```
call_empty_function_from_kusama_runtime_with_pooling_cow_fresh_on_1_threads
time:   [7.1653 us 7.1711 us 7.1774 us]
change: [-26.824% -26.436% -26.018%] (p = 0.00 < 0.05)
Performance has improved.                                                                                                
call_empty_function_from_kusama_runtime_with_pooling_cow_fresh_on_2_threads
time:   [16.442 us 16.740 us 17.046 us]
change: [-19.829% -18.164% -16.341%] (p = 0.00 < 0.05)
Performance has improved.
call_empty_function_from_kusama_runtime_with_pooling_cow_fresh_on_4_threads
time:   [28.369 us 28.550 us 28.737 …
```
=> Bump `wasmtime` to 0.38.0 and `zstd` to 0.11.2

client/consensus/common/src/import_queue.rs, client/network/sync/src/blocks.rs, client/network/sync/src/lib.rs
Currently, duplicate block requests are sent if a node is on a fork and starts syncing with a peer, where our node's best block number is greater than our common block number. In this case, our `best_queued_number` is greater than the common block number, so when we receive the first block response we:
1. Clear the peer download
2. Insert the downloaded block range as `Complete` in the block collection
3. We `drain_blocks` up to `best_queued_number+1` which removes the just-downloaded set of blocks from the block collection
4. We  queue the blocks for import
5. When we make our next set of block requests, our common block number hasn't changed because the blocks haven't been processed yet, so in `needed_blocks` we find that the block collection is empty, and so we think we still need to …
=> Avoid a duplicate block request when syncing from a fork

frame/nomination-pools/src/lib.rs, frame/nomination-pools/src/mock.rs
Fixed the error that occurred during ```pallet-nomination-pools``` compilation.
The error message was: ```not a member of trait `sp_staking::StakingInterface```, this referred to the ```nominations``` function.
=> nomination-pools fix

frame/contracts/common/src/lib.rs, frame/contracts/src/exec.rs
During the implementation of `delegate_call`, the case with the transfer of native token was missed.
If you transfer tokens to a call that does `delegate_call` inside, it causes a double-spend(or more if there are many delegate calls).
It is because for `delegate_call` we add a new frame(like for standard call) and pass `value` inside. On each new frame, we transfer tokens to the contract's account.
The fix is not to transfer tokens for frames caused by delegate calls.
=> [contracts] Fixed the bug with transfer value for delegate call

client/network/sync/src/blocks.rs, client/network/sync/src/lib.rs
There's an issue introduced in #11094
The code there expects that batches of import notifications coming from the client will match batches in which the blocks were downloaded, which is not the case in general. This leads to blocks stuck in the `Queued` state.
This PR fixes the issue by making sure each hash is checked for `Queued` status, and not just the first one.
=> Fix clearing queued blocks in the sync module

client/finality-grandpa/src/voting_rule.rs
This is useful for [malus](https://github.com/paritytech/polkadot/blob/master/node/malus/README.md) and zombienet tests in polkadot to test scenarios with delayed finality.
=> expose grandpa BeforeBestBlockBy voting rule

frame/nomination-pools/src/lib.rs, frame/support/procedural/src/lib.rs
Community has said there is still use for this macro, especially for easily placing some logic into its own transactional layer.
No reason to deprecate it.
=> Un-deprecate Transactional Macro

frame/nomination-pools/src/lib.rs, frame/support/procedural/src/lib.rs
https://github.com/paritytech/substrate/pull/11807
=> Backport #11807

client/network/sync/src/blocks.rs, client/network/sync/src/lib.rs
Fixes another issue introduced in #11094
`queued_blocks` records ranges using `from`, which can be arbitrary. Sync calls this function with `from` set to current best block to make sure no blocks will be returned if there's a gap in the downloaded ranges. The correct way to record a returned range here is using `start` rather than `from`.  Furthermore, all ranges need to be recorded and not just the first one.
Fixes #11812
=> sync: Fixed clearing subsequent ranges

bin/node/cli/benches/transaction_pool.rs, client/cli/src/commands/run_cmd.rs, client/cli/src/config.rs, client/cli/src/params/transaction_pool_params.rs, client/transaction-pool/src/graph/pool.rs, client/transaction-pool/src/graph/rotator.rs, client/transaction-pool/src/graph/validated_pool.rs
New CLI flag `--tx-ban-seconds` to configure transaction ban duration. Defaults to 1800s which is the current default value.
If not explicitly specified and `--dev` is used, the value will be set to 0.
Closes #9921
cumulus companion: https://github.com/paritytech/cumulus/pull/1436
=> CLI flag to configure tx ban duration

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/test.yml
Currently `cancel-pipeline` job doesn't work as intended. It waits until all needed job fail instead of cancelling pipeline if only one job fails. The PR fixes this issue.
=> [ci] fix job `cancel-pipeline`

.gitlab-ci.yml
This PR implements [the spec described here](https://github.com/paritytech/ci_cd/issues/506#issuecomment-1180661449):
* Use lightweight image for the `rusty-cachier-notify` job
* Skip all Git operations
* Run the job on the Kubernetes runner
=> Speed up `rusty-cachier-notify` job

Cargo.lock, client/tracing/Cargo.toml, client/tracing/src/logging/mod.rs, primitives/io/Cargo.toml, primitives/runtime-interface/test/Cargo.toml, primitives/tracing/Cargo.toml
The feature is currently broken with the latest `tracing-core`. We will enable it again, when it is
fixed upstream.
=> Disable the interest cache

.gitlab-ci.yml
A small follow-up to the https://github.com/paritytech/substrate/pull/11841.
=> Don't download artifacts into the `rusty-cachier-notify` job

client/cli/src/commands/run_cmd.rs, client/cli/src/config.rs, client/finality-grandpa/src/communication/gossip.rs, client/network/src/config.rs, client/network/src/protocol/message.rs, client/network/src/service.rs, client/network/src/transactions.rs, client/rpc-api/src/system/helpers.rs, client/service/src/builder.rs, client/service/src/lib.rs, client/service/src/metrics.rs
This PR removes the `--light` CLI option and cleans up the left-overs of the light client in substrate.
polkadot companion: https://github.com/paritytech/polkadot/pull/5794
cumulus companion: https://github.com/paritytech/cumulus/pull/1456
=> Cleanup light client leftovers

scripts/ci/gitlab/pipeline/build.yml
Currently docs are generated with dependencies and `target/doc/` has 2.4 GB size. Github pages don't support projects > 1GB.
PR removes dependencies from build in `build-rustdoc`
Part of https://github.com/paritytech/ci_cd/issues/503
Part of https://github.com/paritytech/ci_cd/issues/476
=> [ci] Generate rustdocs without dependencies

client/network/src/service.rs
This PR addresses https://github.com/paritytech/substrate/issues/8868
In fact, the error message had been already changed and before this PR was
```
💔 The bootnode you want to connect provided a different peer ID than the one you expect: `12D3KooWM8UexU7U2d8BSmYgpdxu7m27C7xGaTXFn3tB7GxVTQKF` with `12D3KooWRuSueDqdQ1eVRnN2uoUr7r4XF1u9HAMdiSVWDm8Jqmz4`:`Dialer { address: "/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWM8UexU7U2d8BSmYgpdxu7m27C7xGaTXFn3tB7GxVTQKF", role_override: Dialer }`.
```
This PR makes it slightly more clear:
```
💔 The bootnode you want to connect to at `/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWM8UexU7U2d8BSmYgpdxu7m27C7xGaTXFn3tB7GxVTQKF` provided a different peer ID `12D3KooWRuSueDqdQ1eVRnN2uoUr7r4XF1u9HAMdiSVWDm8Jqmz4` than the one you expect …
```
=> Clarify wrong bootnode peer ID error message

frame/support/src/weights.rs, frame/system/src/lib.rs, frame/system/src/tests.rs
**Wrong stored pays_fee attribute on Extrinsic events**
lets say, I have a dispatch call with `#[pallet::weight((500_000, Pays::Yes))]`, when I try to do a correction (https://docs.substrate.io/main-docs/build/tx-weights-fees/#post-dispatch-weight-correction) with different `pays_fee`, for example return with `Ok(Pays::No.into())`  or `Ok((Some(2_500_000), Pays::No).into())` or with
```
ensure!(
name_len < 10,
DispatchErrorWithPostInfo {
post_info: PostDispatchInfo {
actual_weight: Some(5_000_000),
pays_fee: Pays::No
},
error: Error::<T>::InvalidParameter(InvalidParameterDetails {
max: 9,
actual: name_len as u8
})
.into()
}
);
```
I can see in `polkadot.js.org` block explorer, that `transactionPayment.TransactionFeePaid` is zero or some value according to `Pays::Yes/No`, looks ok as …
=> Fix for 'note_applied_extrinsic' - consider also actual pays_fee

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/test.yml
The PR fixes `node-bench-regression-guard` job. After the `cargo-check-benches` job was parallelised  `node-bench-regression-guard` job couldn't collect artifacts from master.
=> [ci] fix node-bench-regression-guard job

client/api/src/leaves.rs
Apparently `pending_added` and `pending_removed` fields of `LeafSet` are leftovers from the past.
Previously used to construct a db transaction and introduced here: https://github.com/paritytech/substrate/pull/1338
Their active usage terminates here: https://github.com/paritytech/substrate/pull/5549
---
Fix `Undo<&LeafSet>::undo_import` method: old leaf should be inserted using the old number 
---
Fix `LeafSet::count`: old implementation was counting the number of levels. There can be multiple leaves for each level and if the semantics is to count the number of leaves then this was not correct.
=> Remove unused leaves-set fields

frame/contracts/fixtures/chain_extension.wat, frame/contracts/fixtures/chain_extension_temp_storage.wat, frame/contracts/src/chain_extension.rs, frame/contracts/src/lib.rs, frame/contracts/src/tests.rs, frame/contracts/src/wasm/runtime.rs
Previously, `ChainExtension:call()` didn't had access to `self`. Mainly because it wasn't clear what the lifetime (when is it created and droped) of such a value would be.
Turned out that a useful lifetime for this value is per-call (not per call stack). This allows chain extensions to hold some temporary values within a single call. The need for this came up during implementation of an XCM chain extension. This PR therefore introduces two changes:
This PR changes the interface of `ChainExtension` and hence it will break the build of existing extensions.  Extensions authors need to be aware of the following changes:
Just add `mut &self` to your existing chain extensions' `call` functions. This is all that needs to be done.
Pre-existing chain extensions are probably unit structs and hence …
=> contracts: Allow `ChainExtension::call()` to access `&mut self`

Cargo.lock, client/beefy/Cargo.toml, frame/election-provider-multi-phase/Cargo.toml, primitives/core/Cargo.toml, primitives/core/src/ecdsa.rs, primitives/io/Cargo.toml, primitives/keyring/Cargo.toml, utils/frame/benchmarking-cli/Cargo.toml, utils/wasm-builder/Cargo.toml
update some dependencies to pruned duplicated dependencies
- update `comfy-table` v0.5.1 => v6.0.0
- update `strum` v0.23.0  => v0.24.1
- update `h2` v0.3.9 => v0.3.13
- update `file-per-thread-logger` v0.1.4 => v0.1.5
- update `mio` v0.8.0 => v0.8.4
- update `secp256k1` v0.21.2 => v0.24.0
polkadot companion: https://github.com/paritytech/polkadot/pull/5808
=> Pruned duplicated dependencies

.gitlab-ci.yml
`production` image with latest rust stable and nightly was published, changing it back in ci
cc https://github.com/paritytech/ci_cd/issues/535
=> [ci] Return production image

frame/nomination-pools/src/tests.rs, frame/support/procedural/src/construct_runtime/expand/call.rs, frame/support/procedural/src/pallet/expand/call.rs, frame/support/src/dispatch.rs, frame/support/src/traits.rs, frame/support/src/traits/dispatch.rs
This PR simplifies the use of the Transactional Storage APIs introduced in https://github.com/paritytech/substrate/pull/11431
The creation of a new storage layer is trivial enough that it can just be enabled by default, and thus avoid the use of `in_storage_layer`, and the need for a `DispatchWithStorageLayer` traits.
This also makes it more clear exactly what happens when you dispatch a call, no matter if you are already in a dispatchable or not.
=> Make New Storage Layer Truly Default

Cargo.lock, client/consensus/babe/Cargo.toml, client/consensus/babe/src/lib.rs, client/transaction-pool/Cargo.toml, client/transaction-pool/src/graph/validated_pool.rs
Crate `retain_mut` was throwing errors on CI. Since we are now on 1.62, `retain_mut` is built-in and we can remove the crate.
=> Remove `retain_mut` crate

frame/staking/src/lib.rs, frame/staking/src/migrations.rs
A small fix to the migration of https://github.com/paritytech/substrate/pull/11823
Problem: If some slashes already exist in `UnappliedSlashes`, they will probably never be triggered in the new logic, since we lookup only a specific key of this map at the beginning of the era.
Solution: Try and apply all pending slashes one last time before going to the new logic. 
What I have written now in code is not ideal, but good enough that under normal conditions we survive. If an attacker wants to create more than 512 slash reports or such, it still needs a manual intervention.
=> Fix slashing migration to v10

frame/staking/src/lib.rs, frame/staking/src/migrations.rs
Backport of #11924 to the 0.9.27 release branch
* Fix slashing migration to v10
* add some logs
* Fix default version
* fmt
* Move doc to struct
Co-authored-by: Wilfried Kopp <wilfried@parity.io>
Thank you for your Pull Request! 🙏
Before you submit, please check that:
- What important points should reviewers know?
- Any panickers in the runtime have a proof or were removed.
After …
=> Backport #11924: Fix slashing migration to v10

frame/alliance/src/lib.rs, frame/alliance/src/mock.rs
Discovered this while testing on Westend: Someone joined the Alliance as an `Ally` before the set was initialized by Root. [This caused](https://github.com/paritytech/substrate/blob/bf467e6e08c0e8297af7fa53d0842a5103833df6/frame/alliance/src/lib.rs#L627) the Root call to fail. This PR prevents accounts from joining as Allies until the Alliance gets initialised.
---
I also considered another implementation option of changing the `init_members` function like so:
```rust
ensure!(
!Self::has_member(MemberRole::Founder) &&
!Self::has_member(MemberRole::Fellow) &&
//	!Self::has_member(MemberRole::Ally), <- remove this line
Error::<T, I>::MembersAlreadyInitialized
);
for member in founders.iter().chain(fellows.iter()).chain(allies.iter()) {
Self::has_identity(member)?; …
```
=> Require Alliance Initialisation Before Joining

scripts/ci/gitlab/pipeline/publish.yml
Fix https://github.com/paritytech/opstooling/issues/111
Example of PR: https://github.com/substrate-developer-hub/substrate-node-template/pull/363
Pipeline-script: https://github.com/paritytech/pipeline-scripts/pull/71
=> Integrate automatic update of substrate-node-template

client/network/src/protocol.rs
This PR addresses https://github.com/paritytech/substrate/issues/10800
Probably, similar logic should be implemented for user protocols (non-default peer sets) in polkadot.
=> Always allocate slots for reserved nodes

bin/node-template/runtime/src/lib.rs
Changes the link to the documentation to use a new path.
=> Update the link to the runtime versioning topic

scripts/ci/gitlab/pipeline/test.yml
The `production` ci image now contains `cargo-nextest` so there is no need to install it additionally.
Closes https://github.com/paritytech/ci_cd/issues/334
=> [ci] chores: remove cargo install nextest

frame/babe/src/equivocation.rs, frame/grandpa/src/equivocation.rs, frame/im-online/src/lib.rs, frame/im-online/src/tests.rs, frame/offences/benchmarking/src/lib.rs, frame/offences/src/lib.rs, frame/offences/src/mock.rs, primitives/staking/src/offence.rs
A use-case for this is to be able to have slash_fraction parameters derived from runtime configuration and read this config once and in the right context: https://github.com/paritytech/polkadot/pull/5535#discussion_r933528750.
=> offences: make fn slash_fraction non-static

client/network/src/protocol.rs
Hotfix to https://github.com/paritytech/substrate/pull/11938
polkadot companion: https://github.com/paritytech/polkadot/pull/5849
=> `sync` protocol now can have negotiated fallback name

client/rpc-api/src/system/helpers.rs, client/rpc/src/system/tests.rs, client/service/src/lib.rs
Before `highestBlock` was an optional that was omitted when it was `None`. We recently changed the
way the `highestBlock` is determined, this resulted in having this value in 99.99% of the time being
`None` when the node is syncing blocks at the tip. Now we always return a block for `highestBlock`.
If sync doesn't return us any best seen block, we return our own local best block as `highestBlock`.
This should mainly reflect the same behavior to before we changed the way the best seen block is determined.
Closes: https://github.com/paritytech/polkadot/issues/5860
=> system_syncState: Always return highest block

bin/node/cli/benches/block_production.rs, bin/node/cli/benches/transaction_pool.rs, bin/node/testing/src/bench.rs, client/cli/src/commands/chain_info_cmd.rs, client/cli/src/config.rs, client/cli/src/params/pruning_params.rs, client/db/src/lib.rs, client/network/test/src/lib.rs, client/network/test/src/sync.rs, client/service/src/builder.rs, client/service/src/config.rs, client/service/src/lib.rs, client/service/test/src/client/mod.rs, client/service/test/src/lib.rs, client/state-db/src/lib.rs, test-utils/client/src/lib.rs
This PR is renaming flags  `--keep-blocks` and `--prunning` to `--blocks-pruning` and --state-prunning` accordingly. This makes the flags similar to each other and avoids confusion.
Fixes #11907
polkadot companion: https://github.com/paritytech/polkadot/pull/5863
cumulus companion: https://github.com/paritytech/cumulus/pull/1514
=> Rename --pruning and --keep-blocks to be more similar to one another

frame/contracts/src/chain_extension.rs, frame/contracts/src/tests.rs
It should mask the least 16bit as the doc comment said.
=> pallet-contracts: Fix 16bit func_id

frame/contracts/src/wasm/runtime.rs
This applies the current depth limit of 256 to the decoding in `pallet-contracts` of contract generated data. We do not rely on `MAX_EXTRINSIC_DEPTH` because we cannot risk that this value will be changed in the future and hence break existing contracts.
=> contracts: Apply depth limit when decoding

client/executor/wasmtime/src/runtime.rs, client/executor/wasmtime/src/tests.rs
Fixes https://github.com/paritytech/substrate/issues/11891
This PR restores `wasmtime`'s default stack size limit to 1MB.
Originally `wasmtime`'s default stack size limit was set to 1MB, however in [version 0.35 it was changed to 512 KB](https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md#0350) for reasons which aren't really relevant to us. This flew under the radar until our friends from the Astar parachain noticed that this broke their ability to sync their parachain from scratch.
So this PR simply restores the original limit.
I've also added two extra tests to more closely enforce this limit. Please note that since they test the exact boundary in theory they may also fail if anything else changes related to how much stack space a single frame takes without us modifying …
=> Restore `wasmtime`'s default stack size limit to 1MB

primitives/runtime/src/bounded/bounded_vec.rs
Per title. Needed for https://github.com/paritytech/substrate/pull/11996
=> Add `BoundedVec::sort_by_key`

frame/state-trie-migration/src/lib.rs, frame/support/procedural/src/pallet/expand/call.rs, frame/support/procedural/src/pallet/parse/call.rs, frame/support/src/dispatch.rs, frame/support/test/tests/construct_runtime.rs, frame/support/test/tests/storage_layers.rs, frame/transaction-storage/src/lib.rs, primitives/state-machine/src/basic.rs, primitives/state-machine/src/overlayed_changes/changeset.rs, primitives/state-machine/src/overlayed_changes/mod.rs
Before this pr we only wrapped `pallet::calls` into storage layers when executing the calls with
`dispatch`. This pr is solving that by wrapping each call function inside a storage layer.
=> transactional: Wrap `pallet::calls` directly in storage layers

Cargo.lock, client/executor/common/Cargo.toml, client/executor/common/src/error.rs, client/executor/src/native_executor.rs, primitives/runtime-interface/src/lib.rs
BTW, the `sp-serializer` now is only used as dev-dep.
=> chore: improve runtime executor docs and remove unused error

client/cli/src/commands/run_cmd.rs
https://docs.substrate.io/v3/runtime/custom-rpcs/#public-rpcs is broken, I believe the correct link is now https://docs.substrate.io/main-docs/build/custom-rpc/#public-rpcs
=> Fix broken links in `polkadot --help`

frame/support/src/storage/types/double_map.rs, frame/support/src/storage/types/map.rs
Closes: https://github.com/paritytech/substrate/issues/11992
=> Use correct length for Pallet and Storage prefix when calculating `KeyLenOf`

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/test.yml
The PR improves `cancel-pipeline` job. It posts a message in PR when the one of the `Required` jobs is broken. See examples below. 
cc https://github.com/paritytech/ci_cd/issues/548
=> [ci] Improve cancel-pipeline job

frame/benchmarking/src/lib.rs
Actually adding the name of the benchmark to the log:
For example:
```
2022-08-12 13:27:56.886 TRACE main benchmark: End Benchmark: 930000 ns    
2022-08-12 13:27:56.886 TRACE main benchmark: Read/Write Count (4, 0, 4, 0)    
2022-08-12 13:27:56.968 TRACE main benchmark: Start Benchmark: one_fewer_deciding_failing ([])    
2022-08-12 13:27:56.969 TRACE main benchmark: End Benchmark: 804000 ns    
2022-08-12 13:27:56.969 TRACE main benchmark: Read/Write Count (0, 0, 0, 0)    
2022-08-12 13:27:57.048 TRACE main benchmark: Start Benchmark: one_fewer_deciding_passing ([])
```
=> better benchmark log

client/rpc-servers/src/middleware.rs
=> feat(rpc middleware): use custom time buckets

primitives/core/src/defer.rs, primitives/core/src/lib.rs
Adds a `defer` function that can be used to execute code when the current scope gets dropped.  
This is useful for running cleanup code (need it for a future MR).   
Example:  
```rust
let mut called = false;
{
sp_core::defer!(
called = true;
);
}
assert!(called, "DeferGuard should have executed the closure");
```
Do we already have this? Is `sp-core` the correct spot for this?
=> Add `defer`

frame/benchmarking/src/lib.rs, frame/referenda/src/benchmarking.rs, frame/referenda/src/lib.rs
Benchmarks for Governance V2 were failing: https://github.com/paritytech/polkadot/pull/5205
This should fix them.
Fixes: https://github.com/paritytech/substrate/issues/11906
=> Fix Gov V2 Benchmarks

frame/bags-list/src/benchmarks.rs, frame/conviction-voting/src/benchmarking.rs, frame/referenda/src/benchmarking.rs
Found some instantiable pallets which did not have proper benchmarks using the different instances.
=> Add Benchmarking Instance to Pallets

Cargo.lock, frame/benchmarking/Cargo.toml, frame/benchmarking/src/lib.rs, frame/benchmarking/src/tests.rs
Currently the DB state is not wiped in case that the benchmark returned an error.  
This is only a problem when the benchmark is invoked manually. Fixed it by using the new `defer!` :raised_hands:   
Thanks to @AurevoirXavier for bringing attention to this. There is another oddity with the block number initialization which will be fixed in a new MR.
=> Always wipe DB state after benchmark

frame/benchmarking/src/lib.rs, frame/bounties/src/benchmarking.rs, frame/democracy/src/benchmarking.rs, frame/identity/src/benchmarking.rs, frame/scheduler/src/benchmarking.rs, frame/staking/Cargo.toml, frame/tips/src/benchmarking.rs, frame/treasury/src/benchmarking.rs
Some benchmarks assume Root origin, instead of calling the appropriate `successful_origin`.
This fixes that.
=> Fix Origins Used in Runtime Benchmarks

bin/node/cli/tests/benchmark_storage_works.rs, utils/frame/benchmarking-cli/src/storage/cmd.rs, utils/frame/benchmarking-cli/src/storage/read.rs, utils/frame/benchmarking-cli/src/storage/write.rs
We are using child trees extensively in our blockchain (Frequency) and to be able to evaluate feasibility/scalability of some of these implementations we need to have a better understanding in weight calculations for these nodes that are included in child trees.
- added a feature flag `include-child` to include child tree nodes in storage benchmark calculations
- refactored `write.rs`
- is there any need for polkadot or cumulus companion PRs?
=> benchmark-cli: add child tree support

frame/contracts/src/chain_extension.rs
Downstream code sometimes need to name those state types in order to write code that is generic over those states. Hence we make them public but introduce a new `Sealed` trait to prevent downstream code from implementing those state traits for their own types.
cc @xgreenx
=> contracts: Make chain extension state types public

frame/staking/reward-curve/src/lib.rs
This link is broken because the web3 foundation site was updated and the section structure was altered. I believe this is the link it should be now.
=> Fix broken link to web3 foundation research

Cargo.lock, bin/node-sassafras/node/Cargo.toml, bin/node-sassafras/node/src/chain_spec.rs, bin/node-sassafras/node/src/cli.rs, bin/node-sassafras/node/src/command.rs, bin/node-sassafras/node/src/service.rs, bin/node-sassafras/runtime/Cargo.toml, bin/node-sassafras/runtime/src/lib.rs, client/consensus/sassafras/src/authorship.rs, client/consensus/sassafras/src/aux_schema.rs, client/consensus/sassafras/src/block_import.rs, client/consensus/sassafras/src/lib.rs, client/consensus/sassafras/src/verification.rs, frame/sassafras/Cargo.toml, frame/sassafras/src/benchmarking.rs, frame/sassafras/src/lib.rs, frame/sassafras/src/mock.rs, frame/sassafras/src/session.rs, frame/sassafras/src/tests.rs, primitives/consensus/sassafras/src/digests.rs, primitives/consensus/sassafras/src/lib.rs, primitives/consensus/sassafras/src/vrf.rs
Partially Addresses https://github.com/paritytech/substrate/issues/11515
---
Flows into main Sassafras PR https://github.com/paritytech/substrate/pull/11879
=> Sassafras consensus - Prototype 2.1

frame/support/procedural/src/pallet/parse/storage.rs
This will have slipped through the net as a PR that was good to merge and passed the clippy tests, but then we extended the rules to include unnecessary clones. This fixes clippy on master.
=> clone not required as copy.

client/executor/runtime-test/src/lib.rs, client/executor/src/integration_tests/mod.rs, primitives/core/src/testing.rs
When used a return statement before we directly returned from the function which is obviously wrong.
=> Fix `wasm_export_functions` when using a return statement

.github/workflows/auto-label-issues.yml, .github/workflows/auto-label-prs.yml, .github/workflows/md-link-check.yml, .github/workflows/monthly-tag.yml, .github/workflows/release-tagging.yml
In order to improve our security posture with GitHub Actions usage. I've made a version pinning ether to commit hash or to specific version.
Related issues and policy:
https://github.com/paritytech/ci_cd/issues/464
https://github.com/paritytech/ci_cd/wiki/Policies-and-regulations:-GitHub-Actions-usage-policies
=> pin gha versions

frame/alliance/src/tests.rs
Added some more negative tests to make sure a retired person has no special privileges.
The last 3 asserts currently return Ok(()) and thus fail the test. 
We're using 4 and the announcement origin is defined as the following in the mock:
`type AnnouncementOrigin = EnsureSignedBy<Three, u64>;`
Maybe I have got the test wrong in some way?
=> add negative tests

utils/frame/try-runtime/cli/src/commands/execute_block.rs, utils/frame/try-runtime/cli/src/commands/follow_chain.rs, utils/frame/try-runtime/cli/src/commands/offchain_worker.rs, utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs, utils/frame/try-runtime/cli/src/lib.rs, utils/frame/try-runtime/cli/src/parse.rs
Currently, every subcommand of `try-runtime` operates on externalities with `StateVersion(1)` (which is the default for `RemoteExternalities` - https://github.com/paritytech/substrate/blob/master/utils/frame/remote-externalities/src/lib.rs#L269). Although it will work with any remote chain without any warning or check, some problems may rise if chain uses another state version. For example, Polkadot (afaik) and AlephZero use `StateVersion(0)`.
This PR introduces new CLI option which enables user to specify target state version. By default it is `StateVersion::1`.
cc: @kianenigma
=> `try-runtime` - support all state versions

client/finality-grandpa/src/communication/tests.rs, client/network-gossip/src/bridge.rs, client/network-gossip/src/state_machine.rs, client/network/common/src/service.rs, client/network/src/service.rs, client/offchain/src/api.rs, client/offchain/src/lib.rs, client/service/src/lib.rs, client/service/test/src/lib.rs
Resolves https://github.com/paritytech/substrate/issues/8834.
=> Make `NetworkService::add_reserved_peer()` accept `MultiaddrWithPeerId`

Cargo.lock, client/executor/wasmtime/Cargo.toml
`wasmtime` uses `rustix` to map memory. By default `rustix` uses raw syscalls to call into the OS. This makes it impossible to hook into those calls through conventional means (e.g. through LD_PRELOAD), which makes debugging of memory issues more difficult.
So this PR forces `rustix` to go through `libc` instead of directly calling the appropriate syscalls. Besides making `mmap` etc. hookable this doesn't have any other effects. (We already depend on `libc` anyway, and those calls are heavy enough and not made often enough to make any performance difference at all by having them called directly through a syscall. It's a nice feature when you want to e.g. build a `no_std` program which still can interface with the OS, but in our case it's pointless.)
I've added an extra dependency on an …
=> Force `rustix` to use libc

Cargo.lock, frame/benchmarking/Cargo.toml, frame/benchmarking/src/tests.rs
`test_values_per_component` does change env variables, which can cause other tests to fail when run concurrently.  
Fixed by using [rusty-fork](https://docs.rs/rusty-fork/latest/rusty_fork/) to fork off the process to isolate the env-var changes.
=> Fix sporadic test failure

client/network/src/transactions.rs
The logging before is confusing as it says Propagating but it's not in fact when gossip_enabled is
false. Now it's also consistent with `propagate_transactions` below.
=> Only log when the transaction is actually to be propagated

frame/uniques/src/functions.rs, frame/uniques/src/lib.rs, frame/uniques/src/tests.rs
Currently, the `approved` account of an item doesn't get reset to `None` after each transfer. This can cause a problem because it is possible for the owner of the item to approve an item to his other account and after transferring the item he can claim it back.
=> Uniques: Reset approved account after transfer 

frame/support/src/lib.rs, frame/support/src/storage/mod.rs, frame/support/src/storage/storage_noop_guard.rs
The new struct `StorageNoopGuard` is the guard version of `assert_storage_noop!`.  
Wrapping large code blocks inside a macro is ugly and causes more indentation.  This is useful when writing large zero-sum tests.
```rust
fn my_test() {
new_test_ext().execute_with(|| {
assert_storage_noop!({
// The code
});
});
}
```
```rust
fn my_test() {
new_test_ext().execute_with(|| {
let _guard = StorageNoopGuard::default();
// The code
});
}
```
=> Add `StorageNoopGuard`

frame/alliance/src/benchmarking.rs, frame/alliance/src/lib.rs, frame/alliance/src/migration.rs, frame/alliance/src/tests.rs
Fixes: 
- rename `votable` to `voting`
- fix migration weights
=> Alliance pallet: fix func name, fix migration weights

frame/assets/src/types.rs, frame/support/src/traits/metadata.rs, frame/support/src/traits/tokens/fungibles/approvals.rs, frame/support/src/traits/tokens/fungibles/balanced.rs
Have been reading a lot of code recently. These stood out.
=> Doc only typo fixes

frame/transaction-payment/src/lib.rs
This allows an initial value for `NextFeeMultiplier` to be provided at genesis. 
The current implementation hard-codes the initial value to `FixedU128::saturating_from_integer(1)` when it is absent. While this can be adjusted arbitrarily with `FeeMultiplierUpdate`, this doesn't kick in until the end of block 1.
This means that block 1 fees are impractical on any runtime for which 1 is not a sane value. This is particularly problematic for testing.
An alternative approach would be to add an initial value to the runtime config, but this didn't seem worth the extra bloat to me.
=> Impl transaction-payment GenesisConfig with NextFeeMultplier support

utils/frame/benchmarking-cli/src/overhead/README.md, utils/frame/benchmarking-cli/src/overhead/cmd.rs, utils/frame/benchmarking-cli/src/overhead/template.rs, utils/frame/benchmarking-cli/src/overhead/weights.hbs, utils/frame/benchmarking-cli/src/shared/README.md, utils/frame/benchmarking-cli/src/storage/README.md, utils/frame/benchmarking-cli/src/storage/cmd.rs, utils/frame/benchmarking-cli/src/storage/template.rs, utils/frame/benchmarking-cli/src/storage/weights.hbs
Add `--header` to `benchmark overhead + storage` to swap out the Substrate header for something else.  
To be consistent with `benchmark pallet` it now explicitly requires the Substrate header, otherwise there is none.  
Will need a Polkadot follow-up to update the release CI scripts.  
Part of https://github.com/paritytech/substrate/issues/11141, preparation for https://github.com/paritytech/command-bot/issues/102  
Partially supersedes https://github.com/paritytech/substrate/pull/11893
=> Add `--header` to `benchmark overhead + storage`

frame/babe/src/tests.rs, frame/collective/src/lib.rs, frame/contracts/src/gas.rs, frame/contracts/src/wasm/mod.rs, frame/election-provider-multi-phase/src/lib.rs, frame/election-provider-multi-phase/src/unsigned.rs, frame/examples/basic/src/tests.rs, frame/executive/src/lib.rs, frame/grandpa/src/tests.rs, frame/multisig/src/lib.rs, frame/scheduler/src/lib.rs, frame/staking/src/pallet/mod.rs, frame/staking/src/tests.rs, frame/support/src/weights/block_weights.rs, frame/support/src/weights/extrinsic_weights.rs, frame/support/src/weights/paritydb_weights.rs, frame/support/src/weights/rocksdb_weights.rs, frame/support/src/weights/weight_v2.rs, frame/system/src/extensions/check_weight.rs, frame/system/src/limits.rs, frame/whitelist/src/lib.rs, utils/frame/benchmarking-cli/src/overhead/weights.hbs, utils/frame/benchmarking-cli/src/storage/weights.hbs
Part of #12176.
This PR removes the `PartialOrd` and `Ord` derivation for the new `Weight` struct. The intention here is that normal ordering does not quite make sense for a composite `Weight` struct, and instead we need to be more granular -- do we mean that _all_ constituent weights need to be compared, or _any_ one of them would suffice?
As a result of removing `Ord`, there are places in the code which relied on this behaviour, and reviewers will need to properly check that the more granular comparison makes sense in the context around the affected piece of code.
polkadot companion: paritytech/polkadot#5971
cumulus companion: paritytech/cumulus#1601
=> Remove Ord impl for Weights V2 and add comparison fns

frame/alliance/src/mock.rs, frame/benchmarking/src/lib.rs, frame/identity/src/benchmarking.rs, frame/identity/src/lib.rs, frame/identity/src/tests.rs
Check that a registrar is providing judgement for the correct identity.
=> pallet-identity: Be more paranoid ;)

scripts/ci/gitlab/pipeline/test.yml
The PR name speaks for itself.
=> Fully remove `rusty-cachier` from the `node-bench-regression-guard` job

frame/support/procedural/src/construct_runtime/mod.rs, frame/support/test/Cargo.toml, frame/support/test/tests/pallet.rs, scripts/ci/gitlab/pipeline/test.yml
With the recent addition of supporting features in `construct_runtime!` there was a bug overseen. The `AllPalletsWithSystem` etc type declarations would be declared twice when a certain was enabled. The problem was that in the macro we didn't feature gate the types that should be declared when there is no feature enabled. This pull request now takes care of feature gating this type behind `all(#( not(feature) ))`. So, these types will only be enabled if no of the configured features is enabled.
It also adds a test to ensure that the code is tested properly.
=> construct_runtime: Fix generation of types behind features

bin/node-template/runtime/src/lib.rs, frame/transaction-payment/src/lib.rs
Currently, the template node sets the `FeeMultiplierUpdate` of the `pallet_transaction_payment::Config` to the unit type.
It seems not obvious (and barely noticeable) that the default implementation of the `MultiplierUpdate` trait returns `0` (and not `1`).
Because of that, the transaction weights will be discarded due to the multiplication by 0 [inside the transaction payment pallet](https://github.com/paritytech/substrate/blob/5a48536a49859f83dbbbab1285311f14c192e7b1/frame/transaction-payment/src/lib.rs#L548-L561).
This PR suggests using the `FeeMultipleUpdate` equivalent to the [`SlowAdjustingFeeUpdate`](https://github.com/paritytech/polkadot/blob/87d6cfc7c0531d888898c9bbd1a1e299538a546b/runtime/common/src/lib.rs#L96-L97) from the Polkadot runtime common.
I believe it will fix the …
=> Add `ConstFeeMultiplier` to the transaction payment pallet

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/test.yml
Running downstream pipelines for `master` with images other than the current production one could result in incorrect `node-bench` results and `node-bench-regression-guard`'s false positives. This behavior could happen because of e.g. different stable Rust toolchains in these images. Any successful `cargo-check-benches` job (i.e. it doesn't matter if it was run with e.g. `ci-linux:staging` or `ci-linux:production`) will upload its results and this can result in incorrect performance regression detections.
=> Don't run `cargo-check-benches` for `master` based downstream staging pipelines

frame/election-provider-multi-phase/src/lib.rs
Simply adds back some of these types that have been moved from `trait Config` to `trait MinerConfig` to the metadata.
=> Expose some of the staking miner types over metadata

client/finality-grandpa/src/aux_schema.rs, client/finality-grandpa/src/communication/gossip.rs, client/finality-grandpa/src/communication/mod.rs, client/finality-grandpa/src/environment.rs, client/finality-grandpa/src/finality_proof.rs, client/finality-grandpa/src/justification.rs, client/finality-grandpa/src/lib.rs, client/finality-grandpa/src/tests.rs, client/finality-grandpa/src/until_imported.rs, frame/transaction-payment/rpc/src/lib.rs, primitives/finality-grandpa/src/lib.rs
- I improve type params since many types only want to use `Header` rather than the `Block` type.
- These types are used by me in both no_std/std. And  I need grandpa justification field be `pub`.
=> extract some grandpa types to Primitives crate

utils/frame/benchmarking-cli/src/block/cmd.rs, utils/frame/benchmarking-cli/src/extrinsic/cmd.rs, utils/frame/benchmarking-cli/src/overhead/cmd.rs, utils/frame/benchmarking-cli/src/storage/cmd.rs
Spotted some large weight decrease for `BlockExecutionWeight` on the Polkadot release branch v0.9.29 [here](https://github.com/paritytech/polkadot/pull/5988#discussion_r966960674).  
It comes from the new Trie cache https://github.com/paritytech/substrate/pull/11407 feature which has unforeseen influence on the weights here.  
This MR disables caching per default and makes enabling it explicit.
=> benches: disable caching per default

Cargo.lock, client/service/Cargo.toml, client/service/src/config.rs
Instead of returning always a different path, this now returns the same path for the entire lifetime of the program. We still ensure that the path is cleared at the end of the program.
=> Make `BasePath::new_temp_dir` return the same path for the program lifetime

client/tracing/src/logging/mod.rs
Sadly `trust-dns` and `libp2p::iface` are printing stuff that isn't very informative and just confuses the user. So, we just disable logging output from both of these crates as we already have done this for other crates as well.
=> Clean up the logging output

scripts/ci/gitlab/pipeline/build.yml, scripts/ci/gitlab/pipeline/test.yml
Certain situations exist where depending on a lock file could be a good idea, especially for the CI. This could prevent cases like [this](https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/1839916) (reported on Matrix by @ggwpez) from happening.
This PR adds `--locked` flag to all Cargo runs in the CI, making Cargo always respect existing `Cargo.lock` files.
=> Use `--locked` for Cargo in CI everywhere

bin/node/runtime/src/lib.rs, frame/referenda/src/lib.rs, frame/referenda/src/mock.rs
Fixes https://github.com/paritytech/substrate/issues/12272
Follow ups:
=> Expose tracks as a constant.

client/beefy/src/tests.rs, client/beefy/src/worker.rs
Fix corner case where voter gets a single burst of finality notifications just when it starts.
The notification stream used to be consumed by "wait_for_pallet" logic, then main loop would subscribe to finality notifications, but by that time some notifications might've been lost.
Fix this by subscribing the main loop to notifications before waiting for pallet to become available. Share the same stream with the main loop so that notifications for blocks before pallet available are ignored, while _all_ notifications after pallet available are processed.
Add regression test for this.
=> client/beefy: fix voter initialization corner-case

frame/multisig/src/benchmarking.rs, frame/multisig/src/lib.rs, frame/multisig/src/tests.rs
fixes for https://github.com/paritytech/substrate/pull/12072
=> Multisig: Fix tests and re-introduce reserve logic

client/consensus/aura/src/import_queue.rs, client/consensus/babe/src/lib.rs, client/consensus/common/src/block_import.rs, client/consensus/pow/src/lib.rs
=> Fix warp sync

frame/staking/src/pallet/impls.rs
Blocks https://github.com/paritytech/polkadot/pull/5930 and potentially all the polkadot builds that depend on latest substrate master.
polkadot companion: https://github.com/paritytech/polkadot/pull/5930
^ not really, but we need it for the dependent build to pass
=> [Fix] Benchmark issue in staking

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/test.yml
#12233 introduced a regression where `cargo-check-benches` job stopped to be included in pipelines. This PR fixes that.
=> Fix `cargo-check-benches` job's `rules:`

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/test.yml
PR reverts cancel-pipeline job to an old version in order to change it in the future (more info: https://github.com/paritytech/ci_cd/issues/548#issuecomment-1233436898)
=> [ci] Revert cancel-pipeline job

utils/frame/try-runtime/cli/src/commands/execute_block.rs, utils/frame/try-runtime/cli/src/commands/follow_chain.rs, utils/frame/try-runtime/cli/src/commands/offchain_worker.rs, utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs, utils/frame/try-runtime/cli/src/lib.rs
Better naming and description wrt expectations.
fixes https://github.com/paritytech/substrate/issues/12211
=> try-runtime: rename spec check flag

bin/node/cli/src/service.rs, client/consensus/babe/src/lib.rs, client/consensus/babe/src/tests.rs, client/consensus/common/src/block_import.rs, client/consensus/manual-seal/src/consensus/babe.rs, client/consensus/pow/src/lib.rs, client/consensus/pow/src/worker.rs
Nothing special here... Only a helper method to allow to ignore the way intermediates are stored within the `BlockImportParams`.
The user is still free to use directly the container as before if for some reason it already has a `Cow` (even though nobody in our codebase requires to use it in this way).
=> Introduce 'BlockImportParams::insert_intermediate' method

Cargo.lock, client/executor/wasmtime/Cargo.toml, primitives/wasm-interface/Cargo.toml
This PR bumps our `wasmtime` dependency to the newest version ([changelog](https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md#100))
I see no significant performance differences. There are two new features in 1.0 that are potentially significant and could benefit us - incremental compilation (compiling the runtimes [**is** a significant bottleneck for us](https://github.com/paritytech/polkadot/issues/5821)) and inline stack probes. However, they are disabled by default. I haven't enabled them yet as that would require more in-depth testing (which I do intend to do at a later date).
=> Bump `wasmtime` to 1.0.0

utils/frame/benchmarking-cli/src/overhead/weights.hbs, utils/frame/benchmarking-cli/src/pallet/mod.rs, utils/frame/benchmarking-cli/src/pallet/template.hbs
Changes:
- Manually do what `cargo +nightly fmt` would do to the templates; [example](https://github.com/paritytech/polkadot/blob/28acc786eedd607954a84078f15e6e27ab66d90f/runtime/kusama/constants/src/weights/block_weights.rs#L73).  
Looks like it slipped through in the Weights V2 update.
- Set the default value of `--steps` for `benchmark pallet` to 2, since it otherwise errors with `steps must be at least 2`.
=> Format templates and fix `--steps` default value

frame/benchmarking/README.md, utils/frame/benchmarking-cli/src/pallet/command.rs, utils/frame/benchmarking-cli/src/pallet/writer.rs
`benchmark pallet` currently stringifies the pallet path + instance path and uses that as output name.  
This does not work when the path contains `::`, since the resulting file path should be a valid rust module.  
Changes: 
- Replace `::` with `_` in the auto-generated output path. It does not change the path when it is explicitly specified by the user.
- Use `println!` instead of `log` since that module currently mixes it which causes disordered output.
- Print a warning when multiple results got written to the same file, as this is most likely a usage error.
- Put the file creation at the end of the code to not miss any error output.
That should allow us to update [these](https://github.com/paritytech/pipeline-scripts/blob/5c0703248ea621a73b8ca6bcb46e0478498583ed/bench-bot.sh#L98-L101) …
=> bench: Use `_` instead  of `::` in auto-generated file names

frame/executive/src/lib.rs, frame/support/src/traits/hooks.rs
Fixes https://github.com/paritytech/substrate/issues/12295
@bkchr let me know if that's what you had in mind.
=> [Feature] Sequential migration execution for try-runtime

frame/support/src/lib.rs
To prevent this from happening:
```
error: associated function is never used: `take`
--> frame/support/src/lib.rs:459:6
|
459 |                       pub fn take() -> $type {
|                       ^^^^^^^^^^^^^^^^^^^^^^
|
::: frame/support/src/traits/hooks.rs:465:9
|
465 | /         parameter_types! {
466 | |             static Test1Assertions: u8 = 0;
467 | |             static Test2Assertions: u8 = 0;
468 | |             static Test3Assertions: u8 = 0;
469 | |             static EnableSequentialTest: bool = false;
470 | |             static SequentialAssertions: u8 = 0;
471 | |         }
| |_________- in this macro invocation
```
=> [Fix] parameter_types! dead code errors

primitives/weights/src/weight_v2.rs
Not sure, if this is essentially needed, but with respect to `const`s, which will be one of the common usages of `Weights` as runtime parameters, I am not a fan of saturating operations and the checked versions are currently not really usable as `unwrap()` is not available for consts.
The additional methods allow for usage of weights as `const SOME_WEIGHT: Weight = OTHER_WEIGHT.div(2)`
* `const MAXIMUM_BLOCK_WEIGHT: Weight = WEIGHT_PER_SECOND / 2` does not work, which is fine. 
* `const MAXIMUM_BLOCK_WEIGHT: Weight = WEIGHT_PER_SECOND.checked_div(2).unwrap()` does not work, which is not so fine, as we don't want an `Option<Weight>`
* `const MAXIMUM_BLOCK_WEIGHT: Weight = WEIGHT_PER_SECOND.saturating_add(u64::MAX)` does work, but assuming `WEIGHT_PER_SECOND` is bigger than `u64::MAX ` a …
=> Const impls of base arithmetics for `Weights` with `u64`

bin/node/executor/tests/basic.rs, frame/system/src/extensions/check_weight.rs, frame/system/src/lib.rs, frame/system/src/mock.rs, frame/system/src/tests.rs
Closes https://github.com/paritytech/substrate/issues/12252:  
- Adds the base-weight of the respective dispatch class into the event by modifying `note_applied_extrinsic`.  
- Update tests and give the mocked `Operational` class a distinct base weight, to improve testing.
PolkadotJs now also shows the correct weight of a Remark: `87_298_000 = 86_298_000 (base) + 1_000_000 (remark)`.  
This is identical to the result of `System::blockWeight(block_hash)` in that case.  
cc @notlesh
=> Add base-weight to `System::Extrinsic*` events

frame/staking/src/migrations.rs
Re add the migration pre and post checks that was removed for PR https://github.com/paritytech/substrate/pull/12230. 
With @ruseinov's fix for sequential execution of migrate functions https://github.com/paritytech/substrate/pull/12319, we do not need to do this hack anymore.
=> Undo removing migration checks

frame/alliance/src/lib.rs, frame/collective/src/lib.rs, frame/election-provider-multi-phase/src/unsigned.rs, frame/multisig/src/benchmarking.rs, frame/ranked-collective/src/lib.rs
Since `Call` got renamed to `RuntimeCall`, we don't need the `OuterCall` alias.
=> Removed OuterCall alias & doc fixes

Cargo.lock, frame/fast-unstake/Cargo.toml, frame/fast-unstake/src/benchmarking.rs, frame/fast-unstake/src/lib.rs, frame/fast-unstake/src/mock.rs, frame/fast-unstake/src/tests.rs, frame/fast-unstake/src/types.rs
related: https://github.com/paritytech/substrate/issues/12337
=> [Enhancement] Remove optional Pool subscription from fast-unstake

primitives/state-machine/src/trie_backend_essence.rs
Probably caused by this regression: https://github.com/rust-lang/rust/issues/100544
Closes: https://github.com/paritytech/substrate/issues/12357
=> Fix compilation on 1.66 nightly

client/consensus/aura/src/lib.rs, client/consensus/babe/src/lib.rs, client/consensus/slots/src/lib.rs
Just a trivial renaming of `EpochData` to `AuxData` in the `SimpleSlotWorker` to emphasize that Slot based engines are not necessarily based on (or requires) epochs (even though current  ones are).
The "true" purpose of this type is to represent *some* kind of additional data required by the consensus algorithm to perform its operations.
=> Relax Slots-based engines from Epochs

frame/staking/src/migrations.rs
The storage alias for the staking V12 migration does not have an OnEmpty as the original code did:  
https://github.com/paritytech/substrate/blob/a47f200eebeb88a5bde6f1ed2be9728b82536dde/frame/staking/src/pallet/mod.rs#L247
The migration assume that the value must be present and errors otherwise. Fixed by doing nothing if the value is not present.  
@coderobe this is the issue I was talking about in chat.
=> Account for missing `HistoryDepth` in staking migration V12

frame/benchmarking/src/utils.rs, utils/frame/benchmarking-cli/src/pallet/command.rs, utils/frame/benchmarking-cli/src/pallet/mod.rs
This PR adds a new argument to the benchmarking CLI: `--json-input <path.json>`.
The idea is: you run the benchmarks once and generate raw results with `--json-file`, and then you can rerun the analysis and regenerate the weights as many times as you want, without actually rerunning the benchmarks.
This is in particular useful when working on the code responsible for the analysis since it makes it possible to do apples-to-apples comparisons while keeping the raw benchmark numbers constant.
I've decided to just add an extra argument instead of a new command/subcommand since that seemed to be the least intrusive way to introduce this functionality, and there is already a precedent for it in the form of the `--list` argument; conceptually this might not be the cleanest, but should still be …
=> Support running the pallet benchmarks analysis without running the benchmarks

frame/support/procedural/src/construct_runtime/mod.rs
Fix a typo in the deprecated messages.
=> fix: typo in AllPalletsWithSystem deprecated msg

frame/election-provider-multi-phase/src/lib.rs, frame/election-provider-multi-phase/src/mock.rs, frame/election-provider-support/src/lib.rs, frame/election-provider-support/src/onchain.rs, frame/fast-unstake/src/lib.rs, frame/fast-unstake/src/mock.rs, primitives/npos-elections/src/lib.rs
This PR is in preparation for bounding the staking pallet by `MaxActiveValidators`. https://github.com/paritytech/substrate/issues/12187
This will split up the trait `ElectionProvider` into bounded and unbounded subtraits. The `BoundedElectionProvider` does not have any implementation yet. The follow up PR for this would be `ElectionProviderMultipPhase` implementing `BoundedElectionProvider`.
=> bounding staking: `BoundedElectionProvider` trait

primitives/beefy/src/commitment.rs
We are working on implementing BEEFY finality in the bridges [bridges](https://github.com/paritytech/parity-bridges-common) project and as part of this we'll need to pass the `SignedCommitment` structure as a parameter for extrinsics. In order to do this we need it to implement `TypeInfo`.
=> BEEFY: impl `TypeInfo` for `SignedCommitment`

bin/node-template/runtime/src/lib.rs, bin/node/runtime/src/impls.rs, bin/node/runtime/src/lib.rs, frame/balances/src/tests_composite.rs, frame/balances/src/tests_local.rs, frame/balances/src/tests_reentrancy.rs, frame/contracts/src/tests.rs, frame/democracy/src/tests.rs, frame/election-provider-multi-phase/src/lib.rs, frame/election-provider-multi-phase/src/mock.rs, frame/election-provider-multi-phase/src/signed.rs, frame/election-provider-multi-phase/src/unsigned.rs, frame/elections-phragmen/src/lib.rs, frame/executive/src/lib.rs, frame/fast-unstake/src/mock.rs, frame/grandpa/src/tests.rs, frame/scheduler/src/mock.rs, frame/system/src/extensions/check_weight.rs, frame/system/src/limits.rs, frame/system/src/mock.rs, frame/transaction-payment/asset-tx-payment/src/tests.rs, frame/transaction-payment/src/lib.rs
Part of #12176.
This PR sets the default proof size weight correctly, so that it passes unit tests as intended.
The default max proof size is set at `u64::MAX`, because not all substrate-based chains require submitting PoV blocks to the relay -- standalone sovereign chains can safely ignore this weight component.
For parachains however, the proper parameter to set for the max proof size comes from the relay chain, and is stored a field called `max_pov_size` in this struct: https://github.com/paritytech/cumulus/blob/032540dbf9afc9f5a0d5db7279fc81048f3a168b/pallets/parachain-system/src/lib.rs#L526.
=> Properly set the max proof size weight on defaults and tests

frame/support/procedural/src/pallet/expand/call.rs, frame/support/procedural/src/pallet/expand/hooks.rs
Fixes #12053.
Allows where clauses defined in `Config` to be carried over to the trait impls of `Call` and `Hook` iff they are not defined in the pallet.
=> Carry over where clauses defined in Config to Call and Hook

client/cli/src/config.rs, client/cli/src/params/import_params.rs
Removes deprecated `--unsafe-pruning` flag.
Closes #11380 .
Follow up of #8103
=> unsafe_pruning flag removed

bin/node/runtime/src/lib.rs, client/beefy/src/tests.rs, frame/merkle-mountain-range/rpc/src/lib.rs, frame/merkle-mountain-range/src/lib.rs, frame/merkle-mountain-range/src/tests.rs, primitives/merkle-mountain-range/src/lib.rs
Polkadot companion: https://github.com/paritytech/polkadot/pull/6061
A continuation for #11230
This PR adds a `mmr_generateHistoricalBatchProof()` MMR RPC method. This method can used to generate a historical MMR proof (a MMR proof for when the best known block is older than the best block of the chain).
1) BEEFY light client needs to import explicit commitment + leaf + leaf proof for blocks that are changing validator set. If the chain has progressed since such block, the state of validator-set-change-block may have already been discarded (unless you're using archive node, which we want to avoid) and the call of `mmr_generateProof(use-state-at-validator-set-change-block)` will obviously fail.
2) if block `B` is known to the light client, then we can't simply generate some MMR-related …
=> pallet-mmr: generate historical proofs

primitives/weights/src/weight_v2.rs
`proof_size` is missing here. Lets opt for a future proof implementation.
=> Fix `Weight::is_zero`

frame/support/src/storage/types/counted_map.rs
This PR simply removes unnecessary `Clone` trait bounds on some methods in `CountedStorageMap`.
=> Remove unnecessary Clone trait bounds on CountedStorageMap

docs/CODEOWNERS
I saw the other PR (https://github.com/paritytech/substrate/pull/12406) and thought it'd be a good idea to add myself there too.
I also fixed the paths to which @pepyakin was assigned (both don't exist anymore from what I can see).
=> Add @koute to `docs/CODEOWNERS` and update stale paths

Cargo.lock, frame/beefy-mmr/primitives/Cargo.toml, frame/beefy-mmr/primitives/src/lib.rs, frame/beefy-mmr/src/lib.rs, frame/beefy-mmr/src/mock.rs
Reuse `sp_runtime::traits::Hash` instead of defining a new `Hasher` trait for beefy.
Addresses both items in issue #12387 
polkadot companion: https://github.com/paritytech/polkadot/pull/6098
=> BEEFY: Simplify hashing for pallet-beefy-mmr

client/beefy/src/communication/mod.rs, client/beefy/src/communication/request_response/outgoing_requests_engine.rs, client/beefy/src/lib.rs
Following up with some improvements suggested in https://github.com/paritytech/substrate/pull/12124#pullrequestreview-1129442989
=> client/beefy: small code improvements

frame/alliance/src/lib.rs
Overflow is possible.
Fixes https://github.com/paritytech/srlabs_findings/issues/230
=> Use saturating add for alliance::disband witness data

Cargo.lock, bin/node/runtime/src/lib.rs, frame/contracts/primitives/Cargo.toml, frame/contracts/primitives/src/lib.rs, frame/contracts/src/gas.rs, frame/contracts/src/lib.rs, frame/contracts/src/tests.rs, frame/contracts/src/wasm/code_cache.rs
A few changes were necessary to make `pallet-contracts` compatible with the new weight.
This was a workaround used to emulate the huge PoV impact generated by loading a contract. This is now replaced by setting the `proof_size` to the size of the loaded contract. This is an underestimation but the whole system is just in place to prevent the worst offenders. Charging for anything else is missing anyways and will come later.
Dry runs now include the `proof_size` so that clients can use this to learn about how much `proof_size` a transaction will consume.
`seal_call` and `seal_instantiate` allow only setting 1D weight. Eventually we need to add new versions of those. But the old versions need fixing, too. Current behavior is to set `proof_size` to `0` which is not a good default. It will …
=> Adapt `pallet-contracts` to WeightV2

Cargo.lock, client/beefy/rpc/src/lib.rs, client/beefy/src/worker.rs, primitives/beefy/src/mmr.rs, primitives/merkle-mountain-range/Cargo.toml, primitives/merkle-mountain-range/src/lib.rs
Related to: https://github.com/paritytech/parity-bridges-common/issues/1574
We are working on implementing BEEFY finality in the [bridges](https://github.com/paritytech/parity-bridges-common) project and as part of this we'll need to pass `MmrLeaf` and Mmr `Proof`/`BatchProof` structures as parameters for extrinsics. In order to do this we need them to implement TypeInfo.
=> MMR: impl `TypeInfo` for some structures

client/network/light/src/light_client_requests/handler.rs
At the moment, if the node receives a so-called "light client request" (asking for a storage proof or a call proof), and this request cannot be served, we send back a message indicating that everything is ok, except that it contains an empty proof.
The reason why a request cannot be served is typically that the block has been pruned.
This PR modifies the protocol so that we send back a message without any proof instead.
To do an analogy, right now we more or less send back `Some(Vec::new())`, while this PR modifies this to send back `None`.
This makes it clearer from the point of view of the request sender that something bad has happened.
=> Don't send back empty proofs if light request fails

client/executor/wasmtime/src/runtime.rs
This is a preparation stage for [polkadot#4212](https://github.com/paritytech/polkadot/issues/4212). It does not affect any existing functionality.
This PR contains two closely related but separate changes:
1. Derive `Clone` for `Config`;
2. Implement `Default` for `Config` which is returning not just an empty structure but some reasonable fallback defaults.
1. `sc_executor_wasmtime` is designed to [consume](https://github.com/paritytech/substrate/blob/s0me0ne/executor-config-fixes/client/executor/wasmtime/src/runtime.rs#L671) the config instead of borrowing it. I believe this is due to the possibility of [replacement](https://github.com/paritytech/substrate/blob/s0me0ne/executor-config-fixes/client/executor/wasmtime/src/runtime.rs#L809) of instantiation strategy inside it in some cases. …
=> Implement `Clone` and `Default` for `Config`

Cargo.lock, client/beefy/rpc/src/lib.rs, client/beefy/src/communication/gossip.rs, client/beefy/src/justification.rs, client/beefy/src/lib.rs, client/beefy/src/tests.rs, client/beefy/src/worker.rs, primitives/beefy/Cargo.toml, primitives/beefy/src/commitment.rs, primitives/beefy/src/lib.rs, primitives/beefy/src/mmr.rs, primitives/beefy/src/payload.rs, primitives/beefy/src/witness.rs
Allows to configure the voter with custom `PayloadProvider`s and thus support anything as BEEFY `Payload`.
Fixes https://github.com/paritytech/grandpa-bridge-gadget/issues/409
polkadot companion: https://github.com/paritytech/polkadot/pull/6112
=> Add pluggable BEEFY payload constructors

frame/ranked-collective/src/lib.rs
Unless I am misunderstanding, the comments are suggesting incorrect values:
https://github.com/paritytech/substrate/blob/badc92ac20dbf006595a6af9418da9942527cbd7/frame/ranked-collective/src/lib.rs#L199-L228
Here is an example:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=eabd12199cf5bcad261dd1986e5c540c
Am I missing something or just a typo in the comments that this PR corrects? :crossed_fingers:
=> Fix ranked voting math comment

client/network/common/src/sync/message.rs, client/network/sync/src/lib.rs, client/network/sync/src/schema/api.v1.proto, client/network/sync/src/warp.rs
On the receiving side, this field is completely ignored when we receive a request.
On the sender side, we always set this field to `None`, with the sole exception of warp syncing where we set it to the same value as the starting block because we want one specific block.
As far as I know, not only this field isn't used right now but has never been used.
Since this field is useless, this PR removes it.
Because we're using protobuf, it's not a problem if a client on an old version sends us a warp sync request where the field is defined. The now-unrecognized field will simply be ignored.
If this is approved, a corresponding issue should be opened in the w3f/specs repo.
=> Remove "to_block" field from BlockRequests

utils/frame/benchmarking-cli/src/pallet/command.rs
The error return value of pallet benchmarks were ignored outside of `cargo test` and nobody noticed :see_no_evil: Until @koute did, thanks!  
It is also difficult to notice, since `cargo test` fails but `cargo run` just ignores it.  
@koute can you double check that this fixes it?
=> Dont ignore errors in pallet benchmarking

.gitlab-ci.yml, frame/support/test/tests/construct_runtime_ui/no_std_genesis_config.stderr, frame/support/test/tests/construct_runtime_ui/pallet_error_too_large.stderr, frame/support/test/tests/construct_runtime_ui/undefined_call_part.stderr, frame/support/test/tests/construct_runtime_ui/undefined_event_part.stderr, frame/support/test/tests/construct_runtime_ui/undefined_genesis_config_part.stderr, frame/support/test/tests/construct_runtime_ui/undefined_inherent_part.stderr, frame/support/test/tests/construct_runtime_ui/undefined_origin_part.stderr, frame/support/test/tests/construct_runtime_ui/undefined_validate_unsigned_part.stderr, frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_integrity_test.stderr, frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_on_initialize.stderr, frame/support/test/tests/derive_no_bound_ui/debug.stderr, frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr, frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr, frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr, frame/support/test/tests/pallet_ui/event_field_not_member.stderr, frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr, frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr, primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr, primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
This PR updates UI tests to make stable 1.64 `rustc` happy. The tests were updated via the machinery using the `/.maintain/update-rust-stable.sh` script.
=> Update UI tests for Rust 1.64

client/network/common/src/config.rs, client/network/src/service/tests.rs
Sometimes `NotificationStreamOpenened` would be received for the other protocol before `SyncConnected` was received so when the connection was closed, an incorrect event was read from the event stream.
Also added a comment about the `handshake` field in `NonDefaultSetConfig`. I hope that proper handshake support can be added soon so that comment won't stay there for long.
=> Fix flaky service test

.cargo/config.toml, bin/node/bench/src/core.rs, client/rpc-servers/src/lib.rs, frame/benchmarking/src/analysis.rs, frame/contracts/src/wasm/runtime.rs, frame/election-provider-multi-phase/src/mock.rs, frame/examples/basic/src/benchmarking.rs, primitives/npos-elections/fuzzer/src/common.rs, utils/frame/benchmarking-cli/src/shared/stats.rs
Following the norm set by: https://github.com/paritytech/substrate/pull/6754
Undoes regressions caused by: https://github.com/paritytech/substrate/pull/11154#issuecomment-1272617053
=> Avoid Unstable Sort

client/transaction-pool/tests/pool.rs
This aligns tests in transaction pool added in:
https://github.com/paritytech/substrate/pull/12305
with chanes in `TransactionStatus::Finalized|InBlock` variants added in:
https://github.com/paritytech/substrate/commit/488fc24d98cfe643402b86990ae0aff27ba927b3
=> tx-pool: failing tests fixed

client/network/sync/src/schema/api.v1.proto
I've discovered a stupidity: when we send a block request, the "direction" field (i.e. is the starting block of the request the highest block or the lowest block) is either 0 or 1.
However, the protobuf library that we use can't make the difference between "missing field" and "field that contains a 0".
So whenever we send an "ascending" block request, we are in fact not indicating any direction.
For this reason, I'm opening this PR to clarify that the default value should be interpreted as "Ascending".
It could instead be fixable by releasing a version that also interprets "2" as "Ascending", then later a version that sends "2" for "Ascending", but I don't think it's worth the effort.
=> Clarify the "direction" field of block requests

client/cli/Cargo.toml
By default the `wasmtime`-based WASM executor is not compiled-in (even though *it is the default*!), and only the interpreted executor is included. This doesn't really make any sense (at least not anymore; this executor is widely used, fast and rock-solid stable), and it can unnecessarily trip up people who are unaware of this (like here: https://github.com/paritytech/substrate/issues/12320). So let's just enable it by default and make it opt-out instead of opt-in.
=> Enable the `wasmtime`-based WASM executor by default

primitives/api/test/benches/bench.rs
It changes all the usages of `BlockId::Number` to `BlockId::Hash` wherever such change was trivial.
It complements changes from: #12471
This PR is part of `BlockId::Number` refactoring analysis (https://github.com/paritytech/substrate/issues/11292) .
=> Trivial BlockId::Number => Hash

bin/node/bench/src/import.rs, client/api/src/backend.rs, client/api/src/in_mem.rs, client/basic-authorship/src/basic_authorship.rs, client/block-builder/src/lib.rs, client/db/benches/state_access.rs, client/db/src/lib.rs, client/service/src/client/call_executor.rs, client/service/src/client/client.rs, client/service/test/src/client/mod.rs, primitives/blockchain/src/backend.rs, utils/frame/rpc/state-trie-migration-rpc/src/lib.rs
It changes the argument of `Backend::state_at` from:
`block: BlockId<Block>` to: `hash: &Block::Hash`
This PR is part of `BlockId::Number` refactoring analysis (https://github.com/paritytech/substrate/issues/11292) .
`HeaderBackend::expect_block_hash_from_id` was used to convert `BlockId` to `Block::Hash`.
polkadot companion: paritytech/polkadot#6149
cumulus companion: paritytech/cumulus#1760
=> BlockId removal: refactor: Backend::state_at

Cargo.lock, utils/frame/try-runtime/cli/Cargo.toml, utils/frame/try-runtime/cli/src/commands/follow_chain.rs, utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
Use the correct weight type to prevent decoding errors.
=> Try-runtime CLI fix weight decoding

frame/beefy-mmr/src/tests.rs, frame/merkle-mountain-range/src/lib.rs, frame/merkle-mountain-range/src/mmr/storage.rs, frame/merkle-mountain-range/src/tests.rs
MMR nodes are saved in off-chain db under fork-resistant keys based on `frame_system::block_hash()`, as such only nodes added by latest `frame_system::BlockHashCount` can be accessed that way.
Nodes added by blocks older than `frame_system::BlockHashCount` are moved by `offchain_worker` to "canon" (not fork resistant) location - thus being made available regardless of age.
See https://github.com/paritytech/substrate/pull/11594 for more details.
**Issue** is that `offchain_worker` doesn't run for blocks imported during initial sync. So for initial syncs > `frame_system::BlockHashCount` (practically any node syncing from scratch), MMR nodes aren't moved to canon position and access to them is lost.
**Solution** proposed by this PR: runtime block execution saves node to _both_ fork-resistant …
=> pallet-mmr: fix offchain db for sync from zero

frame/support/src/storage/mod.rs
This PR implemnts `StorageDecodeLength` for  unbounded `BTreeSet`
closes #12443
=> implement storage decode length for BTreeSet

Cargo.lock, primitives/beefy/Cargo.toml, primitives/beefy/src/mmr.rs
Related to: https://github.com/paritytech/parity-bridges-common/issues/1574
We are working on implementing BEEFY finality in the [bridges](https://github.com/paritytech/parity-bridges-common) project and as part of this we'll need to have the initial `BeefyAuthoritySet` in the `GenesisConfig` structure. In order to do this we need `BeefyAuthoritySet` to implement serde serialize/deserialize.
=> derive Serialize/Deserialize for BeefyAuthoritySet

client/cli/src/params/offchain_worker_params.rs
Follow up for https://github.com/paritytech/substrate/pull/12381
There are some places where we pass `enable-offchain-indexing=true` to binaries.
This does not work by default anymore in clap 4 which uses `ArgAction::SetTrue` as default. This means that the occurence of the flag sets the value to true and additional values are not allowed.
While I think the new approach makes more sense, there are some users of this flag and we should not break it if not necessary.
=> Use `ArgAction::Set` for enable-offchain-indexing flag

client/api/src/proof_provider.rs, client/network/light/src/light_client_requests/handler.rs, client/network/sync/src/state_request_handler.rs, client/rpc/src/state/state_full.rs, client/service/src/client/client.rs
It changes the arguments of methods of `ProofProvider` trait from:
block: `BlockId<Block>` to: hash: `&Block::Hash`
=> BlockId removal: refactor: ProofProvider

Cargo.lock, frame/identity/src/benchmarking.rs, frame/identity/src/lib.rs, frame/identity/src/tests.rs
This PR evaluates the error being returned by `repatriate_reserved`
Wrote test
Fixed Benchmarks
closes #12460
Polkadot address: 12ZNas89oEagaxLVNbpqmvfMxdrGrqN7gJKSpwthTUPZsrku
=> registrar: Avoid freebies in provide_judgement

client/api/src/backend.rs, client/beefy/src/tests.rs, client/beefy/src/worker.rs, client/consensus/babe/src/tests.rs, client/consensus/manual-seal/src/finalize_block.rs, client/finality-grandpa/src/environment.rs, client/finality-grandpa/src/finality_proof.rs, client/finality-grandpa/src/tests.rs, client/finality-grandpa/src/warp_proof.rs, client/network/sync/src/lib.rs, client/network/test/src/lib.rs, client/network/test/src/sync.rs, client/rpc/src/chain/tests.rs, client/service/src/client/client.rs, client/service/test/src/client/mod.rs, test-utils/client/src/client_ext.rs
It changes the arguments of methods of `Finalizer` trait from:
block: `BlockId<Block>` to: hash: `&Block::Hash`
cumulus companion: paritytech/cumulus#1779
=> BlockId removal: refactor: Finalizer

Cargo.lock, utils/frame/remote-externalities/Cargo.toml, utils/frame/remote-externalities/src/lib.rs
- remove async-std
- use tracing subscriber to get jsonrpsee logs
- re-use client connection
- create a new tokio runtime in each thread (I think tokio::spawn) should be sufficient here but yeye
- increase connection and request timeout
=> some suggestions

client/api/src/backend.rs, client/api/src/in_mem.rs, client/beefy/src/worker.rs, client/db/src/lib.rs, client/service/src/client/client.rs
It changes the arguments of methods of `BlockImportOperation` trait
from: block: `BlockId<Block>` to: hash: `&Block::Hash`
`Backend::finalize_block` was also changed.
=> BlockId removal: refactor: BlockImportOperation+Bknd::finalize_block

client/api/src/backend.rs, client/api/src/in_mem.rs, client/db/benches/state_access.rs, client/db/src/lib.rs, client/service/src/client/client.rs
It changes the arguments of `Backend::begin_state_operation`
from: block: `BlockId<Block>` to: hash: `&Block::Hash`
=> BlockId removal: refactor: Backend::begin_state_operation

client/network/src/discovery.rs, client/network/src/service.rs
Closes https://github.com/paritytech/substrate/issues/7746 as this is the only remaining substrate protocol not using this convention.
=> Use genesis hash- and fork ID-based protocol name for Kademlia

Cargo.lock, client/beefy/src/tests.rs, client/consensus/babe/Cargo.toml, client/consensus/babe/src/tests.rs, client/finality-grandpa/Cargo.toml, client/finality-grandpa/src/tests.rs
This PR sets the `sp_keystore::testing::KeyStore` as the type used across Babe/Grandpa/Beefy tests.
Previously:
- Babe and Grandpa were using a keystore in a temporary filesystem folder. This is not really required.
- Beefy was using the `LocalKeystore::in_memory`. That for testing purposes should behave equivalently to the `testing::KeyStore`.
Some additional minor cleanup has been introduced
=> Normalize keystore type and its usage across tests

bin/node-template/pallets/template/src/lib.rs
This updates the template pallet to use the latest enum syntax for events (so it follows the patterns from other FRAME pallets too).
=> Update template pallet to latest enum syntax

frame/assets/src/functions.rs, frame/assets/src/lib.rs, frame/assets/src/migration.rs, frame/assets/src/types.rs
This PR moves the is_frozen field of the assetDetails into the AssetStatus Enum.  It's a separate PR to allow ease of reviewing, but should probably be either merged into #12310 or be merged into master immediately after #12310 
Related to: #12310
=> Pallet Assets: move is frozen to asset status

scripts/ci/gitlab/pipeline/test.yml
Example why it's needed https://github.com/paritytech/substrate/pull/12543
close https://github.com/paritytech/ci_cd/issues/641
=> [ci] cargo-check-benches against different base branches

frame/membership/README.md, frame/membership/src/lib.rs
This PR fixes a small typo in the documentation of `membership`.
=> Fix typo in `membership` docs

frame/nomination-pools/src/tests.rs
Resolve CI conflict between #12424 and #12407 to make the master CI :green_heart:
=> Use `minimum_nominator_bond` instead of `nominator_bond`

bin/node/inspect/src/lib.rs, client/api/src/client.rs, client/api/src/in_mem.rs, client/db/src/lib.rs, client/network/sync/src/block_request_handler.rs, client/network/test/src/lib.rs, client/service/src/client/client.rs, client/service/test/src/client/mod.rs, client/tracing/src/block/mod.rs, client/transaction-pool/benches/basics.rs, client/transaction-pool/src/api.rs, client/transaction-pool/src/graph/pool.rs, client/transaction-pool/src/lib.rs, client/transaction-pool/src/tests.rs, primitives/blockchain/src/backend.rs, test-utils/runtime/transaction-pool/src/lib.rs
It changes the arguments of `Backend::body` method from: `BlockId<Block>` to: `&Block::Hash`
polkadot companion: paritytech/polkadot#6223
=> BlockId removal: refactor: Backend::body

client/api/src/client.rs, client/api/src/in_mem.rs, client/beefy/src/communication/request_response/incoming_requests_handler.rs, client/beefy/src/tests.rs, client/beefy/src/worker.rs, client/db/src/lib.rs, client/finality-grandpa/src/finality_proof.rs, client/finality-grandpa/src/tests.rs, client/finality-grandpa/src/warp_proof.rs, client/network/sync/src/block_request_handler.rs, client/network/test/src/block_import.rs, client/network/test/src/lib.rs, client/network/test/src/sync.rs, client/service/src/client/client.rs, client/service/test/src/client/mod.rs, primitives/blockchain/src/backend.rs
It changes the arguments of `Backend::justifications` method from: `BlockId<Block>` to: `&Block::Hash`
polkadot companion: paritytech/polkadot#6229
=> BlockId removal: refactor: Backend::justifications

client/api/src/client.rs, client/api/src/in_mem.rs, client/db/src/lib.rs, client/network/sync/src/block_request_handler.rs, client/service/src/client/client.rs, primitives/blockchain/src/backend.rs
It changes the arguments of `Backend::block_indexed_body` method from: `BlockId<Block>` to: `&Block::Hash`
polkadot companion: paritytech/polkadot#6233
=> BlockId removal: refactor: Backend::block_indexed_body

client/cli/src/params/database_params.rs
This was broken in the switch to Clap v4.
=> Make `--db` case insensitive again

client/transaction-pool/src/enactment_state.rs, client/transaction-pool/src/lib.rs
When `tree_route` computation fails, we still need to update the
`enactment_state` to be aligned with last known finalized/best block.
We do not execute enactment phase of maintain procedure, but we do
update the state.
Fixes: #12623
=> txpool: enactment state forced update

client/network/sync/src/lib.rs, client/network/test/src/sync.rs
If block announcement is received from a peer while ancestor search for that same peer is still in progress, do not update the peer's best hash and best number as that causes the ancestor search to yield different information from what was expected and can cause, for example, a fork of lower height not to be downloaded.
Problem basically was that there was a race condition between concluding the ancestor search for a peer and receiving a block announcement from the same peer with higher block number. If the block announcement was received before the ancestor search was concluded (for a fork with a smaller best block number), the peer information was overwritten and the fork was never downloaded.
Resolves https://github.com/paritytech/substrate/issues/12607
=> Do not update peer information if ancestor search is in progress

.gitlab-ci.yml, frame/support/test/tests/construct_runtime_ui/no_std_genesis_config.stderr, frame/support/test/tests/construct_runtime_ui/undefined_event_part.stderr, frame/support/test/tests/construct_runtime_ui/undefined_genesis_config_part.stderr, frame/support/test/tests/construct_runtime_ui/undefined_origin_part.stderr, frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr, frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr, frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr, frame/support/test/tests/pallet_ui/event_field_not_member.stderr, frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr, frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen_unnamed.stderr, frame/support/test/tests/pallet_ui/storage_info_unsatisfied.stderr, frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr, primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
In order to update rust in CI image tests should be fixed. 
cc https://github.com/paritytech/ci_cd/issues/653
```bash
test tests/pallet_ui/pass/trait_constant_valid_bounds.rs [should pass] ... ok
thread 'pallet_ui' panicked at '8 of 71 tests failed', /cargo_home/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.60/src/run.rs:85:13
stack backtrace:
0: rust_begin_unwind
at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
1: core::panicking::panic_fmt
at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
2: trybuild::run::<impl trybuild::Runner>::run
3: <trybuild::TestCases as core::ops::drop::Drop>::drop
4: core::ops::function::FnOnce::call_once
5: core::ops::function::FnOnce::call_once
at …
```
=> Pipeline with ci image with rust 1.65

primitives/state-machine/src/trie_backend.rs, primitives/state-machine/src/trie_backend_essence.rs, primitives/trie/src/cache/mod.rs, primitives/trie/src/recorder.rs
With `StateVersion::V1` values over a certain size are not inlined and being put into the backend with their own hash. When accessing a value in the trie with a recorder, we check if the value is maybe already recorded and thus, we can check the cache. To check if a value is already recorded, we use the key of the value to differentiate them. The problem is when there are multiple tries, like multiple child tries that all have different values under the same key. Before this pull request we didn't have differentiated for which trie we already had recorded a (key, value) pair. This is now done by also taking the storage root into account in the recorder to differentiate the different (key, value) pair in the tries.
Fixes: https://github.com/paritytech/substrate/issues/12598 (I don't …
=> `sp_trie::Recorder`: Fix recording the same key for different tries

Cargo.lock, frame/transaction-payment/rpc/Cargo.toml, frame/transaction-payment/rpc/runtime-api/Cargo.toml, frame/transaction-payment/rpc/runtime-api/src/lib.rs, frame/transaction-payment/rpc/src/lib.rs, frame/transaction-payment/src/types.rs, primitives/weights/src/lib.rs
The runtime api for querying the payment info depends on the `Weight` type and broke for old runtimes that still use the `WeighV1`. This pull requests fixes this by:
1. Bumping the version of the runtime api.
2. Making the node side code use the correct runtime api function depending on the version of the runtime api.
3. Make the RPC always return `WeighV1`.
Users of the api should switch to `state_call` and decide based on the version of the runtime api which `Weight` type is being returned.
=> `payment_queryInfo`: Make it work with `WeightV2`

.gitlab-ci.yml
Rust in Ci image was updated, can return `production` tag back
close https://github.com/paritytech/ci_cd/issues/653
=> [ci] Use ci-linux:production image in ci

frame/scheduler/src/lib.rs
https://github.com/paritytech/substrate/commit/eefba93cf62ff80e1011dbe1cd3a543b711f7bb9#diff-402ebe8b386bd8422131875c431704f41f17f30dd1cebe04b96082b561ef899bR267
Replaced with TaskName everywhere else but not here
=> Keep the same type of name

client/service/src/client/client.rs
If the parent block is alread finalized, we don't need to do this again.
=> Do not finalize parent twice

frame/contracts/src/benchmarking/mod.rs, frame/contracts/src/wasm/mod.rs, frame/contracts/src/wasm/runtime.rs
We need those functions to be included in the release as they ink! 4.0 beta to be released this week depends on them. This does not break any builds.
=> [contracts] Cherrypick stabilized API onto release branch

frame/contracts/src/lib.rs
Detail discussed at https://github.com/polkadot-js/api/pull/5324
We need to bump API version for the change of https://github.com/paritytech/substrate/pull/12429
=> Contracts pallet: Bump Runtime API

frame/contracts/src/lib.rs
=> Backport "Contracts pallet: Bump Runtime API" to 0.9.32 branch

primitives/runtime/src/lib.rs
=> Fix typo in MultiSignature docs

frame/contracts/src/lib.rs
=> Backport "Contracts pallet: Bump Runtime API (#12677)" to 0.9.33 branch

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/publish.yml
Current buildah image is broken. Using the previous one
cc https://github.com/paritytech/ci_cd/issues/671
=> [ci] fix buildah for publishing docker

frame/referenda/src/lib.rs, frame/referenda/src/types.rs
Exposes read access to `is_passing` and `ReferendumStatus` for precompiles
`TrackInfo` has fields with visibility `pub` so its data can be read in the precompile, but field visibility of `ReferendumStatus`, `DecidingStatus`, `Deposit` are `pub(crate)` so their data cannot be read in the precompile. The options for providing the precompile with read access to `ReferendumStatus` are:
1. change `pub(crate)` to `pub` or conservatively `pub(super)` for `ReferendumStatus`, `DecidingStatus`, `Deposit`
2. add public getters for the fields in `ReferendumStatus`
After initially going with public getters, I changed my mind and went with making the fields `pub` because it's fewer changes. Happy to change it to `pub(super)` or instead add public getters again if requested by reviewers.
Also exposed …
=> Make public is_passing and ReferendumStatus

Cargo.lock, bin/node-template/node/Cargo.toml, bin/node/cli/Cargo.toml, bin/node/executor/Cargo.toml, bin/node/runtime/Cargo.toml, bin/node/testing/Cargo.toml, client/beefy/Cargo.toml, client/cli/Cargo.toml, client/consensus/aura/Cargo.toml, client/consensus/babe/Cargo.toml, client/consensus/babe/rpc/Cargo.toml, client/finality-grandpa/Cargo.toml, client/finality-grandpa/rpc/Cargo.toml, frame/contracts/Cargo.toml, frame/contracts/primitives/Cargo.toml, frame/grandpa/Cargo.toml, frame/indices/Cargo.toml, primitives/keyring/Cargo.toml, test-utils/client/Cargo.toml, test-utils/runtime/Cargo.toml
Allows updating of `subxt` and `cargo-contract`  to use latest [`sp-core` and `sp-runtime` releases](https://github.com/paritytech/substrate/pull/12599)
=> Release `sp-keyring` and `pallet-contracts-primitives` `7.0.0`

frame/contracts/proc-macro/Cargo.toml, scripts/ci/gitlab/pipeline/test.yml
=> Fix `cargo check` for `pallet-contracts-proc-macro`

frame/fast-unstake/src/lib.rs
Fixes https://github.com/paritytech/substrate/issues/12618
=> [Fix] Deposit for fast-unstake has to be define as pallet::constant

client/network/light/src/light_client_requests/handler.rs, client/network/light/src/schema.rs, client/network/light/src/schema/light.v1.proto
Fix #12727 
Amends https://github.com/paritytech/substrate/pull/12372
This PR fixes https://github.com/paritytech/substrate/pull/12372 to do what it was intended to do. Right now the light client handler sends back an empty response in case of error, while what I intended was that it sends a response (most importantly, indicating the type of response) but without a proof in it. This is what this PR does.
This PR also switches the schema to protobuf 2.
In protobuf 2, each field is either optional or required. This is good. It's explicit. You know exactly what you get on the wire. Google, the best™ company in the world, then saw that sometimes we send one or two extra bytes that aren't strictly necessary, and, because they have too many engineers and too much time, decided that they were …
=> Fix the light client protocol protobuf schema

Cargo.lock, client/network/common/src/sync.rs, client/network/src/behaviour.rs, client/network/src/config.rs, client/network/src/protocol.rs, client/network/src/service.rs, client/network/src/service/tests/chain_sync.rs, client/network/src/service/tests/mod.rs, client/network/sync/Cargo.toml, client/network/sync/src/lib.rs, client/network/sync/src/mock.rs, client/network/sync/src/service/mock.rs, client/network/sync/src/service/network.rs, client/network/sync/src/tests.rs, client/network/test/src/lib.rs, client/service/src/builder.rs
This PR moves most of the code related to block requests away from `Protocol`/`Behaviour`/`NetworkWorker` to `ChainSync`. There is still a bit of block request code left relating to incoming peer connection/block announcements but those will be addressed in future PRs.
Resolves https://github.com/paritytech/substrate/issues/12133
polkadot companion: https://github.com/paritytech/polkadot/pull/6319
cumulus companion: https://github.com/paritytech/cumulus/pull/1899
=> Move block/state/warpc sync requests/responses to `ChainSync`

frame/election-provider-multi-phase/src/lib.rs, frame/fast-unstake/src/migrations.rs
we have multiple runtime and configuration checks to believe that this error won't happen, but since this code path is reachable by `on_initialize`, defensively returning an error is better.
=> return error instead of expect in `feasibility_check`

bin/node/runtime/src/lib.rs, frame/nfts/README.md, frame/nfts/src/features/attributes.rs, frame/nfts/src/impl_nonfungibles.rs, frame/nfts/src/lib.rs, frame/nfts/src/mock.rs, frame/nfts/src/tests.rs, frame/nfts/src/types.rs, frame/support/src/traits/tokens/nonfungible_v2.rs, frame/support/src/traits/tokens/nonfungibles_v2.rs
In this PR I:
1) Replaced Box<> with the KeyPrefixIterator (as was previously done for the Uniques pallet);
2) updated the Readme file;
3) changed the create_colleciton logic in public traits, the collection_id param got removed since we use auto-incremental ids;
4) added a code that prevents multiple claims of NFTs when the mint type is `HolderOf`
=> [Uniques V2] Final improvements

client/beefy/src/communication/gossip.rs, client/beefy/src/communication/peers.rs, client/beefy/src/lib.rs, client/beefy/src/tests.rs, client/beefy/src/worker.rs
Network events are many and very frequent, remove the net-event-stream from the main voter loop and drastically reduce BEEFY voter task 'wakeups'.
Instead have the `GossipValidator` track known peers as it already has callbacks for that coming from `GossipEngine`.
Fixes https://github.com/paritytech/substrate/issues/12759
=> BEEFY: optimize voter event loop for fewer 'active' wakeups

frame/alliance/src/lib.rs, frame/alliance/src/migration.rs
Storage migration to remove founder role
=> Storage migration to remove founder role

scripts/ci/gitlab/check-each-crate.sh
This is useful so that crates always get routed to a specific group for a given version of the source code, which means that jobs for each group can be reliably retried individually to target a specific crate.
=> Sort crates before splitting them into groups (+ some improvements)

bin/node/runtime/src/lib.rs, frame/system/src/lib.rs
I would also like to replace all `EnsureRootWithSuccess` to use `EnsureWithSuccess` but that doesn't need to happen in this PR.
=> add EnsureWithSuccess

frame/contracts/Cargo.toml, frame/contracts/README.md, frame/contracts/fixtures/account_reentrance_count_call.wat, frame/contracts/fixtures/call_runtime.wat, frame/contracts/fixtures/reentrance_count_call.wat, frame/contracts/fixtures/reentrance_count_delegated_call.wat, frame/contracts/proc-macro/src/lib.rs, frame/contracts/src/benchmarking/mod.rs, frame/contracts/src/wasm/mod.rs
When we introduced the [unstable interfaces](https://github.com/paritytech/substrate/tree/master/frame/contracts#unstable-interfaces) feature we decided to put those features into a special module called `__unstable__`. This turned out to be a mistake: Whenever we eventually device to stabilize a function we generate a breaking change where a newer `pallet-contracts`version gets incompatible with an older ink!.
This is a big no go for stable functions but is allowed for unstable functions. That said, changing the module on stabilization is just a unnecessary form of breakage. Most of the time functions are stabilized as is.
This PR changes the behavior to to make version and instability orthogonal. The way we want to use this it to put functions into the module in which they are …
=> contracts: Don't put unstable functions in special module

client/offchain/src/api.rs, scripts/ci/gitlab/pipeline/check.yml
Changes:  
- Require the rust-feature check not to fail anymore. There were no hiccups so far, should be fine to require.
- Move the rust-feature check to docker executor since it is a bit slower than anticipated. PS: Does not speed it up…
=> Require rust-features check

frame/referenda/src/lib.rs, frame/referenda/src/tests.rs
Addition to https://github.com/paritytech/substrate/pull/12815
=> Referendum alarm, test

frame/referenda/src/lib.rs, frame/referenda/src/tests.rs
Quantization calculation of the referenda alarm was wrong and resulted in it being in the past. This fixes it.
=> Fix quantization in referenda alarm

frame/benchmarking/src/lib.rs, frame/benchmarking/src/utils.rs, frame/bounties/src/benchmarking.rs, frame/child-bounties/src/benchmarking.rs
The (child)-bounties benchmark require `SpendOrigin` as dispatch origin. Since `SpendOrigin` is configured to `NeverEnsureOrigin` in Polkadot, it is impossible to make these Calls since no origin instance can be created.  
This MR fixes this by:
- Adding a `Weightless` early return option for benchmarks whose weight will be annotated with 0. It is not completly zero since users still pay the `ExtrinsicBaseWeight` and a length-based fee.
- Using this option in the `bounties` and `child-bounties` benches.
This is a better solution than https://github.com/paritytech/substrate/pull/11562 since there would be a lot of ifs needed otherwise.
TODO:
These are not actually companions but needed to make the CI green:  
Polkadot companion: https://github.com/paritytech/polkadot/pull/6328  
Cumulus …
=> Add `Weightless` benchmark bailing

frame/balances/src/lib.rs, frame/balances/src/migration.rs, frame/support/src/traits/tokens/currency.rs, frame/support/src/traits/tokens/fungible.rs, frame/support/src/traits/tokens/fungibles.rs, frame/treasury/src/lib.rs, primitives/wasm-interface/src/lib.rs
Introduces `ActiveIssuanceOf` which is the total issuance not including the treasury funds and any other funds marked as inactive with `deactivate`. This should generally be used rather than `TotalIssuance`.
Balances pallet provides a migration which can be used to mark accounts with inactive funds (which, after the upgrade, we assume will be kept up to date with `deactivate` and `reactivate`). For chains with XCM, *this should be used to mark the **Checking Account** when upgraded.*
=> API for registering inactive funds

frame/balances/src/migration.rs, frame/support/src/traits.rs
One extra migration, in case there are multiple accounts with inactive funds.
=> Tweak to active total migrations

frame/balances/src/lib.rs, frame/balances/src/migration.rs, frame/executive/src/lib.rs
Fixes the inactive funds migration. It was missing to set the `storage_version` attribute for the `Pallet` struct. Besides that it also removes the old `StorageVersion` representation and adds support for instances of pallet-balances.
PR that added the migration: https://github.com/paritytech/substrate/pull/12813
=> pallet-balances: Fix inactive funds migration

frame/conviction-voting/src/tests.rs, frame/conviction-voting/src/types.rs, frame/conviction-voting/src/vote.rs
Introduce abstention to OpenGov (conviction-voting). Takes the form of a new variant in `AccountVote`.
Abstentions are like aye votes in terms of the support, but do not affect the approval, thus allow participants to support the early termination of voting without affecting its result.
In a way it's like saying "I see it and I do not plan on voting".
=> OpenGov: Abstentions

frame/utility/src/lib.rs, frame/utility/src/tests.rs
This adds a new utility function `with_weight` that allows Root origin to override the weight of any function call.
=> Add `with_weight` extrinsic

Cargo.lock, client/beefy/Cargo.toml, client/beefy/rpc/Cargo.toml, client/merkle-mountain-range/Cargo.toml, frame/bags-list/remote-tests/Cargo.toml, frame/beefy-mmr/Cargo.toml, frame/beefy-mmr/primitives/Cargo.toml, frame/beefy/Cargo.toml, frame/state-trie-migration/Cargo.toml, primitives/beefy/Cargo.toml, test-utils/runtime/Cargo.toml, utils/frame/remote-externalities/Cargo.toml, utils/frame/try-runtime/cli/Cargo.toml
For context see https://forum.parity.io/t/new-names-suggestions-for-squatted-crates/1513.
close https://github.com/paritytech/release-engineering/issues/132
polkadot companion: https://github.com/paritytech/polkadot/pull/6385
cumulus companion: https://github.com/paritytech/cumulus/pull/1944
=> Rename some crates for publishing to crates.io

frame/referenda/src/benchmarking.rs
if SubmissionDeposit is zero, the assertion fails.
polkadot companion: https://github.com/paritytech/polkadot/pull/6360
=> Referenda benchmark assert fix

scripts/ci/gitlab/pipeline/build.yml
We need to checkout the branch HEAD explicitly because of our dynamic versioning approach while building a substrate binary in the `build-linux-substrate` CI job. Resolves https://github.com/paritytech/ci_cd/issues/682.
=> Checkout to the branch HEAD explicitly in `build-linux-substrate`

client/cli/src/runner.rs
Now we wait in maximum 60 seconds before we shutdown the node. Tasks are may be leaked and leading to some data corruption.
=> Don't indefinitely block on shutting down Tokio

client/rpc-servers/src/middleware.rs
Add `rpc_metrics::extra` target to log rpc response payloads in the default middleware.
=> Trace response payload in default `jsonrpsee` middleware

Cargo.lock, client/cli/Cargo.toml, client/cli/src/runner.rs
The change of waiting in maximum 60 seconds for the node to shutdown actually introduced a bug. We were actually waiting always 60 seconds as we didn't informed our tasks to shutdown. The solution to this problem is to drop the task manager as this will then inform all tasks to end. It also adds tests to ensure that the behaviors work as expected. (This should already have been done in the first pr! :()
Closes: https://github.com/paritytech/substrate/issues/12892
=> Ensure that we inform all tasks to stop before starting the 60 seconds shutdown

frame/election-provider-multi-phase/src/benchmarking.rs, frame/election-provider-multi-phase/src/lib.rs, frame/election-provider-multi-phase/src/signed.rs, frame/election-provider-support/src/lib.rs
`ElectionProvider` expects `ElectionDataProvider` to return a `desired_targets` value that is not larger than the `MaxWinners` supported by the `ElectionProvider`. This is a little opaque rule for the `ElectionDataProvider` to be aware of. This PR tries to better communicate this rule by exposing a `desired_targets_checked` method to the trait `ElectionProvider` which verifies the above condition.
Fixes https://github.com/paritytech/substrate/issues/12756
=> Safe desired targets call

frame/message-queue/src/benchmarking.rs, frame/message-queue/src/integration_test.rs, frame/message-queue/src/lib.rs, frame/message-queue/src/mock.rs, frame/message-queue/src/mock_helpers.rs
Changing the license from of `pallet-message-queue` GPLv3 to Apache-2.0 as intended for pallets.  
cc @jasl
=> `pallet-message-queue`: Fix license

client/state-db/src/noncanonical.rs
#12239 Itroduced a race  condition. The changeset that is moved out of the noncanonical overlay to the pruning window is removed from the overlay, before being written to the database. 
This fix makes sure the changeset is preserved until the next canonicalization by pinning it internally.
Fixes https://github.com/paritytech/polkadot/issues/6377
=> Fix state-db race

frame/contracts/src/migration.rs
Make sure to only run pallet-contracts `v8 pre-upgrade` check if versions is  **7**.
This is a trivial change and only affect `try-runtime` checks for `pallet-contracts`.
=> pallet-contracts migration pre-upgrade fix for v8

scripts/ci/gitlab/pipeline/publish.yml
Using this custom environment will enable us to set protected secrets specifically for it, as opposed to protected secrets for "All" environments, which is looser. See https://docs.gitlab.com/ee/ci/yaml/#environment for context.
=> Use custom environment for publishing crates

Cargo.lock, frame/assets/Cargo.toml, frame/assets/src/lib.rs, frame/bags-list/src/lib.rs, frame/election-provider-support/Cargo.toml, frame/election-provider-support/src/lib.rs, frame/fast-unstake/Cargo.toml, frame/nomination-pools/Cargo.toml, frame/nomination-pools/benchmarking/Cargo.toml, frame/staking/Cargo.toml, frame/staking/src/pallet/impls.rs, frame/transaction-payment/asset-tx-payment/Cargo.toml, frame/transaction-payment/asset-tx-payment/src/tests.rs, primitives/core/src/lib.rs, primitives/staking/Cargo.toml, primitives/staking/src/lib.rs, utils/wasm-builder/src/wasm_project.rs
Dev dependencies should not appear in the feature list. If features are required, they should be directly enabled for the `dev-dependency`.
=> Fixup some wrong dependencies

primitives/arithmetic/src/rational.rs
This PR adds the numerator and denominator to the `Rational128` `Debug` implementation and increases the number of digits displayed for the float representation. This allows numbers close to zero to be distinguished from zero in the logs.
=> add numerator and denominator to Rational128 Debug impl

client/db/src/lib.rs, client/state-db/src/lib.rs, client/state-db/src/noncanonical.rs
A follow up to #12902. Previous PR did not account for the possibility of multiple blocks finalized in a single transaction. This version accumulates all canonicalized changes pinned in memory, until explicitly released with the `sync` function.  Similar to `apply_changes` function that existed before the state-db refactoring.
=> Fix state-db pinning

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/build.yml, scripts/ci/gitlab/pipeline/publish.yml, scripts/ci/gitlab/pipeline/test.yml
cc https://github.com/paritytech/ci_cd/issues/694
=> [ci] add job switcher

scripts/ci/gitlab/pipeline/publish.yml
Necessary when lots of crates need to be published, as demonstrated by https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2158667
=> Increase timeout for crates publishing job

bin/node-template/node/src/benchmarking.rs
Closes: https://github.com/paritytech/substrate/issues/12936
=> Node template isn't licensed, remove left-over GPL header

client/cli/src/arg_enums.rs, client/cli/src/params/offchain_worker_params.rs
There's many instances on the substrate/cumulus stack where the `Validator` term is used when `Collator` should hold the actual meaning. Unfortunately, it's not trivial to solve many of those cases, because of the way that the dependencies of substrate and cumulus are set up.
In case of this CLI argument for OCWs, I propose improving the description string, at least so that the reader has some context to avoid misleading interpretations.
This PR has similar motivations to https://github.com/paritytech/substrate/issues/12933
=> improve ocw validator/collator CLI description

client/db/src/lib.rs
There is this issue about missing block numbers on forced canonicalization. I looked over the code now 10000 times and there are possible ways this can be triggered, but I don't really know how this is triggered. So, this pr is going to solve the symptom and not the cause. The block number to hash mapping is set when we import a new best block. Forced canonicalization will now stop at the best block and it will canonicalize the other blocks later when the best block moved. As the error reports indicated that this issue mainly happened on major sync, there should not be any forks, so not doing the canonicalization directly shouldn't be that harmful. All known implementations should import all blocks as best block on major sync anyway (I mean somewhere there is the bug, but I didn't yet …
=> Fix missing block number issue on forced canonicalization

frame/support/src/traits/misc.rs
Closes: https://github.com/paritytech/substrate/issues/12940
=> Defensive traits: Ensure doc tests are also working without `debug_assertions`

Cargo.lock, primitives/io/Cargo.toml, primitives/io/src/lib.rs
We should not panic for an invalid signature when the `UseDalekExt` is given.
=> ed25519: Don't panic for invalid signature

client/api/src/in_mem.rs, client/authority-discovery/src/worker/tests.rs, client/consensus/babe/src/lib.rs, client/db/src/lib.rs, client/finality-grandpa/src/import.rs, client/merkle-mountain-range/src/test_utils.rs, client/service/src/client/client.rs, primitives/blockchain/src/backend.rs
It changes the arguments of `HeaderBackend::status` method from: `BlockId<Block>` to: `Block::Hash`
polkadot companion: paritytech/polkadot#6459
cumulus companion: paritytech/cumulus#2007
=> BlockId removal: refactor: HeaderBackend::status

frame/dex/src/benchmarking.rs, frame/dex/src/lib.rs, frame/dex/src/tests.rs
(there's generic transaction deadline functionality already)
=> no need for deadline

frame/scheduler/src/benchmarking.rs, frame/scheduler/src/lib.rs, frame/scheduler/src/migration.rs, frame/scheduler/src/tests.rs
Fixes https://github.com/paritytech/substrate/issues/12977 https://github.com/paritytech/substrate/issues/12851
With the small change to the [script](https://gist.github.com/ggwpez/25af3e6ab69b8b11dd7da2354a62096f) provided by @ggwpez, you can see there are only agendas for the future blocks with all None items.
Its possible because we do not remove such agendas on a cancelation, and they get removed when [serviced](https://github.com/paritytech/substrate/blob/a8b46dacd77e7beffeb0cf91c61fde9ea0c18d2a/frame/scheduler/src/lib.rs#L1008).
From the implementation and tests it looks like it was expected to have empty future agendas, nevertheless it seems to me valid, to remove them on the cancelations and address the raised issues.
// DONE fix benches
// DONE migration to remove empty agendas
=> Scheduler: remove empty agenda on cancel

bin/node/runtime/src/lib.rs, frame/dex/src/mock.rs
Updated kitchen sink runtime to AssetIdParameter
also removed unneeded uniques asset lines.
=> fix kitchen sink

client/transaction-pool/tests/pool.rs, test-utils/runtime/transaction-pool/src/lib.rs
This is a minor clean up.
There was a minor bug in `TestApi::add_block`: the best block flag for given number was not cleared when the new best block with the same number was added.
The usage of `is_best_block` argument in `add_block` method in _txpool_ tests were aligned with the `NewBestBlock` event.
=> txpool: TestApi best_block fix

client/merkle-mountain-range/src/aux_schema.rs, client/merkle-mountain-range/src/lib.rs, client/merkle-mountain-range/src/offchain_mmr.rs, client/merkle-mountain-range/src/test_utils.rs, frame/merkle-mountain-range/src/mmr/storage.rs
Prerequisite for fixing: #12864
=> Mmr client gadget - support pallet reset

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/publish.yml
Related to https://github.com/paritytech/release-engineering/issues/144.
After this is merged we move onto https://github.com/paritytech/ci_cd/issues/709.
=> Change crates publishing to be scheduled

frame/contracts/src/wasm/runtime.rs
Stabilize `[seal0] take_storage` as it's now [covered](https://github.com/paritytech/ink/pull/1492) with an e2e test.
=> [contracts] stabilize `[seal0] take_storage`

client/transaction-pool/src/graph/pool.rs
Fix shall prevent from wasting the CPU during the major sync. Block
transaction don't need to be re-validated when the txpool is empty.
Part of: #12903
=> txpool: don't validate block transactions if the pool is empty

frame/dex/src/benchmarking.rs, frame/dex/src/lib.rs
BalanceOf wasn't pulling its weight.
=> less indirection

frame/aura/src/lib.rs, frame/babe/src/lib.rs
When something tries to enact an authority change with an empty authority set, we will ignore this now.
=> Ignore empty authority changes

bin/node/cli/tests/common.rs, bin/node/cli/tests/remember_state_pruning_works.rs, client/cli/src/params/pruning_params.rs
The state pruning setting is stored in the database when it is created. In later runs it is fine to drop the `--state-pruning` CLI argument as the setting is stored in the database. The state db will only return an error if the stored state pruning doesn't match the state pruning given via CLI. Users of Polkadot have reported exactly this behavior. They had their nodes running without `--state-pruning`, but initially they had created a database using `archive`. With the latest Polkadot release their node rejected to start, because the default value is `256` which is different to `archive`.
Recently we improved the state pruning CLI handling and accidentally made the state pruning value always present (as we set some default value for the clap). If we could find out if a user has passed a …
=> Make CLI state pruning optional again

Cargo.lock, client/network/Cargo.toml, client/network/src/service/out_events.rs, client/utils/Cargo.toml, client/utils/src/mpsc.rs
This is a follow-up PR to https://github.com/paritytech/substrate/pull/12971 addressing code review issues.
polkadot companion: https://github.com/paritytech/polkadot/pull/6481
=> Runtime diagnostics for leaked messages in unbounded channels (part 2)

bin/node/executor/tests/basic.rs, frame/balances/src/migration.rs, frame/treasury/src/lib.rs
=> Improve inactive fund tracking

Cargo.lock, client/cli/Cargo.toml, client/cli/src/runner.rs, client/service/src/lib.rs, client/service/src/task_manager/mod.rs
When the node is shutting down, we give the Tokio runtime 60 seconds to shutdown. If after these 60 seconds there are still running tasks, we now print these tasks. This should help debugging nodes that have stalled tasks.
This pr introduces a `TaskRegistry` that keeps track of all running tasks. Each task registers and unregisters itself in this `TaskRegistry`.
=> Print "stalled" task on shutdown

client/network/common/src/sync.rs
I found this helpful during debugging, other data structures already have `Debug` implemented.
=> Derive `Debug` on `SyncStatus`

.gitlab-ci.yml
`zstd` is much faster for our needs than LZMA2-based `xz` which is used currently. Closes https://github.com/paritytech/ci_cd/issues/698.
=> Enable `zstd` for `rusty-cachier`

.gitlab-ci.yml
Fixes [absent](https://gitlab.parity.io/parity/mirrors/substrate/-/pipelines/235897) `zstd` as it's only available in the latest `production` image.
=> Unpin `ci-linux` and use the latest `production` tag as before

Cargo.lock, bin/node/executor/Cargo.toml, client/rpc-api/Cargo.toml, client/rpc/Cargo.toml, client/tracing/Cargo.toml, frame/transaction-payment/rpc/Cargo.toml, primitives/rpc/Cargo.toml, utils/frame/try-runtime/cli/Cargo.toml
Now that we're not depending on something that needed a higher rpc version we don't have to bump the rpc version. This leads to less noise in the main PR.
=> dex child PR: no longer a need to upgrade rpc version

client/state-db/src/lib.rs, client/state-db/src/noncanonical.rs
This PR is simply for displaying more info when the error `TooManySiblingBlocks` occurs.
=> Enrich TooManySiblingBlocks error info

client/db/src/lib.rs, client/state-db/src/lib.rs
We don't canonicalize on archive nodes and thus `best_canonical` always returned `None`. So, the moment such a node tried to force canonicalize, it was trapped in some endless loop.
This pr solves this by renaming `best_canonical` to `last_canonicalized` and also making the return value more clear by introducing a custom enum `LastCanonicalized`.
Closes: https://github.com/paritytech/substrate/issues/13028
=> Do not run `forced_canonicalization` for archive nodes

bin/node/runtime/src/lib.rs
Just one little change - remove unused constants from runtime configuration
=> remove unused constant: MaxValueSize

frame/nfts/Cargo.toml, frame/nfts/src/lib.rs, frame/nfts/src/types.rs
During the integration of the nfts pallet with the upcoming nft-fractionalization pallet here: #13008, I've noticed a few missing things:
1) it was not possible to set the CollectionConfig fields as they were private (the same applies to the `MintSettings`)
2) in order to mock the nfts pallet, I needed to use: `pallet_nfts::runtime_benchmarks_enabled! { type Helper = (); }` which required adding that line into the lib.rs: `sp_core::generate_feature_enabled_macro!(runtime_benchmarks_enabled, feature = "runtime-benchmarks", $);`
=> Fix NFTs pallet's integration issues

frame/nfts/src/features/create_delete_item.rs, frame/nfts/src/lib.rs, frame/uniques/src/functions.rs, frame/uniques/src/lib.rs
If the NFT was locked externally via the Locker trait, the owner shouldn't be able to burn it.
=> Disallow burning externally locked nfts

frame/nfts/src/impl_nonfungibles.rs, frame/nfts/src/tests.rs, frame/support/src/traits/tokens/nonfungible_v2.rs, frame/support/src/traits/tokens/nonfungibles_v2.rs
This PR adds 4 new methods to clear previously set NFT/Collection attributes via traits
=> Allow to clear nft attributes via traits

bin/node-template/runtime/src/lib.rs, bin/node/runtime/src/lib.rs, frame/executive/src/lib.rs, frame/nomination-pools/src/lib.rs, frame/support/src/traits.rs, frame/support/src/traits/try_runtime.rs, frame/try-runtime/src/lib.rs, utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
🚨 breaking changes:  
- `frame_try_runtime::TryRuntime::on_runtime_upgrade` changes its argument type from `bool` to `UpgradeCheckSelect`. See the companion for an integration example.
Non breaking:
- `try-runtime-cli`: The `--checks` arg of `on-runtime-upgrade` now also accepts: `all`, `none`, `pre-and-post` and `try-state` to select the check to run, instead of running all. The values need to be passed with an `=`.
This makes the type of checks selectable, which is desirable for faster testing since the try-state can take up to two hours for Polkadot when you only want to test the pre- and post-hooks.
(The CI does not realize it needs a companion, but it does)
Polkadot companion: https://github.com/paritytech/polkadot/pull/6498
=> Selectable on-runtime-upgrade checks

primitives/arithmetic/src/traits.rs
Follow up on https://github.com/paritytech/substrate/pull/12967#discussion_r1059864886 to make `BaseArithmetic` work with `Ensure`.  
It re-uses the code from `EnsureOpAssign` in `EnsureOp`, instead of the other way around, which incurred the `Copy` requirement.  
It does contain an artificial dependence of  `EnsureOp` on `EnsureOpAssign` to re-use code, but that should be fine since the trait bounds would be the same anyway.
Removes the `Copy` requirement from:
- `EnsureOp` and `EnsureOpAssign`
- `EnsureFrom` and `EnsureInto`: Not sure about this one since we now generate the error in every case. Could be *slightly* slower.
- Require `Ensure` for `BaseArithmetic`
cc @lemunozm
=> Remove `Copy` from `Ensure*` traits

client/consensus/aura/src/import_queue.rs
When we import the state, we can not fetch authorities to verify the seal etc. So, we can directly skip any verification.
=> Aura: Do not verify on state import

client/consensus/aura/src/import_queue.rs
After #13058 this check is now stale.
=> aura: remove stale check to skip execution

client/network/src/discovery.rs
Before libp2p 0.50.0 we used a quorum of one to fetch records from the DHT. In the pr that upgraded to libp2p 0.50.0 we accidentally changed this behavior. This pr brings back the old behavior of using a qorum of one and thus, a faster discovery. After finding the first value, we directly finish the query. There was also another behavior change in libp2p, they stopped automatic caching on remote nodes. This pr also brings back the remote caching on nodes that are nearest to the key from our point of view of the network.
The pr that changed the behavior in libp2p: https://github.com/libp2p/rust-libp2p/pull/2712
=> Kademlia: Speed-up the record fetching

frame/contracts/proc-macro/src/lib.rs, frame/contracts/src/exec.rs, frame/contracts/src/lib.rs, frame/contracts/src/wasm/mod.rs, frame/contracts/src/wasm/runtime.rs
Follow-up to #11888
This PR makes the documentation for all the defined host functions available trough the rustdoc of the pallet_contracts.
To build the docs:
- pass `doc` attribute to the macro like [`#[define_env(doc)]`](https://github.com/paritytech/substrate/blob/f8def8c6392fd2014a7afc3bd233d05862fdb61f/frame/contracts/src/wasm/runtime.rs#L999),
it will make it expand additional `pallet_contracts::api_doc::seal0`, `pallet_contracts::api_doc::seal1`, `...` modules each having its `Api` trait containing functions holding documentation for every host function defined by the macro;
- just run `cargo doc` as usual;
=> [contracts] Add docs generator for the contracts API to the `#[define_env]` macro

Cargo.lock, frame/election-provider-support/solution-type/Cargo.toml, frame/support/test/Cargo.toml, primitives/api/test/Cargo.toml, primitives/runtime-interface/Cargo.toml, test-utils/Cargo.toml
A feature was added to trybuild >1.0.70 avoid failing on different variant counts in the line `and 278 others`
fixes #12955
=> Update trybuild to avoid random test failures.

Cargo.lock, client/finality-grandpa/Cargo.toml, client/finality-grandpa/rpc/Cargo.toml, frame/grandpa/Cargo.toml, primitives/finality-grandpa/Cargo.toml
New version changes log targets from `afg` to `grandpa`. Related https://github.com/paritytech/substrate/pull/12875.
=> grandpa: bump version to v0.16.1

client/db/src/lib.rs
Just a little cleanup.
While digging through the code I found this `finalization_displaced_leaves` which is not used anywhere. Displaced leaves are getting merged into it in `note_finalized` but the result is never actually used, seems to be a leftover from a previous change.
=> Remove unused finalization_displaced variable in db

frame/system/src/lib.rs
`storage` parameter types are currently not usable as `BlockWeight`, since the `integrity_test` of `frame_system` runs outside of externalities and therefore fails. This MR just wraps it in externalities to allow that.
Having quickly adjustable block PoV weights would be useful for testing the limits on Rococo and Westmint.
=> Run `frame_system` integrity tests in Externalities

frame/fast-unstake/src/lib.rs, frame/nomination-pools/src/lib.rs, frame/staking/src/pallet/mod.rs
Adding some note to justify using twox hasher for storage maps where key is user generated.
**Longer explanation**
By convention, a storage map that has user generated key should use a cryptographic hasher (such as blake2). For storage maps which are populated by a signed `AccountId` as key though, it is fine to use twox hasher since generated `AccountId` is itself a secure hash.
=> [trivial] add note on usage of twox hash

frame/election-provider-multi-phase/src/benchmarking.rs, frame/election-provider-multi-phase/src/lib.rs, frame/election-provider-multi-phase/src/signed.rs, frame/election-provider-multi-phase/src/unsigned.rs, frame/staking/src/pallet/impls.rs, frame/staking/src/pallet/mod.rs, frame/staking/src/tests.rs
This PR refactors some events in the EPM pallet and staking with the goal of making it easier to trace runtime events related to the election provider and staking pallets:
**EPM pallet**
- `SolutionStored { compute, prev_ejected, origin: Option<T::AccountId> }` (modified).
- `PhaseTransitioned { from: Phase, to: Phase, round: u32}`: All the phase transition events (`Event::SignedPhaseStarted`, `Event::UnsighedPhaseStarted`) are replaced by a state transition event that keep the previous and next phase. This will also allow us to easily start emitting when the emergency and phase off start and all new future phases that we may need.
**Staking pallet**:
- `ForceEra { mode: Forcing }`: signals that a new `Forcing` mode was set.
In addition to refactoring and adding new events, this PR also …
=> EPM and staking events improvement

primitives/arithmetic/src/traits.rs, primitives/runtime/src/traits.rs
This PR extends #12967 with the `ensure_pow` function. I think this is also an interesting function to have along with the `ensure_ops` family methods.
`ensure_pow` acts similarly to `checked_pow` but returns an `ArithmeticError` instead.
Related #12754
=> Add ensure_pow method

frame/assets/src/lib.rs, frame/assets/src/migration.rs, frame/balances/src/lib.rs, frame/balances/src/migration.rs, frame/collective/src/lib.rs, frame/collective/src/migrations/v4.rs, frame/elections-phragmen/src/lib.rs, frame/elections-phragmen/src/migrations/v3.rs, frame/elections-phragmen/src/migrations/v4.rs, frame/membership/src/lib.rs, frame/membership/src/migrations/v4.rs, frame/session/src/lib.rs, frame/session/src/migrations/v1.rs, frame/system/src/lib.rs, frame/system/src/migrations/mod.rs, frame/tips/src/lib.rs, frame/tips/src/migrations/v4.rs, frame/uniques/src/lib.rs, frame/uniques/src/migration.rs
use the `LOG_TARGET` constant for more frame pallets.
get's us closer to: #12873
=> introduce log-target constant to more frame pallets

.gitlab-ci.yml, frame/support/test/tests/construct_runtime_ui/invalid_module_details.stderr, frame/support/test/tests/derive_no_bound.rs, frame/support/test/tests/pallet_ui/call_invalid_return.stderr
Also pins the CI image to the current staging with Rust 1.66, will revert back to the generic `production` tag after this is merged.
=> Update tests for 1.66 and switch CI to stable Rust 1.66

frame/nfts/src/features/attributes.rs, frame/nfts/src/features/create_delete_collection.rs, frame/nfts/src/features/create_delete_item.rs, frame/nfts/src/features/metadata.rs, frame/nfts/src/impl_nonfungibles.rs, frame/nfts/src/lib.rs, frame/nfts/src/tests.rs, frame/nfts/src/types.rs
As part of the upcoming feature to support the pre-signed claims those would allow to offload of the deposit onto the final NFT's receiver, we need to start tracking the metadata depositor in a similar way as we did for attributes.
=> [NFTs] Track item's metadata depositor

frame/referenda/src/migration.rs, frame/scheduler/src/lib.rs, frame/scheduler/src/tests.rs
Looks like we forgot to bump the scheduler code version from V3 to V4 here https://github.com/paritytech/substrate/pull/11649  
Chains who deployed a scheduler/genesis without this patch should manually set the scheduler version to 4 and not use `v3::MigrateToV4`.
=> Scheduler is already at V4

client/beefy/src/worker.rs
Minor change to logs but required to minimize spamming during initial BEEFY deployment.
=> [easy-but-important] client/beefy: fix logs

client/consensus/babe/src/lib.rs, client/consensus/epochs/src/lib.rs, client/consensus/epochs/src/migration.rs
Epoch changes data for the gap (i.e. the blocks below the warp sync point) was used to verify the blocks imported after a warp sync.
Currently this verification is not really required since all our security depends on the last finalized block.
Once the last finalized block is imported (i.e. the warp sync point) then we start importing all the previous blocks and we can detect a bad history only after we finished importing the block before the warp sync point.
We may think that in this way we may be tricked by a malicious full node into downloading an history of blocks that in the end we find out to not be good WRT the finalized block we warp synced to. However, the same type of attack can be performed by one of the initial authorities by feeding an history that is coherently signed …
=> Stop keeping track of epoch changes for the sync gap

.gitlab-ci.yml
Latest `production` image includes Rust 1.66.1.
=> CI: Unpin `ci-linux` and use Rust 1.66.1

client/beefy/src/keystore.rs, client/beefy/src/worker.rs, primitives/beefy/src/lib.rs
Still allows custom message hasher, but ties together the crypto used for private+public keys type and the signature type.
Prerequisite for verifying equivocations in https://github.com/paritytech/substrate/pull/13121
=> sp-beefy: align authority id key type with its signature type

frame/transaction-payment/asset-tx-payment/src/payment.rs, frame/transaction-payment/src/payment.rs
Can we use the balance trait here rather than enumerating all the trait bounds that we'd like Balance to have?
=> Use balance trait in transaction-payment pallets

primitives/core/src/crypto.rs
I'm build a tool that will need some secret URI staff, this will made SecretStringError easy to display
=> Annotate thiserror for sp_core::crypto::SecretStringError

bin/node/runtime/src/lib.rs, frame/benchmarking/src/lib.rs
The macros in frame-benchmarking relied on having all the macros imported, which isn't a behavior for a proper macro :D This pr fixes this by making all internal macro usages absolute.
Required for: https://github.com/paritytech/cumulus/pull/2072
=> frame-benchmarking: Macros should not force a particular env

client/api/src/backend.rs, client/rpc-api/src/state/mod.rs, client/rpc/Cargo.toml, client/rpc/src/state/mod.rs, client/rpc/src/state/state_full.rs, client/rpc/src/state/tests.rs, client/rpc/src/state/utils.rs, client/service/src/client/client.rs
This PR makes the following changes to the `storage_size` RPC call:
- When unsafe RPCs are *not* enabled there's now a timeout of 30s; if the `storage_size` call doesn't return a result within this time an error is returned. **This is a breaking change**, however it is a necessary one as the `storage_size` RPC is essentially broken the way it is right now where it's allowed to run forever. When unsafe RPCs *are* enabled the execution time is unbound as before.
- A streaming iterator is now used internally instead of preloading everything into memory first and then iterating over it.
- Add out-of-box support for timeouts into `jsonrpsee`. (I briefly looked since I know there is some support for resource use limiting in there, but I didn't see anything to limit the execution time of the RPC …
=> Fix the `storage_size`/`state_getStorageSize` RPC call

scripts/ci/gitlab/pipeline/zombienet.yml
zombienet tests should not fail
=> zobmienet tests are not supposed to fail

frame/contracts/Cargo.toml
Now that the crate is published to crates.io we should remove unnecessary files to bring down the crate size. This just removes all test fixtures and benchmark files.
=> contracts: Remove fixtures from crate

client/transaction-pool/api/src/lib.rs, client/transaction-pool/src/api.rs, client/transaction-pool/src/enactment_state.rs, client/transaction-pool/src/graph/base_pool.rs, client/transaction-pool/src/graph/listener.rs, client/transaction-pool/src/graph/pool.rs, client/transaction-pool/src/graph/ready.rs, client/transaction-pool/src/graph/validated_pool.rs, client/transaction-pool/src/lib.rs, client/transaction-pool/src/revalidation.rs, client/transaction-pool/tests/pool.rs
=> txpool: LOG_TARGET const added

Cargo.lock, client/executor/Cargo.toml, client/executor/runtime-test/Cargo.toml, client/executor/runtime-test/src/lib.rs, client/executor/src/integration_tests/mod.rs, client/executor/wasmtime/src/runtime.rs
> Once the `validate_block` function from a PVF has been executed, it will return a `u64` containing the pointer and length of the (encoded) return data in the wasm memory. This is [unpacked](https://github.com/paritytech/substrate/blob/5722ece5efb61cc82307f3e919a60bd4e807f1df/client/executor/wasmtime/src/runtime.rs#L763) and the length field is directly used to [allocate a memory buffer](https://github.com/paritytech/substrate/blob/5722ece5efb61cc82307f3e919a60bd4e807f1df/client/executor/wasmtime/src/runtime.rs#L796) on the host side without any prior lenght check, even if the returned length field is larger than the wasm memory. This allocation is only limited to 4 Gb by the `u32` range.
Addresses part 1 of https://github.com/paritytech/srlabs_findings/issues/257. Part 2 will require a …
=> Fix potential huge allocation as a result of `validate_block` output

client/network/src/peer_info.rs, client/network/src/protocol.rs
When running with `--no-private-ipv4` the node should not trying to connect to any private ip addresses. With the switch to libp2p this behavior was broken. Part of this version upgrade was the following pr: https://github.com/libp2p/rust-libp2p/pull/2995. This pr changed the default cache size of `libp2p-identity` from `0` aka disabled to `100`. Together with our implementation that was calling into `identity` to request addresses for a given peer. Before the switch to libp2p 0.50.0 this was returning zero addresses, but now with the cache enabled it started to return addresses. This pr fixes this by only letting discovery return addresses for a peer. It also ensures that we filter private addresses if requested. The cache is also disabled to restore the previous caching behavior, but it …
=> sc-network: Ensure private addresses are disabled if requested

bin/node/cli/src/service.rs, client/sysinfo/src/sysinfo.rs
Sorry the previous code was a bit stupid :man_facepalming:. This moves the requirements check and the printing logic into the CLI.  
cc @bkchr @Szegoo 
polkadot companion: https://github.com/paritytech/polkadot/pull/6269
cumulus companion: https://github.com/paritytech/cumulus/pull/1863
=> Move slow hardware warning print logic to CLI

frame/dex/src/lib.rs, frame/dex/src/tests.rs
Bugfix: We get the asset balances in the right order so we should not be inverting them.
=> dex quote bugfix

client/consensus/babe/src/tests.rs
The `authoring_blocks` test of BABE was calculating the slot based on the timestamp it sometimes failed in CI. The problem is that we combine all the notifications and authoring futures in one big future. This one big future may first polls one authoring future to build a block. Then it polls all notification futures again to import the block. Then some other authoring future is polled and builds on the imported block using the same slot and making the import fail. The solution is that we just artificially increase the slot to make the test work.
Part of: https://github.com/paritytech/substrate/issues/11321
=> Fix flaky BABE test

frame/system/src/lib.rs
The original error only had a panic(`panicked at 'assertion failed: Self::events().iter().any(|record| record.event == event)`), and there was no intuitive debug information. 
A custom panic message is now added to help with debugging.
=> Add debug info in assert_has_event and assert_last_event

client/cli/src/params/network_params.rs, client/network/common/src/config.rs, client/network/src/config.rs, client/network/src/discovery.rs, client/network/src/service.rs, client/service/test/src/lib.rs
Renames the `*-private-ipv4` to `*-private-ip` in the CLI interface. The old names are staying as alias, thus it will not break for anyone. Besides that it also fixes the naming in the rest of the code.
=> Rename `*-private-ipv4` to `*-private-ip` CLI args

frame/support/src/storage/types/counted_map.rs, frame/support/src/storage/types/map.rs
This potentially needs a migration for all the pallets using `CountedMap` and `set`, but I'm not sure how actionable that is. At the very least all the future occurrences will be fixed.
Fixes https://github.com/paritytech/substrate/issues/13212
=> [Fix] CountedMap::set now takes Counter into account

frame/system/src/lib.rs, frame/system/src/tests.rs
An attempt to improve a developer experience.
While developing tests or benchmarks it takes some time to figure out why the events are missing even though an extrinsic is being executed successfully.
=> Debug assert events at genesis

Cargo.lock, bin/node-sassafras/node/Cargo.toml, bin/node-sassafras/runtime/Cargo.toml, bin/node-sassafras/runtime/src/lib.rs, client/consensus/sassafras/Cargo.toml, client/consensus/sassafras/src/authorship.rs, client/consensus/sassafras/src/block_import.rs, client/consensus/sassafras/src/lib.rs, client/consensus/sassafras/src/verification.rs, frame/sassafras/Cargo.toml, frame/sassafras/src/lib.rs, primitives/consensus/sassafras/Cargo.toml, primitives/consensus/sassafras/src/lib.rs, test-utils/runtime/Cargo.toml, test-utils/runtime/src/lib.rs
Partially Addresses https://github.com/paritytech/substrate/issues/11515
Mostly aims to provide:
---
Flows into main Sassafras PR https://github.com/paritytech/substrate/pull/11879
=> Sassafras Iteration 3.1

Cargo.lock, utils/wasm-builder/Cargo.toml
This upgrades binaryen to version 111.
Binaryen (and wasm-opt) now enables the `SignExt` and `MutableGlobals` features by default, which are also enabled in the LLVM backend. In the future Binaryen will align its default feature selection with the LLVM backend.
This is _probably_ is ok for wasm-builder - wasmi supports both these.
This also points to potential future optimizations by explicitly turning on more features that wasmi supports but that aren't enabled in wasm-opt by default.
The [changelog](https://github.com/brson/wasm-opt-rs/blob/master/CHANGELOG.md) for 0.111.0.
=> Upgrade wasm-opt to 0.111.0

client/storage-monitor/src/lib.rs
Should fix: https://github.com/paritytech/substrate/pull/13082#discussion_r1085613384
[`blocks_available`](https://docs.rs/nix/latest/x86_64-apple-darwin/nix/sys/statvfs/struct.Statvfs.html#method.blocks_available) returns `u32` for Apple/Darwin (https://docs.rs/libc/0.2.139/x86_64-apple-darwin/libc/type.fsblkcnt_t.html). This fix should solve this problem.
=> storage-monitor: statvfs arithmetic bug fixed

frame/assets/src/benchmarking.rs, frame/assets/src/functions.rs, frame/assets/src/lib.rs
We are actually passing the `amount` on assets being minted and not the total supply.
Closes: https://github.com/paritytech/substrate/issues/13210
=> pallet-assets: Rename `total_supply` to `amount`

frame/contracts/proc-macro/src/lib.rs, frame/contracts/src/lib.rs, frame/contracts/src/schedule.rs
Follow-up to https://github.com/paritytech/substrate/pull/12976
Even for a single-byte reading operation, proofs of all merkle trie hashes would apparently be needed. Hence this static weight is added to all the storage reading functions.
=> [contracts] Add upfront weight of merkle trie proofs for storage reading functions

utils/frame/try-runtime/cli/src/commands/create_snapshot.rs, utils/frame/try-runtime/cli/src/commands/execute_block.rs, utils/frame/try-runtime/cli/src/commands/follow_chain.rs, utils/frame/try-runtime/cli/src/commands/offchain_worker.rs, utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs, utils/frame/try-runtime/cli/src/lib.rs
run the `create-snapshot`  command in Polkadot will get an error:
```
cargo run --features try-runtime -- try-runtime --runtime existing create-snapshot --uri wss://rpc.polkadot.io:443 --pallet indices
```
```
Invalid input: given runtime is NOT compiled with try-runtime feature!
```
=> Fix try-runtime with create-snapshot

frame/support/src/dispatch.rs, frame/support/src/weights.rs, frame/system/src/extensions/check_weight.rs, frame/system/src/lib.rs, primitives/weights/src/lib.rs, primitives/weights/src/weight_v2.rs
The arithmetical function naming of `PerDispatchClass` does not follow the usual convention.  
Also salvaging some small fixes from https://github.com/paritytech/substrate/pull/13164 
:rotating_light: breaking changes:
- Fix arithmetical semantic of `PerDispatchClass::`
- `add` renamed to `accrue`
- `checked_add` renamed to `checked_accrue`
- `sub` renamed to `reduce`
Non breaking:
- Introduce `sp_weights::Weight::{from_all, saturating_reduce, checked_accrue, checked_reduce}`
- Implement `From<u64>` and `From<(u64, u64)>` for `Weight` in testing environments
TODO:
=> Correct arithmetical semantic of `PerDispatchClass`

client/consensus/aura/src/import_queue.rs
We need to set the fork choice rule! When using Cumulus this is done by the `ParachainsBlockImport`, but for standalone chains we still need this!
Closes: https://github.com/paritytech/substrate/issues/13220
=> Aura: Fix warp syncing

bin/utils/subkey/README.md, client/beefy/src/tests.rs, client/consensus/babe/src/lib.rs, docs/README.adoc, frame/contracts/src/exec.rs, frame/elections-phragmen/src/benchmarking.rs, frame/nfts/src/features/transfer.rs, frame/nomination-pools/src/migration.rs, frame/nomination-pools/test-staking/src/lib.rs, frame/root-offences/src/tests.rs, frame/staking/src/tests.rs, frame/uniques/src/functions.rs
**Description:** 
This pull request updates the usage of binary pronouns to non-binary pronouns throughout the codebase to promote inclusivity and respect for individuals who do not identify as binary.
=> Use non-binary pronouns in comments.

frame/support/src/lib.rs, frame/support/src/storage/generator/value.rs, frame/support/src/storage/mod.rs, frame/support/src/storage/types/value.rs
closes #13133 
polkadot address: 12poSUQPtcF1HUPQGY3zZu2P8emuW9YnsPduA4XG3oCEfJVp
=> mutate_exists for StorageValue with ValueQuery

frame/multisig/README.md, frame/multisig/src/lib.rs, frame/nicks/README.md, frame/proxy/README.md, frame/sudo/README.md, frame/utility/README.md, frame/vesting/README.md
While going through the FRAME docs on Substrate I've noticed a few
broken links on a couple different Pallets. The link were related to
`Config` and `Call` types and there were broken links in both READMEs
and or Rust docs. This PR fix all of those broken links I've found.
=> docs: Fix broken documentation links for pallets

client/cli/src/params/pruning_params.rs, client/finality-grandpa/src/warp_proof.rs
When a node is running with `--blocks-pruning` it will also prunes justifications. So, the warp proof generation can not use `expect` for unwrapping the justification.
Closes: https://github.com/paritytech/substrate/issues/13168
=> sc-finality-grandpa: Warp proof generation can not expect justifications

bin/node-template/pallets/template/Cargo.toml, bin/node-template/pallets/template/src/mock.rs
- Remove trivial alias for `frame_system`
- Dev dependencies should not have `default-features = false`
=> Fix Up Node Template

primitives/runtime-interface/src/impls.rs
Currently runtime interface limits the size of u8 array to 96, because its implementation is generated from hard-coded macro expansion. This PR changes it to use generic instead of macro so as to support arbitrary-sized array.
=> Implement RIType traits for u8 array with an arbitrary size

bin/node-template/runtime/src/lib.rs, bin/node/runtime/src/lib.rs, frame/grandpa/src/lib.rs, frame/grandpa/src/migrations.rs, frame/grandpa/src/mock.rs, frame/grandpa/src/tests.rs
In the GRANDPA pallet we keep a mapping of `set id -> session index`, this is necessary to validate equivocation proofs. The entries in this map were never being pruned. This PR bounds the maximum number of entries in this mapping which will usually be set to the bonding duration (in sessions).
polkadot companion: https://github.com/paritytech/polkadot/pull/6626
=> grandpa: cleanup stale entries in set id session mapping

frame/support/src/storage/generator/double_map.rs, frame/support/src/storage/generator/nmap.rs, frame/support/src/storage/mod.rs, frame/support/src/storage/unhashed.rs
In both StorageDoubleMap and StorageNMap is possible to delete or iterate on entries over a certain prefix, but there's no easy and optimized way of checking if at least one of those entries exists.
If you think I should add tests for StorageNMaps and point me where to add them, I'll be happy to do it.
polkadot address: 12poSUQPtcF1HUPQGY3zZu2P8emuW9YnsPduA4XG3oCEfJVp
=> implemented `contains_prefix` for StorageDoubleMap and StorageNMap

frame/proxy/src/lib.rs, frame/proxy/src/tests.rs
The documentation was incorrect. 
I have updated it and written a test to confirm this.
=> Calling proxy doesn't remove announcement

Cargo.lock, client/consensus/babe/Cargo.toml, client/consensus/babe/src/lib.rs, frame/benchmarking/src/utils.rs, frame/contracts/primitives/Cargo.toml, frame/contracts/primitives/src/lib.rs, frame/support/src/traits/storage.rs, frame/support/src/traits/try_runtime.rs, frame/transaction-payment/src/types.rs, primitives/consensus/babe/src/lib.rs, primitives/core/src/lib.rs, primitives/finality-grandpa/src/lib.rs, primitives/inherents/Cargo.toml, primitives/inherents/src/lib.rs, primitives/merkle-mountain-range/src/lib.rs, primitives/runtime/src/generic/block.rs, primitives/runtime/src/transaction_validity.rs, test-utils/runtime/src/lib.rs
This PR derives the `scale_info::TypeInfo` for each type present in the runtime interface.
The change is required for substrate to generate the `RuntimeMetadata`; to allow higher-level applications to create an interface for calling runtime APIs.
This is part of: https://github.com/paritytech/substrate/issues/12939.
=> Metadata V15: Derive `TypeInfo` for describing runtime types

frame/ranked-collective/src/lib.rs
We use `EnsureMember` in Kusama runtime [here](https://github.com/paritytech/polkadot/blob/48de7a20d95a0ba87447e77ede531dc44cc7cd4a/runtime/kusama/src/governance/fellowship.rs#L306). This requires that there be a successful origin.  
Now there is no member at all and the referenda pallet does not know that it needs to add some to the ranked collective pallet.   IMO we have to add it in the `EnsureMember`. Other solutions welcome.
cc @acatangiu @lexnv 
Needed to unblock Polkadot CI https://github.com/paritytech/polkadot/pull/6663 and https://github.com/paritytech/polkadot/pull/6528
Fake companions to make the CI green:  
Polkadot companion: https://github.com/paritytech/polkadot/pull/6528
=> benchmarks: `EnsureRankedMember` must add ranked members

client/executor/runtime-test/src/lib.rs, client/executor/src/integration_tests/mod.rs
Quick follow-up to https://github.com/paritytech/substrate/pull/13183.
Mainly, I wanted to double check that the `test_return_max_memory_offset` test doesn't pass just because the output length is 0.
I also:
- Organized these tests into a module.
- Added a comment explaining why we don't use the `wasm_export_functions` macro.
=> Minor: Update output validity tests

client/executor/wasmtime/src/runtime.rs
Following https://github.com/paritytech/substrate/issues/11949, this PR will allow parachains with runtimes bigger than Kusama to use the pooling strategy.
=> feat(client): significantly increase wasm instance limits

Cargo.lock, frame/benchmarking/Cargo.toml, frame/benchmarking/src/analysis.rs
Updates linregress in frame-benchmarking to ~0.5.0~ 0.5.1 to avoid deprecation warning coming from nalgebra dependency. Had to make one change in `analysis.rs` because of some syntax changes in linregress.
deprecation warning was reported here: https://github.com/paritytech/substrate/issues/13132#issuecomment-1416515455
=> update linregress in frame-benchmarking to 0.5.1

frame/examples/offchain-worker/src/lib.rs
Update the divider in off-chain-worker example
=> Fix: Off-chain-worker example

primitives/beefy/Cargo.toml, primitives/keyring/Cargo.toml
My PR [here](https://github.com/paritytech/polkadot/pull/6661) fails with a weird error on CI:
```
error[E0152]: duplicate lang item in crate `std` (which `strum` depends on): `panic_impl`.
|
= note: the lang item is first defined in crate `sp_io` (which `pallet_election_provider_multi_phase` depends on)
= note: first definition in `sp_io` loaded from /builds/parity/mirrors/polkadot/target/testnet/wbuild/polkadot-runtime/target/wasm32-unknown-unknown/release/deps/libsp_io-f050ec3b6933463a.rmeta
= note: second definition in `std` loaded from /usr/local/rustup/toolchains/nightly-2022-11-16-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libstd-65032bf6a898adaa.rlib
```
I reproduced it locally, and disabling default features for the `strum` crate seems to fix it (it has an …
=> Disable default features for `strum` (fix `polkadot` CI)

client/db/src/lib.rs
Current code using `blockchain.hash(..)` does not account for potential re-orgs that may be happening in the same DB transaction. In particular in a rare case when there are 3 branches and finalization happens along with a reorg to a longer branch, this may lead to a block being deleted from the canonical chain.
Fixes #13186
=> Fix block pruning after long re-org

frame/contracts/proc-macro/src/lib.rs, frame/contracts/src/wasm/mod.rs
Follow up for https://github.com/paritytech/substrate/pull/13032
Initially, different versions of APIs are emitted into different modules. IMHO that makes discovering all functions harder because you need to look through all modules. Additionally, we also emitted all the functions twice which are exist under different prefixes.
This PR changes this behaviour by only emitting the newest and unprefixed version of each function. Hence we now only have a single trait containing everything relevant.
=> contracts: Rework generated API docs

frame/scheduler/src/lib.rs, frame/scheduler/src/tests.rs, frame/support/src/traits/preimages.rs
The scheduler was not requesting a preimage. When a preimage is requested, a user can deposit it without paying any fees.
=> pallet-scheduler: Ensure we request a preimage

.gitlab-ci.yml, zombienet/0001-basic-warp-sync/test-warp-sync.toml, zombienet/0002-validators-warp-sync/test-validators-warp-sync.toml, zombienet/0003-block-building-warp-sync/test-block-building-warp-sync.toml
Update zombienet version to the latest (v1.3.34) and update the links of the snapshots since the new version require a different directory structure for the snapshots (after this [pr](https://github.com/paritytech/zombienet/pull/673)).
cc @michalkucharczyk @skunert
=> bump version of zombienet and update snaps links

client/finality-grandpa/src/environment.rs, client/finality-grandpa/src/tests.rs
After https://github.com/paritytech/substrate/pull/12477 we started fetching the best block from `SelectChain` to pass along to the voting rules so that they can use this information to potentially restrict the votes. We have an assumption that the best block as returned by `SelectChain` is equal to or a descendant of the finality target. If this assumption doesn't hold, either due to a possible race condition or because of a `SelectChain` implementation that doesn't respect this invariant, we will throw an error and the voter will quit. This PR changes this logic to instead override the best block to be the same as the target block whenever this assumption isn't respected (which is the same behavior we had before https://github.com/paritytech/substrate/pull/12477).
Related #13254.
=> grandpa: don't error if best block and finality target are inconsistent

.maintain/frame-weight-template.hbs, primitives/weights/src/weight_v2.rs, utils/frame/benchmarking-cli/src/pallet/template.hbs
Was browsing through PRs using the new weight template, and I think it would be really more clear to break down each component, rather than using `from_parts`. As I understand, this will also make weights more "forwards" compatible, such that if we add more components, the usage of `from_parts` will not break.
Finally, removing weird APIs which assume you would ever want to scalar add the same amount to both `ref_time` and `proof_size`. This seems like nonsense, since these are totally different units of measurement.
=> Improve Weight Template and API

client/beefy/src/communication/peers.rs, client/beefy/src/communication/request_response/outgoing_requests_engine.rs, client/beefy/src/tests.rs, client/beefy/src/worker.rs
For on-demand justifications, peer selection is based on witnessed gossip votes. This commit changes the condition for selecting a peer to request justification for `block` from
`last voted on >= block` to `peer last voted on > block`.
When allowing `>=` we see nodes continuously spamming unsuccessful on-demand requests to nodes which are still voting on a block without having a justification available.
One way to fix the spam would be to add some rate-limiting or backoff period when requesting justifications.
The other solution (present in this commit) is to simply request justifications from peers that are voting on future blocks so we know they're _guaranteed_ to have the wanted mandatory justification available to send back.
=> client/beefy: request justifs from peers further in consensus

.github/workflows/auto-label-issues.yml
=> [ci] Change GHA to add J2 labels instead Z0

client/db/src/lib.rs, client/state-db/src/lib.rs
When running a node with `--state-pruning archive-canonical` it was directly failing on genesis. There was an issue in the state-db `pin` implementation. It was not checking the state of a block correctly when running with archive canonical (and also not for every other block after they are canonicalized).
Closes: https://github.com/paritytech/substrate/issues/12824
Closes: https://github.com/paritytech/substrate/issues/13269
=> sc-client-db: Fix `PruningMode::ArchiveCanonical`

client/finality-grandpa/src/finality_proof.rs, client/finality-grandpa/src/lib.rs
It will be helpful if export the low level api for grandpa.
=> feat: improve FinalityProofProvider api

frame/timestamp/src/lib.rs, primitives/timestamp/src/lib.rs
The error variant wasn't that useful and it was also used wrongly in the code. In the code we returned this variant when the `timestamp < minimum`. The problem of this is that we waited on the node side some time, but then `set` function rejects the timestamp because of the same check (the timestamp in the block stays the same). We ensure that the timestamp isn't drifting too much in the future, but waiting for the timestamp to be "valid" would open some attack vector. The consensus protocols also compare the slots in the blocks to ensure that there isn't a block from the future and in the runtime we then ensure that `slot = timestamp / slot_duration`. So, we can just remove this variant and replace it with a new variant `TimeBetweenBlocksTooShort` to not even try importing a block which …
=> pallet-timestamp: Remove `ValidAtTimestamp` error variant

scripts/ci/docker/subkey.Dockerfile.README.md, scripts/ci/gitlab/pipeline/publish.yml
Added `subkey` Docker image description for hub.docker.com. More like a draft. Please review and feel free to propose changes.
CI: added GitLab job to push above-mentioned description to the hub.docker.com
=> CI add subkey docker image description and CI job to publish it to the hub.docker.com

scripts/ci/gitlab/pipeline/publish.yml, scripts/ci/gitlab/pipeline/test.yml
Helps with fixing issues like this: https://gitlab.parity.io/parity/mirrors/substrate/-/pipelines/246923
=> [ci] Move publish-crates-locally to publish stage

scripts/ci/gitlab/pipeline/publish.yml
Publishing crates depends on `publish-crates-locally`. If this job fails no publishing should be done
=> [ci] Add dependencies for publish-crates

client/network/src/protocol/notifications/handler.rs, client/network/src/protocol/notifications/upgrade/notifications.rs
Detect that `NotificationOutSubstream` was closed by the remote even if we don't write data into it.
Fixes https://github.com/paritytech/substrate/issues/12435.
In `Notifications` we use two duplex substreams for outgoing and incoming notifications. After the initial handshake, each substream becames a unidirectional stream of data. Unfortunately, `Sink::poll_flush` called on libp2p socket does not produce an error if the substream was dropped on the remote until we write some data into it. In order to overcome this limitation, this PR adds polling of the out_substream for incoming messages (which should be none) in `<NotificationOutSubstream as Sink>::poll_flush` to detect that the stream has terminated (was dropped/closed by the remote).
It may be worth filing a bug to libp2p to expose …
=> network: Detect early that `NotificationOutSubstream` was closed by the remote

frame/babe/src/lib.rs, frame/babe/src/tests.rs
When validating an equivocation proof we need to validate a key ownership proof for the validator that committed the offence at a given epoch. The key ownership proof exists in the context of a given session, therefore we must also validate the mapping between an epoch and a session. Normally these are synced (i.e. `epoch index == session index`), but if epochs are skipped this invariant is broken. This PR adds tracking of skipped epochs so that we can properly validate equivocation proofs after epochs are skipped.
=> babe: account for skipped epochs when handling equivocations

client/network/src/protocol/notifications/handler.rs, client/network/src/protocol/notifications/upgrade/notifications.rs
Reverts paritytech/substrate#13396
After the PR the reported peer count dropped to ~0 peers, and sync doesn't really work (best block reported stays the same). I was not able to find a quick fix for this, so let's revert the PR for now.
=> Revert "network: Detect early that `NotificationOutSubstream` was closed by the remote"

client/state-db/src/lib.rs, client/state-db/src/noncanonical.rs, client/state-db/src/pruning.rs
This pr changes state-db to print a warning when using a large pruning window and running with a database that isn't supporting ref-counting like RocksDb. This makes the user aware of potential out of memory errors because this option together with RocksDb etc puts the entire pruning window into memory. Besides that the pr introduces `LOG_TARGET` for having the target declared central!
=> state-db: Print warning when using large pruning window on RocksDb

client/beefy/src/import.rs, client/beefy/src/tests.rs
BEEFY pallet allows setting on-chain BEEFY genesis to some future block.
Disregard any BEEFY justifications attached to imported blocks that predate configured BEEFY genesis.
Fixes a memory "leak" or bloat where before this PR, "invalid/stale" justifications are enqueued on some channel to be processed by the voter, but the voter task doesn't process the queue until pallet is enabled.
With this PR, justifications are no longer enqueued until pallet is enabled; stale justifications are simply dropped.
=> client/beefy: drop justification on block import if pallet-beefy not enabled

frame/contracts/src/wasm/runtime.rs
Tiny change to make it possible for ink! side to stay [consistent](https://github.com/paritytech/ink/pull/1641#discussion_r1107921565) with the pallet in error names.
=> [contracts] rename call_runtime() returned error

frame/beefy-mmr/src/mock.rs, frame/beefy/src/lib.rs, frame/beefy/src/mock.rs, frame/beefy/src/tests.rs
Add limit for the number of entries in the `SetIdSession` mapping.
For example, it can be set to the bonding duration (in sessions).
Closes https://github.com/paritytech/substrate/issues/13404
Polkadot companion: https://github.com/paritytech/polkadot/pull/6743
=> frame/beefy: prune entries in set id session mapping

frame/support/src/traits/misc.rs
- Change the `defensive!` to use `expr` instead of `tt` and allow a trailing comma.  
- Add a `defensive_assert!` macro for convenience. Example:  
```rust
use frame_support::defensive_assert;
std::panic::catch_unwind(|| {
defensive_assert!(1 == 0, "Must fail")
}).unwrap_err();
```
I am not sure how diligently we use the `note_worthy` label, so I will put it there for now.
=> Add `defensive_assert!` macro

bin/node/runtime/src/lib.rs, frame/democracy/src/lib.rs, frame/democracy/src/tests.rs
This PR adds a `SubmitOrigin` to the democracy pallet.
It replaces the plain `ensure_signed` within the `propose` extrinsic.
To achieve the old behavior, the users of the pallet can insert the following line into the Config:
```rust
type SubmitOrigin = EnsureSigned<AccountId>;
```
Polkadot companion: https://github.com/paritytech/polkadot/pull/6750
=> Introduce EnsureOrigin to democracy.propose

scripts/ci/docker/substrate.Dockerfile.README.md, scripts/ci/gitlab/pipeline/publish.yml
Publish `substrate` docker image description to hub.docker.com.
For now just a stub for description `scripts/ci/docker/substrate.Dockerfile.README.md`. 
Later, when this file get updated, its content will be automatically published as description for https://hub.docker.com/r/parity/substrate
Little optimisation to `subkey` description publish.
Related to https://github.com/paritytech/ci_cd/issues/741
=> CI Publish `substrate` docker image description to hub.docker.com. 

Cargo.lock, Cargo.toml, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs, frame/nfts/runtime-api/Cargo.toml, frame/nfts/runtime-api/README.md, frame/nfts/runtime-api/src/lib.rs, frame/nfts/src/impl_nonfungibles.rs, frame/support/src/traits/tokens/nonfungible_v2.rs, frame/support/src/traits/tokens/nonfungibles_v2.rs
This PR contains changes to the `frame_support::trait::tokens::nonfungible(s)_v2::Inspect` trait:
* `attribute` now doesn't take the `namespace` argument
* Added `custom_attribute` function
* Added `system_attribute` function
* The `typed`-companions are also added
A runtime API is added for the NFTs pallet. The interface is the same as in the `Inspect` trait.
Some docs were modified.
Cumulus Companion: https://github.com/paritytech/cumulus/pull/2217
=> Nfts attribute read interface

client/api/src/backend.rs, primitives/state-machine/src/backend.rs, primitives/state-machine/src/ext.rs, primitives/state-machine/src/lib.rs, primitives/state-machine/src/trie_backend.rs, primitives/state-machine/src/trie_backend_essence.rs
Followup of https://github.com/paritytech/substrate/pull/13284
This PR further cleans up the storage backend trait and gets rid of (now unnecessary) callback-based iteration methods.
=> Further storage iterator refactoring

Cargo.lock, frame/support/Cargo.toml, frame/support/procedural/src/pallet/expand/call.rs, frame/support/src/dispatch_context.rs, frame/support/src/lib.rs, frame/support/test/tests/pallet.rs, frame/treasury/Cargo.toml, frame/treasury/src/lib.rs, frame/treasury/src/tests.rs
When calling `spend` the origin defines the `max_amount` of tokens it is allowed to spend. The problem is that someone can send a `batch(spend, spend)` to circumvent this restriction as we don't check across different calls that the `max_amount` is respected. This pull request fixes this behavior by introducing a so-called dispatch context. This dispatch context is created once per outer most `dispatch` call. For more information see the docs in this pr. The treasury then uses this dispatch context to attach information about already spent funds per `max_amount` (we assume that each origin has a different `max_amount` configured). So, a `batch(spend, spend)` is now checked to stay inside the allowed spending bounds.
Fixes: https://github.com/paritytech/substrate/issues/13167
=> `pallet-treasury`: Ensure we respect `max_amount` for spend across batch calls

bin/node/cli/src/service.rs, client/service/src/error.rs
Removed `Service::Error::Storage` variant. Refer to: https://github.com/paritytech/substrate/pull/13082/files#r1118920136
=> Service::Error: Storage variant removed

client/cli/src/params/network_params.rs
Establish fewer outbound connections in an attempt to allow publicly available nodes to accept more full nodes.
Maintain the overall number of connections node should establish.
=> Adjust the ratio of the `in-peers`/`out-peers`

Cargo.lock, client/network/Cargo.toml, client/network/src/service/out_events.rs
Obsoletes https://github.com/paritytech/substrate/pull/13117. I am also going to replace `futures-channel` with `async-channel` in `client/utils/mpsc`, but this will break the API of [`TracingUnboundedSender`](https://github.com/paritytech/substrate/blob/f2615a4db8bf38927ef961aad926a007f3b4b8ca/client/utils/src/mpsc.rs#L117) (`async-channel` does not implement `Sink` trait), so decided to start with smaller changes in `out_events.rs`
polkadot companion: https://github.com/paritytech/polkadot/pull/6800
CC @nazar-pc
=> Make unbounded channels size warning exact (part 1)

frame/contracts/src/chain_extension.rs
Exposing `ChargedAmount` type through `chain_extension` module. It shouldn't do anything harmful, since we still cannot construct it ourselves, guaranteeing that it was constructed by runtime internals.
1. https://github.com/727-Ventures/obce/blob/liminal-v0.9.32/src/substrate/mod.rs#L190
`OBCE` generates glue code that automatically constructs `ExtensionContext`, with `ChargedAmount` passed to it when weight pre-charging is enabled. To actually refer to the `ChargedAmount` type, we need it exposed. 
2. https://github.com/Cardinal-Cryptography/aleph-node/blob/91d084ef04b82af1efa8c3a566fb4f7fe118ddab/bin/runtime/src/chain_extension/environment.rs#L19
For testing chain extension it is sometimes useful to mock charging. However, in order to abstract it, we also have to know appropriate type …
=> Expose `ChargedAmount`

client/consensus/beefy/src/metrics.rs
Fixes typo in metrics registration that was leading to registration errors, add test for it.
=> sc-consensus-beefy: fix metrics: use correct names

frame/im-online/src/lib.rs, frame/im-online/src/tests.rs
Whenever a validator commits an offence it gets kicked out of the validator set. On top of that, if the offence leads to a slash the validator will also get disabled, this means that even though the validator is part of the validator set, until the era ends when it should get kicked out, it cannot author new blocks. This PR changes the behavior for "offlineness" offences, such that even if the validator gets slashed it will not be disabled and thus can participate in consensus until the end of the era (when it should still get kicked out of the validator set).
For "offlineness" offences we only trigger slashing if more than 10% of the validator set is determined to be offline. I believe there is no advantage in disabling validators for "offlineness" since they're not actively trying to …
=> im-online: don't disable offending validators

primitives/consensus/beefy/src/lib.rs, primitives/merkle-mountain-range/src/lib.rs
Both `BeefyApi` & `MmrApi` have so far been evolving without versioning. This PR sets the current API that's been stable at least since we've reset MMR storage to `api_version(2)`. `BeefyMmrApi` has not changed since inception hence I've left this at implicit `api_version(1)`.
polkadot companion: https://github.com/paritytech/polkadot/pull/6809
=> bump API versions of {Beefy,Mmr}Api

frame/nfts/src/lib.rs
Emits new event and will make the `PalletAttributes` enum appear in the metadata
=> [NFTs] Emit new PalletAttributeSet event

.github/ISSUE_TEMPLATE/feature.yaml
=> fix feature/enhancement issue template

client/service/src/lib.rs
I forgot this in https://github.com/paritytech/substrate/pull/12291
=> Expose `new_full_parts_with_genesis_builder` from sc-service

primitives/runtime/src/generic/block.rs
The BlockId serde is never used in substrate.
And I think it's a bad design. It could not be used in rpc api.
=> remove serde derive for BlockId

primitives/core/src/ed25519.rs, primitives/core/src/sr25519.rs
I believe this was used in rhododendron and it's unused ever since. It's just a plain type with no functionality attached, I don't see any reason to keep it around.
=> core: remove unused localized signature type

docker/README.md, docker/substrate_builder.Dockerfile
Refer to Issue #13071 
Removes all the binaries after using the `ldd` command, otherwise if it's done the other way around the `ldd` command no longer exists. Also updated the associated README.md
@bkchr @ggwpez 
- Any panickers in the runtime have a proof or were removed.
=> fix: Fixes #13071 change order of ldd command and update ./docker/README.md

Cargo.lock, bin/node-template/runtime/Cargo.toml, bin/node-template/runtime/src/lib.rs
Undeploying the insecure randomness pallet from the node-template so that teams don't accidentally have it in the production runtime when using the template.
=> Undeploy insecure randomness pallet

client/consensus/grandpa/src/communication/gossip.rs
As part of the GRANDPA gossip protocol peers exchange small messages (neighbor packets) to inform their peers on what is their local view of the GRANDPA protocol, i.e. what round and set id they are currently observing. This is then used by the gossip logic to avoid gossiping information that peers aren't interested in (either stale or future). Currently these neighbor packets aren't sent to light clients, the reasoning being that since light clients aren't following the full GRANDPA protocol (i.e. they just import commits to finalize blocks), they don't need to care about the state of the peers they are connected to. Still this information can be useful to light clients around validator set boundaries, since it allows light clients to make an informed decision on who to ask …
=> grandpa: send neighbor packets to light clients on set transition

frame/nfts/src/lib.rs
Background:
I'm trying to build a pallet to work with pallet_nft,
my goal is disable most of pallet_nfts extrinsic and my pallet will help to management collection, minting nfts and update them, users can only own and burn, rest of other operations are limited.
my first try is using nonfungibles_v2 traits but meet some trouble (I make a PR https://github.com/paritytech/substrate/pull/13514 ), but I don't know how to construct ItemId so I'm stuck.
here's second try, I'm letting my pallet extending pallet_nft (`pub trait Config<I: 'static = ()>: frame_system::Config + pallet_nfts::Config<I>`), so I can access pallet_nft directly, and most of functions are public so I can call them, however, some of arguments require read from storage (e.g. `collection_id`) are restricted by `pub(super)` so …
=> Make pallet_nfts storages public

frame/nfts/src/types.rs
This would allow construct `ItemConfig` directly, e.g.
```
let config = ItemConfig {
settings: ItemSettings::from_disabled(ItemSetting::Transferable | ItemSetting::UnlockedMetadata),
}
```
Opinions:
- `ItemConfig` default is ambiguous, you don't know by default `ItemSettings` is all enabled or disabled
- Maybe `mint_into` should allow optional `item_config`, when `None` it will use collection's `default_item_settings`
=> Nfts: Make ItemConfig members public

frame/nfts/src/lib.rs, frame/nfts/src/tests.rs, frame/nfts/src/types.rs, frame/support/src/traits/tokens.rs, frame/support/src/traits/tokens/misc.rs
1) Renames `let MintWitness { owner_of_item }` to `let MintWitness { owned_item }`
Since we need to specify here item's id, and not the owner
2) Moves AttributeNamespace into the pallet-nfts types file. At some point, we needed to have the `AttributeNamespace` defined in a general file in order to use them in nonfungible traits, but later we removed that dependency and could safely put that enum back
=> Nfts: minor fixes

frame/babe/src/equivocation.rs, frame/beefy-mmr/src/mock.rs, frame/beefy/src/equivocation.rs, frame/beefy/src/lib.rs, frame/beefy/src/mock.rs, frame/grandpa/src/equivocation.rs, frame/grandpa/src/lib.rs, frame/grandpa/src/mock.rs, frame/grandpa/src/tests.rs, frame/offences/benchmarking/src/lib.rs
https://github.com/paritytech/substrate/pull/13425 follow up
Please refer to the linked PR for details
(Note: this PR contains few modifications to the grandpa/babe docs that can be safely ignored)
---
polkadot companion: https://github.com/paritytech/polkadot/pull/6845
=> BEEFY: introduce offence report system

frame/assets/src/functions.rs, frame/assets/src/lib.rs, frame/assets/src/mock.rs, frame/assets/src/tests.rs
Improves `AssetsCallback` trait by introducing `Result<(), ()>` as the return type.
This allows callback to inform the pallet whether the asset creation (or destruction) should complete or not.
Also moves the `destroyed` callback invocation to `do_finish_destroy` function.
=> pallet-assets callback improvement

client/consensus/slots/src/lib.rs
Calculate remaining proposal duration once and also use proposal time as timeout for creating the inherent data.
=> sc-slots: Cleanup

frame/nfts/src/benchmarking.rs, frame/nfts/src/features/create_delete_item.rs, frame/nfts/src/features/roles.rs, frame/nfts/src/lib.rs, frame/nfts/src/tests.rs
This PR allows setting the Issuer/Admin/Freezer accounts to `None` without the ability to change it back (except for root calls).
This is useful for cases when the collection is created, all the items are minted and now we want to be 100% sure no one will mint any more items, or change the metadata, or disable some item's transfer.
=> [NFTs] Allow to set the role to None

Cargo.lock, primitives/api/proc-macro/Cargo.toml, primitives/api/proc-macro/src/common.rs, primitives/api/proc-macro/src/decl_runtime_apis.rs, primitives/api/proc-macro/src/impl_runtime_apis.rs, primitives/api/proc-macro/src/mock_impl_runtime_apis.rs, primitives/api/proc-macro/src/utils.rs, primitives/api/test/tests/decl_and_impl.rs, primitives/api/test/tests/ui/impl_missing_version.stderr
This pr introduces the `expander` crate to expand the generated source code into a file. This gives better error reporting when trying to fix issues in the macro itself as Rustc will point to the line in this file. The feature can be enabled by setting `SP_API_EXPAND=1` at compile time.
Besides that the code generation is changed to fix warnings in the expanded version.
=> sp-api: Support expanding the macro code

bin/node/runtime/src/lib.rs, frame/election-provider-multi-phase/src/lib.rs, frame/election-provider-multi-phase/src/mock.rs, frame/election-provider-multi-phase/src/signed.rs, frame/election-provider-multi-phase/src/unsigned.rs
The goal with this commit is to expose the `feasibility_check ` such that anyone that implements the `MinerConfig trait` can utilize it.
polkadot companion: https://github.com/paritytech/polkadot/pull/6842
=> frame epm: expose `feasibility_check` in MinerConfig

primitives/weights/src/lib.rs, primitives/weights/src/weight_v2.rs
Zero logic refactor as preparation for https://github.com/paritytech/cumulus/pull/2326.  
Changes:
- add `Weight::{without_ref_time, without_proof_size}`.
- Add a  `FeePolynomial` to properly type the weight polynomial coefficients in a OOP manner to reusability downstream.
Eventually the `WeightToFeePolynomial` should be two dimensional, but i want to keep this MR minimal for now.
=> Add dedicated `FeePolynomial` struct

bin/node/runtime/src/lib.rs, frame/salary/src/lib.rs, frame/salary/src/tests.rs, frame/support/src/traits/tokens.rs, frame/support/src/traits/tokens/pay.rs
- Moved the `Pay` trait to live in `frame_support`.
- Added a new associated type `AssetKind` to enable usage of this trait via XCM (and possibly others?).
- Changed `AccountId` to `Beneficiary` since we may want to pay more general concepts like XCM's `MultiLocation`
- Used unit type for `AssetKind` on the salary pallet
Solves https://github.com/paritytech/substrate/issues/13603.
=> Make Pay trait from salaries pallet more generic

frame/examples/offchain-worker/src/lib.rs
Fixes a few typos caught while I was looking through the example pallet.
=> Fix typos in example pallet

Cargo.lock, client/consensus/grandpa/Cargo.toml, client/consensus/grandpa/rpc/Cargo.toml, frame/grandpa/Cargo.toml, primitives/consensus/grandpa/Cargo.toml, primitives/consensus/grandpa/src/lib.rs
This was required to remove a temporary implementation of `Eq` trait for the grandpa's equivocation struct.
Done this as soon as `finality-grandpa 0.16.2` has been published on crates.io (before I forget)
=> Bump grandpa to 0.16.2

Cargo.lock, primitives/state-machine/Cargo.toml, primitives/state-machine/src/trie_backend.rs
This PR bumps `trie-db` to version 0.27.1 (see [this PR](https://github.com/paritytech/trie/pull/190) for details) which mainly changes two things:
1) It fixes a bug with storage iteration where in certain cases the iterator would return keys outside of the specified prefix (see [this issue](https://github.com/polkadot-js/apps/issues/9103) for details)
2) It changes how the iterator works when both a prefix and a key from which to start iteration from is specified. This cleans up some corner cases and solidifies the behavior of how the iteration works which, AFAIK, previously was entirely accidental. The iteration now always follows the following two rules:
* All of the keys returned by the iterator are guaranteed to start with the specified prefix (if present).
* All of the keys returned …
=> Bump `trie-db` to 0.27.1 (fix storage iteration bug + change seek behavior with prefix)

bin/node/executor/tests/basic.rs, frame/contracts/src/benchmarking/mod.rs, frame/contracts/src/exec.rs, frame/contracts/src/lib.rs, frame/contracts/src/storage.rs, frame/contracts/src/tests.rs, frame/contracts/src/wasm/mod.rs, frame/contracts/src/wasm/runtime.rs
fix https://github.com/paritytech/substrate/issues/13594
=> contracts: Refactor `trait Ext::*_storage_transparent` functions

frame/nis/src/benchmarking.rs
https://github.com/paritytech/polkadot/pull/6780 is currently stuck because of a rounding error in the NIS pallet / `sp-arithmetic`.  
This MR hot-fixes it by increasing the pot amount to make the benchmark pass. Obviously not a proper *fix*, but something to unblock the CI for everyone else.
=> Hotfix NIS benchmark

frame/executive/src/lib.rs
=> frame::executive: `LOG_TARGET` const added

scripts/ci/gitlab/pipeline/publish.yml
Fixes CI jobs for publishing docker images description to hub.docker.com
Also removed `publish-refs` from those jobs, as we only should publish images description when its merged into master
=> fix publish docker description ci job

scripts/ci/gitlab/pipeline/publish.yml
Currently those jobs also get included in multi-project pipelines such as https://gitlab.parity.io/parity/mirrors/scripts/-/pipelines/255546, even when the description hasn't actually changed, because `changes:` conditions always evaluate to true on non-branch pipelines.
=> only push docker descriptions on master branch pipelines

client/rpc/src/state/mod.rs, client/rpc/src/state/state_full.rs, client/rpc/src/state/tests.rs, client/service/src/builder.rs, client/tracing/src/block/mod.rs
Close #13623 
This limit on `state_traceBlock RPC` is not needed anymore as the JSON-RPC servers doesn't terminate the connection if the RPC max limit is exceeded anymore
Until this PR is merged, it's also possible to run `--rpc-max-payload <LIMIT>` for the limit in the state RPC to work properly.
=> refactor: state RPC remove `max_rpc_payload_size`

Cargo.lock, frame/core-fellowship/Cargo.toml
These pallets are not just required for tests, but also for the runtime-benchmarks feature.
CI is currently [failing on master](https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2559380) due to this.
=> core-fellowship: promote dev-dependencies to regular dependencies

client/network/sync/src/engine.rs
Remove some leftover light-client code.
`SyncingEngine` instantiated here: https://github.com/paritytech/substrate/blob/91e0d66258a5143e2f4fa9bbf591d0ded4cd44b0/client/service/src/builder.rs#L830 
Can not be light client : https://github.com/paritytech/substrate/blob/91e0d66258a5143e2f4fa9bbf591d0ded4cd44b0/client/network/common/src/role.rs#L100-L107
=> Remove unused light-client leftover

Cargo.lock, client/rpc-spec-v2/Cargo.toml, client/rpc-spec-v2/src/chain_head/mod.rs, client/rpc-spec-v2/src/chain_head/test_utils.rs, client/rpc-spec-v2/src/chain_head/tests.rs
This PR checks the correct behavior of the chainHead RPC API when the
`FinalizedNotification` is received before the `BlockImportNotification`. 
To achieve this a `ChainHeadMockClient` mocks the `BlockchainEvents` trait to ensure
that tests can trigger either `FinalityNotification` or `BlockImportNotification` on demand.
Other traits imposed by the bounds of the `ChainHead` are implemented as pass-through.
While at it, increase the timeout duration of the `get_next_event()` that awaits for `chainHead`
events in the testing environment.
This is a follow-up for the fix https://github.com/paritytech/substrate/pull/13632.
// CC @paritytech/tools-team
=> chain_head/tests: Check finalized block event before new block

bin/node/cli/src/service.rs, bin/node/executor/tests/submit_transaction.rs, client/authority-discovery/src/error.rs, client/authority-discovery/src/worker.rs, client/consensus/aura/src/lib.rs, client/consensus/babe/rpc/src/lib.rs, client/consensus/babe/src/authorship.rs, client/consensus/babe/src/lib.rs, client/consensus/grandpa/src/lib.rs, client/consensus/slots/src/lib.rs, client/keystore/src/local.rs, client/rpc/src/author/tests.rs, primitives/application-crypto/src/lib.rs, primitives/application-crypto/src/traits.rs, primitives/application-crypto/test/src/ecdsa.rs, primitives/application-crypto/test/src/ed25519.rs, primitives/application-crypto/test/src/sr25519.rs, primitives/consensus/common/src/error.rs, primitives/consensus/grandpa/src/lib.rs, primitives/core/src/crypto.rs, primitives/core/src/ecdsa.rs, primitives/core/src/ed25519.rs, primitives/core/src/sr25519.rs, primitives/io/src/lib.rs, primitives/keystore/src/lib.rs, primitives/keystore/src/testing.rs, primitives/runtime/src/traits.rs
Closes https://github.com/paritytech/substrate/issues/13556
polkadot companion: https://github.com/paritytech/polkadot/pull/6944
cumulus companion: https://github.com/paritytech/cumulus/pull/2371
---
Within this PR:
- Removal of `CryptoTypePublicId` type
- Introduce explicit signing methods to the `Keystore` trait
- `Keystore::sign_with` method has been retained. But a default implementation has been provided in the trait definition. In the end this is a convenience method that can be used in some specific use cases (to prevent code duplication in all the cases where the key is generic such as AURA).
- nevertheless in all the places where we can use the explicit keystore methods we save the casts to and from raw byte vectors that by definition are fallible (but in our use cases were …
=> Keystore overhaul (final)

primitives/application-crypto/src/traits.rs
=> Fix 'AppCrypto' docs

client/informant/src/display.rs, client/network/common/src/sync.rs, client/network/sync/src/engine.rs, client/network/sync/src/lib.rs
`Protocol` is not a reliable source for the information of connected peers because it does't have real-time information about the real connectivity state.
The way to address this properly would be to refactor `SyncingEngine` and `ChainSync`, remove duplicate peer counting and return a unified `SyncState` but I haven't found time for that refactoring yet, hopefully soon.
=> Get the correct number of connected peers in `SyncState`

frame/offences/benchmarking/src/lib.rs, frame/offences/benchmarking/src/mock.rs
=> Fix failing offences bench test

client/cli/src/lib.rs, client/cli/src/runner.rs, client/cli/src/signals.rs
- Make runner code more clear.
- Improve the signals, now it could work well outside the sc-cli.
--- 
polkadot address: 15ouFh2SHpGbHtDPsJ6cXQfes9Cx1gEFnJJsJVqPGzBSTudr
=> chore(sc-cli): improve runner and signals

scripts/ci/gitlab/pipeline/test.yml
as requested in https://github.com/paritytech/ci_cd/issues/761
=> add a new ci job to fuzz sp-arithmetic

frame/referenda/src/lib.rs, frame/referenda/src/tests.rs
We were doing a straight `mul` to get the block number from a `Perbill`, which will round down if the fractional part is half or less. We should always be rounding up, though, to ensure that when the alarm goes off the confirmation period is definitely ready to begin.
It would be good to write a fuzzer to ensure the issue manifested itself prior and no longer manifests after these changes. It is also possible that the issue was fixed by #13660, so if a fuzzer doesn't find this has fixed anything we might want to try testing with the [commit](https://github.com/paritytech/substrate/commit/bf395c8308c481a9774373e0b0b14bd7a2e4b8d2) immediately before.
Possible fix for https://github.com/paritytech/substrate/issues/13658
=> FRAME: Fix the Referenda confirming alarm

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/test.yml
For whatever reason `cargo` [started to receive](https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2599321#L979) truncated `RUSTFLAGS` on `master`, which led to the `RUSTFLAGS` inconsistency between `master` and PRs and further cache invalidation.
This PR reformats `RUSTFLAGS` in a more accepted way, which brings the flags consistency back.
Resolves https://github.com/paritytech/ci_cd/issues/762.
=> CI: rephrase `RUSTFLAGS`

frame/contracts/README.md
proper link to `Event` documentation
=> contracts: proper event link in docs

Cargo.lock, primitives/io/Cargo.toml, primitives/io/build.rs, primitives/io/src/lib.rs, utils/wasm-builder/README.md, utils/wasm-builder/src/lib.rs, utils/wasm-builder/src/prerequisites.rs, utils/wasm-builder/src/version.rs
This pull request brings support for compiling the runtime with stable Rust. This requires at least rust 1.68.0 to work on stable. The code is written in a way that it is backwards compatible and should automatically work when someone compiles with 1.68.0+ stable.
Closes: https://github.com/paritytech/substrate/issues/1252
polkadot companion: https://github.com/paritytech/polkadot/pull/6967
cumulus companion: https://github.com/paritytech/cumulus/pull/2393
=> Support stable rust for compiling the runtime

.gitlab-ci.yml
Currently this variable is configured exclusively via a project variable, which makes it impossible to override for specific test prs.
=> provide a default value for RELENG_SCRIPTS_BRANCH

Cargo.lock, primitives/core/Cargo.toml, primitives/core/src/crypto.rs
Motivations:
- `base58` has hard limit of 128 bytes output (`bs58` doesn't have any limit)
- with the introduction of https://github.com/paritytech/substrate/pull/13618 we require to decode longer strings
- (marginal) `bs58` is also used by `libp2p` so we depend on it anyway
- (marginal) `bs58` docs declares to be faster but I found the two almost equivalent.
=> Swap 'base58' with 'bs58'

.gitlab-ci.yml
This reverts commit 56d8cbfcac926439aa78b684b7c77921dd2f4a7f.
=> Clean up after debian 11 rollout

bin/node/runtime/Cargo.toml
We're currently at the tuple element limit, when we reach that - the runtime compilation fails with a cryptic error. This PR bumps the tuple element number by 50% to ensure nobody hits this. 
Details could be found here: https://substrate.stackexchange.com/questions/7212
=> [Fix] Bump tuple element number in frame-support.

frame/contracts/src/tests.rs
When debugging tests, the CARGO_* environment variables are not set, and thus the relative path fails to resolve.
using a path relative to PWD should make things work
=> contracts: make test work with debugger

frame/balances/src/lib.rs, frame/nis/src/lib.rs
As per https://github.com/paritytech/substrate/pull/12951#discussion_r1141335468
=> FRAME: Minor fix for failsafe.

Cargo.lock, client/network/Cargo.toml
This fixes the compilation on master for the node template that was not pulling the latest release as part of its build.
=> Force upgrade snow to 0.9.2

utils/wasm-builder/src/wasm_project.rs
Followup of https://github.com/paritytech/substrate/pull/13758
Looks like just setting `target-cpu=mvp` is not enough.
Fixes https://github.com/paritytech/substrate/issues/13636 (this time for real)
=> Disable `sign-ext` WASM feature when building runtimes

Cargo.lock, frame/benchmarking/pov/src/lib.rs, frame/benchmarking/src/tests.rs, frame/benchmarking/src/tests_instance.rs, frame/collective/src/tests.rs, frame/examples/offchain-worker/src/lib.rs, frame/executive/src/lib.rs, frame/membership/src/lib.rs, frame/nicks/src/lib.rs, frame/scored-pool/src/lib.rs, frame/sudo/src/lib.rs, frame/support/procedural/Cargo.toml, frame/support/procedural/src/pallet/expand/call.rs, frame/support/test/tests/pallet.rs, frame/support/test/tests/pallet_instance.rs, frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr, frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr, frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr, frame/support/test/tests/pallet_ui/call_missing_index.stderr, frame/support/test/tests/pallet_ui/call_weight_argument_has_suffix.rs, frame/support/test/tests/pallet_ui/call_weight_argument_has_suffix.stderr, frame/support/test/tests/pallet_ui/call_weight_const_warning.rs, frame/support/test/tests/pallet_ui/call_weight_const_warning.stderr, frame/support/test/tests/pallet_ui/call_weight_const_warning_twice.rs, frame/support/test/tests/pallet_ui/call_weight_const_warning_twice.stderr, frame/support/test/tests/pallet_ui/dev_mode_without_arg_max_encoded_len.stderr, frame/support/test/tests/pallet_ui/weight_argument_has_suffix.stderr, frame/support/test/tests/storage_layers.rs, frame/utility/src/tests.rs
Cleaning up the code a bit by using [proc-macro-warning](https://github.com/ggwpez/proc-macro-warning) and emitting a warning when using a hard-coded weight on a non-dev-mode pallet (https://github.com/paritytech/substrate/pull/13774).  
In cases where `dev` mode is not possible and you explicitly want to ignore this warning; wrap it in curly brackets like `{1}`.
This enforces consistent formatting and grammar across different warnings for enhanced developer experience.
```pre
warning: use of deprecated constant `pallet::warnings::ImplicitCallIndex::_w`: 
It is deprecated to use implicit call indices.
Please instead ensure that all calls have the `pallet::call_index` attribute or that the `dev-mode` of the pallet is enabled.
For more info see: …
```
=> Uniform pallet warnings

client/executor/benches/bench.rs, client/executor/src/wasm_runtime.rs, client/executor/wasmtime/src/runtime.rs, client/executor/wasmtime/src/tests.rs
During a recent [LLVM incident](https://github.com/paritytech/substrate/issues/13636), we discovered that enabling and disabling WASM extensions is not only a matter of our will. Teams working on compilers and WASM runtimes stabilize things independently, and we need a mechanism to enable those extensions deterministically on a per-session basis.
Thus, paritytech/polkadot#6918 was raised. To enable the underlying execution logic to control the extensions, the Substrate has to expose corresponding handles through Wasmtime executor semantics. This PR solves that. The controlling logic will be implemented in a separate PR in the Polkadot repo.
Closes #13809 
Unblocks paritytech/polkadot#6918
Polkadot companion: paritytech/polkadot#6998
=> Expose WASM extensions in executor semantics

bin/node/testing/src/bench.rs, client/api/src/execution_extensions.rs, client/service/src/builder.rs, client/service/src/client/call_executor.rs, client/service/src/client/client.rs, primitives/core/src/traits.rs, primitives/state-machine/src/lib.rs, test-utils/client/src/lib.rs, utils/frame/benchmarking-cli/src/pallet/command.rs, utils/frame/try-runtime/cli/src/commands/execute_block.rs, utils/frame/try-runtime/cli/src/commands/fast_forward.rs, utils/frame/try-runtime/cli/src/commands/follow_chain.rs, utils/frame/try-runtime/cli/src/commands/offchain_worker.rs, utils/frame/try-runtime/cli/src/lib.rs
Instead of registering `ReadRuntimeVersionExt` in `sp-state-machine` it is moved to `ExecutionExtension` which provides the default extensions.
=> Move registration of `ReadRuntimeVersionExt` to `ExecutionExtension`

client/cli/src/params/network_params.rs
`./substrate --help` logs duplicate possible values for the `--sync` flag.
=> de-duplicate --help --sync docs

frame/nis/src/lib.rs, frame/support/procedural/src/construct_runtime/expand/freeze_reason.rs, frame/support/procedural/src/construct_runtime/expand/hold_reason.rs, frame/support/procedural/src/construct_runtime/expand/lock_id.rs, frame/support/procedural/src/construct_runtime/expand/slash_reason.rs, frame/support/procedural/src/lib.rs, frame/support/src/lib.rs, frame/support/test/tests/pallet.rs
Partial #12918.
Adds the `HoldReason` as a `composite_enum` to the NIS pallet. Also fixes a couple of naming bugs and adds more tests.
=> Add HoldReason to the NIS pallet

client/executor/common/src/error.rs, client/executor/src/integration_tests/mod.rs, client/executor/wasmtime/src/runtime.rs
Previously this was a `WasmError`, which is intended for runtime construction errors. However this led to confusion as output-exceeds-bounds occurs due to execution of `validate_block`.
(Please review closely and correct me if I'm mistaken about something, the error story here is pretty confusing.)
=> WASM executor: add `OutputExceedsBounds` variant to `Error`

client/executor/benches/bench.rs
`cargo +nightly check --benches --all` outputs an unused import warning
=> Remove unused import from bench.rs

frame/support/src/traits/tokens/fungible/regular.rs, frame/support/src/traits/tokens/fungibles/regular.rs
There is a bug in the calculation of the return value of the `fungible` and `fungibles` `set_balance` default implementation.
The doc comment says it should return the new balance, but instead it returns `requested_balance +/- balance_change`. 
I have tests in [this PR](https://github.com/paritytech/substrate/pull/13852) that show the incorrect return value.
This test
```
cargo test --package pallet-balances -- tests::fungible_conformance_tests::set_balance_mint_success --nocapture
```
shows
```
initial_balance: 11
set_balance_amount: 16
expected_set_balance_return_value: 16
actual_set_balance_return_value: 21
```
and this test
```
cargo test --package pallet-balances -- tests::fungible_conformance_tests::set_balance_burn_success --nocapture
```
shows
```
initial_balance: 11 …
```
=> Fix fungible and fungibles set_balance return value

scripts/ci/gitlab/pipeline/build.yml, scripts/ci/gitlab/pipeline/test.yml
for https://github.com/paritytech/ci_cd/issues/767
cargo-fmt stays on the nightly pipeline; our fmt config uses a heap of
unstable features.
=> use stable rust toolchain in ci

client/consensus/beefy/src/communication/gossip.rs, client/consensus/beefy/src/communication/mod.rs, client/consensus/beefy/src/communication/peers.rs, client/consensus/beefy/src/communication/request_response/incoming_requests_handler.rs, client/consensus/beefy/src/communication/request_response/mod.rs, client/consensus/beefy/src/communication/request_response/outgoing_requests_engine.rs, client/consensus/beefy/src/import.rs, client/consensus/beefy/src/justification.rs, client/consensus/beefy/src/lib.rs, client/consensus/beefy/src/metrics.rs, client/consensus/beefy/src/tests.rs, client/consensus/beefy/src/worker.rs
Added peer reputation reporting to BEEFY gossip and BEEFY on-demand-requests network protocols.
Fixes https://github.com/paritytech/substrate/issues/12293
Fixes https://github.com/paritytech/substrate/issues/12294
=> sc-consensus-beefy: add peer reputation cost/benefit changes

frame/contracts/src/wasm/runtime.rs
Stabilize `[seal0] call_runtime()` as it is covered by [e2e test](https://github.com/paritytech/ink/blob/6fb975d77c61bd08c662e2111c4f35b0e50a3d37/integration-tests/call-runtime/lib.rs).
=> contracts: stabilize `[seal0] call_runtime()`

.gitlab-ci.yml, scripts/ci/gitlab/crate-publishing-pipeline.yml, scripts/ci/gitlab/default-pipeline.yml
It's not neccessary to dynamically change the `interruptible` setting for *all* jobs as the old approach does; gitlab already considers a pipeline uninterruptible as soon as a single uninterruptible job has started (cf https://docs.gitlab.com/ee/ci/yaml/#interruptible).
IMO this approach is more readable, as it avoids dynamically loading the `.defaults` section from different files based on import conditions; the logic is now shorter and entirely contained in the main .gitlab-ci.yml.
In addition to the refactoring, this PR also adds a condition to make multi-project pipelines uninterruptible too. Currently, a substrate pipeline triggered e.g. by a ci-linux build in the scripts repo could be interrupted, thus unneccessarily preventing a `ci-linux:production` deployment.
=> Refactor the automatic-crate-publishing logic, make triggered pipelines uninterruptible as well

client/utils/src/mpsc.rs
Fix #13849 
`tracing_unbounded` uses `async_channel` internally, in which, the pending messages of the channel will not be dropped even if all the receivers have been dropped and these messages can never be accessed.
This may cause blocking issues when using `tracing_unbounded` to send `Sender<T>` and there is quite a lot of such usage within substrate as #13849 mentioned.
This PR fixes the issue by manually draining all the pending messages in the channel when `TracingUnboundedReceiver` is dropped and a test is added to cover the abovementioned case.
cc @bkchr
=> Drain all the pending messages in the channel when `TracingUnboundedReceiver` is dropped

client/allocator/src/freeing_bump.rs
We should not panic on an invalid header pointer and instead return an error. It is possible that the application modifies the header pointer illegally, but then we should return an error instead of panicking.
Closes: https://github.com/paritytech/substrate/issues/13924
=> sc-allocator: Do not panic on invalid header pointer

client/network/src/protocol.rs
In tests, it can happen that `Notifications` doesn't produce any events which causes `poll()` to return `Poll::Pending` and the substream validation futures won't get polled.
Poll the futures before calling `Notifications` so results for substream validations are received even if `Notifications` is not producing any events.
=> Poll the substream validation before polling `Notifications`

Cargo.lock, Cargo.toml, frame/examples/dev-mode/Cargo.toml, frame/examples/dev-mode/README.md, frame/examples/dev-mode/src/lib.rs, frame/examples/dev-mode/src/tests.rs, frame/support/procedural/src/lib.rs
=> Adds example for dev_mode and updates doc

Cargo.lock, primitives/arkworks/Cargo.toml, primitives/arkworks/src/bls12_377.rs, primitives/arkworks/src/bls12_381.rs, primitives/arkworks/src/bw6_761.rs, primitives/arkworks/src/ed_on_bls12_377.rs, primitives/arkworks/src/ed_on_bls12_381.rs, primitives/arkworks/src/utils.rs, primitives/arkworks/test/Cargo.toml, primitives/arkworks/test/tests/bls12_377.rs, primitives/arkworks/test/tests/bls12_381/mod.rs, primitives/arkworks/test/tests/bw6_761.rs, primitives/arkworks/test/tests/ed_on_bls12_377.rs, primitives/arkworks/test/tests/ed_on_bls12_381.rs, primitives/arkworks/test/tests/mod.rs, primitives/io/src/lib.rs
Use [ark-scale](https://github.com/w3f/ark-scale) by @burdges for (de-)serialization.
=> use ark_scale

frame/nfts/src/common_functions.rs, frame/nfts/src/lib.rs, frame/nfts/src/tests.rs
When we try to sign some data using the UIs like PolkadotJS apps, PolkadotJS extension + some others, all of them implicitly wrap the data value into the <Bytes> tag. That behaviour leads to different signatures generated, which look incorrect from the pallet's side.
This PR improves the offchain signature's validation by adding the support of wrapped into <Bytes> data values
=> [NFTs] Improve offchain signature validation

client/network/sync/src/lib.rs
When peer disconnects or the syncing is restarted, remove the pending response so syncing won't start sending duplicate requests/receive stale responses from disconnected peers.
Before this commit pending responses where stored in `FuturesUnordered` which made it hard to keep track of pending responses for each individual peer.
=> Keep track of the pending response for each peer individually

frame/balances/src/impl_currency.rs
Per a suggestion from @kianenigma, adding a note to the `balances` `currency` implementation explaining that `WithdrawReasons` are intentionally ignored. 
This is to help prevent possible developer confusion as they read the implementation.
=> `balances` `impl_currency` WithdrawReasons note

Cargo.lock, bin/node/bench/Cargo.toml, client/db/Cargo.toml
polkadot companion: https://github.com/paritytech/polkadot/pull/7113
=> update rocksdb to 0.20.1

primitives/application-crypto/src/lib.rs, primitives/core/src/crypto.rs, primitives/core/src/ecdsa.rs, primitives/core/src/ed25519.rs, primitives/core/src/sr25519.rs
Just duplicated code
1. If passing raw bytes we need to construct proper backend types anyway to verify the signature (so no real added value)
2. Not used anywhere
=> Remove superfluous Pair::verify_weak

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/publish.yml
PR updates buildah command and version. More info can be found in https://github.com/paritytech/ci_cd/issues/779
=> [ci] Update buildah command and version

frame/support/Cargo.toml, frame/support/procedural/Cargo.toml
We didn't had the tuples features declared for the `frame-support-procedural` crate and thus, it could not properly detect that the feature was already enabled.
=> frame-support-procedural: Fix detection of the tuples feature

frame/democracy/src/lib.rs, frame/democracy/src/tests/metadata.rs, frame/support/src/traits/schedule.rs
The requesting of the proposal is actually done now in `pallet-scheduler`.
Fixes: https://github.com/paritytech/substrate/issues/13534
=> pallet-democracy: Do not request the proposal when scheduling

scripts/ci/gitlab/pipeline/test.yml
PR adds message to `cargo-deny` (cc https://github.com/paritytech/substrate/pull/13956#issuecomment-1521200933)
=> [ci] Add message to cargo-deny

.maintain/frame-weight-template.hbs, utils/frame/benchmarking-cli/src/pallet/template.hbs
This change allows people to use `#![deny(missing_docs)]` for pallets should they wish to.
=> Easy PR: Allow missing docs for autogen weights

frame/contracts/src/tests.rs
follow up to https://github.com/paritytech/substrate/pull/13565
=> contracts: fix failing test

frame/contracts/fixtures/call.wat, frame/contracts/src/tests.rs
Add missing test for storage deposit
=> contracts Add storage_deposit test

primitives/state-machine/src/testing.rs, utils/frame/remote-externalities/src/lib.rs
As suggested by @arkpar (https://github.com/paritytech/substrate/issues/13562#issuecomment-1520853103), adds batch inserting of key/value pairs to remote-externalities so the trie root doesn't need to be re-computed after every insertion.
at `ws://localhost:9944` is an (optimised build) kusama node
| Task | Build | Before | After | Improvement |
|---------|-------|--------|-------|-----|
| `on-runtime-upgrade` (live) | release | 72s | 59s | 18% |
| `on-runtime-upgrade` (live) | debug | 174s | 73s | 58% |
| `create-snapshot` | release | 70s | 58s | 17% |
| `create-snapshot` | debug | 173s | 57s | 67% |
| `on-runtime-upgrade` (snap) | release | 21s | 5s | 76% |
| `on-runtime-upgrade` (snap) | debug | 125s | 19s | 84% |
=> remote-externalities: batch insert key/values

frame/collective/src/lib.rs, frame/collective/src/tests.rs
The Collective pallet currently does not check that genesis members are sorted or sort them before setting them as expected by the pallet:
https://github.com/paritytech/substrate/blob/9370f42ab35f7013f70b703884c9884888a3b153/frame/collective/src/lib.rs#L281-L285
`kitchen-sink-runtime` invariants are currently broken due to this bug.
This PR adds sorting logic into the `initialize_members`, ensuring genesis members are inserted in sorted order.
Props to @Szegoo for adding the Collective try-state hooks (https://github.com/paritytech/substrate/pull/13645) that caught this!
--- 
Open question: what's the likelihood there're other pallets that suffer from a similar bug? Should an issue need to be opened to investigate that?
=> pallet Collective: fix genesis member sort order

client/network/sync/src/lib.rs
Before this wasn't printing a warning for `VerificationFailed` when there wasn't a peer assigned to the error message. However, if there happens an error on importing the state there wouldn't be any error. This pr improves the situation to also print an error in this case. Besides that there are some other cleanups.
=> sc-network-sync: Improve error reporting

frame/contracts/src/tests.rs
missed file rename from https://github.com/paritytech/substrate/pull/13565/files#diff-6370b6056b1f65146c88f1b9f291c2d3a64bc5f59c93b1905bad95a09d959f7b
=> contracts fix store-call test path

client/cli/src/commands/build_spec_cmd.rs, client/cli/src/commands/check_block_cmd.rs, client/cli/src/commands/export_blocks_cmd.rs, client/cli/src/commands/generate_node_key.rs, client/cli/src/commands/import_blocks_cmd.rs, client/cli/src/commands/insert_key.rs, client/cli/src/commands/inspect_key.rs, client/cli/src/commands/inspect_node_key.rs, client/cli/src/commands/run_cmd.rs, client/cli/src/params/import_params.rs, client/cli/src/params/network_params.rs, client/cli/src/params/node_key_params.rs, client/cli/src/params/offchain_worker_params.rs, client/cli/src/params/prometheus_params.rs, client/cli/src/params/pruning_params.rs, client/cli/src/params/shared_params.rs, client/cli/src/params/telemetry_params.rs
So many docs not present in cli binary. 
`clap` now ignores documents below blank lines.
So we need to delete these blank lines.
--- 
polkadot address: 15ouFh2SHpGbHtDPsJ6cXQfes9Cx1gEFnJJsJVqPGzBSTudr
=> chore(cli): make cli display docs correctly

client/api/src/in_mem.rs
The `clone` logic is wrong. Should clone `Arc` rather than clone inner `BlockchainStorage`
=> fix(in_mem): fix the clone logic

.gitlab-ci.yml, scripts/ci/gitlab/pipeline/publish.yml
Fixes a previous attempt in https://github.com/paritytech/substrate/pull/14044.
=> Don't run `check-crates-publishing` job on prs

client/service/src/client/client.rs
Calculation of these tree routes is very expensive. When the finalized block is very far from the best block, it can take multiple seconds to calculate this tree route, blocking the import lock.
If there is only one leave, we can skip this calculation since the best block is guaranteed to be a descendant of the new finalized one.
Closes https://github.com/paritytech/cumulus/issues/2494, https://github.com/paritytech/substrate/issues/13947, 
Could impact the parachain part of https://github.com/paritytech/substrate/issues/14049
~Edit: Do not close the above issues for now, freshly syncing node still has issues.~
=> Only calculate tree route during finalization when there are multiple leaves

frame/contracts/src/wasm/runtime.rs
Folllow-up to https://github.com/paritytech/substrate/pull/13901.
It could be a mess to find out the error cause in `call_runtime` calls. This small improvement should make it simpler.
=> contracts: add error logging to `call_runtime`

utils/frame/remote-externalities/src/lib.rs
If payload length is less than parallel requests, this panics. Small fix to ensure we divide payload in at least one chunk.
=> Remote ext parallel download fix

bin/node/cli/benches/block_production.rs, bin/node/cli/benches/transaction_pool.rs, client/cli/src/commands/run_cmd.rs, client/cli/src/config.rs, client/cli/src/runner.rs, client/service/src/config.rs, client/service/src/lib.rs, client/service/test/src/lib.rs
Follow-up on https://github.com/paritytech/substrate/pull/13384
It changed the rpc_port from a  `Option<u16>` -> `u16` which broke overriding it in cumulus (see https://github.com/paritytech/cumulus/issues/2529) and the default value was used instead
polkadot companion: https://github.com/paritytech/polkadot/pull/7192
cumulus companion: https://github.com/paritytech/cumulus/pull/2539
=> fix cli: make rpc port Option<u16> again

scripts/ci/gitlab/pipeline/test.yml, test-utils/cli/src/lib.rs
With the recent change of re-running flaky tests this should be fine!
=> Re-enable `node-cli` tests in CI and fix them

.gitlab-ci.yml
There are still a bunch of open questions on how to handle image pinning; in the meantime, let's keep using the production tag.
=> Move back to ci-linux:production image after upgrade

frame/uniques/src/benchmarking.rs, frame/uniques/src/functions.rs, frame/uniques/src/impl_nonfungibles.rs, frame/uniques/src/lib.rs
This PR relaxes the requirement that the `CollectionId` in the uniques pallet must be `Copy`.
I'm planning to make `AssetId`/`MultiLocation` types in `polkadot` non-`Copy` (to reduce the size of those types by almost ~90%), and there's at least one crate in `polkadot` which uses those types as a `CollectionId`.
=> Remove the `Copy` bound on `CollectionId` in the uniques pallet

.gitignore, Cargo.lock, Cargo.toml, scripts/ci/deny.toml, scripts/ci/node-template-release/Cargo.toml
(Preparation for the monorepo)
Including the `node-template-release` now in the workspace to have compatible dependencies.
=> Include `node-template-release` in workspace

Cargo.lock
...to keep up with the `cargo update` changes.
=> Bump `Cargo.lock`

client/service/test/src/client/mod.rs, test-utils/runtime/client/src/lib.rs, test-utils/runtime/src/genesismap.rs, test-utils/runtime/src/lib.rs, test-utils/runtime/src/substrate_test_pallet.rs
Lazy creation of public keys from AccountId in the `GenesisStorageBuilder::build()` method.
Reason: the new strategy better fits when we require to create keys using a different scheme.
Previous approach assumes that all the runtime pallets will require the same scheme (sr25519) but this is not always the case (sassafras uses bandersnatch vrf keys or grandpa).
Postponing the creation of the keys allows to maintain only the account ids list in the builder and then create all the key types we require (currently only sr25519) when we require them
---
Other trivial tweaks:
- `substrate-test-pallet`'s `Authorities` storage is used to store other protocols keys that doesn't instance the pallet within the test runtime (e.g. aura). Thus, is more appropriate to store a raw sr25519 key instead of …
=> Postpone public key creation in the test GenesisStorageBuilder

client/network/src/lib.rs, client/network/src/peer_info.rs, client/network/src/transport.rs
Makes `discovery`, `peer_info` and `transport` mods public in `sc-network`.
Makes it easy to develop lightweight binaries that want to become of libp2p swarm and use libp2p's `NetworkBehaviour`s.
=> expose transport, peer_info and discovery in sc-network

primitives/consensus/aura/Cargo.toml
This is followup of #13027.
`sp-consensus-aura` need to enable `serde` feature in dependent crates, otherwise test-substrate-runtime compilation (or other environmet) fails with the following error if `serde` is enabled:
```
error: cannot find macro `format` in this scope
-->
/home/miszka/parity/10-genesis-config/substrate-master/primitives/consensus/aura/src/lib.rs:50:3
|
50 |         app_crypto!(ed25519, AURA);
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: consider importing one of these items:
scale_info::prelude::format
sp_application_crypto::format
= note: this error originates in the macro
`$crate::app_crypto_public_common_if_serde` which comes from the
expansion of the macro `app_crypto` (in Nightly builds, run with -Z
macro-backtrace for more info)
```
=> Added serde feature to sp-consensus-aura

client/cli/src/commands/revert_cmd.rs
This exposes the database params for the `RevertCmd` via CLI. So, users can use `revert` with ParityDb.
Closes: https://github.com/paritytech/substrate/issues/14046
=> RevertCmd: Expose database params via CLI

test-utils/runtime/src/lib.rs, test-utils/runtime/src/substrate_test_pallet.rs
This is required to make different unsigned extrinsics resolve to different transactions in the tx pool by having `provides` set to the hash of the call.
=> test-runtime: Return hashed call as provides in unsigned validation

frame/beefy-mmr/src/tests.rs, frame/merkle-mountain-range/src/lib.rs, utils/binary-merkle-tree/src/lib.rs
Reverts the lexical ordering of hashing of the BEEFY authority merkle tree #12857 since we still require commitment to the leaf indices, which the lexical ordering removes and would require another mechanism for enforcement.
See https://github.com/paritytech/substrate/issues/12820 for context. Some candidates for salvaging the gas improvement down the line are described [here](https://hackmd.io/@Lederstrumpf/SkfTo87rh), albeit they currently still require benchmarking.
cc @doubledup & @vgeddes (can't request review), since you'll adjust correspondingly in Solidity, and in case you've had changes to the verifier affected by this (other than the lexical ordering).
=> Revert "Optimize merkle proofs for efficient verification in Solidity (#12857)"

client/executor/benches/bench.rs, client/executor/wasmtime/src/lib.rs, client/executor/wasmtime/src/runtime.rs
See title. Also export `WasmtimeRuntime`, returned by the `create_runtime*` functions.
I benchmarked the performance regression out of curiosity: https://github.com/bytecodealliance/wasmtime/pull/6420. But since runtime creation is not at all a bottleneck, it makes sense to always use this new function for the reasons given in the related issue and PR.
Needed for https://github.com/paritytech/polkadot/pull/7246#discussion_r1199178044
Closes https://github.com/paritytech/substrate/issues/13861
=> Executor: Add `create_runtime_from_artifact_bytes`

client/network/common/src/sync/warp.rs, client/network/sync/src/lib.rs
This makes it for the user more obvious on what we are waiting and not just "waiting for peers".
=> WarpSync: Show number of required peers in informant

primitives/trie/src/cache/mod.rs
First, we increase the size to 10MiB for the local cache. Second, we give the node cache a bigger max size than the value cache, see the changed comment on why.
In general this should ensure that we are able to cache the `:code` and not directly throw it out of the cache because it is too big (which currently happens when the size of the runtime > 2MiB). In the future this should be improved to ensure that certain values are not removed from the cache at all, like `:code`.
=> TrieCache: Fine tune the size of the local and node cache

client/db/src/lib.rs
Wrote this test to debug https://github.com/paritytech/substrate/issues/14194.
=> sc-client-db: add test for reverting finalized blocks

Cargo.lock, client/consensus/beefy/Cargo.toml, client/consensus/beefy/src/communication/request_response/incoming_requests_handler.rs, client/consensus/beefy/src/communication/request_response/mod.rs, client/network/bitswap/Cargo.toml, client/network/bitswap/src/lib.rs, client/network/light/Cargo.toml, client/network/light/src/light_client_requests/handler.rs, client/network/src/request_responses.rs, client/network/sync/Cargo.toml, client/network/sync/src/block_request_handler.rs, client/network/sync/src/state_request_handler.rs, client/network/sync/src/warp_request_handler.rs
Resolves https://github.com/paritytech/substrate/issues/14138 by replacing `futures::channel::mpsc::channel` incoming request channel with `async_channel::bounded`, which doesn't have a limitation that every `Sender` clone allocates an extra queue slot.
polkadot companion: https://github.com/paritytech/polkadot/pull/7276
=> Fix request-response protocols backpressure mechanism

Cargo.lock, client/network/transactions/Cargo.toml, client/network/transactions/src/lib.rs
The `validation` future is boxed, so the `PendingTransaction` struct can just be `Unpin`.
=> Get rid of some pointless pin_project stuff

client/network/sync/src/engine.rs
Parachain collators may need to wait to receive a relaychain block before they can start producing blocks which can cause `SyncingEngine` to incorrectly evict them.
When `SyncingEngine` is started, wait 2 minutes before the eviction is activated to give collators a chance to produce a block.
=> Don't start evicting peers right after `SyncingEngine` is started

test-utils/client/src/lib.rs
In the cases where a reorg happens we might receive notifications for different blocks at the same level, so instead of the chain having `count` new blocks it has less and that will break the tests which use this function.
So, use the block number to identify that `count` blocks have been built in the chain.
Examples where this issue was hit:
https://github.com/paritytech/polkadot/issues/7267
=> test-utils: Fix wait_for_blocks in presence of reorgs

Cargo.lock, bin/node-template/node/Cargo.toml, client/executor/runtime-test/build.rs, primitives/runtime-interface/test-wasm-deprecated/build.rs, primitives/runtime-interface/test-wasm/build.rs, utils/wasm-builder/Cargo.toml, utils/wasm-builder/src/builder.rs, utils/wasm-builder/src/wasm_project.rs
This pr changes the `wasm-builder` to enforce the `runtime_version` wasm section. This wasm section is being created by the `sp_version::runtime_version` attribute macro. This attribute macro now exists since quite some time and `runtime_version` also is the only way for parachains to support reading the `RuntimeVersion` from the runtime.
\# Disabling the check
By default the `WasmBuilder` will now check for this wasm section and if not found, exit with an error. However, there are situations where you may want to disable this check (like for tests). In this case there exists the `disable_runtime_version_section_check` function.
```
WasmBuilder::new()
...
...
...
.disable_runtime_version_section_check()
.build()
```
By using this method you get back the old behavior.
Should prevent issues …
=> wasm-builder: Enforce `runtime_version` wasm section

client/network/src/protocol/notifications/behaviour.rs
Resolves https://github.com/paritytech/substrate/issues/14225.
=> [minor] Fix misleading comment in `Notifications`

Cargo.lock, primitives/api/proc-macro/src/runtime_metadata.rs, primitives/api/test/Cargo.toml, primitives/api/test/tests/ui/positive_cases/custom_where_bound.rs
The where bound for the `create_metadata` function wasn't correct. This pr fixes this by using the where bound declared at the type declaration augmented with the manual where bound.
Closes: https://github.com/paritytech/substrate/issues/14250
=> sp-api: Set correct where bound in the generated code

primitives/authority-discovery/Cargo.toml, primitives/statement-store/Cargo.toml
serde feature added for:
- sp-statement-store
- sp-authority-discovery
Step towards: #13334
=> primitives: added serde feature

Cargo.lock, primitives/core/Cargo.toml
polkadot companion: paritytech/polkadot#7305
Step towards: #13334
=> bounded-collections bump to 0.1.7

Cargo.lock, bin/node-template/node/Cargo.toml
The faulty version was yanked from crates.io.
=> Remove `enum-as-inner` pin

primitives/blockchain/src/error.rs
In our project, when running the node, we meet the error:
```bash
2023-05-29 12:38:18 | 2023-05-29 04:38:17.993  WARN tokio-runtime-worker sc_service::client::client: Block import error: Database
```
Then the following blocks can not sync.
Look deep into the code, I know the error appear in the deep level of database, for example now we are using the rocksdb, so this error comes from the rockesdb.
However in the error log, the database error is dropped in the `sp-runtime::Error` type.
And I think the error type `sp-database::DatabaseError` already impl `Debug` trait, so I think this error info can show in the `sp-runtime::Error` also.
https://github.com/paritytech/substrate/blob/b8d7dd51b0a48314ceb4440a0ad4026277712450/primitives/database/src/error.rs#L18-L21
In this pr, I plan to let …
=> print error info for Database error in the `sp-blockchain::Error` type.

primitives/api/proc-macro/src/decl_runtime_apis.rs, primitives/api/src/lib.rs, primitives/api/test/tests/decl_and_impl.rs, primitives/api/test/tests/ui/changed_in_no_default_method.rs, primitives/api/test/tests/ui/changed_in_no_default_method.stderr, primitives/api/test/tests/ui/changed_in_unknown_version.rs, primitives/api/test/tests/ui/changed_in_unknown_version.stderr, primitives/api/test/tests/ui/empty_impl_runtime_apis_call.rs, primitives/api/test/tests/ui/empty_impl_runtime_apis_call.stderr, primitives/api/test/tests/ui/impl_incorrect_method_signature.rs, primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr, primitives/api/test/tests/ui/impl_missing_version.rs, primitives/api/test/tests/ui/impl_missing_version.stderr, primitives/api/test/tests/ui/impl_two_traits_with_same_name.rs, primitives/api/test/tests/ui/impl_two_traits_with_same_name.stderr, primitives/api/test/tests/ui/missing_block_generic_parameter.rs, primitives/api/test/tests/ui/missing_block_generic_parameter.stderr, primitives/api/test/tests/ui/missing_path_for_trait.rs, primitives/api/test/tests/ui/missing_path_for_trait.stderr, primitives/api/test/tests/ui/missing_versioned_method.rs, primitives/api/test/tests/ui/missing_versioned_method.stderr, primitives/api/test/tests/ui/missing_versioned_method_multiple_vers.rs, primitives/api/test/tests/ui/missing_versioned_method_multiple_vers.stderr, primitives/api/test/tests/ui/positive_cases/custom_where_bound.rs, primitives/api/test/tests/ui/positive_cases/default_impls.rs, primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.rs, primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Remove the requirement on `GetNodeBlockType` and `GetRuntimeBlockType`. Actually this wasn't already used anymore and only referenced in tests.
cumulus companion: https://github.com/paritytech/cumulus/pull/2687
=> sp-api: Remove requirement on `Get*BlockType`

bin/node-template/README.md
This PR fixes a few broken links to the Substrate docs and makes a few clarifications in the README of the node-template. It also updates the link to the `construct_runtime` macro to the latest rustdoc Substrate release (previously pointing [here](https://crates.parity.io/frame_support/macro.construct_runtime.html)).
=> Improvements to node template README 

client/executor/wasmtime/src/tests.rs
As the test is executed inside the workspace, `cargo metadata` will automatically detect the correct `Cargo.toml`. This is required for the mono repo.
=> sc-executor-wasmtime: Do not use absolute path to `Cargo.toml` in test

bin/node-template/node/src/benchmarking.rs, bin/node-template/node/src/cli.rs, bin/node-template/node/src/rpc.rs, bin/node-template/node/src/service.rs
This PR fixes some clippy warnings that turn up in the node-template when it becomes detached from the main substrate code base (and the clippy allow directives in its .cargo/config.toml) which happens when it is used as intended (a node template).
=> fix clippy warnings in node template

docs/PULL_REQUEST_TEMPLATE.md
This PR replaces the relative paths pointing to `docs/CONTRIBUTING.adoc` with the the actual URLs to the CONTRIBUTING.adoc doc. Otherwise, if users click on the links in the preview of the template, because the root dir is `compare` they won't be directed to the right place.
=> Fix links to CONTRIBUTING.adoc in PR template

client/network/src/protocol/notifications/behaviour.rs, client/network/src/protocol_controller.rs
This should simplify debugging of `ProtocolController` & `Notifications` state machine synchronization issues.
=> [network] Extend `Notifications` logs with `SetId` where missing

client/basic-authorship/src/basic_authorship.rs
Non-controversial refactoring of the BlockBuilder to make https://github.com/paritytech/substrate/pull/14275/ easier to review.  
Changes:
- Splits the code of `propose_with` into `apply_inherents`, `apply_extrinsicis` and `print_summary`.
- Prints `no extrinsics` instead of `extrinsics (0): []` when there are none.
- Adds log level.
=> Refactor `BlockBuilder::propose_with`

client/cli/src/params/network_params.rs, client/network/src/config.rs, client/network/src/discovery.rs, client/network/src/service.rs
Exposes setting Kademlia replication factor through node's CLI.
Default Kademlia replication factor is 20. In environments (testing for example) with less than 20 nodes `AuthorityDiscovery` fails to publish DHT records containing node's `Multiaddrs`. So to make `AuthorityDiscovery` work in test environments it's  useful to have option to manually adjust Kademlia replication factor.
=> expose setting kademlia replication factor through node CLI

client/network/src/service.rs
This improves the reporting of invalid boot nodes. First, it will only report each boot node once as invalid and not every time we try to connect to the node. Second, the node will only report for addresses that we added as startup and not for addresses of the boot node that the node learned from other nodes.
Closes: https://github.com/paritytech/substrate/issues/13584
Closes: https://github.com/paritytech/polkadot/issues/7385
=> sc-network: Improve invalid boot node reporting

utils/frame/try-runtime/cli/src/commands/on_runtime_upgrade.rs
`default_value` is actually `pre-and-post`, not `none`
=> fix on-runtime-upgrade --checks docs

client/cli/src/arg_enums.rs, client/network/common/src/sync.rs, client/network/src/config.rs, client/network/sync/src/engine.rs, client/network/sync/src/lib.rs, client/network/sync/src/mock.rs, client/network/test/src/lib.rs, client/network/test/src/sync.rs, client/service/src/builder.rs, client/service/src/config.rs
There were two of the same, but slightly different enums. For some other changes I'm planning to do it is helpful if they are the same.
`Light` sync mode was removed as it is not used for some time. `SyncMode::Fast` is `SyncMode::LightState` now the way it was in one of the data structures (and is a better name IMHO).
When creating this PR I noticed there is a third `SyncMode` in `sc-cli`, I didn't touch it.
=> Unify `SyncMode` data structures under one

client/tracing/src/lib.rs
We should only print events for whitelisted targets, otherwise we may run into some stack overflow while printing the event.
=> sc-tracing: Only print events for whitelisted targets

utils/wasm-builder/src/version.rs
Apparently there are installations where the `hash` and `date` is optional.
Closes: https://github.com/paritytech/substrate/issues/14335
=> wasm-builder: Make `hash` and `date` optional

frame/babe/src/equivocation.rs, frame/beefy/src/equivocation.rs, frame/grandpa/src/equivocation.rs
This PR only fixes a typo in the documentation, it has no effect on the code (A2-insubstantial)
Fixes #14479
=> Fix typo (#14479)

bin/node-template/node/src/command.rs, bin/node/cli/src/command.rs, bin/node/executor/benches/bench.rs, client/cli/src/commands/insert_key.rs, client/cli/src/lib.rs, client/cli/src/runner.rs
The native runtime will be removed in the near future and thus this function will not be required anymore.
Downstream users just need to remove `native_runtime_version` from their implementation of the `SubstrateCli` trait.
polkadot companion: https://github.com/paritytech/polkadot/pull/7459
cumulus companion: https://github.com/paritytech/cumulus/pull/2821
=> sc-cli: Remove `SubstrateCli::native_runtime_version` function

scripts/ci/gitlab/pipeline/test.yml
There is a new feature flag `experimental`, see: https://github.com/paritytech/substrate/issues/14345
- Updates `cargo-check-try-runtime` to `cargo-check-try-runtime-and-experimental`
- `experimental` code may rely on `try-runtime` and vice-versa
- Updates `test-linux-stable` and `test-frame-support` to run with `experimental`
=> ci: run tests with --features experimental

Cargo.toml
Checked with `python check-deps.py substrate/` [script](https://github.com/ggwpez/substrate-scripts/blob/80ed86c1b929b9fafa17ba02ec9f310fe8d6c51b/import-runtime-repos/check-deps.py).
=> Add missing workspace member

bin/utils/subkey/README.md
getsubstrate.io is not maintained.
Perhaps other things should be updated here in this PR too - open to suggestions!
=> Update `subkey` README.md

bin/node/cli/tests/benchmark_block_works.rs, bin/node/cli/tests/benchmark_extrinsic_works.rs, bin/node/cli/tests/benchmark_overhead_works.rs, bin/node/cli/tests/benchmark_pallet_works.rs, primitives/core/src/defer.rs, utils/frame/benchmarking-cli/src/pallet/command.rs, utils/frame/benchmarking-cli/src/pallet/mod.rs
Changes:
- Re-add the `--execution` arg on command `benchmark pallet` that was removed in [#14387](https://github.com/paritytech/substrate/pull/14387). It is a No-OP and prints `⚠️  Argument --execution is deprecated. Its value of wasm will be ignore` now upon usage.
- Add `DeferGuard::new` as convenience function.
- Extend `benchmark *` cmd tests.
=> Re-add deprecated `--execution` arg on `benchmark pallet`

client/executor/src/executor.rs
Add `ignore_onchain_heap_pages` flag to `WasmExecutorBuilder` to ignore the on-chain value of heap pages and use the default one.
More info in https://github.com/paritytech/cumulus/issues/2641#issuecomment-1593117543
=> WasmExecutor flag to ignore onchain heappages value

client/cli/src/commands/run_cmd.rs
close #14574 
In this pr, we just filter `http://` `https://` prefix in the string, not including word `www`
=> wrong name regex to filter url when provide --name=www as parameter in cli

primitives/core/src/crypto.rs
I am a student at the PBA and I came across this issue when completing the first assignment as I was reading the rust docs.
It looks a few functions in this file are documented as if they have an `Option` return type when they are actually returning a `Result`
- What does this PR do?
Fixes the documentation for 3 functions by changing returns a `None` to returns an Error
- Why are these changes needed?
I think the documentation is incorrect
- How were these changes implemented and what do they affect?
They will change the rust documentation
=> fixing return types in crypto module documentation

client/cli/src/commands/run_cmd.rs
See https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3206771.
polkadot companion: https://github.com/paritytech/polkadot/pull/7484
(the companion above is fake, needed to unlock ci)
=> client: fix invalid node name pattern regex

bin/node-template/runtime/src/lib.rs, bin/node/runtime/src/lib.rs, frame/babe/src/default_weights.rs, frame/babe/src/lib.rs, frame/babe/src/mock.rs, frame/babe/src/tests.rs, frame/beefy-mmr/src/mock.rs, frame/beefy/src/default_weights.rs, frame/beefy/src/lib.rs, frame/beefy/src/mock.rs, frame/beefy/src/tests.rs, frame/grandpa/src/default_weights.rs, frame/grandpa/src/lib.rs, frame/grandpa/src/mock.rs, frame/grandpa/src/tests.rs, test-utils/runtime/src/lib.rs
This PR changes the `report_equivocation` weight calculation to take into account the runtime configured maximum number of nominators per validator, rather than using a constant value.
polkadot companion: https://github.com/paritytech/polkadot/pull/7432
=> Don't use fixed nominator count for report_equivocation weight calculation

NEW-PR, client/consensus/aura/src/import_queue.rs, client/consensus/aura/src/lib.rs, client/consensus/common/src/import_queue.rs, primitives/core/src/crypto.rs
In general `Pair` trait is not strictly required to be `Send/Sync/Clone`.
Secrets throughout the codebase are constructed and destroyed asap (as should be).
In some situation these bounds could even be detrimental; some components may require the secrets to not be shared across threads (in practice silently moved to another stack without cleaning up the previous location) or cloned  (e.g. in cases where the backend doesn't implement something like `zeroize` to clean-up memory).
Furthermore, secrets provided by some backends may not allow for these bounds. For example the upcoming Bandersnatch `ring-vrf` secret is  not `Sync`. So  here there is not much space for options wrt this trait bound.
---
The only place where these bounds are currently *vacuously* required is in AURA code.
Here …
=> Relax Send/Sync/Clone requirements for Pair

client/network/src/discovery.rs
refs https://github.com/paritytech/substrate/pull/14429#discussion_r1272061153
=> use `Toggle` instead of Option for mdns

scripts/ci/gitlab/pipeline/build.yml
Closes https://github.com/paritytech/pipeline-scripts/issues/104
=> ci: remove `--locked` from `check-runtime-migration` script

client/network/src/discovery.rs
otherwise, the DHT connectivity drops significantly as the graphs of our internal cluster showed.
PR where the regression was introduced: #14429
=> [network] fix: always set Kademlia mode to server

utils/frame/benchmarking-cli/src/pallet/command.rs
I don't know if this is a leftover debugging code or something but it is useless and broke our bencher bot
You can see [here](https://github.com/AcalaNetwork/Acala/actions/runs/5791725354/job/15696975201) it is printing a lot of useless `2496 bytes` in stdout
Please also backport this to 1.0.0 release branch
=> dont print proof size

bin/node/runtime/src/lib.rs
Use the same values for the metadata/attributes limits as on the AssetHub.
P. S. the old limit of 50 chars per metadata prevents testing the ipfs links locally
=> Sync NFT metadata limits with AssetHub values

bin/node/cli/benches/block_production.rs, bin/node/cli/benches/transaction_pool.rs, client/cli/src/commands/run_cmd.rs, client/cli/src/config.rs, client/cli/src/runner.rs, client/service/src/config.rs, client/service/test/src/lib.rs
BEEFY is soon expected to run on all substrate-based chains, make it part of `sc-cli`.
Note: in case of `polkadot` binary, CLI doesn't change. `--no-beefy` is moved from polkadot specific cli to `sc-cli`.
polkadot companion: https://github.com/paritytech/polkadot/pull/7600
cumulus companion: https://github.com/paritytech/cumulus/pull/2996
=> sc-cli: add no-beefy flag to cli config

client/consensus/beefy/src/lib.rs
When BEEFY voter is initialized from scratch (no aux db persistent data present), it needs to find BEEFY genesis block and all subsequent Mandatory blocks and sync justifications for them.
The initialization code was getting active validator sets for these older blocks from state, but in cases such as 'fast sync', state is unavailable.
This commit adds a fallback initialization mechanism when state is unavailable: parse header Digests looking for validator set change log deposits.
=> sc-consensus-beefy: fix BEEFY fast sync

bin/node/cli/build.rs, bin/node/cli/doc/shell-completion.adoc, bin/node/cli/src/chain_spec.rs, bin/node/cli/src/service.rs
The PR makes documentation fixes to the node cli section. There are some grammatical improvements and also ending a doc comment with a terminating `.`.
The changes are needed to make documentation consistent and grammatically correct.
=> fix: node cli docs

docs/DOCUMENTATION_GUIDELINES.md
Remove a sentence that was duplicated in the documentation guidelines.
=> Remove duplicate sentence

bin/node-template/pallets/template/src/lib.rs
_Micro_ nit to get clippy all green.
This will propagate downstream next release & CI PR to the https://github.com/substrate-developer-hub/substrate-node-template/ itself.
cc @shawntabrizi
=> `cargo clippy +nightly --fix` run on downstream node template

Cargo.lock, utils/wasm-builder/Cargo.toml
Just keeping wasm-opt updated.
There isn't much to be aware of in the binaryen 114 release notes:
https://github.com/WebAssembly/binaryen/blob/main/CHANGELOG.md#v114
=> Update wasm-opt to 0.114

client/consensus/manual-seal/src/lib.rs, client/consensus/manual-seal/src/rpc.rs, client/consensus/manual-seal/src/seal_block.rs
Return proof size on manually created blocks (for tests only)
- What does this PR do?
The goal of this change is to be able to get the size of the storage proof of the block in test context.
- Why are these changes needed?
To be able to check PoV limits in end2end tests like typescript tests
- How were these changes implemented and what do they affect?
=> return proof size on manually created blocks (for tests only)

client/consensus/beefy/src/communication/peers.rs, client/consensus/beefy/src/communication/request_response/incoming_requests_handler.rs, client/consensus/beefy/src/communication/request_response/mod.rs, client/consensus/beefy/src/error.rs, client/consensus/beefy/src/lib.rs, client/consensus/beefy/src/worker.rs, primitives/consensus/beefy/src/mmr.rs
When detecting pallet-beefy consensus reset, just reinitialize the worker and continue without bringing down the task (and possibly the node).
=> sc-consensus-beefy: restart voter on pallet reset
