paritytech/substrate

- Cargo.lock
- polkadot/cli/Cargo.toml
- polkadot/cli/src/cli.yml
- polkadot/cli/src/lib.rs
- polkadot/service/src/lib.rs
- substrate/client/src/client.rs
- substrate/client/src/lib.rs
- substrate/codec/src/slicable.rs
- substrate/primitives/src/authority_id.rs
- substrate/runtime/primitives/src/generic.rs
On top of #229. Review last commit please.
Closes #219.
> Block import and export

- Cargo.lock
- polkadot/parachain/Cargo.toml
- substrate/executor/Cargo.toml
- substrate/executor/src/wasm_utils.rs
- substrate/primitives/Cargo.toml
- substrate/primitives/src/sandbox.rs
- substrate/runtime-sandbox/Cargo.toml
- substrate/runtime-sandbox/with_std.rs
wasmi 0.3.0 received some initial optimizations which resulted in quite measurable speed ups on benchmarks (up to 2x).
I haven't measured the impact on the block import performance though (because I haven't succeeded to sync even a block with the current master).
> Bump wasmi to 0.3.0

- demo/runtime/src/lib.rs
- polkadot/runtime/src/lib.rs
- substrate/runtime/version/src/lib.rs
The default (poc-1 era) runtime is `polkadot-0:0`; poc-2 version should be accordingly different `polkadot-1:1`.
> Update versions, docs.

- substrate/client/src/call_executor.rs
- substrate/client/src/client.rs
- substrate/client/src/light/call_executor.rs
- substrate/executor/src/error.rs
- substrate/executor/src/lib.rs
- substrate/executor/src/native_executor.rs
This will:
1. expose a new `runtime_version` API to retrieve the (cached) `RuntimeVersion` for a code-block
2. refactor cache to keep both version and way in which it should be executed
3. replace code execution in clients with newly added `runtime_version` call
Notes:
This makes the cache value a bit more of a complex construct, keeping track of both the runtime to use and the version determined, rather than having separate caches for version and runtime which would be more costly in either parsing the wasm module more than once or running twox more than once. Through this slight increase in complexity we can prevent both of them.
> Cache the RuntimeVersion for code blocks, too

- polkadot/consensus/src/lib.rs
- polkadot/primitives/src/parachain.rs
- polkadot/runtime/src/parachains.rs
- polkadot/transaction-pool/src/lib.rs
- substrate/client/db/src/lib.rs
- substrate/client/db/src/light.rs
- substrate/client/db/src/utils.rs
- substrate/client/src/block_builder.rs
- substrate/client/src/genesis.rs
- substrate/network/src/protocol.rs
- substrate/rpc/src/state/mod.rs
- substrate/runtime/council/src/voting.rs
- substrate/runtime/executive/src/lib.rs
- substrate/runtime/primitives/src/generic.rs
- substrate/runtime/primitives/src/traits.rs
- substrate/runtime/staking/src/lib.rs
- substrate/runtime/system/src/lib.rs
- substrate/test-runtime/src/system.rs
fixes #172 .
Rename `runtimes-primitives::traits::Hashing` to `Hash` to make it more idiomatic. Also replaces `HashingFor` with `HashFor` and all the dependent uses of any of them in our code base. The cases I opted for `Hash as HashT`-imports is because it would otherwise lead to conflicting/overwriting imports from other modules.
Note: there is still one occurrence of `Hashing` in the code base: as a type on `Header`, which has both `Hash` and `Hashing` types defined. I was thinking of renaming it `Hasher` or `Hashed` but it wasn't clear to me what this is really referring to.
> Rename Hashing Trait to Hash

- substrate/environmental/src/lib.rs
Changes the `environmental!` macro to handle generic traits, e.g. `environmental!(ext: Externalities<KeccakHasher>);`.
Macros and generics don't [really mix well](https://users.rust-lang.org/t/how-to-create-a-macro-to-impl-a-provided-type-parametrized-trait/5289/14), but for limited use it can be made to work. In this case we need to handle a type parameter before [`state-machine` becomes generic](https://github.com/paritytech/polkadot/pull/297).
If there's an easier and better way to do this, I'd love to explore it.
> environmental! handles generics

- polkadot/service/src/chain_spec.rs
Apparently 128-bit integers are still not supported when serializing into `json::Value`.
Fixes #302
> Fixed spec serialization

- polkadot/service/src/chain_spec.rs
- substrate/runtime/staking/src/lib.rs
Also remove bootnodes invalid for libp2p
> Avoid accounts destroyed in payments from being aux

- substrate/network-libp2p/src/network_state.rs
Calling `disable_peer` disables a peer for only five minutes.
> Disable peers only for 5 minutes

- polkadot/cli/src/lib.rs
- polkadot/service/res/poc-1.json
- polkadot/service/src/chain_spec.rs
- substrate/service/src/chain_spec.rs
https://github.com/paritytech/polkadot/issues/279
TODO
> Issue 279 - unique path for each chains db, network, keystore to prevent collisions

- demo/cli/src/lib.rs
- demo/executor/src/lib.rs
- polkadot/cli/src/cli.yml
- polkadot/cli/src/lib.rs
- substrate/client/src/genesis.rs
- substrate/client/src/light/call_executor.rs
- substrate/executor/src/native_executor.rs
- substrate/service/src/config.rs
- substrate/service/src/lib.rs
- substrate/test-client/src/client_ext.rs
- substrate/test-client/src/lib.rs
128, in fact, wasn't enough. Also, there was no effective way of altering this within `substrate::service`. This is now fixed.
> heap-size is a CLI arg, make it 512 by default [v0.2-devp2p]

- Cargo.lock
- substrate/network-libp2p/Cargo.toml
- substrate/network-libp2p/src/custom_proto.rs
- substrate/network-libp2p/src/network_state.rs
- substrate/network-libp2p/src/service.rs
This replaces the Kademlia and custom protocols connections with [the `UniqueConnec` type](https://github.com/tomaka/libp2p-rs/blob/polkadot-tmp/core/src/unique.rs) which I've added to rust-libp2p.
There are several cases that are currently not handled properly: dialing a node that we already tried dialing earlier, handling connection failures, refusing an incoming connection to a peer when we already have one, etc.
This change delegates all this to the `UniqueConnec`.
> More robust connections

- polkadot/cli/src/lib.rs
I think it is meant to use `create` instead of open, simply because it doesn't make sense to get `Write` trait obj from `open`.
> Use create instead of open for export blocks

- substrate/network/src/import_queue.rs
- substrate/network/src/protocol.rs
- substrate/network/src/service.rs
- substrate/network/src/sync.rs
It must be stopped before the network service is stopped to make sure the thread doesn't holds the references to the network itself. This should fix the `resource deadlock avoided` error, reported by @tomaka (though I failed to reproduce it).
> Explicit stop of import queue thread

- Cargo.lock
- substrate/network-libp2p/Cargo.toml
- substrate/network-libp2p/src/network_state.rs
- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/src/transport.rs
Fixes the most pressing issues with the networking:
- Fixes a panic in `IdentifyTransport`.
- Adds a 20 seconds timeout to connections. We try to dial nodes again later if an earlier connection fails.
- Do not take into account connections that only have a Kademlia substream (and not a substrate substream) for `min_peers`/`max_peers`.
- Print the error in the logs when a connection attempt fails.
- Instead of connecting to the results of the Kademlia queries, we just pick random nodes from the peer store.
- We immediately try to connect to random nodes from the peer store at startup. The first time a node is started, it will connect to the bootstrap nodes, but afterwards it will connect to nodes it learned about earlier.
> Fix the networking

- substrate/network-libp2p/src/lib.rs
- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/src/timeouts.rs
I misinterpreted the code of devp2p. Right now timeouts only fire once, while in reality they should continue to fire forever.
cc @arkpar
> Timeouts now repeat forever

- Cargo.lock
- substrate/network-libp2p/Cargo.toml
- substrate/network-libp2p/src/custom_proto.rs
- substrate/network-libp2p/src/network_state.rs
- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/src/transport.rs
- Don't connect to our own node for Kademlia.
- Make the logs way more clear.
- Manually clear the open connections when we destroy a peer ; right now when a ping times out we destroy the peer, which is supposed to close all open futures, but this doesn't happen for an unknown reason so we do it manually
- Unsynchronize Kademlia and the connection cycles, so that logs are easier to read. The discovery cycle is now 32 seconds instead of 30.
- Should fix `assertion failed: self.remaining_mut() >= src.remaining()`.
> More networking fixes

- substrate/network-libp2p/src/network_state.rs
- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/tests/tests.rs
- substrate/network/src/service.rs
The code tries to connect to nodes immediately at startup, but since no protocol has been registered yet nothing ends up happening. This fixes it by passing the list of protocols to `start()`.
Also includes a small improvement of logging messages.
> Register protocols at the same time as we start

- polkadot/cli/src/lib.rs
- substrate/network-libp2p/src/network_state.rs
- substrate/network-libp2p/src/service.rs
fixes #339
As a fallback, we now allow one to pass bootnodes in the form of IP:PORT. In 
that case, we connect to the nodes immediately and query for its PeerID and 
store it in the peerstore after. ~~As this is a slight security risk, the query 
as well as the found response are printed as warnings.~~
This also contains the following smaller fixes:
- tiny simplification of the CLI-parsing (specifically the exit)
- centralised, single place to deal with bootnodes
- additional `add_peer` function on service
Build on top of (and included in here): #385 .
> Allow bootnodes as IP:PORT, query Peer-id

- Cargo.lock
- substrate/network-libp2p/src/transport.rs
After this PR, by default nodes will continue to use the `mplex` multiplexing protocol, but they also support `yamux`. If a node specifically requests `yamux` (ie. with a local change), it will be accepted.
I'd like to try if `yamux` happens to decrease the likehood of timeouts, because multiplexing is a tricky area and is a potential source of connection issues.
In any way, I would like to introduce `yamux` at some point in the future anyway, because `mplex` is only just a dummy protocol that exists mostly because it's easy to implement.
> Introduce support for yamux

- polkadot/network/src/lib.rs
- polkadot/network/src/tests.rs
- substrate/network-libp2p/src/connection_filter.rs
- substrate/network-libp2p/src/custom_proto.rs
- substrate/network-libp2p/src/error.rs
- substrate/network-libp2p/src/lib.rs
- substrate/network-libp2p/src/network_state.rs
- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/src/timeouts.rs
- substrate/network-libp2p/src/traits.rs
- substrate/network-libp2p/src/transport.rs
- substrate/network-libp2p/tests/tests.rs
- substrate/network/src/import_queue.rs
- substrate/network/src/io.rs
- substrate/network/src/lib.rs
- substrate/network/src/on_demand.rs
- substrate/network/src/protocol.rs
- substrate/network/src/sync.rs
- substrate/network/src/test/mod.rs
This changes the peer/`SyncIo`/`NetworkContext` API to make it more declarative and less instructive. There are no changes to logic (expect, I think in one instance), but semantics are tweaked to make it clear that it's not up the high-level (Substrate protocol) to manage the peer set first-hand. Rather the high-level can *inform* the libp2p about certain (non-)events that could only be knowable by the high-level API, such as invalid or non-existent responses, badly formatted queries or inconsistent data. The lower, libp2p, layer can then decide what course of action to take.
Rather than two separate functions (which is something of a pain), there is a single API for reporting high-level misbehaviour information on a peer: `report_peer`. There is always a `reason` given when calling …
> Refactor out disable/disconnect peer to make API more declarative

- Cargo.lock
- substrate/network-libp2p/Cargo.toml
- substrate/network-libp2p/src/transport.rs
Integrates PRs https://github.com/libp2p/rust-libp2p/pull/355 and https://github.com/libp2p/rust-libp2p/pull/360
This fixes the follwing:
- We would open multiple TCP connections for multiple substreams if they didn't open quick enough (ie. based on the order in which futures were processed).
- Even if all substreams to a remote were closed (as was the case when a ping fails for example), the code would continue to assume that the TCP connection was alive and would try use it for new substreams.
- Mplex substreams would never close, even when closed by the remote.
The network should be much more reliable with this change.
> General multiplexing fixes

- Cargo.lock
Fixes handling empty list of parameters, see https://github.com/paritytech/jsonrpc/pull/293
> Bump jsonrpc.

- substrate/network-libp2p/src/service.rs
The timeouts stream is supposed to be infinite.
I don't think there's a bug in this, but it doesn't hurt to add a warning.
> Add some logging if the timeouts stream ends

- substrate/network-libp2p/src/service.rs
It looks like the public keys of the bootnodes don't match the ones hardcoded in the binary.
> Better logging for public key mismatch

- substrate/cli/src/lib.rs
- substrate/runtime-io/without_std.rs
- substrate/state-machine/src/lib.rs
- substrate/test-runtime/src/system.rs
I've finally collected 5 items that I missed (or possibly deliberately skipped, since they are not worth mentioning) in PRs or while I was surfing the code.
> 5 random fixes (#1)

- substrate/network-libp2p/src/network_state.rs
Fix #404
Tested manually the following cases:
- no `peers.json`
- incorrect (old format) content in `peers.json`
- correct/current content 
- invalid json in `peers.json`
> Reset peers.json if the content is not loadable

- substrate/state-machine/src/ext.rs
- substrate/state-machine/src/lib.rs
> Iterate over overlay to decide which keys to purge

- README.adoc
- docker/Dockerfile
Minor changes to the doc and to the docker image.
Fix #437
> Export ws port 9944 and add doc

- Cargo.lock
Right now it happens that the buffer of `mplex` becomes full because the remote just sends us tons of packets at once. If that happens, additional packets (like, packets of data) are simply ignored.
This fixes it by increasing the buffer size (the value is now high enough that it is never reached) and killing all the substreams of the connection if we happen to reach the limit.
> Update libp2p again

- Cargo.lock
- demo/cli/src/lib.rs
- demo/executor/src/lib.rs
- polkadot/api/src/full.rs
- polkadot/parachain/Cargo.toml
- substrate/cli/src/cli.yml
- substrate/cli/src/lib.rs
- substrate/client/src/genesis.rs
- substrate/client/src/light/call_executor.rs
- substrate/executor/Cargo.toml
- substrate/executor/src/error.rs
- substrate/executor/src/native_executor.rs
- substrate/executor/src/sandbox.rs
- substrate/executor/src/wasm_executor.rs
- substrate/primitives/Cargo.toml
- substrate/runtime-sandbox/Cargo.toml
- substrate/service/src/config.rs
- substrate/service/src/lib.rs
- substrate/state-machine/src/lib.rs
- substrate/test-client/src/client_ext.rs
Since wasm interpreter now allocates memory lazily it is safe to set page limit to a high value without performance loss.
> Wasm execution optimizations

- substrate/network/src/sync.rs
Skim through the code, and this show up in my editor, can't help fixing this...
> should be MAX_IMPORTING_BLOCKS

- substrate/codec/src/codec.rs
io::Write::write is not guaranteed to process the entire buffer. it return how many bytes were processed, which might be smaller than a given buffer’s length. use write_all instead.
> use write_all instead of write

- substrate/cli/src/lib.rs
- substrate/service/src/config.rs
I have assumed that it is the full extended version name that is desired i.e. version, commit hash, platform as used in the telemetry and when starting Polkadot.
There is already a function in service::Configuration to produce this text string so it makes sense to call into it for consistency. I have made this logic available statically however, so that it can be called before there is an instance of Configuration (which can only be created after the --version string has been set because it requires return values of clap::App)
This function could be moved outside of Configuration if preferable.
> Added commit hash to --version

- Cargo.lock
- substrate/client/src/client.rs
- substrate/client/src/notifications.rs
- substrate/rpc/Cargo.toml
- substrate/rpc/src/chain/error.rs
- substrate/rpc/src/chain/mod.rs
- substrate/rpc/src/chain/tests.rs
- substrate/rpc/src/lib.rs
- substrate/rpc/src/state/mod.rs
- substrate/rpc/src/state/tests.rs
- substrate/test-client/src/block_builder_ext.rs
- substrate/test-client/src/lib.rs
Currently when you subscribe to either `newHeads` or `storage` you only get updates (so after next block is imported).
Dapps workflow usually involves first displaying current state and then subscribing to incoming changes.
To simplify this we send the initial values as the first notification in the subscription.
Also introduces `BlockBuilderExt` to simplify building test blocks using `test_client + test_runtime`
> Send initial values with subscription.

- substrate/cli/src/lib.rs
- substrate/service/src/config.rs
- substrate/service/src/lib.rs
Moved static method `full_version_from_strs` out of the `Configuration` struct to be a free function within the same module. This has simplified calls to the function by avoiding the complicated type of `Configuration`.
The `platform` function has also made the same journey for the same reasons. Additionally it is called by `full_version_from_strs` so needs to be easily accessible from the new location.
Closes #468
> --version commit hash - style improvement

- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/tests/tests.rs
- substrate/network/src/service.rs
- substrate/service/src/lib.rs
Instead of creating the service with `new()`, then calling `start()`, we do both at once.
This makes the code of `NetworkService` much more straight-forward, and is IMO better programming practices.
If we ever want to be able to stop the network, I suggest using a `Option<NetworkService>` instead.
> NetworkService::new starts the network

- polkadot/parachain/src/wasm.rs
- polkadot/parachain/tests/adder.rs
> Place call data into newly allocated pages

- ci/script.sh
Imagine you have a clean repo, you run `cargo build`, and then you do `git status` and you notice that cargo has modified the `Cargo.lock`. That happens because the `Cargo.lock` wasn't in sync with the `Cargo.toml`.
The `--locked` flag means that Cargo will return an error when they are not in sync, instead of updating the Cargo.lock.
> Locked Cargo.lock

- substrate/client/src/client.rs
- substrate/client/src/error.rs
- substrate/rpc/src/state/mod.rs
- substrate/rpc/src/state/tests.rs
> substrate: return Option in all storage related RPC methods

- Cargo.lock
- substrate/cli/Cargo.toml
- substrate/cli/src/lib.rs
- substrate/network-libp2p/Cargo.toml
- substrate/network-libp2p/src/lib.rs
- substrate/network-libp2p/src/network_state.rs
- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/src/traits.rs
- substrate/network-libp2p/tests/tests.rs
- substrate/network/src/service.rs
- Removed all the unused fields from `NetworkConfiguration`. I removed the fields that were neither set by the CLI nor implemented by libp2p. Re-adding some fields (such as `max_handshakes`) can easily be done at the time we implement them.
- The `listen_address` and `public_address` are now a `Multiaddr` instead of a `SocketAddr`. This doesn't change much in practice for now.
- Removed the `IpFilter` and `NetworkIoMessage` types and the dependency on the `ipnetwork` crate.
> Some networking cleanups

- substrate/runtime/contract/src/exec.rs
- substrate/runtime/contract/src/tests.rs
Bail out if we try to call/create when the max depth is reached.
> If contract reaches max depth, return Err

- substrate/cli/src/cli.yml
- substrate/cli/src/lib.rs
- substrate/runtime/staking/src/lib.rs
The current version listens *only* on 127.0.0.1. 
This change is required for containerised versions to run properly.
Adds:
- `--ws-external`
- `--rpc-external`
```
USAGE:
polkadot [FLAGS] [OPTIONS] [SUBCOMMAND]
FLAGS:
--dev             Run in development mode; implies --chain=dev --validator --key Alice
-h, --help            Prints help information
--light           Run in light client mode
--no-telemetry    Should not connect to the Polkadot telemetry server (telemetry is on by default on global
chains)
⥤    --rpc-external    Listen to all rpc interfaces (Default is local)
-t, --telemetry       Should connect to the Polkadot telemetry server (telemetry is off by default on local chains)
--validator       Enable validator mode
-V, --version         Prints version information
⥤ …
```
> New flags to listen to all interfaces

- README.adoc
Docker command with this typo just doesn't wok
> README: fixed typo in docker run command

- substrate/service/src/lib.rs
In order to have somewhat reliable way to keep track of / sticky specific nodes through reconnects.
> Expose node public key to telemetry

- substrate/service/src/lib.rs
Reverts paritytech/polkadot#522
> Revert "Expose node public key to telemetry"

- Cargo.lock
- substrate/network-libp2p/src/network_state.rs
- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/src/transport.rs
- Updates libp2p, bringing hopefully some fixes. This notably increases the mplex buffer size limit again.
- Add some diagnostic when a connection closes for the reason why it closed.
Before this PR, sometimes the local node drops a connection because the mplex buffer is full, and sometimes the remote drops the connection for an unknown reason.
After this PR, the problem is solved on our side but we still get connections closed by the remote.
While this PR doesn't show any improvement to the networking, if we suppose that the remote closes connections because this mplex buffer issue, then deploying it would solve a lot of things.
> Update libp2p and some log

- substrate/client/db/src/utils.rs
- substrate/network/src/service.rs
- substrate/primitives/src/hexdisplay.rs
- substrate/primitives/src/sandbox.rs
- substrate/runtime/contract/src/double_map.rs
- substrate/state-db/src/lib.rs
> typo fixes

- substrate/cli/src/lib.rs
- substrate/service/src/config.rs
- substrate/service/src/lib.rs
* Update lib.rs
* Update lib.rs
* Update config.rs
* Update lib.rs
* Update lib.rs
* tab correction
> [backport] --version commit hash - style improvement (#496)

- .gitlab-ci.yml
Add a gitlab CI build file for linux.
> Gitlab CI build file for linux.

- substrate/cli/src/cli.yml
- substrate/cli/src/lib.rs
> cli: add min-peers and max-peers

- polkadot/consensus/src/lib.rs
- polkadot/transaction-pool/src/error.rs
- polkadot/transaction-pool/src/lib.rs
- substrate/extrinsic-pool/src/listener.rs
- substrate/extrinsic-pool/src/pool.rs
Move rejection from consensus to pool verifier, so that large transactions are not propagated around.
> Reject too large transactions

- substrate/runtime/session/src/lib.rs
- substrate/runtime/staking/src/tests.rs
> Update some outdated slashing tests in runtime

- Cargo.lock
- demo/cli/src/lib.rs
- polkadot/transaction-pool/src/lib.rs
- substrate/extrinsic-pool/src/api.rs
- substrate/extrinsic-pool/src/pool.rs
- substrate/rpc-servers/Cargo.toml
- substrate/rpc-servers/src/lib.rs
- substrate/rpc/src/author/mod.rs
- substrate/rpc/src/author/tests.rs
- substrate/service/src/lib.rs
Not sure about the namespace though, should it go to a separate one? Any ideas for the name? `node` maybe? @gavofyork, @jacogr ?
> RPC: Pending Extrinsics

- substrate/rpc-servers/src/lib.rs
- substrate/rpc/src/chain/mod.rs
- substrate/rpc/src/chain/tests.rs
> RPC: Get block

- Cargo.lock
- substrate/cli/Cargo.toml
- substrate/cli/src/informant.rs
- substrate/cli/src/lib.rs
- substrate/telemetry/src/lib.rs
Fixes #443, however, it doesn't send IO usage, as it's not available in
this `sysinfo` crate.
I believe we should provide a way to opt out this feature, how do you think?
> send memory usage and cpu usage to telemetry

- Cargo.lock
- demo/runtime/src/lib.rs
- polkadot/consensus/src/offline_tracker.rs
- polkadot/runtime/src/checked_block.rs
- polkadot/runtime/src/lib.rs
- polkadot/runtime/src/parachains.rs
- polkadot/runtime/src/utils.rs
- substrate/runtime/contract/src/tests.rs
- substrate/runtime/council/src/lib.rs
- substrate/runtime/democracy/src/lib.rs
- substrate/runtime/executive/src/lib.rs
- substrate/runtime/primitives/src/traits.rs
- substrate/runtime/session/src/lib.rs
- substrate/runtime/staking/src/genesis_config.rs
- substrate/runtime/staking/src/lib.rs
- substrate/runtime/staking/src/mock.rs
- substrate/runtime/staking/src/tests.rs
Redesigns the slashing subsystem to make incremental slashing more sensible, offers a way out for validators that want a fail-safe and provides more scope for fail-overs (especially when done in combination with a weighted leader-selection algorithm).
- validators can set preferences;
- force-unstake when balance too low;
- auto-unstake after N slashes according to validator's preferences;
- exponential (base 2) slashing;
- don't early-terminate session/era unless validator becomes unstaked;
- offline grace period before punishment;
- introduced support for the new inherent extrinsic into the block-authoring subsystem.
Still to do:
> New slashing mechanism

- substrate/codec/derive/src/lib.rs
- substrate/executor/src/native_executor.rs
- Use blake2 instead of xxhash for guaranteed safety
- Simplify by caching the version rather than the compatibility (this makes it possible to provide logs to debug any potential problems)
- Additional logging
- Remove an `.expect`
> Fix runtime version cache

- substrate/executor/src/native_executor.rs
- substrate/state-machine/src/lib.rs
- One extra log from previous PR's grumble
- Kill spurious identification of consensus errors (when both wasm & native return an error)
> Fix logging

- polkadot/transaction-pool/src/error.rs
- polkadot/transaction-pool/src/lib.rs
- polkadot/transaction-pool/src/rotator.rs
If the pool occupies the queue for more than 5 minutes:
1. Remove it from the pool
2. Ban for next 30 minutes
> Time-based transaction banning

- substrate/extrinsic-pool/src/lib.rs
- substrate/extrinsic-pool/src/pool.rs
- substrate/extrinsic-pool/src/rotator.rs
* Allow replacing transactions.
* Clear old transactions and ban them temporarily.
* Move to a separate module and add some tests.
* Add bound to banned transactions.
* Remove unnecessary block and double PoolRotator.
> [forwardport] Time-based transaction banning (#594)

- substrate/executor/wasm/build.sh
- substrate/runtime-std/src/lib.rs
- LLD flag `--export-table` for wasm has been turned on by default rust-lang/rust#53237
- `feature(use_extern_macros)` has been stabilized in the latest nightlies
Recreation of #596
> Minor fixes for nightly 2018-08-18

- substrate/extrinsic-pool/src/rotator.rs
> extrinsic-pool: use retain()

- polkadot/transaction-pool/src/lib.rs
- polkadot/transaction-pool/src/rotator.rs
Authorities can figure out that transactions are invalid and remove them from the pool.
If that happens we actually make sure to ban them as well, so they don't get easily re-imported.
Addresses:  #612
> Make sure to ban invalid transactions.

- substrate/cli/src/cli.yml
- substrate/cli/src/lib.rs
- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/src/traits.rs
Allows the user to specify a multiaddress for listening, and listening on multiple addresses at once by passing the option multiple times.
Right now only the `/ip4/.../tcp/...`, `/ip6/.../tcp/...`, and `.../ws` schemes are supported in substrate.
This makes the `--port` option a bit redundant. I kept it for backward compatibility, but we ideally it would be removed.
> Allow specifying listening multiaddresses

- Cargo.lock
- substrate/bft/src/lib.rs
- substrate/client/src/client.rs
Closes #605 .
The only new commit is 6c6cae1 which will need to be backported to v0.2. All the others are cherry-picks from v0.2.
> Forward-port BFT fixes from v0.2 and restructure agreement cancelling

- substrate/runtime/contract/src/gas.rs
- substrate/runtime/contract/src/genesis_config.rs
- substrate/runtime/contract/src/lib.rs
- substrate/runtime/contract/src/tests.rs
Introduce per block gas limit checking.
Before buying gas we check how much gas available to spend in this block. The available gas is computed by substracting spent gas from the block limit. Spent gas is increased at the same time when we do refunds and reset at the block finilization stage.
> Contracts: Per block gas limit

- demo/cli/src/error.rs
- demo/cli/src/lib.rs
- subkey/src/main.rs
- substrate/cli/src/error.rs
- substrate/client/db/src/lib.rs
- substrate/client/src/call_executor.rs
- substrate/client/src/light/backend.rs
- substrate/client/src/light/mod.rs
- substrate/executor/wasm/src/lib.rs
- substrate/extrinsic-pool/src/pool.rs
- substrate/network-libp2p/src/network_state.rs
- substrate/network-libp2p/src/service.rs
- substrate/network/src/blocks.rs
- substrate/network/src/protocol.rs
- substrate/primitives/src/bytes.rs
- substrate/primitives/src/rlp_codec.rs
- substrate/rpc/src/author/tests.rs
- substrate/runtime-io/src/lib.rs
- substrate/runtime-io/without_std.rs
- substrate/runtime-sandbox/src/lib.rs
- substrate/runtime-std/src/lib.rs
- substrate/runtime/contract/src/vm/mod.rs
- substrate/service/src/components.rs
- substrate/state-db/src/unfinalized.rs
- substrate/state-machine/src/ext.rs
- substrate/state-machine/src/lib.rs
- substrate/state-machine/src/trie_backend.rs
In the spirit of https://github.com/paritytech/substrate/pull/435
It is better to check each commit separately.
> 5 random fixes (#2)

- substrate/executor/wasm/src/lib.rs
- substrate/runtime-io/src/lib.rs
- substrate/runtime-io/without_std.rs
- substrate/runtime-sandbox/src/lib.rs
- substrate/runtime-std/src/lib.rs
according to this warning:
warning: use of deprecated attribute `panic_implementation`: This attribute was renamed to `panic_handler`. See https://github.com/rust-lang/rust/issues/44489#issuecomment-415140224
> rename to panic_handler as panic_implementation is deprecated in nightly

- Cargo.lock
- substrate/network-libp2p/Cargo.toml
Removes the mplex buffer size limit, which is too quickly reached now.
This should remove some random disconnects, provided nodes upgrade.
> Backport removing mplex buffer in libp2p

- Cargo.lock
- demo/cli/src/lib.rs
- demo/executor/src/lib.rs
- demo/runtime/wasm/Cargo.lock
- substrate/cli/src/cli.yml
- substrate/cli/src/lib.rs
- substrate/client/src/call_executor.rs
- substrate/client/src/genesis.rs
- substrate/client/src/light/backend.rs
- substrate/client/src/light/call_executor.rs
- substrate/executor/src/lib.rs
- substrate/executor/src/native_executor.rs
- substrate/executor/src/sandbox.rs
- substrate/executor/src/wasm_executor.rs
- substrate/service/src/config.rs
- substrate/service/src/lib.rs
- substrate/state-machine/Cargo.toml
- substrate/state-machine/src/lib.rs
- substrate/test-client/src/client_ext.rs
- substrate/test-runtime/src/genesismap.rs
- substrate/test-runtime/wasm/Cargo.lock
try to fix #312 
But I have several question regarding this:
1. we have a CLI option to specify max heap pages, how are we going to handle this? simply remove it or make it a max cap?
2. should we have a hard limit on the heap size? otherwise I'm a bit concerned about the allocation attack.
3. we should use the `usize::decode()` interface to decode, right?
@gavofyork
> WIP on chain heap

- substrate/client/db/src/lib.rs
- substrate/state-db/src/lib.rs
- substrate/state-db/src/pruning.rs
Also fixed an issue that prevented block 0 from being pruned.
> Check for pruned block state

- Cargo.lock
- substrate/cli/src/lib.rs
- substrate/network-libp2p/Cargo.toml
- substrate/network-libp2p/src/custom_proto.rs
- substrate/network-libp2p/src/lib.rs
- substrate/network-libp2p/src/network_state.rs
- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/src/timeouts.rs
- substrate/network-libp2p/src/traits.rs
- substrate/network-libp2p/src/transport.rs
- substrate/network-libp2p/tests/tests.rs
Backports the networking from master to v0.2, so that it is identical.
This supposedly doesn't fix much, but at least we will have a unique version of libp2p everywhere.
I just copy-pasted the content of `network-libp2p` from master to v0.2, and updated the CLI crate.
Also includes a small libp2p fix.
> Backport the current networking to v0.2

- Cargo.lock
- substrate/runtime-support/Cargo.toml
- substrate/runtime-support/src/dispatch.rs
- substrate/runtime-support/src/lib.rs
The new function `json_metadata` returns the module declaration
as a json string.
Progress on: #535
> Implement function `json_metadata` in `decl_module!`

- Cargo.lock
- substrate/runtime/staking/Cargo.toml
- substrate/runtime/staking/src/lib.rs
- substrate/runtime/staking/src/tests.rs
Validators can now specify an amount of reward that they take at minimum, before the rest of the spoils get split with their nominators.
> Off-the-table staking preference

- Cargo.lock
- Cargo.toml
- demo/executor/src/lib.rs
- demo/runtime/src/lib.rs
- polkadot/parachain/test-chains/basic_add/Cargo.lock
- substrate/runtime-support/src/dispatch.rs
- substrate/runtime-support/src/storage/generator.rs
- substrate/runtime/balances/src/lib.rs
- substrate/runtime/balances/src/mock.rs
- substrate/runtime/contract/src/lib.rs
- substrate/runtime/contract/src/tests.rs
- substrate/runtime/council/Cargo.toml
- substrate/runtime/council/src/lib.rs
- substrate/runtime/council/src/voting.rs
- substrate/runtime/democracy/src/lib.rs
- substrate/runtime/example/Cargo.toml
- substrate/runtime/example/src/lib.rs
- substrate/runtime/executive/src/lib.rs
- substrate/runtime/primitives/src/traits.rs
- substrate/runtime/session/src/lib.rs
- substrate/runtime/staking/src/lib.rs
- substrate/runtime/staking/src/mock.rs
- substrate/runtime/staking/src/tests.rs
- substrate/runtime/timestamp/src/lib.rs
- substrate/runtime/treasury/Cargo.toml
- substrate/runtime/treasury/src/lib.rs
- Rename `Executable` to `OnFinalise` to reflect meaning.
- Remove unused storage item.
- Introduce `OnMinted` trait.
- Introduce new skeleton treasury module.
> Introduce treasury and document

- Cargo.lock
- substrate/network-libp2p/Cargo.toml
- substrate/network-libp2p/src/service.rs
Libp2p diff:
https://github.com/libp2p/rust-libp2p/pull/455
https://github.com/libp2p/rust-libp2p/pull/456
https://github.com/libp2p/rust-libp2p/pull/457
The last one is probably the most important, as it will allow me to check whether there's a bug in the AES crypto library we're using, as I suspect.
> Upgrade to libp2p master

- substrate/network-libp2p/src/topology.rs
Even if a node doesn't respond, we try dialing it again after 1 minute, as opposed to 30 minutes before.
This is a temporary change to hopefully improve the network.
> Backport: Reduce max backoff to 60 seconds

- substrate/runtime/staking/src/lib.rs
- substrate/runtime/staking/src/tests.rs
Use a proper struct for prefs rather than anonymous tuple.
> Minor refactor for staking module

- Cargo.lock
- substrate/network-libp2p/Cargo.toml
- substrate/network-libp2p/src/service.rs
#660 backported to v0.2.
I included a commit that upgrades tokio in the Cargo.lock to latest versions.
> Backport: Upgrade to libp2p master

- substrate/client/src/light/backend.rs
- substrate/client/src/light/blockchain.rs
- substrate/client/src/light/call_executor.rs
- substrate/client/src/light/fetcher.rs
- substrate/network/src/on_demand.rs
Implementation of [this comment](https://github.com/paritytech/substrate/issues/150#discussion_r189261529)
> Limit number of retries for light client queries

- scripts/init.sh
This reverts commit ad89579fe79af80b7de72840367146c9887ecd05.
> Revert "Install llvm-tools-preview component (#643)"

- demo/runtime/src/lib.rs
- substrate/runtime-support/src/dispatch.rs
- substrate/runtime/balances/src/lib.rs
- substrate/runtime/consensus/src/lib.rs
- substrate/runtime/contract/src/lib.rs
- substrate/runtime/council/src/lib.rs
- substrate/runtime/council/src/voting.rs
- substrate/runtime/democracy/src/lib.rs
- substrate/runtime/example/src/lib.rs
- substrate/runtime/session/src/lib.rs
- substrate/runtime/staking/src/lib.rs
- substrate/runtime/timestamp/src/lib.rs
- substrate/runtime/treasury/src/lib.rs
With this patch, the `decl_module!` macro does not require function indices.
This implementation has two drawbacks:
1. The json function id looks like `"0 + 1 + 1"` for the second index. Its not that huge problem, as the sum should be easily implementable in javascript.
2. The encoder and decoder implementations switch from using `match` to `if`s. This could have some impact on the performance.
> Remove requirement of function indices for decl_module!

- Cargo.lock
- substrate/network-libp2p/Cargo.toml
- substrate/network-libp2p/src/custom_proto.rs
- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/src/transport.rs
There are a lot of changes because we now require `Send` everywhere.
Eventually these `Send` requirements will disappear again once libp2p gets more work.
Note that since the master branch doesn't compile anymore on my machine, I'm a bit blind.
However the same changes ported to branch v0.2 worked.
> Update to latest libp2p

- Cargo.lock
- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/src/topology.rs
Backports #684 #671 
Reverts #662 
Should fix all the performances issues.
> Backport networking changes 2018-09-07 edition

- substrate/network-libp2p/src/topology.rs
Fixes all the performances issues, and should also fix most of the weird disconnects.
> Use BufReader and BufWriter

- Cargo.lock
- substrate/network-libp2p/Cargo.toml
- substrate/network-libp2p/src/network_state.rs
- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/src/topology.rs
Also updates to latest libp2p.
Changes:
- The score of an address is raised to a certain minimum value when we successfully connect to it.
- When the results of a Kademlia query indicate that the remote is connected to a peer, the reported addresses get bonus score.
- If we respond to a Kademlia query with a peer we are connected to, only report the addresses we are actually connected to. This addresses a shortcoming in the Kademlia protocol of libp2p, as there's no way to indicate individual connection statuses per address.
- Start with empty k-buckets instead of loading elements from the peer store. K-buckets contain the nodes that are reported by Kademlia.
- Fixes the fact that addresses we are connected to would be purged from the reputation because they "expired".
- Add a log entry …
> Improvements to the Kademlia system

- substrate/runtime-support/src/storage/generator.rs
- substrate/runtime-support/src/storage/mod.rs
- substrate/runtime/example/src/lib.rs
- substrate/runtime/treasury/src/lib.rs
Fixes #667 
The interface is slightly different, it actually has two forms, one for the APIs that return `Option<T>` and the other for APIs that return the raw type.
@gavofyork
> add mutate api

- substrate/service/src/lib.rs
Instead of https://github.com/paritytech/polkadot/pull/13
> Flag if the node is an Authority for Telemetry

- substrate/client/src/call_executor.rs
> Don't use Ext outside of runtime!!!

- substrate/environmental/src/lib.rs
- substrate/environmental/with_std.rs
- substrate/environmental/without_std.rs
An attempt to make the hash type parameter generic. Not fully done, but need some guidance if I'm on the right track...
> generic hash

- substrate/runtime/timestamp/src/lib.rs
Add some docs for the timestamp module
> Timestamp module docs

- srml/balances/src/lib.rs
- srml/consensus/src/lib.rs
- srml/council/src/seats.rs
- srml/council/src/voting.rs
- srml/democracy/src/lib.rs
- srml/example/src/lib.rs
- srml/session/src/lib.rs
- srml/staking/src/lib.rs
- srml/staking/src/tests.rs
- srml/support/src/dispatch.rs
- srml/treasury/src/lib.rs
> enhance dispatch

- core/executor/wasm/build.sh
- core/test-runtime/wasm/build.sh
- node/runtime/wasm/build.sh
This is required for environments where `rust` is not installed via `rustup`.
In my case, I work in such an environment and get the following error for `cargo +nightly`:
`error: no such subcommand:  +nightly`
> Check if `cargo` already from nighlty in wasm build scripts

- scripts/runtime-dep.py
> add a python script to show the runtime packages' dependencies

- node/runtime/src/lib.rs
- srml/council/src/lib.rs
- srml/executive/src/lib.rs
- srml/support/src/event.rs
- srml/support/src/metadata.rs
Depends on: https://github.com/paritytech/substrate/pull/723
> Make `impl_outer_event!` aware of required generic parameters

- srml/support/src/lib.rs
- srml/support/src/origin.rs
Fixes: https://github.com/paritytech/substrate/issues/693
> Make `impl_outer_origin!` support generic `Origin`s

- Cargo.lock
- core/cli/Cargo.toml
- core/cli/src/lib.rs
- core/network-libp2p/Cargo.toml
- core/network-libp2p/src/error.rs
- core/network-libp2p/src/lib.rs
- core/network-libp2p/src/traits.rs
- core/network-libp2p/src/transport.rs
- core/network-libp2p/tests/tests.rs
- core/network/Cargo.toml
- core/network/src/lib.rs
- core/network/src/service.rs
- node/executor/src/lib.rs
- srml/balances/src/lib.rs
- srml/balances/src/mock.rs
- srml/balances/src/tests.rs
- srml/contract/src/exec.rs
- srml/contract/src/tests.rs
- srml/support/src/lib.rs
- srml/support/src/origin.rs
[issue:#722](https://github.com/paritytech/substrate/issues/722)
would_create flag should depend on dest, not origin.
change 
```rust
let would_create = from_balance.is_zero();
```
to 
```rust
let to_balance = Self::free_balance(&dest); 
let would_create = to_balance.is_zero(); 
```
in the other hand, provide `fn new_test_ext2()` and let `transfer_fee=10`, `creation_fee=50` for test case
> bugfix: balances::transfer for new_account issue#722

- srml/contract/src/exec.rs
- srml/contract/src/lib.rs
- srml/contract/src/tests.rs
- srml/contract/src/vm/env_def/mod.rs
- srml/contract/src/vm/mod.rs
Several contract runtime functions require to return arbitrary sized buffers. These functions are:
1. `ext_get_storage`. This PR lifts the limitation on the storage value size. Now it can be arbitrary long. Thus, the length of the buffer that `ext_get_storage` returns needs to be arbitrary long too.
2. `ext_call`. Callee can return a buffer of arbitrary size.
3. `ext_create`. Returns the address (or rather `T::AccountId`) of the created contract. Typically, it is of fixed sized, but we still have to treat it as of arbitrary size since the value depends on the result of `T::AccountId::encode` (after all, nothing prevents it from returning vectors of different sizes).
so, there is a clearly need for returning arbitrary sized buffers from the contract runtime functions. I reviewed a few …
> Contracts: return arbitrary sized buffers

- Cargo.lock
- substrate/network-libp2p/Cargo.toml
- substrate/network-libp2p/src/traits.rs
Incorporates https://github.com/libp2p/rust-libp2p/pull/483, which should fix https://github.com/paritytech/polkadot/issues/21
Also hard-code an increase in the listeners slots, so that the bootstrap nodes accept more nodes.
> Update libp2p and increase listeners slots

- Cargo.lock
- core/telemetry/Cargo.toml
- core/telemetry/src/lib.rs
- Replaced the `websocket` crate with `ws`.
- `TelemetryWriter` starts a child thread which spins the `ws` connection event loop. This thread answers all `ping` frames with `pong` frames as well as handles reconnects. In catastrophic scenario where the whole event loop comes crashing down, it will just spin a new one.
- The reconnect every 2 minutes is removed. We can add something analog back if necessary (timing out on ping?) but from what I've tested if I disable and re-enable wifi the connection resets properly.
- Added few more traces.
> Telemetry refactor

- core/client/src/call_executor.rs
- core/client/src/client.rs
- core/client/src/light/fetcher.rs
- core/primitives/src/storage.rs
- core/state-machine/src/changes_trie/build.rs
- core/state-machine/src/ext.rs
- core/state-machine/src/lib.rs
- core/state-machine/src/overlayed_changes.rs
- core/state-machine/src/testing.rs
- core/test-runtime/src/genesismap.rs
- core/test-runtime/src/system.rs
- srml/consensus/src/lib.rs
- srml/system/src/lib.rs
We adding more and more keys that is native code should be aware of. However, there is no list of what currently keys substrate can expect from the runtime, what their types are, and whether they are required or not. Also, it's hard to attach documentation to literals.
This change proposes to move all known to date keys into a single place, in substrate-primitives, and maintain this list from now on, adding new keys as needed.
As a downside, this will require adding dependency on `substrate-primitives` even if these constants are all of only needed. OTOH, it didn't require to add new dependencies since `substrate-primitives` is already used as a dependency.
> Extract well known keys into a single place

- core/executor/src/sandbox.rs
- core/executor/src/wasm_executor.rs
- core/executor/wasm/src/lib.rs
- core/sr-sandbox/src/lib.rs
- core/sr-sandbox/with_std.rs
- core/sr-sandbox/without_std.rs
- srml/contract/src/vm/mod.rs
A few errors were found while analysing contracts module for running time and memory consumption characteristics.
> Fix error handling in sandboxing/contracts modules

- Cargo.lock
- substrate/network-libp2p/Cargo.toml
- substrate/network-libp2p/src/node_handler.rs
- substrate/network-libp2p/src/service.rs
- substrate/network-libp2p/src/service_task.rs
- substrate/network-libp2p/src/swarm.rs
Backport of the additional commits in #742
> Networking backport for 2018-09-20

- core/state-machine/src/backend.rs
If I read that code correctly, this function is duplicate and it seems we don't need the "pub" and we could remove the "clone()" call here. need @svyatonik 's review to verify.
> remove duplicate try_into_trie_backend

- Cargo.lock
- substrate/cli/src/lib.rs
- substrate/network-libp2p/Cargo.toml
- substrate/network-libp2p/src/lib.rs
- substrate/network-libp2p/src/node_handler.rs
- substrate/network-libp2p/src/service_task.rs
- substrate/network-libp2p/src/swarm.rs
- substrate/network-libp2p/src/topology.rs
- substrate/network-libp2p/src/traits.rs
- Should hopefully fix all the panics.
- Some reputation score adjustments: we give higher priority to addresses that nodes we are connected to report for themselves, and don't decrease the reputation if we disconnect nodes because are full or because reserved mode has been enabled.
- No longer register the dialing port in the topology (cc #747)
The bug where syncing doesn't work is not really improved by these changes, but I think it's because we keep bouncing between nodes that refuse us because they are full, and because we have random disconnects. Both problems were fixed by unreleased PRs. Once this code has been deployed to more than a few nodes, syncing should hopefully work reliably again.
> Various networking fixes for v0.2

- core/client/db/src/light.rs
- core/client/src/cht.rs
- core/client/src/light/call_executor.rs
- core/client/src/light/fetcher.rs
- core/service/src/components.rs
This removes the `From<H256>` bound for `Hash` that needs to be specified everywhere the `Service` is used.
> Removed From<H256> bound

- Cargo.lock
- node/runtime/src/lib.rs
- node/runtime/wasm/Cargo.lock
- srml/contract/Cargo.toml
- srml/contract/src/exec.rs
- srml/contract/src/lib.rs
- srml/contract/src/tests.rs
Closes #696 
Deposits the `Transfer` event each time some amount of value is transfered (initiated either by message-call or create). Events are deposited only at the top-level in case of successful execution. Events from nested contexts are only accrued if the nested context finished successfully.
> Contracts: Add transfer event

- core/client/db/src/lib.rs
- core/sr-primitives/src/generic/block.rs
- core/state-db/src/lib.rs
- core/state-db/src/noncanonical.rs
- srml/balances/src/address.rs
> State db random fixes

- Cargo.lock
- core/network-libp2p/Cargo.toml
- core/network-libp2p/src/lib.rs
- core/network-libp2p/src/traits.rs
Progress on: https://github.com/paritytech/substrate/issues/808
> Remove `ethereum-types` as direct dependency

- core/client/src/call_executor.rs
- core/client/src/client.rs
- core/client/src/genesis.rs
- core/client/src/light/call_executor.rs
- core/executor/src/lib.rs
- core/executor/src/native_executor.rs
- core/sr-version/src/lib.rs
- core/test-client/src/lib.rs
- core/test-runtime/src/lib.rs
- node/executor/src/lib.rs
- node/runtime/src/lib.rs
> Support authoring for multiple runtime versions

- srml/balances/src/mock.rs
- srml/balances/src/tests.rs
Instead of using `new_test_ext`/`new_test_ext2` this change proposes to use a builder pattern. IMO this makes code more readable, although a bit more verbose.
For example, it converts 
```rust
new_test_ext2(10, true)
```
to
```rust
&mut ExtBuilder::default()
.existential_deposit(10)
.creation_fee(50)
.monied(true)
.build()
```
This PR does **NOT** change behavior, although there is some formatting was done to keep lines
reasonably long.
> Introduce ExtBuilder in balances tests

- srml/balances/src/lib.rs
- srml/balances/src/tests.rs
Based on #822 
An user can make a call to `transfer` with such `value`, that overflows and wraps when added with `fee`. If it passes `balance too low` and `destination balance too high to receive value` checks then it could be used to create value from the thin air.
> Prevent exploiting overflow in Balances::transfer

- core/client/db/src/lib.rs
- core/client/db/src/light.rs
- core/client/db/src/utils.rs
> pass correct header column to read_meta again

- Cargo.lock
- core/rpc/Cargo.toml
- core/rpc/src/lib.rs
- core/rpc/src/state/error.rs
- core/rpc/src/state/mod.rs
The metadata call does not work anymore with JSON and just returns an
opaque blob.
> Remove `serde_json` stuff from the metadata RPC

- core/network-libp2p/src/custom_proto.rs
- core/network-libp2p/src/node_handler.rs
Right now for each substrate substream we're creating two channels, and the incoming and outgoing packets are transmitted over those channels.
This PR changes this so that we use a "flat" structure that simply polls a `CustomProtocolSubstream` struct for incoming packets, and calls a method for outgoing packets.
> Clean up the "custom protocol" code

- Cargo.lock
- core/network/Cargo.toml
- core/network/src/consensus_gossip.rs
- core/network/src/lib.rs
- core/network/src/sync.rs
Send gossip messages to `sqrt()` peers on average. Authorities still get all messages unconditionally.
> Limit gossip for non-authorities

- Cargo.lock
- subkey/Cargo.toml
- subkey/src/cli.yml
- subkey/src/main.rs
- subkey/src/vanity.rs
- Add `clap` as a dependency
- Extract vanity module and make it a subcommand
- Add `restore` command to restore a pubkey from a seed
> Add `restore` command to subkey

- core/rpc/src/state/mod.rs
- core/rpc/src/state/tests.rs
This PR changes serialization and deserialization of `data` and result of `state_call` to `Bytes` rather than `Vec<u8>`. It allows us to use `0x0020` notation rather than `[0, 32]`, e.g.:
```
$ curl \
-H 'Content-Type: application/json'\
-d '{"jsonrpc": "2.0", "method":"state_call", "params":["account_nonce", "0xf295940fa750df68a686fcf4abd4111c8a9c5a5a5a83c4c8639c451a94a7adfd"], "id":1}' \
-s http://localhost:9933/ | jq '.'
{
"jsonrpc": "2.0",
"result": "0x0000000000000000",
"id": 1
}
```
> Take and return Bytes in state_call

- core/executor/wasm/src/lib.rs
- core/sr-io/src/lib.rs
- core/sr-sandbox/src/lib.rs
- core/sr-std/src/lib.rs
This PR fixes the following warning in the CI build
```
warning: the feature `panic_handler` has been stable since 1.30.0 and no longer requires an attribute to enable
--> /home/gitlab-runner/builds/133083f6/1/parity/substrate/core/sr-std/src/lib.rs:23:43
|
23 | #![cfg_attr(not(feature = "std"), feature(panic_handler))]
|                                           ^^^^^^^^^^^^^
|
= note: #[warn(stable_features)] on by default
```
> Remove `#![feature(panic_handler)]`

- core/rpc/src/state/mod.rs
Same as #842 but for metadata
There are no places where we return `Vec` left
> metadata returns Bytes

- srml/council/src/lib.rs
- srml/democracy/src/lib.rs
- srml/metadata/src/lib.rs
- srml/support/src/dispatch.rs
- srml/support/src/lib.rs
- srml/support/src/metadata.rs
- srml/support/src/runtime.rs
This pull request adds support for encoding the outer dispatch in the metadata. So, we now should be able to use the outer dispatch from javascript.
> Some metadata cleanup and improvements

- Cargo.lock
- core/network-libp2p/Cargo.toml
- core/network-libp2p/src/lib.rs
- core/network-libp2p/src/service.rs
- core/network-libp2p/src/traits.rs
- core/network/src/protocol.rs
- core/network/src/service.rs
cc @tomusdrw 
Makes the node ID always available when querying information about a peer.
> The NodeId is always available in the session info

- Cargo.lock
- core/cli/Cargo.toml
Just a version bump to the `sysinfo` crate. [More info in the issue](https://github.com/GuillaumeGomez/sysinfo/issues/143).
Closes #870.
> Fix CPU metrics on Linux

- core/sr-primitives/src/generic/digest.rs
- core/sr-primitives/src/traits.rs
- srml/executive/src/lib.rs
To avoid commenting/uncommenting print-s in runtime. Shouldn't be a big overhead.
The only important addition is that `DigestItem` is now `Codec`, but looks like this has been the original intention, according to [this comment](https://github.com/paritytech/substrate/blob/master/core/sr-primitives/src/traits.rs#L478).
> Compare digests item-by-item

- core/network/src/on_demand.rs
- core/network/src/protocol.rs
Two light node related changes:
1) do not send OnDemand requests to peers that are missing required block;
2) do not connect to full nodes that are too far behind our best block
> Filter peers on light nodes

- core/transaction-graph/src/ready.rs
According to the comments:
```
/// Minimum number of blocks a transaction will remain valid for.
/// `TransactionLongevity::max_value()` means "forever".
pub type TransactionLongevity = u64;
```
```max_value()``` is a valid value, so we need to make sure it doesn't overflow, also add the unit test for checking this.
@tomusdrw
> fix the overflow issue

- core/executor/wasm/src/lib.rs
trivial fix.
it looks like `impl_stubs` is not important anymore, but still the `nodecode` should be removed for clarity. 
@bkchr
> remove unused nodecode in impl_stubs

- core/cli/src/lib.rs
- core/telemetry/src/lib.rs
+ Turns off all log levels for the `ws` crate used by Telemetry. (Do we use it elsewhere? Do we need error logs from it?)
+ Adds a 5s timer after failed connection due to DNS lookup (source of the spam when the node is offline).
> Silence Telemetry WS errors

- ci/script.sh
- core/client/src/blockchain.rs
- core/executor/src/wasm_utils.rs
- srml/contract/src/vm/env_def/macros.rs
I would like to put the long running tests into ignored tests. these three take too long... It speeds up my dev and testing process.
Now the ci would run both ignored and non ignored ones.
**EDIT**: after discussion, I'll just fix the ignored tests in doc test, move them to either `text` or `nocompile`. After this fix, the `cargo test -- --ignored` can run properly.
> fix the ignored tests in doc test

- core/service/src/lib.rs
- core/transaction-pool/graph/src/base_pool.rs
- core/transaction-pool/graph/src/future.rs
- core/transaction-pool/graph/src/lib.rs
- core/transaction-pool/graph/src/pool.rs
- core/transaction-pool/graph/src/ready.rs
- core/transaction-pool/graph/src/rotator.rs
- core/transaction-pool/src/tests.rs
- node/consensus/src/lib.rs
Currently it's `O(n)` to remove stale transactions - we could optimize this bucketing transactions into eras (like every 64 blocks) and then just considering transactions in a particular era (that would add another mapping to the queue `(era -> transaction)` that would have to be kept in sync though)
> Pool: Longevity handling.

- Cargo.lock
Progress on: https://github.com/paritytech/substrate/issues/886
The problem is, that we still pull in `Openssl 0.9.x` via `native-tls`.
> Updates `ws` dependency

- srml/session/src/lib.rs
Changes the comments to match the actual function to my knowledge.
> Drew.commentfix: There is no next_era function in staking.

- core/client/db/src/cache/list_storage.rs
- core/client/db/src/cache/mod.rs
- core/client/db/src/lib.rs
- core/client/db/src/light.rs
- core/client/db/src/utils.rs
> Index blocks by number in the DB

- core/client/src/client.rs
- core/network/src/protocol.rs
- core/network/src/service.rs
- core/rpc/src/author/mod.rs
- core/service/src/lib.rs
- core/service/test/src/lib.rs
- core/sr-primitives/src/transaction_validity.rs
- core/test-runtime/src/system.rs
- core/transaction-pool/graph/src/base_pool.rs
- core/transaction-pool/graph/src/pool.rs
- core/transaction-pool/graph/src/ready.rs
- core/transaction-pool/src/tests.rs
- srml/executive/src/lib.rs
- Change the `TransactionValidity` to return named fields (not sure if that's a breaking change in runtime - afair the encoding should be the same for named and index-based enum variants, so it should be good)
- Change `.ready()` to actually return an iterator that doesn't borrow the queue. Instead we have a `Arc<RwLock<_>>` storing all transactions in the pool, so now pending set can be computed in parallel with importing new transactions to the pool.
> Pool: parallel ready and runtime changes

- core/transaction-pool/graph/src/pool.rs
Fixes: https://github.com/paritytech/substrate/issues/928
> Fixes tests on master

- .dockerignore
- Dockerfile
This is the Dockerfile used to produce https://hub.docker.com/r/chevdor/substrate/tags/ and used by the BBQ node called `crash-burn`. In other words, it works as a start.
> Add docker file for Substrate

- core/service/test/src/lib.rs
- core/sr-primitives/src/generic/digest.rs
- core/sr-primitives/src/lib.rs
- core/sr-primitives/src/traits.rs
- node/runtime/src/lib.rs
- node/service/src/lib.rs
closes #926 
Brief overview:
1) moved `impl DigestImpl for Log` from runtime to `impl_outer_log` macro, so that it is implemented by `construct_runtime` macro
2) removed default impls of `DigestItem::as_*` methods to make sure when methods are adding, `impl_outer_log` macro is also updated
> Moved DigestItem impl to impl_outer_log

- README.adoc
Note: Alternative may have been to rename LICENSE to LICENSE.adoc so it would be recognised as an AsciiDoc file and modify to be `include::LICENSE.adoc[]`  https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/include-directive.adoc
> docs: Fix broken link to License in Readme

- core/client/db/README.adoc
- core/client/src/lib.rs
- core/consensus/common/README.adoc
- core/consensus/common/src/lib.rs
- core/consensus/rhd/README.adoc
- core/consensus/rhd/src/lib.rs
- core/executor/src/lib.rs
- core/finality-grandpa/README.adoc
- core/finality-grandpa/src/lib.rs
- core/keyring/src/lib.rs
- core/service/src/lib.rs
- core/sr-api/README.adoc
- core/sr-api/src/lib.rs
- core/sr-primitives/README.adoc
- core/sr-primitives/src/lib.rs
- core/sr-sandbox/src/lib.rs
- core/sr-version/README.adoc
- core/sr-version/src/lib.rs
- core/telemetry/src/lib.rs
- core/transaction-pool/README.adoc
- core/trie/README.adoc
- core/trie/README.md
- core/trie/src/lib.rs
- doc/packages/misc.adoc
- doc/packages/substrate.adoc
* Add missing README.adoc to substrate/core packages
* Add missing description tag to lib.rs so README.adoc may interpret
* Remove deprecated substrate/core packages from substrate.adoc
> docs: Relates to Issue #995. Fix links in existing documentation

- srml/example/src/lib.rs
- srml/support/src/storage/generator.rs
- srml/support/src/storage/mod.rs
This is an attempt to fix #921
However, this doesn't quite follow the exact the requirement in that issue, we could have some discussion here:
1. Should this also be applied to StorageMap's mutate? In this commit, I converted it too.
2. Because for mutate's FnOnce, we're passing the "mut ref" down, so I don't think we should pass another value out, that would be a bit inconvenient, unless we make the signature look like this `FnOnce(Self::Query) -> Self::Query`.
@gavofyork @snd
> mutate returns a value

- core/executor/src/native_executor.rs
- srml/support/src/storage/generator.rs
This needs the latest rust version of 1.30.0 
This patch would save us lots of similar code. about 800 lines removed.
> Remove pub in macros

- .dockerignore
- Dockerfile
1) by installing cargo deps before copying code, we don't have to reinstall deps every time code changes
2) by adding Dockerfile and .dockerignore to the .dockerignore, we don't have to rebuild every time while testing Docker changes
> improve docker build caching

- Dockerfile
reduces the image size by ~25%. this is motivated by wanting to reduce the memory footprint of a container in the case of testing many nodes at once. i can also include this as a separate dockerfile if we don't want to default to alpine/musl.
``` 
$ docker stats --no-stream --format "table {{.Name}}\t{{.MemUsage}}"
NAME                        MEM USAGE / LIMIT
substrate:alpine            37.23MiB / 31.3GiB
substrate:phusion           48.18MiB / 31.3GiB
$ docker images --filter=reference='substrate' --format="table {{.Repository}}\t{{.Tag}}\t{{.Size}}"
REPOSITORY          TAG                 SIZE
substrate           alpine              41.8MB
substrate           phusion             241MB
```
@chevdor @gavofyork
> docker: use alpine to slim down images

- srml/balances/src/lib.rs
Fixes: https://github.com/paritytech/substrate/issues/1050
> Make `balance::Trait::Balance` require `Member`

- core/rpc/src/chain/mod.rs
- core/rpc/src/chain/tests.rs
> Last finalised block PubSub & RPC

- core/client/src/block_builder.rs
- core/client/src/error.rs
Rename method name since it is missing the letter `r`. i.e. ApplyExt**r**insicFailed instead of  ApplyExtinsicFailed
> refactor: Fixes #1083. Rename ApplyExtrinsicFailed method without typo

- subkey/src/cli.yml
- subkey/src/main.rs
Some small improvementes that help understanding key derivation
> Simplify onboarding when using `subkey restore`

- Cargo.lock
- core/rpc/Cargo.toml
- core/rpc/src/system/error.rs
- core/rpc/src/system/mod.rs
- core/rpc/src/system/tests.rs
- core/service/src/chain_spec.rs
- core/service/src/lib.rs
- node/cli/res/bbq-birch.json
- node/cli/src/chain_spec.rs
Fixes #918 
Adds an RPC method `system_properties` which returns the top level `properties` from chain spec (must be a valid JSON object). It is optional, if not specified the RPC will return an empty json object `{ }`.
> RPC: expose chain spec `properties` 

- Dockerfile
The fix in #1101 fixed the build but it produces an image that could not run.
This PR fixes that as well.
Ref #1099
> Also change the image for the second stage

- Cargo.lock
- Cargo.toml
- core/keystore/src/lib.rs
- core/service/src/lib.rs
- node/cli/Cargo.toml
- node/cli/src/chain_spec.rs
- node/cli/src/lib.rs
- test-utils/chain-spec-builder/Cargo.lock
- test-utils/chain-spec-builder/Cargo.toml
- test-utils/chain-spec-builder/src/cli.yml
- test-utils/chain-spec-builder/src/main.rs
added a cli to generate arbitrary chain specs for testing. this will enable people to programmatically create valid chain specs for local test chains. currently, there is only support for 2 validator nodes on the local chain and i wanted to be able to spin up a cluster of arbitrary size.
i'm hoping at some point this doesn't need to take a dependency on `node-cli` and `substrate-service`, but those seem like bigger changes, and it's not urgent.
i'm also curious about people's take on leaving this out of the workspace. i'm not super familiar with cargo, so i don't know what the right thing to do here is, but it seems weird to have this build included in the top level cargo package.
> test-utils: add chain-spec-builder cli

- Cargo.lock
- core/finality-grandpa/Cargo.toml
- core/finality-grandpa/primitives/Cargo.toml
- core/finality-grandpa/src/lib.rs
- node/runtime/Cargo.toml
- node/runtime/src/lib.rs
- node/runtime/wasm/Cargo.lock
- node/runtime/wasm/Cargo.toml
Addresses @gnunicorn's last grumble on #1014
> rename fg-primitives to more verbose name

- core/consensus/aura/src/lib.rs
- node/cli/src/service.rs
> add extra verification for aura

- node/cli/src/chain_spec.rs
- node/executor/src/lib.rs
- srml/balances/src/mock.rs
- srml/consensus/src/mock.rs
- srml/contract/src/tests.rs
- srml/council/src/lib.rs
- srml/democracy/src/lib.rs
- srml/example/src/lib.rs
- srml/executive/src/lib.rs
- srml/session/src/lib.rs
- srml/staking/src/mock.rs
- srml/support/src/storage/generator.rs
- srml/system/src/lib.rs
- srml/timestamp/src/lib.rs
- srml/treasury/src/lib.rs
This makes it possible to support `GenesisConfig`s that to do not use
generic parameter.
> Introduce a `PhantomData` field in `GenesisConfig`

- core/cli/src/lib.rs
It has been changed (accidentally?) in #1128
> Fix purge-chain cli option

- core/finality-grandpa/src/lib.rs
- core/network/src/protocol.rs
- core/network/src/service.rs
- core/network/src/test/mod.rs
We keep repeating the `with_spec`-block everywhere anyone wants to send a consensus message, however this is internal behavior of the protocol and shouldn't be necessary to have knowledge of from the outside in order to send a message.
This PR changes that by providing a new `send_consensus_message` on `service` which encapsulates this entire setup and consequentially moves `consensus_gossip` a little more into the interior.
> Simplify consensus message sending

- Cargo.lock
- core/service/src/lib.rs
- node/cli/Cargo.toml
- node/cli/src/lib.rs
- node/cli/src/service.rs
The smallest possible patch to get #1158 ready for poc-3: Remove the - otherwise not needed - `ProposerFactory` from `service` and let this happen within the consensus setup itself, thus allowing the polkadot consensus framework to bring their own.
However, this does not yet offer to have this as an external crate, nor does it move the glue out of the service crate. Both could be tackled nicely in a bigger refactor with #1021.
> Remove Proposer from Service

- core/cli/src/lib.rs
- core/cli/src/params.rs
- node/cli/src/lib.rs
Parameters like `--dev`, `--base-path` or `--chain` were replicated
for each subcommand and were also present in the "top". This pr removes
these parameters from the subcommands.
The subcommands also ignored stuff like `--dev` as it was only read in
the top matcher, that did not look into the subcommand matchers.
Now, if you specify one of the parameters for a subcommand, you will get
an error instead of silently ignoring it.
Fixes: https://github.com/paritytech/substrate/issues/1184
> Cleanup the cli interface

- README.adoc
Fixes ordering of command-line arguments. `substrate --help` shows usage as substrate `[FLAGS] [OPTIONS] [SUBCOMMAND]`, where `--chain=staging` is one of the possible OPTIONS, and `build-spec` is a possible SUBCOMMAND.
The ordering should be `substrate --chain=staging build-spec` instead.
Relates to issue raised by user attente in Riot https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$154385734133299JuBZU:matrix.parity.io
> docs: Fixes ordering of command-line arguments for dumping chainspec to file

- Cargo.lock
- core/consensus/rhd/src/lib.rs
- core/sr-primitives/src/lib.rs
- srml/support/src/inherent.rs
- srml/timestamp/Cargo.toml
- srml/timestamp/src/lib.rs
This enables consensus proposers to finish proposing only when `check_inherents(block_with_inherents)` returns Ok.
In `srml-timestamp`, the `set` inherent will automatically be set forward to the next valid time, but proposers should not broadcast their block until waiting until a time specified by `CheckInherentError::ValidAfterTimestamp`.
The `check_inherents` generated by the macro will choose the highest `ValidAtTimestamp` variant returned by submodules.
> CheckInherentError can now report when something would be valid

- core/network-libp2p/src/secret.rs
- core/network-libp2p/src/service_task.rs
Fixes issue where the network folder is not created when node is run with `--node-key` arg
This causes the network toplogy to fail during `flush_to_disk()`as the "chains/target_chain/network" folder hasn't been created yet.
Example error log
```
2018-12-06 00:22:13 tokio-runtime-worker-1 WARN sub-libp2p Failed to flush topology: Os
{ code: 2, kind: NotFound, message: "No such file or directory" }
````
> Move create network folder structure to top level of start_service

- core/client/src/client.rs
The existing implementation required that a block at the given limit existed, although only if it was in the canon chain. This method is currently only used by the grandpa voter where we limit our votes based on when the next authority set change should be enacted (if any). If no block at the given max depth exists on the canon chain we fallback to the best block.
> core: fix max depth handling of best_containing

- core/client/src/client.rs
`justify_and_import` is renamed to `import` but looks like there were merge resolving issues.
> Fix master test build

- core/cli/src/lib.rs
- core/cli/src/params.rs
This restores an old behavior with more checks to inform the user
about misuse.
Only the `build-spec` parameter is not accepting these flags and options.
This subcommand only works with the options specified on the main command,
this is a restriction of the current cli parse/execute design.
> Make cli subcommands accept `--dev`, `--chain` and `--base_path`

- core/network/src/import_queue.rs
- core/network/src/sync.rs
- core/network/src/test/mod.rs
The sync module needs to track the best queued block, it does not care so much about the best imported. Before the block queue was introduced these were effectively the same. With the block queue this small change is required.
> Fixed common block tracking when syncing

- Cargo.lock
- core/rpc/src/author/mod.rs
- core/rpc/src/chain/mod.rs
- core/rpc/src/chain/tests.rs
- core/rpc/src/state/mod.rs
- core/rpc/src/state/tests.rs
- Add a missing test for `state_subscribeRuntimeVersion`
- Bump `jsonrpc` to latest version (`Metadata` for unsubscribe)
CC @jacogr might require some change in the JS API
> [RPC] Move runtime version from chain to state

- core/client/src/call_executor.rs
- core/state-machine/src/lib.rs
Following #1213 
When full node generates execution proof AND when light node checks this proof, both storage root and (if enabled) changes trie root is computed. These are immediately dropped, but cause warnings in light client logs. So I have removed calculation in this PR. But...
If we ever need roots calculation on the light node, proof should also include proof-of-touch for all modified storage items (like if we have smth like `<Events<T>>::kill();` - events are not read => execution proof doesn't have any events footprints). Not sure if we need it => extracted this change into separate PR to have separate discussion.
> Do not compute storage root when proving execution/checking proof

- core/sr-primitives/src/traits.rs
- srml/staking/src/lib.rs
- srml/staking/src/tests.rs
Previously, if a validator was slashed more times than the bit-width of the `Balance` type, the `slash` value would overflow. This would panic if the native runtime was compiled in debug mode, and the included wasm, being compiled in release mode, would silently overflow, leading to a consensus mismatch.
The way I solved this was to stop incrementing `slash_count` once the slashing logic can't handle it any more. It does it in a way that rules out 0-bit integers, but this is probably not an issue.
Closes #1260
> fix overflow in slashing logic

- srml/assets/src/lib.rs
* Run tests with `cargo test -p srml-assets`
* Add feature and tests to allow querying total supply
* Add assertion and tests to ensure that transfer amount is greater than or equal to one unit
* Replace broad `it_works` function test with various specific unit tests
* (REVERTED) Fix `destroy` function by moving assertion before the action
* Fix typos `Transfered` should be `Transferred`, `requried` should be `required`
* Reference: https://hackmd.io/nr6kPD2sR4urmljtvHs0CQ?view#Assets-Module
> Update SRML Assets: add total supply query, refactor with specific tests

- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/consensus_gossip.rs
- core/network/src/message.rs
- core/network/src/protocol.rs
- core/network/src/service.rs
- core/network/src/test/mod.rs
- core/service/src/lib.rs
- core/service/test/src/lib.rs
- node/cli/src/chain_spec.rs
- node/cli/src/service.rs
Fix #1265.
The grandpa liveness oracle was a bit flaky and could easily report false negatives. This PR removes the liveness oracle and instead always imports unjustified change blocks, this is currently safe to do since we guarantee that we won't import multiple pending change blocks for the same fork, although it could lead to stalls if the block isn't finalized in the future. I also changed the consensus gossip so that grandpa commit messages are broadcast to all peers (rather than just all authorities). The full node now always runs the grandpa voter.
In a future PR this will be extended with a sync protocol to request block justifications.
> Remove grandpa liveness oracle

- node/cli/res/charred-cherry.json
Add additional properties to the `properties` section of the chain specification -
- `networkId` - useful for determining the prefix id used in address encoding (API middleware and UI). Set to `68`, aligning with BBQ
- `tokenDecimals` - useful for user inputs e.g. Balance in UIs. Set to `15`, aligning with BBQ (naming of this property aligning with already-existing `tokenSymbol`)
> Add additional Charred Cherry chain specification properties

- core/client/src/client.rs
- core/sr-primitives/src/generic/mod.rs
- core/sr-primitives/src/generic/unchecked_mortal_compact_extrinsic.rs
Introduce a new extrinsic type that ensures the index is expressed in `Compact` form. The existing non-Compact variant (currently used by CC) will be phased out in due course and removed from the codebase hence no effort to try to deduplicate code.
> Compact extrinsics

- node/cli/src/lib.rs
- node/cli/src/params.rs
- node/cli/src/service.rs
The full node always runs the grandpa voter. If `--validator` is passed the node is started as an authority for both aura and grandpa (both validator sets are linked right now).
> node: remove grandpa authority flags

- core/sr-primitives/src/generic/digest.rs
While both works, it just looks inconsistent.
> typo: Hash -> Self::Hash

- core/cli/src/params.rs
The parameter pruning is handled by core/cli/src/lib.rs. The params type should be String.
> fix params pruning type

- core/client/src/leaves.rs
> Make sure displaced leaves are removed from the db

- core/network/src/on_demand.rs
Fix a bug where the ondemand dispatch function would loop forever. Improved the loop so that we try to dispatch as much requests as we can (currently we stop on the first request we can't dispatch).
> Improve ondemand request dispatch

- srml/support/src/runtime.rs
Documentation says the `default` macro expands to `Module, Call, Storage, Event<T>, Config`, but it actually uses the generic config: `Module, Call, Storage, Event<T>, Config<T>`
> Small update to documentation of `construct_runtime!`

- core/cli/src/lib.rs
- core/client/db/src/lib.rs
* must pass sub_matches to function, so that could get `<num>` in revert
* revert should del current best index block, not prev block
> fix bug for revert block command

- srml/council/src/seats.rs
* Add assertion and associated tests to prevent a vote from voters that provide a list of votes with a length that exceeds the amount of candidates, since otherwise an attacker may be able to submit a very long list of `votes` that far exceeds the amount of candidates and waste more computation than a reasonable voting bond would cover. Added additional associated test that may be run with `cargo test -p srml-council`
* Add assertion and associated tests so that amount of candidates must be greater than zero when calling `set_approvals` for a list of votes to be made by a voter 
* Update comment to refer to `reporter` instead of `who` (target of inactivity), since the origin is the `reporter`
* Update comment to refer more specifically to how many vote indexes, since `InactiveGracePeriod` …
> Update SRML Council: prevent excess votes/computation

- core/basic-authorship/src/lib.rs
Makes it possible to extend it and to reference those traits.
> Expose all authorship APIs

- Cargo.lock
- core/basic-authorship/src/basic_authorship.rs
- core/rpc-servers/src/lib.rs
- core/rpc/src/chain/mod.rs
- core/rpc/src/lib.rs
- core/service/src/components.rs
- core/sr-primitives/src/generic/block.rs
- core/sr-primitives/src/generic/header.rs
- core/sr-primitives/src/traits.rs
> Remove unneeded Deserialize impls.

- core/sr-io/without_std.rs
This would be useful for using non-Rust language to write Substrate-compatible modules and debugging modules at the WebAssembly level.
See also https://github.com/paritytech/substrate/issues/1331
> Some documentation for ext_ functions in Substrate Runtime API

- srml/session/src/lib.rs
- srml/support/src/lib.rs
- srml/timestamp/src/lib.rs
Moves the tuple macro into support so that it can be used be other modules easily.
> drew.tupletimestamp - Add tuple macro for timestamps too, break macro out into support

- core/network-libp2p/src/lib.rs
- core/network/src/lib.rs
- core/network/src/protocol.rs
- core/network/src/service.rs
- core/rpc-servers/src/lib.rs
- core/rpc/src/system/helpers.rs
- core/rpc/src/system/mod.rs
- core/rpc/src/system/tests.rs
I want to investigate some networking issues (#1335, #1346) but figuring out the current node status only via logs is hard. So I want to have some RPC methods to expose internal information for diagnostic purpose.
I am planning to include more details about dropped/banned peers, maybe behind a diagnostic mode flag.
Example output:
```
$ curl -H 'Content-Type: application/json' -d '{ "jsonrpc": "2.0", "method":"system_peers", "params":[], "id": 1 }' http://localhost:9933/ | jq '.'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   745  100   678  100    67  45888   4534 --:--:-- --:--:-- --:--:-- 48428
{
"jsonrpc": "2.0",
"result": [
{
"best_hash": "0x771a8de21d7a77374425b1dcf8694b039290b9c630d9112f95978e152f0f135 …
```
> expose peer information via rpc

- README.adoc
Two dashes are rendered in AsciiDoc as an em dash (`—`), so they should be escaped in order to preserve correct commands.
I suppose this pull request can be marked as `insubstantial`, but because it is my first contribution I prefer not to do so.
> Escape dashes in shell commands

- Cargo.lock
- core/keystore/Cargo.toml
- core/keystore/src/lib.rs
- core/network-libp2p/Cargo.toml
- core/primitives/Cargo.toml
Ring 0.12 and subtle 0.5 have been yanked on crates.io.
This PR updates them to newest versions.
The libp2p commit change is a quick backport of bumping ring on the version used by Substrate at the moment.
> Update ring to 0.13 and subtle to 2.0

- srml/contract/src/account_db.rs
- srml/contract/src/lib.rs
- srml/contract/src/tests.rs
- srml/support/src/double_map.rs
- srml/support/src/lib.rs
I will like to reuse the double map for a modified version of assets module to allow features like remove all balances for a particular asset (self destruct an asset).
> Move double map to support module and generalize it

- core/client/db/src/storage_cache.rs
- core/client/src/client.rs
- core/client/src/light/backend.rs
- core/rpc/src/state/mod.rs
- core/state-machine/src/backend.rs
- core/state-machine/src/proving_backend.rs
- core/state-machine/src/trie_backend.rs
Useful to get all the keys (for explorer and diagnostic purpose), get all the related keys for a particular contract, and all the modules that uses `StorageDoubleMap`.
> new state api state_getKeys to expose storage keys

- core/basic-authorship/src/basic_authorship.rs
- core/consensus/aura/src/lib.rs
Fixes #1138.
I opted for keeping the mentioned message but rephrase it slightly, because it still contains other useful information and is a good 
default in non-aura cases. Instead I added another message post pre-sealing in aura to announce the hash change, that felt more explicit 
and cleaner to me.
Run with `RUST_LOG=info node` now announces them as:
```
2019-01-11 13:50:41 Prepared block for proposing at 1 [hash: 0xe07f9bcda5e8cdf4d1d2cd5ed5787b8a7d471cf4a269b5f32dfdd6871bdb5904; 
parent_hash: 0x7171…78a8; extrinsics: [0xad52…0fdd]]
2019-01-11 13:50:41 Pre-sealed block for proposal at 1. Hash now 0x9923b1c5cc870c25175c65dd32caeb5661c36e74f1a92c7becf171e98bb74c08, 
previously 0xe07f9bcda5e8cdf4d1d2cd5ed5787b8a7d471cf4a269b5f32dfdd6871bdb5904.
```
> Properly log sealing and the newly created proposal hash from aura

- Cargo.lock
- core/client/Cargo.toml
- core/client/db/Cargo.toml
- core/network-libp2p/Cargo.toml
short-term fix for #1396. We still need to upstream (FIXME states as much).
> Upgrade the rocksdb dependency to 0.11

- CONTRIBUTING.adoc
Fix broken links to labels, update link to style guide. Add breaksapi and breaksconsensus and add a section on easy, medium and mentor ticket to get started. Slight rephrasing to clarify current process.
> Update links, labels and process in CONTRIBUTING.adoc

- README.adoc
Hi.
Here's my attempt to document how to build substrate on Windows and to finish #1343. 
To build substrate one has to install the following tools:
1. Build Tools for Visual Studio 2017 
- The Rust Installer throws an error if no Build Tools for Visual Studio are installed so I did not document how to install it explicitly. Maybe we want to make it explicit?
2. Rust
3. LLVM
4. OpenSSL
The shell files like `scripts/build.sh` can be executed with the Git Bash which I also left out for the moment.
Cheers,
Fabian
> Document how to build substrate on Windows (#1343)

- Cargo.lock
- core/network-libp2p/src/behaviour.rs
Improves peers discovery and the encryption handshake performances.
Integrates https://github.com/libp2p/rust-libp2p/pull/855 and https://github.com/libp2p/rust-libp2p/pull/856
Running the tests in `node/cli` yields something like:
Before:
```
real    0m48,839s
user    0m9,830s
sys     0m2,104s
```
After:
```
real    0m8,442s
user    0m2,685s
sys     0m0,988s
```
cc @arkpar who reported the problem
> Update libp2p-kad and libp2p-secio

- core/network-libp2p/src/custom_proto/upgrade.rs
Apparently this floods the logs of the authority nodes.
cc @ddorgan
> Remove warning for large buffer

- Cargo.lock
- core/cli/src/lib.rs
- node/cli/Cargo.toml
- node/cli/src/lib.rs
rather than always falling back to "substrate" path, which might conflict with other implementations.
fixes #1465
> Allow implementation to provide AppInfo to figure out default paths

- srml/contract/src/exec.rs
- srml/contract/src/wasm/mod.rs
- srml/contract/src/wasm/runtime.rs
This PR adds a several trivial to implement externality functions:
- `ext_value_transferred`
- `ext_gas_price`
- `ext_gas_left`
- `ext_balance`
They are all similar in the sense that they return some property of a execution context. In each case the value is returned via the scratch buffer. This works, but is little awkward for `gas_left` in particular since some amount of noise might be introduced by the high-level language compiler between calling `gas_left` and actually getting a value from it. It was discussed that we can actually constrain `Gas` type to a `u64` and just return it via a regular return value rather than (un)marshalling it through the scratch buffer but we decided to delay it for now.
cc @Robbepop
> Some trivial externalities added

- core/sr-primitives/src/generic/digest.rs
- core/sr-primitives/src/traits.rs
Uses parity-coded representation of DigestItem instead of relying on auto-derived serialization from `serde`.
This makes is more compact and more future-proof.
> Serialize digest logs as hex

- core/network-libp2p/src/custom_proto/upgrade.rs
Very minor change. Once we start shutting down our substream to a node, don't continue buffering items because we're not going to send them anyway.
May save a little bit of memory.
This could maybe affect #1414, but I don't think so.
> Don't queue messages after shutdown

- Cargo.lock
- core/network-libp2p/Cargo.toml
- core/network-libp2p/src/transport.rs
Add back support for listening on addresses that end with `/ws`, and dial addresses that end with `/ws`.
This is a step to make in-browser JavaScript nodes possible.
I had removed support due to the large number of potentially problematic dependencies.
> Put back support for WebSockets in the transport

- core/trie/src/lib.rs
Generally functions of this form, like all others in the crate, should use `IntoIterator` instead of `Iterator`. `Iterator` already implies `IntoIterator`, so this is backwards compatible.
> remove unneeded iterator bound on ordered_trie_root

- srml/contract/src/wasm/prepare.rs
This test should have been added there long time ago.
> Verify that contracts cannot use float operations

- core/cli/src/lib.rs
- core/network-libp2p/src/behaviour.rs
- core/network-libp2p/src/service_task.rs
- core/network-libp2p/src/traits.rs
- core/service/test/src/lib.rs
Report the client version to the remote (which includes the git commit hash for substrate/node), and store client versions of the nodes we are connected to with the Substrate-specific protocol. If we ban or drop a node, we show the remote's client version in the logs.
This should greatly easen debugging in the future. Unfortunately right now clients don't report their version on the wire, so that will only be helpful after people have upgraded to a version after this PR.
> Store identification info about the remote

- Cargo.lock
- core/executor/Cargo.toml
- core/executor/src/heap.rs
- core/executor/src/lib.rs
- core/executor/src/wasm_executor.rs
- core/sr-io/without_std.rs
```
$ rm -rf /home/michi/.local/share/substrate                                                                                                                   
$ ./scripts/build.sh
*** Building wasm binaries in core/executor/wasm                                                                                                              
Finished release [optimized] target(s) in 0.16s                                                                                                           
*** Building wasm binaries in node/runtime/wasm
Finished release [optimized] target(s) in 0.16s                                                                                                           
*** Building wasm binaries in core/test-runtime/wasm
Finished release [optimized] target(s) in …
```
> Fix wasm allocator

- srml/contract/src/wasm/prepare.rs
- srml/contract/src/wasm/runtime.rs
This is done because
1. there is literally no sense to use `gas` function except to acurately burn gas. Similar functionality can be achieved in the userland as well, although with some difficulties. 
2. this will allow us to move to other way of gas metering more easier. One option, is to move metering purely inside of wasm code, i.e. without calling external function. This should be useful since external calls going through sandboxing boundary is somewhat more expensive than regular external calls.
> Remove `gas` function from the public API

- core/finality-grandpa/src/lib.rs
`GrandpaBlockImport` could be given an already imported change block and it would duplicate the authority set changes. Instead, we must revert any authority set changes unless the block is successfully `Queued`.
> core: revert grandpa authorities unless imported blocked is queued

- core/finality-grandpa/src/communication.rs
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/tests.rs
Closes https://github.com/paritytech/substrate/issues/1487
We rebroadcast messages from the latest GRANDPA set/round, once every minute. In general, this is not needed, but when nodes are stuck or experience temporarily bad connectivity this can allow them to catch up to the latest round more easily.
> a wrapper network for rebroadcasting GRANDPA messages periodically

- Cargo.lock
- core/client/Cargo.toml
- core/client/db/Cargo.toml
- core/primitives/Cargo.toml
- core/sr-io/Cargo.toml
- core/state-machine/Cargo.toml
- core/trie/Cargo.toml
- node/executor/Cargo.toml
> Switch trie dependency to released versions

- srml/treasury/src/lib.rs
Fix https://github.com/paritytech/substrate/issues/1405
any params of type Permill and Perbill in runtime dispatched functions are switched to the compact variants.
> use compact Permill in methods

- core/network-libp2p/src/behaviour.rs
- core/network-libp2p/src/custom_proto/behaviour.rs
- core/network-libp2p/src/custom_proto/handler.rs
- core/network-libp2p/src/custom_proto/upgrade.rs
- core/network-libp2p/src/service_task.rs
- core/network/src/protocol.rs
- core/network/src/service.rs
Continuation of #1528 
Should now fully diagnose #1414 
When a clogging occurs, we print all the messages of the queue in the logs.
Note that logging `sync=debug` has to be enabled.
> Log the clogging networking messages

- core/finality-grandpa/src/authorities.rs
When checking for authority set changes we signal activation if `finalized >= change.effective_number`.Tthis is correct, but in practice grandpa will always vote to finalize change blocks (and not past them). This PR changes `Authorities::enacts_change` to only return `true` for the exact `change.effective_number` and not any block past it. This is necessary because otherwise sync will try to fetch justifications for all blocks imported after any block with a pending change.
> core: fix grandpa authorities enacts_change

- core/finality-grandpa/src/communication.rs
- core/finality-grandpa/src/lib.rs
- core/network/src/consensus_gossip.rs
- Only broadcast grandpa messages if the node is an authority in the current set
- Keep known consensus gossip messages for twice their expiration time
> Reduce consensus gossip spam

- core/sr-primitives/src/generic/digest.rs
- core/sr-primitives/src/lib.rs
- core/sr-primitives/src/testing.rs
- core/sr-primitives/src/traits.rs
- core/sr-primitives/src/transaction_validity.rs
- Removes `RefInto` since it doesn't seem to be used and functionally it's the same as `std::convert::AsRef`
> Add missing docs to sr-primitives

- core/inherents/src/lib.rs
- node/runtime/src/lib.rs
This makes working with them easier.
> Adds some derives for the inherent data stuff

- core/client/src/error.rs
The reasons for removing the message are:
- `error_chain` doesn't support generic parameters, so either we would need to have a different "host" error type for every state_machine or rewrite the error type without `error_chain`.
- There is little reason to handle different low-level `state_machine` errors specifically.
- With `Box` we cannot match on concrete errors, but it is also true for generic errors.
- The blokchain error is boxed too.
Closes #1422.
> Remove TODO comment about unboxing state_machine error

- core/transaction-pool/graph/src/pool.rs
> core: fix transaction-pool tests

- core/inherents/src/lib.rs
> Fix inconsistency between `CheckInherentsResult::new()/default()`

- srml/balances/src/lib.rs
> Refactor `transfer()` logic outside of dispatched function #1555

- Cargo.lock
- core/cli/src/informant.rs
- core/network-libp2p/Cargo.toml
- core/network-libp2p/src/service_task.rs
- core/network-libp2p/src/transport.rs
- core/network-libp2p/src/transport/bandwidth.rs
- core/network/src/service.rs
Fix #1545 
The file `core/network-libp2p/src/transport/bandwidth.rs` should eventually be moved to libp2p, but since libp2p master contains breaking changes, it would have been painful to integrate in Substrate on a short time frame.
We also now send `bandwidth_download` and `bandwidth_upload` to the telemetry (an integer containing the number of bytes per second), but the telemetry server doesn't interpret them.
Here is a picture:
> Report the average network bandwidth

- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/tests.rs
Instead of voting on their best block, voters instead vote on the block at depth 3/4 of the unfinalized chain. This should help with reducing the number of votes on temporary forks.
> core: grandpa limits votes to 3/4 of the unfinalized chain

- core/finality-grandpa/src/tests.rs
- core/network/src/protocol.rs
- core/network/src/sync.rs
Block requests would take precedence over justification requests. In practice, all peers would always be occupied for us to request a justification (or they would be useless: best lower than requested justification). This would stall syncing if a node imported a change but didn't observe finality through grandpa (e.g. the node was restarted).
> core: send justification requests in parallel to block requests

- core/network/src/sync.rs
Requesting from a peer that's doing ancestry search would leave it in invalid state.
> Only request justifications from available peers

- core/client/db/src/lib.rs
Seems like it has been broken recently when atomic operations were introduced. So when GRANDPA finalizes several blocks at once they're enumerated [here](https://github.com/paritytech/substrate/blob/1a26bd70b7d7b1f6411558c81753d607883566ba/core/client/db/src/lib.rs#L733) and when 2nd block is finalized, [this check](https://github.com/paritytech/substrate/blob/1a26bd70b7d7b1f6411558c81753d607883566ba/core/client/db/src/lib.rs#L637) fails, because meta still contain previous best-finalized block.
I've also noticed that now we can't import block + finalize it in single operation, because commit first tries to finalize not-yet-inserted block. Also seems like there could be an issue with internal `Backend`' state because `Backend`' meta is updated first and then we could fail for example …
> Fixed multiple blocks finalization

- subkey/Cargo.toml
- subkey/src/main.rs
- test-utils/chain-spec-builder/Cargo.toml
- test-utils/chain-spec-builder/src/main.rs
> Migrate subkey and chain-spec-builder to the 2018 edition

- core/sr-primitives/src/lib.rs
- srml/staking/src/lib.rs
- srml/treasury/src/lib.rs
related to https://github.com/paritytech/substrate/issues/1577
This PR impl Mul for Perbill and a type that is `As<u64>`
To avoid overflow we use the saturating mul method on u64. So Perbill and the other factor are converted to u64 and multiplication is made.
Previously Perbill was converted to the other factor using As.
note: we could also have used From and Into instead of As.
> harden permill perbill and impl Mul

- core/transaction-pool/Cargo.toml
- core/transaction-pool/graph/Cargo.toml
- core/transaction-pool/graph/src/base_pool.rs
- core/transaction-pool/graph/src/error.rs
- core/transaction-pool/graph/src/future.rs
- core/transaction-pool/graph/src/lib.rs
- core/transaction-pool/graph/src/listener.rs
- core/transaction-pool/graph/src/pool.rs
- core/transaction-pool/graph/src/ready.rs
- core/transaction-pool/graph/src/rotator.rs
- core/transaction-pool/graph/src/watcher.rs
- core/transaction-pool/src/api.rs
- core/transaction-pool/src/error.rs
- core/transaction-pool/src/lib.rs
- core/trie/Cargo.toml
- core/trie/benches/bench.rs
- core/trie/src/lib.rs
- core/trie/src/node_codec.rs
> Migrate tx-graph, tx-pool and trie to the 2018 edition

- node/cli/Cargo.toml
- node/cli/build.rs
- node/cli/src/chain_spec.rs
- node/cli/src/error.rs
- node/cli/src/lib.rs
- node/cli/src/service.rs
- node/executor/Cargo.toml
- node/executor/src/lib.rs
- node/primitives/Cargo.toml
- node/primitives/src/lib.rs
- node/runtime/Cargo.toml
- node/runtime/src/lib.rs
- node/runtime/wasm/Cargo.toml
- node/runtime/wasm/src/lib.rs
> Migrate node (cli, executor, primitives and runtime) to the 2018 edition

- core/network-libp2p/src/traits.rs
Right now when I'm starting two local nodes like that:
```bash
rm -rf db.alice && ./substrate --chain=local --node-key 0000000000000000000000000000000000000000000000000000000000000002 --key Alice --validator --port=30333 --bootnodes /ip4/127.0.0.1/tcp/30334/p2p/QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN -d db.alice --rpc-port=11010 --ws-port=11011 2>&1 | gawk '{ print strftime("Alice: [%Y-%m-%d %H:%M:%S]"), $0 }'
rm -rf db.bob && ./substrate --chain=local --node-key 0000000000000000000000000000000000000000000000000000000000000001 --key Bob --validator --port 30334 --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/QmXiB3jqqn2rpiKU7k1h7NJYeBg8WNSx9DiTRKz9ti2KSK -d db.bob --rpc-port=11012 --ws-port=11013 2>&1 | gawk '{ print strftime("Bob  : [%Y-%m-%d %H:%M:%S]"), $0 }'
```
I keep getting "Port …
> Make --port CLI option work again

- core/network-libp2p/src/service_task.rs
> Backport #1628

- srml/support/src/storage/generator.rs
Otherwise, with edition 2018, and use to import macros, it would complain `__storage_items_internal` not found.
> Support edition 2018 for storage_items macro

- Cargo.lock
- core/client/db/Cargo.toml
- core/client/db/src/lib.rs
- core/state-db/src/lib.rs
- core/state-db/src/noncanonical.rs
- core/state-db/src/pruning.rs
Currently we check if the block parent state is not pruned by the block number. This adds a more thorough check by block hash. 
Also fixed genesis block pruning here.
> Check for disposed blocks when creating a state.

- README.adoc
This minor pr fixes a mistake in the command to generate a chain spec in the substrate readme. Fix taken from https://github.com/paritytech/substrate/issues/1643
> Fix minor error in chain-spec generation command in readme

- core/state-db/src/lib.rs
- core/state-db/src/noncanonical.rs
> Fixed state-db block insertion

- Cargo.lock
- core/finality-grandpa/src/communication.rs
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/tests.rs
- core/network/Cargo.toml
- core/network/src/consensus_gossip.rs
- core/network/src/lib.rs
- The predicate that was being used to clean up gossip messages was wrong, so all messages were being pruned.
- The logic for keeping known messages relied on this predicate as well, so these messages would be immediately forgotten after getting pruned.
- Right after pruning we'd get them all back from the network and import them all (20K+ messages).
- Commit topics weren't being pruned at all.
- I set the expiration-based pruning to be a bit more agressive (the higher layers already have logic for resending messages when necessary).
- Garbage collection is now done on a topic, and we ignore any further messages for that topic.
- Commit messages are no longer broadcast to all peers (this was probably a bad idea all along, sorry). This might make it so that non-authority nodes observe …
> Reduce consensus spam

- Cargo.lock
- Cargo.toml
- core/cli/Cargo.toml
- core/cli/src/lib.rs
- core/executor/Cargo.toml
- core/executor/src/native_executor.rs
- core/panic-handler/Cargo.toml
- core/panic-handler/src/lib.rs
- core/state-machine/Cargo.toml
- core/state-machine/src/ext.rs
- node/src/main.rs
> Fixed panic handling

- core/finality-grandpa/src/until_imported.rs
- core/network/src/consensus_gossip.rs
This message is mostly useful when debugging a stalled grandpa voter. Also added missing docs on `consensus_gossip`.
> Lower log level of grandpa until_imported message

- core/state-db/src/noncanonical.rs
This removed linear performance dependency on the number of uncanonicalised blocks for a bit of memory tradeoff. Helps with performance now that we have uncanonicalised blocks limit increased to 4096.
> Reference counted uncanonicalised overlay

- .gitlab-ci.yml
when a tag that should become the builds version
> build tagged versions

- core/sr-primitives/Cargo.toml
- core/sr-primitives/src/generic/block.rs
- core/sr-primitives/src/generic/checked_extrinsic.rs
- core/sr-primitives/src/generic/digest.rs
- core/sr-primitives/src/generic/era.rs
- core/sr-primitives/src/generic/header.rs
- core/sr-primitives/src/generic/mod.rs
- core/sr-primitives/src/generic/tests.rs
- core/sr-primitives/src/generic/unchecked_extrinsic.rs
- core/sr-primitives/src/generic/unchecked_mortal_compact_extrinsic.rs
- core/sr-primitives/src/generic/unchecked_mortal_extrinsic.rs
- core/sr-primitives/src/lib.rs
- core/sr-primitives/src/testing.rs
- core/sr-primitives/src/traits.rs
- core/sr-primitives/src/transaction_validity.rs
- core/sr-sandbox/Cargo.toml
- core/sr-sandbox/build.rs
- core/sr-sandbox/src/lib.rs
- core/sr-sandbox/with_std.rs
- core/sr-std/Cargo.toml
- core/sr-std/build.rs
- core/sr-std/src/lib.rs
- core/sr-version/Cargo.toml
- core/sr-version/src/lib.rs
> Migrate sr-primitives, sr-sandbox, sr-std and sr-version to the 2018 edition.

- core/network/src/test/mod.rs
With #1340 the testing logic was changed to wait for a bit longer in case a node doesn't have any messages to send. Instead of sleeping, `sync` is changed to only terminate after 10 consecutive sync steps with no changes.
Fixes a grandpa test and should make them faster to run overall.
> core: network: fix sync on testing network

- Cargo.lock
Integrates the critical fix https://github.com/libp2p/rust-libp2p/pull/927
> Update libp2p-core to 0.3.4

- core/network-libp2p/src/custom_proto/behaviour.rs
- core/network-libp2p/src/custom_proto/handler.rs
Instead of starting in the enabled or disabled state, we start in the `Init` state and wait for the other task to notify whether we should be enabled or disabled. This is the correct way to do.
> Fix panic in custom protocol handler

- core/network/src/sync.rs
We request a justification for a block from a peer with the assumption that the peer has the block in its chain (because we might have announced it to him). With this assumption, the peer should never reply with an empty response to the justification request, it should just provide a `None` for the justification. But that might not be the case, the peer might not have the block in its chain (even though we assume it had), and therefore replying with an empty response is legitimate behavior that shouldn't be reported.
> Fix block justification response handling

- core/network-libp2p/src/behaviour.rs
If a node doesn't listen on any address, its identify response will not contain any address. This is therefore not a problem.
> Remove warning about empty list of identify addresses

- Cargo.lock
- core/cli/Cargo.toml
- node-template/Cargo.toml
Just some minor dependency updates
> Update substrate-cli & node-template deps

- core/network-libp2p/src/custom_proto/behaviour.rs
- core/network-libp2p/src/custom_proto/handler.rs
cc #1738 
Once a node misbehaves on the network, we print a warning once and ban it for 5 minutes.
Also fixes a bug where banning didn't work because we would clear the list of banned peers every time `poll()` was called.
> Reduce the spam from network misbehaviours

- core/network-libp2p/tests/test.rs
Close #1645 
We now check for the bandwidth usage during discovery (no more than 1kiB/sec/node), and make sure to properly account for disconnects (which can happen in case of simultaneous dialing).
> Make the discovery test more strict

- core/network-libp2p/src/custom_proto/behaviour.rs
`next_connect_to_nodes` is a `tokio_timer::Delay` that triggers when we need to call `connect_to_nodes()`.
Normally, when `connect_to_nodes()` is called, it resets `next_connect_to_nodes` to the moment when we need to call `connect_to_nodes()` again the next time.
However, in reserved mode we return early and don't reset the timer. This means that we would poll the timer, call connect_to_nodes, poll the timer, call connect to nodes, and so on, forever.
> Fix infinite loop in reserved mode

- core/network-libp2p/src/custom_proto/behaviour.rs
> Backport #1759

- core/finality-grandpa/src/lib.rs
Follow up on https://github.com/paritytech/substrate/pull/1340#discussion_r253978853
> Remove wait on future in network bridge

- core/network-libp2p/src/service_task.rs
- core/network/src/io.rs
> Backport #1769

- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/test/mod.rs
This logic was introduced in https://github.com/paritytech/substrate/pull/1658 and then mistakenly reverted in https://github.com/paritytech/substrate/pull/1340.
> core: grandpa: collect garbage for topic

- node/runtime/src/lib.rs
- scripts/gitlab/check_runtime.sh
- srml/balances/src/mock.rs
- srml/balances/src/tests.rs
Should fix https://github.com/paritytech/substrate/issues/1778
> Adding vesting tests to Balances module

- core/network-libp2p/src/secret.rs
On a first, clean build:
```
cargo run --bin substrate -- build-spec --chain=staging > ~/.substrate/chainspec.json 
Finished dev [unoptimized + debuginfo] target(s) in 0.54s
Running `target/debug/substrate build-spec --chain=staging`
2019-02-14 15:57:35 Building chain spec
2019-02-14 15:57:35 Failed to store secret key in file "/home/roman/.local/share/substrate/chains/staging_testnet/network/secret" ; err = Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
It seems to be the responsibility of `obtain_private_key` to ensure the directory exists, as per the purpose of this function, otherwise it should probably state the requirement that the directory exists prominently in its documentation. I don't quite understand why the removal of that line has been approved in …
> Ensure config directory exists.

- .gitlab-ci.yml
- scripts/gitlab/check_merge_conflict.sh
- scripts/gitlab/check_runtime.sh
The idea was to build the wasm files in a separate pipeline and create a pull request to the feature branches of pull requests that have changes in their source code and versions.
source code: https://gitlab.parity.io/parity/infrastructure/github-api/blob/master/.gitlab-ci.yml#L45
pipeline: https://gitlab.parity.io/parity/infrastructure/github-api/pipelines/30329
This PR can be merged safely as the corresponding pipeline will perform dry-run action only for the start.
Feel free to comment your thoughts on it.
(this is just the pr #1744 aiming at the master branch)
> Ci wasm builds

- core/service/src/chain_ops.rs
> Fix --import-blocks

- .gitlab-ci.yml
allow doc jobs to fail due to [this bug](https://github.com/rust-lang/rust/issues/58519).
> allow build:rust:doc:release job to fail

- Cargo.lock
- core/consensus/aura/src/lib.rs
- core/consensus/common/Cargo.toml
- core/consensus/common/src/import_queue.rs
- core/consensus/common/src/lib.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/protocol.rs
- core/network/src/service.rs
- core/network/src/sync.rs
- core/network/src/test/block_import.rs
- core/network/src/test/mod.rs
- core/network/src/test/sync.rs
- core/service/src/chain_ops.rs
- core/service/src/lib.rs
- node-template/src/service.rs
- node/cli/src/service.rs
> Rewrite the BasiQueue using channels

- core/network/src/protocol.rs
Closes #1698 
While browsing through `network::protocol` I refactored some small bits and pieces:
1. Embedded `PeerInfo` into `Peer` instead of reproducing the fields which makes it a tad more convenient to get a `PeerInfo` of a `Peer`.
2. Removed the inherent methods of `ProtocolContext` in preference of the corresponding methods of the `Context` trait impl.
3. Lowered the visibility of some structs from `pub(crate)` to private as they did not seem to be used outside of the module.
4. Addressed #1698 and removed temporary vectors.
> Small refactoring of `network::protocol` module.

- core/finality-grandpa/src/communication.rs
> Fixed sending commit message

- core/network/src/service.rs
- core/service/src/lib.rs
cc @maciejhirsz 
Reports the network identity of the node (eg. `QmSuby4Qd3QJPCq6uu9RNwPkkCWs3EeQnftQzENVThLNvt`)
> Report the network PeerId to the telemetry

- Cargo.lock
- core/cli/src/lib.rs
- core/network-libp2p/Cargo.toml
- core/network-libp2p/src/behaviour.rs
- core/network-libp2p/src/lib.rs
- core/network-libp2p/src/service_task.rs
- core/network-libp2p/tests/test.rs
- core/network/src/lib.rs
Bumps a lot of old dependencies in the process.
Fixes an infinite loop: https://github.com/libp2p/rust-libp2p/pull/961
> Update to libp2p v0.4

- srml/assets/Cargo.toml
- srml/aura/Cargo.toml
- srml/balances/Cargo.toml
- srml/consensus/Cargo.toml
- srml/contract/Cargo.toml
- srml/council/Cargo.toml
- srml/democracy/Cargo.toml
- srml/example/Cargo.toml
- srml/executive/Cargo.toml
- srml/grandpa/Cargo.toml
- srml/session/Cargo.toml
- srml/staking/Cargo.toml
- srml/sudo/Cargo.toml
- srml/timestamp/Cargo.toml
- srml/treasury/Cargo.toml
Previously `cargo test` gave the following error:
```rust
--> srml/staking/src/mock.rs:97:23
|
97 |     t.extend(::balances::GenesisConfig::<Test>{
|                          ^^^^^^^^^^^^^ not found in `balances`
```
`cargo test --all` passes normally though.
> SRML staking: remove 'default-features = false' from balances dev-dependency

- core/network/src/service.rs
This was accidentally removed during a merge conflict.
> Add back logging when we ban a peer

- Cargo.lock
- core/network-libp2p/Cargo.toml
- core/network-libp2p/src/custom_proto/behaviour.rs
- core/network-libp2p/src/custom_proto/handler.rs
- core/network-libp2p/src/custom_proto/mod.rs
- core/network-libp2p/src/custom_proto/topology.rs
- core/network-libp2p/src/custom_proto/upgrade.rs
- core/network-libp2p/src/lib.rs
- core/network-libp2p/tests/test.rs
- core/network/src/message.rs
Next two items of #1692 
Fix #1517 
See the comment here for a description: https://github.com/paritytech/substrate/issues/1517#issuecomment-461460022
This PR still uses the old behaviour by default. Once the network has upgraded to a version of Substrate/Polkadot that contains this PR, I'll try if everything works correctly (if we can still sync), then switch to the new behaviour by default, then eventually remove the old behaviour in the future.
While this PR adds a lot of code, removing the old behaviour would remove almost all of the `custom_protos` module, as we would switch to helpers that are inside libp2p.
~~I marked as "onice" because we need to publish a new version of the `yamux` crate that fixes some issues, but other than that the PR is ready.~~
> Split Substrate messages into multiple substreams

- core/network/src/service.rs
- node/cli/src/lib.rs
The threads will be named `main-tokio-0`, `main-tokio-1`, `libp2p-0`, `libp2p-1`, and so on, as opposed to `tokio-runtime-worker-N` at the moment.
Makes it easier to identify them when debugging, and makes it easier to identify where a panic comes from.
> Add names to tokio threads

- core/client/db/src/lib.rs
- core/client/db/src/light.rs
- core/client/src/leaves.rs
- core/client/src/lib.rs
* support multiple leaves at same height in leaves set
* prune leaves on finalization
* test leaves behavior in client-db
* fix no-std compilation
> Backport: Prune leaves on finality (#1871)

- core/client/db/src/light.rs
reported by @rphmeier 
I'm having test failure on this branch, as well as on master:
```
test tests::panic_execution_with_foreign_code_gives_error ... FAILED
test tests::successful_execution_with_native_equivalent_code_gives_ok ... ok
test tests::deploying_wasm_contract_should_work ... ok
test tests::full_wasm_block_import_works ... ok
test tests::wasm_big_block_import_fails ... ok
failures:
---- tests::panic_execution_with_foreign_code_gives_error stdout ----
thread 'tests::panic_execution_with_foreign_code_gives_error' panicked at 'assertion failed: `(left == right)`
left: `Ok(Success)`,
right: `Err(CantPay)`', node/executor/src/lib.rs:139:3
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
0: …
```
> Fixed instant finalization of genesis block on light client

- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/consensus_gossip.rs
- core/network/src/test/mod.rs
Reverts paritytech/substrate#1894
> Revert "Backport of gossip improvements to v0.10"

- core/network-libp2p/src/behaviour.rs
- core/network-libp2p/src/custom_proto/behaviour.rs
- core/network-libp2p/src/custom_proto/topology.rs
- core/network-libp2p/src/lib.rs
- core/network-libp2p/src/service_task.rs
- core/network/src/lib.rs
- core/network/src/service.rs
- core/rpc/src/system/mod.rs
- core/rpc/src/system/tests.rs
Close #1870 
Adds a new JSON-RPC query `system_network_state` that returns lots of things to make it possible to understand why peers are not connected.
I don't know if I'm supposed to ping someone to add the query on the JS frontend?
> Add an RPC request for the state of the network

- Cargo.lock
- core/cli/src/informant.rs
- core/cli/src/lib.rs
- core/cli/src/params.rs
- core/client/db/src/light.rs
- core/client/src/client.rs
- core/consensus/aura/Cargo.toml
- core/consensus/aura/src/lib.rs
- core/finality-grandpa/Cargo.toml
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/consensus_gossip.rs
- core/network/src/test/mod.rs
- core/service/src/chain_spec.rs
- core/service/src/config.rs
- core/service/src/lib.rs
- core/service/test/src/lib.rs
- core/telemetry/Cargo.toml
- core/telemetry/src/lib.rs
- node/cli/Cargo.toml
- node/cli/src/chain_spec.rs
(including up to the gossip improvements)
> Some backports from master

- core/cli/src/informant.rs
- core/cli/src/lib.rs
- core/client/src/client.rs
- core/client/src/lib.rs
- core/consensus/aura/src/lib.rs
- core/finality-grandpa/src/lib.rs
- core/service/src/lib.rs
> Get rid of wildcard imports

- core/network/src/service.rs
When dropping a node.
May help revealing bugs in the sync.
> Add even more diagnostic messages

- core/rpc/src/author/error.rs
> Extract specific transaction pool errors.

- core/network-libp2p/src/custom_proto/behaviour.rs
When an issue happened on a connection, we would disable it.
However the `connect_to_nodes` method doesn't take into account existing but disabled connections. The connection would keep existing but be totally useless.
This PR fixes this.
#1777 is still there, but happens way less often.
> Fix old connections not being reused

- core/sr-api-macros/src/decl_runtime_apis.rs
- core/sr-api-macros/src/impl_runtime_apis.rs
Those rust2015 imports crash cargo doc in current stable.
This is fixed in current beta but it will be published in some weeks.
> make sr-api-macros doc compile with current stable

- core/network-libp2p/src/custom_proto/behaviour.rs
- core/network-libp2p/src/custom_proto/handler.rs
- Adds a timeout when waiting for a substrate substream. When two peers connect, the dialing side is supposed to initiate a substream, while the listening side just waits. This PR adds a timeout so that the waiting side doesn't wait forever. A timeout is considered as a misbehaviour.
- In case of misbehaviour, we now always disconnect the peer. This was not the case before for non-severe misbehaviours.
- Fixes a potential panic if a protocol error message is followed with a substream-open message. When the misbehaviour message gets processed, the outer code disables the peer. Then when the substream-open message gets processed, the outer layer ignores it because the peer is disabled. Then the now-disabled peer closes the substream, and this message gets propagated despite the opening …
> Add timeouts for initialization and opening

- srml/staking/src/lib.rs
- srml/support/procedural/src/storage/transformation.rs
- srml/support/src/dispatch.rs
- Hides several metadata auxiliary functions
- Moves documentation to `GenesisConfig` fields and `Module` storage functions
- Hides dispatch functions in `Module`
- Hide `__GetByteStruct*` types in the docs
> Cleanup rustdoc

- srml/support/procedural/src/storage/impls.rs
- srml/support/procedural/src/storage/transformation.rs
- srml/support/procedural/tools/src/lib.rs
- srml/support/src/dispatch.rs
- Bring back public calls in `Module` documentation
- Forward storage item documentation to storage structs
> More documentation improvements

- core/network-libp2p/src/custom_proto/upgrade.rs
Right now the limit is not set.
> Add a 16MiB hard limit to Substrate packets

- core/finality-grandpa/src/communication.rs
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/consensus_gossip.rs
- core/network/src/protocol.rs
- core/network/src/service.rs
- core/network/src/test/mod.rs
- Remove time-based expiration. Messages are only expired by the associated `GossipValidator`.
- Force re-sending gossip messages when rebroadcasting grandpa votes.
> Minor gossip changes

- core/client/src/block_builder/api.rs
- core/consensus/aura/src/lib.rs
It was broken anyway for chains that had a different `InherentData`. It's not going to be part of our 1.0 API and most chains should have upgraded runtime by now to something handling new `InherentData`.
> remove aura inherent-checking compatibility shim

- Cargo.lock
- core/primitives/Cargo.toml
- subkey/Cargo.toml
Cargo uses "revision" (`rev`) instead of "commit" as a keyword.
> Replace the incorrect `commit` keyword with `rev`

- core/state-db/src/pruning.rs
See #1970 for issue description.
This fix might end up leaving a few unpruned nodes in the DB in case transaction fails, but the implementation is much simpler.
> Account for pending insertions when pruning

- subkey/README.adoc
The subkey README was out of date and was not very helpful to users of the tool. I've updated it to show the current usage it provides.
> Update the subkey README

- core/consensus/common/src/import_queue.rs
- core/finality-grandpa/src/authorities.rs
- core/finality-grandpa/src/import.rs
- core/network/src/sync.rs
- core/util/fork-tree/src/lib.rs
This PR contains multiple fixes related to the justifications handling.
- Since justification import is now asynchronous we need to make sure we keep track of the justifications that we sent to the import queue, otherwise we might process a finalization notification before the import result notification from the queue (which will ruin our bookkeeping);
- In grandpa block import make sure we can import a justification before trying, i.e. there aren't any dependent pending changes, otherwise we'll validate the justification against an invalid voter set.
- Change the search in the fork tree to always check the given predicate first, which is supposed to be cheaper than a call to `is_descendent_of` (comparing block numbers).
This fixes the sync slowdown observed on Alexander at around blocks …
> Fix handling of justifications

- core/network-libp2p/src/custom_proto/handler.rs
That's an overlook from me.
If the timer triggers we print an error. The next time we poll (eg. as a response to a network event), we will print the error again because the timer we still be ready.
> Don't print dozens of the times the handler init warning

- core/network-libp2p/src/service_task.rs
Fixes a stupid mistake in #2042: we use hardcoded values instead of the ones provided in the configuration.
> Fix hardcoded values in the PSM config

- core/network-libp2p/src/custom_proto/behaviour.rs
Situation:
- Node A tries to dial node B.
- Node B is unreachable, so node A "bans" it for 5 seconds.
- Node B tries to dial node A.
- Node A receives the connection.
Before this PR, node A would see that node B is banned and delay the connection being enabled until the end of the ban. After this PR, node A will accept node B.
The comes from a "misunderstanding" of the banning mechanism. The ban is not actually a ban but a prevention against repeatedly dialing the same node over and over again.
> Always accept incoming connections

- core/network-libp2p/src/custom_proto/behaviour.rs
If libp2p connects to a node that is banned, we should accept it as well. At the moment we just print an error in the logs and go on, which causes further state mismatches later on.
> Forgot to handle Banned in inject_connected

- core/cli/src/params.rs
I got the following error message when I was trying to run a node with the latest master:
```
StefanieMBP:substrate stefaniedoll$ cargo run --release \-- --dev
Finished release [optimized] target(s) in 0.92s
Running `target/release/substrate --dev`
error: 'NativeWhenPossible' isn't a valid value for '--offchain-worker-execution <STRATEGY>'
[possible values: Both, Native, NativeElseWasm, Wasm]
Did you mean 'Native'?
USAGE:
substrate --block-construction-execution <STRATEGY> --dev --importing-execution <STRATEGY> --in-peers <IN_PEERS> --node-key-type <TYPE> --offchain-worker <ENABLED> --offchain-worker-execution <STRATEGY> --other-execution <STRATEGY> --out-peers <OUT_PEERS> --pool-kbytes <COUNT> --pool-limit <COUNT> --syncing-execution <STRATEGY>
```
I think the reason is just a wrong …
> Fix offchain-worker-execution default value

- node-template/runtime/src/lib.rs
- node-template/src/chain_spec.rs
This will fix issues with `substrate-node-template` compatibility with the new crypto
> Update AccountId to use sr25519 in node-template

- core/network/src/service.rs
These messages are too low-level to be logged at info.
> core: network: reduce log level of peer drop messages

- core/cli/src/params.rs
> Use NativeWhenPossible for offchain worker.

- core/network-libp2p/src/service_task.rs
`nodes_info` is not updated properly after recent refactoring
This fixes issue with peers not being dropped and spamming logs.
> Track peers in network-libp2p

- core/client/db/Cargo.toml
- core/client/db/src/cache/mod.rs
- core/client/db/src/lib.rs
- core/client/db/src/light.rs
- core/client/src/backend.rs
- core/client/src/blockchain.rs
- core/client/src/client.rs
- core/client/src/in_mem.rs
- core/client/src/light/backend.rs
- core/client/src/light/blockchain.rs
- core/consensus/aura/src/lib.rs
- core/consensus/common/src/block_import.rs
- core/consensus/common/src/import_queue.rs
- core/consensus/common/src/lib.rs
- core/finality-grandpa/src/import.rs
> Use [u8; 4] for well known cache keys

- core/consensus/aura/slots/src/lib.rs
- core/consensus/aura/src/lib.rs
Previously, it would re-construct the digest from the parameters -- when importing blocks with deprecated but accepted seal format, this would change the seal format and lead to a hash mismatch.
> fix backwards compatibility for aura seals

- .gitlab-ci.yml
- new Dockerfile: https://github.com/paritytech/scripts/pull/63
- new cache is being saved in docker volume:
- `CARGO_HOME` set for every job's name to avoid data race condition while `cargo` tries to access the cache. `Cargo` saves dependencies and their git repositories to `CARGO_HOME`. Saving this means it's no more needed to download dependencies.
- `sccache` saves compilation cache and significantly increases compilation speed. Avoids race conditions by design (hopefully).
`GIT_STRATEGY` allows GitLab to save repository in the docker cache and update it via `git fetch`
It's required to modify runners config.
Example:
```
[[runners]]
name = "QA_experiments"
url = "https://gitlab.parity.io"
token = ""
executor = "docker"
output_limit = 16384
[runners.docker]
privileged = false …
```
> new Dockerfile, new cache

- core/consensus/aura/src/lib.rs
- node-template/runtime/wasm/Cargo.lock
- node-template/src/service.rs
- node/cli/src/service.rs
- node/runtime/wasm/Cargo.lock
Invoking `aura::import_queue` gives a chain without backwards compatibility, and the deprecated function can be removed in v2.0
This breaks compatibility with Dried Danta and old `node-template` chains.
> Aura: add a deprecated method for seal compatibility

- srml/contract/src/wasm/runtime.rs
Follow up to #2184, addressing grumbles.
Explicitly specifying `StorageKey` type alias when initialising the buffer will protect against size changes.
> Remove redundant Ok(()) and explicitly specify StorageKey buffer type

- core/client/db/src/lib.rs
(it is used to prune changes tries on finalization)
So the config is still read in `note_finalized`, since it requires much less code than reading it in constructor + updating when genesis `BlockImportOperation` is committed (+ there's a lot of tests which are constructing blocks with invalid `state_root` => storage reads in constructor are failing). Instead it is cached && the cached version is used later.
> Cache changes trie config in db storage

- core/sr-api-macros/src/decl_runtime_apis.rs
Backport of https://github.com/paritytech/substrate/pull/2190
> Fix version check for renamed runtime api methods

- core/executor/src/native_executor.rs
- core/state-machine/src/basic.rs
- core/state-machine/src/ext.rs
- core/state-machine/src/lib.rs
- core/state-machine/src/testing.rs
Both functions will ignore any overlayed changes and access the backend
directly.
> Introduce `original_storage` and `original_storage_hash`

- node/runtime/src/lib.rs
- srml/staking/src/lib.rs
Code cleanup extract from #2205 
I don't think a version bump is needed.
> code cleanup

- core/network-libp2p/src/custom_proto/handler.rs
- core/peerset/src/lib.rs
Fixes an issue with stuck connections
> Disconnect on protocol timeout

- core/network-libp2p/src/behaviour.rs
- core/network-libp2p/src/custom_proto/behaviour.rs
- core/peerset/src/lib.rs
- reduces number of calls to `alloc_slots` which always pops a peer from discovered list
> Peerset::discovered accepts many peer ids

- node/runtime/src/lib.rs
- srml/executive/src/lib.rs
Instead of calculating the `storage_root` a second time, we just can
take the `storage_root` from the new header.
> Use `storage_root` of newly calculated header

- core/network-libp2p/src/custom_proto/behaviour.rs
- core/network-libp2p/src/custom_proto/handler.rs
A connection handler can be in four different states: open+enabled, open+disabled, closed+enabled, closed+disabled.
At the moment, if the handler is open+enabled and the remote closes the substream, the handler switches to closed+disabled but the behaviour erroneously thinks the handler's new state is closed+enabled.
This PR fixes it by making the handler switch to closed+enabled, and by making the behaviour send a "disabled" message to the handler as a response to that transition.
> Fix state inconsistency between handler and behaviour

- subkey/src/main.rs
still brittle because of double-hardcoded genesis_hash
should be cmdline argument
> !fixed subkey xfer creation 

- core/network/src/test/mod.rs
In support of https://github.com/paritytech/polkadot/pull/202
> Remove Clone bound on specialization in TestNetFactory

- Cargo.lock
- core/finality-grandpa/Cargo.toml
- core/finality-grandpa/src/authorities.rs
- core/finality-grandpa/src/aux_schema.rs
- core/finality-grandpa/src/communication/mod.rs
- core/finality-grandpa/src/environment.rs
- core/finality-grandpa/src/finality_proof.rs
- core/finality-grandpa/src/import.rs
- core/finality-grandpa/src/justification.rs
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/tests.rs
Depends on #2110.
- Upgrade to finality-grandpa 0.7 (unreleased, depends on https://github.com/paritytech/finality-grandpa/pull/57, https://github.com/paritytech/finality-grandpa/pull/58, https://github.com/paritytech/finality-grandpa/pull/59).
- Support primary propose.
- Persist own votes and resend them when restarting (if appropriate).
- Persist all votes and base for the last completed round (useful for creating catch-up messages later on).
TODO
> grandpa: Voter persistence and upgrade to finality-grandpa v0.7

- core/service/src/lib.rs
We don't want Substrate, Polkadot, EdgeWare, etc. to use the same protocol ID.
If no protocol ID is configured in the chain specs, a chain automatically use the Substrate protocol ID.
This PR adds a warning if that happens.
> Add warning when using default protocol ID

- node/runtime/wasm/Cargo.lock
- srml/support/src/dispatch.rs
- srml/timestamp/src/lib.rs
Fixes: https://github.com/paritytech/substrate/issues/2235
> Throw a compile error for `on_finalise` and `on_initialise`

- core/peerset/src/lib.rs
- core/peerset/src/slots.rs
changes:
- `in_slots`, `out_slots` and `discovered` now utilize the same data structure
- discovered nodes list is now limited to `1000` entries
- `clear_common_slots` is now faster
- `add_peer` is now faster in a case where we need to swap common node with a reserved node
- `Slots` implements custom `fmt::Debug` which is more readable
> Peerset: reuse Slots data structure for discovered peers

- core/cli/src/params.rs
Consistency with Parity Ethereum CLI Light option https://github.com/paritytech/parity-ethereum/blob/master/parity/cli/mod.rs#L263
> docs: Update Substrate CLI Light option to be experimental

- core/network/src/service.rs
- core/peerset/src/lib.rs
This restores peer banning for e.g. being on a different chain, until this is properly implemented.
> Apply negative rating on explicit ban

- core/cli/src/lib.rs
- core/cli/src/params.rs
- core/rpc-servers/src/lib.rs
- core/service/src/components.rs
- core/service/src/config.rs
- core/service/src/lib.rs
- core/service/test/src/lib.rs
By default allow `localhost` origins and `https://polkadot.js.org`.
> Enable CORS checks

- node/cli/src/chain_spec.rs
- node/runtime/src/lib.rs
- srml/contract/src/lib.rs
- srml/contract/src/wasm/prepare.rs
- srml/contract/src/wasm/runtime.rs
Rel: https://github.com/Robbepop/pdsl/issues/20
Introduces the `ext_println` function which can be imported by smart contracts and used for debugging. 
There was some discussion with @pepyakin and @Robbepop about whether any debugging code should be allowed in the runtime at all, with the preferred long term solution being [Diagnostic Runtimes](https://github.com/paritytech/substrate/issues/2082).
However that is an `epic` task, and we agreed that in the interest of improving the smart contract debugging experience in the short term (in time for Sub0) we should introduce the simple `ext_println`.
This MUST be used on dev chains only. Contracts which import `ext_println` will be rejected when deployed to a chain with contract debugging disabled.
> Introduce `ext_println` to contract runtime

- core/consensus/aura/src/lib.rs
- core/consensus/common/Cargo.toml
- core/consensus/common/src/import_queue.rs
- core/finality-grandpa/Cargo.toml
- core/finality-grandpa/src/tests.rs
- core/network/Cargo.toml
- core/network/src/protocol.rs
- core/network/src/service.rs
- core/network/src/test/mod.rs
- core/network/src/test/sync.rs
closes #2143 
closes #2121 
The original issue was that there was no guarantee that `Protocol` (and sometimes `BasicQueue`) thread has processed incoming messages before some decisions were made. E.g. exit condition of [this loop](https://github.com/paritytech/substrate/blob/b5b5c32895c046767827b8264f868e80b22965ad/core/network/src/test/mod.rs#L730) is: if there are no outgoing messages from all peers for 3 consequent checks => exit. But there's no guarantee that `Protocol`s threads had a chance to process messages from the previous loop iterations. The same was with some sync tests (especially where `thread::sleep` has been used).
I've tried to make least intrusive solution - instead of introducing for-tests synchronous implementations of `Protocol` and `BasicQueue`, there are couple of …
> Fix races in sync tests

- node-template/Cargo.toml
- node-template/runtime/src/lib.rs
- node-template/src/main.rs
For substrate-up scripts:
https://github.com/paritytech/substrate-up/pull/23
> Update `template-node` to `node-template`

- core/client/db/src/lib.rs
- core/client/src/client.rs
- core/finality-grandpa/src/environment.rs
- core/network/src/consensus_gossip.rs
- core/network/src/message.rs
- core/network/src/test/sync.rs
- node-template/runtime/src/template.rs
Self-explanatory. Just to remove the known/trivial ones to make the rest of the warnings that are probably more important more emphasized.
A test will likely fail until https://github.com/paritytech/substrate/pull/2267 is merged. 
Only major warning left is explained here: https://github.com/paritytech/substrate/issues/1547.
A few doc-strings above macros changed to `//`. Makes sense since no rustdoc is generated from them. There might be more across the code-base but currently `cargo check` doesn't show more.
> Remove unused imports/ doc comments.

- core/finality-grandpa/src/lib.rs
Would only be persisted later on through `Environment`.
> core: grandpa: persist voter set state on authority set change

- core/network/src/protocol.rs
- core/network/src/service.rs
Peers running `v1.0` would ban peers running `master` as they consider new types of GRANDPA messages invalid. This PR fixes connectivity by disabling gossip with peers running older versions.
> Disable gossip for peers running old version

- core/cli/src/lib.rs
- core/cli/src/params.rs
And also whitelist `https://substrate-ui.parity.io`.
Closes #2287
> Disable CORS when running in --dev

- core/cli/src/params.rs
- core/network-libp2p/src/config.rs
We shouldn't use secp256k1, as it's deemed unsafe.
cc @romanb @burdges
**Note**: We must wait for devops to add the `--node-key-type=secp256k1` CLI option to the bootnodes of Polkadot/Substrate before deploying that, otherwise their keys will change and nobody will be able to connect anymore.
I'm unsure how to notify other chains that have a running testnet about this change.
> Use ed25519 by default for network keys

- core/peerset/src/slots.rs
We should not test debug output, especially when it can change.
> Remove peerset debug output test (again)

- Cargo.lock
- core/finality-grandpa/Cargo.toml
- core/finality-grandpa/src/environment.rs
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/observer.rs
- core/finality-grandpa/src/tests.rs
- node/cli/src/service.rs
This implements a minimal GRANDPA worker that only listens to `COMMIT` messages to finalize blocks instead of following the full GRANDPA voter protocol.
Closes #1039.
Depends on #2229 and https://github.com/paritytech/finality-grandpa/pull/61.
> grandpa: observer

- srml/support/procedural/Cargo.toml
Rel #2326 
Restrict the version of syn because of [breaking change](https://github.com/dtolnay/syn/pull/620) in parsing API.
> [srml-support] restrict patch version of syn

- node/runtime/src/lib.rs
- srml/executive/src/lib.rs
For account based systems it's fine if we only require one previous transaction, the rest (everything else between `expected_nonce .. index - 1` is required transitvely)
This allows us to remove the limitation of max 257 queued transactions, cause the vector is now always bounded.
Fixes #2308
> Remove limitation to 256 transactions, don't construct a vector.

- core/trie/src/node_codec.rs
- node/runtime/wasm/Cargo.lock
Do not allow other padding than 0x0 in trie odd nibble (this is forced on encoding).
> assert trie odd nibble padding on decoding

- core/executor/src/wasm_executor.rs
- core/primitives/src/storage.rs
- core/sr-io/with_std.rs
- core/sr-io/without_std.rs
- core/state-machine/src/basic.rs
- core/state-machine/src/ext.rs
- core/state-machine/src/lib.rs
- core/state-machine/src/testing.rs
- core/trie/Cargo.toml
- core/trie/src/lib.rs
- node/runtime/src/lib.rs
- srml/contract/src/lib.rs
- srml/contract/src/tests.rs
All functions that work with child storage (aka sub tries) take a `storage_key`. The storage key is not just a sequence of bytes as one could imagine, it is required to have a certain prefix, namely `:child_storage:`. This check was not performed however and child storage modifications were silently ignored, which has lead to missing the following issues:
- https://github.com/paritytech/substrate/issues/2277
- https://github.com/paritytech/substrate/issues/2284
Also, many child storage functions are inconsistent in the way how they handle incorrect input: no op,  return default value, return bool, return Option.
The proposed changes check for validity of a storage key. Instead of taking raw slices/vecs for a `storage_key`, a special structure is introduced: `ChildStorageKey`. It serves a …
> Check storage_key for validity

- core/network-libp2p/src/custom_proto/upgrade.rs
- core/network-libp2p/src/lib.rs
- core/network-libp2p/tests/test.rs
- core/service/src/lib.rs
Turns `ProtocolId` into a `SmallVec` instead of a `[u8; 3]`.
I put the "breaksapi" label, but this only breaks the networking API which is unstable. Technically this doesn't consist in a breaking change, but I put it just in case.
> ProtocolId can now be more than 3 bytes

- core/executor/src/wasm_executor.rs
- core/primitives/src/storage.rs
- core/sr-io/with_std.rs
- core/sr-io/without_std.rs
- core/state-machine/src/basic.rs
- core/state-machine/src/ext.rs
- core/state-machine/src/lib.rs
- core/state-machine/src/testing.rs
- core/trie/Cargo.toml
- core/trie/src/lib.rs
- srml/contract/src/lib.rs
- srml/contract/src/tests.rs
> Backport: Check storage_key for validity

- core/cli/src/informant.rs
- core/cli/src/lib.rs
- core/cli/src/params.rs
- core/client/db/src/lib.rs
- core/client/db/src/storage_cache.rs
- core/client/src/backend.rs
- core/client/src/in_mem.rs
- core/client/src/light/backend.rs
- core/service/src/components.rs
- core/service/src/config.rs
- core/service/test/src/lib.rs
Closes https://github.com/paritytech/substrate/issues/1360 and replaces the inaccurate guesstimate which was used when setting  up the state cache with exact tracking/enforcement.
The difference in the function signature of `storage_insert(…)` and `storage_remove(…)` is because when `storage_remove` is called `cache` is already borrowed mutably.
Side note: https://crates.io/crates/lru-cache contains
>WARNING: THIS PROJECT IS IN MAINTENANCE MODE, DUE TO INSUFFICIENT MAINTAINER RESOURCES
>It works fine, but will generally no longer be improved.
> Configurable state cache size and enforce exact state cache size

- Cargo.lock
- core/keystore/src/lib.rs
- core/primitives/src/ed25519.rs
- core/test-runtime/wasm/Cargo.lock
- node-template/runtime/wasm/Cargo.lock
- node/runtime/wasm/Cargo.lock
- subkey/src/vanity.rs
> Use from_ss58check and to_ss58check from Ss58Codec for ed25519

- .gitattributes
I don't know why this was done but my editor respects this and I have to edit it out every time I want to diff the `Cargo.lock`.
> git: allow diffing Cargo.lock

- core/network-libp2p/src/custom_proto/handler.rs
- core/network-libp2p/src/custom_proto/mod.rs
- core/network-libp2p/src/custom_proto/upgrade.rs
- core/network-libp2p/src/lib.rs
- core/network-libp2p/tests/test.rs
- core/network/src/message.rs
cc #1692
"Reverts" #1517 
#1517 added a new network system based on opening one new substream for each request, but kept the old networking code on the side for backwards compatibility. This was IMO a step in the right direction. However since it isn't properly tested, this new system wasn't enabled by default.
This pull request removes this system and renames "backwards compatibility mode" into "normal mode".
This PR doesn't fix any issue and doesn't change anything on the wire, but has the objective of greatly simplifying the code.
I intend to open another PR on top of this.
> Remove the multiplexed networking system

- core/trie/src/lib.rs
Directly using `trie_root` is more efficient.
> Use trie_root instead of TrieDBMut to calculate default_child_trie_root

- core/network-libp2p/src/custom_proto/handler.rs
This modifies `handler.rs` to allow multiple simultaneous Substrate substreams.
Normally, only one Substrate-related substream should be open at any given time with the remote.
However, in the situation where we close the substream with a remote, both the remote and us will re-open one at the same time.
When that happens, both the remote and us will think that the remote misbehaved, and will close the substream that the remote opened, leading to zero substream in the end.
If we were allowed to break backwards compatibility, I would make both sides open a substream when we connect. In the end, only the dialer opens one, to stay compatible with the current behaviour.
One remaining issue is that if we want to re-enable a disabled connection, the remote, if it is running an old node, may …
> Allow multiple substreams

- core/network/src/consensus_gossip.rs
- core/network/src/protocol.rs
- core/network/src/sync.rs
Starting some refactoring of the `network` crate.
Replaces `Context::send_message` with more specialized methods, so that we can eventually isolate code a bit more.
I kept `send_chain_specific` because it is used by Polkadot.
> Split Context::send_message into multiple methods

- node/runtime/src/lib.rs
- srml/contract/src/account_db.rs
related to https://github.com/paritytech/substrate/issues/2365
also it could be better to have safety in child storage. https://github.com/paritytech/substrate/issues/2413
(I'm not sure I completely know why it is not the responsability of the contract to do it though)
> store contract keys with blake2_256

- node/runtime/src/lib.rs
- srml/contract/src/account_db.rs
* store contract keys with blake2_256
* bump version
backport fix of https://github.com/paritytech/substrate/issues/2365
I don't know if backport is necessary, close it if not.
> backport store contract keys with blake2_256 (#2414)

- Cargo.lock
- core/consensus/aura/Cargo.toml
- core/consensus/aura/src/lib.rs
- core/consensus/slots/Cargo.toml
- core/consensus/slots/src/lib.rs
For #2416, let's deprecate the functions that call `thread::spawn` and instead ask the user to create a thread themselves if they want one.
The two deprecated functions aren't used anywhere.
> Depreate functions that spawn a thread

- srml/contract/src/lib.rs
This is to support a wrapper module which will add an access control layer to the SRML Contract module.
See: https://github.com/shawntabrizi/sudo-contract
I am not 100% this will work, so if there are suggestions or guidance here, I am open ears.
> Add `pub` to functions in Contract module

- core/network-libp2p/src/behaviour.rs
- core/network-libp2p/src/custom_proto/behaviour.rs
- core/network-libp2p/src/custom_proto/handler.rs
Adds in the API a reason why the handler reported the connection as closed.
Also fixes #2379 not being implemented correctly, because we would close the connection on the first substream that gets closed.
> Add reason for closing and fix multiple substreams

- core/sr-std/with_std.rs
We became to can use BTreeSet Encode/Decode.(ref: https://github.com/paritytech/parity-codec/pull/75)
So, I add BtreeSet within sr-std.
> Add BtreeSet with sr-std.

- core/cli/src/lib.rs
- node-template/src/cli.rs
- node/cli/src/lib.rs
This is a breaking change and not sure if this is the best way to do it.
But I want to be able to customize the config including the core one before running the node, without the needs to fork substrate.
This also allow me to implement something like `--my-dev` which set bunch parameters include chain, cors, validator, key, etc. Similar to `--dev`, but with different set of configs.
> Pass CLI `RunCmd` parameter to the user

- srml/contract/src/lib.rs
Switch terminology to "balance units" since EDG was used only for example, and doesn't really represents the state of things, i.e. srml-contract is a module which can be used in different chains which can have their own balances called whatever they want.
This PR doesn't alter any logic, only rustdoc.
> Change terminology used in srml-contract docs

- Cargo.lock
- core/consensus/common/Cargo.toml
- core/consensus/common/src/error.rs
Replaces `tokio` with `tokio-timer`, so that we don't indirectly depend on `mio`.
Relevant for #2416.
Shouldn't break any API.
> tokio -> tokio-timer in consensus

- core/consensus/common/src/import_queue.rs
- core/network-libp2p/src/behaviour.rs
- core/network-libp2p/src/lib.rs
- core/network/src/consensus_gossip.rs
- core/network/src/lib.rs
- core/network/src/on_demand.rs
- core/network/src/protocol.rs
- core/network/src/service.rs
- core/network/src/sync.rs
- core/network/src/test/mod.rs
Replaces reporting peers by severity with reputation changes and disconnects.
Also adds beneficial reputation changes for some events.
I replaced reporting "bad" peers with adding `i32::min_value()` to their reputation and sending a disconnect message.
The reputation values are quite arbitrary. I took some inspiration from the ones in `finality-grandpa`, but am unfortunately not sure about the frequency of events.
Breaks the API of the `network` crate, which is marked as unstable anyway.
> Add reputation system to network crate

- core/cli/src/lib.rs
- core/cli/src/params.rs
One will no longer connect to other nodes when using `--dev`.
> Disable mDNS when passing --dev

- core/network/src/service.rs
Method is unused. We have `report_peer` right below that does the same.
> Remove NetworkService::report_handle

- core/network-libp2p/src/behaviour.rs
On the Emberic Elm network, we sometimes have misbehaving nodes that report too many listened addresses (in practice it is probably caused by a very old bug in libp2p). We print more information about the node when that happens.
> Show more information when too many addresses are reported

- core/network-libp2p/src/lib.rs
While the text is obviously technically correct, I would be glad if someone did an orthograph/grammar/style pass on this.
> Add some crate-level documentation to network-libp2p

- node/runtime/src/lib.rs
- srml/support/procedural/src/lib.rs
- srml/support/procedural/src/storage/impls.rs
- srml/support/procedural/src/storage/mod.rs
- srml/support/procedural/src/storage/transformation.rs
- srml/support/src/hashable.rs
- srml/support/test/tests/final_keys.rs
I don't know if it is wanted in v1.0
backport https://github.com/paritytech/substrate/pull/2451
related to https://github.com/paritytech/substrate/issues/2443
and update the doc of decl_storage as on master
another possibility would be to document current behavior in the doc.
> backport fix doublemapkey

- core/executor/wasm/src/lib.rs
- core/finality-grandpa/primitives/src/lib.rs
- core/primitives/src/lib.rs
- core/sr-io/src/lib.rs
- core/sr-sandbox/src/lib.rs
- core/sr-std/src/lib.rs
- core/trie/src/lib.rs
- node-template/runtime/src/lib.rs
- node/primitives/src/lib.rs
- node/runtime/src/lib.rs
- srml/executive/src/lib.rs
- srml/support/src/lib.rs
- srml/system/src/lib.rs
- First 80 random values come from cycling the incomplete series (
instead of filling with zeroes)
- Calculate random material each usage (use a single amalgamated
ring buffer to store them for avoiding 81 lookups each time)
- Mutate inputs by hashing each with:
- its index (into the 81)
- an additional "subject" key provided by caller
This keeps the final output low-influence while still allowing
it to be used as the seed to independent contexts. (Hashing the
result to give the final seed is no better than using parent_hash).
> Clean up random seed to make a bit more flexible

- Cargo.lock
- core/primitives/Cargo.toml
- core/primitives/benches/benches.rs
fix #2354.
- Split benches into fixed size (hash one key with `MAX` size `N` times) and dynamic size (hash keys with size in range `(2,MAX,4)` `N` times).
- Interestingly shows that the twox hashes are dependent on the input size while blake seems to be not.
> Move hashing benches to Criterion.

- Cargo.lock
- core/cli/src/lib.rs
- core/cli/src/params.rs
- core/consensus/common/Cargo.toml
- core/network-libp2p/Cargo.toml
- core/network-libp2p/src/behaviour.rs
- core/network-libp2p/src/custom_proto/behaviour.rs
- core/network-libp2p/src/custom_proto/handler.rs
- core/network-libp2p/src/custom_proto/mod.rs
- core/network-libp2p/src/custom_proto/upgrade.rs
- core/network-libp2p/src/lib.rs
- core/network-libp2p/src/service_task.rs
- core/network-libp2p/tests/test.rs
- core/network/src/consensus_gossip.rs
- core/network/src/message.rs
- core/network/src/protocol.rs
- core/network/src/service.rs
- core/network/src/sync.rs
- core/peerset/Cargo.toml
- core/service/src/lib.rs
- core/service/test/src/lib.rs
Backports everything related to networking before May 3rd, plus #2467 and #2473.
This includes some breaking changes to the API, which is fine since:
- We warn that the network crate's API is unstable.
- 1.0 isn't out yet anyway.
> v1.0 networking backports

- Cargo.lock
- core/cli/src/lib.rs
- core/cli/src/params.rs
- core/consensus/common/Cargo.toml
- core/network-libp2p/Cargo.toml
- core/network-libp2p/src/behaviour.rs
- core/network-libp2p/src/custom_proto/behaviour.rs
- core/network-libp2p/src/custom_proto/handler.rs
- core/network-libp2p/src/custom_proto/mod.rs
- core/network-libp2p/src/custom_proto/upgrade.rs
- core/network-libp2p/src/lib.rs
- core/network-libp2p/src/service_task.rs
- core/network-libp2p/tests/test.rs
- core/network/src/consensus_gossip.rs
- core/network/src/message.rs
- core/network/src/protocol.rs
- core/network/src/service.rs
- core/network/src/sync.rs
- core/peerset/Cargo.toml
- core/service/src/lib.rs
- core/service/test/src/lib.rs
This PR is against `v1.0` but it is not strictly a backport, it "forks" a bit v1.0 compared to master.
Based on top of #2486, and only the last commit is relevant.
More specifically, it silences two warnings in v1.0:
- "Banning node ...": banning has been removed in master by #2454, but the change is quite experimental and it might be a bad idea to backport it.
- "Handler initialization is too long": this is being fixed in master as part of the current effort to rework the threading story of network (#2475). But similarly this is too big of a change to backport.
> v1.0: Silence errors

- core/sr-std/with_std.rs
- core/sr-std/without_std.rs
- Add convert
- Add btree_set for without_std
> Fix std/core crates

- core/client/src/light/call_executor.rs
- core/network/src/consensus_gossip.rs
- core/network/src/protocol.rs
There are 3 issues currently (each one takes its own commit):
- the main issue that causes (almost) instant disconnect is that consensus gossip messages are sent to light nodes && light nodes do not have gossip listeners registered. I've fixed that by ignoring light nodes in `ConsensusGossip` - think that is the correct way;
- the second issue is a typo in `LightCallExecutor::version` - instead of "version" it should call "Core_version". Currently aura verifier calls this - that should be fixed by #1669 ;
- the third one is the most complex, linked to the peer reputation system. The initial node reputation is zero. Normally, when full nodes are connected to each other, they first interchanging with GRANDPA messages => their reputation is increased. But because of (first issue) above, we …
> Fix light connection issues

- node/runtime/src/lib.rs
- srml/balances/src/lib.rs
- srml/staking/src/lib.rs
- srml/support/src/traits.rs
(I don't expect this can be merged. This is more of an issue with related code to show my point.)
I think we should release the `As` bound on `Balance` type because it may cause issues (#1377). Even substrate code base have no such issue exists, it is impossible to ensure such issue won't exist on other runtimes.
One module requires `Balance: As<usize>` shouldn't affect the shared abstract `Currency::Balance` type otherwise it means the abstraction is not correct.
In this case the Staking module can add additional trait bound and for people are not using Staking module, they don't need to support `Balance: As<usize>` at all.
Another reason I want to do this is because this prevents me to use some fancy type to support multi token currency with the existing `Currency` trait.
I want to use …
> Remove As trait bound from Currency::Balance

- core/sr-api-macros/src/impl_runtime_apis.rs
- core/test-runtime/wasm/Cargo.lock
- node-template/runtime/wasm/Cargo.lock
- node/runtime/wasm/Cargo.lock
`impl_runtime_apis!` is not only implementing the apis, it also calls
them internally and thus generates the warning. So, we just allow
depracted calls in the generated code.
Fixes: https://github.com/paritytech/substrate/issues/2252
> Silence the deprecated warning in generated code

- .gitlab-ci.yml
- Cargo.lock
Part of #2416 
Updates `parity-crypto` and `fixed-hash`. Adds CI tests for the crates that are now compiling successfully.
> Make more crates compile for WASM browser

- core/network/src/test/mod.rs
Spawning a tokio runtime for each peer added on every test that's running concurrently can deplete system resources and have tests fail with: 
`thread '<unnamed>' panicked at 'failed to start new Runtime: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:997:5`
> core: use current_thread tokio runtime to poll network to proto channel

- core/finality-grandpa/src/communication/gossip.rs
No need to acquire the lock in the `None` case, and no need to hold it while decoding the block.
> Don't acquire the lock unless, and only hold it for as long as, necessary

- core/sr-api-macros/src/impl_runtime_apis.rs
- core/test-runtime/wasm/Cargo.lock
- node-template/runtime/wasm/Cargo.lock
- node/runtime/wasm/Cargo.lock
`impl_runtime_apis!` is not only implementing the apis, it also calls
them internally and thus generates the warning. So, we just allow
depracted calls in the generated code.
Backport of: https://github.com/paritytech/substrate/pull/2513
> Backport: Silence the deprecated warning in generated code

- .dockerignore
- Dockerfile
Alpine base images make great docker images because they are very small. Some of the binaries come unfortunately with delay. It happened already several times for the Substrate and Polkadot repos that the cargo version available on alpine was a tad too old and did not allow building substrate/polkadot.
The docker image for polkadot was reverted a while back already.
This PR reverts from `alpine` to using `phusion/base`. I did attempt to keep alpine as second stage which ends up being a little headache. The reason for that is that alpine uses `musl` instead of `glibc`. So the options would be to build using `musl` or install `glibc` in alpine. The second option is not trivial and ideal as the size will grow significantly.
I also tried a second stage using debian:stretch but the …
> Revert from alpine to phusion and include wasm build

- core/network/src/protocol.rs
- core/network/src/service.rs
- core/network/src/sync.rs
- core/network/src/test/mod.rs
- core/network/src/test/sync.rs
Based on top of #2475 
Removes all `Arc`s (explicit or implicit (ie. the one inside of `Box<ImportQueue>`)) from the `sync.rs` module. This makes the code of `sync.rs` deterministic (except for request timeouts).
The only logic that's been removed, which is importing blocks and justifications to the import queue, has been moved to `service.rs`.
> Isolate the code of ChainSync and turn it into a state machine

- core/finality-grandpa/src/communication/gossip.rs
Just realized that after last commit of #2533 messages are still sent under lock, because lock is held for the whole statement execution time.
> Send GRANDPA messages without holding validator lock

- node-template/runtime/src/lib.rs
- node/runtime/src/lib.rs
- srml/council/src/voting.rs
- srml/democracy/src/lib.rs
This PR settles on referenda as the plural of referendum. Supporting [ngram comparison](https://books.google.com/ngrams/graph?content=referendums%2C+referenda&case_insensitive=on&year_start=1800&year_end=2010&corpus=15&smoothing=3&share=&direct_url=t4%3B%2Creferendums%3B%2Cc0%3B%2Cs0%3B%3Breferendums%3B%2Cc0%3B%3BReferendums%3B%2Cc0%3B.t4%3B%2Creferenda%3B%2Cc0%3B%2Cs0%3B%3Breferenda%3B%2Cc0%3B%3BReferenda%3B%2Cc0#t4%3B%2Creferendums%3B%2Cc0%3B%2Cs0%3B%3Breferendums%3B%2Cc0%3B%3BReferendums%3B%2Cc0%3B.t4%3B%2Creferenda%3B%2Cc0%3B%2Cs0%3B%3Breferenda%3B%2Cc0%3B%3BReferenda%3B%2Cc0)
It is a continuation of https://github.com/paritytech/substrate/pull/2457 which I accidentally fubar-ed.
I've updated the version numbers as requested there, but I'm not yet sure how / where to make a release …
> Language adjustment: Referendums -> Referenda

- core/network/src/on_demand.rs
- core/network/src/service.rs
- core/service/src/lib.rs
Replaces the `NetworkChan` with a `OnDemandNetwork` trait. Makes the code more flexible. The ultimate goal is to remove the `NetworkMsg` enum from the API surface of `network`.
cc #2536
> Remove the NetworkChan from the OnDemandService

- core/network/src/protocol.rs
- core/network/src/sync.rs
The `peer_info`, `client` and `send_block_request` methods of the `Context` are only ever used by the sync code.
This PR creates a different trait specific to the sync code, so that we don't expose these methods in the `Context` trait that everyone has access to.
The advantage of doing so is that the remaining methods (`disconnect_peer`, `report_peer`, `send_consensus` and `send_chain_specific`) can all be implemented by sending a message on a channel, therefore removing the need to somehow hold some sort of lock to the `Protocol` struct.
Does break the API of `network`, but doesn't break polkadot expect that we have to remove [these lines](https://github.com/paritytech/polkadot/blob/41f626526854757c219b55c91fa3a5531d761da7/network/src/tests/mod.rs#L48-L50) and [these …
> Split SyncContext from protocol Context

- subkey/README.adoc
- subkey/src/cli.yml
- subkey/src/main.rs
Needed for chaos testnet tooling.
@rphmeier Can you please take a look if this fulfills your requirements? Please note that the returned value atm is an `UncheckedMortalCompactExtrinsic`, not an `UncheckedMortalExtrinsic`.
```
$ cd subkey/
$ cargo run -- sign-transaction \
--call 0300ff408aa36b945720031fbb2e661fc9c9f1ed799be5369f991bbfce02103b5f0e44e514 \
--nonce 0 \
--suri //Alice/// \
--password password \
--prior-block-hash f8349fe94e9fd86e8a85745bbb70a4d2d5f4d8fc32a1f8fc08088faf1840e705
0x250281ffd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d0ecdb36c371c4a5e2d7528e12f68fcc57912df0c80418cca794fd83c24f29825efbaaaa2ae4472726e065f4f1db75ba7c39114e25b58de4dde54d6b51aa3e20500000300ff408aa36b945720031fbb2e661fc9c9f1ed799be5369f991bbfce02103b5f0e44e514
```
> Add possibility to sign calls via cli

- node/runtime/src/lib.rs
- srml/treasury/src/lib.rs
I was looking at Treasury and noticed that if `minted > portion` then this could overflow. Added a few checks.
Related https://github.com/paritytech/substrate/issues/1572
> Fix over/under flow risk in OnDilution

- core/service/src/components.rs
- core/service/src/error.rs
- core/service/src/lib.rs
- node-template/src/service.rs
- node/cli/src/service.rs
Right now light client fails to start because `build_select_chain` returns `Result<SelectChain>`. Since (as I understood from chat), `SelectChain` is not supposed to be used on light client, I'v changed it to `Result<Option<SelectChain>>`. There's still a way (*which isn't guarded by `#deprecated`*) to get best block hash/number by calling `Client::info()` => I've used it to get best-block to use during startup (it is only used in initial telemetry && log related calls).
> Fix light client startup (build_select_chain returns Result<Option>)

- core/network-libp2p/tests/test.rs
I spotted a CI failure caused by the `MAX_BANDWIDTH` being exceeded during this test.
For context, we spawn 25 nodes and wait for them to connect to each other. Then we check that the bandwidth usage doesn't exceed the `MAX_BANDWIDTH` constant.
Paradoxically, this limit could also be reached if our code becomes too efficient.
This constant is arbitrary anyway, so let's make it a bit more tolerant. 2kiB/sec per node is still very low.
> Increase tolerance for bandwidth usage in test

- core/network/src/config.rs
- core/network/src/consensus_gossip.rs
- core/network/src/on_demand.rs
- core/network/src/protocol.rs
- core/network/src/sync.rs
- core/network/src/test/mod.rs
- core/network/src/test/sync.rs
- core/service/src/lib.rs
Changes introduced in this PR:
1) when new **light** peer connects, it is completely ignored by the `network/src/sync.rs`, because we can't benefit from syncing from light client (except if we're also light client ++ we're at the same CHT with the peer, but this is too large restriction => ignore this case);
2) if light client received `BlockRequest` message, the peer is considered bad && disconnected.
> Do not try to synchronize from light client

- node/cli/res/flaming-fir.json
Reflects changes that have been made to the configuration of the bootnodes.
cc'ing @TriplEight @ddorgan 
We added WebSocket addresses for in-browser experiments. Maybe it's a bit early to put that in the chainspecs.
> Add WebSocket addresses for bootnodes

- core/network/src/sync/extra_requests.rs
Fixes
```bash
Checking srml-grandpa v2.0.0 (/home/niklasad1/Github/substrate/srml/grandpa)
warning: the item `HashSet` is imported redundantly
--> core/network/src/sync/extra_requests.rs:307:7
|
17  | use std::collections::{HashMap, HashSet, VecDeque};
|                                 ------- the item `HashSet` is already imported here
...
307 |         use std::collections::HashSet;
|             ^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: #[warn(unused_imports)] on by default
```
> fix(remove redundant import)

- .gitlab-ci.yml
- Check-web-wasm job now uses the default builder image
> Default image to build wasm

- node/runtime/src/lib.rs
- srml/contract/src/lib.rs
increase the block gas limit by 10.
should solve https://github.com/paritytech/substrate/issues/2566
To be honest I still can't reproduce, with master everything works fine to me... so I don't know if it is enough...
Then we might want to backport to v1.0
> increase block gas limit

- core/network-libp2p/src/behaviour.rs
- core/network-libp2p/src/behaviour/debug_info.rs
- core/network-libp2p/src/custom_proto/behaviour.rs
- core/network-libp2p/src/lib.rs
- core/network-libp2p/src/service_task.rs
Continuation of #2374 
Does some rearchitecturing in network-libp2p.
At the moment we keep information about nodes (its version and ping time) when we open a gossiping channel with this node, and destroy these information when we close the channel.
This PR changes this to keep information when we are connected to a node (even if we don't have any gossiping channel), and for 10 minutes after disconnection. Therefore also reports the client version and ping time in the debug JSON for disconnected nodes when possible.
This is done by moving the `Ping` and `Identify` behaviours to a new `DebugInfoBehaviour` that also stores information about nodes.
This is important for #2374, because if we make libp2p generic we won't be able to know when the user-defined protocol opens a channel or not …
> Keep node information about disconnection

- node/cli/res/flaming-fir.json
To avoid clashes with other networks (Emberic Elm and others).
```
2019-05-15 11:52:33 Banning PeerId("QmTtcYKJho9vFmqtMA548QBSmLbmwAkBSiEKK3kWKfb6bJ") because "Peer is on different chain (our genesis: 0x78be?87c7 theirs: 0xe1aa?65e6)"
2019-05-15 11:52:33 Banning a node is a deprecated mechanism that should be removed
2019-05-15 11:52:33 Banning PeerId("QmWv9Ww7znzgLFyCzf21SR6tUKXrmHCZH9KhebeH4gyE9f") because "Peer is on different chain (our genesis: 0x78be?87c7 theirs: 0xe1aa?65e6)"
2019-05-15 11:52:33 Banning a node is a deprecated mechanism that should be removed
2019-05-15 11:52:34 Banning PeerId("QmTtcYKJho9vFmqtMA548QBSmLbmwAkBSiEKK3kWKfb6bJ") because "Peer is on different chain (our genesis: 0x78be?87c7 theirs: 0xe1aa?65e6)"
2019-05-15 11:52:34 Banning a node is a deprecated …
```
> node: set protocol id for flaming fir

- core/telemetry/src/lib.rs
> fix(telemetry): remove needless `Box`

- node/runtime/src/lib.rs
- srml/metadata/src/lib.rs
- srml/support/src/dispatch.rs
Was cleaning Metadata on the JS side, and saw a couple of stuff here that dates back to MetadataV0. Removing them.
> Remove remains from metadata v0

- README.adoc
- node-template/README.md
Relates to https://github.com/paritytech/substrate/pull/2290
> Update libp2p addresses in readme

- core/client/src/light/blockchain.rs
- core/client/src/light/fetcher.rs
- core/network/src/message.rs
- core/network/src/on_demand.rs
- core/network/src/protocol.rs
- core/test-client/src/lib.rs
> feat(light client): fetch block body from remote

- core/consensus/babe/src/lib.rs
- core/finality-grandpa/src/lib.rs
Denying warnings is a bad good-idea. New versions of Rust almost always introduce new warnings, be it deprecated functions or new lints. For example a new version of Rust may decide that it's no longer necessary to explicitly put lifetimes at certain locations, and emit a warning if you do.
It has personally happened to me often enough in the past that I now religiously remove all the `forbid(warnings)` that I stumble upon.
Forbidding warnings also paradoxically leads to silencing warnings, such as with the `allow(deprecated)` that I removed in this PR as well.
> Allow warnings

- core/peerset/src/peersstate.rs
In integration tests we add the same peer as reserved multiple times. That isn't good, but panic is an overreaction in this case, imo.
> Fix panic in PSM when add_reserved_peer(same_peer) is called twice

- node-template/runtime/wasm/build.sh
This enables use of the sandbox needed for running smart contracts on Substrate
See: https://github.com/paritytech/substrate/issues/2570
> Update build script to create a table for the runtime

- srml/support/src/storage/mod.rs
I think these changes are correct, but I'm not entirely sure. Please review.
> docs: Update Support SRML rephrasing EnumerableStorageMap comment in Rustdocs

- core/cli/src/informant.rs
- node-template/src/cli.rs
- node/cli/src/lib.rs
For #2416
Deprecates `informant::start()` and replaces it with `informant::build()`. The user would then be responsible for polling the informant.
Also decreases the API surface. We makes fewer assumptions about how the user wants to use our code, which is always a good thing IMO.
> Remove TaskExecutor from the API of the informant

- core/network-libp2p/src/behaviour.rs
This was apparently ambiguous. "external node address" can be interpreted as "address of external node", while it means "external address of node".
> Make info! string less ambiguous

- srml/support/procedural/src/storage/impls.rs
- srml/support/procedural/src/storage/transformation.rs
- srml/support/src/storage/hashed/generator.rs
- srml/support/src/storage/mod.rs
- srml/support/src/storage/storage_items.rs
- srml/support/src/storage/unhashed/generator.rs
Fix https://github.com/paritytech/substrate/issues/2474
currently in the code base we make use of RefCell to write to genesis storage. This is because we wrote the trait to write on a storage with immutability access to storage.
But the genesis storage can be handled as a mutable storage. instead of wrapped into an unnecessary RefCell.
The RuntimeStorage being an empty struct we can give mutable reference when wanted.
This PR make the add_extra_genesis build function being able to write to storage easily, for instance this PR wouldn't make use of a RefCell https://github.com/paritytech/polkadot/pull/245
breaking change: if other module are making use of refcell then just use the inner type or borrow mutably when necessary.
> get rid of refcell, use &mut storage

- .gitlab-ci.yml
- Cargo.lock
- core/keystore/Cargo.toml
- core/keystore/src/lib.rs
For #2416 
This technically breaks the API by removing the `KEY_ITERATIONS` constant, but this constant is totally unused. Depending on how strict we are on not breaking APIs even when they don't make sense, I can add it back as a `pub const KEY_ITERATIONS: usize = 10240;`.
Adds `substrate-keyring` and `substrate-keystore` to the list of crates that successfully compile for WASM.
> Remove dependency on parity-crypto

- Cargo.lock
Fixes:
ID:      RUSTSEC-2019-0003
Crate:   protobuf
Version: 2.5.0
Date:    2019-06-08
URL:     https://github.com/stepancheg/rust-protobuf/issues/411
Title:   Out of Memory in stream::read_raw_bytes_into()
Solution: upgrade to: ^1.7.5 OR >= 2.6.0
> fix(protobuf vulner): update to 2.6

- core/cli/src/lib.rs
- core/cli/src/params.rs
- core/rpc-servers/src/lib.rs
- core/service/src/components.rs
- core/service/src/config.rs
- core/service/src/lib.rs
- core/service/test/src/lib.rs
Adds `--ws-max-connections` cli option to set the maximum number of WS connections allowed on the RPC server (defaults to 100).
> core: allow setting max ws rpc connections

- core/network/src/config.rs
- core/network/src/lib.rs
- core/network/src/on_demand.rs
- core/network/src/on_demand_layer.rs
- core/network/src/protocol.rs
- core/network/src/service.rs
- core/network/src/test/mod.rs
- core/service/src/lib.rs
The way it works before this PR:
- When constructing a light client, the client itself creates an `Arc<OnDemand>` object containing a `dyn FetchChecker` and returns it.
- We then create the `NetworkService` and pass the `Arc<OnDemand>` to the constructor.
- We then call `OnDemand::set_network_interface` in order to store, in an abstract way, a weak pointer to some struct containing channels. If we forget to do that, everything will panic.
- The client keeps a copy of the `Arc<OnDemand>` and uses it to perform queries. These queries are sent to the network interface through the channels in the weak pointer. The client holds a `future::sync::oneshot::Receiver` for each request performed this way.
- Whenever the network receives a response, it locks a mutex and gives it to the `OnDemand`. …
> Rework the OnDemand service

- core/rpc/src/chain/number.rs
remove unused import.
refactor code that fix building warnings.
> remove unused import

- core/rpc/src/state/tests.rs
I assumed that runtime size will never go down, but it's very wrong.
> Lower the required code threshold.

- core/finality-grandpa/src/communication/mod.rs
- core/finality-grandpa/src/communication/tests.rs
- core/finality-grandpa/src/environment.rs
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/observer.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/consensus_gossip.rs
The grandpa `VoterSetState` is persisted and it contains the votes seen in the latest completed rounds. When a node starts these votes are now registered with the gossip service so that they are available to be broadcast to other peers (e.g. if they send us a neighbor packet and they're on a previous round).
> Register previous rounds' votes with gossip service on startup

- core/network-libp2p/src/service_task.rs
The "not connected peers" are computed by taking all the peers minus the "connected peers".
But I screwed up the filter, so we were actually returning the connected peers.
> Fix not connected peers being connected peers

- core/peerset/src/lib.rs
This is an extremely niche issue, but when playing around with `network-libp2p`, I noticed that if you drop the `PeersetHandle`, the peerset itself would report that it has "ended", which doesn't make sense.
> Peerset should never return Ready(None)

- Cargo.lock
- core/network-libp2p/src/config.rs
- core/network-libp2p/src/service_task.rs
- core/network-libp2p/src/transport.rs
- core/service/test/src/lib.rs
For #2416 
Adds a field to `NetworkConfiguration` that lets you pass an "external transport".
The objective of that is to make it possible to inject some network binding code that calls the browser APIs.
(note: I don't really know who to ask for a review)
> Allow passing an optional transport to network-libp2p

- core/network/src/specialization.rs
It's not called, not used by Polkadot, and doesn't really make sense anyway.
> Deprecate NetworkSpecialization::on_abort

- srml/balances/src/lib.rs
The original wording of docs on `Imbalance` imply that the user needs to do something with the imbalance. The user _can_ manage an `Imbalance` if they want, but the default action for the user is just to do nothing at all since the `Drop` trait will handle updating the total issuance accordingly.
> Update docs on `Imbalance` in the Balances module

- core/client/db/Cargo.toml
- core/client/db/src/lib.rs
- core/client/db/src/light.rs
- core/client/db/src/utils.rs
- core/service/Cargo.toml
For #2416 
Makes RocksDB an optional feature in `substrate-client-db`, but that's always enabled in `substrate-service`.
When the library is compiled without the feature flag, we use `kvdb-memorydb` and a warning is printed.
When the library is compiled with the feature, we use `kvdb-rocksdb`.
This will make `substrate-client-db` successfully compile for WASM-browser once the telemetry has been revamped.
> Make RocksDB optional in client-db

- core/executor/src/native_executor.rs
- srml/support/src/traits.rs
Currently this macro cannot be called as `substrate_executor::native_executor_instance`. It is required to import `native_executor_instance` in scope either with `use substrate_executor::native_executor_instance` or `macro_use` attribute.
> Use $crate inside of native_executor_instance and parameter_types macros

- node/runtime/Cargo.toml
Fixes: https://github.com/paritytech/substrate/issues/2724
> Enable `std` feature for all required crates

- core/rpc/src/author/hash.rs
- core/rpc/src/author/mod.rs
- core/rpc/src/author/tests.rs
- core/transaction-pool/graph/src/pool.rs
Resolves #2604 
I've decided to support both hash and raw representation of the extrinsic because `pending_extrinsics` removes the raw form.
It uses existing `remove_invalid` API, that will temporarily ban the transactions as well and remove all dependent transactions too.
> Add RPC to remove and ban transactions from the pool.

- Cargo.lock
- core/cli/src/lib.rs
- core/cli/src/params.rs
https://github.com/TeXitoi/structopt/pull/190 Introduces handling of `Option<Option<T>>` parameters in `structopt` directly.
We've used the type together with `parse(try_from_str)` which now is broken with that type.
To overcome the issue I've introduced `Cors` enum that we parse the CLI option to first.
> Bump structopt and fix compilation.

- core/network/src/protocol.rs
- core/network/src/sync.rs
- core/network/src/test/mod.rs
- core/network/src/test/sync.rs
Small light-related optimization - instead of requiring `BlockAnnounce` -> `BlockRequest` -> `BlockResponse` messages sequence for import of single announced block, we may simply use header from `BlockAnnounce`. 
On light nodes block import = import of block header + (if available) import of justification. This means that when block is announced, we already have all **minimal-required** data to import announced block. Justification, if required, will be requested separately (as a part of finality proof) and, if not required, iirc we wanted to announce justifications separately (it isn't done yet, right? haven't found any related network messages).
The optimization currently won't work in some cases - like when peer that have announced block is currently occupied with other requests. This …
> Import headers from BlockAnnounce message on light nodes

- README.adoc
Fixes the typo reported in https://github.com/paritytech/substrate/issues/2751
> Typo fix Substate -> Substrate

- node/runtime/src/lib.rs
- srml/aura/src/lib.rs
They did not compile, since `Encode` and `Decode` are deliberately not
implemented for `usize`.
Fixes #2742.
> Remove spurious `#[derive(Encode, Decode)]`

- core/network/src/lib.rs
- core/network/src/protocol.rs
- core/network/src/specialization.rs
- core/network/src/test/mod.rs
The gossiping code no longer has access to `send_chain_specific`, and the chain-specific code no longer has access to `send_consensus`.
> Split specialization context from network context

- node/runtime/src/lib.rs
- srml/support/src/traits.rs
- srml/system/src/lib.rs
This adds support for multiple modules to be specified with the `OnNewAccount` hook in the Balances module like so:
```
type OnNewAccount = ((Module1, Module2), Module3);
```
or
```
type OnNewAccount = (Module1, Module2, Module3);
```
Updates `OnFreeBalanceZero` to use the same `for_each_tuple` macro.
Fixes https://github.com/paritytech/substrate/issues/2763
> Add support for tuples in `OnNewAccount` hook

- core/client/db/src/lib.rs
- core/client/db/src/storage_cache.rs
- core/client/src/call_executor.rs
- core/client/src/cht.rs
- core/client/src/client.rs
- core/client/src/light/backend.rs
- core/client/src/light/call_executor.rs
- core/state-db/src/lib.rs
- core/state-db/src/noncanonical.rs
- core/state-machine/src/backend.rs
- core/state-machine/src/lib.rs
- core/state-machine/src/proving_backend.rs
- core/state-machine/src/trie_backend.rs
Pruning is delayed for states that are still referenced in memory. Also make sure that such states are not discarded when finalizing blocks.
Fixes #2693
> Pin states in memory so that they are not pruned away while still referenced

- srml/treasury/src/lib.rs
This work in progress makes the SRML's Treasury reference documentation conform to the template.
It still needs
* A working example? I'm really struggling on that. I think because all of the dispatchable methods are private.
* ~~Clarity on what the `OnDilution` stuff is about. I'm not yet stuck on this.~~ Done
> WIP: Treasury reference docs

- node/runtime/src/lib.rs
- srml/support/src/traits.rs
- srml/system/src/lib.rs
Backport: https://github.com/paritytech/substrate/pull/2765
Fixes: https://github.com/paritytech/substrate/issues/2763
This adds support for multiple modules to be specified with the `OnNewAccount` hook in the Balances module like so:
```
type OnNewAccount = ((Module1, Module2), Module3);
```
or
```
type OnNewAccount = (Module1, Module2, Module3);
```
Updates `OnFreeBalanceZero` to use the same `for_each_tuple` macro.
> Backport #2765: Add support for tuples in `OnNewAccount` hook

- core/network/src/lib.rs
- core/network/src/protocol.rs
- core/network/src/specialization.rs
- core/network/src/test/mod.rs
- node/cli/src/service.rs
#2745 prevents us from upgrading Polkadot.
I didn't realize that Polkadot was passing the context received through the network specialization to the gossiping code.
> Revert #2745

- core/consensus/aura/src/lib.rs
- core/consensus/babe/src/lib.rs
- core/consensus/slots/src/lib.rs
- node-template/src/service.rs
- node/cli/src/service.rs
- Removes the `on_exit` parameter. The caller is now responsible for doing the `select()`.
- Removes the `on_start` trait method. It didn't really make sense to call `start_slot_worker` with a trait object only for it to call `on_start` immediately after.
- Makes `start_slot_worker` always succeed.
- Removes an `Arc` that has no reason to be an `Arc`.
> Small slots refactor

- core/client/src/client.rs
- core/network/src/protocol.rs
- core/network/src/sync.rs
- core/service/test/src/lib.rs
- node/cli/src/service.rs
closes #2555 (though we might want to add more tests later. but at least this ensures that light client is able to start, connect to other nodes && sync)
> Light client integration tests

- core/network-libp2p/src/behaviour.rs
> Make info! string less ambiguous (#2661)

- core/network-libp2p/src/custom_proto/behaviour.rs
- core/network-libp2p/src/custom_proto/handler.rs
Very small change.
Since libp2p 0.8, the handler knows about the `ConnectedPoint` and can therefore deduce whether we are the dialer or the listener. Therefore we don't need to pass that information in the `Enable` message anymore.
> Don't pass the Endpoint as message

- .gitlab-ci.yml
- Cargo.lock
- core/service/src/lib.rs
- core/telemetry/Cargo.toml
- core/telemetry/src/lib.rs
- core/telemetry/src/worker.rs
- core/telemetry/src/worker/node.rs
- core/test-runtime/wasm/Cargo.lock
- node-template/runtime/wasm/Cargo.lock
- node/runtime/wasm/Cargo.lock
For #2416 and #2536 
Rewrites the telemetry to use libp2p and adds a lot of documentation.
Note that when I say "use libp2p", I mean just the small part of it that allows opening WebSocket connections, not the entire rust-libp2p library.
What this means:
- We're now using a single background task instead of 2 threads.
- One can now pass an external WASM transport. This makes it possible to use the telemetry from within the browser.
- `substrate-telemetry` now compiles for WASM-browser.
- We replace 3 Arcs, 1 mutex and 2 channels with 1 Arc, 1 mutex and 0 channels. Theoretically we could do with just 1 channel (0 Arc 0 mutex), but the work would be quite involved because `slog` doesn't expose a way to clone records (even though `slog_async` clones records internally). I'm going to open an …
> Rewrite telemetry using libp2p

- node/runtime/src/lib.rs
- srml/council/src/seats.rs
- srml/democracy/src/lib.rs
Trivial attempt at https://github.com/paritytech/substrate/issues/2779
`cargo test -p srml-council` and `cargo test -p srml-democracy` both pass.
> Move Council and Democracy logic to block initialization

- srml/contract/COMPLEXITY.md
This PR updates complexity.md in particular:
1. Add a few notes about underlying storage system,
2. Mention explicitly that ext_rent_allowance and ext_get_storage both make a DB read.
As a side note, we are thinking about removing the DB read for ext_rent_allowance by the means of https://github.com/paritytech/substrate/issues/2793.
cc @thiolliere
> srml-contract: update complexity.md

- .gitlab-ci.yml
- Cargo.lock
- core/consensus/aura/Cargo.toml
- core/consensus/aura/src/lib.rs
- core/consensus/babe/Cargo.toml
- core/consensus/babe/src/lib.rs
- core/consensus/slots/Cargo.toml
- core/consensus/slots/src/lib.rs
- core/consensus/slots/src/slots.rs
- core/test-runtime/wasm/Cargo.lock
Makes more crates compile for wasm-browser (#2416)
Removes the deprecated function `start_slot_worker_thread`.
> More crate compiling for WASM-browser

- Cargo.lock
After this PR, one can compile Substrate for Android by disabling RocksDB.
RocksDB can be disabled by removing the feature [here](https://github.com/paritytech/substrate/blob/389d4f93f4cf52cf821403793555b33df11c092f/core/service/Cargo.toml#L26).
> Make it build for Android

- ci/script.sh
- core/executor/wasm/build.sh
- core/test-runtime/wasm/build.sh
- node-template/runtime/wasm/build.sh
- node-template/scripts/build.sh
- node/runtime/wasm/build.sh
- scripts/build.sh
- scripts/update.sh
This PR adds additional passthrough for shell scripts and fixes issues with d6e91c1335 (ping @tomaka ) in order to support command line arguments with spaces in them. Without the extra quotes those would get passed as separate (unquoted) arguments.
> Passthru build.sh/script.sh command line arguments

- Cargo.lock
- core/client/src/runtime_api.rs
- core/consensus/aura/primitives/Cargo.toml
- core/consensus/aura/primitives/src/lib.rs
- core/finality-grandpa/primitives/src/lib.rs
- core/finality-grandpa/src/communication/mod.rs
- core/sr-primitives/src/testing.rs
- core/sr-primitives/src/traits.rs
- node/runtime/src/lib.rs
- node/runtime/wasm/Cargo.lock
- srml/aura/src/lib.rs
- srml/grandpa/src/lib.rs
- srml/grandpa/src/mock.rs
- srml/grandpa/src/tests.rs
- srml/session/src/lib.rs
- srml/staking/src/mock.rs
- srml/staking/src/tests.rs
In some tests there was a delay factor that reduced the session reward by one for each second the block was produced of target. I removed those, but I'm not completely sure if that's ok.
I also moved OpaqueKeys to primitives, due to orphaning rules OpaqueKeys can only be implemented for UintAuthorityId in primitives::testing or session. Moving it altogether to primitives seemed like a good idea.
> Fixes staking tests in gav-new-sessions

- node/runtime/src/lib.rs
- srml/metadata/src/lib.rs
- srml/support/procedural/src/storage/impls.rs
- srml/support/procedural/src/storage/mod.rs
- srml/support/procedural/src/storage/transformation.rs
- srml/support/src/double_map.rs
- srml/support/src/lib.rs
- srml/support/src/metadata.rs
Fix https://github.com/paritytech/substrate/issues/2449
> Make use of StorageHasher and HasherKind

- core/consensus/aura/src/lib.rs
- core/consensus/babe/src/lib.rs
- core/consensus/common/src/lib.rs
- node-template/src/service.rs
- node/cli/src/service.rs
We have this `ExtraVerification` parameter when creating the import queue that is totally unused. It's also unused in Polkadot. Let's remove it.
If this parameter turns out to be needed later, we can always revert this PR.
> Refactoring: Remove ExtraVerification in the import queue

- Cargo.lock
- core/cli/Cargo.toml
- core/cli/src/informant.rs
- core/service/Cargo.toml
- core/service/src/lib.rs
At the moment, it's the CLI that periodically sends information to the telemetry. And it's not just vague information, but the main source of data for the telemetry is being sent here.
If we ever use Substrate from within a browser, or on Android, or as a library, etc. we won't be using `substrate-cli`.
Since it is a crucial part of the having the telemetry work at all, to me it makes more sense to me if it is the `service` that sends this information. I therefore moved this there.
It is however still `substrate-cli` that prints the periodic line on stdout.
After discussing with @maciejhirsz, I've also removed the `"status"` field from `"system.interval"` because it was unused.
> Move the telemetry information to service

- core/service/src/chain_ops.rs
- core/sr-api-macros/benches/bench.rs
- core/telemetry/src/lib.rs
- test-utils/transaction-factory/src/complex_mode.rs
Changes consensus telemetry datapoints to not be send if the default telemetry logging level (`0`) is used, only if explicitly enabled (discussed with @gavofyork).
Fixes the bug from #2859, though the issue should not be closed until it's clear how (or if) we want to prevent this from reoccuring in the future.
Adds better import indication when importing from a file via cli (from #1860).
> Various minor fixes

- node/runtime/src/lib.rs
- srml/balances/src/lib.rs
Currently, calling `set_balance` sudo method in balances module will not alter `TotalIssurance` when the account is above minimal balance. This PR fixes this.
rel #668 in the case that it can cause `TotalIssurance` to go negative.
> Maintain TotalIssurance integrity in case of sudo set_balance

- srml/assets/src/lib.rs
This is a test PR to get an opinion on whether this approach looks good.
For https://github.com/paritytech/substrate/issues/706, some of the overflow issues are just something-will-never-happen-in-next-100-years. For them, we may not need any checked proof or panic situations by code, and can use the plain `+`. However, it is still good to have it written down. So I added an "Assumptions" section in the module docs to document them.
> Add assumptions that must be held in assets module

- core/cli/src/informant.rs
- core/network/src/lib.rs
- core/network/src/service.rs
- core/rpc/Cargo.toml
- core/rpc/src/helpers.rs
- core/rpc/src/system/mod.rs
- core/rpc/src/system/tests.rs
- core/service/src/components.rs
- core/service/src/lib.rs
- core/service/test/src/lib.rs
cc #2536 
I discussed this change with @folsen and @tomusdrw already before opening this.
Instead of passing to the RPC handler an `Arc<NetworkService>` where `NetworkService` contains a `Mutex`, we instead pass a channel sender that the RPC will use to send requests. The service is then responsible for polling RPC requests and answering them.
This will make it possible in the future to, for example, not answer RPC requests if the rest of the service is too busy, or to progressively build the answer to an RPC request without blocking the rest of the system.
By not passing the `NetworkService` to the RPC, we also decouple them a bit more, and avoid poisoning the `NetworkService` if the RPC handler panics.
I also removed the `SyncProvider` trait in the process.
> Handle RPC requests in the substrate-service

- core/client/db/src/utils.rs
- core/rpc/src/author/error.rs
- core/util/fork-tree/src/lib.rs
Fixes  #2885 
Remove call to `description()` , use `format!` including actual error
> Remove uses of Error::description() use Display instead

- Cargo.lock
- core/network/Cargo.toml
- core/network/src/protocol.rs
- core/network/src/protocol/sync.rs
- core/network/src/protocol/sync/extra_requests.rs
Instead it only maintains the invariants and leaves the actual I/O part to the parent module (i.e. `sync`).
Changes in detail:
1. Removed `ExtraRequestsEssence` trait and `ExtraRequestsAggregator`
- Instead `ChainSync` has `ExtraRequests` values for justifications and finality proofs which makes it aware of the context for the additional requests so it can construct and send the actual request values.
2. Replaced `ExtraRequests::dispatch` with a `Matcher` object
- The dispatch method was sending out requests directly. Instead the `Matcher` merely matches requests to available peers and performs no I/O on its own.
3. Added a couple of property tests
> Change `network::sync::extra_requests` to not send.

- core/network/src/custom_proto/handler.rs
- core/network/src/custom_proto/mod.rs
- core/network/src/custom_proto/tests.rs
- core/network/src/custom_proto/upgrade.rs
- core/network/src/service.rs
The next refactoring step I'd like to make is remove `start_service` and shuffle things a bit around.
Unfortunately the current libp2p tests use `start_service` (as it was the main entry point in `network-libp2p`).
This PR moves the libp2p tests in the `custom_protos` module where they are more appropriate.
> Move libp2p tests to custom_proto

- .gitlab-ci.yml
publish rustdocs to gh repo substrate-developer-hub/rustdocs
remove docs on s3
> Ci publish rustdocs GitHub

- .gitlab-ci.yml
publish rustdocs on github repo substrate-developer-hub/rustdocs
> ci: publish rustdocs to github repo substrate-developer-hub/rustdocs

- .gitlab-ci.yml
publish rustdocs on github.com/substrate-developer-hub/rustdocs and remove s3 publishing
> ci: publish rustdocs to github repo substrate-developer-hub/rustdocs ii

- node/runtime/src/lib.rs
- srml/support/src/runtime.rs
Fix https://github.com/paritytech/substrate/issues/2892
Old behavior only allowed default with additional elements, now no `{}` expands to `{default}` which himself expands to `{Module, ...,}`.
Only fully expanded `{}` is parsed
> Fix construct_runtime default expansion

- core/network/src/custom_proto/tests.rs
Right now two of the networking tests sometimes fail on CI.
I can't manage to reproduce the failure on my local machine, so this PR is very speculative.
What I think happens is that the two simulated nodes connect to each other simultaneously, which causes one of the connections to be closed. But since for test purposes we're using the `MemoryTransport`, which instantly delivers messages, the closed connection had already managed to negotiate the Substrate substream, which then causes the substream to be closed (only for it to be reopened immediately after on the other connection).
This is all normal and expected behaviour. However, the network tests are simplistic and don't handle the substream being closed. Handling that properly would complicate the code of the tests a lot.
What this …
> Try fix the failing networking tests

- core/client/src/client.rs
- core/rpc/src/state/mod.rs
- core/rpc/src/state/tests.rs
- core/test-runtime/client/src/block_builder_ext.rs
- core/test-runtime/src/lib.rs
- core/test-runtime/src/system.rs
closes #2826 
The first problem occurs when CT are disabled. The result of `state_queryStorage` includes entries for every block in the range, even though changes are empty:
```json
{"jsonrpc":"2.0","result":[{"block":"0x610c","changes":[["0x05","0x05"],["0x0a","0x0a"]]}, {"block":"0x81..8d","changes":[]}],"id":1}
```
I've added a check for that && now entry is only included when `changes` field is not empty.
The second problem is linked to CT + fake changes (see #2865 ). When there's fake change, it is shown in `changes` => redundant entry appears.
```json
{"jsonrpc":"2.0","result":[{"block":"0x61..0c","changes":[["0x05","0x05"]]}, {"block":"0x81..8d","changes":[["0x05","0x05"]]}],"id":1}
```
I've fixed that by adding a check that `prev_value != new_value`.
```json …
```
> Do not return empty entries from state_queryStorage

- core/service/src/lib.rs
It was previously inside of an `Option` so that we can shut it down in the `Drop` implementation.
The logic of the network is now in the `NetworkWorker`, which is shut down with the `on_exit`.
It therefore doesn't make sense anymore to have the `NetworkService` in an `Option`.
> The network is no longer an Option

- node/executor/src/lib.rs
- node/runtime/src/lib.rs
- srml/contracts/COMPLEXITY.md
- srml/contracts/src/tests.rs
- srml/contracts/src/wasm/mod.rs
- srml/contracts/src/wasm/runtime.rs
Closes #2829
This PR removes the input buffer and at the start of execution fills the scratch buffer with the input data (as disccused in #2829).
Please note that now we are copying the `input_data` whereas it seems it shouldn't be necessary. This is planned to be addressed in a follow-up refactoring PR.
> Ditch the input buffer

- node/runtime/src/lib.rs
- srml/contracts/src/wasm/runtime.rs
Minor memory optimization in the wasm runtime. Instead of allocating a new byte buffer from the heap on each write to scratch, reuse existing buffer.
> srml-contract: Use encode_to rather than encode to reduce allocations.

- Cargo.lock
- core/cli/src/informant.rs
- core/network/src/lib.rs
- core/network/src/protocol.rs
- core/network/src/protocol/sync.rs
- core/network/src/service.rs
- core/network/src/test/mod.rs
- core/network/src/test/sync.rs
- core/service/Cargo.toml
- core/service/src/lib.rs
At the moment, you can can register a sender to the network, and it then periodically (every 5 seconds) reports its status to these senders.
This mechanism should be orthogonal to the networking, and I therefore moved it to the `Service`.
I think that the long term vision is that the informant itself should decide of the frequency of the report, and query the service for the information.
In details, the future in substrate-service that polls the network now also polls an interval, retrieves the information from the `NetworkWorker`, and sends it out.
As a general additional cleanup, I also moved the average bandwidth reporting to that struct, and removed the `ProtocolStatus`.
> Move the network status reporting to the service

- .gitlab-ci.yml
Backporting: https://github.com/paritytech/substrate/commit/6ea53d8614e7dd46f21d912bbcb2b8b1555df636#diff-96edf7a6f008de9e928d04e1ae5e12a5
Noticed that the v1.0 docs were still missing some crates, and here is the reason why.
> Backport 2773: Generate docs for all workspace crates

- core/finality-grandpa/src/communication/mod.rs
- core/network/src/lib.rs
- core/network/src/protocol_behaviour.rs
- core/network/src/service.rs
- core/service/src/components.rs
- core/service/src/lib.rs
The next step in the refactoring is to implement the libp2p `NetworkBehaviour` trait on `Protocol`. This was done by adding a `ProtocolBehaviour` struct.
In other words:
Before: `CustomProto <-> Service <-> Protocol`.
After: `Service <-> (CustomProto <-> Protocol)`, and the thing in parentheses is `ProtocolBehaviour`.
This made it possible to move `start_service` in the constructor of `NetworkWorker`, which I did as well.
This unlocks the next step, which is to split `Protocol` in multiple `NetworkBehaviour`s.
Because #2500 was "rejected", I've had to use some hacks for granting access to the gossiping and specialization. It is unclear how I will clean that up, but I'll try to find a solution.
> Add ProtocolBehaviour

- srml/contracts/src/lib.rs
- srml/contracts/src/tests.rs
Closes #2900.
This test confirms that it was not a bug in the first place. If the execution traps, then `call` will return here: https://github.com/paritytech/substrate/blob/0ead54732eb44083660aee1778a01adc5173dfb3/srml/contracts/src/exec.rs#L361-L369 and the dispatched calls will not be added to the top level context (and thus not dispatched).
For extra safety we *could* add add an `if let Ok(_) = result` around this block https://github.com/paritytech/substrate/blob/0ead54732eb44083660aee1778a01adc5173dfb3/srml/contracts/src/lib.rs#L435-L438 to make it clearer/safer.
> srml-contract: test calls not dispatched if tx fails

- node/runtime/src/lib.rs
- srml/contracts/src/gas.rs
- srml/contracts/src/tests.rs
At the moment, there is this piece of code
https://github.com/paritytech/substrate/blob/1c2eaa3bc6a5659fb70cfcc88037573921612064/srml/contracts/src/gas.rs#L128-L132
If you take a look at it, it feels weird. And it just doesn't allow spending the last unit of gas. However, the way it's written implied that it is for purpose there. @jimpo [raised a question](https://github.com/paritytech/substrate/pull/2924#discussion_r296813273) whether we actually need this. I was unable to find any evidence that it is actually used.
So what we did here is added some tests. Initially we thought that we would need to add some balancing mechanism to ensure that new tests work, but it turns out that it is not necessary.
cc @jimpo
> Allow spending all available gas.

- core/network/src/lib.rs
- core/service/src/config.rs
- core/service/src/lib.rs
- core/service/test/src/lib.rs
For #2416 
I've recently added the possibility to have an external transport for the telemetry, but it wasn't accessible through the configuration. This is now done.
> Expose the telemetry external transport in the config

- Cargo.lock
- node/cli/Cargo.toml
- node/cli/src/chain_spec.rs
- node/runtime/src/lib.rs
- srml/contracts/src/exec.rs
- srml/contracts/src/gas.rs
- srml/contracts/src/lib.rs
- srml/contracts/src/tests.rs
- srml/contracts/src/wasm/code_cache.rs
- srml/contracts/src/wasm/env_def/macros.rs
- srml/contracts/src/wasm/mod.rs
- srml/contracts/src/wasm/prepare.rs
- srml/contracts/src/wasm/runtime.rs
Second attempt at fixing #2630.
Gas units are generic in the contract module configuration and the size may exceed that of u64. In order to facilitate potentially moving more gas metering operations into the contract runtime, we make Gas an unconfigurable type fixed as u64, which should be more than enough precision for any use case with little performance hit vs a smaller type on common architectures.
@pepyakin
> srml-contract: Fix Gas type to u64

- .gitlab-ci.yml
- Cargo.lock
- core/cli/src/lib.rs
- core/consensus/common/src/import_queue.rs
- core/finality-grandpa/Cargo.toml
- core/finality-grandpa/src/communication/mod.rs
- core/finality-grandpa/src/communication/periodic.rs
- core/finality-grandpa/src/environment.rs
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/until_imported.rs
- core/offchain/Cargo.toml
- core/offchain/src/lib.rs
- core/rpc/Cargo.toml
- core/rpc/src/author/tests.rs
- core/rpc/src/chain/tests.rs
- core/rpc/src/state/tests.rs
- core/rpc/src/subscriptions.rs
- core/service/Cargo.toml
- core/service/src/chain_ops.rs
- core/service/src/components.rs
- core/service/src/lib.rs
- core/service/test/src/lib.rs
- node-template/src/cli.rs
- node-template/src/service.rs
- node/cli/src/chain_spec.rs
- node/cli/src/lib.rs
- node/cli/src/service.rs
Lots of small changes for #2416 :
- The RPC service now accepts an `Arc<dyn futures::future::Executor<Box<dyn Future>>>` instead of `tokio::runtime::TaskExecutor`, which makes it possible to not depend on tokio anymore.
- The import queue now manually polls the worker if we fail to spawn a future.
- The `Service` itself now works like the import queue: it must be polled, and polling attempts to spawn background tasks. If spawning a task fails, we poll it manually.
- Removes the `TaskExecutor` and `on_exit` from `TelemetryOnConnect`. Grandpa now spawns telemetry futures on the main executor.
- **Biggest breaking change**. Removes the `executor` parameter from various service constructors and components. You can use `service.spawn_task` instead of spawning a task using the executor.
- …
> Remove tokio dependencies

- node/runtime/src/lib.rs
- srml/contracts/src/gas.rs
- srml/contracts/src/rent.rs
- srml/contracts/src/tests.rs
- srml/contracts/src/wasm/mod.rs
- srml/contracts/src/wasm/prepare.rs
- srml/contracts/src/wasm/runtime.rs
This PR bundles up a few different cleanups and one bug fix for the contract module so that I only need to bump impl_version once. They are split up by commit, though I'm also happy to split into multiple PRs if people prefer.
The biggest change is to fix a bug with over-deductions on rent payments in the `srml-contract: Add tests and comments for bugs in rent payment logic.` and `srml-contract: Refactor try_evict_or_and_pay_rent to make tests pass.` commits. This refactor, however, changes the behavior in the case that the account has locks on the balance (in the Balances module). Previously, the rent payment logic used `make_free_balance_be` to bypass the locks, whereas in the refactored version it doesn't. This definitely needs some discussion on whether the locks should be respected …
> srml-contract: Contract refactors

- srml/balances/src/lib.rs
modify `T::Balance` to `Self::Balance`  in `srml-balances` mod to fit `srml_support::Currency` trait, which would eliminate error hints.
> fix typo in balances module

- Cargo.lock
- core/service/Cargo.toml
- core/service/src/lib.rs
For #2416.
Sysinfo 0.9 now "supports" WASM by returning an error when you call `get_current_pid`. Sysinfo 0.8 doesn't even compile.
> Update sysinfo to 0.9

- core/sr-std/src/lib.rs
This macro compiles and executes the given code only when `std` feature
is enabled. This can be useful for debugging without needing to worry
that your code does not compile on `no_std`.
> Adds `if_std!` macro

- core/client/db/src/cache/list_cache.rs
- core/client/db/src/cache/list_entry.rs
- core/client/db/src/cache/mod.rs
Initial idea was that `None` has a meaning of "value unknown at this block". So if we've failed to get value from the cache => usual mechanism should have been used (like remote call of `authorities()`). But actually authorities are always available when block is imported on light. So now cache is used more as a storage than a cache. And the original behavior (if required) could be achieved externally by declaring `ListCache<Option<T>>` instead of `ListCache<T>`.
I'm planning to use this cache for storing changeable `ChangesTrieConfiguration` both on full and light nodes => it will not only be used for storing values, but also for querying blocks where value has been changed. That's why we should get rid (in general) of treating `None` as a "value unknown at this block".
> Change meaning of None in blockchain cache

- core/test-runtime/wasm/Cargo.lock
- node-template/runtime/wasm/Cargo.lock
- node/runtime/wasm/Cargo.lock
- test-utils/chain-spec-builder/Cargo.lock
Fixes  https://github.com/servo/rust-smallvec/issues/148
> bump `smallvec 0.6.10` to fix vulnerability

- core/sr-std/without_std.rs
fix typo
- In particular, mind the maximal line length.
Thank you!
> typo fix in without_std.rs

- node/runtime/src/lib.rs
This has been the source of some confusion and silly comments/debates on PRs.
> Document convention for updating node runtime version.

- .gitlab-ci.yml
add a step to the ci that tests staking in srml
Related #2882
> ci: add job to test staking in srml

- srml/council/src/lib.rs
- srml/council/src/motions.rs
- srml/council/src/seats.rs
- srml/council/src/voting.rs
Supersedes https://github.com/paritytech/substrate/pull/2281
I removed the list of functions in 572c1c4 because it is massive and I think it will be hard to remain. Open to revert if people want it in.
> Council Module Documentation

- core/service/src/lib.rs
Let's implement `Executor` instead of having an inherent method on `SpawnHandle`.
Necessary to upgrade Polkadot, so it would be great to merge this quickly-ish.
> Implement Executor for Service and SpawnHandle

- node/runtime/src/lib.rs
- srml/contracts/src/exec.rs
- srml/contracts/src/rent.rs
- srml/contracts/src/tests.rs
Previously, the calls would transfer funds and succeed without executing any code on the target account, which is unintuitive behavior.
There is also a bit of refactoring to reduce unnecessary storage lookups when constructing `ExecutionContext`s. 
@pepyakin
> srml-contract: Fail calls to removed contracts instead of succeeding.

- Cargo.lock
- core/client/Cargo.toml
- core/client/db/Cargo.toml
- core/primitives/Cargo.toml
- core/sr-io/Cargo.toml
- core/state-machine/Cargo.toml
- core/test-client/Cargo.toml
- core/test-runtime/Cargo.toml
- core/trie/Cargo.toml
- node-template/Cargo.toml
- node/executor/Cargo.toml
- node/runtime/src/lib.rs
This PR update trie dependencies. Trie crate update include update of parity-util-mem to version 0.2.0 which do not include anymore a problematic dependency to clear_on_drop (clear_on_drop remains used by dalek crate and schnorkel but it is probably correctly managed for no_std).
I added patch version to all trie dependency so it becomes easier to sed update next time.
> Update trie dependencies.

- Dockerfile
`./scripts/build.sh` was removed in #2868.
> scripts: fix Dockerfile

- core/consensus/common/src/block_import.rs
- core/consensus/common/src/import_queue.rs
- core/finality-grandpa/src/import.rs
- core/finality-grandpa/src/light_import.rs
Some basic refactoring.
Instead of giving `on_start` full access to the import queue link, we make it have a more precise behaviour.
The objective of that is to allow some more refactoring of the import queue.
> on_start now returns the precise elements to request

- core/finality-grandpa/src/communication/mod.rs
- core/finality-grandpa/src/observer.rs
Since the observer isn't using `round_communication` we weren't noting any round updates with the `GossipValidator`, therefore we would ignore all round messages. We want all full nodes to contribute to round messages availability. The observer now calls `note_round` after successfully importing a commit for round R.
> grandpa: make observer relay round messages

- Cargo.lock
- core/primitives/Cargo.toml
- subkey/Cargo.toml
cc #2416 
It happens to support no_std environments as well.
> Use bip39 from crates.io

- Cargo.lock
- core/executor/runtime-test/build.rs
- core/test-runtime/build.rs
- core/utils/wasm-builder/Cargo.toml
- core/utils/wasm-builder/src/lib.rs
- core/utils/wasm-builder/src/prerequisites.rs
- node-template/runtime/build.rs
- node/runtime/build.rs
Using `compile_error!` was a stupid idea by me, as rust would not re-execute the build.rs.
> End build when `wasm-builder` does not find a prerequisite

- core/finality-grandpa/src/lib.rs
Reference `run_grandpa_voter` instead of deprecated function `run_grandpa` in `substrate_finality_grandpa` crate docs.
> core/finality: Ref `run_grandpa_voter` instead of deprecated func in doc

- README.adoc
Block period was renamed to minimum period in https://github.com/paritytech/substrate/pull/2132. This commit updates the
README accordingly.
Relates to https://github.com/paritytech/substrate/pull/2132.
> README: Replace outdated `period` with `minimumPeriod`

- core/network/src/protocol.rs
- core/network/src/protocol/specialization.rs
- core/network/src/test/mod.rs
`Message` is an enum that contains all the possible network messages.
Right now the `NetworkSpecialization` receives only the `ChainSpecific` variants (and `RemoteReadChildRequest` variants, but that's a mistake) but wrapped inside of this `Message` enum.
This PR breaks the API but doesn't wrap the message inside of `Message` anymore.
Here's the Polkadot patch to apply:
```patch
diff --git a/network/src/lib.rs b/network/src/lib.rs
index 379f9dbc..e16409f1 100644
--- a/network/src/lib.rs
+++ b/network/src/lib.rs
@@ -573,24 +573,18 @@ impl Specialization<Block> for PolkadotProtocol {
&mut self,
ctx: &mut dyn Context<Block>,
who: PeerId,
-		message: &mut Option<message::Message<Block>>
+		message: Vec<u8>,
) {
-		match message.take() {
-			Some(generic_message::Message::ChainSpecific(raw)) …
```
> Specialization::on_message now takes Vec<u8>

- srml/democracy/src/lib.rs
- srml/democracy/src/vote_threshold.rs
Relates to https://github.com/paritytech/substrate-developer-hub/issues/28
Requires update for consistency with https://github.com/paritytech/substrate/pull/2172
> Documentation for the Democracy Module

- core/network/src/protocol/sync.rs
Instead of logging the fact that a generic invalid block announcement is
ignored, log that the given block is the genesis block.
This warning log line confused me while debugging a different issue.
Let me know if this makes sense.
> core/network: Log when ignoring genesis block announcement

- scripts/sentry-node/docker-compose.yml
Follow up to https://github.com/paritytech/substrate/pull/3018#discussion_r301662567.
Ensure all nodes in the sentry setup run in release mode. In addition
configure sentry-a as a reserved node for validator-a.
> scripts/sentry-node: Ensure release mode and reserved connection for A

- core/network/src/protocol.rs
Genesis block announcements are ignored (https://github.com/paritytech/substrate/blob/master/core/network/src/protocol/sync.rs#L799) therefore we shouldn't be sending them. I think this happens when starting an empty chain since on the first round of GRANDPA voters will be voting for genesis (and announce the block they voted on).
> network: don't announce genesis block

- core/consensus/aura/src/lib.rs
- core/consensus/babe/src/lib.rs
- core/consensus/common/src/block_import.rs
- core/consensus/common/src/import_queue.rs
- core/consensus/common/src/import_queue/basic_queue.rs
- core/consensus/common/src/import_queue/buffered_link.rs
- core/consensus/common/src/lib.rs
- core/finality-grandpa/src/light_import.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/config.rs
- core/network/src/protocol.rs
- core/network/src/protocol/sync.rs
- core/network/src/service.rs
- core/network/src/test/block_import.rs
- core/network/src/test/mod.rs
- core/service/src/chain_ops.rs
- core/service/src/components.rs
- core/service/src/lib.rs
- node-template/src/service.rs
- node/cli/src/service.rs
Fix #2857 
We build a "finality proof request builder" when creating the service.
Before this PR, this FPRB is passed to the import queue. This import queue then calls `set_finality_proof_request_builder()` in order to pass that FPRB to the network. The network then stores that into the `sync` protocol.
After this PR, we directly pass the FPRB to the network as parameter when constructing it.
I also moved the `FinalityProofRequestBuilder` and `BoxFinalityProofRequestBuilder` items to the network configuration, where it is now more appropriate.
Polkadot patch:
```patch
diff --git a/service/src/lib.rs b/service/src/lib.rs
index 2501e633..fe205a42 100644
--- a/service/src/lib.rs
+++ b/service/src/lib.rs
@@ -329,7 +329,6 @@ service::construct_service_factory! {
block_import, …
```
> Remove set_finality_proof_request_builder

- node/cli/src/chain_spec.rs
In #2970 the session module was changed to operate on stash accounts, but when defining the session config in chain spec we were passing the controller accounts instead. At the end of the era we would try to fetch session keys using the wrong account ids.
Fix #3064.
> node: pass stash accounts to session module config

- core/cli/src/lib.rs
- core/cli/src/params.rs
`--execution-all` sets the execution strategies for all available
execution contexts.
Fixes: https://github.com/paritytech/substrate/issues/2636
> Cleanup CLI and introduce `execution-all`

- Cargo.lock
- core/cli/Cargo.toml
- core/cli/src/informant.rs
- core/client/Cargo.toml
- core/client/src/client.rs
- core/client/src/lib.rs
- core/client/src/light/backend.rs
- core/client/src/light/blockchain.rs
- core/client/src/light/call_executor.rs
- core/client/src/light/fetcher.rs
- core/client/src/notifications.rs
- core/consensus/aura/Cargo.toml
- core/consensus/aura/src/lib.rs
- core/consensus/babe/Cargo.toml
- core/consensus/babe/src/lib.rs
- core/finality-grandpa/Cargo.toml
- core/finality-grandpa/src/tests.rs
- core/finality-grandpa/src/until_imported.rs
- core/network/Cargo.toml
- core/network/src/on_demand_layer.rs
- core/network/src/test/mod.rs
- core/rpc/Cargo.toml
- core/rpc/src/chain/mod.rs
- core/rpc/src/state/mod.rs
- core/service/Cargo.toml
- core/service/src/lib.rs
- core/test-client/Cargo.toml
- core/test-client/src/lib.rs
cc #3099 
Switches `substrate-client` to new futures. The two changes are the notification channels and the fetcher.
> Switch the client to new futures

- Cargo.lock
- core/service/Cargo.toml
- core/service/src/lib.rs
- core/telemetry/Cargo.toml
- core/telemetry/src/lib.rs
- core/telemetry/src/worker.rs
- core/telemetry/src/worker/node.rs
cc #3099 
The majority of the switch to new futures is straight-forward, but for the telemetry it is pretty much not straight-forward.
Since libp2p is using futures v0.1, and the telemetry has a wrapper that guarantees that one telemetry write equals one WebSocket frame, we need to have a compatibility shim.
After this PR, the API of `substrate-telemetry` uses new futures.
> Switch the telemetry to new futures

- node-template/runtime/src/lib.rs
- node-template/src/chain_spec.rs
- node/cli/src/chain_spec.rs
- node/cli/src/factory_impl.rs
- node/executor/src/lib.rs
- node/runtime/src/lib.rs
- srml/aura/src/lib.rs
- srml/aura/src/mock.rs
- srml/babe/src/lib.rs
- srml/contracts/src/tests.rs
- srml/session/src/historical.rs
- srml/session/src/lib.rs
- srml/session/src/mock.rs
- srml/staking/src/mock.rs
- srml/timestamp/src/lib.rs
There was no need to keep minimum block time as a storage item. This just switches it to a static Getter.
>  Convert unnecessary storage item to static.

- .gitlab-ci.yml
Logs for `test-linux-stable-int` CI job are too massive (161 Mb now). 
Now they are saved to the job artifacts only in case of failure. 
The failure is also listed to the CI's UI after the job is finished.
An example of the failed job: https://gitlab.parity.io/parity/substrate/-/jobs/183680
> Logs will be saved to the job artifacts only in case of failure.

- node/cli/src/service.rs
The chain spec used for the integration tests used to have a 4 second block time which was changed in #3093. In the integration tests we generate blocks manually which means that the timestamp we set on the block must be consistent with the slot duration of the block proposal mechanism. The tests were failing because the seal (i.e. slot number) and timestamp were not consistent with each other.
> node: fix hardcoded block time in integration tests

- core/network/src/service.rs
Make `NetworkService.{get,put}_value` only take a self reference instead
of a mutable self reference. When retrieving `NetworkService` via
`NetworkWorker` one only gets an immutable reference.
> core/network: Remove self mutability on put and get value

- core/client/db/src/lib.rs
- core/client/db/src/light.rs
- core/client/src/client.rs
When we finalize a block on a divergent branch from the currently tracked best we need to figure out what the new best block is on the finalized branch and we need to re-org to it. This is done by having `finalize_block` optionally take a `SelectChain` which is the pluggable logic for best fork selection (currently only longest chain is implemented). If no `SelectChain` is provided and the finalized block is on a divergent branch then we set the finalized block as best (this is the case for the light client since it doesn't track leaves). When importing a block that is finalized the same thing can happen but in this case we don't need `SelectChain` since the given block that's being imported must be the new best.
I also renamed the `finality_target` in `SelectChain` since there's nothing …
> client: Reorg to new best when finalizing divergent branch

- node/runtime/src/lib.rs
- srml/contracts/src/exec.rs
- srml/contracts/src/lib.rs
- srml/contracts/src/tests.rs
- srml/contracts/src/wasm/mod.rs
- srml/contracts/src/wasm/runtime.rs
Limits contract storage values to 16 KiB. Based on analysis [here](https://github.com/paritytech/substrate/issues/2966#issuecomment-510087309), this is a threshold where reads/writes to/from LevelDB are minimally impacted by the size of the value stored. Above this threshold, the IO required to read/write the value begins to have a noticeable impact.
Fixes #2192.
> Contract storage limit

- core/client/db/src/storage_cache.rs
- core/consensus/aura/src/lib.rs
- core/consensus/babe/src/lib.rs
- core/consensus/common/src/lib.rs
- core/consensus/rhd/src/lib.rs
- core/consensus/slots/src/lib.rs
- core/network/src/protocol/sync.rs
Addresses my review on #3105 and renames `Block` to `BlockT` everywhere.
Doesn't break any API, since this is just about renaming an import.
> Consistency with the Block trait name

- .gitlab-ci.yml
These tests are fully deterministic. Let's forbid merging PRs if they don't pass.
> Don't allow failure for more CI stages

- node/runtime/src/lib.rs
- srml/contracts/COMPLEXITY.md
- srml/contracts/src/exec.rs
Tiny optimization in contract execution noticed during review of #3114 
See https://github.com/paritytech/substrate/pull/3114#discussion_r303402045
> srml-contracts: Avoid unnecessary lookups during call context initialization

- Cargo.lock
- core/client/Cargo.toml
- srml/babe/Cargo.toml
further shuts down the already closed https://github.com/paritytech/substrate/issues/3134.
old versions hex-literal broke with a recent nightly version. They tend to not break on `hex-literal : 0.2`
> Update hex-literal dependency version.

- node/runtime/src/lib.rs
- srml/README.adoc
- srml/staking/src/lib.rs
We might as well move the relevant part of [the high-level Substrate Runtime docs](https://substrate.dev/docs/en/runtime/substrate-runtime-module-library) to the [SRML readme](https://github.com/paritytech/substrate/blob/master/srml/README.adoc). cc @shawntabrizi 
Also, I noticed that the `srml/staking/lib.rs` requires a `SessionInterface` because it claims that `Staking` sets the `ValidatorId` of the `session::Trait`. `Staking` seems to set the `ValidatorIdOf` for `session::Trait` in [`node/runtime`](https://github.com/paritytech/substrate/blob/cf98501f92a98ab7133829a746128be98aea0117/node/runtime/src/lib.rs#L218);`ValidatorId = AccountId` in `node/runtime`. I changed a comment in `staking` to reflect this, but, if there is something I'm missing here, this change can easily be reverted.
> docs: add srml readme, clarify comment in staking

- core/client/src/client.rs
- core/consensus/aura/src/lib.rs
- core/consensus/babe/src/lib.rs
- core/consensus/common/src/block_import.rs
- core/consensus/common/src/import_queue.rs
- core/consensus/common/src/lib.rs
- core/consensus/rhd/src/lib.rs
- core/finality-grandpa/src/import.rs
- core/finality-grandpa/src/light_import.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/test/mod.rs
- core/service/src/lib.rs
- core/service/test/src/lib.rs
- core/test-client/src/client_ext.rs
- node/cli/src/service.rs
- test-utils/transaction-factory/src/lib.rs
We've got three items whose names are quite similar: `BlockImport`, `ImportBlock`, and `IncomingBlock`. This can be confusing.
For clarity, let's rename `ImportBlock` to `BlockImportParams`. This makes it obvious that it's just something you pass to `BlockImport`.
The usage of this struct is spread everywhere, therefore it's better if I do it in a single PR than if this change is hidden in the middle of a larger PR.
> Rename ImportBlock to BlockImportParams

- core/client/db/src/offchain.rs
- core/executor/src/wasm_executor.rs
- core/offchain/src/api.rs
- core/offchain/src/lib.rs
- core/offchain/src/testing.rs
- core/primitives/src/crypto.rs
- core/primitives/src/offchain.rs
- core/service/src/components.rs
- core/service/src/lib.rs
- core/sr-io/src/lib.rs
- core/sr-io/with_std.rs
- core/sr-io/without_std.rs
- core/state-machine/src/lib.rs
- node-template/src/service.rs
- node/cli/src/service.rs
- node/runtime/src/lib.rs
- srml/im-online/src/lib.rs
Required for #3034 Closes #3150 
cc @gavofyork @tomusdrw @cmichi
> Refactors the offchain worker api

- srml/elections/src/lib.rs
Closes: https://github.com/paritytech/substrate/issues/3167
> Export `VOTER_SET_SIZE` and `APPROVAL_SET_SIZE` in srml elections

- core/network/src/discovery.rs
I accidentally broke it in #3116 
It could on principle be a good idea to write a test for mDNS, but the test unfortunately can't be isolated from the network, so I don't think it's a good idea in practice.
cc @andresilva
> Fix mDNS not working

- core/network/src/custom_proto/behaviour.rs
- core/peerset/src/lib.rs
Right now we have a lot of network activity, and most of it is caused by trying to connect to "bad" nodes (nodes from a different chain, or IPFS nodes for example).
A "severe protocol error" happens when we detect a "bad" node. This PR makes it so that severe protocol errors now decrease the node's reputation by 2^31, hence lowering the chances we try this node again in the short term.
> Report to the PSM when a severe protocol error happens

- srml/support/src/lib.rs
I missed this while making parameter types more flexible.
> Make function `get` of parameter types public

- Cargo.lock
- node/runtime/src/lib.rs
- srml/metadata/src/lib.rs
- srml/support/procedural/src/storage/transformation.rs
- srml/support/procedural/tools/src/lib.rs
- srml/support/src/lib.rs
- srml/support/src/metadata.rs
- srml/support/src/runtime.rs
- srml/support/src/storage/storage_items.rs
- srml/support/test/Cargo.toml
- srml/support/test/tests/instance.rs
- Introduces metadata v7
- If a module is using instancing, the storage exposes the instance in
metadata
- Metadata module name is now the upper case one given to
`construct_runtime!`
> Expose instancing in metadata

- core/utils/wasm-builder/src/lib.rs
- core/utils/wasm-builder/src/prerequisites.rs
- core/utils/wasm-builder/src/wasm_project.rs
I [added](https://github.com/paritytech/ink/pull/124) a dev-dependency on substrate from `ink!`, and the build failed with https://github.com/paritytech/substrate/blob/33609c707a3bf7b1a520d639b7b1199dc77c0cff/core/utils/wasm-builder/src/prerequisites.rs#L40
It's because ink has the `rust-toolchain` file https://github.com/paritytech/ink/blob/master/rust-toolchain, which means that the vanilla `cargo` defaults to that version. It's a fixed version of nightly, and the wasm toolchain is installed for that version and not the latest nightly.
This PR fixes `get_nightly_cargo` to return the default `cargo` command if it is a nightly version.
> wasm-builder: allow default cargo nightly

- core/cli/src/informant.rs
- core/cli/src/informant/display.rs
Fix #2652 
Splits the informant in two files, one that does the `Future` stuff and one that only does the displaying.
Also fixes #2652 by trying `try_into::<u128>` and falling back to pure-integer mathematics if it fails.
For what it's worth, I locally tested the pure-integer code path, and it doesn't seem to cause any abnormal CPU usage, even in debug.
> Informant cleanup

- core/network/src/protocol/on_demand.rs
I've seen failures of `receives_remote_failure_after_retry_count_failures` twice yesterday (locally). Found that all that thread-related stuff is now unnecessary, thanks to the Pierre.
> Fixed spuriously failing on_demand test

- node/runtime/src/lib.rs
- srml/staking/src/lib.rs
Adds a field in the staking module that tracks the session index at which the current era started. This is necessary for the ui to be able to display the progress of the current era, since eras can be skipped we can't do this based on session index alone.
cc @jacogr
> srml: staking: track session index of current era start

- core/consensus/aura/src/lib.rs
- core/consensus/slots/src/slots.rs
- core/test-runtime/src/lib.rs
- node-template/runtime/src/lib.rs
- node/cli/src/service.rs
- node/executor/src/lib.rs
- node/primitives/src/lib.rs
- node/runtime/src/constants.rs
- node/runtime/src/lib.rs
- srml/timestamp/src/lib.rs
The srml timestamp module itself is unit dependent, as long as we are consistent with the data that we feed it. I only needed to update the `InherentDataProvider` to extract milliseconds from clock time, and the slot worker to use millisecond resolution for slot duration. This change is needed because BABE needs to be able to define slot durations at the millisecond level to account for the security parameters.
> Use milliseconds for timestamp resolution

- node/cli/src/service.rs
- node/runtime/src/constants.rs
- node/runtime/src/lib.rs
~Depends on #3210. Only the last commit in this PR is relevant, you should review only that change until #3210 is merged.~
This PR updates the slot duration, epoch duration (to define it in slots), and `c` parameter for the BABE protocol. These parameters were chosen in accordance to the results in https://research.web3.foundation/en/latest/polkadot/BABE/Babe/#6-practical-results. Specifically, we are targetting a 6 second block time with resistance of maximum network delay up to 2 seconds. 
The epoch duration should be way longer in order to collect enough randomness, but for development purposes it is useful to have it relatively low. For Kusama we will use a much longer period.
cc @burdges
> node: Update BABE protocol parameters

- core/client/src/genesis.rs
- core/client/src/light/call_executor.rs
- core/client/src/light/fetcher.rs
- core/executor/src/native_executor.rs
- node/executor/src/lib.rs
Remove a no-longer-true comment, and the `NativeExecutionDispatch::new` method.
> Minor cleanup in native_executor.rs

- core/network/src/custom_proto/behaviour.rs
- core/network/src/custom_proto/handler.rs
- core/network/src/custom_proto/mod.rs
- core/network/src/custom_proto/tests.rs
- core/network/src/custom_proto/upgrade.rs
- core/network/src/protocol.rs
- core/network/src/protocol/message.rs
Considering that the `network-libp2p` and `network` crates have now been merged, let's make the protocol not generic over the type of the network message anymore. This PR removes the generic template parameter of everything in `custom_proto` to be hardcoded to `Message<B>` (which is the enum of all the possible Substrate-specific network messages).
To me, the code in `custom_proto` is pretty much "legacy". It has several issues that are not caused by the code but by the protocol level itself, and that we cannot fix without breaking the entire network.
We can expand the `Message` enum, but we shouldn't expand the protocol itself using `custom_proto`. In other words, we shouldn't create a new `Foo` enum and start using `CustomProto<Foo>` in parallel with `CustomProto<Message<B>>`. Hence why …
> Network: stop being generic over the type of message

- core/executor/src/wasm_executor.rs
- core/sr-io/src/lib.rs
- srml/support/src/storage/mod.rs
- srml/support/src/storage/unhashed/mod.rs
Fix: https://github.com/paritytech/substrate/issues/3219
> Remove `IncrementalInput` and fix wasm `storage_into*`

- Cargo.lock
- core/consensus/common/primitives/Cargo.toml
- core/consensus/common/primitives/src/lib.rs
- node/runtime/Cargo.toml
- node/runtime/src/lib.rs
The goal of the commit is to be able to retrieve the current set of authorities
without needing to know the concrete consensus mechanism in place.
In order to achieve the above this commit introduces the
`core/consensus/common/primitives` crate, declaring the `ConsensusApi` runtime
API. In addition it implements the above mentioned trait definition in
`node/runtime` by returning the current authorities of the BABE consensus
mechanism.
>  You bumped the runtime version if there are breaking changes in the runtime.
Does adding an API require a runtime version bump? 
This is part of the effort of validators discovering and connecting other
validators on the network layer (See https://github.com/paritytech/substrate/issues/1693). I will be proposing small
pull requests instead of a single big …
> core/consensus,node/runtime: Declare and implement authorities endpoint

- Cargo.lock
- core/cli/src/lib.rs
- core/cli/src/params.rs
- node/cli/Cargo.toml
- node/cli/src/factory_impl.rs
- node/cli/src/lib.rs
- test-utils/transaction-factory/src/complex_mode.rs
- test-utils/transaction-factory/src/lib.rs
There is currently an issue with the `substrate factory` CLI command (for dev chains) due to a hard-coded minimum balance. This fixes the issue so that the produced blocks are valid.
Also adds a new CLI flag for factory and import-blocks to set the execution engine.
These issues were surfaced during performance testing of Wasm execution.
> Fix substrate factory CLI command

- core/service/src/chain_spec.rs
- node/cli/src/chain_spec.rs
For #2416 I'd like to be able to pass the chain-spec JSON from the JavaScript API.
Right now, you can create a `ChainSpec` from only three ways: from a `&'static [u8]`, from a file (through a `PathBuf`), or manually.
This PR adds the possibility to pass a `Vec<u8>`.
> Allow creating a ChainSpec from a Vec<u8>

- core/consensus/babe/primitives/src/lib.rs
- core/test-runtime/src/lib.rs
- node/runtime/src/constants.rs
- node/runtime/src/lib.rs
- srml/babe/src/lib.rs
Since BABE is probabilistic it is not trivial to figure out what the expected average block time should be based on slot duration and the security parameter `c`. Still this is useful for the dashboard to be able to show what the expected block time is (and maybe compare it with what we're actually getting), so this PR adds a constant field with this value to the BABE runtime module.
Additionally I also exposed the `EpochDuration` field since it is needed for the dashboard to calculate progress in current session.
cc @jacogr
> srml: babe: add expected block time and epoch duration constants

- core/service/src/chain_ops.rs
cc @jimpo 
Calling `import_blocks` returns a `Future` that imports the blocks passed as parameter into the database. However, at the moment, if an error happens in the import queue, that `Future` will just wait forever and never stop. This PR fixes this.
Additionally, improves the error being displayed on error.
> Properly stop block import on error

- Cargo.lock
- node/cli/Cargo.toml
- node/cli/src/factory_impl.rs
Partly due to interaction with #3191.
> Remove unused imports introduced in #3239.

- Cargo.lock
- core/cli/src/informant.rs
- core/client/Cargo.toml
- core/client/db/src/lib.rs
- core/client/db/src/storage_cache.rs
- core/client/src/client.rs
- core/state-db/src/lib.rs
- core/test-client/src/client_ext.rs
The cache is not currently updated to match the best state when re-org is caused by setting finality, and not by importing a block. 
Also fixed informant reporting false re-orgs.
> Synchronize state cache on finalization

- core/consensus/babe/src/lib.rs
- node/runtime/src/lib.rs
The median calculation that is done to figure out at what time the current slot should start (i.e. offset) is currently not properly implemented. Since it is currently unused I have removed the call from verify to it to avoid any issues. I have also fixed an issue that caused it to panic.
Fixes #3248.
> babe: Disable unused median calculation

- core/state-machine/src/basic.rs
Fixes: https://github.com/paritytech/substrate/issues/3174#issuecomment-516154658
> Don't set `HEAP_PAGES` in `BasicExternalities`

- scripts/flamingfir-deploy.sh
Small fix to correct the artifact VERSION info for flaming fir deployments. This caused problems during the most recent deployment.
> Fix artifact location required for flaming fir deployments

- core/telemetry/src/worker/node.rs
If flushing returns `Pending`, we need to return `Pending` instead of looping.
Therefore fixes the telemetry taking 100% of the CPU if we happen to disconnect from the server.
> Fix infinite loop in telemetry

- README.adoc
Flaming Fir doesn't always sync with latest master and this is not obvious to the user from the README.
I added a hash of the latest known working commit on Flaming Fir and also added some explanation for why this is the case.
> Extend flaming fir version details on README

- Cargo.lock
- core/telemetry/Cargo.toml
- core/telemetry/src/lib.rs
Fix #2823 
The context is explained in #2823 
This PR replaces a `Mutex` with a channel. The `Mutex` still exists because of the hack that #3259 fixes, but it is only ever expected to be locked once at a time. We use `try_lock` and print a warning if the mutex happens to already locked.
I went with forking `slog-async` and doing some minor changes while waiting for https://github.com/slog-rs/slog/issues/221.
The changes compared to upstream `slog-async` can be seen here: https://github.com/slog-rs/async/compare/master...paritytech:master
cc @andresilva
> Replace the telemetry Mutex with a channel

- core/cli/src/lib.rs
If a user desires instantiating and registering their own logger with
the `log` crate before loading substrate, the substrate cli crate
will panic when attempting to initialize the logger. This commit fixes
that.
I targeted the 1.0 branch since that's what I'm using, and this seems
really easy to forward-port. Lemme know if there's an issue with that.
Thanks for your hard work on Substrate!
> Fix panic if a logger has already been initted

- core/telemetry/src/worker/node.rs
Change issues with connecting to a telemetry server from `DEBUG` to `WARN`.
Drawback: if we're offline, we'll get spammed with warnings about failing to reach the telemetry server. There's a delay of 5 to 10 seconds between two connection attempts, so it should be fine.
> Telemetry connectivity issues are now WARN

- core/telemetry/src/worker.rs
- core/telemetry/src/worker/node.rs
Fix #3190 
We now read from the telemetry websocket, because the underlying library relies on that to respond to pings.
The change is untested. If someone has an idea how to test if we're responding to pings, please try.
> Fix telemetry not responding to pings

- core/executor/src/native_executor.rs
- core/panic-handler/src/lib.rs
- core/state-machine/src/ext.rs
A few low-effort changes to `substrate-panic-handler`:
- Renames `AbortGuard::new(false)` to `AbortGuard:force_unwind` and `AbortGuard::new(true)` to `AbortGuard::force_abort` (breaking).
- Makes the implementation details (`set_abort` and `ABORT`) private.
- Adds documentation to the crate.
> Documentation and small cleanup in panic-handler

- node/runtime/src/lib.rs
- srml/staking/src/lib.rs
This is needed for other module to be able to call it.
Also the storage is now private as it shouldn't be written by other module directly
> Make staking add_reward_points_to_validator public

- Cargo.lock
- core/consensus/babe/Cargo.toml
- core/consensus/babe/primitives/Cargo.toml
- core/primitives/Cargo.toml
- core/primitives/src/sr25519.rs
- subkey/Cargo.toml
@bkchr This is intended to merge into your upgrade branch.
- allows for verification of 0.1.1 and 0.8.x signatures
- aligns derivation with 0.1.1
- aligns expansion of pairs with 0.1.1
> Bump schnorrkel to 0.8.3

- node/runtime/src/lib.rs
- srml/staking/src/lib.rs
- srml/staking/src/phragmen.rs
- srml/staking/src/tests.rs
`total` (which includes the amounts that are being unstaked) is wrong when evaluating stakes of validators/nominators for Phragmen. Rather should be `active`.
> Fix staking

- Cargo.lock
- core/primitives/Cargo.toml
- core/test-runtime/wasm/Cargo.lock
- node-template/runtime/wasm/Cargo.lock
- node/runtime/wasm/Cargo.lock
Fixes #3245 in branch v1.0
I force v1.0 to use an old version of substrate-bip39.
> Fix schnorrkel version conflict in branch v1.0

- core/client/src/client.rs
- core/finality-grandpa/src/environment.rs
- core/sr-primitives/src/generic/unchecked_extrinsic.rs
- core/sr-primitives/src/traits.rs
- node/cli/src/factory_impl.rs
- node/cli/src/service.rs
- node/executor/src/lib.rs
- node/runtime/src/lib.rs
- srml/balances/src/lib.rs
- srml/executive/src/lib.rs
- srml/grandpa/src/lib.rs
- srml/staking/src/tests.rs
- srml/system/src/lib.rs
- subkey/src/main.rs
- test-utils/transaction-factory/src/complex_mode.rs
- test-utils/transaction-factory/src/lib.rs
- test-utils/transaction-factory/src/simple_modes.rs
This changes the transaction format. Specifically, the signed data in substrate node is now:
call, era, era milestone block hash, genesis hash, nonce, tip.
> Check the genesis hash in transactions regardless of era.

- core/consensus/babe/primitives/src/lib.rs
- core/consensus/babe/src/lib.rs
- node/runtime/src/lib.rs
- srml/babe/src/lib.rs
- srml/session/src/lib.rs
We already had all the infrastructure in place to collect authorship data from BABE predigests but it wasn't wired in on the node runtime.
Fixes #2986.
> node: use BABE predigest data to find authorship

- core/rpc/src/helpers.rs
- core/rpc/src/system/mod.rs
- core/rpc/src/system/tests.rs
- core/service/src/components.rs
- core/service/src/lib.rs
cc #3099 
Continuation of the switch, this time with the API of the `substrate-rpc` crate.
Again, the logic is very straight-forward.
The code is a bit dirty because both `jsonrpc` and `substrate-service` use old futures at the moment, so we're converting to new futures and then back to old futures.
As the switch continues, the code will get cleaner.
> Switch RPCs to stable futures

- node/cli/src/service.rs
Transaction format was updated in #3286, the raw payload needed to be updated in the integration test that creates and send extrinsics from scratch.
> node: fix integration test transaction format

- node/runtime/src/lib.rs
- srml/babe/src/lib.rs
Follow the spec: Use the concatenation of VRF outputs within the epoch as opposed to the XOR.
> fix BABE randomness calculation

- srml/staking/src/inflation.rs
DONE:
* we don't hard-code x_ideal to 0.5 in some tests
* improved doc
Keep in mind that this is internal doc. user of staking module doesn't see anything of what is there
cc @AlfonsoCev
> Improve internal doc of inflation module

- node/runtime/src/lib.rs
- srml/support/procedural/src/storage/impls.rs
- srml/support/src/storage/hashed/generator.rs
- srml/support/test/tests/instance.rs
Default implementation of insert_ref was writting to using twox 128 hasher instead of choosen hasher.
Also linkedmap implementation was wrong because default implementation wasn't override.
> Fix decl_storage map and linked_map for insert_ref

- core/network/src/on_demand_layer.rs
- core/network/src/protocol.rs
- core/network/src/protocol/light_dispatch.rs
- core/network/src/protocol/light_server.rs
- core/network/src/service.rs
Can be reviewed commit by commit, but the PR is almost insubstantial and should be very straight-forward to review.
Does some basic house-keeping: renames `OnDemandCore` to `LightDispatch` in order to make what it is more explicit, and `on_block_announce` to `update_best_number` for the same reason.
Adds some documentation.
> Rename on_demand to light_dispatch and various minor changes

- core/client/db/src/light.rs
It isn't used anywhere - `fn leaves()` on light blockchain is simply `unimplemented()` ([here](https://github.com/paritytech/substrate/blob/5342c6309490aa37de3a5a3dbc19c4542294bc91/core/client/src/light/blockchain.rs#L183)). If we would need this, this commit could be reverted, but for now it is just a noise in the code && small performance overhead in runtime.
> Remove leaves tracking from light backend

- core/telemetry/src/worker/node.rs
> Handle telemetry socket errors

- core/network/src/lib.rs
- core/network/src/transport.rs
Fix #3304
Yamux has been the default multiplexing layer for a long time and seems to work well. Mplex was still available as a backup option, but we have not needed it in the past six months. Let's remove support for it.
> Remove support for mplex

- core/sr-primitives/src/lib.rs
- node/runtime/src/lib.rs
CompactAs derive introduced in recent `parity-scale-codec` release https://github.com/paritytech/parity-scale-codec/pull/97
>  Derive CompactAs for Perbill/mill/U128 

- core/network/src/lib.rs
- core/network/src/transport.rs
When opening #3312, I overlooked the fact that mplex is the only thing supported by Jaco's JS light client.
> Reintroduce mplex (revert #3312)

- core/cli/src/lib.rs
- core/cli/src/params.rs
- core/service/src/config.rs
- core/service/test/src/lib.rs
- node/cli/src/service.rs
- Removes `--validator` and `--grandpa-voter`
- Make `--alice` etc work without `--dev`
> Clean up CLI interface

- Cargo.lock
- core/client/src/client.rs
- core/network/src/protocol/sync.rs
- core/service/src/lib.rs
Fixes #3269 
* Cache idle state in sync so that requests are not collected with every network poll.
* Block import are printed in the console by default
* Removed some additional console spam.
> Improve console output

- Cargo.lock
- core/primitives/src/crypto.rs
- core/rpc/Cargo.toml
- core/rpc/src/author/mod.rs
- core/rpc/src/author/tests.rs
- core/rpc/src/state/tests.rs
- core/service/Cargo.toml
- core/service/src/components.rs
- core/test-runtime/Cargo.toml
- core/test-runtime/src/lib.rs
- node/primitives/Cargo.toml
`author_rotateKeys` will rotate all session keys, store them into the
keystore and returns their encoded public keys as result. These encoded
public keys can be used directly to send the transaction to the chain.
> Adds `author_rotateKeys` RPC

- node/runtime/src/lib.rs
- srml/contracts/src/lib.rs
- srml/contracts/src/wasm/runtime.rs
The access pattern of reading sandbox memory and decoding is used a lot and pretty ugly. This cleans that up.
Also, two tiny and likely inconsequential storage access tweaks.
Was reminded of this during review of #3255.
> srml-contracts: Refactor away some duplication in runtime functions.

- srml/staking/src/lib.rs
The documentation for the `set_controller` function was copied from the function above it, however it does not do the same thing. Fixed the documentation to fit the correct description of what `set_controller` does.
> Fix documentation set_controller

- core/finality-grandpa/src/lib.rs
- node/cli/src/service.rs
Block production would break if `--no-grandpa` was passed since the finality tracker inherent provider was not registered.
> grandpa: fix --no-grandpa flag breaking block production

- core/finality-grandpa/src/tests.rs
In the catch up test we spin up 2 nodes and wait for them to finalize until block 50 (at least 4 rounds). Then we spin up a new voter and wait until it catches up to the latest round (which can only be achieved by sending a catch up request). Previously, we'd wait for the later voter to finalize block 50 before checking the round it is in (to assert it has caught up to the latest round), this assumed that the only way to finalize block 50 would be to catch up to the latest round which is not true since the voter can also observe commits and finalize blocks. I changed the test so that we don't check which blocks were finalized, and instead just wait until we catch up to the latest round (timing out after 5 minutes if we don't).
Seems to solve the issue with #3325 and should make the test …
> grandpa: fix catch up test

- core/cli/src/lib.rs
- core/cli/src/params.rs
- node/cli/src/service.rs
Conflicts with #3348 but I think I prefer this one instead, because realistically no one will actually pass `--no-validator` and full nodes will be unnecessarily running validator code.
> node: Reintroduce `--validator` cli flag

- core/finality-grandpa/src/lib.rs
- core/network/src/protocol/consensus_gossip.rs
- node/cli/src/service.rs
When we run with GRANDPA disabled besides registering the finality tracker inherent provider we must also register a gossip validator for GRANDPA messages, otherwise we will ban peers who send us GRANDPA `Neighbor` messages since there's no validator associated with consensus engine id of message. I added a validator that just discards all messages. I tested this locally with 2 authorities (one running with `--no-grandpa`) and it works correctly now.
> node: setup disabled grandpa properly

- node-template/runtime/src/lib.rs
- node/cli/src/factory_impl.rs
- node/primitives/src/lib.rs
PR into the `gav-scale` branch (along with BlockNumber move)
> Move Nonce/Index to u32

- core/cli/src/lib.rs
- node-template/src/cli.rs
- node/cli/src/lib.rs
Deprecates `parse_and_execute` and replaces it with a new `parse_and_prepare` function whose control flow is in my opinion way easier to read.
I invite you to check out the third commit to see what the new code looks like.
The reason for this change is that I'd like to get rid of the `ServiceFactory` and `Components` traits, which `parse_and_execute` uses.
This PR instead moves the `ServiceFactory` trait usage to when the user calls `run()`, which makes it possible in the future to add functions other than `run()` that don't require this trait.
As an example, we could add a function to `ParseAndExecute::RevertChain` that simple requires passing a `Client` by parameter, instead of asking for a `ServiceFactory`.
> Refactor parse_and_execute

- core/cli/src/error.rs
- core/finality-grandpa/src/lib.rs
- core/service/src/components.rs
- core/service/src/lib.rs
- core/service/test/src/lib.rs
- node-template/src/cli.rs
- node-template/src/main.rs
- node/cli/src/lib.rs
- node/cli/src/service.rs
- node/src/main.rs
Currently if either GRANDPA or BABE fails the node continues running, this behavior might be hard to spot by the users. For example, if the GRANDPA voter fails, the node might keep producing blocks but not observing finality anymore (and potentially not participating in the protocol). Most likely validators will have some process monitoring in place which will just restart the node afterwards.
In this PR when either of these validator tasks fails we shut down the service and exit cleanly.
> node: exit on GRANDPA voter or BABE authoring error

- core/executor/runtime-test/src/lib.rs
- core/executor/src/wasm_executor.rs
- core/sr-io/src/lib.rs
- core/sr-io/with_std.rs
- core/sr-io/without_std.rs
- core/sr-primitives/src/traits.rs
- core/test-runtime/src/system.rs
- srml/system/src/lib.rs
> Remove enumerate_trie_root in favour of ordered_trie_root #2382

- core/network/src/legacy_proto/upgrade.rs
peers can send us all kinds of garbage; it shouldn't fill up the logs.
> downgrade log-level of malformed packets to debug

- core/sr-sandbox/src/lib.rs
- node/executor/src/lib.rs
- node/runtime/src/lib.rs
- srml/contracts/COMPLEXITY.md
- srml/contracts/src/exec.rs
- srml/contracts/src/lib.rs
- srml/contracts/src/tests.rs
- srml/contracts/src/wasm/mod.rs
- srml/contracts/src/wasm/prepare.rs
- srml/contracts/src/wasm/runtime.rs
This PR does two things
1. Refactor the exec logic so that a single allocated scratch buffer is used for all nested calls during a contract execution.
2. Allow the "call" and "deploy" functions in contracts to return an exit status and output data through the scratch buffer. This is an implementation of #3038.
The PR could be split into two if people prefer, but the status code changes somewhat motivate the other refactors.
The idea with the global scratch buffer is that a contract execution may invoke other nested executions through `ext_call` or `ext_create`. Each execution needs a scratch buffer. Notably, the scratch buffer is overwritten on both of these calls so it is possible to pass ownership of the same scratch buffer to the nested executions in order to reduce memory allocations. …
> srml-contracts: Contract calls/instantiations to return exit statuses

- core/sr-primitives/src/generic/block.rs
- core/sr-primitives/src/generic/digest.rs
- core/sr-primitives/src/generic/header.rs
- core/sr-primitives/src/lib.rs
Required for sharing `SignedBlock` and `Header` with users so they don't have to redefine them.
> Implement Deserialize for SignedBlock and Header.

- node/cli/src/chain_spec.rs
- node/executor/src/lib.rs
- node/runtime/src/lib.rs
- srml/staking/src/lib.rs
- srml/staking/src/mock.rs
- srml/staking/src/tests.rs
Before it was only possible to force an era. Now we can force eras not to happen, useful for the PoA period of Kusama.
> Era change can be forced on and forced off

- subkey/src/main.rs
Old behaviour didn't take account of `--network` flag when inspecting a derived address.
> subkey network default works

- core/network/src/config.rs
- core/network/src/service.rs
`PeerSetHandle.set_priority_group` allows modifying a priority group by
group identifier. With this commit the function can be accessed through
`NetworkService`.
This is need in order for a validator to connect to as many other
validators as configured without reserving a specific connection slot
for them.
This is needed for #3247, see https://github.com/paritytech/substrate/pull/3247#issuecomment-516351141 for details.
> core/network: Surface peerset's `set_priority_group` in NetworkService

- core/client/db/src/lib.rs
- core/state-db/src/lib.rs
- core/state-db/src/noncanonical.rs
Currently, when pinned state is discarded on canonicalization state-db would refuse to canonicalize and delay it till next call to `canonicalize_block`. This may lead to state-db canonicalized block and blockchain metadata finalized block to go out of sync. 
This PR changes the implementation to apply canonicalization regardless of pinned state, keeping pinned values in memory until they are not needed anymore. 
Also fixed a race between `is_pruned` and `pin`
> More robust state pinning

- core/consensus/aura/src/lib.rs
- core/consensus/babe/src/lib.rs
- core/consensus/babe/src/tests.rs
- core/service/src/chain_ops.rs
- core/service/src/components.rs
- core/service/src/lib.rs
- node-template/src/service.rs
- node/cli/src/service.rs
We need to submit report transactions when we discover an equivocation while importing [(see here for definition of equivocation)](https://research.web3.foundation/en/latest/polkadot/slashing/).
As a starting point, this PR adds the transaction pool to Aura and Babe import queue (and `check_header`).
> Add transaction pool to Aura and Babe import queue

- core/network/src/protocol/light_dispatch.rs
- node/cli/src/chain_spec.rs
- node/runtime/src/lib.rs
- srml/contracts/src/tests.rs
- srml/im-online/src/lib.rs
The behavior we want is for gossiping to occur automatically right at startup.
It's not necessary to make this configurable. Also it's possibly dangerous to make this configurable, since if misconfigured a heartbeat would only be sent out at the configured block ‒ possibly resulting in slashing if this block is greater than the session length.
> Replace config field with default value (srml/im-online)

- srml/collective/src/lib.rs
- srml/membership/src/lib.rs
- srml/support/src/traits.rs
Fixes: https://github.com/paritytech/substrate/issues/3373
> Make sure that `srml-collective` does not initialize `Members` twice

- srml/generic-asset/src/lib.rs
- In particular, mind the maximal line length.
Thank you!
> clarify comment

- core/rpc/src/subscriptions.rs
Just fixes a minor typo in a comment.
> Minor typo fix. bu -> by

- core/finality-grandpa/src/tests.rs
Similar to #3393 and #3309. This time in the GRANDPA tests.
cc #3099 
(lots of 0, 3 and 9 in these numbers)
> Remove usage of loop_fn in the GRANDPA tests

- srml/staking/src/lib.rs
This PR makes the inflation module public so that one can access the functions inside.
I am trying to access the inflation functions/rate in order to mint tokens for the Treasury. We would like to do so in different time intervals. My intuition is that if I provide a smaller interval I will still get roughly the same inflation rate as is created over an era.
> Make inflation mod public to access inflation functions

- Cargo.lock
- core/consensus/aura/src/lib.rs
- core/consensus/babe/src/lib.rs
- core/consensus/babe/src/tests.rs
- core/consensus/slots/Cargo.toml
- core/consensus/slots/src/lib.rs
Introduce `SimpleSlotWorker` trait which implements `on_slot` with the current logic shared between Aura and Babe.
> consensus: refactor aura and babe proposer

- core/finality-grandpa/src/lib.rs
In the same vein as #3309, remove the usage of a futures combinator loop for the voter.
This makes the code cleaner, and also makes it possible to transition to stable futures.
I took the liberty to replace the `Option<Voter>` (that was polled through a `poll_fn`) with a `Box<Future>`, where `None` is a `futures::empty()`.
cc #3099
> Rewrite the GRANDPA voter to not use a loop

- Cargo.lock
- core/rpc/src/author/mod.rs
- core/rpc/src/author/tests.rs
- core/service/src/lib.rs
- core/transaction-pool/Cargo.toml
- core/transaction-pool/graph/Cargo.toml
- core/transaction-pool/graph/src/pool.rs
- core/transaction-pool/graph/src/watcher.rs
**Please don't merge before #3384 to save me a painful rebase**.
cc #3099 
Everything in `core/transaction-pool` now uses stable futures.
New-futures receivers can no longer error.
> Transition the transaction-pool to new futures

- core/network/src/protocol/consensus_gossip.rs
Previously, some terms such as `topic` and the role of the consensus engine ID were not discussed.
> add some docs for consensus-gossip

- core/network/src/protocol/sync.rs
When we receive a new block announcement we check whether we already know the block or its parent in order to update common block number of the peer that sent the announcement. We were performing the check for `known_parent` first, which means that if we already knew the announced block (not its parent!) we would still set our common number to `announced - 1`, instead of `announced`. This lead to continuously downloading and importing the tip of the chain.
The fix is to change the order of the checks, so that the check for known announced block is done before the check for its parent.
> sync: fix peer common number on block announce

- node/runtime/src/lib.rs
- srml/im-online/src/lib.rs
The session module peforms a "buffering" of validator sets, i.e. when we start session N, we already know the validator set for session N+1. The `on_new_session` handler gets as parameter the validator set for the session that's just starting (N), and what the validator set will be for the follow up session (N+1). Whenever the session changed, the i'm online module was setting the keys for the follow-up session (N+1) rather than for the session that was just starting.
> im-online: use new session keys (not upcoming session)

- node/cli/src/chain_spec.rs
- node/runtime/src/lib.rs
- srml/aura/Cargo.toml
- srml/aura/src/lib.rs
- srml/babe/src/lib.rs
- srml/grandpa/Cargo.toml
- srml/grandpa/src/lib.rs
- srml/grandpa/src/mock.rs
- srml/im-online/src/lib.rs
- srml/session/src/lib.rs
- srml/session/src/mock.rs
- srml/staking/src/mock.rs
The `SessionHandler` is extended with a method for informing about the genesis validator set. This avoids having to configure all of the keys in the chain spec as they will all be initialized from the session module. I still kept the authorities configurable in the modules that interact with session (grandpa, babe, i'm online) because it is useful when using those modules without session.
> session: add handler for genesis session

- core/transaction-pool/graph/src/error.rs
- core/transaction-pool/graph/src/pool.rs
We use `provides` tags to uniquely identify transactions (i.e. there can be many different transactiions with the same `hash`, that lead to the same effect - hence `provides`).
Transactions with no `provides` are effectively never evicted properly from the pool (they are only removed after some timeout), cause we currently don't do hash-based eviction, but rather provided-tags-based one.
This PR rejects immediately transactions with no `provides` tags to force runtime implementers to provide some.
Related to `claims` module issues in polkadot repo.
CC @jacogr
> Reject transactions with no `provides` tags.

- core/sr-primitives/src/traits.rs
- node/runtime/src/lib.rs
- srml/im-online/src/lib.rs
Closes: #3091
We can't rely on checks done in `validate_unsigned`, since they are only done for the transaction pool and during regular execution (i.e. `apply_extrinsic`) we really need to perform them again, to prevent a malicious actor creating a block with such invalid extrinsic.
Since the testing boilerplate for `im-online` is non-existent in `master` I'll add a test for this after #3322 is merged.
> Verify signature and session index during apply phase of im-online.

- srml/staking/src/lib.rs
- srml/staking/src/tests.rs
Offences from a prior era are discarded, and we track how much of the current era's exposure we've already slashed to avoid over-slashing.
> Allow slashing only on current era

- core/executor/src/wasm_runtimes_cache.rs
- core/test-runtime/src/lib.rs
Currently, the `:heap_pages` parameter is not respected, i.e. when `heap_pages` is changed on chain the runtime doesn't get invalidated. This PR performs this invalidation.
Initially was spotted while implementing #3011, but then I figured that the PR was already growing unwieldy.
This PR introduces additional look up on every fetch of the current runtime. Haven't done any benchmarks yet.
> Respect heap_pages parameter.

- srml/staking/src/tests.rs
Apparently, the separate CI job to test staking without the default features (which is needed) was skipped.
> Fix staking tests

- Cargo.lock
- core/client/Cargo.toml
- core/client/src/client.rs
When importing a new block we now check that it doesn't revert finality and in case it does we refuse to import the block. The number of the block being imported must be higher than the last finalized number (cheaper first check), and the imported block must be a descendant of the last finalized block.
> client: refuse to import blocks that revert finality

- core/finality-grandpa/src/environment.rs
- core/network/src/protocol/sync/extra_requests.rs
We can finalize blocks either through sync (import justifications) or gossip (grandpa voter/observer). Which means that we need to guard against the best finalized block before trying to finalize, otherwise some of the internal data structures (like `AuthoritySet`) will error with finality reversions.
> grandpa: fix finalization race condition

- Cargo.lock
- core/client/Cargo.toml
- core/client/db/Cargo.toml
- core/primitives/Cargo.toml
- core/sr-io/Cargo.toml
- core/state-machine/Cargo.toml
- core/test-client/Cargo.toml
- core/test-runtime/Cargo.toml
- core/trie/Cargo.toml
- node-template/Cargo.toml
- node/executor/Cargo.toml
- node/runtime/src/lib.rs
This PR updates trie dependencies to 0.15.2 which uses hashbrown in replacement of hashmap_core.
> Update trie crate to hashbrown usage.

- core/network/src/protocol/sync/extra_requests.rs
We don't want to return immediately if we get a revert from the fork tree, we still want to update the internel state. I actually pushed this yesterday to #3437 but it didn't go through (shitty internet) and I didn't notice.
> sync: don't return on fork tree revert

- srml/support/procedural/src/lib.rs
Was trying to figure out how to use the genesis config functionality and realized the docs were incorrect, so I fixed them.
> Added more correct documentation for using genesis config

- Cargo.lock
This version fixes an issue with lifetime elision which causes compilation to fail on recent rustc versions (e.g. 1.39.0-nightly (bea0372a1 2019-08-20)).
See https://github.com/paritytech/soketto/pull/1 for more information.
> Update soketto to version 0.2.3

- core/consensus/aura/src/lib.rs
If we are going to author blocks we need to have a keystore available, otherwise it is useless to start the worker in the first place.
> aura: keystore is required for authoring

- node/runtime/src/lib.rs
- srml/contracts/src/account_db.rs
- srml/contracts/src/exec.rs
- srml/contracts/src/tests.rs
- srml/contracts/src/wasm/runtime.rs
This implements a solution to #3254, in particular the one described in [this comment](https://github.com/paritytech/substrate/issues/3254#issuecomment-521630165).
- If a contract is called and returns from a call with a balance below the existential deposit, the contract is immediately removed and its balance is set to 0. This is visible to any contracts calling it higher in the execution stack.
- There is an exception if the contract with insufficient balance is being recursively called from itself. If a contract returns with balance below existential deposit and is also being executed higher up in the execution stack, then the nested call traps immediately. The caller sees the trap and may be able to recover.
- If a contract is instantiated and returns from the constructor with a …
> srml-contracts: Apply contract removals immediately

- srml/support/src/runtime.rs
In case you write a not generic Event in construct_runtime for an instantiable module it just gets ignored. This print a message.
> construct_runtime: Avoid ignore not generic Event  for instantiable modules.

- Cargo.lock
- core/sr-primitives/src/traits.rs
- srml/balances/src/lib.rs
- srml/contracts/src/lib.rs
- srml/example/Cargo.toml
- srml/example/src/lib.rs
- srml/system/src/lib.rs
Closes #3299 
Also adds some documentation about the replacement of `MakePayment`: `SignedExtensions` to the example module.
> Remove MakePayment and introduce SignedExtension docs/examples

- core/finality-grandpa/src/communication/gossip.rs
- core/finality-grandpa/src/communication/mod.rs
- core/finality-grandpa/src/communication/tests.rs
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/observer.rs
- core/finality-grandpa/src/tests.rs
Currently, the GRANDPA observer would be sending catch up messages based on neighbor's packets even though the reply is ignored by the observer. This PR makes the catch up requests optional and disables it for the observer.
> grandpa: observer doesn't send catch up messages
