- node/runtime/src/lib.rs
- srml/support/procedural/src/storage/impls.rs
- srml/support/src/lib.rs
As for now default implementation of swap in srml-support/storage/hashed/generator breaks linked_map implementation of its linked list.
I'm not sure what are the most idiomatic rust but it feels to me in the future we should remove this default implementation of storage map as it is confusing with other implementation (such as linkedmap) which break assumptions of this default.
for me either we divide into two different trait or we make no default implementation.
But before this happens here is a fix in the current design.
default swap method in storagemap is override in the implementation for linkedmap made in decl_storage.
* The changes or remains of order of the linked_list for a swap is not specified in the API. No guarantee must be made by user. maybe this should deserve a comment …
> Fix linkemap swap

- core/rpc/src/chain/mod.rs
- core/rpc/src/chain/tests.rs
Closes #3431
The old name is available as an alias.
CC @jacogr
> Pluralise newHead RPC subscription

- .gitlab-ci.yml
- Cargo.lock
- core/offchain/Cargo.toml
- core/offchain/src/api.rs
- core/offchain/src/api/http.rs
- core/offchain/src/api/timestamp.rs
- core/offchain/src/testing.rs
- core/primitives/src/offchain.rs
- core/sr-io/src/offchain/http.rs
- core/sr-io/without_std.rs
- node/runtime/src/lib.rs
Supersedes #3447 
Since I couldn't push to @tomaka's branch, I'm reopening the PR with the last TODO fixed.
Repasting the description here as well.
Implements the currently-unimplemented API.
**I'm opening this PR as a draft because I'm going to be away for a bit, and I encourage someone to finish it if they want**.
The only thing that's not implemented is a small TODO to fix: we unwrap if we fail to initialize the `TlsConnector`. How is it even possible to fail to initialize TLS? I have absolutely no idea, and I think it's a platform-specific "just in case" thingy. But since the word `unwrap` is explicitly written in the code, I guess we have to handle this situation.
I'd like to fix that by having some `enum { HttpConnector, HttpsConnector }` where we fall back to the `HttpConnector` if …
> Implement HTTP request in offchain workers

- srml/support/procedural/src/storage/transformation.rs
defining the type allow better error message.
and having the span allow compiler to points to the closure.
> Decl_storage: improve error msg on wrong closure signature

- core/client/src/light/call_executor.rs
- core/test-runtime/src/system.rs
At some point  we started to use parent header' digest in `check_execution_proof()`, instead of empty digest (that is used when proof is built). This PR fixes that + modifies existing test to catch this type of errors.
> Fixed digest in execution proof check

- node/runtime/src/lib.rs
- srml/balances/src/lib.rs
- srml/democracy/src/lib.rs
- srml/elections/src/lib.rs
- srml/staking/src/lib.rs
- srml/treasury/src/lib.rs
I realized ([thorough a copypasta](https://github.com/paritytech/substrate/pull/3364#discussion_r313800241)) that they are sitting on top of a few runtime modules with no purpose whatsoever. My guess is that the original author intended to do something like they have done in `finality-tracker`: declaring a few `pub const DEFAULT_XXX` in each module and aggregating in `node/runtime` if needed. Either way, removed since not used. We also have `const.rs` for this.
> Clean runtime constants

- node/runtime/src/lib.rs
- srml/balances/src/lib.rs
- srml/balances/src/tests.rs
This will help rather a lot with Kusama's PoA period.
> Allow root to force transfers

- node/runtime/src/lib.rs
- srml/aura/src/lib.rs
- srml/democracy/src/lib.rs
- srml/staking/src/lib.rs
- srml/support/src/traits.rs
- srml/timestamp/src/lib.rs
Saves some typing and I don't see way it can't have `Copy`
> add Copy to Moment type

- core/rpc/src/state/tests.rs
- core/sr-version/src/lib.rs
Currently `RuntimeVersion` fails to deserialize, because it has custom serialization for `ApisVec` (8 byte hex strings) but uses the default derived deserializer.
This PR adds a custom deserializer for `ApisVec`. There might be a cleverer way to do this with serde magic - not an expert with that.
> Custom deserialize impl for ApisVec

- README.adoc
Missed a typo ("SEEED") in a review on Saturday, fixing here.
> Fix typo in readme

- core/client/db/src/cache/mod.rs
- core/client/db/src/light.rs
> Init blockchain cache on restart

- Cargo.lock
- core/client/src/client.rs
- core/offchain/src/lib.rs
- core/primitives/Cargo.toml
- core/primitives/src/lib.rs
- core/primitives/src/offchain.rs
- core/sr-api-macros/src/decl_runtime_apis.rs
- node/runtime/src/lib.rs
If we call into the runtime, we can pass various `ExecutionContext`s to identify where is it coming from.
Initially this was only affecting how we run the call (a.k.a execution strategy = native / wasm), with introduction of `OffchainWorkers` this also controls the APIs that are available for that part of the runtime.
Recently in #3296 we've introduced additional keystore APIs that must not be available for consensus-critical code, but are very useful for off-chain calls, like rotating the keys - they are only valid in  `ExecutionContext::Other`.
This PR introduces a possibility to further control what APIs (`Capabilties`) are available for particular off-chain call and tries to make it more explicit. This will come handy to implement equivocation reporting for Grandpa/Babe, since we will …
> Introduce capabilities filtering for off-chain runtime calls.

- core/rpc/src/author/error.rs
Closes: https://github.com/paritytech/substrate/issues/3489
> Improve `insert_key` error message on unsupported key type

- node/runtime/src/lib.rs
- srml/authorship/src/lib.rs
I would also suggest uncle pruning to be moved from `on_initalize` to `set_uncles`
> Fixed uncle pruning

- core/service/src/lib.rs
Require the `SelectChain` trait for the `SelectChain` associated type.
Minor tweak to make the `AbstractService` trait more usable.
> Require the `SelectChain` trait for the `SelectChain` associated type

- Cargo.lock
- core/client/src/genesis.rs
- core/executor/src/native_executor.rs
- core/rpc/Cargo.toml
- core/rpc/src/state/tests.rs
- core/test-runtime/client/src/lib.rs
- core/test-runtime/src/genesismap.rs
- node-template/src/service.rs
- node/executor/src/lib.rs
This PR consist of 3 changes separated by commits:
1. In substrate-test-client we can now add arbitrary storage entries (only main storage though),
2. Use that functionality for creating custom storage entry for testing the RPC storage behavior,
3. Since that leaves no usages of it in the codebase, retire `native_equivalent`.
> Eradicate native_equivalent

- core/offchain/src/api/http.rs
- core/offchain/src/api/timestamp.rs
Fixes a bug where we were not inserting the request back in case of a deadline when waiting.
Adds a lot of clarifications to the code.
Maybe the code should also be split a bit more and the worker extracted to a different module, but that's a low priority change.
> Some tweaks to offchain HTTP workers

- Cargo.lock
- core/application-crypto/src/traits.rs
- core/consensus/aura/primitives/src/lib.rs
- core/rpc/src/author/mod.rs
- node/cli/src/chain_spec.rs
- node/runtime/src/lib.rs
- srml/authority-discovery/Cargo.toml
- srml/authority-discovery/src/lib.rs
- srml/im-online/src/lib.rs
The i'm online module is hardcoded to use sr25519 keys but we have no specific requirement on crypto type. The crypto is now generic and we support ed25519 and sr25519 for the module. Additionally, I also had to change the `authority-discovery` module to depend on `im_online` and use it's generic public key type.
cc @drewstone
> im-online: use generic crypto

- core/finality-grandpa/src/communication/gossip.rs
- core/finality-grandpa/src/communication/tests.rs
Observers update their view with neighbor packets but since they don't run the full GRANDPA protocol they don't keep track of the vote data necessary to reply to catch-up requests. We need to make sure that we only issue catch up requests to authorities.
> grandpa: only send catch-up requests to authorities

- node/cli/src/service.rs
When using BABE import queue we create a task that takes care of pruning the Epoch change tree based on finality. This task was previously not started for the light client because when using `construct_service_factory!` it could only be done in `AuthoritySetup` where we had access to the `Service`. After #3382 it is now possible to spawn the task for the light client as well.
> node: spawn babe epoch pruning in light client

- node/runtime/src/lib.rs
- srml/system/src/lib.rs
Currently `Mortal` transactions are not tracked correctly in the transaction pool. The `TransactionValidity` indicates `longevity: max_value()` while in practice, they are not valid beyond some point.
Block producing nodes are able to detect that when they attempt to push transactions to the block - they remove such transactions as invalid afterwards.
However regular nodes will store such transactions indefinitely, which in turn may cause issues with `nonce` reusal.
See https://github.com/polkadot-js/api/issues/1268 for some context.
CC @jacogr 
I'll also prepare a follow-up PR that re-validates all transactions in the pool periodically (if they occupy the pool for a longer period of time), so that we can detect any other stallness (like sender balance dropping after the transaction get's …
> CheckEra affects longevity of transactions

- Cargo.lock
- README.adoc
- core/executor/runtime-test/build.rs
- core/test-runtime/build.rs
- core/utils/wasm-builder-runner/Cargo.toml
- core/utils/wasm-builder-runner/src/lib.rs
- core/utils/wasm-builder/Cargo.toml
- core/utils/wasm-builder/src/lib.rs
- core/utils/wasm-builder/src/wasm_project.rs
- node-template/runtime/build.rs
- node/runtime/build.rs
- scripts/build-only-wasm.sh
- Adds a new env variable `WASM_TARGET_DIRECTORY` that controls the target directory for copying the builded WASM binary
- Adds script `build-only-wasm.sh` to only build the WASM binary
- Further improvements to `wasm-builder` to reduce the number of required rebuilds
> Make it easier to just rebuild the WASM files

- .gitlab-ci.yml
for making srml staking tests mandatory in github for merging pull requests status reports are required for every pull request.
as a result of discussion here: https://github.com/paritytech/substrate/pull/3428
> enable srml tests for every pr

- srml/assets/Cargo.toml
- srml/membership/Cargo.toml
- srml/membership/src/lib.rs
- srml/scored-pool/Cargo.toml
- srml/scored-pool/src/lib.rs
- srml/sudo/Cargo.toml
- srml/sudo/src/lib.rs
- srml/support/Cargo.toml
- srml/support/src/double_map.rs
- srml/support/src/lib.rs
- srml/support/src/storage/generator/double_map.rs
- srml/support/src/storage/generator/linked_map.rs
- srml/support/src/storage/generator/map.rs
- srml/support/src/storage/generator/value.rs
it seems codebase is divided between sr_std and rstd.
This PR uniformize to the most used.
> Rename the few remaining sr_std to rstd

- srml/contracts/src/exec.rs
- srml/contracts/src/wasm/mod.rs
- srml/contracts/src/wasm/runtime.rs
There are two changes separated by commits:
1. Introduction of a new srml-contracts API function `ext_minimum_balance`. Now contracts don't know the minimum amount of funds to create a contract. Contract writers can hardcode it, but then it is going to be problematic if the balance is increased. `ext_minimum_balance` returns the exact amount which is required for creation of an account.
2. Renaming `existential_deposit`to `minimum_balance`. The reason for this change is that `existential_balance` is the term of the `balances` module. However, we don't really interact with it directly and query `T::Currency::minimum_balance()`. So I guess `minimum_balance` is a better name.
> Publish minimum balance from within srml-contracts API

- core/client/src/genesis.rs
- core/client/src/light/fetcher.rs
- core/network/src/chain.rs
- core/network/src/protocol.rs
- core/rpc/src/state/tests.rs
- core/test-runtime/client/src/lib.rs
- core/test-runtime/src/genesismap.rs
@twittner find that on_custom_message for child trie read was missing. This PR adds it (see on_remote_read_child_request).
There is also additional test for child trie (requires a slight change to test genesis builder in order
to be able to init some children values).
Possible suggestion/change:
- merge child test with non child test (and use a store value different than heap for this one).
- use a single primitive and storage when using add_extra_data (with optional storagekey and none for top storage).
> Add missing child trie rpc on_custom_message handler

- node/runtime/src/lib.rs
- srml/staking/src/lib.rs
We use `minimum_balance` unless it refers directly to balances module which uses `existential_deposit`.
> Drive by docs fix re minimum_balance

- core/client/src/client.rs
This check is a major performance hit because a tree route to the last finalized block may potentially contain thousands of blocks (as it does on kusama)
It is also unnecessary since the same condition is properly checked here: https://github.com/paritytech/substrate/blob/7276eeab7da8b78f007a99129aad6e89e9d588c7/core/client/db/src/lib.rs#L897-L904
> Removed superfluous safety check

- core/client/src/client.rs
- core/consensus/common/src/block_import.rs
- core/finality-grandpa/src/light_import.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/test/block_import.rs
Fixes https://github.com/paritytech/substrate-telemetry/issues/175.
Right now we always report to telemetry when we import a new block. Telemetry assumes that this is the new best block which may not be true (we sync all forks we see). This leads the telemetry UI to show more "re-orgs" than actually exist, and also to always show the highest block number for a peer (instead of best). After this PR telemetry UI should always show the latest block notified by the peer (regardless of number), since that it will always be the best block.
> client: only report block import to telemetry if new best

- node/runtime/src/lib.rs
While working on integration tests it was discovered that the units that are used within srml-contracts module are disproportional with the other units used in other places and was disproportionally small.
> srml-contracts: Fix values used for state rent

- core/basic-authorship/src/basic_authorship.rs
- core/client/src/backend.rs
- core/client/src/client.rs
- core/finality-grandpa/src/until_imported.rs
- core/service/src/builder.rs
- core/service/src/lib.rs
- core/transaction-pool/graph/src/pool.rs
> Add transactions from retracted blocks back to the pool

- core/sr-primitives/src/traits.rs
Although simple, the current `Maybe*` trait implementations are based on
a manual approach that uses some code duplication. Now this duplication
is removed using a declarative macro.
Tested locally, the modifications don't seem to affect building times.
> Implement `Maybe*` marker traits using a declarative macro

- core/authority-discovery/Cargo.toml
- node-template/src/service.rs
I am getting this issue when using a project based off node-template and upgrade to latest substrate
```
--> /Users/xiliangchen/.cargo/git/checkouts/substrate-7e08433d4c370a21/17e389d/core/authority-discovery/src/lib.rs:46:38
|
46 | use authority_discovery_primitives::{AuthorityDiscoveryApi, AuthorityId, Signature};
|                                      ^^^^^^^^^^^^^^^^^^^^^ no `AuthorityDiscoveryApi` in the root
```
This fixes the issue. Also fixed an unused var warning.
I guess CI should also be improved to make sure node-template builds?
> Fix node template build issue

- core/finality-grandpa/src/import.rs
- core/network/src/protocol/sync.rs
- core/network/src/protocol/sync/extra_requests.rs
Currently `GrandpaBlockImport` tracks authority set changes in `AuthoritySet`, we require a justification for blocks that enact an authority set change. Additionally, the GRANDPA voter will restrict its votes to blocks that enact an authority set change. This guarantees that said blocks, if finalized, will always have a justification. Additionally, `GrandpaBlockImport` keeps track of consensus changes, this is any kind of changes to the client cache (e.g. a BABE epoch change), and we also require justification for those blocks (added in #3301).
The problem with the current logic is that the sync code will always make the justification requests in-order, therefore if we cannot guarantee that a justification exists for a given block, we might get stuck requesting something endlessly. This …
> grandpa: don't require justification of consensus changes on full node

- core/network/src/protocol/sync/extra_requests.rs
Follow up for this discussion: https://github.com/paritytech/substrate/pull/3540#discussion_r320582285
> Handle missing finality notifications in ExtraRequests

- .gitlab-ci.yml
- ci/check_for_exit.sh
- core/service/src/lib.rs
- node/cli/src/service.rs
Closes: https://github.com/paritytech/substrate/issues/3577
> Augment every task spawned by Service with `on_exit`

- core/offchain/primitives/src/lib.rs
Offchain workers should be run in the context of block `X`, at the same state as it was after the block is imported. This allows us to inspect `system` module and for instance get events that were deposited by extrinsics in a block.
Having no `skip_initialize_block`, actually re-intializes the state with header at `X+1` so this useful data was being erased.
> Don't initialize block for offchain workers.

- README.adoc
Users should be told to use the `--release` flag when running a node, otherwise users may run into block production time problems.
> Use `--release` for running a Substrate dev node

- core/executor/src/wasm_executor.rs
- core/sr-io/with_std.rs
- core/test-runtime/src/lib.rs
- node/runtime/src/lib.rs
There is a problem with `read_storage`, if an offset passed that is out of bounds of the length of the value the implementation of an extrinsic will panic. This PR solves it.
There is another problem with the API itself: there is no way to indicate how many bytes were read. So even if we fix the panic, the API wouldn't be universally usable since the API cannot indicate how many bytes it wrote to the buffer.
The API is not used within Substrate, except for implementing `exists` (e.g. [this](https://github.com/paritytech/substrate/blob/b21d76db6edd4540ee9bd5ed2cbaef2b395a21f8/srml/support/src/storage/child.rs#L85)).
> read_storage panics

- core/finality-grandpa/src/environment.rs
- core/finality-grandpa/src/import.rs
Since we finalize blocks through sync (justification request) and GRANDPA we might run into a race condition when finalizing. All of the finality paths end up in `environment::finalize_block` and we already had a guard there against finalizing something lower than what the client reports as best finalized, but we could race on this check and try to finalize the same block twice (which will fail e.g. if it's an authority set change block). Instead of introducing a new lock I decided to just co-opt `SharedAuthoritySet` to do this synchronization.
> grandpa: fix race condition

- core/network/src/protocol.rs
- core/network/src/protocol/message.rs
- core/network/src/protocol/sync.rs
- core/network/src/service.rs
- core/network/src/test/mod.rs
- core/service/src/lib.rs
Adds block status to `BlockAnnounce` message. This allows for better tracking of perceived best block for peers and removes assumption that their longest chain is the best.
Fixes #3545.
> Send block status with announcement

- core/sr-io/Cargo.toml
- core/sr-io/without_std.rs
- srml/aura/Cargo.toml
- srml/babe/Cargo.toml
By accident it was already enabled in master for quite some time. To
make sure that we don't blow up the wasm binary size, I compiled the
binary with the feature enabled and disabled. With nice panic messages
enabled, the binary size increases by 908 bytes. Given the value that
this feature brings, I think it is okay to have these panic messages
enabled by default.
> Enable nice wasm panic messages by default

- node/cli/src/service.rs
- node/rpc/src/lib.rs
The `ContractsApi` was only created for light-client `rpc_extension`.
I've moved the instantiation to `node/rpc` crate, to avoid duplication.
CC @jacogr
> Fix missing `contracts` RPC on a full node.

- core/consensus/slots/src/lib.rs
If the user sees a warning about `block production took too long` and we detect the user has compiled their node with `debug` mode, suggest to them to instead compile with `--release` mode for computational optimizations which could remove problems with block production taking too long.
```
2019-09-17 13:02:46 Discarding proposal for slot 522906053; block production took too long
2019-09-17 13:02:46 Recompile your node in `--release` mode to mitigate this problem.
2019-09-17 13:02:47 Starting consensus session on top of parent 0x059e1fd59e4e4829eaa33e61696da472b79109056845767965afd14ccaa95f2a
```
> Suggest `--release` compilation

- core/consensus/slots/Cargo.toml
- core/consensus/slots/build.rs
- core/consensus/slots/src/lib.rs
`debug-assertions` can also be enabled in for release builds. This
introduces a new build-script that extracts the build type from the
`PROFILE` env variable and sets the `build_type` cfg.
> Properly detect debug build in slots

- .gitlab-ci.yml
this will enable the full pipeline for the `polkadot-v0.5` branch.
Reconsidering my question i think it will be useful to have binaries and docker images around.
> add polkadot-v0.5 branch to the ci

- Cargo.lock
- core/executor/Cargo.toml
- core/executor/src/wasm_runtimes_cache.rs
- core/sr-sandbox/Cargo.toml
- node/runtime/src/lib.rs
- srml/contracts/Cargo.toml
- srml/contracts/src/wasm/mod.rs
I updated the direct `parity-wasm` dependencies from `0.31` to `0.40`. This resolves #2517 (I think). There are still some indirect dependencies, see the output of `cargo tree -p parity-wasm:0.31.3 -i`.
I'm getting a few failed tests where the gas left is up by 1, but I'm not sure if these are really errors or not.
```
---- wasm::tests::contract_transfer stdout ----
thread 'wasm::tests::contract_transfer' panicked at 'assertion failed: `(left == right)`
left: `[TransferEntry { to: 9, value: 6, data: [1, 2, 3, 4], gas_left: 49971 }]`,
right: `[TransferEntry { to: 9, value: 6, data: [1, 2, 3, 4], gas_left: 49970 }]`', srml/contracts/src/wasm/mod.rs:468:3
```
> Update parity-wasm to 0.40

- README.adoc
- core/utils/wasm-builder/src/prerequisites.rs
Closes: https://github.com/paritytech/substrate/issues/3615
@akru could you check that the error message tells you to install `rust-lld` now? :)
> Make `wasm-builder` check for `rust-lld`

- Cargo.lock
- core/executor/runtime-test/Cargo.toml
- core/executor/runtime-test/build.rs
- core/test-runtime/Cargo.toml
- core/test-runtime/build.rs
- core/utils/wasm-builder/Cargo.toml
- core/utils/wasm-builder/README.md
- core/utils/wasm-builder/src/lib.rs
- core/utils/wasm-builder/src/wasm_project.rs
- node-template/runtime/Cargo.toml
- node-template/runtime/build.rs
- node/runtime/Cargo.toml
- node/runtime/build.rs
- srml/contracts/Cargo.toml
(GitHub won't let me reopen #3637 because I force-pushed, so I have to create another PR)
Removes the fact that the WASM builder requires the no_std feature.
The motivation behind this change is the surprise effect. Why do I need a no_std feature in my runtime?
Additionally, semantically it's not a great idea to have a "no_std" feature. People might misuse it because they think it means "opposite of std feature", while it is not that at all. There is a history in the Rust ecosystem of misusing features named "no_std", and we're giving out a bad example.
In practice, Polkadot doesn't use that feature, only the Substrate runtime does.
The only consequence might be that we have to activate features on "std" that we wouldn't normally need, which will result in a very slightly larger binary …
> Remove the no_std feature from the WASM builder

- core/primitives/src/crypto.rs
- subkey/src/cli.yml
- subkey/src/main.rs
- Adds Polkadot, Kusama, and Dothereum to the list of default parsable address formats.
- Sets the Dothereum address prefix to 20 in accordance with [External Address Format (SS58)](https://github.com/paritytech/substrate/wiki/External-Address-Format-(SS58)).
- Adds Dothereum to the list of supported networks for `subkey`.
- Fixes #3641
- Fixes https://github.com/paritytech/polkadot/issues/394
- Required for the next iteration of the Dothereum testnet config coming with a custom address format (validators).
- Ref https://github.com/dothereum/dothereum/pull/10
- Ref https://github.com/dothereum/dothereum/issues/7
- Partially addresses #3389, a follow-up could come up with a more …
> core, subkey: allow to read Polkadot, Kusama, and Dothereum address types

- node/executor/src/lib.rs
- node/runtime/src/lib.rs
- srml/contracts/COMPLEXITY.md
- srml/contracts/src/lib.rs
- srml/contracts/src/tests.rs
See #2828. I'm not sure how much of the documentation needs updating.
> srml-contract: Rename Contract::create to instantiate

- core/client/src/client.rs
- core/consensus/aura/src/lib.rs
- core/consensus/babe/primitives/src/digest.rs
- core/consensus/babe/primitives/src/lib.rs
- core/consensus/babe/src/aux_schema.rs
- core/consensus/babe/src/epoch_changes.rs
- core/consensus/babe/src/lib.rs
- core/consensus/babe/src/tests.rs
- core/consensus/common/src/block_import.rs
- core/consensus/common/src/import_queue.rs
- core/consensus/slots/src/lib.rs
- core/finality-grandpa/src/environment.rs
- core/finality-grandpa/src/import.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/test/mod.rs
- core/service/src/chain_ops.rs
- core/service/test/src/lib.rs
- core/test-runtime/src/lib.rs
- core/utils/fork-tree/src/lib.rs
- node-template/runtime/src/lib.rs
- node-template/src/service.rs
- node/cli/src/chain_spec.rs
- node/cli/src/service.rs
- node/runtime/src/lib.rs
This is the counterpart to the initial type-definition work done in #3611 on the core side.
Rough overview of changeset:
- Extract `SharedEpochChanges` logic out to its own module in a way that can be more cleanly tested
- Track chain total-weight offchain and handle it in the block-import worker
- Define epoch 0 as starting at block 1. There might be multiple block 1s, so they might all kick off slightly competing epochs.
- Allow epochs to change between blocks and grab epoch based on start slot as well as ancestry.
- Detect that the first block in an epoch is such by comparing the epoch start slot to the parent block's slot. The first block in an epoch must issue a `NextEpochDescriptor` about the following epoch.
- Does not define pruning of the epoch fork-tree at this point. That can …
> Fix BABE epochs-transition logic on the core side

- core/consensus/aura/src/lib.rs
- core/consensus/babe/src/lib.rs
- core/consensus/slots/src/lib.rs
#3158 
Rename confusing `import_block` function to `block_import_params`
> fn import_block -> fn block_import_params in SimpleSlotWorker

- Cargo.lock
- core/consensus/babe/primitives/src/digest.rs
- core/phragmen/benches/phragmen.rs
- core/sr-io/src/lib.rs
- core/sr-io/with_std.rs
- core/sr-io/without_std.rs
- core/sr-primitives/src/testing.rs
- node/cli/src/service.rs
- node/runtime/src/lib.rs
- srml/babe/Cargo.toml
- srml/babe/src/lib.rs
- srml/babe/src/mock.rs
- srml/babe/src/tests.rs
As requested by @rphmeier.  Based on #3305.
> BABE srml tests

- Cargo.lock
- core/basic-authorship/Cargo.toml
- core/cli/Cargo.toml
- core/client/Cargo.toml
- core/consensus/aura/Cargo.toml
- core/consensus/babe/Cargo.toml
- core/consensus/common/Cargo.toml
- core/consensus/common/src/import_queue/basic_queue.rs
- core/consensus/pow/Cargo.toml
- core/consensus/slots/Cargo.toml
- core/finality-grandpa/Cargo.toml
- core/network/Cargo.toml
- core/offchain/Cargo.toml
- core/peerset/Cargo.toml
- core/rpc/Cargo.toml
- core/rpc/api/Cargo.toml
- core/service/Cargo.toml
- core/telemetry/Cargo.toml
- core/test-client/Cargo.toml
- core/transaction-pool/graph/Cargo.toml
- node/cli/Cargo.toml
Now that https://github.com/rust-lang-nursery/futures-rs/pull/1750 has been merged and included in `futures-preview` version `0.3.0-alpha.18`, we can use `ThreadPool::spawn_ok()`, getting rid of a TODO in `core/consensus/common/src/import_queue/basic_queue.rs`.
I had to bump `futures-timer` from `v0.2.1 -> v0.3` in  order for `futures-preview` to play nice.
> Use `ThreadPool::spawn_ok()` instead of `ThreadPool::spawn()`

- core/client/src/client.rs
the code as currently written assumes that the canonical chain has a block with the number of the requested block, which isn't guaranteed in all fork-choice rules.
> find best_containing even if best chain is shorter

- core/service/src/builder.rs
During reorg, we should only submit signed extrinsics back to pool for retracted blocks. This avoids those error messages "Extrinsic invalid", because unsigned inherents will not pass `validate_transaction` check.
> Only submit signed extrinsics back to pool when retracting block

- node/runtime/src/lib.rs
- srml/contracts/COMPLEXITY.md
- srml/contracts/src/account_db.rs
- srml/contracts/src/exec.rs
- srml/contracts/src/lib.rs
- srml/contracts/src/tests.rs
- srml/contracts/src/wasm/mod.rs
- srml/contracts/src/wasm/runtime.rs
Closes #3645
See #3645. I've tried to have 'instantiation' refer specifically to contracts while 'creation' refer to accounts. This gets a little tricky when you're talking about smart contract accounts, so I've kept lines like:
```
srml/contracts/src/lib.rs
392:	/// The fee required to create an account.
393:	type CreationFee: Get<BalanceOf<Self>>;
423:/// and the account id that requested the account creation.
491:		/// The fee required to create an account.
492:		const CreationFee: BalanceOf<T> = T::CreationFee::get();
568:		/// a regular account will be created and any value will be transferred.
589:		/// - The smart-contract account is created at the computed address.
590:		/// - The `ctor_code` is executed in the context of the newly-created account. Buffer returned
681:				// We …
```
> Rename more things related to contract instantiation

- core/executor/src/allocator.rs
- core/executor/src/sandbox.rs
- core/executor/src/wasm_executor.rs
- node/executor/src/lib.rs
These are some refactors to ease the integration of a compiled Wasm executor. This decouples the memory allocator and sandbox from wasmi. In the case of the sandbox, sandboxed environments will still execute with wasmi in the near future, so the decoupling is just on the supervisor side. (The supervisor is the substrate runtime, which handles external calls from the sandboxed runtime).
With the allocator, it no longer relies on dynamic borrows (which the `wasmi::MemoryRef` does under the hood), and instead gets a reference to the runtime memory on each `allocate` and `deallocate` call.
> Decouple node-executor structures from wasmi

- core/finality-grandpa/src/aux_schema.rs
- core/finality-grandpa/src/lib.rs
The authority id was previously sent to telemetry, but removed as part of the [key management refactoring](https://github.com/paritytech/substrate/commit/ed61b1fd98010b85d508bdd17867bf6bfb5cfee7#diff-16b4c34d50bdfcbf732c09c7be1fdcf9L468). It is needed for the consensus visualization.
The corresponding telemetry PR is https://github.com/paritytech/substrate-telemetry/pull/179.
> Send local GRANDPA authority id to telemetry

- Cargo.lock
- core/consensus/babe/Cargo.toml
- core/consensus/babe/src/lib.rs
This would resolve #2926, but `median_algorithm` isn't currently used. I haven't written a test yet, but I'd like to if it's important enough.
> use pdqselect for median_algorithm selection

- node/runtime/src/lib.rs
- srml/support/procedural/src/storage/impls.rs
- srml/support/src/storage/generator/linked_map.rs
- srml/support/src/storage/storage_items.rs
- srml/support/test/tests/final_keys.rs
in https://github.com/paritytech/substrate/pull/3344 I wrongly change the specification of linkedmap
before the key of the head of the linkedmap was stored at `$hash("head of " ++ module_name ++ " " ++ storoagename)` and after it was stored at `"head of " ++ module_name ++ " " ++ storoagename`.
Fix PR Fixes it.
> Fix head not hashed

- core/phragmen/src/lib.rs
- node/runtime/src/lib.rs
- srml/staking/src/lib.rs
Apparently I assumed at the time return from closure is the same as break 🤦🏻‍♂️
> Fix Phragmen equalize loop.

- node/runtime/src/lib.rs
- srml/support/procedural/src/storage/transformation.rs
- srml/support/test/tests/final_keys.rs
Currently the head of a linked map for an instantiable module is put at: "Instance0head of MyModule MyStorage" instead of "head of Instance0MyModule MyStorage"
from the metadata user have the module name `Instance0MyModule` and the storage name `MyStorage` so he can't really get the head of the linkedmap.
I think this is a bug. fortunately there is no linked_map in instantiable module in substrate nor polkadot.
* fix the head key for instantiable module
* make test to test instantiable module with default instance and instance2
> Fix linkedmap instance head of

- srml/support/procedural/src/lib.rs
- srml/support/src/storage/generator/double_map.rs
- srml/support/src/storage/generator/linked_map.rs
- srml/support/src/storage/generator/map.rs
- srml/support/src/storage/generator/value.rs
* specification of how keys are inserted into storages are moved into generator docs
* decl_storage is more small and link to generator doc when necessary
* maybe we should make the specification compiling, but all of this is tested in srml/support/test/test/final_keys.rs
> Improve storage doc

- core/finality-grandpa/src/lib.rs
When starting a new GRANDPA voter we send a message to telemetry with the set id and the node name. In this PR we also add the local authority id (if any) to the message. This was requested by a user on riot so that we have one single message where it's possible to associate an authority id with a node name.
> grandpa: send authority id to telemetry when starting new voter

- core/executor/src/wasm_executor.rs
Instead, use `Debug` for `debug_trace!`
> Pointer does not implement Display

- Cargo.lock
- core/executor/Cargo.toml
- core/sr-io/Cargo.toml
- node/runtime/src/lib.rs
This supposedly removes some duplicated dependencies of such as sha2. Note that currently `libp2p-core` still depends on `0.2`, and we need https://github.com/libp2p/rust-libp2p/pull/1258 to completely remove that.
> Update libsecp256k1 dep to 0.3.0

- core/cli/src/params.rs
Yesterday I learned that structopt makes a distinction between short and long parameter descriptions (`-h` vs `--help`). The distinction is made by adding an empty line in the middle of the parameter docs so I cleaned up some of the parameters with longer descriptions. I also made sure all descriptions were terminated with a dot (because OCD).
> cli: clean up flag descriptions

- Cargo.lock
- Cargo.toml
- core/sr-api-macros/Cargo.toml
The protobuf crate introduced a breaking change within its semver minor
update from 2.8.1 to 2.9.0. This commit ensures Substrate uses anything
within the 2.8 minor releases.
> core/sr-api-macros/Cargo.toml: Pin protobuf version

- Cargo.lock
- core/sr-api-macros/Cargo.toml
Reverts paritytech/substrate#3723
https://github.com/stepancheg/rust-protobuf/issues/453 was fixed, so we can revert this hack before it gets forgotten.
> Revert "core/sr-api-macros/Cargo.toml: Pin protobuf version"

- node/runtime/src/lib.rs
- srml/im-online/src/lib.rs
- srml/im-online/src/tests.rs
All of the heartbeat messages that were received at session `n` should be pruned after they have been processed and the session ends. Currently this was done on `on_new_session` but it was removing messages for the session that had just started and not the previous one. I moved this to `on_before_session_ending` so that we remove the messages right after they've been processed, also added a test for this.
This is the reason for the current flaming fir stall, since the double map is currently filled with all messages that were received in all session, the heartbeat extrinsic takes too long to execute and hence block production takes too long as well.
> srml: im-online: fix received heartbeats pruning

- Cargo.lock
- core/consensus/aura/Cargo.toml
- core/consensus/aura/src/lib.rs
See #2688. Currently, Aura (and other consensus crates, I'll get round to those later) use `String`s for error handling. This PR replaces those `String`s with an `Error`. Currently, these errors have to be cast to `String`s for the `Verifier` trait: https://github.com/paritytech/substrate/blob/759ecfcaad312a8325b135761f7b4720dda96bc0/core/consensus/common/src/import_queue.rs#L72-L83
This is something that we should look into changing.
> Add an Error type to Aura

- node/runtime/src/lib.rs
- srml/system/src/lib.rs
Add a `kill_prefix` extrinsic to system. This is useful to manually cleanup storage from double maps (needed as a result of #3724 but should be useful in general).
> srml: system: add kill_prefix

- srml/sudo/src/lib.rs
- srml/support/src/runtime.rs
So, instead of:
`type ALL_MODULES = (Module1, Module2, Module3)`;
Generate it like this:
`type ALL_MODULES = ((Module1, Module2), Module3,);`
This should make `construct_runtime!` support an "unlimited" number of
modules.
> Let `construct_runtime!` generate `ALL_MODULES` as nested tuples

- core/finality-grandpa/src/environment.rs
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/until_imported.rs
The `UntilImported` stream abstracts the logic of withholding messages until the blocks that they refer to are imported. This is used for both round and global messages with different underlying streams. This PR adds a string identifier to `UntilImported` which is used when logging what hashes we are waiting on, this is useful to be able to distinguish whether it is a round message (i.e. a vote) or a global message (a commit or a catch-up).
> grandpa: add identifier to UntilImported logging message

- core/consensus/babe/src/tests.rs
- srml/authority-discovery/src/lib.rs
- srml/generic-asset/src/lib.rs
- srml/scored-pool/src/lib.rs
- srml/staking/src/mock.rs
- srml/support/src/storage/storage_items.rs
Removes some unused imports that gave warnings when compiling `substrate`.
Plus there's a comment in `srml/support/src/storage/storage_items.rs` that refers to three data types being supported where it seems to be just two: `StorageValue` and `StorageMap`.
> Remove unused imports

- Cargo.lock
- Cargo.toml
- core/authority-discovery/src/lib.rs
- core/cli/Cargo.toml
- core/cli/src/informant.rs
- core/client/Cargo.toml
- core/client/db/Cargo.toml
- core/client/db/src/lib.rs
- core/client/db/src/light.rs
- core/client/header-metadata/Cargo.toml
- core/client/header-metadata/src/lib.rs
- core/client/src/blockchain.rs
- core/client/src/client.rs
- core/client/src/in_mem.rs
- core/client/src/light/blockchain.rs
- core/consensus/babe/Cargo.toml
- core/consensus/babe/src/epoch_changes.rs
- core/consensus/babe/src/lib.rs
- core/finality-grandpa/Cargo.toml
- core/finality-grandpa/src/environment.rs
- core/network/Cargo.toml
- core/network/src/chain.rs
- core/test-client/src/lib.rs
- core/test-runtime/client/src/lib.rs
Fixes #3592
This PR removes some inefficiencies of `tree_route` and calling functions. Previously, `tree_route` was computing the path between two blocks by loading headers from database. Now, we cache the information needed in an LRU cache in-memory. 
Also, many times we were using `tree_route` just to check if a block is descendant of another one. Instead, this PR introduces a function `lowest_common_ancestor` that compute descendants in `O(1)` (most of the time).
As a side effect, this improves syncing speed for Kusama from ~2 hours to ~20 minutes (25 bps -> 35 bps in wasm, 80 bps -> 400 bps in native).
- Introduce a `CachedHeaderMetadata` with fields hash, number, parent and ancestor. The `ancestor` field is used to quickly jump through the tree. 
- We cache the last `20_000 …
> Optimize tree route to sync faster

- .gitlab-ci.yml
- rustdoc-header.html
Add customized header in rustdocs to enable google analytics, related issued: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/227
> Enable google analytics.

- core/consensus/babe/src/epoch_changes.rs
- core/consensus/babe/src/lib.rs
- core/consensus/babe/src/tests.rs
- core/utils/fork-tree/src/lib.rs
Currently as we observe BABE epoch changes we track them in a fork tree which keeps growing indefinitely as the chain grows. Since we have finality, after a given block is finalized we know that the chain will not revert past that point and therefore we can prune the tree out of epochs that could not be live at the finalized block (i.e. epochs from other forks, and epochs on the canonical chain for which `epoch.end_slot() <= finalized_slot`). The implementation is rather simple since we just use `find_node_where` to find the deepest ancestor of the finalized block that passes the given predicate, and if found we re-root the tree to it.
I built polkadot with this patch using the database of one of the validators which was filled with ancient forks. The tree was pruned correctly and import …
> babe: ancient epoch tree pruning

- core/consensus/babe/src/lib.rs
- core/consensus/babe/src/tests.rs
- core/utils/fork-tree/src/lib.rs
After merging #3746 with master that contained #3658, we ended up with a compilation error due to a change in `find_pre_digest` signature.
I also included a suggestion that @rphmeier gave in #3746's review.
> babe: small compilation fix

- core/client/db/src/lib.rs
- core/client/db/src/light.rs
- core/client/src/in_mem.rs
- core/consensus/babe/src/lib.rs
`header_metadata` is more efficient and specific that `header` and therefore should be used whenever possible
> Use header metadata in babe verify.

- core/consensus/babe/src/lib.rs
This isn't entirely necessary, but since we didn't use to prune the epoch tree it is useful as a migration, so that nodes prune long trees on startup rather than waiting until importing the next epoch change block (which can take a while with degraded performance).
> babe: prune the epoch tree on startup

- Dockerfile
Fixes #3731
The error `apt-get upgrade` is giving is due to not having `-o Dpkg::Options::="--force-confold"` to keep existing configurations. It is recommended by the Phusion docs to include this when doing an upgrade in a Dockerfile: https://github.com/phusion/passenger-docker#upgrading_os
Tested the build locally after updating `Dockerfile` and the error no longer occurs and image builds successfully.
> Fix docker builds #3731

- core/client/db/src/lib.rs
- core/client/header-metadata/src/lib.rs
Fix for regression introduced in #3665. The result of `tree_route` would be erroneously computed since it was taking into account the `ancestor` in `CachedHeaderMetadata` for the comparison.
I removed the `Eq` and `PartialEq` from `CachedHeaderMetadata` to avoid any similar issues from being introduced, I also added a test that fails without this fix.
> client: fix comparison of CachedHeaderMetadata in tree_route

- node/runtime/src/lib.rs
- srml/metadata/src/lib.rs
- srml/support/src/dispatch.rs
- srml/support/src/error.rs
- srml/support/src/metadata.rs
- srml/support/test/tests/system.rs
Closes #2954 
This introduces Metadata V8 cc @jacogr
> expose module errors into metadata

- Cargo.lock
- srml/bridge/Cargo.toml
- srml/bridge/src/error.rs
- srml/bridge/src/lib.rs
- srml/bridge/src/storage_proof.rs
> Logic for checking Substrate proofs from within runtime module.

- node-template/runtime/src/lib.rs
- node/runtime/src/lib.rs
- srml/contracts/Cargo.toml
- srml/contracts/src/exec.rs
- srml/contracts/src/lib.rs
- srml/contracts/src/tests.rs
- srml/randomness-collective-flip/src/lib.rs
- srml/support/src/traits.rs
Decouple randomness-collective-flip and other modules
> Decouple randomness-collective-flip

- core/sr-primitives/src/traits.rs
- srml/system/src/lib.rs
Signed-off-by: yjhmelody <465402634@qq.com>
> fix comments

- core/executor/runtime-test/src/lib.rs
- core/executor/src/sandbox.rs
- core/executor/src/wasmi_execution.rs
- core/primitives/src/lib.rs
- core/primitives/src/testing.rs
The macro generates the functions with the signature we expect for wasm
functions. This macro is useful for tests where we need to call into
wasm. Parameter passing is done by SCALE encoding the input and output
parameters.
CC @lamafab
> Provide macro for exporting functions from wasm

- core/rpc/api/src/subscriptions.rs
- core/rpc/src/author/mod.rs
- core/rpc/src/author/tests.rs
- core/transaction-pool/graph/src/pool.rs
Before #3650 the transactions were imported to the pool in a synchronous manner,. Because of that it was simple for `submit_and_watch_extrinsic` subscription to return an error if the transaction was rejected, instead of starting the subscription.
The async refactoring missed one case that handles the asynchronous verification in the pool - errors in that verification only lead to a warning and the subscription was started anyway, but never produced any message.
This PR fixes this behavior. CC @jacogr
> Fix asynchronous transaction rejections.

- core/client/src/client.rs
- core/sr-primitives/src/generic/block.rs
- core/sr-primitives/src/testing.rs
- core/sr-primitives/src/traits.rs
- node/runtime/src/lib.rs
Fixes #1536.
_WARNING_: day 3 Rust developer and total Substrate newbie here, plus the proposed solution is surprisingly simple so it is entirely possible that, at this stage, this is just mindless babbling; I apologize in advance if that turns out to be the case.
This proposal follows from the fact that SCALE [encodes tuples and structs in the same way](https://substrate.dev/docs/en/overview/low-level-data-format#tuples-and-structures) and [`parity-scale-codec`](https://github.com/paritytech/parity-scale-codec) seems to [support tuple encoding](https://github.com/paritytech/parity-scale-codec/blob/4a559de5f6fece90205a159e008b86304d4c8750/src/codec.rs#L812).
Concretely I added an `encode_from(&header, &extrinsics) -> Vec<u8>` function to the `Block` trait and straightforwardly implemented …
> Fix #1536: do not require to construct a block for encoding it

- core/rpc/api/src/system/helpers.rs
- core/rpc/api/src/system/mod.rs
- core/rpc/src/system/mod.rs
- core/rpc/src/system/tests.rs
- core/service/src/lib.rs
(Sort-of) closes #1941. It currently doesn't get the authority ID (I might need a few pointers as for how to connect that up), and the way it figures out node roles is a little hacky.
> WIP: Node role RPC call

- core/finality-grandpa/src/communication/gossip.rs
- core/finality-grandpa/src/communication/tests.rs
The GRANDPA gossip validator uses mainly two storage items to validate/expire messages: a topic tracker with hashes of the topics we're interested in, and a local view of the GRANDPA state (round and set number). When validating whether to accept a gossip message or not we check our round in the local view, and we accept messages for `R-1`, `R` and `R+1`. When checking whether a message is expired (or whether it is allowed to send to a given peer), we check whether the topic for that message is live in our topic tracker. The issue is that the topic tracker is currently only tracking topics `R, R-1, ..., R - KEEP_RECENT_ROUNDS`, and the next round topic isn't tracked there. This means that we can accept messages for the next round and subsequently expire them before processing them. In …
> grandpa: don't expire next round messages

- Cargo.lock
- srml/contracts/rpc/Cargo.toml
- srml/contracts/rpc/src/lib.rs
Switch to using Bytes for CallRequest.input_data in place of Vec<u8> for easier UI interaction
> Use Bytes for contract rpc input_data

- core/network/src/protocol.rs
- core/network/src/protocol/sync.rs
- core/network/src/test/mod.rs
- core/network/src/test/sync.rs
Currently block announcements may be ignored occasionally. This PR changes handling announcements in the same way as explicit sync requests.
> Persist block announcements

- core/sr-std/without_std.rs
- core/utils/wasm-builder/src/prerequisites.rs
- node/runtime/src/lib.rs
By relaxing some checks we can easily make the build work using Debian's system rustc (which I maintain), avoiding having to install rustc nightly:
~~~~
$ apt install rustc libstd-rust-dev-wasm32-cross libssl-dev
$ RUSTC_BOOTSTRAP=1 cargo build
[..]
Compiling transaction-factory v0.0.1 ($PWD/test-utils/transaction-factory)
Finished dev [unoptimized + debuginfo] target(s) in 11m 07s
~~~~
> Make build work with rustc 1.37 stable and RUSTC_BOOTSTRAP=1

- core/client/db/src/cache/mod.rs
- core/consensus/babe/primitives/src/digest.rs
- core/consensus/babe/src/aux_schema.rs
- core/consensus/slots/src/aux_schema.rs
- core/consensus/slots/src/lib.rs
- core/finality-grandpa/src/lib.rs
- core/primitives/src/ed25519.rs
- core/primitives/src/sr25519.rs
- core/rpc-servers/src/lib.rs
- core/service/src/chain_ops.rs
- srml/support/src/hash.rs
- srml/support/src/traits.rs
- srml/system/src/lib.rs
Compliance with all default hard errors and crates that are explicitly
using `#![deny(warnings)]`.
There are some legitimate warnings like `println!("")` -> `println!()` but
they aren't considered in this PR.
> It's Clippy time!

- core/offchain/src/api.rs
Bump the submission error from `debug` to `warn`
> Improve logging for offchain transaction submission.

- core/primitives/src/lib.rs
Signed-off-by: yjhmelody <465402634@qq.com>
> refactor map macro for more general use

- node/executor/src/lib.rs
- node/runtime/src/impls.rs
- node/runtime/src/lib.rs
Builds on top of https://github.com/paritytech/substrate/pull/3823 but has _both_ desirable properties:
* All constants declared in `parameter_types!` are used as associated types with `get`
* All transaction fee calculation constants are in one place
@kianenigma and I had both previously wanted to use an _instance_ of a struct to calculate weight fees because we could give it a field to represent the slope. But `transaction_payment::Trait` requires an associated _type_. Generating a type when you really want a constant is exactly what `parameter_types!` is for. The solution is to make the fee:weight ratio itself a type parameter for the struct as I've done here.
> Price to Weight ratio as type parameter

- core/cli/src/lib.rs
- core/cli/src/params.rs
Currently GRANDPA needs to import all blocks that are voted on, and therefore requires to have state available for those blocks. During periods of long finality stalls we run the risk of state being pruned due to depth (we prune after 4096 blocks regardless of finality), or e.g. a short-lived fork being pruned out. This PR changes the default pruning mode to be set to archive if the node is a validator, otherwise it defaults to keeping state for the last 256 blocks. The node will refuse to start if the node is a validator and pruning is enabled, unless the flag `--unsafe-pruning` is given as well.
Currently the node doesn't seem to detect whether the existing database is an archive or pruned. This means that if you start with a pruned database, and restart the node as archive, the node …
> cli: disable pruning on validators

- srml/assets/Cargo.toml
Fixes: https://github.com/paritytech/substrate/issues/3889
> Fix srml assets compilation with `std` feature

- Cargo.lock
- core/executor/runtime-test/Cargo.toml
- core/test-runtime/Cargo.toml
- core/utils/wasm-builder-runner/Cargo.toml
- core/utils/wasm-builder-runner/src/lib.rs
- node-template/runtime/Cargo.toml
- node/runtime/Cargo.toml
`CARGO_TARGET_DIR` needs to be unset or otherwise cargo deadlocks,
because cargo always holds an exclusive lock on target dir.
> Wasm-builder-runner unset `CARGO_TARGET_DIR` and release 1.0.4

- Cargo.lock
- node/cli/src/chain_spec.rs
- node/primitives/src/lib.rs
- node/runtime/Cargo.toml
- node/runtime/src/lib.rs
- node/testing/src/genesis.rs
- srml/elections-phragmen/src/lib.rs
I seem to have forgotten to include `rstd::prelude` 
- also include it in `substrate-node`
- also remove a very ambiguous type def (we basically had `type UncheckedExtrinsic` defined twice). For the future I prefer and recommend moving all of the `type Extra`, `Type Extrinsic` etc. form node-runtime to node-primitives).
> Fix phragmen election to wasm 

- core/cli/src/lib.rs
- core/cli/src/params.rs
- core/network/Cargo.toml
- core/network/src/config.rs
- core/network/src/lib.rs
- core/network/src/service.rs
We've deprecated secp256k1 keys and defaulted to ed25519 keys a long time ago. This PR removes support for secp256k1.
Note that we still support situations where a remote node supports secp256k1 keys. This only removes support for using a secp256k1 key on your local node.
I wasn't sure whether to keep the infrastructure for `--node-key-type` or if this should be removed altogether. For now I kept it.
> Remove support for secp256k1 for network keys

- Cargo.lock
- core/cli/src/informant.rs
- core/service/Cargo.toml
- core/service/src/builder.rs
- core/service/src/lib.rs
- core/service/src/status_sinks.rs
Fix #3541 
Two changes:
- The `network_state()` method on the `AbstractService` trait now takes a `Duration` for the interval at which the state should be reported. This is IMO a more sensible design, as it allows the informant to decide how often it should be displayed.
- Splits the `"system.interval"` telemetry report in two: the `"system.interval"` report no longer contains the `"network_state"` field. Instead, there's a new `"system.network_state"` message that contains a single field named `"state"`. This new message is sent only every 30 seconds.
The telemetry backend should obviously be updated accordingly. cc @maciejhirsz
> Split the telemetry net status report in two

- node-template/src/service.rs
- node/cli/src/service.rs
This used to be correctly spawned as an essential task but was changed back in #3382 (probably when handling merge conflicts).
> node: spawn grandpa voter as essential task

- node-template/src/service.rs
Tasks spawned by `spawn_task`/`spawn_essential_task` are already guarded by `on_exit`.
> node-template: remove unnecessary on_exit guard

- core/sr-primitives/src/generic/unchecked_extrinsic.rs
Update the transaction version after #3861 since the over-the-wire formats between the current and the previous v3 are not compatible.
> Bump transaction version

- node/cli/src/chain_spec.rs
- node/runtime/src/lib.rs
- node/testing/src/genesis.rs
- srml/treasury/src/lib.rs
Fix https://github.com/paritytech/substrate/issues/3879
Superseed https://github.com/paritytech/substrate/pull/3797
* treasury account is created at genesis config.
* pot doesn't include existential deposit thus pot can be entirely spend with no issue.
* we could also keep old behavior with treasury being created when it happens that dilution is more than ED. but seem better that we create it once and for all.
* I still kept resolve_creating to ensure it still works on Kusama if there is no treasury account then it will just get created once on_dilution mint more than ED instead of never be created.
Also in case someone forget to include Config in construct runtime (thus account is not created) then this account can be created later as well.
> Fix treasury kept and spend when emptied

- node-template/Cargo.toml
- node-template/src/chain_spec.rs
- node-template/src/service.rs
This PR makes an insubstantial change to how the node-template imports it's runtime. In Cargo.toml
```diff
- node-template-runtime = { path = "runtime" }
+ runtime = { package = "node-template-runtime", path = "runtime" }
```
While small, this change has two positive effects downstream.
1. When a developer starts a project from the node template, and later choose to rename it, they change the name in fewer places. (They no longer have to touch `service.rs` at all.)
2. When changing the template to use a runtime from an external crate (as is done in [recipes](https://github.com/substrate-developer-hub/recipes/blob/ec8c53d01f1888bbb50b3acc466f2f2967c4b663/kitchen/node/Cargo.toml#L37-L40) and [joystream](https://github.com/Joystream/substrate-node-joystream/blob/master/Cargo.toml#L47)), they …
> Rename node template's runtime dependency "node-template-runtime" -> "runtime"

- core/chain-spec/src/chain_spec.rs
- core/sr-primitives/src/lib.rs
- node/runtime/src/lib.rs
- srml/support/procedural/src/storage/genesis_config/builder_def.rs
- srml/support/procedural/src/storage/genesis_config/mod.rs
There is no reason to consume the GenesisConfig when using it to initialize a new storage backend. Instead, build_storage and assimilate_storage now operator on self references.
The motivation is benchmarks that need to repeatedly initialize new storage backends. It would be nice to do so without rebuilding the config each time (which involves key generation).
> support: BuildStorage methods to take self reference

- core/finality-grandpa/src/communication/mod.rs
- core/finality-grandpa/src/import.rs
- core/finality-grandpa/src/justification.rs
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/tests.rs
Currently `GrandpaBlockImport` only tries to import justifications for blocks that it needs to (i.e. authority set change blocks), even if a justification is available it is discarded. 
This means that during sync, on a network with no authority set changes there are long periods of unfinalized blocks, since we are discarding any available justification. On a PoS network this should not be an issue as there regular authority set changes.
This PR makes it so it always tries to import the block justification if it is available.
> grandpa: always try to import available block justifcation

- Cargo.lock
- node-template/Cargo.toml
- node-template/runtime/src/lib.rs
- node-template/src/chain_spec.rs
- node-template/src/service.rs
- node/cli/src/chain_spec.rs
Use MultiSignature to maintain compatibility with substrate-node. The extrinsic version is hardcoded to 4 on unchecked_extrinsic which the frontend expects MultiSiganture but the Signature type was not changed for node-template.
Reset version to 1. It doesn't make sense for a new project to start version from 4.
Remove unused const
> Fix node-template

- Cargo.lock
- core/rpc-servers/Cargo.toml
- core/rpc/Cargo.toml
- core/rpc/api/Cargo.toml
- core/rpc/api/src/author/mod.rs
- core/rpc/src/author/mod.rs
- core/rpc/src/author/tests.rs
- core/transaction-pool/graph/src/pool.rs
- core/transaction-pool/graph/src/validated_pool.rs
- core/transaction-pool/graph/src/watcher.rs
- node/cli/Cargo.toml
- node/rpc-client/Cargo.toml
- node/rpc/Cargo.toml
- srml/contracts/rpc/Cargo.toml
- srml/system/rpc/Cargo.toml
not sure about naming though @tomusdrw
> Watch existing extrinsics RPC

- Cargo.lock
- core/rpc-servers/Cargo.toml
- core/rpc/Cargo.toml
- core/rpc/api/Cargo.toml
- core/rpc/api/src/author/mod.rs
- core/rpc/src/author/mod.rs
- core/rpc/src/author/tests.rs
- core/transaction-pool/graph/src/pool.rs
- core/transaction-pool/graph/src/validated_pool.rs
- core/transaction-pool/graph/src/watcher.rs
- node/cli/Cargo.toml
- node/rpc-client/Cargo.toml
- node/rpc/Cargo.toml
- srml/contracts/rpc/Cargo.toml
- srml/system/rpc/Cargo.toml
Reverts paritytech/substrate#3873
> Revert "Watch existing extrinsics RPC"

- srml/assets/src/lib.rs
Change `less than` to be `more than` to reflect the test purpose.
> Fix test description.

- core/primitives/src/sr25519.rs
- node/runtime/src/lib.rs
- srml/balances/src/lib.rs
- srml/contracts/src/exec.rs
- srml/contracts/src/gas.rs
- srml/contracts/src/rent.rs
- srml/elections-phragmen/src/lib.rs
- srml/elections/src/lib.rs
- srml/generic-asset/src/lib.rs
- srml/support/src/traits.rs
- srml/transaction-payment/src/lib.rs
- srml/treasury/src/lib.rs
Several subsystems (staking, elections-phragmen) routinely introduce account locks. Though account locks are able to cover only a subset of funds, allowing there to be unlocked funds to do stuff like sending new transactions, often times it's easy to accidentally lock all funds in the account, preventing all further activity until the account is topped up with fresh, unlocked funds.
This introduces a new kind of `WithdrawReason`: `Tip`, which allows us to distinguish between transaction payment that goes primarily to the system `::TransactionPayment` and transaction payment that goes primarily to a validator `::Tip`. By doing this we can allow transactions to draw down on locked funds if all funds are exclusively used for `::TransactionPayment` and not `::Tip`, thereby removing the …
> Tip payment is a different withdraw reason.

- core/network/src/behaviour.rs
There is a limit of 30 external addresses a node can have. This warning is printed when a node sends us more than 30 addresses. In practice, it is printed when we connect to a node with a very old version of Polkadot.
It turns out that it is printed quite often, and it isn't a very useful information, so let's turn it into a `debug!` instead.
> Too many addresses for a node is now a debug! rather than warn!

- core/phragmen/src/lib.rs
- core/sr-primitives/src/weights.rs
- node/cli/src/chain_spec.rs
- node/runtime/src/lib.rs
- node/testing/src/genesis.rs
- srml/elections-phragmen/src/lib.rs
- srml/example/src/lib.rs
- srml/staking/src/lib.rs
- srml/system/src/lib.rs
- srml/transaction-payment/src/lib.rs
- some leftover doc updates for weights (related to the ongoing doc PR)
- storage -> associated type for elections
- Store the equivalent of `exposure.total` in elections as well. if executed according to the plan, no logic has changed.
needless to say, needs to be taken into account in the next polkadot update.
> Updates to elections-phragmen and some runtime docs. 

- Cargo.lock
- core/application-crypto/src/ed25519.rs
- core/application-crypto/src/sr25519.rs
- core/application-crypto/src/traits.rs
- core/sr-primitives/src/lib.rs
- core/sr-primitives/src/testing.rs
- core/sr-primitives/src/traits.rs
- core/test-runtime/src/lib.rs
- node-template/runtime/src/lib.rs
- node/runtime/src/lib.rs
- srml/aura/src/lib.rs
- srml/authority-discovery/src/lib.rs
- srml/babe/src/lib.rs
- srml/babe/src/mock.rs
- srml/grandpa/src/lib.rs
- srml/im-online/src/lib.rs
- srml/session/Cargo.toml
- srml/session/src/historical.rs
- srml/session/src/lib.rs
- srml/session/src/mock.rs
- srml/staking/src/mock.rs
- `OpaqueKeys` now has an associated type `KeyTypeIdProviders`. This can
be used in the runtime as input for `SessionHandler` from the session
trait.
- `impl_opaque_keys` now works with modules and extracts the `KeyTypeId`
from the module directly.
- Added some checks to the `session` storage initialization that checks
that the `SessionHandler` and `Keys` use the same number of keys and
that the order is equal.
> Remove footgun around session keys/handlers

- core/finality-grandpa/src/communication/gossip.rs
- core/finality-grandpa/src/communication/mod.rs
- core/finality-grandpa/src/communication/tests.rs
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/observer.rs
- core/finality-grandpa/src/tests.rs
- node-template/src/service.rs
- node/cli/src/service.rs
GRANDPA has a protocol for requesting data from its peers in order to catch up to the latest round. Currently, we restrict these requests to other authorities, assuming that non-authorities are running the GRANDPA observer protocol which does not have the data available to answer catch up requests.
With the current setup for sentry nodes, the validator is only connected to non-authority nodes (the sentries), and therefore if it ever gets behind on the round it cannot issue catch-up requests to anyone. Also, the assumption that only authorities can answer catch-up requests may be incorrect depending on the network service setup.
This PR makes this configurable, so that on Kusama where the GRANDPA observer protocol isn't currently enabled, we can issue catch-up requests to all full nodes …
> grandpa: fix handling of catch-up requests

- core/cli/src/lib.rs
- core/cli/src/params.rs
- core/service/src/config.rs
- core/service/test/src/lib.rs
- node-template/src/cli.rs
- node-template/src/service.rs
- node/cli/src/lib.rs
- node/cli/src/service.rs
This PR adds a `--sentry` flag to the node. The node is started as a validator (i.e. authority role, pruning restrictions, runs full GRANDPA protocol, etc.), but no keystore is passed to any consensus module so that the node **cannot** actively participate in it.
> node: add sentry mode flag

- Cargo.lock
- core/primitives/Cargo.toml
- core/primitives/storage/Cargo.toml
- core/sr-version/Cargo.toml
To fix this in Substrate: https://github.com/paritytech/substrate/issues/3946
> Upgrade `impl-serde` to `0.2.3`

- test-utils/chain-spec-builder/Cargo.toml
- test-utils/chain-spec-builder/build.rs
- test-utils/chain-spec-builder/src/main.rs
One should use the chain spec builder test util in `--release` mode to produce a proper chain specification. This pull requests makes the builder print a warning whenever not run in `--release` mode.
> test-utils/chain-spec-builder: Add note to run builder in release mode

- core/client/src/client.rs
> Remove deprecated `Client::backend`

- .gitlab-ci.yml
- core/offchain/Cargo.toml
- core/offchain/src/api.rs
- core/offchain/src/api/http_dummy.rs
cc #2416
When compiling for an unknown OS, we use a dummy non-working implementation of HTTP instead of hyper.
This dummy implementation always fails to create an HTTP request.
> Make substrate-offchain compile for WASM again

- .gitlab-ci.yml
- core/chain-spec/Cargo.toml
- core/chain-spec/src/extension.rs
- core/chain-spec/src/lib.rs
Compiling the `substrate-chain-spec` crate for WASM triggers an ICE at the moment.
See https://github.com/rust-lang/rust/issues/65971
The ICE is caused by renaming `substrate-chain-spec-derive` to `chain-spec-derive`.
This PR bypasses this issue by not renaming.
> Fix compiling substrate-chain-spec for WASM

- node/runtime/src/lib.rs
- srml/im-online/src/lib.rs
Currently the `priority` is set to `0` which means it has the lowest possible value in the transaction pool.
We have a notion of `Operational` transactions (`DispatchClass`), however it only applies to transactions with `CheckWeight` `SignedExtension`. Since heartbeat is actually an `UnsignedTransaction` it's currently not using this mechanism (see #3419)
> Increase priority of ImOnline heartbeats

- core/network/src/protocol.rs
- core/network/src/protocol/specialization.rs
- core/network/src/service.rs
- core/network/src/test/mod.rs
Some refactoring/clean-up.
Calling `NetworkSpecialization::on_event` was initially the way that we had planned to receive DHT events.
However the `NetworkWorker` will now generate these DHT events on its stream output, and these events can be made accessible by passing a channel when building the `Service` (using `with_dht_event_tx` method).
This PR consequently deprecates `on_event`, with the intent of removing it in the not-so-far future.
I don't think Polkadot needs DHT events, but if there's ever a need for them that isn't satisfied with `with_dht_event_tx`, we can always revisit this.
> Remove NetworkSpecialization::on_event

- core/service/src/builder.rs
- node/cli/src/service.rs
Some RPC functions need to access backend (for e.g. to store info or communicate with the offchain worker). The proper way to do that now is holding a reference during setup phase - this PR exposes the backend-reference to the rpc_extension-builder function.
Probably needs an update in polkadot as well. Investigating and will follow asap.
> Expose backend to rpc builder

- srml/support/src/storage/mod.rs
As implementation of storages abstraction are made by generator, I think it worth link to it in the doc so people can know the implementation.
> Improve doc for storages in srml-support

- Cargo.lock
- core/finality-grandpa/primitives/Cargo.toml
- core/finality-grandpa/primitives/src/lib.rs
- core/finality-grandpa/src/authorities.rs
- core/finality-grandpa/src/aux_schema.rs
- core/finality-grandpa/src/communication/tests.rs
- core/finality-grandpa/src/finality_proof.rs
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/light_import.rs
- core/finality-grandpa/src/tests.rs
- node-template/runtime/src/lib.rs
- node-template/src/service.rs
- node/cli/src/service.rs
- node/runtime/src/lib.rs
- srml/grandpa/Cargo.toml
- srml/grandpa/src/lib.rs
- srml/grandpa/src/mock.rs
- srml/grandpa/src/tests.rs
Reverts paritytech/substrate#3734
Needs more thought and testing for the runtime migration.
> Revert "grandpa: Use storage proofs for Grandpa authorities"

- core/service/src/lib.rs
This warning has existed for a long time, but https://github.com/paritytech/substrate/pull/3326 turned it into a debug message.
This actually happens in Polkadot, so let's put it back as a warning, but with a higher time.
> Print warning again if polling network is too long

- core/network/src/protocol.rs
- core/network/src/protocol/specialization.rs
- core/sr-primitives/src/generic/checked_extrinsic.rs
- node/runtime/src/lib.rs
- srml/im-online/src/lib.rs
- srml/im-online/src/tests.rs
> Add events for im_online

- core/network/src/config.rs
`NetworkConfiguration`, `TransportConfig`, `NodeKeyConfig` and `Secret`.
Needs a new release of the `rust-libp2p` crate. This PR is just a
reminder.
> Implement Debug for some structures

- core/client/db/src/storage_cache.rs
This is a possible fix to an issue that causes sync to stall in some cases.
In order to reproduce the issue you can create a fork (using `--reserved-only` or Blockade partitions) and then join the network. Depending on the length of the fork it may delay or stall sync, producing an error similar to `Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', srml/executive/src/lib.rs:271`.
- After creating the forks, restart the clients removing `--reserved-only`, joining the network.
- When restarting the nodes `cache.modifications` will be empty.
- We can get cache misses while executing best block, filling `local_cache`.
- When other node is discovered, it imports and execute common ancestor block.
- Since `cache.modifications` is still empty, `is_allowed()` …
> Possible fix to storage cache

- core/executor/src/lib.rs
- core/executor/src/native_executor.rs
- core/executor/src/wasm_runtime.rs
- core/executor/src/wasmi_execution.rs
- core/executor/src/wasmtime/runtime.rs
The runtime version is now fetched and cached at a higher level, not within the WasmRuntime trait implementations. The purpose is primarily to reduce duplication.
> executor: Move runtime version caching out of WasmRuntime interface.

- Cargo.lock
- core/chain-spec/Cargo.toml
- core/phragmen/Cargo.toml
- core/phragmen/src/lib.rs
- core/sr-primitives/Cargo.toml
- srml/authorship/Cargo.toml
- srml/finality-tracker/Cargo.toml
- srml/session/Cargo.toml
- srml/support/Cargo.toml
- srml/system/Cargo.toml
- srml/timestamp/Cargo.toml
useful for third party tools that might use the algorithm outside of substrate.
> Optional serde for phragmen support

- node/runtime/src/impls.rs
Terms were reversed according to https://research.web3.foundation/en/latest/polkadot/Token%20Economics/#1-fast-adjusting-mechanism
s is the current weight and s* is the target weight
> Correct Fee Adjustment Formula [doc]

- core/authority-discovery/src/lib.rs
Refactor code, remove unused import: `runtime_api::StorageProof`
> refactor code: remove unused import

- Cargo.lock
- core/rpc-servers/Cargo.toml
- core/rpc/Cargo.toml
- core/rpc/api/Cargo.toml
- core/test-runtime/src/genesismap.rs
- node/cli/Cargo.toml
- node/rpc-client/Cargo.toml
- node/rpc/Cargo.toml
- srml/contracts/rpc/Cargo.toml
- srml/system/rpc/Cargo.toml
- srml/transaction-payment/rpc/Cargo.toml
Another small one while developing tools around the rpc client. 
This might be breaking for
- https://github.com/paritytech/substrate-subxt
- https://github.com/scs/substrate-api-client
the core of the issue is that if your crate depends on a different version of `jsonrpc-core-client`, compared to `substrate-rpc-api` who  also depends on `jsonrpc-core-client`, you get all sorts of `trait not implemented for type` errors, as expected.
> Update RPC deps.

- core/network/src/protocol/sync.rs
- core/network/src/protocol/sync/blocks.rs
The network is clogged with gossip messages. Peers often timeout when responding with block data, leading to nodes falling behind. This enables parallel block download at the tip of the chain from up to 3 peers at once.
> Enable parallel block download

- core/network/src/legacy_proto/behaviour.rs
- core/network/src/legacy_proto/handler.rs
- core/network/src/legacy_proto/tests.rs
- core/network/src/legacy_proto/upgrade.rs
- core/network/src/protocol.rs
- core/network/src/protocol/message.rs
Collect stats on sync protocol traffic.
> Traffic statistics

- node/runtime/src/lib.rs
- srml/im-online/src/lib.rs
- srml/im-online/src/mock.rs
By talking with @jacogr I realised that the heartbeat transactions effectively live forever in the pool (as we issue `immortal` transactions in the runtime). This PR limits the longevity of those transactions to 128 blocks (~13mins with 6s block time).
> Limit longevity of im-online heartbeats.

- core/client/db/src/lib.rs
- core/client/src/client.rs
- core/consensus/common/src/block_import.rs
- core/consensus/common/src/import_queue.rs
- core/finality-grandpa/src/light_import.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/protocol/sync.rs
- core/network/src/test/block_import.rs
- core/network/src/test/mod.rs
- core/network/src/test/sync.rs
- core/test-client/src/lib.rs
* Sync requests coming from GRANDPA are now done in header-only mode.
* Tweaked import pipeline to enable header-only import.
> Header-only sync for old forks

- Cargo.lock
- core/utils/build-script-utils/Cargo.toml
- core/utils/build-script-utils/src/lib.rs
- node-template/Cargo.toml
- node-template/build.rs
- node/cli/Cargo.toml
- node/cli/build.rs
- Add new crate `substrate-build-script-utils` to unify the code of
`node`, `node-template` and `polkadot-node`.
- The `node-cli` build script needs to search upwards for the
`.git/HEAD` file to find it.
> Don't re-compile on every `cargo run`

- core/network/src/discovery.rs
- core/sr-io/with_std.rs
* Moved runtime output under `runtime=debug`
* Hid discovery message
> Less verbose console output

- core/externalities/src/extensions.rs
- core/primitives/src/offchain.rs
- core/state-machine/src/testing.rs
Fixes: https://github.com/paritytech/substrate/issues/4013
CC @geigerzaehler
> Make `TestExternalities` implement `Send`

- node/executor/src/lib.rs
- node/runtime/src/lib.rs
- srml/staking/src/lib.rs
- srml/staking/src/mock.rs
- srml/support/src/traits.rs
- srml/treasury/src/lib.rs
This alters the functionality of staking so that 10% inflation per year is fixed and any of the 10% not paid to stakers instead goes to the treasury.
It no longer attempts to keep stakers "only at" the level of inflation, as before.
This also adds a new event to the `treasury` called `Deposit`, given out when funds are received through the `Treasury` imbalance handler.
> Treasury rewards should pay the remainder of the 10%

- scripts/node-template-release/src/main.rs
fix the following error:
```
$ ./scripts/node-template-release.sh substrate-node-template.tar.gz
Finished dev [unoptimized + debuginfo] target(s) in 0.05s
Running `target/debug/node-template-release /Users/ys/Desktop/polkadot/substrate/node-template /Users/ys/Desktop/polkadot/substrate/substrate-node-template.tar.gz`
error: failed to read `/private/var/folders/vm/yzhl_9_959gchmw245_0l4dw0000gn/T/.tmpIpC397/core/utils/build-script-utils/Cargo.toml`
Caused by:
No such file or directory (os error 2)
thread 'main' panicked at 'assertion failed: Command::new("cargo").args(&["build",
"--all"]).current_dir(path).status().expect("Compiles node").success()', src/main.rs:165:2
```
> Also replace paths in [build-dependencies]

- core/finality-grandpa/primitives/src/lib.rs
- core/finality-grandpa/src/authorities.rs
- core/finality-grandpa/src/aux_schema.rs
- core/finality-grandpa/src/communication/tests.rs
- core/finality-grandpa/src/finality_proof.rs
- core/finality-grandpa/src/lib.rs
- core/finality-grandpa/src/light_import.rs
- core/finality-grandpa/src/tests.rs
- node-template/runtime/src/lib.rs
- node-template/src/service.rs
- node/cli/src/service.rs
- node/runtime/src/lib.rs
- srml/grandpa/Cargo.toml
- srml/grandpa/src/lib.rs
- srml/grandpa/src/mock.rs
- srml/grandpa/src/tests.rs
This is a follow-up to #3734 to ensure new nodes on Kusama (or any Substrate chain deployed before #3734) can still get the initial authority set in order to sync. Without this, existing nodes would be fine since the authority set is persisted locally by the grandpa service, but new nodes would not be able to read the initial authority set.
The main difference from #3734 is that the `GenesisAuthoritySetProvider` uses the Grandpa runtime API, which is backwards compatible, instead of a direct storage lookup.
I have tested that this works locally with the following steps:
1. Checkout master. Change `MILLISECONDS_PER_BLOCK` in `node/runtime/src/constants.rs` to 6000 and build. Save the built `substrate` binary as `substrate-master`.
2. Checkout this branch. Change `MILLISECONDS_PER_BLOCK` in …
> grandpa: Re-add Grandpa runtime API for genesis authority set.

- core/client/db/src/lib.rs
- core/client/src/client.rs
- core/consensus/aura/src/lib.rs
- core/consensus/babe/src/lib.rs
- core/consensus/babe/src/tests.rs
- core/consensus/common/src/block_import.rs
- core/consensus/common/src/import_queue.rs
- core/consensus/pow/src/lib.rs
- core/finality-grandpa/src/light_import.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/protocol/sync.rs
- core/network/src/test/block_import.rs
- core/network/src/test/mod.rs
- core/network/src/test/sync.rs
- core/service/src/chain_ops.rs
- core/test-client/src/client_ext.rs
- core/test-client/src/lib.rs
- node-template/build.rs
- node/cli/src/service.rs
- test-utils/transaction-factory/src/lib.rs
This is another take on reverted #3942
Instead of doing header-only sync we do regular sync here and skip state enactment if parent state is not available.
> Allow import withouth state verification

- srml/support/procedural/src/storage/genesis_config/genesis_config_def.rs
- srml/support/procedural/src/storage/genesis_config/mod.rs
Due to a bug, the runtime code was previously serialized as a JSON array of numbers, pretty printed one byte per line. This could be seen by running `$ substrate build-spec`.
This fixes the `decl_storage!` proc macro so that the `serde` directive [already in the SRML system module code](https://github.com/paritytech/substrate/blob/master/srml/system/src/lib.rs#L421) is not ignored.
> Correctly serialize code in chain spec as hex

- core/client/src/client.rs
- core/network/src/protocol/message.rs
This pr fixes two small typos.
> fix two typos

- core/cli/src/lib.rs
- core/cli/src/params.rs
- core/finality-grandpa/src/tests.rs
- core/network/src/config.rs
- core/network/src/protocol.rs
- core/network/src/protocol/sync.rs
- core/network/src/protocol/sync/blocks.rs
- core/network/src/service.rs
- core/service/test/src/lib.rs
Logs show that sometimes all 3 peers timeout.
> Increase parallel downloads to 5

- Cargo.lock
- core/offchain/Cargo.toml
- core/offchain/src/api/http.rs
We really really don’t want to depend on OpenSSL, as that requires us
make a new release for non-Linux platforms whenever an upstream OpenSSL
security vulnerability affects us.
We currently depend on OpenSSL only via the `native-tls` crate, which
we depend on via `hyper-tls` and `tokio-tls`.  This PR is a
work-in-progress because it only removes the first dependency.  Removing
the second one will require a change to the `websocket` crate.
> Remove dependencies on OpenSSL

- core/state-machine/src/backend.rs
when converting the in memory to a triebackend, if the main trie is empty then child trie root hash were not inserted into the main trie.
This can happen for instance with an empty trie with only one transaction:
```rust
vec![(Some(b"1".to_vec()), b"2".to_vec(), Some(b"3".to_vec()))]
```
But actually I'm not completely sure such a transaction is valid, maybe transaction must include the value to write in the main trie.
> Fix in_memory backend for child tries.

- core/finality-grandpa/src/communication/gossip.rs
- core/network/src/protocol/consensus_gossip.rs
Currently in GRANDPA gossip we have the notion of politeness to restrict who we should gossip messages to (i.e. only send messages to nodes that are close to the messages' round). Still, assuming that all nodes are up-to-date with the latest round we will potentially gossip messages to all of the peers we are connected to. This results in a lot of churn in the network as we keep receiving the same message multiple times from different peers.
This PR adds logic for restricting the number of peers we gossip to and progressively increase the set as necessary (i.e. if GRANDPA doesn't make any progress). The logic for filtering peers follows the given state transitions:
- State 0: don't send to anyone (only if our local node is not an authority)
- State 1: send to random `sqrt(authorities)`
- …
> grandpa: progressively increase target gossip peers

- Cargo.lock
- core/transaction-pool/Cargo.toml
- core/transaction-pool/src/api.rs
Since currently the full client requires a synchronous runtime call to validate transaction it might take a lot of time.
Transaction verification is being triggered from the network stack it may block all the tokio runtime threads and cause issues with networking (potentially a reason why some nodes fall behind the sync).
> Separate thread pool for transaction verification

- core/network/src/protocol.rs
- core/network/src/protocol/consensus_gossip.rs
- core/network/src/protocol/message.rs
- core/state-machine/src/backend.rs
Should help with tokio overhead and allocation fragmentation
> Batch gossip messages

- srml/example/src/lib.rs
Corrects grammar in a comment in srml-example
> Fix minor comment typo "do" -> "do not"

- core/network/src/protocol/sync.rs
- core/network/src/test/sync.rs
Recently we've introduced an`is_best` flag to the block announcement to keep track of peer's best block. Before that we've assumed that the best block is always with the highest number, which is not the case with BABE. 
When peer announces a known ancient block with `best` flag, we would not update their best block, but rather common block. Which effectively makes sync think they are on a huge fork and try to sync it. 
This PR removes the incorrect assumption that best block number can't decrease, effectively preventing sync to such peers.
> Fix sync downloading ancient chains

- core/sr-api-macros/tests/ui/empty_impl_runtime_apis_call.stderr
- core/sr-api-macros/tests/ui/impl_incorrect_method_signature.stderr
- core/sr-api-macros/tests/ui/invalid_api_version.stderr
- core/sr-api-macros/tests/ui/invalid_api_version_2.stderr
- core/sr-api-macros/tests/ui/invalid_api_version_3.stderr
- core/sr-api-macros/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
Fixes: https://github.com/paritytech/substrate/issues/4063
> Fix the ui tests

- core/transaction-pool/graph/src/listener.rs
- core/transaction-pool/graph/src/pool.rs
- core/transaction-pool/graph/src/validated_pool.rs
To debug slow notifications to UI.
> Additional logging for the transaction pool.

- core/service/src/builder.rs
cc @maciejhirsz 
Passes the node startup time to the telemetry when connected.
This way, if we disconnect then reconnect, the telemetry knows that it's just the connection that closed and not the node as a whole.
> Pass startup_time to telemetry

- core/network/src/protocol/sync.rs
- core/network/src/test/sync.rs
Common block should only be updated if indicated as best
> Further fix for common block update

- core/cli/src/lib.rs
- core/cli/src/params.rs
- core/network/src/behaviour.rs
- core/network/src/config.rs
- core/network/src/discovery.rs
- core/network/src/service.rs
- core/service/test/src/lib.rs
- node/cli/src/browser.rs
Fix https://github.com/paritytech/polkadot/issues/543
If passed, the `--no-private-ipv4` CLI option will prevent the networking from trying to connect to the ranges `10.0.0.0/8`, `172.16.0.0/12` and `192.168.0.0/16`.
> Add a --no-private-ipv4 CLI option

- .editorconfig
Sine we allow lines longer than 100 only in "exceptional circumstances" let's lower the `max_width` in `.editorconfig` to make the editors automatically wrap beyond that point.
> Change max width to 100.

- srml/timestamp/src/lib.rs
Timestamps in srml-timestamp used to be defined in seconds but were changed to milliseconds later on. When importing a block we allow for a drift in the timestamp but the constant was defined in seconds and wasn't updated. This PR fixes the max drift definition to 30 seconds, defined in millis.
> srml-timestamp: define max timestamp drift in millis

- core/phragmen/src/lib.rs
- core/phragmen/src/mock.rs
- core/phragmen/src/tests.rs
- srml/elections-phragmen/src/lib.rs
- srml/staking/src/lib.rs
- srml/treasury/src/lib.rs
Another important step toward moving phragmen entirely out of substrate repo. 
During the first test of phragmen on Alexander, all candidates were being evicted since no one used to nominate and no candidate had any _external_ backing stake. So we added the proxy _self-vote_. All validators will vote for themselves by default. The vote was injected at the beginning and removed from the output, inside the `elect` function. 
This was wrong from the get-go since it is leaking a logic from staking into phragmen. And it already broke with `srml-elections-phragmen` where `self_vote = false` parameter was added to _disable_ the self vote. 
Now, phragmen does not care about any of this. The caller is responsible for 
- creating self vote if desired
- removing the self-votes from the result, if …
> Remove Self vote from phragmen

- core/network/src/protocol/sync.rs
- core/network/src/test/sync.rs
The check is obsolete now that we support downloading with missing state. It also interferes with parallel block downloading.
> Allow ancient fork download after ancestry search

- core/network/src/protocol/sync.rs
Make sure we don't request any blocks past finality point
> Don't request old obsolete blocks

- core/consensus/slots/src/lib.rs
```
2019-11-11 12:15:30 Initializing Genesis block/state (state: 0x5b7a…35d9, header-hash: 0xf4fa…d66d)
2019-11-11 12:15:30 Loading GRANDPA authority set from genesis on what appears to be first startup.
2019-11-11 12:15:30 Loaded block-time = 15000 seconds from genesis on first-launch
2019-11-11 12:15:30 Highest known block at #0
2019-11-11 12:15:30 Using default protocol ID "sup" because none is configured in the chain specs
2019-11-11 12:15:30 Local node identity is: QmWDyvCu283NQQ3ZstJu4t2Yy8FuJ9SiiqCtjbq4u42N5g
```
The slot duration is denoted in milliseconds not seconds. This PR simply fixes the console output.
Alternatively, one could divide the slot duration by 1_000. I'm not sold on any approach.
> core/consensus: fix console output for slot duration

- .gitlab-ci.yml
Superseding https://github.com/paritytech/substrate/pull/4075 to test on a pull request based on a repository fork.
> [WIP] .gitlab-ci.yml: Fix a check for polkadot to work on forked repos v2

- srml/evm/src/lib.rs
EVM currently remembers its contracts' balances outside of the issuance system. This leads to `TotalIssuance` being less than it should be as it doesn't count any account balances of EVM contracts. This fixes that in the same way it's handled for treasury module.
> EVM should store contracts' balances in an account.

- node/runtime/src/impls.rs
- srml/balances/src/lib.rs
- srml/generic-asset/src/lib.rs
- srml/support/src/traits.rs
- srml/treasury/src/lib.rs
Closes #4088 
Introduce a new `TryDrop` trait to get around the fact that `Imbalance` trait is itself generic. Then always `try_drop` before actually acting on the imbalance. This means that zero imbalances will be silently dropped without being explicitly handled, as they should be.
> Do nothing for zero imbalances

- core/client/src/client.rs
- core/consensus/common/src/block_import.rs
- core/consensus/common/src/import_queue.rs
- core/network/src/protocol.rs
- core/network/src/protocol/sync.rs
- core/test-client/src/client_ext.rs
* Work around the reorg-to-not-the-best-block by not restarting sync in such cases.
* Small optimization to avoid copying huge `peers` structure needlessly.
> Fix sync stalling on moving head (best block) prior to the tip of the chain sometimes

- Cargo.lock
- core/sr-arithmetic/fuzzer/Cargo.lock
This lets us get rid of some duplicate dependencies, which is nice.
> Bump dependencies with `cargo update`

- core/network/src/protocol.rs
Currently we may cache up to 64Mb of these hashes per peer.
> Sensible limits for known blocks and extrinsics

- core/network/src/protocol/sync.rs
- core/network/src/protocol/sync/blocks.rs
This prevents downloading blocks too far ahead if there's a gap.
> Do not download blocks too far ahead

- core/network/src/protocol/sync.rs
Sync now better tracks the best good imported block, instead of relying on the client. The client might occasionally report the best block that already has children, that we don't want to download again.
> Keep track of best imported block precisely

- Cargo.lock
- core/executor/Cargo.toml
- core/executor/src/error.rs
- core/executor/src/wasmi_execution.rs
- core/primitives/Cargo.toml
- core/sr-sandbox/Cargo.toml
- core/wasm-interface/Cargo.toml
- node/cli/Cargo.toml
- node/executor/Cargo.toml
Related #3780 
This PR makes the erasing procedure in wasmi runtimes failable. If the erasing fails it will be returned as an error instead of panicking on expect.
> Additional wasm diagnostics

- paint/support/src/storage/generator/double_map.rs
- paint/support/src/storage/mod.rs
I noticed that there isn't `hashed_key_for()` getter method for `StorageDoubleMap` whereas one exists in `StorageMap`. This PR adds the method.
> add hashed_key_for() getter method for StorageDoubleMap

- Cargo.lock
- primitives/core/Cargo.toml
- primitives/core/src/ecdsa.rs
- primitives/core/src/ed25519.rs
- primitives/core/src/sr25519.rs
- primitives/sr-primitives/src/lib.rs
This PR adds support for `serde` serialization and deserialization to the Signature types of all cryptosystems that Substrate uses. It also adds support to the `MultiSIgnature` enum class through automatic derivation.
Please note that hex-string encoding was chosen for Signature classes for simplicity.
> Add serde for Signature types

- Cargo.lock
- client/header-metadata/Cargo.toml
- client/header-metadata/src/lib.rs
- client/network/Cargo.toml
- client/network/src/protocol/consensus_gossip.rs
- primitives/peerset/Cargo.toml
This PR replaces the `lru-cache` crate with `lru`. We use this LRU cache in gossip to keep track of what messages we have already seen previously, the issue is that we commonly call `contains_key` on this cache (e.g. when receiving a new message, or when collecting garbage) and this moves the given entry to the front of the LRU list. This made it so that we wouldn't expire messages by insertion order and instead it would depend on how many times we saw the message and when, leading us to sometimes expire recent messages which would then be added as duplicates under `self.messages`.
The `lru-cache` crate is also unmaintained now and therefore it makes sense to replace it with `lru`. The `contains` method in `lru` doesn't update the LRU list and therefore we will always make sure gossip …
> gossip: replace LRU cache

- docs/CODEOWNERS
Folders were moved in #4074 and some paths weren't properly updated in CODEOWNERS file.
> docs: fix CODEOWNERS paths

- Cargo.lock
- client/rpc/Cargo.toml
- paint/transaction-payment/rpc/runtime-api/Cargo.toml
- paint/transaction-payment/rpc/runtime-api/src/lib.rs
- primitives/sr-primitives/src/weights.rs
We serialize to `serde_json::Value` internally in `jsonrpc` and without `arbitrary_precision` feature the `u128` (used as `Balance`) is not support and causes a failure.
Also fixes the format of returned response to be more javascripty.
CC @jacogr
> Fix serialization of `transaction_paymentInfo`

- client/finality-grandpa/src/environment.rs
The GRANDPA protocol requires honest voters to always vote for some block that is below the given round base (i.e. last finalized block). We allow users to plug arbitrary voting rules that will further restrict round votes, still the `Environment` needs to make sure that whatever restriction is applied we guarantee that the block we vote on is greater or equal to the round base. This PR adds the aforementioned verification.
> grandpa: voting rules shouldn't restrict past round base

- client/chain-spec/Cargo.toml
- client/chain-spec/src/extension.rs
When we enabled arbitary precision for `serde_json`, the feature leaked
through the whole workspace. The given test fails because of some bug in
serde json when the feature is enabled.
> Fix `forks_should_work_correctly` test

- client/finality-grandpa/src/communication/gossip.rs
The timeout for catch up requests was a bit too strict (5 seconds), my node was timing out requests from peers that eventually came up with an answer (some seconds later). For reference, currently sync requests timeout after 40 seconds.
> grandpa: increase timeout for catch up requests

- Cargo.lock
- client/executor/Cargo.toml
- client/executor/src/native_executor.rs
This makes it possible to use custom runtime interfaces within your
runtime by registering them at the native executor.
> Support custom runtime interfaces in native executor

- Cargo.lock
- client/executor/Cargo.toml
- client/executor/src/wasmtime/trampoline.rs
Second attempt to use wasmtime from crates.io, this time followed by official announcment of publishing on crates.io.
This would allow us to get rid of another git dependency.
> Use crates.io version of wasmtime

- paint/session/src/lib.rs
Clarifies the documentation comment on `session::Trait`'s associated type `ValidatorIdOf`.
The correction is
```diff
- Converts to B to A
+ Converts from A to B
```
> Fix typo: to -> from

- Cargo.lock
- primitives/state-machine/Cargo.toml
- primitives/trie/Cargo.toml
- primitives/trie/src/lib.rs
- primitives/trie/src/node_codec.rs
- test/utils/runtime/Cargo.toml
The new version of `trie-db` has some breaking API changes, but the node encoding format remains the same.
> Upgrade trie-db crate to 0.16.0.

- Cargo.lock
- palette/balances/Cargo.toml
- palette/balances/src/lib.rs
- palette/balances/src/mock.rs
- palette/balances/src/tests.rs
- primitives/core/Cargo.toml
- primitives/runtime-interface/src/impls.rs
There is not really anything more we can do at the moment, if we disable the default features for the `dev-dependencies` it at least fixes the problem described in the linked issue.
Fixes: https://github.com/paritytech/substrate/issues/4179
> Clean up depedencies and cargo tomls

- client/network/src/protocol.rs
When something bad happens with a peer, and this peer is in the reserved peers list, we bump the log level to `warn`.
> Improve logging for reserved peers

- palette/support/src/storage/child.rs
- palette/support/src/storage/generator/linked_map.rs
- palette/support/src/storage/unhashed.rs
Fix corrupted storage panic
In the long term we should implement https://github.com/paritytech/substrate/issues/3700
> Remove panic on corruped storage

- frame/im-online/src/lib.rs
Caught in the renaming process. It is not obvious to me why `frame/` or `palette/` or `srml/` was included in the DB key.
If there is rational, would love to know what that is before this is closed.
> Remove `frame/` prefix from `im_online` DB_KEY.

- client/api/src/backend.rs
- client/api/src/blockchain.rs
- client/db/src/lib.rs
- client/db/src/storage_cache.rs
- client/src/call_executor.rs
- client/src/client.rs
- client/src/in_mem.rs
- client/src/light/backend.rs
* Make sure cache is updated under impror lock so that the best block info is always consistent.
* `is_best` functor was checked under cache lock, which was supposed to guarantee consistency. But in reality it does not, because cache is also updated when validating transactions outside of import lock. So this is removed.
* Changed import lock to be `Rwlock` instead of `Mutex` for extra performance.
> Fixed shared cache race on import

- Cargo.lock
- client/rpc/api/src/chain/mod.rs
- client/rpc/src/chain/mod.rs
- client/rpc/src/chain/tests.rs
- primitives/rpc/Cargo.toml
- primitives/rpc/src/lib.rs
- primitives/rpc/src/list.rs
- primitives/rpc/src/number.rs
CC @jacogr 
This allows getting multiple block hashes, by sending a single request for multiple block numbers.
Even though it's possible to send a batch RPC query for that, the protocol overhead is too big for such small input/output values.
> Allow batch query for block hash.

- client/finality-grandpa/src/communication/gossip.rs
- client/network/src/protocol/consensus_gossip.rs
This reworks #4050 to use time-based gossip progression, rather than relying on the number of attempts, which is quite random.
> Time-based gradual gossip

- Cargo.lock
- client/cli/src/params.rs
- client/tracing/Cargo.toml
- client/tracing/src/lib.rs
This starts the integration between grafana and tracing output:
I opened the PR to get ideas on how to best integrate this two modules and on the usefulness of it.
TODO:
- Make the aggregation more precise (module, function, scopes?).
- Support multiple receivers? (e.g. stdout, grafana, telemetry)
> Integrate grafana and tracing

- client/consensus/slots/src/lib.rs
- client/consensus/slots/src/slots.rs
This tries to address the issue that proposers giving up proposing blocks due to long proposing time, causing the network not producing blocks for a long time.
`remaining_duration`, which is the parameter used to determine how long the proposing logic tolerant execution, is now splited into two -- `slot_remaining_duration`, for inner proposing logic to determine pushing extrinsic, and `proposing_remaining_duration`, for outer `on_slot` to determine the actual timeout. The timeout is now configurable by each consensus engine. For example, an engine can change this to be determined by last proposing slot `actual_slot - expected_slot > expected_slot - parent_slot`.
When review, please note that the behavior is changed that `on_slot` will not time out on proposing by default. I talked with …
> Make block proposing remaining duration configurable

- client/executor/runtime-test/src/lib.rs
- client/executor/src/integration_tests/mod.rs
- primitives/core/src/hashing.rs
- primitives/sr-io/src/lib.rs
Widely used hash function, supported by [bitcoin](https://en.bitcoin.it/wiki/Script#Crypto) and [ethereum](https://solidity.readthedocs.io/en/v0.5.13/units-and-global-variables.html#mathematical-and-cryptographic-functions)
> Add sha2-256 hash function

- bin/node/runtime/src/lib.rs
- frame/executive/src/lib.rs
- frame/metadata/src/lib.rs
- frame/support/procedural/src/lib.rs
- frame/support/procedural/src/storage/instance_trait.rs
- frame/support/procedural/src/storage/storage_struct.rs
- frame/support/src/storage/generator/double_map.rs
- frame/support/src/storage/generator/linked_map.rs
- frame/support/src/storage/generator/map.rs
- frame/support/src/storage/generator/mod.rs
- frame/support/src/storage/generator/value.rs
- frame/support/src/storage/mod.rs
- frame/support/test/tests/final_keys.rs
- frame/support/test/tests/instance.rs
- utils/frame/rpc/support/src/lib.rs
This updates the way storages are implemented now all storage are prefixed resulting in:
* storage value at `twox128(module) ++ twox128(storagename)`
* linked_map and map at `twox128(module)++twox128(storagename)++hasher(key)`
* linked_map head at `twox128(module) ++ twox128("HeadOf" ++ storagename)`
* double_map at `twox128(module)++twox128(storagename)++hasher(key1)++hasher(key2)`
TODO:
I have no idea how we want to launch this PR in regards to Kusama, nor what the schedules are, but here it is.
NOTE:
* some improvement could be done by returning arrays instead of Vector for generating the final keys, but this is not very important.
* this doesn't implement any new sr-io method to iterate on anything
CC @bkchr @jacogr
> Implement all storage after prefix

- Cargo.lock
- primitives/state-machine/Cargo.toml
- primitives/trie/Cargo.toml
- primitives/trie/src/lib.rs
- primitives/trie/src/node_codec.rs
- test/utils/runtime/Cargo.toml
This PR brings back trie 0.16 dependency to substrate.
The only difference from previous state is that trie-bench is now versioned 0.17.
It breaks consensus by fixing trie 0.15 iterator issue.
> Update trie to 0.16 again

- client/consensus/babe/src/lib.rs
Uses a linear method for the back-off.
> back-off block proposal in BABE

- primitives/core/src/ecdsa.rs
> Use raw public key instead of compressed

- Cargo.lock
- bin/node/executor/src/lib.rs
- client/db/src/lib.rs
- client/db/src/storage_cache.rs
- client/executor/src/deprecated_host_interface.rs
- client/executor/src/wasm_runtime.rs
- client/src/cht.rs
- client/src/light/backend.rs
- client/src/light/fetcher.rs
- frame/system/src/lib.rs
- primitives/externalities/Cargo.toml
- primitives/externalities/src/lib.rs
- primitives/sr-io/src/lib.rs
- primitives/sr-primitives/src/traits.rs
- primitives/state-machine/src/backend.rs
- primitives/state-machine/src/basic.rs
- primitives/state-machine/src/changes_trie/build.rs
- primitives/state-machine/src/changes_trie/changes_iterator.rs
- primitives/state-machine/src/changes_trie/mod.rs
- primitives/state-machine/src/changes_trie/prune.rs
- primitives/state-machine/src/ext.rs
- primitives/state-machine/src/lib.rs
- primitives/state-machine/src/overlayed_changes.rs
- primitives/state-machine/src/proving_backend.rs
- primitives/state-machine/src/testing.rs
- primitives/state-machine/src/trie_backend.rs
- primitives/state-machine/src/trie_backend_essence.rs
- primitives/trie/src/lib.rs
- test/utils/runtime/src/system.rs
Currently the runtime interface enforces `H256` as hash type, but in the
future people could use whatever they want as hash type. The hash type
always needs to match between the runtime and the node, but that is
already required.
> The storage runtime interface should not enforce a hash type

- frame/support/src/traits.rs
Without this we cannot have a Moment parameter in dispatchable functions
> Parameter trait for Time::Moment

- bin/node-template/src/cli.rs
- bin/node/cli/src/cli.rs
- bin/node/cli/src/service.rs
- client/cli/src/lib.rs
- client/cli/src/params.rs
- client/consensus/aura/src/lib.rs
- client/consensus/babe/src/lib.rs
- client/consensus/babe/src/tests.rs
- client/consensus/pow/src/lib.rs
- client/finality-grandpa/src/light_import.rs
- client/finality-grandpa/src/tests.rs
- client/network/src/protocol/sync.rs
- client/network/src/test/block_import.rs
- client/network/src/test/mod.rs
- client/service/src/builder.rs
- client/service/src/chain_ops.rs
- client/service/src/lib.rs
- client/src/client.rs
- primitives/consensus/common/src/block_import.rs
- primitives/consensus/common/src/import_queue.rs
- test/utils/client/src/client_ext.rs
- test/utils/transaction-factory/src/lib.rs
A CLI command to re-validate existing block. This is useful for debugging/tracing block execution. 
Also fixed `--pruning` option for import/export commands and got rid of macros in service, such as `import_blocks!`
> Check block CLI command

- bin/node/cli/src/cli.rs
- client/cli/src/lib.rs
- client/cli/src/params.rs
After #4240 substrate binary ended up having duplicate "execution" args.
> Fixed node binary

- client/cli/src/lib.rs
This fixes the following error.
```
substrate-master git:(master) ✗ ./target/debug/substrate --dev            
2019-11-30 18:02:18 Running in --dev mode, RPC CORS has been disabled.
2019-11-30 18:02:18 Substrate Node
2019-11-30 18:02:18   version 2.0.0-ccd72addd-x86_64-linux-gnu
2019-11-30 18:02:18   by Parity Technologies, 2017-2019
2019-11-30 18:02:18 Chain specification: Development
2019-11-30 18:02:18 Node name: guarded-science-6820
2019-11-30 18:02:18 Roles: AUTHORITY
Error: Service(Client(Backend("IO error: No such file or directoryWhile mkdir if missing: No such file or directory")))
```
The function called contains the replaced ones and adds the path.
> Fix db path on normal run.

- client/keystore/src/lib.rs
Fixes: https://github.com/paritytech/polkadot/issues/635
> Check filename length is valid in keystore

- client/transaction-pool/graph/src/base_pool.rs
- client/transaction-pool/graph/src/pool.rs
- client/transaction-pool/graph/src/ready.rs
- client/transaction-pool/graph/src/validated_pool.rs
- client/transaction-pool/src/maintainer.rs
Most of the chains will not really use a runtime-type of `UncheckedExtrinsic` for their in-block extrinsic type, but rather the node will only know about `OpaqueExtrinsic` type.
This type implements `Extrinsic` trait, however `is_signed` always returns `None`.
The fix makes sure we re-import transactions even though `is_signed` is `None`, and we also tone-down the warning level (which seemed to be a reason to add that check in the first place).
Additionally some small changes to add logging and an attempt to clean the naming of methods (`remove_invalid` vs `remove_subtree`). This is an intro to a bigger change which would be periodic revalidation of transactions in the pool.
Should fix #4107
> Fix reimporting transactions from retracted blocks.

- frame/balances/src/lib.rs
- frame/support/src/traits.rs
This takes the "vesting" part of the Balances module into its own `VestingCurrency` trait.
This will help solve the problem outlined here:
https://github.com/paritytech/polkadot/issues/612
In summary, vesting can only be set directly in the balances module through genesis config. The `claims` module wants to apply some vesting schedule if the user claims their tokens after genesis.
We extract the following functionality into this new trait:
* `vesting_balance`: Returns the vesting balance of a user.
* `add_vesting_schedule`: Allows you to add a new vesting schedule to an account. It will fail if there is any existing schedule.
* `remove_vesting_schedule`: Allows you to remove a vesting schedule from an account.
I believe then this will allow us to use this trait in the Claims module where …
> Introduce `VestingCurrency` trait

- Cargo.lock
- bin/node-template/Cargo.toml
- bin/node/cli/Cargo.toml
- client/basic-authorship/Cargo.toml
- client/offchain/Cargo.toml
- client/rpc/Cargo.toml
- client/service/Cargo.toml
- client/transaction-pool/Cargo.toml
- client/transaction-pool/graph/Cargo.toml
- client/transaction-pool/graph/benches/basics.rs
- utils/frame/rpc/system/Cargo.toml
when attempting to fix an error in #4223 , I accidentally was too promiscuous in the pattern and renamed two crates along with it. This PR fixes that.
Test still passed because all was consistent internally, but the name of the crates was just wrong.
> Fix sc-tracing-* -> sc-transaction-

- .maintain/rename-crates-for-2.0.sh
- Cargo.lock
- bin/node-template/runtime/Cargo.toml
- bin/node-template/runtime/src/lib.rs
- bin/node/runtime/Cargo.toml
- bin/node/runtime/src/lib.rs
- client/rpc/Cargo.toml
- client/service/Cargo.toml
- primitives/session/Cargo.toml
- test/utils/runtime/Cargo.toml
`sesssion` -> ` session`. Introduced in #4223.
> Fix sp-session typo

- frame/elections-phragmen/src/lib.rs
This ensures that the `ChangeMembers` signal is properly sorted. Test added.
cc @kianenigma
> Another fix for elections-phragmen 

- bin/node/runtime/src/lib.rs
- frame/democracy/src/lib.rs
- primitives/sr-version/src/lib.rs
Right now although we can enumerate all *values* of the `democracy::DispatchQueue` mapping, we cannot enumerate all the keys. This is a general failing of `map`, since it will be default use a cryptographic hash (Blake2) to index the item, which is by design not useful for deriving the key itself.
This uses a non-cryptographic hash (the key material is a block number coming from a high-friction governance process and cannot be easily or cheaply gamed) along with the index itself, allowing the index to be derived from the database key.
CC @jacogr
> Enumeratable dispatches using unhashed index in key

- bin/node/cli/src/chain_spec.rs
Adds members to both collective modules for testing purposes
> Add testnet council and tech committee members

- .maintain/sentry-node/docker-compose.yml
- bin/node/cli/src/service.rs
- client/authority-discovery/src/lib.rs
- client/cli/src/lib.rs
- client/cli/src/params.rs
- client/network/src/config.rs
- client/service/test/src/lib.rs
Enable operators to specify the public addresses of sentry nodes infront of a validator node so that the validator node can announce the sentry node addresses instead of its own public addresses on the DHT via the authority discovery module.
This pull request is based on https://github.com/paritytech/substrate/pull/4274, thus it should only be merged after https://github.com/paritytech/substrate/pull/4274. One can ignore the first two commits when reviewing this pull request.
Commit 3 (updating `.maintain/sentry-node/docker-compose.yml`) and commit 5 (shortening line length to 100 instead of 120 char) should not need much review.
Commit 4 (https://github.com/paritytech/substrate/commit/a5b5db7f4c1bda0ac906bb04fa67826eabbe9b5b) is the core of this pull request.
Given that this changes the …
> client: Introduce --sentry-nodes flag

- frame/executive/src/lib.rs
- frame/support/src/dispatch.rs
- primitives/sr-primitives/src/traits.rs
- primitives/sr-version/src/lib.rs
For some obscure historical reason (and most likely my laziness), the method of `OffchainWorker` trait is called `generate_extrinsics`. This PR renames it to just `offchain_worker`.
Note this trait is rarely (rather close to never) implemented manually, it's auto-implemented via `decl_module` macro, so this change should be non-breaking.
> Rename OffchainWorker internal method.

- Cargo.lock
- client/transaction-pool/graph/Cargo.toml
- client/transaction-pool/graph/src/pool.rs
- client/transaction-pool/graph/src/ready.rs
- client/transaction-pool/graph/src/validated_pool.rs
- client/transaction-pool/src/maintainer.rs
This should fix transactions stalling in the pool for a long time.
I'm still running tests for Kusama to make sure it works correctly.
> Revalidate some transactions on every block import.

- client/authority-discovery/src/lib.rs
The authority discovery module publishes and queries (onto) the DHT on an interval. Given that the `futures-timer` crate removed `Interval` the concept of an `Interval` was introduced into the authority discovery module directly.
In order for the custom implementation to equal the old `futures-timer` implementation, it should support an instant `Interval` as well as *queuing* events when the `Interval` is not polled for a while.
---
Maybe worth discussing after this pull request:
I don't think the authority discovery module should have its own implementation of `Interval`, but rather I would like it to move to its own library, or us depending on an alternative to `futures-timer` with an `Interval` equivalent implementation.
As of now the unit smoke tests depend on timing assumptions that …
> client/authority-discovery: Fix interval_at to fire on start

- client/consensus/aura/src/lib.rs
This implements the linear-back off that exists for babe worker, for the aura worker. It does so by simple piggybacking off the previous slot number.
@rphmeier this still hasn't solved my issue as I just tried running an upgrade where all I did is increment the spec/impl versions. The upgrade still stalled. I'm using the polkadotjs UI, maybe there's something in my process I'm doing incorrectly?
> Add linear back-off for aura slot workers

- frame/transaction-payment/rpc/runtime-api/Cargo.toml
- frame/transaction-payment/rpc/runtime-api/src/lib.rs
- frame/transaction-payment/rpc/src/lib.rs
`payment_fee` is not likely to ever exceed `u64` anyway, and by not using `Balance` directly we can avoid running into issues with `u128` balances.
Fixes: https://github.com/paritytech/polkadot/issues/654
> Use balance capped to u64 for transaction payment RPC.

- client/transaction-pool/graph/src/listener.rs
- client/transaction-pool/graph/src/validated_pool.rs
Follow up on #4292 
We don't print a warning about invalid transaction if it wasn't known previously. That prevents reporting inherent extrinsics as `invalid` for every block.
> Tone down warnings when resubmitting to the pool.

- Cargo.lock
- client/authority-discovery/Cargo.toml
- client/authority-discovery/src/lib.rs
When receiving more addresses for a given authority than a defined
threshold (5), the authority discovery drops the remaining in order to
prevent a single authority to fill all priority group slots.
> client/authority-discovery: Limit the amount of sentries per authority

- frame/balances/src/lib.rs
This PR is a request from @emielvanderhoek
Right now, the ordering of events from a `transfer` call can be unclear.
For example, when an account is reaped, the order of transactions is:
1. Account Reaped
2. Balance Transferred
But we would expect that the balance `Transfer` event happens first, which then _results_ in an `ReapedAccount` event.
This simply changes the order of actions (in a part of the runtime code which **cannot fail**) to make the order of events more coherent.
> Note: we consciously kept the `NewAccount` event before the transfer. The idea being, first a new account is emitted to the world, and then a transfer is passed to it.
Feedback welcome.
> Change order of events emitted from transfer.

- Cargo.lock
- frame/contracts/rpc/Cargo.toml
- frame/contracts/rpc/runtime-api/Cargo.toml
- frame/contracts/rpc/runtime-api/src/lib.rs
- frame/contracts/rpc/src/lib.rs
The Contracts RPC outputs data in a non-common format (i.e. raw bytes, etc).
This PR fixes the format to be more consistent with the rest of the RPCs.
Please take a look at the tests to see how we serialize it now.
> Fix Contracts RPC output format.

- primitives/sr-arithmetic/src/per_things.rs
Perthing types only derive `PartialOrd` and `Ord` under `std`, that makes it not possible to compare by operators like `<` or `<=` etc in runtime modules.
The workaround I could find is using `.deconstruct()` method, but it's verbose. If no particular reasons, it's better to have `PartialOrd` and `Ord` derives under `no_std`.
https://github.com/laminar-protocol/flowchain/blob/52af7fc619c9fd0576b6f924faa8e3727a0fe550/modules/synthetic-protocol/src/lib.rs#L294
> Perthings: derive PartialOrd and Ord under no_std.

- client/authority-discovery/src/lib.rs
Small follow up to https://github.com/paritytech/substrate/pull/4302#issuecomment-562201549.
> client/authority-discovery: Warn when specifying too many sentry nodes

- client/grafana-data-source/src/lib.rs
This is a lot easier than just disabling the macro entirely.
> Disable record_metrics_slice in grafana macro on wasm

- bin/node/cli/res/flaming-fir.json
Small update to bump protocol id for flaming fir to force a new chain on end nodes.
> New protocol id for flaming fir

- frame/support/procedural/src/storage/genesis_config/builder_def.rs
- frame/support/test/tests/decl_storage.rs
Fix https://github.com/paritytech/substrate/issues/4315
Allow optional storage value builder to build None such as:
```rust
decl_storage!{
Foo build(|config: &GenesisConfig<T>| None): Option<u64>;
}
```
although regular storage value are not supposed to build nothing thus it still can only insert some value:
```rust
decl_storage!{
Foo build(|config: &GenesisConfig<T>| 1): u64;
}
```
> decl_storage: Allow storage value builder to put no value

- Cargo.lock
- client/telemetry/Cargo.toml
- client/telemetry/src/async_record.rs
- client/telemetry/src/lib.rs
By putting that record we are using directly into the crates–internal use only. Leaving a FIXME comment on the top to remove this once the PR has cleared.
Because this is completely internally an update removing this file and replacing the dependency later would only require a patch-level update.
> Remove slog-async Github

- Cargo.lock
- primitives/transaction-pool/Cargo.toml
This was causing a compilation error in `subxt` with a dependency on `sp-transaction-pool-api`. 
```
|
41 | pub use primitives::to_substrate_wasm_fn_return_value;
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `to_substrate_wasm_fn_return_value` in the root
```
Looks like it was defaulting to `no_std` and failing to compile. 
Also `sp-core` is not even used here so have removed it.
Rel https://github.com/paritytech/substrate/pull/4320
> sp-transaction-pool-api: make default std, remove unused sp-core dependency

- .gitlab-ci.yml
- Cargo.lock
- primitives/core/Cargo.toml
fix build error caused by features change of ed25519-dalek
check polkadot in ci will be fixed by #4341
> Fix build for full_crypto

- primitives/sr-io/src/lib.rs
This fixes the inconsistency:
- In Cargo.toml: `disable_allocator`
- In lib.rs: `disable_global_allocator`
> Wrong feature name `disable_allocator` in sr-io

- Cargo.lock
- client/Cargo.toml
> remove unnecessary client-db dependency

- frame/elections-phragmen/src/lib.rs
The `is_defunct_voter` function is intended to check whether all of a given voter's selections are invalid. A selection is valid if it is a candidate in the next round, i.e. if it is a current member or runner-up (and thus automatically added as candidates), or on the candidates list.
However, the function as implemented did not check for runners-up. This PR adds this check to fix the bug, which would have permitted incorrect reports of defunct voters if they only voted for current runners-up. This PR also expands the `can_detect_defunct_voter` test case to catch the bug.
> Including runners-up in check for defunct phragmen voter.

- frame/elections-phragmen/src/lib.rs
Even if they are bounded, I prefer to fix it. From `O(NlogN)` to `O(logN)`.
Removes the use of `members_id` and `runners_up_id` that are linear.
> Improve is_member and is_runner.

- .gitlab-ci.yml
This will fix the problem currently that https://crates.parity.io/
Redirects to: "substrate_service/index.html", when it has been renamed to `sc_service`.
> Update rustdocs landing page

- client/consensus/babe/src/lib.rs
- frame/support/src/storage/mod.rs
Swaps out the linear backoff for an exponential one.
> babe: exponential backoff on missed blocks

- bin/utils/subkey/src/main.rs
- primitives/core/src/crypto.rs
This adds `ss58_address_format` macro, with the following syntax to simplify adding additional variant:
```
[variant] => ([network_id], [description_name], [description_doc])
```
This also adds `KulupuAccountDirect` variant into the list, with id `16`.
> Simplify adding new Ss58AddressFormat variant and add KulupuAccountDirect

- frame/collective/src/lib.rs
A simple oversight means that a refused proposal can never be reproposed.
> Remove proposal when it is refused

- frame/identity/src/lib.rs
This adds two features:
- `SuperOf` public map item, for looking up the super account of a sub-account. Sub-accounts should be able to be looked up directly since the UI has no way of efficiently enumerating them.
- `fn set_account_id` dispatchable call so that registrars are able to reset their account ID.
> Identity module enhancements

- frame/elections-phragmen/src/lib.rs
> Remove incorrect assumption that runners-up were sorted by account

- frame/evm/src/lib.rs
* Provide default implementation for `FeeCalculator` and `ConvertAccountId`, so that using the EVM module is easier.
* Move gas price parameter to dispatch parameter, and change `FeeCalculator` to output minimal gas price. This allows `FeeCalculator` to depend on storage values and thus more flexible.
> pallet-evm: default implementation for FeeCalculator and ConvertAccountId and separate gas price

- client/finality-grandpa/src/communication/mod.rs
- client/finality-grandpa/src/communication/tests.rs
- client/finality-grandpa/src/environment.rs
- client/finality-grandpa/src/lib.rs
- client/finality-grandpa/src/observer.rs
- client/network-gossip/src/bridge.rs
- client/network-gossip/src/lib.rs
Supersedes #4359 
The finality-grandpa module needs two sets of functionalities from the
network:
1. Everything gossip related, e.g. event_stream, write_notification, ...
2. The ability to set a fork sync request for a specific block hash.
Instead of embedding (2) inside of (1) this patch extracts (2) from (1)
having finality-grandpa depend on a `Network` that fulfills the
`network_gossip::Network` trait and that can set block sync requests.
On the one hand this improves the overall structure splitting things
that don't logically belong together. On the other hand it does
reintroduce a lot of trait bounds within finality-grandpa.
> client: Do not set fork sync request via network-gossip

- client/finality-grandpa/src/authorities.rs
- client/finality-grandpa/src/environment.rs
- client/finality-grandpa/src/finality_proof.rs
- client/finality-grandpa/src/import.rs
- client/finality-grandpa/src/light_import.rs
For some reason we were logging some grandpa messages under the `finality` target rather than `afg`. I don't remember any clear reason for doing this and in practice it's one more logging target that we need to think about adding. I changed it so that all messages are logged under the `afg` target.
> grandpa: log everything under afg target

- client/finality-grandpa/src/communication/tests.rs
In the GRANDPA test `good_commit_leads_to_relay` we test the gossip layer by sending a valid commit message and then making sure it is propagated after validation. This test was taking a long time to run, the reason was that we were only connected to one peer, so after receiving the commit from it we would refuse to resend the message to it until a periodic forced broadcast was triggered (which took 5 minutes to trigger). An easy fix is to add another peer to the test environment to whom the commit will be immediately propagated.
> grandpa: fix slow gossip test

- client/rpc-api/src/author/mod.rs
- client/rpc-api/src/system/mod.rs
- client/transaction-pool/graph/src/listener.rs
- client/transaction-pool/graph/src/pool.rs
- client/transaction-pool/graph/src/watcher.rs
- primitives/transaction-pool/src/pool.rs
Resolves: #4434 
Related: #4438 
This PR adds documentation on the `TransactionStatus` type, outlining the ordering of events that may occur on specific transaction.
I've also noticed that `Usurped` and `Dropped` events were not causing stream termination, yet the transaction was no longer in the pool. Technically it may still re-enter the pool, but actually it's the case for every terminating state, and imho the callers should re-subscribe if they are interested. (CC @jacogr hope it's backward compatible for polkadot.js)
Additionally I renamed `Finalized` event to `InBlock` in the code, but kept backward compatibility on the RPC layer. This is an introduction to #4438
> Document TransactionStatus and fix termination conditions.

- primitives/phragmen/src/tests.rs
Tests to make sure the invariants mentioned in https://github.com/paritytech/substrate/issues/4331 about phragmen hold.
> Few extra tests for phragmen

- bin/node/executor/src/lib.rs
- frame/transaction-payment/src/lib.rs
This PR is the result of investigating the fee system in Substrate and possible issues around calculating fees.
When the `TargetedFeeAdjustment` calculation reached `-1`, the fee calculation mechanism would reduce the total fee a user paid to zero.
Instead, we now ensure that the `base_fee` is unaffected by this adjustment multiplier, so even when the network is so un-congested, the user will pay at a minimum some `base_fee`. This adjustment multiplier now only affects the length fee and weight fee of a transaction.
```
final_fee = base_fee + targeted_fee_adjustment(len_fee + weight_fee) + tip;
```
This includes a new test which verifies that the `compute_fee` function behaves as it should in various scenarios with this new formula.
> Fix Fees in Substrate

- frame/balances/src/lib.rs
> Add new event for registering deposits.

- client/cli/src/lib.rs
- client/cli/src/params.rs
- client/rpc-api/src/system/mod.rs
> Warn about using --rpc-external and --ws-external options

- client/consensus/babe/src/lib.rs
Duplicate definition some lines above.
> babe: remove unused slot_duration variable

- .gitlab-ci.yml
spin off of #4377 
It seems unneeded now - integration tests are pretty stable now. At my laptop tests were running for ~1:30 with single test thread and ~0:40 with multiple threads.
> Use multiple threads in integration tests

- frame/system/src/lib.rs
Seems that it might be quite useful (calling two methods that require `ensure_origin` check) and seems implemented for existing `Origin` anyway.
Unfortunately I don't think it's possible to add a bound like this within `decl_module`, so there is no way to only require that for some runtimes.
CC @shawntabrizi
> Add `Clone` bound to the `Origin`.

- Cargo.lock
- bin/utils/subkey/Cargo.toml
- bin/utils/subkey/src/main.rs
- primitives/core/src/crypto.rs
This cleans up definition of `Ss58AddressFormat`, ensuring that all custom ones are only present in the macro invocation, and nowhere else.
> Clean up definition for custom ss58 address formats

- client/authority-discovery/src/lib.rs
> Change log level for DhtEvent::ValueNotFound from warn to debug

- .gitlab-ci.yml
- .maintain/gitlab/check_runtime.sh
CI jobs are failing due to recently introduced shallow clones for ci checks e.g. https://gitlab.parity.io/parity/substrate/-/jobs/333878
Increasing the cloning depth to 100 should be a safe value :crossed_fingers: 
failing refs in local copy:
```
fatal: ambiguous argument 'origin/master...2003b9d8a08c9b9370a94cb0ee3c0f3e05607ce6': unknown revision or path not in the working tree.
```
> ci: increase git cloning depth to 100

- client/transaction-pool/graph/src/base_pool.rs
- client/transaction-pool/graph/src/ready.rs
By looking at the code I found a potential issue with `replace_previous`. The clean up procedure that was supposed to remove all traces of replaced transactions was not correct. The bug was not critical, it could only cause a slight incoherence in the internal pool tracking.
The main bug was assuming that newly imported transaction will always have empty `unlock` collection. Which is not necessarily true, if we replace a transaction in the middle of a chain:
`Tx1 -> Tx2 - > Tx3`, then we replace with `Tx2'` and that transaction should still unlock `Tx3`.
> Fix replace_previous of Ready Transaction Queue.

- primitives/runtime-interface/src/impls.rs
Remove a bit of unnecessary unsafe code. The former version should be literally the same as the current one both logically and performance-wise.
> Remove unnecessary unsafe.

- bin/node/runtime/src/lib.rs
I think this is missed in #4449
> use generated ModuleToIndex type

- Cargo.lock
- bin/utils/subkey/Cargo.toml
- bin/utils/subkey/src/main.rs
- bin/utils/subkey/src/vanity.rs
```
Running `target/debug/subkey generate --words 1234123`
Error:
Invalid number of words given for phrase: must be 12/15/18/21/24
```
> Improve subkey error reporting

- .gitlab-ci.yml
- less dupes:
`&name` is called "the yaml anchor", and used to reduce dupes, like that:
```
jobname:          &name
stage:          test
variables:
var1:         1
script:
- do that
another-jobname:
<<:   *name
script:
- do this
```
> less dupes, cleanup

- Cargo.lock
- bin/node/cli/Cargo.toml
- bin/node/cli/src/cli.rs
- bin/utils/chain-spec-builder/Cargo.toml
- client/cli/Cargo.toml
- client/cli/src/lib.rs
- client/cli/src/params.rs
- client/cli/src/traits.rs
- frame/indices/Cargo.toml
- frame/indices/src/mock.rs
This is just some hotfix to make everything compile. In the future it
will require another pr to not depend on internals of StructOpt, but
that will probably also require some additions to StructOpt itself. To
not break the code again with another StructOpt, this also pins the
StructOpt version.
> Fix cli for structopt 0.3.7 and pin to that version

- utils/wasm-builder/src/wasm_project.rs
Wasm-builder now removes members that point to packages that do not
exist anymore or that were renamed. Up to now, the build would fail and
required manual fixing.
> Make wasm-builder remove invalid members

- frame/metadata/src/lib.rs
Changes in https://github.com/paritytech/substrate/pull/4462 required a
metadata version increment that was forgotten.
> Increase metadata version to 10

- primitives/core/Cargo.toml
- primitives/core/src/ecdsa.rs
- primitives/core/src/hexdisplay.rs
- primitives/runtime/src/lib.rs
- primitives/runtime/src/traits.rs
`MultiSigner` did not compressed the ECDSA public key before hashing it but `MultiSignature` expected that the public key is compressed when verifying a signature. Thus, the signature verification could never succeed. 
This pr changes the following:
- `MultiSigner` compresses the public key before hashing it with `blake256`.
- `Verify for ecdsa::Signature` compresses given public key before comparing it.
- `ecdsa::Public` is now an enum that distinguishes between the full and compressed format.
Fixes: #4498
> Make `MultiSigner` use compressed ECDSA public key

- bin/node/cli/src/service.rs
- client/cli/src/informant.rs
- client/consensus/aura/src/lib.rs
- client/consensus/babe/src/lib.rs
- client/consensus/babe/src/tests.rs
- client/finality-grandpa/src/environment.rs
- client/finality-grandpa/src/import.rs
- client/finality-grandpa/src/lib.rs
- client/finality-grandpa/src/light_import.rs
- client/finality-grandpa/src/observer.rs
- client/finality-grandpa/src/tests.rs
- client/network/src/chain.rs
- client/network/src/protocol.rs
- client/network/src/protocol/sync.rs
- client/network/test/src/lib.rs
- client/network/test/src/sync.rs
- client/rpc/src/author/mod.rs
- client/rpc/src/chain/mod.rs
- client/rpc/src/state/state_full.rs
- client/rpc/src/state/state_light.rs
- client/service/src/builder.rs
- client/service/src/chain_ops.rs
- client/service/src/lib.rs
- client/service/test/src/lib.rs
- client/src/client.rs
- client/src/light/fetcher.rs
- primitives/api/test/benches/bench.rs
- primitives/api/test/tests/runtime_calls.rs
- test-utils/runtime/client/src/trait_tests.rs
- test-utils/runtime/src/lib.rs
Right now Client api consumers request full `ClientInfo` when they only need `sp_blockchain::Info`, this addresses this.
While now it is rather cheap to construct ClientInfo (though it requires shared cache locking and cache structure traversing already), this is expected to be not that cheap (more memory stats, along with I/o stats)
> Refactor Client consumers to use only chain info where needed

- client/network/src/service.rs
I've only recently noticed this mistake. It's definitely meant to be "Service" (as in "NetworkService to NetworkWorker") and not "Server".
> Typo fix: ServerToWorkerMsg -> ServiceToWorkerMsg

- .gitlab-ci.yml
Depends on https://github.com/paritytech/srml-contracts-waterfall/pull/28
Won't work until https://github.com/paritytech/srml-contracts-waterfall/issues/27 is solved. [Proof](https://gitlab.parity.io/parity/srml-contracts-waterfall/-/jobs/339252) that CI passes with al older substrate version.
After, it will make sense to add `strategy:                      depend` and to add this job to a stage between `build` and `publish` stages, to fail pipeline by this job.
> triggers srml-contracts-waterfall ci

- Cargo.lock
- bin/node/cli/Cargo.toml
- client/Cargo.toml
- client/api/Cargo.toml
- client/db/Cargo.toml
- client/db/src/cache/list_storage.rs
- client/db/src/cache/mod.rs
- client/db/src/children.rs
- client/db/src/lib.rs
- client/db/src/light.rs
- client/db/src/utils.rs
- client/src/leaves.rs
- primitives/state-machine/Cargo.toml
- primitives/trie/Cargo.toml
- test-utils/runtime/Cargo.toml
- No more `ElasticArray`
- Columns are now required, and no "default column" notion exists
> Update to new kvdb/trie/memdb versions

- bin/node/cli/src/service.rs
- client/service/src/builder.rs
- client/service/src/lib.rs
Follow up to https://github.com/paritytech/substrate/pull/4284.
Previously one would create a sender and receiver channel pair, pass the
sender to the `build_network_future` through the service builder and
funnel network events returned from polling the network service into the
sender to be consumed by the authority discovery module owning the
receiver.
With recent changes it is now possible to register an `event_stream`
with the network service directly, thus one does not need to make the
detour through the `build_network_future`.
> *: Register network event stream for authority discovery

- .gitlab-ci.yml
I've been asked to run this job only nightly and on merges, anyways it's always failing.
> check_polkadot now runs nightly and on master (merges) only

- client/api/src/client.rs
- client/src/client.rs
With the current definition of the `ForkBlocks` type the correct json definition should be like:
```
"forkBlocks": {
"516510": "0x15b1b925b0..."
}
```
Unfortunately, Serde fails to deserialize this with an error:
`Error: Input("Error parsing spec file: invalid type: string \"516510\", expected u32 at line 3457 column 1")`
Changing the type to a vector of tuples instead makes it work properly:
```
"forkBlocks": [
[516510, "0x15b1b925b0..."]
]
```
This is just a temporary work around as we need this feature for the upcoming Kusama fix and this feature is currently unused (so changing format is a non-issue). I didn't spend too much time to try and figure out why deserialization failed.
Created #4540 so that we find a proper fix for this aftewards and revert to `HashMap`.
> client: hack around fork blocks deserialization issue

- client/service/src/builder.rs
- client/service/src/lib.rs
An helper for creating a client given a config without going through creating the whole service. In particular, we only need a borrow to the config (unlike full service creation), this is helpful in some scenarios since the config isn't cloneable.
> client: helper to create standalone client without service

- client/api/src/backend.rs
- client/db/src/lib.rs
- client/src/client.rs
- client/src/in_mem.rs
- client/src/leaves.rs
- client/src/light/backend.rs
This PR extends the revert functionality to allow reverting past finalized blocks. It also fixes the handling of leaves when reverting blocks.
> client: allow reverting finalized blocks

- bin/node/cli/res/flaming-fir.json
- bin/node/cli/src/chain_spec.rs
- client/api/src/client.rs
- client/db/src/lib.rs
- client/service/src/builder.rs
- client/src/client.rs
- client/src/lib.rs
- client/src/light/mod.rs
- test-utils/client/src/lib.rs
We already have a "whitelist" feature through `ForkBlocks` which allows defining the canonical block at a given height in the chainspec. This PR adds a `BadBlocks` extension that allows defining bad block hashes, the client will refuse to import these blocks.
> client: add a block blacklist extension

- client/src/client.rs
Just fixes a minor typo in docs
> typo: lead -> leave

- client/network/src/protocol/sync.rs
Dumb error message causing confusion.
> Fix error message

- frame/support/src/event.rs
Fixes: https://github.com/paritytech/substrate/issues/4551
> `decl_event` support trailing comma in args

- frame/staking/src/slashing.rs
- frame/staking/src/tests.rs
cc @burdges, @jacogr 
When a validator is slashed, its nominators are currently kicked until explicit re-nomination. This PR causes that not to happen. The phragmén election already pre-filters for votes cast _after_ a validator's most recent slash, so the nominators' votes on the slashed validator will be ignored until next explicit nomination.
The UX here is not ideal, since those votes on slashed validators will be silently ignored. User apps will be able to perform the same check as the staking code - I've spoken with @jacogr about this before, but pinging again here.
> do not chill indirectly-slashed nominators

- client/cli/src/lib.rs
This allows for implementation to preload chain spec before executing any commands.
Required for https://github.com/paritytech/polkadot/pull/733
> Expose load_spec

- client/network-gossip/src/bridge.rs
- client/network-gossip/src/state_machine.rs
`GossipEngine::abort` and thus `ConsensusGossip::abort` are never
called. This patch removes both.
As far as I can tell, Polkadot is not using it. Are there any other
consumers of the functions that I am not aware of?
> client/network-gossip: Remove `GossipEngine::abort` method

- utils/grafana-data-source/src/database.rs
These asserts fail occasionally, and as we're going to remove the embedded metrics server anyway (#4511 etc.), we should just remove them.
> Remove timing based bits of grafana test

- primitives/runtime/src/offchain/http.rs
> Fix Request::new documentation

- Cargo.lock
- client/Cargo.toml
- client/api/Cargo.toml
- client/api/src/backend.rs
- client/api/src/client.rs
- client/api/src/light.rs
- client/cli/src/informant.rs
- client/db/Cargo.toml
- client/db/src/lib.rs
- client/db/src/light.rs
- client/service/src/builder.rs
- client/src/client.rs
- client/src/in_mem.rs
- client/src/light/backend.rs
- client/src/light/blockchain.rs
- utils/browser/Cargo.toml
As a part of #4209, #830
~~Based on not yet published `kvdb`/`kvdb-rockdb`, but can be reviewed~~
> Memory and I/O stats for backend database(s)

- client/finality-grandpa/src/authorities.rs
- client/finality-grandpa/src/environment.rs
GRANDPA needs to keep track of all pending authority set changes across all forks, in order to limit its votes to not be past any authority set change block. If we have multiple pending changes across forks, we restrict our votes to the earliest one.
With BABE sessions are defined in number of slots (not blocks), which means that authority set changes can happen at different block numbers on different forks. Therefore we need to choose the correct limit according to the given round vote base block, to guarantee that we don't pick a lower limit from some other fork.
> grandpa: guarantee that vote limit is never lower than vote base

- frame/system/src/lib.rs
https://github.com/paritytech/substrate/pull/2491 introduced light client friendly events.
It used a trick with the `double_map` api where it was able to clear a single map by removing a single prefix of the `double_map`.
See: https://github.com/paritytech/substrate/issues/2553#issuecomment-493411639
Now that all storage items use `StoragePrefixedMap`, we can now access the `remove_all` API directly from a single map.
This updates the implementation of `EventTopics` to use a single map and the `remove_all` api rather than the `double_map` hack.
> Use single map and `remove_all` for `EventTopics`

- primitives/arithmetic/src/per_things.rs
The macro which generates "generic" per-things had hard written comment about `permill`.
Updated.
> Update `per_thing` docs

- frame/identity/src/lib.rs
Afaik all dispatchable functions need a weight annotation.
Even though weights are gonna be updated later, I prefer to fix it now so we don't forget.
The weight is copy pasted from others functions in the module.
> Add missing weights for Identity module.

- bin/node/cli/Cargo.toml
Polkadot builds wasmtime support by default. Substrate node could do as well.
> Build wasmtime support by default

- client/network-gossip/src/bridge.rs
- client/network-gossip/src/lib.rs
- client/network-gossip/src/state_machine.rs
- client/network-gossip/src/validator.rs
- client/network/src/protocol.rs
Performs a few clean-ups related to the `sc-network-gossip` crate:
- Removes usage of `sc_network::Context`, and directly pass a `&mut dyn Network` instead.
- Since gossiping doesn't use `sc_network::Context` anymore, removes the `Context::send_consensus` method. The `Context` is now used exclusively for the `NetworkSpecialization` stuff, which is hopefully going to disappear in the future as well.
- Moves the `Validator` trait and its related traits and structs to a separate module.
> Clean-ups in the network-gossip crate

- client/api/src/light.rs
- client/db/src/light.rs
- client/src/cht.rs
- client/src/in_mem.rs
- client/src/light/blockchain.rs
- client/src/light/fetcher.rs
closes #4507 
There was a light-specific code that has been assuming that IF `local_storage.header()` returns `None`, AND the `local_storage.status() != Unknown` THEN the header is a part of CHT. If that code has been called during block import, it may have returned `None` from `local_storage.header()` and then, after insertion, may have also passed the `local_storage.status() != Unknown` condition. So the light node was assuming that it is part of CHT, even though it was not.
This PR makes `*_cht_root()` functions return `Ok(None)` if there's no yet CHT for given block => we assume that the header is unknown in the above ^^^ case. Previously these functions were failing, which leading to occasional test failures.
> Fix race on light client when header is read during import

- frame/society/src/lib.rs
society merge has conflicted with new syntax of doublemap https://github.com/paritytech/substrate/pull/4576
Here is the fix.
> Fix master

- bin/node/runtime/src/lib.rs
- frame/elections-phragmen/src/lib.rs
same issue as: https://github.com/paritytech/substrate/pull/4429/files
- Tests already existed; yet they also worked with the wrong binary search since the container to search was just one element. I reviewed all leftover of the `binary_seach_xxx` in that file and they only apply to members and candidates who _are_ actually sorted by account id; This should close this whole issue. 
- With or without this update, in the next Kusama term change the candidate list should be cleaned. Luckily the phragmen implementation also ignores (kinda by luck; needs issue to be cleaned) dupe candidates so we should be fine.
> Fix runners-up candidacy submission check in council

- primitives/io/src/lib.rs
This is a drive-by fix as I'm slowly digging into the code.
We don't use any explicit `#[lang = ...]` items anymore (`panic_fmt` is replaced with now-stable `#[panic_implementation]`, OOM is handled via `alloc_error_handler` feature directly etc.), so I thought it'd be good to remove it for clarity to limit used nightly features.
> Remove now unused `lang_items` feature in IO primitives

- bin/node/runtime/src/lib.rs
- frame/evm/src/lib.rs
- frame/example/src/lib.rs
- frame/support/src/dispatch.rs
- frame/support/src/weights.rs
- frame/utility/src/lib.rs
This allows free transactions to be batched and still be free.
> Improve PaysFee trait and dispatch info logic in utility module

- client/state-db/src/noncanonical.rs
Fixed a couple of potential soundness issues with pinned states in states in state-db
* Pinned state would not pin parent state, so it could still be discarded 
* Pinned state nodes still could be discarded if they had more than one references and only one of the referencing states is pinned.
Fixes https://github.com/paritytech/polkadot/issues/705
> Fixed state pinning in state-db

- frame/support/src/storage/mod.rs
Add a function to migrate values from one type to one another.
In case we fail to migrate one element we return an error with the key that has failed to decoded.
We could also remove values that fail to decode and finish the migration and at the end returning an error saying there is some value that has been removed.
> Add translate function for storage prefixed map.

- client/chain-spec/src/chain_spec.rs
- client/db/src/lib.rs
- client/src/client.rs
- client/src/lib.rs
- client/src/light/mod.rs
- frame/staking/src/lib.rs
- test-utils/client/src/lib.rs
Instead of having these weird implementation of `BuildStorage for
&ChainSpec` we should just take the `genesis_storage` by ref. The
`BuildStorage` trait changed some time ago to take a self ref anyway,
instead of a self value.
Also fixes warnings in frame-staking
> Take `genesis_storage` by ref

- client/network/src/protocol.rs
- client/rpc/src/state/state_light.rs
Fixes two related issues:
1) there's no need to issue empty `RemoteRead` && `RemoteReadChild` requests from light node and it turns current UI (at https://polkadot.js.org/apps/#/) does this;
2) I've recently introduced invalid `trace!()` call in network (when we moved to single-key-in-remote-request to multiple-keys-in-single-remote-request) which leads to panic when invalid request is received  over network :(
> Do not issue empty remote read request + fix rr-related trace on full node

- client/offchain/src/lib.rs
This will help debugging possible issues when we migrate to future versions.
1. Display an error if version is not supported.
2. Support only version 1 and 2. Will error out when we ever switch to `v3`.
> Make offchain worker calls more future proof.

- client/network/src/service.rs
(I hesitated to label this PR as "insubstantial")
Adds more `trace!` logging to the network.
The most important one is the `Failed to reach ...`, which might help figuring out why nodes can't connect to each other. Most of the time the error is going to be either a boring "timeout" or a boring "connection rejected", but sometimes it's a "peer id mismatch", in which case it's important to know.
Additionally, we now use the `next_event()` method on the `Swarm`, which guarantees that `None` cannot be returned.
> Add more logging to the network

- frame/balances/src/lib.rs
- frame/transaction-payment/src/lib.rs
Fixes https://github.com/paritytech/substrate/issues/4402
This PR adds a simple check before relevant balances functions that the "action to be performed" would result in a change.
For example: the function `can_slash` would normally query the free balance of a user and do a comparison function. However, if `can_slash` has `value.is_zero()`, we can simply return true without doing a storage read.
Further, a function like `set_lock` used to write zero amount locks, which we now skip. Same with `add_vesting_schedule`.
Ultimately, this PR also catches situations where some external logic, like the fee system, would try to do some action into the balances module with value zero. This may trigger unexpected side effects like emitting a `ReapedAccount` event when nothing changed in the system. …
> Return early when fees/balances/values are zero

- bin/node/cli/src/service.rs
- client/basic-authorship/src/basic_authorship.rs
- client/basic-authorship/src/lib.rs
- client/consensus/aura/src/lib.rs
- client/consensus/babe/src/lib.rs
- client/consensus/babe/src/tests.rs
- client/consensus/pow/src/lib.rs
- client/consensus/slots/src/lib.rs
- primitives/consensus/common/src/lib.rs
Needed for an upcoming Polkadot refactor and is strictly more general. This API was always intended to be used in an async context, so it doesn't break any underlying assumptions.
> Make Proposer instantiation potentially async.

- bin/node/cli/src/cli.rs
- client/cli/src/lib.rs
Probably as a workaround until better refactoring
Fixes #4623
> Use default in-memory keystore for commands that don't use keystore

- Cargo.lock
- client/finality-grandpa/Cargo.toml
- client/finality-grandpa/src/lib.rs
- client/finality-grandpa/src/tests.rs
- client/finality-grandpa/src/voting_rule.rs
We already had a voting rule that made sure that the GRANDPA voter would vote at most for `best_block - 1`. This PR changes the rule so that the distance from best block is arbitrary. Additionally, we change the default distance to be 2 blocks. 
This is useful for Kusama in case we need to easily revert a borked runtime upgrade triggered through democracy.
> grandpa: generic voting rule for backing off from best block

- client/network/test/src/sync.rs
This test starts by waiting for nodes 0 and 1 to be major-syncing.
However what I think sometimes happens is that the background task fully syncs these nodes and that therefore `is_major_syncing` returns false. The test then freezes because it's still waiting for the major syncing to happen even though it's already finished.
Since this test is entirely single-threaded, it's still unclear to Arkadiy and me why this happens only from time to time. EDIT: probably because libp2p 0.14 spawns connection tasks on a thread pool no matter what
> Make the sync_cycle_from_offline_to_syncing_to_offline test non flaky

- docs/CODEOWNERS
This adds myself to CODEOWNERS file for pow and EVM module, so that I can receive specific notifications.
> CODEOWNERS: Add myself to pow and EVM module

- client/finality-grandpa/src/communication/gossip.rs
- client/finality-grandpa/src/communication/mod.rs
- client/finality-grandpa/src/communication/tests.rs
- client/finality-grandpa/src/lib.rs
- client/finality-grandpa/src/observer.rs
- client/finality-grandpa/src/tests.rs
The `finality-grandpa` `GossipValidator` is called by the `GossipEngine`
in a synchronous fashion on each gossip message. Its main task is to
decide whether to gossip the given message on, or whether to drop it.
In addition it also updates the reputation of a node's peers based on
the incoming gossip messages. To do so it needs to be able to report the
reputation change which it does through an unbounded channel (in order
to stay synchronous).
Previously the receiving side of this channel would be handled by a new
task, polling the channel and forwarding the changes to a clone of the
`GossipEngine` that it would own.
Instead the receiver of the above mentioned channel is now being polled
by the `NetworkBridge` within its `Future::poll` implementation.
Reputation changes are reported …
> client/finality-grandpa: Reintegrate gossip validator report stream

- Cargo.lock
- bin/node/cli/Cargo.toml
- frame/society/src/lib.rs
- frame/society/src/tests.rs
There is a fringe scenario where a member might be asynchronously removed from the membership pool before a vote is tallied. (i.e. through the Defender lifecycle).
In this case, the votes that this user may have stored will not be cleaned up during the rotation cycles.
In addition to `take` while iterating over members to calculate votes, we also call `remove_all` on the vote storage items to really make sure all votes are gone after we have finished tallying.
This fixes the behavior for both `Votes` and `DefenderVotes`.
> Society: Ensure all votes are removed after tally

- frame/transaction-payment/src/lib.rs
We want some additional custom logic on tx fee but don't want to copy & paste the whole transaction payment module. This will allow us to reuse some logic.
The module we are implementing: https://github.com/AcalaNetwork/Acala/issues/58 https://github.com/AcalaNetwork/Acala/pull/70
> make compute_fee public

- primitives/runtime-interface/src/impls.rs
- primitives/runtime-interface/src/lib.rs
- primitives/runtime-interface/src/pass_by.rs
Adds a table to the rustdoc that shows how each individual type is
passed between the wasm and the host side.
> `sp-runtime-interface` add table about FFI types

- client/network/src/protocol/specialization.rs
- client/network/test/src/lib.rs
Right now it is defined in `sc-network-test`, but I need to use it for tests within `sc-network`. We can avoid a dependency loop by moving it to `sc-network`.
cc'ing @rphmeier because there might be a conflict with #4665
> Move DummySpecialization to sc-network

- frame/staking/src/lib.rs
- frame/staking/src/migration.rs
- frame/staking/src/slashing.rs
- frame/staking/src/tests.rs
fixes #4636 - I was wrong in my issue comment about the migration not being possible, due to prefixed map changes I wasn't aware of.
> keep nominations after getting kicked with zero slash

- client/network/src/protocol.rs
- client/network/src/protocol/message.rs
Needed for #4665 
To be removed in a future PR, once Polkadot/Cumulus no longer requires this for its collator protocol.
> deprecate chain_status field of network handshake

- client/finality-grandpa/src/communication/gossip.rs
Applying review suggestion from https://github.com/paritytech/substrate/pull/4661/files#r368046058.
@rphmeier I think the members of the struct are self-explanatory. Let me know if you still want them documented.
> client/finality-grandpa/communication: Add doc comment for PeerReport

- .gitlab-ci.yml
increase test log file retention to 144h
cannot debug https://gitlab.parity.io/parity/substrate/-/jobs/356316/artifacts/file/cc589213_int_failure.log anymore
> ci: increase retention for logs of tests to 144 hours

- primitives/core/src/ecdsa.rs
- primitives/runtime/src/lib.rs
- primitives/runtime/src/traits.rs
Some fixes after: https://github.com/paritytech/substrate/pull/4502
This removes the unwanted `expect`s from `MultiSigner`. Instead we
convert from full to compressed in `TryFrom` and can return an error on
invalid input.
> Only support ECDSA compressed public keys

- bin/node/cli/src/cli.rs
Otherwise using tokio sockets or timers will panic.
Note that this doesn't affect Polkadot of `node-template` because they do `Runtime::new` instead of using a `RuntimeBuilder`.
> Call enable_all() when building tokio runtime

- Cargo.lock
- bin/node-template/runtime/build.rs
- bin/node/cli/src/cli.rs
- bin/node/runtime/build.rs
- client/cli/src/execution_strategy.rs
- client/cli/src/lib.rs
- client/cli/src/params.rs
- client/executor/runtime-test/build.rs
- primitives/runtime-interface/test-wasm/build.rs
- test-utils/runtime/build.rs
- utils/wasm-builder/Cargo.toml
- utils/wasm-builder/src/wasm_project.rs
This pr makes debug builds more usable in terms of `cargo run -- --dev`.
1. `--dev` activates `--execution native`, iff `--execution` is not
given or no sub `--execution-*` is given.
2. It was probably a mistake to compile WASM in debug for a debug build.
So, we now build the WASM binary always as `release` (if not requested
differently by the user). So, we trade compilation time for a better
debug experience.
> Make debug builds more usable

- client/finality-grandpa/src/communication/mod.rs
- client/finality-grandpa/src/justification.rs
GRANDPA messages are localized when encoded, to include the round and set id they refer to. This means that given a message and a signature there's an extra step of intermediary encoding needed to do the verification. This PR re-uses the buffer used for encoding when verifying multiple messages at once (i.e. commits, catch-up requests and justifications).
@arkpar reported that checking of compact commits was showing up on the profiler as performing a lot of allocations.
> grandpa: reduce allocations when verifying multiple messages

- bin/node-template/src/cli.rs
- bin/node/cli/src/cli.rs
- client/service/src/builder.rs
- client/service/src/config.rs
- client/service/src/error.rs
- client/service/src/lib.rs
- client/service/test/src/lib.rs
- utils/browser/src/lib.rs
Hopefully fixes the performance issues that Polkadot was having.
One issue that we have in master right now is that all the tasks go through this path:
- https://github.com/paritytech/substrate/blob/a90c72e6d7088d0473670bf74253c65791411589/client/service/src/lib.rs#L334
- https://github.com/paritytech/substrate/blob/a90c72e6d7088d0473670bf74253c65791411589/client/service/src/lib.rs#L339-L341
In other words, everything is single-threaded (except the networking).
In this PR, we now pass a "tasks executor" through the `Configuration` struct.
It is set up to be a tokio runtime, or the `spawn_local` function of `wasm_bindgen_futures`, ~~or a threads pool by default, or local polling if all else fails~~ EDIT: removed fallbacks after review.
**Important**: this executor is stored within the …
> Pass an executor through the Configuration

- frame/contracts/src/exec.rs
- frame/contracts/src/lib.rs
- frame/contracts/src/rent.rs
- frame/contracts/src/tests.rs
- frame/contracts/src/wasm/mod.rs
- frame/contracts/src/wasm/runtime.rs
Improves contracts PALLET by
- adds two new events: `Restored` and `Evicted`
- `Event::Evicted(AccountId, bool)`
1. `contract: AccountID`: The account ID of the evicted contract.
1. `tombstone: bool`: True if the evicted contract left behind a tombstone.
- `Event::Restored(AccountId, AccountId, Hash, Balance, bool)`
1. `donor: AccountId`: The Account ID of the restoring contract
1. `dest: AccountId`: The account ID of the restored contract
1. `code_hash: Hash`: The code hash of the restored contract
1. `rent_allowance: Balance`: The initial rent allowance of the restored contract
1. `success: bool`: If restoration was successful
- rename `Event::Contract` to `Event::ContractExecution` so that it is clear that the event was triggered by a contract execution
- improving error message that …
> contracts: New contract events + unconfusions

- bin/node-template/runtime/build.rs
- bin/node-template/src/main.rs
- ancient attribute removed
- license preamble from node-template/build.rs removed (not sure here)
> Couple of improvements on node-template

- client/finality-grandpa/src/communication/mod.rs
The GRANDPA client sends telemetry events upon receiving a new vote or commit. These events are then used to produce a visualization of the round state. With a high number of authorities, say 150, every node will be sending ~300 telemetry events per round, for a total of ~45000 events. Currently on the Kusama network, a round usually takes less than a second to complete. @arkpar mentioned that formatting of these telemetry events showed up in the memory profiler. With a validator set of that size the visualization UI is also unusable, therefore we will filter sending these telemetry events if the validator set size is bigger than 10.
> grandpa: filter some telemetry events on larger voter sets

- primitives/runtime-interface/src/impls.rs
- primitives/runtime-interface/src/lib.rs
- primitives/runtime-interface/test-wasm/src/lib.rs
- primitives/runtime-interface/test/src/lib.rs
This implements support for `u128`/`i128` as parameters/return value in
runtime interfaces. As we can not pass them as identity, as for the
other primitives types, we pass them as an pointer to an `[u8; 16]` array.
> Support `u128`/`i128` in runtime interface

- Cargo.lock
- Cargo.toml
- client/executor/common/Cargo.toml
- client/executor/common/src/error.rs
- client/executor/runtime-test/Cargo.toml
- client/executor/runtime-test/src/lib.rs
- client/executor/src/lib.rs
- client/executor/wasmi/Cargo.toml
- client/executor/wasmi/src/lib.rs
- client/executor/wasmtime/Cargo.toml
- client/executor/wasmtime/src/function_executor.rs
- primitives/allocator/Cargo.toml
- primitives/allocator/src/error.rs
- primitives/allocator/src/freeing_bump.rs
- primitives/allocator/src/lib.rs
- primitives/core/src/lib.rs
- primitives/runtime/src/traits.rs
- primitives/sandbox/src/lib.rs
- primitives/wasm-interface/Cargo.toml
- primitives/wasm-interface/src/lib.rs
This moves the wasm-allocator (`FreeingBumpHeapAllocator`) into its own
crate `sp-allocator`. This new crate can theoretically provide multiple
different allocators. Besides moving the allocator, this pr also makes
`FreeingBumpHeapAllocator` compile on `no_std`.
> Move "wasm" allocator into its own crate

- bin/node/executor/tests/common.rs
Instead of getting a transaction root mismatch at the end of the block execution, you will get a nice panic message, which might save you some nerves and time units.
> Add fool protection and comment construct_block

- client/finality-grandpa/src/communication/mod.rs
- client/finality-grandpa/src/environment.rs
- client/finality-grandpa/src/tests.rs
`round_communication` returns a `Sink` and a `Stream` for outgoing and
incoming messages. The messages send into the `Sink` are forwarded down
to the network as well as send back into the `Stream` to ensure the node
processes its own messages.
So far, to send messages into the `Sink` back into the `Stream`, an
unbounded channel was used. This patch updates `round_communication` and
`OutgoingMessages` to use a bounded channel.
This is part of a greater effort to reduce the number of owners of
components within `finality-grandpa` and `network` as well as to reduce
the amount of unbounded channels. For details see d4fbb897c and
f0c18520a.
> client/finality-grandpa: Make round_communication use bounded channel

- bin/node/testing/src/client.rs
- client/block-builder/src/lib.rs
- client/src/block_rules.rs
- client/src/client.rs
- client/src/lib.rs
- primitives/runtime/src/traits.rs
- test-utils/client/src/lib.rs
- test-utils/runtime/client/src/lib.rs
This slightly refactors how client processes fork_blocks/bad_blocks internally, and also puts those under tests
> Refactor and test spec block rules

- frame/contracts/src/exec.rs
- frame/contracts/src/lib.rs
- frame/contracts/src/wasm/mod.rs
- frame/contracts/src/wasm/runtime.rs
This add the `ext_tombstone_deposit` to the contract host API to make it possible for smart contracts to query the amount of balance they need to create a tombstone upon eventual eviction.
This API is required since without it users cannot determine precisely what `rent_allowance` they should minimal choose in order to be guaranteed to create a tombstone upon contract eviction.
> [contracts] Add ext_tombstone_deposit

- bin/node/runtime/src/lib.rs
Small follow-up on PR #4722 to bump `spec_version` and `impl_version` respectively.
> [contracts] minor follow-up on PR #4722

- frame/recovery/src/lib.rs
Exposes the recovery pallet errors in the metadata.
> Expose recovery module errors in metadata

- client/rpc-api/src/author/error.rs
- client/transaction-pool/graph/src/pool.rs
- client/transaction-pool/src/lib.rs
- primitives/transaction-pool/src/pool.rs
So open mainly to discuss the decision
1. Combining async-await with trait implementation might force to write some lifetime bounds in both trait and trait impl, and probably also will need to propagate some bounds to the consumers.
2. But async code greatly improves thanks to async-await
So I wonder if we can avoid (1), which I hope, or is it tolerable, which I don't think so.
(Made pr against my other branch so that diff is not crazy)
> Async/await in transaction-graph

- frame/support/procedural/src/storage/parse.rs
- frame/support/procedural/tools/derive/src/lib.rs
- frame/support/procedural/tools/src/syn_ext.rs
Small step for https://github.com/paritytech/substrate/issues/3788
This is a small PR that improve the current state of parsing in decl_storage.
* removing of `Opt` struct in syn_ext because the error message can hide valuable message, example:
```diff
-               pub BlockHash get(fn block_hash) build(|_| vec![(T::BlockNumber::zero(), hash69())]): map T::BlockNumber => T::Hash;
+               pub BlockHash get(fn block_hash) build(|_| { let a=;vec![(T::BlockNumber::zero(), hash69())]}): map T::BlockNumber => T::Hash;
```
Before:
```
error: expected `:`
--> frame/system/src/lib.rs:443:36
|
443 |         pub BlockHash get(fn block_hash) build(|_| { let a=;vec![(T::BlockNumber::zero(), hash69())]}): map T::BlockNumber => T::Hash;
|                                          ^^^^^
``` …
> Improve decl storage parsing

- client/executor/src/integration_tests/mod.rs
- client/executor/src/lib.rs
- client/executor/src/wasm_runtime.rs
- client/executor/wasmi/src/lib.rs
- client/executor/wasmtime/src/runtime.rs
- client/executor/wasmtime/src/util.rs
This is a quick and dirty implementation of the wasmtime counterpart of https://github.com/paritytech/substrate/pull/4550. This is aimed to unblock polkadot progress while we are waiting #4686.
The idea is that we employ parity-wasm to extract all the imports and do the resolving ourselves, then we collect all the missing function imports and create modules and stubs for them.
> Cursed implementation of allowing missing imports on wasmtime

- frame/aura/src/lib.rs
- frame/session/src/lib.rs
- frame/sudo/src/lib.rs
Fixes #4574 by removing references to the no-longer-existant `frame_consensus`.
Should anything more be done here? The docs for Aura used to say:
> The Consensus module does not relate directly to Aura, but serves to manage offline reporting by implementing `ProvideInherent` in a similar way.
> Remove references to frame_consensus from docs

- client/network/src/protocol.rs
- client/network/src/service.rs
- client/network/test/src/lib.rs
- client/service/src/builder.rs
- client/service/src/lib.rs
- client/transaction-pool/graph/src/base_pool.rs
- client/transaction-pool/graph/src/future.rs
- client/transaction-pool/graph/src/pool.rs
- client/transaction-pool/graph/src/ready.rs
- client/transaction-pool/graph/src/validated_pool.rs
- client/transaction-pool/src/lib.rs
- primitives/transaction-pool/src/pool.rs
Currently iterations over the transaction pool to propagate transactions are quadratic (number of new transactions * total length of transaction pool). 
This triggers propagations only for specific transactions.
Note that entire transaction pool content is periodically propagated anyway (once in 3 seconds).
> Fix quadratic iterations over transaction pool

- Cargo.lock
Compared to v0.4.0 connection reset errors are logged on debug level.
> Update yamux to version 0.4.1

- client/src/call_executor.rs
This PR makes sure that `backend.destroy_state` is being called even if the call returns an error.
Seems that the consequences could be unsynchronized cache or incorrect usage reporting (so nothing super bad afaiu).
Long term solution would rather be to have a guard that does that on `Drop`, but I've heard that @arkpar might be investigating this already.
> Make sure destroy_state is called in case of errors.

- bin/node/runtime/src/lib.rs
- frame/executive/src/lib.rs
- frame/system/src/lib.rs
- primitives/runtime/src/traits.rs
Before we printed the error of a transaction only when importing a
block, this pr changes it to print the error also at building the block.
> Print extrinsic failed error always, not just on import

- bin/node-template/runtime/src/template.rs
This PR demonstrates the `decl_error!` macro in the TemplateModule. The big changes are:
* Adds a decl_error block
* Adds a dispatchable call which throws errors under appropriate circumstances
* Updates language from module to pallet
* Adds a test to ensure the proper error is thrown in a particular case.
> Add decl_error to template module

- bin/node/runtime/src/lib.rs
- primitives/core/src/crypto.rs
Thank you for your work on substrate!
As discussed in the Substrate Builder's Program call, we would love to use our own network identifier for Centrifuge Chain. 
There are multiple reasons for that, the main one is to prevent reusage across networks, decreasing the value at risk if a private key is lost. Also it allows us to easily identify Centrifuge addresses, which will start with `4b` to `4h`. 
Looking forward to hear your feedback!
> Add SS58 network identifier for Centrifuge

- Cargo.lock
- client/offchain/src/lib.rs
prints out the results of `has_api_with` either be it `Ok(bool)` or the errors. This should help debug `version:0` issues observed on some Kusama nodes.
> Display `has_api_with` results if invalid version of Offchain Workers is detected.

- bin/node/runtime/src/lib.rs
- frame/generic-asset/src/lib.rs
The generic asset create extrinsic duplicated code that was already in `create_asset`.
This is a simple refactoring to make generic asset a tiny bit DRY-er.
No functional changes made.
> Remove unnecessary duplication in generic asset create

- Cargo.lock
- client/offchain/src/lib.rs
- client/rpc-api/src/offchain/error.rs
- client/rpc-api/src/offchain/mod.rs
- client/rpc/Cargo.toml
- client/rpc/src/offchain/mod.rs
- client/rpc/src/offchain/tests.rs
- client/service/src/builder.rs
- primitives/core/src/offchain/mod.rs
@tomusdrw 
This RP is for RPC api to set/get offchain local storage, See aslo https://github.com/paritytech/substrate/issues/4420.
> RPC api for offchain storage

- frame/bridge/Cargo.toml
- frame/bridge/src/lib.rs
- frame/bridge/src/storage_proof.rs
I've rebased the `hc-jp-bridge-module` branch onto `master` from last week-ish, and now in this PR I've make some changes to make the pallet compile. The two main things are using the new `decl_error!` changes introduced by Basti, and updating dependencies to use their 2.0.0 versions.
> Update bridge pallet to work with the (almost) lastest master

- client/cli/src/lib.rs
- client/cli/src/params.rs
A light client can not be a validator, so we should not set `authority
== true` in dev mode.
> Don't run dev light client as validator

- Cargo.lock
- bin/node-template/src/service.rs
- bin/node/cli/src/service.rs
- client/service/Cargo.toml
- client/service/src/builder.rs
- client/service/src/lib.rs
- client/transaction-pool/Cargo.toml
- client/transaction-pool/src/api.rs
- primitives/consensus/common/Cargo.toml
- primitives/consensus/common/src/import_queue/basic_queue.rs
This adds names to tasks and integrates the `futures-diagnose` tool into Substrate.
Start your node with the `PROFILE_DIR=profiles` environment variable, and `futures-diagnose` will create a directory named `profiles` that will contain a trace of all the future tasks being executed in Substrate (at least, all the tasks that got wrapped around `futures-diagnose`, I hope I didn't forget any).
You can then open the traces by starting Chrome and browsing to `chrome://tracing`. There's a load button top.
Example output:
The X axis is the time, and the Y axis is the thread number.
Each block represents a task being polled. Here we can see the the import queue monopolizes an entire thread (unsurprisingly, this is while syncing). The little green lines are networking and telemetry sockets being …
> [Maybe controversial?] Add diagnostics to tasks

- client/api/src/light.rs
- client/consensus/aura/src/lib.rs
- client/executor/src/integration_tests/mod.rs
- client/rpc/src/state/state_light.rs
- client/service/src/builder.rs
- client/transaction-pool/graph/benches/basics.rs
- frame/contracts/src/wasm/prepare.rs
- primitives/arithmetic/benches/bench.rs
- primitives/core/benches/bench.rs
- primitives/phragmen/benches/phragmen.rs
- primitives/runtime/src/generic/era.rs
- primitives/state-machine/src/stats.rs
Change spaces to tabs, add missing trailing new lines and tidy up a comment.
> Chores: clean up indentation problems

- frame/support/procedural/src/storage/storage_struct.rs
- frame/support/test/tests/final_keys.rs
StoragePrefixedMap means a storage has all its value after a prefix
.
But for the linkedmap the value is different from `#value_type` as the actual value stored is `#values_type++Option<previous_key>++Option<next_key>`
and also there is a head key which is after another prefix.
This creates 2 bugs:
* remove_all doesn't remove the head.
* translate actually removes all `Option<previous_key>++Option<next_key>`, breaking the linkedmap.
We should implement those functions in storagelinkedmap directly.
> LinkedMap doesn't implement StoragePrefixedMap

- primitives/core/src/crypto.rs
We'd like to add a special SS58 format identifier for [SubstraTEE](https://github.com/scs/substraTEE) because addresses for chain-isolated SubstraTEE accounts should never be published. We think it is better to clearly distinguish between accounts to be used on-chain and those only to be used within enclaves (what we called "incognito" accounts in our [private-tx example](https://github.com/scs/substraTEE/blob/master/M5_DEMO.md))
> adding a ss58 format for SubstraTEE

- client/network-gossip/Cargo.toml
- client/network/Cargo.toml
This is a very stupid pull request, but every time I have to touch this Cargo.toml I find it messy and hate that it's not ordered alphabetically.
> Order network dependencies alphabetically

- client/finality-grandpa/src/observer.rs
Patch d4fbb897c reintegrated the periodic neighbor packet worker, by
moving its logic into a `Future` implementation on `NetworkBridge` which
needs to be polled by its upper layer.
Polling by the upper layer was implemented within the `Future`
implementation of the `VoterWork` struct but not within the `Future`
implementation of the `ObserverWork` struct. This patch adds polling of
the `NetworkBridge` to the latter.
Without this bugfix nodes running as a Grandpa Observer don't report
reputation changes to the underlying network and don't send neighbor
packets.
> client/finality-grandpa/src/observer: Poll NetworkBridge

- bin/node-template/src/cli.rs
- bin/node-template/src/service.rs
- bin/node/cli/src/cli.rs
- client/finality-grandpa/src/lib.rs
- client/network/test/src/lib.rs
There is one left that I don't really know where it's coming from. My suspicion is that it's the `codec` derive code that generates a code with this unused variable. That should probably be fixed in upstream `codec` crate.
```rust
warning: unused variable: `message`
--> primitives/runtime/src/lib.rs:376:3
|
367 |       /// A custom error in a module
|  _____-
368 | |     Module {
369 | |         /// Module index, matching the metadata module index
370 | |         index: u8,
...   |
375 | |         #[allow(unused_variables)] // most likely caused by codec(skip)?
376 | |         message: Option<&'static str>,
| |         ^^^^^^-
| |_______________|
|                 help: try ignoring the field: `message: _`
|
= note: `#[warn(unused_variables)]` on by default
```
> Fix warnings.

- .maintain/check_for_exit.sh
I don't see any good reason to build with --release to test this but this step takes 8-8:30 min on the CI and I suspect we would save some time by using the debug build instead.
> Remove --release from check_for_exit.sh

- .maintain/gitlab/check_runtime.sh
To my knowledge, we don't keep wasm blobs checked in anymore.
> Remove notices regarding wasm file in check_runtime.sh

- primitives/core/src/sr25519.rs
So that `verify(..) { true }` won't pass all suite
> Add negative tests for signatures

- .maintain/rename-crates-for-2.0.sh
I was using this [script](https://github.com/paritytech/substrate/blob/master/.maintain/rename-crates-for-2.0.sh) as a reference of the crate name changes, and found a couple of outdated names:
```
sc-api       =>  sc-client-api (./client/api)
sc-database  =>  sc-client-db  (.client/db`)
```
> Update to the latest crate names

- frame/contracts/src/rent.rs
This is follow-up to #4754 and #4733.
Runtime version doesn't need to be updated.
> Small follow-up docs improvements in rent module

- client/api/src/notifications.rs
- client/cli/src/node_key.rs
- frame/staking/reward-curve/src/lib.rs
Fix the compiler warning:
```
warning: this method call currently resolves to `<&[T; N] as IntoIterator>::into_iter` (due to autoref coercions), but that might change in the future when `IntoIterator` impls for arrays are added.
--> client/cli/src/node_key.rs:169:28
|
169 |             NodeKeyType::variants().into_iter().try_for_each(|t| {
|                                     ^^^^^^^^^ help: use `.iter()` instead of `.into_iter()` to avoid ambiguity: `iter`
|
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #66145 <https://github.com/rust-lang/rust/issues/66145>
```
Note that all instance of this code are in test so that doesn't even matter to right that this could be …
> Remove ambiguous into_iter

- primitives/runtime/src/generic/unchecked_extrinsic.rs
to be able to use the ChainApi RPC from the client side. Of course guarded behind `std`.
> Adding Serde Deserialisation to UncheckExtrinsics

- Cargo.lock
- client/finality-grandpa/Cargo.toml
- client/finality-grandpa/src/communication/mod.rs
- client/finality-grandpa/src/communication/tests.rs
- client/finality-grandpa/src/observer.rs
Same as #4778, except with nits fixed.
> client/finality-grandpa: Add regression test for observer polling network (was #4778)

- client/network/src/behaviour.rs
It seems that we're actually getting other implementations trying to connect to our nodes :tada: 
Therefore, let's remove the warning that pops when we detect a foreign object.
> Remove warning about connecting to non-Substrate nodes

- utils/fork-tree/src/lib.rs
(Split out of #4600, for easier review/merge.)
This adds support to get mutable references of `Node` in a `ForkTree`, by using a helper method `find_node_index_where` that returns the indexes to access the node. Mutable reference is needed for consensus such as Sassafras, because we need to push VRF proofs after the epoch data is created.
> fork-tree: add support for find_node_mut_where

- Cargo.lock
- primitives/arithmetic/fuzzer/Cargo.lock
This pulls in the latest release of *ring* and also removes some
duplicate dependencies.
> Bump dependencies

- client/consensus/pow/src/lib.rs
- primitives/consensus/common/src/block_import.rs
- primitives/consensus/common/src/error.rs
Use built-in rust dynamic types `Box<dyn Any>`. This avoids the extra step of encoding/decoding.
> block_import: switch to Box<dyn Any> for intermediates representation

- primitives/state-machine/src/ext.rs
Prior to this PR, calling `child_storage_hash` would not work. The function is actually unused by runtime macros and is only exposed to the rpc, so it seems safe to fix it.
> Fix call to backend in child_storage_hash

- primitives/core/src/sr25519.rs
When messing with the signature, we need to make sure that we acutally
mess-up the signature. As the generated private/public key is random,
the signature is random as well. It can happen that `bytes[0] ==
bytes[2]` which makes the test fail. We fix this problem by just
inverting the bytes at `0` and `2`.
> Fix flaky messed signature test

- Cargo.lock
- bin/node/runtime/src/lib.rs
- frame/evm/src/lib.rs
cc @danforbes
Currently it's not trivial to fetch the created address after contract creation. This PR adds `Event::Created(H160)` so that the address is apparent.
> pallet-evm: log created address

- client/network/src/debug_info.rs
- client/network/src/discovery.rs
- client/network/src/protocol.rs
- client/network/src/protocol/legacy_proto/tests.rs
I realized this right after opening #4828 
Fixes an overlook: at several places we have manual implementations of `NetworkBehaviour` that wouldn't redirect events to their underlying codes.
In particular, this means that we wouldn't notify Kademlia when we fail to reach a node.
> Fix missing overrides of NetworkBehaviour

- client/network/src/transport.rs
It's always been intended that we deprecate secio in favour of noise. Noise has been working in production for the past six months to a year, without causing any issue. We can say it's working.
Let's remove secio before we ship Substrate 2.0, in order to avoid having to make a networking breaking change afterwards.
This unfortunately breaks the browser stuff (cc @expenses). The intent is to restore it as soon as possible by doing https://github.com/libp2p/rust-libp2p/issues/1414.
> Remove support for secio

- client/network/src/discovery.rs
Kusama validators have been reporting that the listening socket sometimes isn't open anymore after a while.
We currently don't print any error when the socket reports an error. This PR fixes that.
> Print an error if listener is closed

- primitives/application-crypto/Cargo.toml
- primitives/io/src/lib.rs
- primitives/sandbox/src/lib.rs
- primitives/std/src/lib.rs
- primitives/std/without_std.rs
Removes all instances of usage `core_intrinsics`. In two cases they were really useless. In the third case, we could substitute it with a call to `core::arch::wasm32::unreachable` which is stable.
One little step towards https://github.com/paritytech/substrate/issues/1252
The behavior hasn't changed, thus no bumping of runtime is required.
> Get rid of in-substrate usages of `core_intrinsics` feature

- client/executor/common/src/sandbox.rs
- client/executor/wasmi/src/lib.rs
- client/executor/wasmtime/src/function_executor.rs
Two changes basically which can be reviewed commit-by-commit. 
1. Don't require `store` and `store_mut` impl by `SandboxCapabilities`. This is achieved by doing some borrowck gymnastics introducing separate structures.
2. Don't require `allocate`, `deallocate`, `read_memory` and `write_memory` since those are already provided by the `FunctionContext` and practically `SandboxCapabilities` implements it. So I just have added an explicit requirement for that.
I think we could do better by abstracting more common logic, but I will save that for another day.
> executor: Simplify the SandboxCapabilities interface

- bin/node/runtime/src/lib.rs
The current implementation of the finality tracker can only track finality using a window of the last 100 blocks, with 3s block times this means that any GRANDPA stall longer than 5 minutes triggers a forced authority set change. This feature is currently unused in Polkadot and we don't have plans to use the automatic fallback anytime soon (it would require changing the finality tracker implementation to efficiently allow tracking longer windows), and instead we plan on implementing a way to manually trigger a forced change (which on Kusama/Polkadot would happen through democracy). Having this enabled makes it harder to diagnose any finality issues introduced by recent changes / test builds on Flaming Fir since the authority set will be forcefully changed after any temporary stall.
I …
> node: disable grandpa automatic finality fallback

- primitives/runtime-interface/src/impls.rs
- primitives/runtime-interface/src/pass_by.rs
- primitives/runtime-interface/test-wasm/src/lib.rs
- primitives/runtime-interface/test/src/lib.rs
We used `slice::from_raw_parts` in runtime-interface which did not free
the memory afterwards. This pr changes it to `Vec::from_raw_parts` to
make sure `drop` is called properly and the values are freed.
> Fix memory leak in runtime interface

- bin/node/cli/src/command.rs
- client/cli/src/lib.rs
Fixes:
```
➜  substrate-3 git:(master) ./target/debug/substrate factory --dev
Error: Service(Other("No keystore config provided!"))
```
> Fix broken factory by adding keystore back.

- primitives/allocator/src/freeing_bump.rs
This pr changes how we initialize the `heads` of the allocator. Instead of using `0`, we initialize them to `u32::max_value()`. This fixes a bug that the first allocated pointer could not be reused after being freed. The first pointer is `0` (index into the heap) and this break the reusable-check `if heap[list_index] != 0`.
Besides the bug fix, the pr changes the handling of the `PREFIX` in the allocate/deallocate functions to make them more readable.
> Allocator improvements/clean ups

- .gitlab-ci.yml
https://github.com/paritytech/devops/issues/419
building and publishing rustdocs is requested to happen for pre-tags as the distance to official tagged releases is too long.
> ci: enable build for pre-tags

- client/finality-grandpa/src/tests.rs
by default ThreadPool spawns 1 per core, that's too much
> Easier with threads in tests

- client/consensus/pow/src/lib.rs
This restores the API of PoW engine after https://github.com/paritytech/substrate/pull/4652. No-parent verification now again becomes optional (called `preliminary_verify`). This is needed because for some algorithms only linear verification is possible (for PoW algorithms that just relies on parent block information). Also fixed some unused generic parameters.
> pow: re-add support for algorithms where only linear verification is possible

- bin/node-template/node/src/command.rs
- bin/node/cli/src/command.rs
- client/cli/src/lib.rs
- client/cli/src/params.rs
Follow up of: https://github.com/paritytech/substrate/pull/4845
> Move tracing cli args to `ImportParams`

- Cargo.lock
- client/service/Cargo.toml
This will remove on extra dependency in substrate:
```
[0] [11:12:31] ~/r/substrate cecton-cargo-update > cargo update -p parity-multihash
error: There are multiple `parity-multihash` packages in your project, and the specification `parity-multihash` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
parity-multihash:0.1.3
parity-multihash:0.2.1
```
> Update parity-multiaddr dependency

- bin/node/cli/src/command.rs
- bin/node/cli/tests/common.rs
- bin/node/cli/tests/purge_chain_works.rs
- bin/node/cli/tests/running_the_node_and_interrupt.rs
- client/cli/src/lib.rs
- client/cli/src/params.rs
We need to set `config_dir` and `database_path` for almost every
command.
This fixes `purge-chain` and also adds a test to make sure we don't
break it again.
Closes: https://github.com/paritytech/substrate/issues/4849
> Fix CLI setup again

- primitives/runtime/src/lib.rs
This allows automatic conversion from the FRAME `DispatchError` type to a static string.
> Implement From<DispatchError> for '&static str

- bin/node/runtime/src/lib.rs
- frame/balances/src/lib.rs
- frame/collective/src/lib.rs
- frame/contracts/src/account_db.rs
- frame/contracts/src/tests.rs
- frame/democracy/src/lib.rs
- frame/elections-phragmen/src/lib.rs
- frame/elections/src/lib.rs
- frame/generic-asset/src/lib.rs
- frame/identity/src/lib.rs
- frame/im-online/src/lib.rs
- frame/offences/src/lib.rs
- frame/recovery/src/lib.rs
- frame/recovery/src/tests.rs
- frame/scored-pool/src/lib.rs
- frame/society/src/lib.rs
- frame/staking/src/lib.rs
- frame/staking/src/tests.rs
- frame/support/src/storage/generator/double_map.rs
- frame/support/src/storage/generator/linked_map.rs
- frame/support/src/storage/generator/map.rs
- frame/support/src/storage/mod.rs
- frame/support/test/tests/instance.rs
- frame/system/src/lib.rs
- frame/treasury/src/lib.rs
- frame/vesting/src/lib.rs
As mentioned in #4839 it would be nice to align the `StorageMap` interface with the ones provided by Rusts `HashMap` and `BTreeMap`.
This PR renames `StorageMap::exists(key)` to `StorageMap::contains_key(key)` (and adjusts usage in pallets).
As I don't have a good overview of substrate, yet, please let me know which documentation needs to change.
See paritytech/polkadot#827 and substrate-developer-hub/substrate-developer-hub.github.io#445 for the companion PRs.
> Rename StorageMap::exists to ::contains_key (Resolves #4839)

- client/db/src/lib.rs
- client/db/src/light.rs
Should properly return some usage info even after a short time has passed since service start
> Alter usage collection a bit

- bin/node/runtime/src/lib.rs
- frame/support/src/debug.rs
Before this fix runtime_print! can be used only once in a scope because of the name pollution.
> Wrap runtime_print! macro in its own scope

- primitives/api/proc-macro/Cargo.toml
A trivial change. Tested by `cargo test`.
> Remove the unnecessary std dependency from 'blake2-rfc'

- primitives/finality-grandpa/Cargo.toml
- primitives/finality-grandpa/src/lib.rs
Exporting GRANDPA `AuthorityPair` can make it easier to build a light client in Intel SGX (no_std) environment.
This PR is a re-open of #4869. In the previous PR I forgot to add the AuthorityPair change.
> Export GRANDPA AuthorityPair when full_crypto is enabled

- Cargo.lock
- bin/node/executor/Cargo.toml
- primitives/state-machine/Cargo.toml
This will remove the duplicate dependencies on trie-db and trie-root
```
[0] [09:52:55] ~/r/substrate cecton-update-trie-db > rg trie-root
Cargo.lock
3419: "trie-root 0.15.2",
7199: "trie-root 0.15.2",
7266: "trie-root 0.16.0",
8151: "trie-root 0.16.0",
8183:name = "trie-root"
8192:name = "trie-root"
```
> Update trie-db to the latest

- bin/node/executor/src/lib.rs
- client/executor/src/integration_tests/mod.rs
- primitives/io/src/lib.rs
Instead of exposing the benchmarking functions to each Substrate runtime by default, it must be explicitly enabled in the  `native_executor_instance!` macro call.
If the functions are not exported, but requested by the runtime, the instantiation will fail.
> Don't expose `Benchmarking` host functions by default

- client/src/client.rs
I think we should trace the timing for import block.
I'm not sure this is the best place though (another option may be to log in `import_batch_of_blocks`?).
> Add timing trace for import block.

- primitives/allocator/src/freeing_bump.rs
A little bit belated refactoring of the allocator crate.
Overview of changes:
- A concept of `Order` and a separate type is introduced for it. The term Order was inspired by [this](https://www.kernel.org/doc/gorman/html/understand/understand009.html).
- Instead of juglling around with u32 for specifying the pointer to the next item, a separate enum `Link = Ptr(u32) | Null` is introduced. The end of linked list is still ultimately encoded as a `u32::max_value`.
- Prefix is now referred as a Header. A separate enum is introduced as a `Header = Free(Link) | Occupied(Order)`. Apart from that, the in-memory encoding is changed so that it is now it is possible to tell if the header encodes a free or occupied variant, which should aid in detecting memory corruptions.
- Introduced the `Memory` …
> Refactor and document allocator

- primitives/runtime-interface/test-wasm/src/lib.rs
> Fix runtime interface tests on Windows

- Cargo.lock
- frame/evm/Cargo.toml
- primitives/arithmetic/Cargo.toml
- primitives/arithmetic/fuzzer/Cargo.toml
- primitives/core/Cargo.toml
- primitives/runtime-interface/Cargo.toml
> Update primitive-types crate

- client/db/src/utils.rs
- client/offchain/src/lib.rs
- client/service/src/builder.rs
- primitives/blockchain/src/backend.rs
Current execution of offchain workers is potentially racey with block (fork) imports. We run the workers at specific block NUMBER, while we should be running at specific block HASH.
This PR changes the execution to be bound to a specific hash and adds a bunch of more detailed logging to `UnknownBlock` errors that are observed in the wild.
```
2020-02-10 03:14:37.295 import-queue-worker-0 TRACE babe  Ignoring digest not meant for us
2020-02-10 03:14:37.297 import-queue-worker-0 TRACE db  Canonicalize block #979162 (0x1fe9739db9a2f21edc075394a166e631d20296dad1d8757e01ab98f79f1506da)
2020-02-10 03:14:37.297 import-queue-worker-0 DEBUG db  DB Commit 0x41222a919b0d1fdc868f6566d8093f5e84f671b49d9bfe8dfbf9d88647087518 (983258), best = false
2020-02-10 03:14:37.297 import-queue-worker-0 TRACE …
```
> Run offchain workers at hash, not number.

- bin/node/runtime/src/lib.rs
- frame/babe/src/lib.rs
- frame/support/src/traits.rs
- primitives/runtime/src/traits.rs
This will allow BABE to be slotted in places that were previously using `RandomnessCollectiveFlip`.
> impl Randomness trait for Babe and remove unused RandomBeacon trait

- client/network/src/behaviour.rs
- client/network/src/discovery.rs
- client/network/src/service.rs
Substrate currently opens **a lot** of TCP connections.
I'm going to properly investigate why tomorrow, but here's a small PR that makes sense to me: we should stop the discovery process if we have a lot of existing connections.
> Pause Kademlia if too many connections

- bin/node/runtime/src/lib.rs
- frame/evm/src/lib.rs
Some operations in EVM needs precise values of nonce. This PR adds an optional parameter `nonce`. If set, it requires that the source account nonce equals to that value. If not, it consumes all gases but does not do any other state changes.
> pallet-evm: optional nonce parameter

- client/peerset/src/lib.rs
This is a random attempt at improving the number of active TCP connections (#4679) by increasing the reputation penalty for nodes being offline.
Right now it is only `-10`, which actually immediately vanishes because reputations regress towards 0 at each tick.
This reduces the chances that we try to connect to the the exact same node again in the near future.
I noticed locally that doing this change seems to improve the ratio of active per inactive connection.
Even if this doesn't improve anything, it's still a change in the right direction considering that right now that penalty might as well be 0.
> Increase the reputation penality for being offline

- Cargo.lock
- bin/utils/subkey/Cargo.toml
- bin/utils/subkey/src/main.rs
This PR adds a new subcommand to subkey, 'generate-node-key' which can be used to generate a new libp2p secret key, save it to file in the format required by a substrate node and also print its peer ID.
> Add a sub command to generate a node key file

- Cargo.lock
- client/cli/src/lib.rs
- client/cli/src/params.rs
- client/network/Cargo.toml
- client/network/src/config.rs
- client/network/src/service.rs
- client/network/src/transport.rs
- client/service/test/src/lib.rs
- utils/browser/src/lib.rs
We never enabled proper flow-control for yamux streams which may cause stream buffers to exceed their configured limit when the stream producer outpaces the stream consumer. By switching the window update mode to on-read, producers will only receive more sending credit when all data has been consumed from the stream buffer. Using this option creates backpressure on producers. However depending on the protocol there is a risk of deadlock if both endpoints concurrently attempt to send more data than they have credit for and neither side reads before finishing their writes. To facilitate proper testing, this PR adds a command-line flag `use-yamux-flow-control`.
In addition, this PR enables another yamux option -- `lazy_open` -- which prevents the sending of an initial control frame as soon …
> Add command-line flag to enable yamux flow control.

- primitives/runtime/src/generic/digest.rs
This documents an assumption about how those will be used.
> add some more docs on PreRuntime digests

- bin/node/runtime/src/lib.rs
- frame/transaction-payment/rpc/runtime-api/src/lib.rs
- frame/transaction-payment/rpc/src/lib.rs
- frame/transaction-payment/src/lib.rs
- primitives/runtime/src/traits.rs
Fixes #4897 
Not sure if I need to an implementation with `deserialize_with`
This is kind of a breaking change but polkadot.js should automatically handle string to number conversion.
> serialize partial_fee into string

- .gitlab-ci.yml
- Cargo.lock
- bin/node/runtime/src/lib.rs
- bin/node/testing/Cargo.toml
- bin/node/testing/benches/import.rs
- bin/node/testing/src/client.rs
- bin/node/testing/src/genesis.rs
- client/api/src/client.rs
- client/db/src/lib.rs
- client/db/src/light.rs
- primitives/keyring/src/sr25519.rs
`$ cargo bench -p node-testing import`
This isolates block execution and benches under worst programmable (not imaginable) conditions  - no cache due to random transfer destinations.
What it does is first generates block full of randomized transactions (so that cache never should be hit when importing it), and then measures many imports of such a block on new fresh database every time.
Also there is a small profiling "benchmark" (not actually benchmark) to help profiling in perf/instruments (it makes pause right before and right after actual _interesting_ work is done, so the right time interval can be selected in instruments). This is just there until better tooling for sending signals to perf/instruments somewhere available.
> Full block import benchmark

- Cargo.lock
- bin/node/testing/Cargo.toml
@shawntabrizi 
FYI it is impossible to reference `sc-cli` now without similar fix, you will get error
```
error[E0425]: cannot find function `benchmark_runtime` in module `sc_service::chain_ops`
--> client/cli/src/params.rs:1265:26
|
1265 |         sc_service::chain_ops::benchmark_runtime::<BB, BC::NativeDispatch, _, _>(spec, execution_strategy, wasm_method, pallet, extrinsic, steps, repeat)?;
```
> Fix benchmarks on master

- bin/node/runtime/src/lib.rs
- frame/contracts/src/tests.rs
- frame/contracts/src/wasm/runtime.rs
**Description**
When a contract encounters a runtime error a wasm trap is
triggered and the execution is halted. Currently, no matter
what was the cause for the trap it is always reported as:
DispatchError::Other("contract trapped during execution").
However, the trap that is triggered if a contract exhausts
its gas budget is particulary interesting. Therefore we add
a seperate error message for this cause:
DispatchError::Other("ran out of gas during contract execution").
A test is added hat executes a contract that never terminates.
Therefore it always exhausts is gas budget.
fixes #2584
**Open Issues**
* ~~I am not sure whether to bump `impl_version`or `spec_version`.~~
_spec_version should be bumped_
* ~~The field of the `Other` error variant (the error string) seems not to be passed …
> Allow to distinguish out of gas from other traps

- Cargo.lock
- frame/im-online/src/lib.rs
- primitives/application-crypto/src/lib.rs
- primitives/authority-discovery/src/lib.rs
- primitives/consensus/aura/src/lib.rs
- primitives/finality-grandpa/Cargo.toml
- primitives/finality-grandpa/src/lib.rs
This macro will "generate" the given code only when the crypto pair is
available. So, when either the `std` or the `full_crypto` feature is
enabled.
CC @h4x3rotab
> Adds `with_pair!` macro to application-crypto

- bin/node/cli/src/service.rs
- bin/node/testing/benches/import.rs
- bin/node/transaction-factory/src/lib.rs
- client/consensus/aura/src/lib.rs
- client/consensus/babe/src/lib.rs
- client/consensus/babe/src/tests.rs
- client/consensus/manual-seal/src/lib.rs
- client/consensus/manual-seal/src/seal_new_block.rs
- client/consensus/pow/src/lib.rs
- client/consensus/slots/src/lib.rs
- client/finality-grandpa/src/import.rs
- client/finality-grandpa/src/light_import.rs
- client/finality-grandpa/src/tests.rs
- client/network/test/src/lib.rs
- primitives/consensus/common/src/block_import.rs
- test-utils/client/src/client_ext.rs
This marks `BlockImportParams` as `non_exhaustive`. From time to time we add new field into the struct. By making sure users use initialization function we avoid too much breakage.
> Refactor BlockImportParams to be non_exhaustive

- client/cli/src/runtime.rs
- client/consensus/babe/src/tests.rs
- client/network/test/src/lib.rs
- primitives/consensus/common/src/import_queue/basic_queue.rs
- primitives/consensus/common/src/import_queue/buffered_link.rs
Due to the way rs-futures `ThreadPool` is implemented, Importing threads may outlive the queue instance and even the main thread. This leads to a race on closing rocksdb database vs cleaning the C++ runtime in the main thread, causing segfaults and preventing the database from being closed properly.
This PR adds explicit synchronization between importing threads and the queue shutdown.
Fixes #4913
> Fix import queue thread pool shutdown

- Cargo.lock
- bin/utils/subkey/Cargo.toml
- client/authority-discovery/Cargo.toml
- client/network-gossip/Cargo.toml
- client/network/Cargo.toml
- client/network/src/behaviour.rs
- client/network/src/debug_info.rs
- client/network/src/discovery.rs
- client/network/src/protocol.rs
- client/network/src/protocol/block_requests.rs
- client/network/src/protocol/legacy_proto/behaviour.rs
- client/network/src/protocol/legacy_proto/handler.rs
- client/network/src/protocol/legacy_proto/tests.rs
- client/network/src/protocol/light_client_handler.rs
- client/network/src/protocol/light_dispatch.rs
- client/network/src/service.rs
- client/network/test/Cargo.toml
- client/peerset/Cargo.toml
- client/peerset/src/peersstate.rs
- client/peerset/tests/fuzz.rs
- client/telemetry/Cargo.toml
- primitives/consensus/common/Cargo.toml
- utils/browser/Cargo.toml
Unlocks a few cool things, notably #4880 and #4887. cc'ing @expenses
Should also reduce the memory usage of connections, cc #4679 
Changes should be straight-forward.
> Update libp2p to 0.16

- bin/node/testing/benches/import.rs
- speeds up benchmarking dramatically (since keyring generation no longer done on every iteration)
- allows to reuse seed databases (just `clone`, and you get a copy with brand new directory)
> Database & keyring generation for benchmarks optimised

- client/network/src/protocol/legacy_proto/behaviour.rs
- client/peerset/src/lib.rs
Fixes two mistakes related to time:
- In the peerset, we require that `latest_time_update` is always superior or equal to `created`.
This can potentially not be the case due to the fact that we call `Instant::now()` twice.
- In `legacy_proto/behaviour.rs`, we do `if a > Instant::now() { let b = a - Instant::now(), ... }` but it is possible that `a` was just *slightly* superior to `Instant::now()`, which would cause the subtraction to panic.
Maybe fixes #4949, although I can't be sure.
> Fix potential panics related to time

- Cargo.lock
- client/network/Cargo.toml
- client/offchain/Cargo.toml
- client/offchain/src/api/http.rs
- client/service/Cargo.toml
- utils/grafana-data-source/Cargo.toml
- utils/grafana-data-source/src/lib.rs
- utils/grafana-data-source/src/server.rs
Fixes the regressed offchain HTTP API by upgrading hyper to use tokio 0.2.
While an integration test for offchain HTTP API [exists](https://github.com/paritytech/substrate/blob/b02a97129286a8453ef78f58963b72c7ae47aef6/client/executor/src/integration_tests/mod.rs#L469), it [uses mocks in `TestOffchainExt`](https://github.com/paritytech/substrate/blob/6e0a4877afbe2309e106b84333bb70200531b604/primitives/core/src/offchain/testing.rs#L199-L304), so I decided against duplicating an another harness with actual HTTP.
I imagine a better approach would be to set up most of the runtime and test the HTTP from offchain workers directly but didn't want to block the fix here, let me know if I should work on setting that up as well.
Tested manually on …
> offchain: Upgrade hyper to 0.13, which uses tokio 0.2

- Cargo.lock
- bin/node/testing/Cargo.toml
- bin/node/testing/benches/import.rs
- bin/node/testing/src/bench.rs
- bin/node/testing/src/lib.rs
This puts benchmarking db tools in `node-testing/bench` module for reuse
> Reusable bench-db & bench-keyring

- Cargo.lock
- client/network/Cargo.toml
- client/network/src/transport.rs
libp2p-0.16 allows configuring yamux through libp2p-yamux, so the direct dependency is no longer needed.
While at it we also update to the latest versions of yamux and nohash-hasher, though the code changes do not depend on it.
> Remove direct yamux dependency.

- client/network/src/protocol.rs
- client/network/src/protocol/sync.rs
- client/network/src/protocol/sync/extra_requests.rs
If we ask for a justification for a given block to a peer that doesn't know that block (different from not having a justification), the peer will reply with an empty response. Currently, we would ignore the empty response and not notify the `ExtraRequests` scheduler, this caused the request to always be considered in active state preventing it from ever being rescheduled to another peer (unless the peer disconnected from us). This should fix the issue with some nodes getting stuck on finalized blocks that are around authority set changes and never making any progress until restart (since the request would be properly rescheduled on startup).
> sync: process empty response for justification requests

- client/transaction-pool/src/testing/pool.rs
> Fix flaky finalisation test

- bin/node/testing/benches/import.rs
it was already merged #4956, just missed the right branch to merge into :)
> Wasm benchmark import per block size

- client/peerset/src/lib.rs
Nothing important, but makes it so that one doesn't need to import `libp2p` in order to use `sc-peerset`.
> Re-export PeerId from the peerset API

- client/network/src/discovery.rs
The current approach makes it difficult to figure out what the underlying error was, that made the operation fail.
> Log kademlia errors when get/put record fails.

- client/service/src/chain_ops.rs
This is probably a very old code artefact that was still laying around.
Removes building a network message within the chain_ops for seemingly no reason.
> Remove using a network message in the chain_ops (?!?!)

- client/consensus/babe/src/authorship.rs
`commit_bytes` is renamed to `append_message` in `merlin`.
> babe: fix deprecated function in transcript

- client/transaction-pool/src/testing/pool.rs
I discovered the tx `from_dave` sometimes never re-enters the pool, erroring with `PriorityTooLow`. Simply increasing the nonce got rid of the flakiness. :ok:
> fixes sc_transaction_pool::testing::fork_aware_finalization

- bin/node/runtime/src/lib.rs
- frame/support/src/traits.rs
- frame/vesting/src/lib.rs
This is a small improvement to the `vesting_balance` API, which now returns an `Option<Balance>` rather than just a balance.
The old api:
```rust
/// Get the amount that is currently being vested and cannot be transferred out of this account.
fn vesting_balance(who: &T::AccountId) -> BalanceOf<T> {
if let Some(v) = Self::vesting(who) {
let now = <frame_system::Module<T>>::block_number();
let locked_now = v.locked_at::<T::BlockNumberToBalance>(now);
T::Currency::free_balance(who).min(locked_now)
} else {
Zero::zero()
}
}
```
If we observe the previous behavior, when a user did not have a vesting schedule, we would return `vesting_balance` of zero. We could _also_ return zero if the balance of the account is zero **even though** they may actually have some vesting schedule!
Then let us …
> `vesting_balance` returns `Option`

- Cargo.lock
- client/finality-grandpa/src/communication/tests.rs
- client/network-gossip/Cargo.toml
- client/network-gossip/src/bridge.rs
- client/network-gossip/src/lib.rs
Let's also clean up the public-facing API of `sc-network-gossip` by turning the futures 0.1 into a futures 0.3.
I don't know if I should mark as "client-noteworthy" considering that this concerns a trait that exists purely in order to be able to mock the network for testing purposes. Polkadot in particular doesn't implement this trait.
> Clean up the public API of sc-network-gossip

- Cargo.lock
- bin/node/executor/tests/basic.rs
- bin/node/executor/tests/fees.rs
- bin/node/runtime/src/lib.rs
- frame/executive/src/lib.rs
- frame/system/src/lib.rs
Currently we entirely miss the fact that [these too can be heavy and their weight should be noted](https://github.com/paritytech/substrate/pull/4517/files#diff-32ce5961608780655bf3e00b2cc07d59R1179).
> Unsigned transactions should also note weight

- bin/node/cli/src/service.rs
- bin/node/runtime/src/lib.rs
- client/block-builder/src/lib.rs
- client/consensus/babe/src/lib.rs
- frame/babe/src/lib.rs
- frame/babe/src/mock.rs
- frame/babe/src/tests.rs
- frame/grandpa/src/lib.rs
- primitives/block-builder/src/lib.rs
- primitives/blockchain/src/error.rs
Remove deprecated api and dead code before 2.0 release.
Closes #4935.
> Remove deprecated API

- .gitlab-ci.yml
Simple job template added to .gitlab-ci.yml. At the very least, copying and using this template will create a job that won't error and includes required fields.
> CI: Add example CI job template to .gitlab-ci.yml

- bin/node/runtime/src/lib.rs
- client/consensus/babe/src/authorship.rs
- frame/executive/src/lib.rs
- frame/im-online/src/lib.rs
- frame/im-online/src/tests.rs
- frame/support/src/unsigned.rs
- primitives/runtime/src/generic/checked_extrinsic.rs
- primitives/runtime/src/testing.rs
- primitives/runtime/src/traits.rs
Related #4419 and #3419 
Implementing unsigned validation via `SignedExtension` for a single pallet is a bit cumbersome currently. We're lacking some extra glue code to make it as easy as for `ValidateUnsigned`.
Because of this I'd like to propose to un-deprecate `ValidateUnsigned` for 2.0 release and possibly deprecating it only after (but as I said in #4419 I think it may end up useful anyway; I'm currently evaluating that).
Submitting this as a minimal PR so that it can later be reverted easily if needed.
> Un-deprecate ValidateUnsigned

- client/consensus/babe/src/authorship.rs
It says "calls append_message with the 8-byte little-endian encoding of x" so it's of the same encoding.
> babe: directly use append_u64 in transcript instead of to_le_bytes

- bin/utils/subkey/Cargo.toml
- client/authority-discovery/Cargo.toml
- client/network-gossip/Cargo.toml
- client/network/Cargo.toml
- client/network/test/Cargo.toml
- client/peerset/Cargo.toml
- client/telemetry/Cargo.toml
- primitives/consensus/common/Cargo.toml
- utils/browser/Cargo.toml
We've made a few small fixes in 0.16.1 that I want to be sure Polkadot is using.
> Make sure we use libp2p 0.16.1

- bin/node-template/node/src/service.rs
- bin/node/cli/src/service.rs
- client/finality-grandpa/src/lib.rs
- client/finality-grandpa/src/observer.rs
- client/finality-grandpa/src/tests.rs
Currently both the `node` and `node-template` run the GRANDPA observer protocol rather the full protocol if the node is not an authority. The observer currently has some issues with guaranteeing block and vote data availability, and having most nodes on a network run it could lead to finality stalls. We currently don't use the observer in Polkadot and as such it has not had much extensive testing either. This PR makes sure that both `node` and `node-template` always run the full GRANDPA protocol, the reason to do this is to prevent other projects from eventually using the observer on their network and running into issues (since they have no way to know about this and will mostly copy the service instantiation code from `node` / `node-template`.)
> node, node-template: disable GRANDPA observer

- client/service/src/lib.rs
RPC servers currently don't wait for worker threads to cleanup. This may result in RPC handlers, which contain a reference to the DB, to be still alive when the main thread terminates, leading to segfaults.
@tomusdrw perhaps `http::Server` should wait on `drop` internally?
> Wait for RPC server to cleanup on shutdown

- bin/node/cli/src/service.rs
- client/consensus/babe/rpc/src/lib.rs
- client/consensus/babe/src/lib.rs
- client/consensus/babe/src/tests.rs
> Removes use of sc_client::Client from sc_consensus_babe

- .gitlab-ci.yml
- scripts/gitlab/lib.sh
- scripts/gitlab/publish_draft_release.sh
Idea is much the same as we currently do on polkadot - When a new tag is pushed (that fits our pattern for tags, e.g. `v1.2.3`), find a list of labelled changes and generate a changelog based on that. Create a draft release on Github and post about it on Matrix.
> Add gitlab job for publishing draft releases

- frame/benchmarking/src/lib.rs
- frame/benchmarking/src/utils.rs
- utils/frame/benchmarking-cli/src/lib.rs
This is a small PR which additionally adds storage root recalculation time to our pallet benchmarking setup.
Storage root recalculation is measured using:
```
sp_io::storage::root
```
Results now look like:
```
Pallet: "pallet-identity", Extrinsic: "add_registrar", Steps: 10, Repeat: 100
r,extrinsic_time,storage_root_time
1,305000,65000
1,97000,39000
1,281000,39000
1,102000,41000
```
> Add storage root recalculation time to benchmarks

- .gitlab-ci.yml
- Cargo.lock
- bin/node/testing/Cargo.toml
- bin/node/testing/src/bench.rs
- client/authority-discovery/Cargo.toml
- client/network-gossip/Cargo.toml
- client/network/Cargo.toml
- primitives/runtime-interface/test-wasm/Cargo.toml
- primitives/test-primitives/Cargo.toml
- test-utils/client/Cargo.toml
- test-utils/runtime/Cargo.toml
- test-utils/runtime/client/Cargo.toml
- test-utils/runtime/transaction-pool/Cargo.toml
> adding unleash to ci

- bin/node/cli/tests/check_block_works.rs
- bin/node/cli/tests/common.rs
- bin/node/cli/tests/import_export_and_revert_work.rs
- bin/node/cli/tests/inspect_works.rs
- bin/node/cli/tests/purge_chain_works.rs
- client/cli/src/commands/export_blocks_cmd.rs
- client/cli/src/commands/revert_cmd.rs
- client/cli/src/params/import_params.rs
- client/cli/src/params/mod.rs
- client/cli/src/params/pruning_params.rs
There seems to be quite a lot of timeouts in the CI lately for stopping the nodes:
* https://gitlab.parity.io/parity/substrate/-/jobs/396630
* https://gitlab.parity.io/parity/substrate/-/jobs/396707
* https://gitlab.parity.io/parity/substrate/-/jobs/396726
Some tests are not using `--dev` and because of that they take time to connect.
This change will display a message when the process takes too long to exit (> 5 seconds) and use `--dev` everywhere.
> Fix: CI failing for some CLI tests

- bin/node-template/node/src/service.rs
- client/consensus/aura/src/lib.rs
This was initially added in order for the client to push equivocation transactions directly to the transaction pool. This will instead be done by calling into the runtime in an off-chain context and therefore the client code won't need direct access to the transaction pool.
Making this change to stabilize the API.
> aura: remove unused tx pool

- utils/wasm-builder/README.md
- utils/wasm-builder/src/lib.rs
- utils/wasm-builder/src/wasm_project.rs
Instead of just testing `cargo` and `rustup run nightly`, we now test
the `CARGO` env variable and also scan non default nightlies. The user
is also now able to select the toolchain with `WASM_BUILD_TOOLCHAIN`.
Fixes: https://github.com/paritytech/substrate/issues/3492
CC @xlc
> Extend rust nightly detection in `wasm-builder`

- bin/node/runtime/src/lib.rs
- frame/benchmarking/src/lib.rs
- frame/benchmarking/src/utils.rs
- utils/frame/benchmarking-cli/src/lib.rs
Changes:
- Make `--steps` option to take as input a serie of numbers separated by comma (e.g. `10,50,30`) denoting the number of steps for each component of the corresponding extrinsic. Previously it was using the same steps number for all the components. Example:
`substrate benchmark --chain dev --execution=native  --extrinsic set_identity --pallet pallet-identity --steps 50,100 --repeat 1`
- Set the max value for the other components as default in order to hit worst case.
- Other nits.
> Add steps setting to benchmarking CLI

- client/chain-spec/src/chain_spec.rs
The structs themselves are already private, so I'm not sure why these fields were public.
> Make these chainspecs fields private

- .maintain/Dockerfile
Version bump of the base image to allow building the image.
I have tested the image build.
> Fix dockerfile

- primitives/externalities/src/lib.rs
- primitives/state-machine/src/basic.rs
This adds documentation to `wipe` and `commit` of `Externalities`.
Besides that it removes the default implementation that would just panic
and requires that all implementers of the trait implement the functions.
> Adds documentation for `wipe` and `commit`

- client/transaction-pool/src/lib.rs
- client/transaction-pool/src/revalidation.rs
- client/transaction-pool/src/testing/pool.rs
The problem was that revalidation queue wasn't accepting same transaction twice for revalidation, and transaction that were valid for some time, then became invalid, were stuck and not revalidated.
> Fix revalidation not revalidating multiple times

- bin/node-template/node/src/service.rs
- bin/node/cli/src/service.rs
- client/api/src/backend.rs
- client/finality-grandpa/Cargo.toml
- client/finality-grandpa/src/environment.rs
- client/finality-grandpa/src/import.rs
- client/finality-grandpa/src/justification.rs
- client/finality-grandpa/src/lib.rs
- client/finality-grandpa/src/light_import.rs
- client/finality-grandpa/src/observer.rs
- client/finality-grandpa/src/tests.rs
- client/src/client.rs
- client/src/lib.rs
See #4452
Introduces a new trait `ClientBackend` to `sc_client_api`, for methods that interact with the backend.
eg `fn lock_import_and_run`
> removes use of sc_client::Client from sc_finality_grandpa

- frame/transaction-payment/src/lib.rs
A drive by fix of some stuff in the transaction-payment pallet: whitespaces, exceeding lines and making the tests more readable. There is no change of behavior and it is expected that check-runtime fails.
> pallet-transaction-payment clean up

- Cargo.lock
- client/cli/Cargo.toml
- client/service/Cargo.toml
- client/service/src/builder.rs
- client/service/src/config.rs
- client/service/src/error.rs
- utils/prometheus/Cargo.toml
- utils/prometheus/src/lib.rs
This patch renames the crate for the following two reasons:
1. The prometheus-exporter crate introduces native in-process Prometheus
style instrumentation to the Substrate project. Within the Prometheus
ecosystem the term "exporter" is used for external processes exposing
metrics for e.g. the Linux Kernel. In-process exposition would be
described via the term "endpoint".
2. "prometheus-exporter" is generic and ignores the fact that it is only
usable within the context of Substrate. In addition the name
"prometheus-exporter" is already taken on crates.io.
Fixes https://github.com/paritytech/substrate/issues/5074
> *: Rename prometheus-exporter crate to substrate-prometheus-endpoint

- Cargo.lock
- bin/node/cli/Cargo.toml
- utils/browser/Cargo.toml
It's a good idea to give the crate a more descriptive name before publishing on crates.io.
> rename `browser-utils` to `substrate-browser-utils`

- bin/node/runtime/src/lib.rs
- frame/im-online/src/lib.rs
- frame/im-online/src/mock.rs
- frame/offences/src/lib.rs
- frame/offences/src/tests.rs
- frame/staking/src/lib.rs
- primitives/staking/src/offence.rs
Add a `Result` return type for `report_offence` in `offences` module. At this moment it's only purpose is  to report the caller if they are submitting a duplicate offence report.
This is a companion for paritytech/polkadot#840
> Offence reporting returns a result

- Cargo.lock
- bin/utils/subkey/Cargo.toml
- client/authority-discovery/Cargo.toml
- client/network-gossip/Cargo.toml
- client/network/Cargo.toml
- client/network/test/Cargo.toml
- client/peerset/Cargo.toml
- client/telemetry/Cargo.toml
- primitives/consensus/common/Cargo.toml
- utils/browser/Cargo.toml
Make sure we don't accidentally regress to buggy versions.
> Update to libp2p 0.16.2

- Cargo.lock
- client/api/src/client.rs
- client/db/src/lib.rs
- client/db/src/light.rs
- client/informant/src/lib.rs
- client/service/src/builder.rs
- client/state-db/Cargo.toml
- client/state-db/src/lib.rs
- client/state-db/src/noncanonical.rs
- client/state-db/src/pruning.rs
This exposes memory statistics from the state-db.
Contributes to: https://github.com/paritytech/substrate/issues/5106
> Expose `state-db` memory info

- .maintain/Dockerfile
This PR contains the following:
- same fix than in #5059 
- fix substrate default chain location (old issue finally fixed)
- add prometheus port to the list of hinted exposed ports
So this PR means we no longer *have to* provide the `-d /data` to substrate to make the volume mounting works.
> Fix substrate default storage location

- client/rpc-api/src/chain/mod.rs
- client/rpc/src/chain/mod.rs
- client/rpc/src/chain/tests.rs
Added subscribe_all_heads RPC call, there was no way to get all blocks received by the node through RPC. This will help apps that analyze blockchain. I.E. Equivocation detection can now be done by apps connected to RPC. 
Also fixed updated comments and added test.
fixes #4738
> Added subscribe_all_heads RPC function

- client/cli/src/params/import_params.rs
Through rigorous analysis *coughcough* ... random testing, we've noticed that the db-cache default is a lot higher than it needs to be. This PR drops it from 1gig to defaulting to 32mb. This has a few added benefits:
- a lower footprint without obvious decrease in bps imported
- leaks should be easier and quicker to detect (rather than only after the 1gig of DB cache is filled)
> Drop db-cache default from 1gig to 32mb

- primitives/core/src/crypto.rs
We would like to claim those ss58 prefixes:
- 8: Acala Karura canary network
- 9: Laminar Reynolds canary network
- 10: Acala mainnet
- 11: Laminar mainnet
We will be using 42 for Acala Mandala Testnet & Laminar Turbulence Testnet.
Also sorted the networks by prefix.
> add ss58 prefix for Acala & Laminar

- client/cli/src/params/import_params.rs
During another rigorous analysis, little values of cache lead to increased cpu usage during node normal operation (probably due to rocksdb needs to do uncompressing of data from system cache)
> Use 128mb for db cache default

- frame/executive/src/lib.rs
- primitives/runtime/src/generic/checked_extrinsic.rs
- primitives/runtime/src/testing.rs
- primitives/runtime/src/traits.rs
It looks like `Applyable::sender` along with its `Applyable::AccountId` are not used within primitives/FRAME. This PR just removes that.
The runtime behavior is not changed.
> Remove `sender` from `Applyable`.

- primitives/core/src/crypto.rs
In order to prevent the re-usage across networks, decreasing the value at risk if a private key is lost, and also to identify easily.  We want to registry the Subkey Address Type as 18 for [Darwinia](https://github.com/darwinia-network/darwinia) mainnet, and we will use 42 in our last testnet.  If there are any concerns please kindly tell us.  
Many thanks for your hard-working on Substrate.
> adding a ss58 format for Darwinia Network

- bin/node/cli/Cargo.toml
- bin/node/runtime/Cargo.toml
This exposes the `runtime-benchmarks` feature via the cli crate and
makes sure the benchmarking can be enabled. This requires that the user
goes to `bin/node/cli` and runs `cargo build --features
runtime-benchmarks` to build a node that has the feature enabled.
> Expose the `runtime-benchmarks` feature to the cli crate

- client/network/src/protocol.rs
- client/network/src/protocol/sync.rs
- client/network/src/protocol/sync/extra_requests.rs
- client/network/src/service.rs
> Add more prometheus metrics to `network::Protocol`.

- client/cli/src/commands/runcmd.rs
The only up-to-date deployment of PolkadotJS apps is currently on https://polkadot.js.org/apps/.
https://substrate-ui.parity.io is only useful as deliberately kept outdated version of Apps, to be used for projects still on Substrate 1.0
It cannot be used with the up-to-date chains running the Substrate 2.0 codebase, and probably won't be maintained much longer.
> Remove substrate-ui.parity.io from CORS whitelist

- bin/node-template/runtime/src/lib.rs
- bin/node/runtime/src/lib.rs
- client/basic-authorship/src/basic_authorship.rs
- client/block-builder/src/lib.rs
- client/rpc/src/state/tests.rs
- client/service/src/lib.rs
- frame/executive/src/lib.rs
- frame/im-online/src/tests.rs
- frame/transaction-payment/src/lib.rs
- primitives/block-builder/src/lib.rs
- primitives/runtime/src/generic/mod.rs
- primitives/runtime/src/generic/unchecked_extrinsic.rs
- primitives/runtime/src/testing.rs
- primitives/runtime/src/traits.rs
- test-utils/runtime/src/lib.rs
- test-utils/runtime/src/system.rs
After speaking with @tomusdrw, we came to the conclusion that we should remove this feature. It is nice and could bring some speedups, but the security problems are too large. 
- A transaction could sit in the tx-pool waiting to be included and the account index is reaped in the meantime, someone else starts using the account index and we include this transaction. The signature verification would clearly fail at this point.
> Revert "Build block without checking signatures (#4916)"

- client/network-gossip/src/state_machine.rs
When we receive a batch of gossip messages we will call into all registered gossip validators with potentially no messages (they are filtered beforehand by gossip engine id), in which case we don't want to log a useless statement that we have received 0 messages.
> client: don't log on 0 gossip messages

- bin/node/runtime/src/lib.rs
- frame/session/src/lib.rs
- frame/staking/src/lib.rs
the property `"Error: start_session_index must be set for active_era + 1"` is false, there can be no future era planned yet, there is a future era planned only one session before the end of the era is kusama.
Although this was a bug, the behavior wasn't broken because in case no era is planned, then index 0 is returned and the comparison:
```rust
if next_active_era_start_session_index == session_index + 1 {
```
would return false which is good because no era was planned thus, the session doesn't end an era.
> Fix staking bug

- bin/node-template/runtime/src/lib.rs
This PR increases the node template's maximum block weight from 1 million (`1_000_000`) to 1 billion (`1_000_000_000`) to match the main Substrate node. The former lower weight is the exact weight of a balance transfer which means that after a timestamp is in the block there isn't enough room left for even a single balance transfer.
A mystery that I haven't solved is why this just became a problem when none of those weight have changed in 9 months since https://github.com/paritytech/substrate/pull/3157
Cross reference: https://github.com/substrate-developer-hub/substrate-node-template/pull/25
Dumb question: Does this require a spec version bump? I think it does.
> Increase node template max block weight

- primitives/core/src/crypto.rs
This small PR adds ss58 prefix for Plasm Network project: https://www.plasmnet.io/
> Adding a ss58 format for Plasm Network

- client/executor/src/wasm_runtime.rs
Calling `std::time::Instant::now` panics in wasm.
> Fix a runtime panic in the browser node

- frame/balances/src/migration.rs
Forgot to encode the left key :-/
> Migration fix

- client/transaction-pool/src/revalidation.rs
- client/transaction-pool/src/testing/pool.rs
It might be the case when revalidation is queued across multiple blocks
> Fix possible corner case in revalidation

- client/network/src/config.rs
- client/network/src/protocol.rs
- client/network/src/protocol/light_dispatch.rs
- client/network/src/service.rs
- client/network/test/src/lib.rs
For backwards-compatibility reasons, right now the lifetime of a "notifications substream" is still tied to the lifetime of a handshake on the main substream.
At the moment, we report that we opened substreams when a handshake succeeds, and we report that we closed substreams when we disconnected.
However this left a bug: if a node connects then disconnects before the handshake, then we'd report that we closed substreams even though we have never reported that they were open.
While this bug doesn't really have bad consequences, it is the reason why the `polkadot_sub_libp2p_opened_notification_streams` metric is underflowing at the moment.
> Fix NotificationStreamClosed reported when it shouldn't

- bin/node/runtime/src/lib.rs
- frame/staking/src/lib.rs
- frame/staking/src/tests.rs
`cancel_deferred_slash` had a flaw where the vec of deferred slashes to remove could have duplicate values, and as a result, mess up the intended behavior.
This makes the extrinsic more restrictive, requiring the sender to submit a:
1. Non-empty
2. Sorted
3. Unique
4. In-Bound
List of deferred slashes to remove.
Tests have been updated so that all of these possible error conditions result in a noop.
> Update logic to cancel_deferred_slash

- primitives/core/src/crypto.rs
Our team is going to take 6 as address type of ss58 for Bifrost Network. https://bifrost.codes/
> Add 6 as address type of ss58 for Bifrost Network

- frame/staking/src/migration/deprecated.rs
- frame/staking/src/migration/tests.rs
to follow guidelines this changes space indentation to tab indentation in some missed files
> Change space to tab

- utils/wasm-builder-runner/src/lib.rs
Fixes: https://github.com/paritytech/substrate/issues/5190
> Make sure to always run `wasm-builder` for the `HOST` architecture

- Cargo.lock
- client/offchain/Cargo.toml
- client/offchain/src/api/http.rs
This PR fixes the test code loop caused by low fd limit on macOS by increasing the limit programmatically for the test code.
Reproduced on Linux using `ulimit -S -n 50` and confirmed the fix from this PR.
Just to be sure, it'd be great to also confirm the fix on macOS (I don't have access to a Mac).
Closes #5102 
(also did some small drive-by fixes, I can split them off this PR if needed)
> Make sc-offchain tests more resilient on macOS

- client/service/src/builder.rs
Add static Prometheus metric exposing the chain name, the version and
the commit.
```bash
curl localhost:9615/metrics | grep -E "build_info"
substrate_build_info{commit="607e197f0",name="Substrate Node",version="2.0.0-alpha.3"} 1
```
Fixes https://github.com/paritytech/substrate/issues/5181.
In addition this pull request contains a second commit: 
- client/service/src/builder.rs: Move node_role to static metrics
The Prometheus metrics `node_role` is static and thus there is no need
to keep a reference of it within `ServiceMetrics`. This follows the
example of the `build_info` metric.
> client/service/src/builder.rs: Add build_info metric

- .gitlab-ci.yml
Now `check_warnings` job starts right after `test-linux-stable` and also it's marked as a required status check in the settings.
> Necessary warnings test

- .maintain/gitlab/check_runtime.sh
we only need to bump the runtime version if there have been changes to the runtime since the last release (tracked by the `release` tag), not every time the runtime is changed.
> CI: Check runtime version against last release, not master

- bin/node/runtime/src/lib.rs
- frame/staking/src/lib.rs
its adds some documentation + use clipped exposure for validator payout.
It shouldn't change the behavior of the runtime because for validator payout clipped exposure and exposure hold same information. It should just optimise the read of validator exposure.
> Staking improve payout_validator

- bin/node/runtime/src/lib.rs
- frame/contracts/COMPLEXITY.md
- frame/contracts/src/tests.rs
- frame/contracts/src/wasm/runtime.rs
This PR splits the
```
ext_set_storage(key_ptr: u32, value_non_null: u32, value_ptr: u32, value_len: u32);
```
into two APIs:
```
ext_set_storage(key_ptr: u32, value_ptr: u32, value_len: u32);
ext_clear_storage(key_ptr: u32);
```
We perform this change to make it simpler for static analyzers to analyze the underlying code semantically.
The old API with its `value_non_null` parameter is theoretically impossible to analyze statically since the `value_non_null` parameter could be any runtime computed value. So it is potentially very hard for static analyzers to apply the correct gas costs in the case where we want to differentiate between setting and clearing contract storage entries.
**Why do we want to differentiate between those two operations?**
The operations have completely different …
> Split ext_clear_storage out from ext_set_storage

- utils/frame/benchmarking-cli/src/lib.rs
closes #5154. 
I went for removing the `update_config()` call, other options could be to add a `default_chain: Option<>` argument to it (maybe better), or to keep the call as it is and set the default before (imo worst).
> Add dev chain as default chain for benchmarks.

- .maintain/sentry-node/docker-compose.yml
This patch adds the Prometheus endpoint port of validator A to the
exposed ports to access it from the host network namespace.
> .maintain/sentry-node/docker-compose: Expose Prometheus endpoint to host

- bin/node/runtime/src/lib.rs
- frame/support/src/traits.rs
- frame/transaction-payment/src/lib.rs
Alternative for #4364.
Closes https://github.com/paritytech/substrate/issues/4363
This avoids making too many changes by allowing `OnUnbalanced` to handle iterators of `Imbalance`s. A default and backwards compatible default implementation is provided. It is used by the transaction payment system in order to deal with fees and tips separately.
It should give strictly the same amount of storage accesses and runtime/native crossings as before, adding only a small amount of extra arithmetic, much of which should be optimisable away.
> Split fees and tips between author and treasury independently

- frame/staking/src/lib.rs
Closes https://github.com/paritytech/substrate/issues/5223
The reason to emit events is to find out the actual change to the staking ledger as users could call `bond`, `bond_extra`, `unbond`, or `withdraw_unbonded` with a different `value` than will actually update the staking ledger.
> Emit events to bonding and unbonding ops in Staking pallet

- client/chain-spec/derive/src/lib.rs
- frame/balances/src/lib.rs
- frame/democracy/src/lib.rs
- frame/staking/reward-curve/src/lib.rs
- frame/support/procedural/src/lib.rs
- frame/support/procedural/tools/derive/src/lib.rs
- frame/vesting/src/lib.rs
- primitives/api/proc-macro/src/lib.rs
- primitives/debug-derive/src/lib.rs
- primitives/runtime-interface/proc-macro/src/lib.rs
- primitives/sr-api/proc-macro/src/lib.rs
as it looks like it is no longer needed https://blog.rust-lang.org/2020/03/12/Rust-1.42.html#use-proc_macro:tokenstream;-now-works
and some unused imports.
> Remove `extern crate proc_macro`

- bin/node/runtime/src/lib.rs
- frame/contracts/COMPLEXITY.md
- frame/contracts/src/exec.rs
- frame/contracts/src/wasm/mod.rs
- frame/contracts/src/wasm/runtime.rs
This PR adds the following contract syscall:
```
ext_transfer(account_ptr: u32, account_len: u32, value_ptr: u32, value_len: u32);
```
It behaves similarly to `ext_call`. The differences are:
- Saves three arguments `input_ptr, input_len, gas_limit`.
- Garanteed to never execute code at the destination account (in case it is a contract).
Using `ext_call` for balance transfers has one major flaw: You need to know which kind of contract you are calling because otherwise you do not know if you are actually triggering contract code execution for the input you are passing. Nothing stops a contract from acting on an empty input in an arbitrary way.
Sparing the contract the hassle of passing gas costs and saving some overhead is merely a bonus.
closes #5027
> Add ext_transfer call

- client/finality-grandpa/src/communication/gossip.rs
- client/finality-grandpa/src/communication/mod.rs
- client/finality-grandpa/src/communication/tests.rs
- client/finality-grandpa/src/lib.rs
- client/finality-grandpa/src/observer.rs
- client/finality-grandpa/src/tests.rs
Instrument finality grandpa `GossipValidator` exposing count of messages
validated by message type and message action.
```
\# HELP substrate_finality_grandpa_communication_gossip_validator_messages Number of messages validated by the finality grandpa gossip validator.
\# TYPE substrate_finality_grandpa_communication_gossip_validator_messages counter
substrate_finality_grandpa_communication_gossip_validator_messages{action="discard",message="neighbor"} 39
substrate_finality_grandpa_communication_gossip_validator_messages{action="keep",message="vote"} 28
```
> client/finality-grandpa: Add Prometheus metrics to GossipValidator

- .github/workflows/release-tagging.yml
The intent of the `release` tag is to always track the current/latest release (used in CI scripts like `check_runtime.sh`). This github action will run whenever a new release is prereleased or published, and force an update to the `release` tag.
Note: there's a small bug at the moment whereby for prereleases, the action will run twice, and one of the two jobs will fail. Currently WIP until I find out if I can fix this.
> Create release-tagging github action

- client/db/src/bench.rs
The assumptions with Runtime Benchmarks is that we seed the benchmarks with some initial genesis state, and as we run `steps` or `repeats` of the benchmark, we always reset to genesis.
However, there was a bug such that we were clearing the full state of the chain, and not resetting to the genesis state. This fixes that issue.
cc @arkpar
> Fix benchmarks to reset to genesis state

- frame/metadata/src/lib.rs
- frame/support/procedural/src/storage/metadata.rs
- frame/support/src/lib.rs
- frame/support/test/tests/decl_storage.rs
- frame/support/test/tests/instance.rs
PR into `gav-refactor-hashing` branch (sep. due to the tests being updated as well)
- removes Tombstone
- rename `is_linked`
> Rename Map is_linked -> unused, keeping backwards compat

- .maintain/gitlab/check_runtime.sh
fixes https://gitlab.parity.io/parity/substrate/-/jobs/418272
release tag is more than 100 commits away in the history.
> ci: check_runtime: fetch release tag

- .maintain/gitlab/check_runtime.sh
fix release tag not being properly fetched e.g. https://gitlab.parity.io/parity/substrate/-/jobs/418866#L21
> ci: check_runtime: fetch release tag ii

- client/network/src/protocol.rs
I have the following suggestions for the Prometheus metrics within `client/network/src/protocol.rs`:
1. Start Prometheus metric help with capital
2. Differentiate metric status as label 
Prometheus query language is powerful through its multi-dimensional data
model. Metric names are hirarchical whereas labels enable data to become
multi-dimensional.
Exposing the justification of finality-proof status as a label allows
for more powerful queries.
3. Remove 'Total' from non counter metric help
The word 'total' is reserved for accumulating counters. Counters have to
be monotonically increasing. `obsolete_requests` can decrease, thereby
it is defined as a `Gauge` and not a `Counter`.
For more details on metric naming see
https://prometheus.io/docs/practices/naming/
> client/network/src/protocol: Refactor Prometheus metric logic

- frame/contracts/COMPLEXITY.md
- frame/contracts/src/exec.rs
- frame/contracts/src/tests.rs
- frame/contracts/src/wasm/mod.rs
- frame/contracts/src/wasm/runtime.rs
This PR adds the following contract syscall  ( closes #4952 )
```
ext_terminate(beneficiary_ptr: u32, beneficiary_len: u32);
```
It removes a contract from storage (terminates it) after sending all remaining balance to a beneficiary. The beneficiary can be a contract or a plain account. The call never returns: Neither on success (execution halts and changes are committed) nor on failure (trap and rollback).
This PR also changes the semantics of all other contract initiated balance transfers to fail if they would bring the caller below the existential deposit. This makes `ext_terminate` the only way for a contract to self-destruct.
Due to upcoming changes with the FRAME balances pallet we won't be able to rely on the callback called upon decreasing a contract's balance below existential …
> Add ext_terminate call

- client/finality-grandpa/src/communication/mod.rs
Heaptrack shows this is second hottest source for temporary allocations.
`voters.len() <= TELEMETRY_VOTERS_LIMIT` should not be the case on kusama as I understand.
> Don't format addresses when telemetry is disabled

- frame/example-offchain-worker/src/lib.rs
if statement logic for `last_sent` block was inverted in the example-offchain-worker pallet
> A very minor bug fix - if statement logic

- .maintain/monitoring/grafana-dashboards/substrate-dabsboard.md
- .maintain/monitoring/grafana-dashboards/substrate-dashboard.json
This PR includes a simple grafana json dashboard and a brief usage guide.
The dashboard plots the graphs from a Prometheus data source, and prometheus scrapes the metrics directly from the substrate daemon.
Credits of this PR idea for @mxinden who suggested me to upload it in this subfolder.
> [[WIP]] Substrate grafana dashboard example

- bin/utils/subkey/src/main.rs
- bin/utils/subkey/src/rpc.rs
- bin/utils/subkey/src/vanity.rs
This PR has a very simple motivation that the `subkey` utility should only print "real" output to `stdout` while direct other messages like errors or vanity progress to `stderr`.
I only modified some of `println!` to `eprintln!`. And I only checked `subkey`.
> Print non-output messages to stderr in subkey

- .maintain/gitlab/check_runtime.sh
fix for https://gitlab.parity.io/parity/substrate/-/jobs/421175 when the release tag was withing git depth of cloning.
> ci: check_runtime: fetch release tag iii

- client/network/src/protocol/generic_proto/upgrade/notifications.rs
If polling encounters a `Poll::Pending` we need to return it instead of continuing the loop which may turn it into a blocking operation, causing problems with executors.
For context see: https://github.com/paritytech/polkadot/issues/909.
> sc-network: Return on Poll::Pending.

- .gitlab-ci.yml
- Cargo.lock
- client/executor/Cargo.toml
- client/executor/common/Cargo.toml
- client/executor/wasmi/Cargo.toml
- client/executor/wasmtime/Cargo.toml
- frame/benchmark/Cargo.toml
- frame/elections-phragmen/Cargo.toml
- frame/example-offchain-worker/Cargo.toml
- frame/example/Cargo.toml
- frame/staking/Cargo.toml
- primitives/allocator/Cargo.toml
- primitives/io/Cargo.toml
- primitives/phragmen/Cargo.toml
- primitives/runtime-interface/Cargo.toml
- primitives/sandbox/Cargo.toml
- primitives/wasm-interface/Cargo.toml
- test-utils/Cargo.toml
The CI failed because it missed some cargo metadata and had some version mismatches. This fixes it.
It also to roling release tags, switches to triggering the unleash-process whenever it sees `ci-release` (which we force reset) and we tag the appropriate version after it succeeded
> alpha.4 release fixes

- Cargo.lock
- client/finality-grandpa/src/communication/mod.rs
- client/finality-grandpa/src/observer.rs
- client/network-gossip/Cargo.toml
- client/network-gossip/src/bridge.rs
Previously within `<GossipEngine as Future>::poll` one would poll the
`network_event_stream` ignoring all messages other than
`Poll::Ready(Some())`. Ignoring `Poll::Ready(None)` leads to a panic on
the next poll of the stream, gien that it is not fused.
By design `network_event_stream` does not close unless an unbounded send
into it fails, or the `NetworkWorker` gets shut down.
> The stream never ends (unless the `NetworkWorker` gets shut down).
> (client/network/src/service.rs)
An `unbounded_send` to fail on an unbounded channel is unlikely. The
`NetworkWorker` shutting down is not unlikely. In such case the
`GossipEngine` should shut down as well.
With this patch a `<GossipEngine as Future>` finishes on
`Poll::Ready(None)` returned from `network_event_stream`.
In addition this pull …
>  client/network-gossip/src/bridge: Finish when network event stream closes

- .maintain/Dockerfile
Since we build them anyway, utilities such as subkey and the chain-spec-builder can be included in the image.
The new content can be checked with:
```
docker run --rm -it chevdor/substrate:20200318-8516190a8 ls -al /usr/local/bin
```
Subkey for instance can be used with:
```
docker run --rm -it chevdor/substrate:20200318-8516190a8 subkey --help
```
chain-spec-build:
```
docker run --rm -it chevdor/substrate:20200318-8516190a8 chain-spec-builder --help
```
etc...
> Add more generated utils to the image

- client/finality-grandpa/src/import.rs
- client/finality-grandpa/src/lib.rs
This PR adds support in GRANDPA for defining tuples `(SetId, (BlockHash, BlockNumber), AuthorityList)` which will be replace any existing pending authority set changes and additionally will also replace the signalled authority set change when importing a hard fork block (e.g. when syncing the chain after the fact).
> grandpa: support for hard forking any pending standard changes

- client/finality-grandpa/src/communication/tests.rs
`env_logger::init()` can lead to panics on concurrent test execution.
See: https://gitlab.parity.io/parity/substrate/-/jobs/422283
> Safe logger initialisation in test.

- client/network/src/protocol.rs
- client/network/src/protocol/sync.rs
- client/network/src/service.rs
- client/network/test/src/lib.rs
- client/network/test/src/sync.rs
This fixes a couple of issues observed on one of the validators:
* When syncing to old forks we don't check if the downloaded block is already in the queue. This may cause the same block to be added to the queue multiple times on restart. 
* When receiving announcement for some known block we set common block for that peer to be the announced block. The code assumes that if the block is known it is lower than our best blocks. This is not true since reorgs to previous (lower) blocks is possible. Fixed that check.
> Fixed a couple of syncing issues

- bin/utils/subkey/src/vanity.rs
The `vanity` subcommand of `subkey` will search for an address with a pattern. Since the address are subject to base58 encoding, the characters in the pattern should also narrow to base58. Otherwise the search will never end which is the current behaviour.
This PR fix the problem by prompting an error when user provide an invalid pattern.
> Prompt error if vanity pattern is not valid base58

- client/transaction-pool/src/lib.rs
Fixing a lone `txqueue` log target to group with `txpool`.
> Fix lone txqueue log target

- client/consensus/babe/Cargo.toml
- primitives/consensus/babe/Cargo.toml
- primitives/core/Cargo.toml
following up #4808 this makes sure we use the latest minor of schnorrkel, because before there was a potential incompatibility issue.
> Ensure schnorrkel is always _at least_ 0.9.1

- .gitlab-ci.yml
- Cargo.lock
- frame/example-offchain-worker/Cargo.toml
- frame/example-offchain-worker/src/lib.rs
- frame/example-offchain-worker/src/tests.rs
- frame/example/Cargo.toml
This makes sure that `frame-example` and `frame-example-offchain-worker`
compile for wasm.
This also fixes compilation for these crates. The offchain worker
example doesn't use serde-json anymore as that is too heavy and breaks
`no_std` compilation.
> Make sure frame examples compile for wasm

- client/network-gossip/src/state_machine.rs
The modified gossip debug message currently accounts for about 35% of all log messages on a node with quite a few debug options enabled. This adds up a bit when shipping logs remotely, could we reduce the log level to trace.
> Adjust loglevel on gossip output

- client/network-gossip/src/state_machine.rs
A gossip validator returns `ValidationResult::Discard` for messages that
should not be processed nor kept due to not being useful for the node.
Examples are out-of-scope messages or messages with bad signatures. The
corresponding log message did not reflect this, thus the update through
this patch.
One caveat is a finality grandpa neighbor packet. Given that the concept
of neighbor packets is handled in the finality grandpa gossip validator
only, valid neighbor packets are always discarded on the
`client/network-gossip` layer.
> client/network-gossip/state_machine: Fix log message

- client/network/src/protocol/generic_proto/tests.rs
Fix #5345 
At the end of the test, we wait 3 seconds to make sure that nodes don't disconnect during this period. The panic #5345 happens if we receive *any* event from the network service during this wait, including things not related to connections/disconnections.
In addition to fixing the panic I also rewrote the test to use async/await.
> Rewrite reconnect_after_disconnect test with async/await

- bin/node/runtime/src/lib.rs
- frame/elections-phragmen/src/lib.rs
- frame/staking/src/lib.rs
- frame/support/src/storage/migration.rs
- primitives/phragmen/src/lib.rs
- primitives/phragmen/src/mock.rs
- primitives/phragmen/src/tests.rs
Fixes #5290 
This just uses Borda count for now.
This also combines the `StakeOf` and `VotesOf` items which were inexplicably separated, thus causing two trie ops when one was required.
> Sensible way of selecting Prime member

- frame/treasury/src/benchmarking.rs
- frame/treasury/src/lib.rs
- frame/treasury/src/tests.rs
A reduction of https://github.com/paritytech/substrate/pull/5314/files
This simply updates the pallet to use `on_initialize` instead of `on_finalize`, and updates the `tip` logic so that it keeps the Treasury account alive.
> Switch Treasury to `on_initialize`, Tips `KeepAlive`

- utils/frame/benchmarking-cli/Cargo.toml
This duplicates the behavior of `client/service` and adds a default feature of `rocksdb` to the `frame-benchmarking-cli`.
Closes https://github.com/paritytech/substrate/issues/5363
> Add default rocksdb feature to `frame-benchmarking-cli`

- .gitlab-ci.yml
This adds a new CI job which compiles and tests the Substrate node with the feature flag `runtime-benchmarks` to ensure nothing is broken or gets broken.
I see one issue already:
```
error[E0046]: not all trait items implemented, missing: `add`
--> /Users/shawntabrizi/.cargo/git/checkouts/substrate-7e08433d4c370a21/feac1d9/frame/elections-phragmen/src/lib.rs:773:1
|
773 | impl<T: Trait> Contains<T::AccountId> for Module<T> {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `add` in implementation
|
= help: implement the missing item: `fn add(_: &T) { todo!() }`
```
Eventually, when benchmarks automatically create tests which verify the benchmarks work, this will be especially helpful.
> Add `runtime-benchmarks` compile/test in CI pipeline

- frame/contracts/COMPLEXITY.md
The `ext_terminate` [PR](https://github.com/paritytech/substrate/pull/5234) was missing some updates to the `COMPLEXITY.md`. This adds the missing explanations and other updates.
I am unsure about how many DB writes a contract deletions induces. Please review that part carefully.
> Update COMPLEXITY.md for ext_terminate

- client/consensus/babe/src/authorship.rs
- client/consensus/babe/src/lib.rs
- client/consensus/babe/src/tests.rs
- client/consensus/babe/src/verification.rs
- frame/babe/src/lib.rs
- frame/babe/src/tests.rs
- primitives/consensus/babe/src/digests.rs
- primitives/consensus/vrf/src/schnorrkel.rs
This splits BABE's `PreDigest` into `PrimaryPreDigest` and `SecondaryPreDigest`, making some code clearer, and also allowing reuse of `SecondaryPreDigest` in Sassafras. Encoding should stay the same.
> Split PrimaryPreDigest and SecondaryPreDigest

- frame/staking/reward-curve/src/log.rs
Replace base two operations with a simple shift left operation.
Moves the operation from `O(log(N))` to `O(1)` where `N` is the exponent.
The PR should be fairly frictionless.
> frame: base 2 pow is just a shift left op

- frame/contracts/COMPLEXITY.md
- frame/contracts/src/tests.rs
- frame/contracts/src/wasm/runtime.rs
Two XX is an unsecure hash which is pretty fast. It is not clear how the contracts will use this and if there would be actual big differences with the crypto hashes.
So we just wipe this until we find good reasons to put it back.
Kudos to @Robbepop who spotted this.
> Remove XX hash from contract API.

- client/service/src/lib.rs
Notification stream pops hashes for all transactions, and only propagable should be picked in network service.
> Fix propagation in network

- .gitlab-ci.yml
- primitives/arithmetic/fuzzer/Cargo.toml
After #5401 I noticed that CI failed on master (https://gitlab.parity.io/parity/substrate/-/jobs/432668), this PR adds the missing metadata.
Also, do we really want to get this particular crate published on crates.io?
> primitives: add missing cargo metadata to sp-arithmetic-fuzzer

- bin/node-template/node/Cargo.toml
- bin/node-template/node/src/chain_spec.rs
- bin/node-template/node/src/service.rs
- bin/node-template/pallets/template/Cargo.toml
- bin/node-template/pallets/template/src/lib.rs
- bin/node-template/pallets/template/src/mock.rs
- client/executor/src/native_executor.rs
A few months ago the majority of `Cargo.tmol` files throughout the Substrate code base were refactored to not alias crates. This PR cleans up a few that were missed in the node template.
> Remove package aliases from node template

- client/finality-grandpa/src/until_imported.rs
`BlockGlobalMessage` owns an `inner` which contains (1) a count for the
amount of outstanding blocks to be waited on and (2) the message itself.
Given that both is already wrapped in an `Arc` there is no need to keep
track of the outstanding blocks, given that it simply corresponds to the
amount of strong reference counts on the `Arc` itself.
This commit removes the atomic counter within `inner` and piggy backs on
the `Arc` reference counter instead.
---
On the one hand this reduces the amount of complexity given that there is no need to update the *blocks-to-be-awaited* counter anymore, on the other hand it makes the *blocks-to-be-awaited* counting implicit instead of explicit. Let me know what you think.
> client/finality-grandpa/src/until_imported: Refactor BlockGlobalMessage

- client/network/src/protocol/sync.rs
- client/network/test/src/sync.rs
Root issue is this:
1. Our best block is N, all other peers have best block N'. Our common block with all other peers is N-1
2. We finalize N, all other peers also re-org to N and finalize it. At this point we assume all other peers are still on N' since the network protocol does not notify of re-orgs.
3. Since we now assume all peers are on a fork that we discarded after finalization we don't request anything from them.
Before #5277 it kinda worked because we'd update common block next time peers send us new block announcement. Relying on block announcements for this is still incorrect though. Reorgs that happen due to finalization don't produce any announcements. I believe this should be properly fixed by introducing a new network message that notifies of reorgs eventually.  For now …
> Allow syncing to peers with finalized common block

- primitives/core/src/crypto.rs
I found myself wanting to use this as the key in a map (not in a runtime), and couldn't because it wasn't hashable. Didn't see any reason it shouldn't be.
Thanks!
> Make AccountId32 hashable

- frame/contracts/src/account_db.rs
- frame/contracts/src/lib.rs
- frame/contracts/src/tests.rs
Contracts now longer rely on this callback to tell them when they are removed. Instead, they can only self destruct  using `ext_terminate`.
Even without this change the now removed implementation wasn't called anymore in our default substrate runtime.
closes #4952
> contracts: Remove OnKilledAccount implementation

- .maintain/gitlab/check_polkadot.sh
fix for https://github.com/paritytech/substrate/pull/5262 to be able to use links in the reference of polkadot companions.
this is just for testing:
polkadot companion: https://github.com/paritytech/polkadot/pull/938
> ci: check_polkadot: accept linking to polkadot pr

- .maintain/gitlab/check_polkadot.sh
follow-up pr of https://github.com/paritytech/substrate/pull/5410
check for a reference to a polkadot pull request in the description of a pull request here if no explicit declaration can be found.
this pull request https://github.com/paritytech/polkadot/pull/916 is just set for testing.
this is for overwriting the pr mentioned in the description before:
polkadot companion: paritytech/polkadot#919
> ci: check_polkadot: look for arbitrary link to polkadot pr eventually

- frame/babe/src/lib.rs
- frame/grandpa/src/lib.rs
- frame/im-online/src/lib.rs
- frame/staking/src/inflation.rs
- frame/staking/src/slashing.rs
- primitives/arithmetic/fuzzer/src/per_thing_rational.rs
- primitives/arithmetic/src/per_things.rs
- primitives/runtime/src/curve.rs
This removes the requirement to import `PerThing` to use a type that
implements the trait.
Fixes: https://github.com/paritytech/substrate/issues/5421
> Make all `PerThing` types implement all trait methods on the type

- frame/staking/src/mock.rs
- frame/staking/src/tests.rs
- frame/timestamp/src/lib.rs
tests in staking were triggering the error:
```
[2020-03-26T15:55:16Z ERROR pallet_timestamp] `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0
```
This is because in the test environment the timestamp was set at 0 as if the tests were happening at UNIX_EPOCH.
This PR fix this false positive.
Additionnal note: should we turn `frame_support::debug::error!` into a panic when compiled in debug mode? or should we make CI fail on those messages?
I don't know how to avoid having this happening again
> Fix staking tests false positive log error

- .gitlab-ci.yml
- bin/node/cli/Cargo.toml
When using the new feature of cargo `cargo build -Z features=itarget`,
the `wasmtime` feature will not bleed into the build for other
architectures.
We can do the same for Polkadot.
Fixes: https://github.com/paritytech/substrate/issues/4188
CC @bjornwgnr @pepyakin @riusricardo
> Enable `wasmtime` only for `x86_64` in substrate node

- frame/support/procedural/src/storage/genesis_config/mod.rs
- frame/support/src/event.rs
in the expansion of generic event we forgot to hide the function metadata from the doc,
but we do in the expansion of non generic event.
in the expansion of decl_storage GenesisConfig struct and one of its function doesn't have doc.
This fix it.
> Hide metadata function for in decl_event, and add doc for GenesisConfig

- primitives/core/src/crypto.rs
Forgive me if this is philosophically objectionable for some reason, if it is please enlighten me. After I made the change from old `AnySignature` to the new `MultiSignature` I found myself needing to do this in my rust client code quite a bit, and this change would avoid newtype wrappers or ugly `.0.into()` conversions.
> Provide easy conversions from common key types to `AccountId32`

- Cargo.lock
- client/transaction-pool/Cargo.toml
- client/transaction-pool/src/lib.rs
- client/transaction-pool/src/revalidation.rs
- client/transaction-pool/src/testing/pool.rs
Closes #5399 
Closes #5313 
Closes #5144
> Refactor timer in txpool tests

- Cargo.lock
- bin/node/cli/src/command.rs
- client/cli/Cargo.toml
- client/cli/src/lib.rs
The signal handler will be reset to the default system one. This means
the program will be exited instead of panicking. This is required to
support piping in the console.
Fixes: https://github.com/paritytech/substrate/issues/4248
> Add method to `sc-cli` to reset the `SIGPIPE` signal handler

- primitives/arithmetic/src/per_things.rs
@thiolliere probably need to turn on remove whitespaces at the end of line
> Fix warnings & format

- client/service/src/builder.rs
The library `sysinfo` exposes process memory as kibibytes and not bytes,
thus the value needs to be multiplied by 1024 to comply with the metric
name and the Prometheus base units [1].
[1] https://prometheus.io/docs/practices/naming/#base-units
> src/service/src/builder: Fix memory metric exposed in bytes not KiB

- bin/utils/subkey/src/main.rs
Showing the Network ID/Version when creating or inspecting with subkey
This helps a user to confirm the input parameters are correct when creating or inspecting a key with a specific network.
> Show network id/version in subkey

- .gitlab-ci.yml
- .maintain/gitlab/check_polkadot_companion_build.sh
- .maintain/gitlab/check_polkadot_companion_status.sh
check the status of a polkadot companion pull request
> Ci check companion

- Cargo.lock
- client/network/src/protocol/generic_proto/handler/group.rs
- client/transaction-pool/Cargo.toml
- client/transaction-pool/src/testing/pool.rs
(testing timers is hard, but it should nail it)
Closes #5144
> And one more fix to flaky tests

- bin/node/runtime/src/lib.rs
- frame/benchmarking/src/lib.rs
This iterates on https://github.com/paritytech/substrate/pull/5436.
* Moves the macro to `frame_benchmarking`
* Updates the name from `pallet!` to `add_benchmark!`
* Update the syntax and construction of the macro just a little bit to pass the non-local variables to the rust macro.
> Its a little bit nasty, but imo not that bad.
* Adds some docs.
> Move fast benchmarks macro into `frame_benchmarking`

- client/authority-discovery/src/tests.rs
- client/finality-grandpa/src/tests.rs
- primitives/api/proc-macro/src/decl_runtime_apis.rs
- primitives/api/proc-macro/src/impl_runtime_apis.rs
- primitives/api/proc-macro/src/lib.rs
- primitives/api/proc-macro/src/mock_impl_runtime_apis.rs
- primitives/api/proc-macro/src/utils.rs
- primitives/api/src/lib.rs
- primitives/api/test/tests/decl_and_impl.rs
- primitives/api/test/tests/ui/mock_only_error_associated_type.rs
- primitives/api/test/tests/ui/mock_only_error_associated_type.stderr
- primitives/api/test/tests/ui/mock_only_one_block_type.rs
- primitives/api/test/tests/ui/mock_only_one_block_type.stderr
- primitives/api/test/tests/ui/mock_only_one_error_type.rs
- primitives/api/test/tests/ui/mock_only_one_error_type.stderr
- primitives/api/test/tests/ui/mock_only_one_self_type.rs
- primitives/api/test/tests/ui/mock_only_one_self_type.stderr
- primitives/api/test/tests/ui/mock_only_self_reference.rs
- primitives/api/test/tests/ui/mock_only_self_reference.stderr
This pr adds support for easily mock runtime api implementations for
tests by using the `mock_impl_runtime_apis!` macro. The syntax is
similar to `impl_runtime_apis!`. The mocked implementation automatically
implements `ApiExt`, `ApiErrorExt` and `Core` as these are required by
the runtime api traits, but not required in tests or only a subset of them.
- Grandpa & authority discovery tests look much better.
Closes: https://github.com/paritytech/substrate/issues/1120
polkadot-companion: https://github.com/paritytech/polkadot/pull/957
> Implements mocking of runtime apis

- .maintain/gitlab/check_polkadot_companion_status.sh
disable check for `mergeable_status` on polkadot companion pr
> ci: check_polkadot_companion_status: don't verify mergeable_state

- client/network/src/protocol/generic_proto/handler/group.rs
- client/network/src/protocol/light_client_handler.rs
I'm working on a pull request that switches to this new light client protocol, but I realized that none of the requests are going through on Polkadot because the maximum response size is too low.
Even the most basic responses are 1.7MiB in size, so more than the default 1MiB.
Unfortunately this also causes the connection to be force-closed (and immediately reopened afterwards) because of https://github.com/libp2p/rust-libp2p/issues/1530
I'm opening this PR separately because we need it to be deployed on full nodes before light client can switch to this new protocol.
> Increase limit on light client response size

- client/finality-grandpa/src/environment.rs
- client/finality-grandpa/src/lib.rs
- client/finality-grandpa/src/observer.rs
- client/finality-grandpa/src/until_imported.rs
The `UntilImported` queue takes as input finality grandpa messages that
depend on blocks that are not yet imported and holds them back until
those blocks are imported.
This commit adds a basic metric, the amount of messages waiting in the
queue, to the module. For now this metric is only available for the
global `UntilImported` queue awaiting blocks for commit and catch-up
messages.
```
substrate_finality_grandpa_until_imported_waiting_messages_number 11
```
> client/finality-grandpa: Instrument until-imported queue

- Cargo.lock
- bin/node/cli/src/chain_spec.rs
- bin/node/runtime/src/lib.rs
- bin/node/testing/src/genesis.rs
- frame/elections-phragmen/Cargo.toml
- frame/elections-phragmen/src/lib.rs
- primitives/arithmetic/src/per_things.rs
Fix https://github.com/paritytech/substrate/issues/5097. 
Although, this mostly demonstrates the issue. This is kind of a footgun since the genesis value of collective and elections must be the same, otherwise the behaviour is even more obscure.  and I think a better way is to: 
- `trait ChangeMembers` should expose one function `initial_members()` that `elections()` can call and get the initial members. 
Basically, from the PoV of elections, whatever module we report the new members to, also gives us the initial ones. Hence, no need for a new trait and can be within the same trait.  
Although, this brings the question of: How much stake should we give to the initial members? the collective module does not know that. The current genesis approach is good in the sense that it makes it …
> Fix Collective <-> Elections initialization.

- client/network/src/behaviour.rs
- client/network/src/lib.rs
- client/network/src/protocol.rs
- client/network/src/protocol/generic_proto/behaviour.rs
Small clean up.
Removes the `DiscoveryNetBehaviour` trait and turns its method into a regular method. The trait is entirely internal to the network crate, so this is not a breaking change.
This trait was an earlier attempt at a first step to make the behaviour configurable, which we've given up for now considering the stability requirements of Substrate.
> Remove DiscoveryNetBehaviour trait

- client/consensus/babe/src/aux_schema.rs
- client/consensus/epochs/src/lib.rs
- client/consensus/epochs/src/migration.rs
This was removed in https://github.com/paritytech/substrate/pull/5291 but it's still too early to do it as it requires nodes still on Polkadot v0.7.26 to resync from scratch.
Fixes #5486
> babe: restore epoch changes migration code

- .gitlab-ci.yml
Previously `CARGO_HOME` was divided between CI jobs only, and it was fine. There was no sensible concurrency for the dependencies' sources. 
Since [1.41](https://github.com/rust-lang/cargo/issues/4007) we've been experiencing a lot of troubles with the corrupted cache.
This PR is a simple workaround:
Pros:
+ It **should stop** requiring cache purging because of the error
Cons:
- every **new** PR pipeline will download all the deps for every CI runner. 
- it will use more disk space on CI servers
On the bright side, it will be easier to clean cache only for those jobs which need that.
> ci: divide cache between branches

- client/cli/src/lib.rs
When formatting timestamps used for logging we convert from nanoseconds to milliseconds by dividing and rounding up, instead we should floor the result. Spotted here:
```
2020-04-02 18:03:46.055 main-tokio- INFO substrate  💤 Idle (0 peers), best: #462 (0x0635…d863), finalized #459 (0x7364…9476), ⬇ 0 ⬆ 0
2020-04-02 18:03:47.999 main-tokio- TRACE babe  extract timestamp
2020-04-02 18:03:47.999 main-tokio- TRACE babe  extract timestamp
2020-04-02 18:03:47.1000 main-tokio- TRACE babe  extract timestamp
```
> cli: fix milliseconds formatting on logs

- Cargo.lock
- bin/node-template/pallets/template/Cargo.toml
This PR removes an unneeded dependency on `safe-mix` from the template pallet.
> Remove unused dependency on safe-mix

- client/network/src/protocol.rs
- client/network/src/protocol/generic_proto/behaviour.rs
- client/network/src/protocol/generic_proto/handler/group.rs
- client/network/src/protocol/generic_proto/handler/notif_out.rs
- client/network/src/protocol/generic_proto/tests.rs
- client/network/src/protocol/generic_proto/upgrade/notifications.rs
- client/network/src/service.rs
- utils/prometheus/src/lib.rs
Reports on a `Histogram`, for each protocol, the queue size.
This means that if we send for example 2 messages, then we will report 2 then 1 then 0, or 2 then 0. Therefore the "sum" is rather meaningless, as when sending 2 messages it could be either 3 or 2.
Instead, the idea is to use the "buckets" feature of Prometheus to see the number of times where we reached a certain value.
One question is: should be really call `observe()` when we flush the queue? Should we not call it only when we push a message, so that the value represents the size that a queue had when we sent a message?
> Add a sub_libp2p_notifications_queues_size Prometheus metric

- primitives/core/src/crypto.rs
**Motivation**
Added standard account prefix for [Robonomics](https://robonomics.network) and [derivative](https://blog.aira.life/genesis-block-of-dao-ipci-on-robonomics-substrate-ed4b6f7f991) networks.
> Added Robonomics network standard account prefix

- client/network/src/protocol/generic_proto/handler/notif_out.rs
- client/network/src/protocol/generic_proto/upgrade/notifications.rs
Supercedes #5500 
Improves the logging for the queue being full, and fixes the fact that the warning is being printed when we fail to immediately flush the queue.
We now only push the element, and flushing is handled by the `poll` function.
This is how this code was originally intended to behave, and the fact that we were immediately trying to flush the queue was not intended.
We also now report the queue size to Prometheus even when it's full.
> Improve warning about notifications queue and remove spurious triggers

- .maintain/gitlab/check_polkadot_companion_build.sh
Ci for companion on #4857 stopped working after #5468. I am not totally sure how to reproduce it, locally I simple uses zsh that seems to do a similar thing (pr_body fails to extract), when bash works just fine.
This change attempt to fix that by just removing the body extract, which is not very satisfying, I did not find a way to extract the body properly (I wonder if jq is available for ci).
> Companion PR ci sed issue.

- frame/staking/src/benchmarking.rs
The `payout_nominator` benchmarks was returning an error because we try to test for nominating zero validators, which is an error case in the extrinsic.
This simply updates the test to run starting from 1.
> Fix `payout_nominator` benchmarks

- frame/benchmarking/src/lib.rs
- frame/example/Cargo.toml
- frame/example/src/lib.rs
We made it so that events are not emitted on block zero, but did not bump the block number for running benchmarks.
This fixes that by setting the block number to one at the beginning of every benchmark.
EDIT: This additionally fixes a CI issue where benchmarks in the Example pallet weren't compiling to Wasm because they weren't behind a feature flag.
> Run Runtime Benchmarks on Block One

- .maintain/gitlab/check_polkadot_companion_build.sh
check for arbitrary `paritytech/polkadot#123` like strings as well
> ci: check_polkadot: check for companion

- frame/recovery/src/lib.rs
- frame/scheduler/src/lib.rs
- frame/sudo/src/lib.rs
- frame/support/src/dispatch.rs
- frame/support/src/lib.rs
- frame/support/src/weights.rs
- frame/utility/src/lib.rs
- primitives/runtime/src/generic/checked_extrinsic.rs
- primitives/runtime/src/lib.rs
- primitives/runtime/src/testing.rs
- primitives/runtime/src/traits.rs
#5130: The GCD is an older alternate approach to the same problem. This PR seeks to replace it.
#5032: In this PR we lay the ground work that will eventually allow refunding. The linked PR therefore depends on the work done here. However, the linked PR is currently stand alone and will probably be rewritten given  the approach in this PR is deemed viable.
Introduce an associated type `PostInfo`  to the `Dispatchable` trait that becomes part of its return type and implement it in frame so that it is used to return the a posteriori actual weight of a call.
It is done in a way that requires very little code changes to the existing frame pallets. The only pallets that need to be (minimally) changed are those that do dispatching (sudo, recovery, ...) because they need to deal with the new …
> Make Dispatchable return the actual weight consumed

- client/service/Cargo.toml
- client/service/src/metrics.rs
following #5414, this adds a more specific plattform bound around the usage of `procfs` and fixes some minor bugs to to fix the build on mac and windows.
> Fix non-linux build of sc-client

- frame/elections-phragmen/src/lib.rs
Elections Phragmen importantly assumes that the `Member` list is sorted. However, construction of the storage item in genesis did not check that it was sorted.
This fixes that and adds a test :)
(It also repairs my sanity, took me a while to find what was messing up my benchmarks!)
> Sort members in elections-phragmen genesis

- .gitlab-ci.yml
Reverts paritytech/substrate#5505
Apparently, cache pre-population from other branches with other versions of deps can cause the `cargo` [bug](https://github.com/rust-lang/cargo/issues/4007).
To avoid it, everyone should rebase on this commit.
<details>
<summary>Logs</summary>
```
thread 'main' panicked at 'packages downloaded: failed to download `hermit-abi v0.1.10`
Caused by:
0: unable to get packages from source
1: failed to parse manifest at `/ci-cache/substrate/cargo/5515/check-web-wasm/registry/src/github.com-1ecc6299db9ec823/hermit-abi-0.1.10/Cargo.toml`
2: no targets specified in the manifest
either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
0: cargo::ops::cargo_read_manifest::read_package
1: cargo::sources::path::PathSource::read_packages
2: …
```
> Revert "prepopulate CARGO_HOME caches"

- client/network/src/service.rs
- utils/prometheus/src/lib.rs
Instead of reporting just the number of notifications sent and received through a counter, this PR now also reports their sizes in bytes through a histogram.
Consequently I renamed `notifications_total` to `notifications_sizes`.
> Prometheus Metrics: Turn notifications_total counter into notifications_sizes histogram

- .gitlab-ci.yml
Since we care to fail the merge if warnings are found in the test CI job, it makes sense to merge `check_warnings` job into `test-linux-stable`. 
As a bonus, it will not queue for docker runners.
> change (ci): merge check warnings into test linux job

- primitives/application-crypto/src/lib.rs
- primitives/phragmen/src/reduce.rs
The macros should not generate code that requires that the calling crate
has a feature with the name `std` defined.
> Make `application-crypto` `std` feature internal

- client/consensus/babe/src/lib.rs
- client/finality-grandpa/src/authorities.rs
- client/finality-grandpa/src/environment.rs
- client/finality-grandpa/src/import.rs
- client/finality-grandpa/src/lib.rs
- client/finality-grandpa/src/observer.rs
During initial sync the following consensus log messages are logged under debug to avoid spamming the output.
```
2020-04-06 19:59:57 👶 Next epoch starts at slot 262521879
2020-04-06 19:59:58 👶 New epoch 47 launching at block 0x456c…19f0 (block slot 262521879 >= start slot 262521879).
2020-04-06 19:59:58 👶 Next epoch starts at slot 262522479
2020-04-06 19:59:58 👴 Applying authority set change scheduled at block #28175
2020-04-06 19:59:58 👴 Applying GRANDPA set change to new set with 20 authorities
2020-04-06 19:59:58 👴 Imported justification for block #28175 that triggers command Changing authorities, signaling voter.
```
> babe, grandpa: restrict info logging during initial sync

- frame/balances/src/tests.rs
- frame/balances/src/tests_composite.rs
- frame/balances/src/tests_local.rs
- frame/contracts/src/lib.rs
- frame/contracts/src/tests.rs
- frame/example/src/lib.rs
- frame/executive/src/lib.rs
- frame/staking/src/lib.rs
- frame/staking/src/tests.rs
- frame/support/src/dispatch.rs
- frame/support/src/metadata.rs
- frame/system/src/lib.rs
- frame/transaction-payment/src/lib.rs
- primitives/runtime/src/generic/checked_extrinsic.rs
- primitives/runtime/src/generic/unchecked_extrinsic.rs
- primitives/runtime/src/testing.rs
- primitives/runtime/src/traits.rs
- test-utils/runtime/src/lib.rs
polkadot companion: https://github.com/paritytech/polkadot/pull/979
This PR refactors the trait `SignedExtension`. The following changes where applied:
This information logically belongs to the `Dispatchable`. Not having it there requires consuming types to duplicate this as an associated type (`SignedExtension, Applyable`).
This is a requirement for the first change. Because the `DispatchInfo` type is now an associated type on `Dispatchable`.
This is a followup of #5458 that passes this new information to the `SignedExtension` where it can then be used to accomplish weight refund (in a followup PR).
There was no apparent reason (or is there one?) for having `DispatchInfo` to be cloned into every `SignedExtension`.
> Refactor SignedExtension

- client/network/src/service.rs
cc #5235 (although none of the metrics I added are mentioned in this issue)
I think this adds all the metrics that we might want to have when it comes to low-level connections. Also modifies the `connections` metric to show the direction ("in" or "out").
I'm going to test this out on my node, but you can start reviewing.
> Add more Prometheus metrics

- Cargo.lock
- client/transaction-pool/Cargo.toml
- client/transaction-pool/src/revalidation.rs
- client/transaction-pool/src/testing/pool.rs
Again, deterministic timers is hard, but this should work. The idea is to trigger event only when something was processed, thus test code can block on that :)
> Remove flakiness from transaction pool tests (again)

- utils/build-script-utils/src/git.rs
There was a bug in determining the correct git files that should be
tracked. The ref extracted from `.git/HEAD` pointed to a relative path
and thus could not be found by cargo and resulted in always recompiling
the binary.
> Don't always recompile the node binary on `cargo run`

- client/authority-discovery/src/error.rs
- client/authority-discovery/src/lib.rs
- client/authority-discovery/src/tests.rs
When the dht event stream returns Poll::Ready(None) it is likely due to
the network terminating. When the network terminates due to the node
itself shutting down or due to a fatal error, there is no purpose in
continuing to run the authority discovery module.
> client/authority-discovery: Terminate when network does

- client/network/src/protocol.rs
- client/network/src/protocol/generic_proto.rs
- client/network/src/protocol/generic_proto/behaviour.rs
- client/network/src/protocol/generic_proto/handler.rs
- client/network/src/service.rs
The `"Severe protocol error"` in practice at the moment happens only if the remote is not on the same chain as we do. The comment mentions "a peer that doesn't speak the same protocols", but that equates "being on a different chain".
Since it can happen frequently even in normal situations, this PR turns it into a `debug` log in order to not spam users.
Additionally, we now also report ping failures and voluntarily closing the connection in separate categories.
(voluntarily closing the connection happens as a result of the "Severe protocol error")
> Report local force-closing connections to Prometheus

- client/network/src/protocol/generic_proto/behaviour.rs
A follow-up patch to https://github.com/paritytech/substrate/pull/5278. I believe this to be the cause for https://github.com/paritytech/substrate/issues/5592 because `inject_connection_closed` prematurely triggers an emit of `CustomProtocolClosed`, but it should only do so if `open` is empty (and was not already empty before).
> Do not prematurely emit CustomProtocolClosed on connection close.

- Cargo.lock
- bin/utils/subkey/Cargo.toml
- client/authority-discovery/Cargo.toml
- client/network-gossip/Cargo.toml
- client/network/Cargo.toml
- client/network/src/service.rs
- client/network/test/Cargo.toml
- client/peerset/Cargo.toml
- client/telemetry/Cargo.toml
- primitives/consensus/common/Cargo.toml
- utils/browser/Cargo.toml
This PR is ready and can be reviewed.
I marked this as "draft" because libp2p 0.18 hasn't been published yet and the CI will fail.
> Update to libp2p 0.18

- frame/elections-phragmen/src/lib.rs
- frame/staking/src/lib.rs
- frame/staking/src/mock.rs
- frame/staking/src/tests.rs
Adds some tests that get executed at the end of each test case in some modules: 
- `staking`: Ledger and Exposure should always be correct.
- `elections-phragmen`: Members must always be sorted. Members, runners-up and candidates must be disjointed etc.   
This should make it easier to detect bugs such as https://github.com/paritytech/substrate/pull/5522.
- I think more modules can use such a pattern. Balances should always be consistent but maybe that is too trivial (total == free + reserved).
> Post-condition checking for some pallets 

- bin/node/executor/tests/basic.rs
- frame/support/src/weights.rs
- frame/system/src/lib.rs
- frame/transaction-payment/src/lib.rs
#5032 predecessor and replaced by this PR
#5458 Groundwork that allows dispatchables to return the actual weight consumed
#5540 Groundwork that allows `SignedExtension` to access the actual weight
This changes the `CheckWeight` and `ChargeTransactionPayment` signed extensions to refund portions of the annotated a priori maximum weight in their `post_dispatch` method. A  `Dispatchable` has the ability (since #5458) to  return the a posteriori weight that is lower than the annotated max weight. Here we make use of that information in order to do the actual refund.
We want dispatchables to be able to refund portions it their static a priori weight maximum. The reason for that is that there are dispatchables where the average weight consumed differs from the maximum. Without a refund we are …
> Introduce weight refund

- primitives/timestamp/Cargo.toml
Fixes: https://github.com/paritytech/substrate/issues/5607
> Disable `wasm-timer` in `no_std`

- Cargo.lock
- bin/node-template/node/src/command.rs
- bin/node/cli/Cargo.toml
- bin/node/cli/src/command.rs
- client/cli/Cargo.toml
- client/cli/src/runner.rs
- frame/collective/src/benchmarking.rs
Polkadot companion: https://github.com/paritytech/polkadot/pull/983
> Fix native version text on startup

- client/network/src/protocol/sync.rs
This adds additional protection against misbehaving peers.
*  When peers sends us blocks that we already have we decrease their reputation. This may happen during initial sync currently only if they lied about their common block.
* When doing initial ancestry search on connection, we might be actively syncing so it's hard to find a common block correctly. If the sync made progress while the search is in progress it is now aborted and the common block assumed to be found under certain conditions.
> More robust sync

- bin/node/bench/src/core.rs
- bin/node/bench/src/import.rs
- bin/node/bench/src/main.rs
```
-m, --mode <mode>    
Mode
"regular" for regular becnhmark
"profile" mode adds pauses between measurable runs, so that actual interval can be selected in the profiler
of choice. [default: regular]
```
> Benchmarks profile mode

- Cargo.lock
- primitives/arithmetic/Cargo.toml
- primitives/arithmetic/src/fixed128.rs
- primitives/arithmetic/src/lib.rs
- primitives/arithmetic/src/per_things.rs
- primitives/arithmetic/src/traits.rs
- primitives/runtime/src/lib.rs
Supersede #5606
Initially developed at https://github.com/laminar-protocol/open-runtime-module-library/blob/master/utilities/src/fixed_128.rs
Only checked and saturating ops are implemented and no panic ops.
TODO:
> Introduce `Fixed128` from ORML to `sp_arithmetic`

- bin/node/cli/src/service.rs
- client/network-gossip/src/bridge.rs
- client/network-gossip/src/lib.rs
- client/network/src/service.rs
- client/network/src/service/out_events.rs
- client/network/src/service/tests.rs
Calling `NetworkService::event_stream` now requires passing a name that helps identify it in the Prometheus metrics.
polkadot companion: https://github.com/paritytech/polkadot/pull/995
> Give names to channels

- frame/staking/src/lib.rs
- frame/staking/src/mock.rs
- frame/staking/src/offchain_election.rs
- frame/staking/src/tests.rs
phragmen solution should be submitted for the current era. the pallet-session can decide to delay by one or multiple era and dynamically. The active era should only be used for rewards stuff.
Phragmen solution submittion submit solution for the next current era so they should be submitted in the current_era, regardless of the active_era.
> Phragmen solution should submit for current era and be checked against current era

- frame/system/src/lib.rs
- frame/transaction-payment/src/lib.rs
This adds tests that check whether the weight refund is working. It is a followup to #5584. Both `frame_system::CheckWeight` and `pallet_transaction_payment` are tested.
> Add tests for weight refund

- Process.toml
Adding a basic `Process.toml` file for the processbot to be able to pick up owners and do its thing.
> Adding Process.toml for processbot
