paritytech/substrate

primitives/api/proc-macro/src/decl_runtime_apis.rs, primitives/api/src/lib.rs, primitives/api/test/tests/ui/changed_in_no_default_method.rs, primitives/api/test/tests/ui/changed_in_no_default_method.stderr
This adds another check to the macro that ensures that not only methods
with `changed_in` exists, but there are also the default methods exist.
=> `decl_runtime_apis!` - check that a method without `changed_in` exists

Cargo.lock, client/service/Cargo.toml, client/service/src/builder.rs, client/service/src/lib.rs, client/service/src/task_manager.rs, client/service/src/task_manager/prometheus_future.rs
This PR adds Prometheus metrics to the `sc_service::task_manager` module.
There are four new metrics, each accepting a task name as label:
- A counter incremented when we create a task.
- A counter incremented when a task stops. The idea being to do `started - stopped` to know what's running.
- A histogram with how long it took to run `Future::poll`. This can be used to figure out the CPU usage of the node.
- A counter incremented every time we start polling a task. While this is kind of redundant with `poll_duration_count`, the idea is to do `poll_started - poll_duration_count` to detect tasks that are stuck.
I have consequently removed the `futures-diagnose-exec` tool, that was supposed to serve the same purpose but was totally undocumented and way more annoying to use on real nodes …
=> Report tasks metrics to Prometheus

client/cli/src/runner.rs
This used to be a prefix, but all tokio threads now have the same name. It doesn't really make sense to rename them anymore.
https://docs.rs/tokio/0.2.18/tokio/runtime/struct.Builder.html#method.thread_name
=> Remove the tokio thread name

client/network/src/protocol/generic_proto/upgrade/notifications.rs, client/network/src/service.rs
It seems that the queue size of GrandPa notifications now frequently reaches the 128-256 elements bucket, as seen on this graph:
Since the hard limit is 256, I can't actually know whether notifications are discarded or not. But whether they are or not, let's increase the limit until this is taken care of.
The proper solution is #5481
=> Temporarily increase notifications buffer size

client/authority-discovery/src/lib.rs
Increase counter for every authority-addresses-request, instead of a
single increase for a batch of requests for all authorities.
With this commit one can see the amount of in-flight requests
subtracting the request counter from the
event_received{name=~"found|not_found"} counter.
---
Probably easiest to review https://github.com/paritytech/substrate/commit/65c42030fdb478c3dc9ec5d11f88a28ed6a770c7 directly.
=> client/authority-discovery: Increase request counter per request 

Cargo.lock, client/service/Cargo.toml
This release includes a fix for an out of bound access that was reported
by one of the validators.
=> Upgrade sysinfo to `0.13.3`

client/network/src/service.rs, client/network/src/service/out_events.rs
@mxinden Sorry to make you review all these changes, but you're "the Prometheus expert"!
This PR contains a couple of tweaks to the Prometheus metrics:
- Removed `connections` (a gauge) and replaced it with `connections_opened_total` (a counter), so that we no longer lose information about connections opening and closing quickly.
- Splits `connections_closed` by `in` and `out` for parity with `connections_opened_total`.
- Removed `opened_notification_streams` (a gauge) and replaced it with `notifications_streams_opened` and `notifications_streams_closed`, for the same reason.
- Added channel names to `num_channels`.
- Added a `reason` label to the `sub_libp2p_incoming_connections_handshake_errors_total` metric.
=> Several tweaks to networking Prometheus metrics

client/authority-discovery/src/error.rs, client/authority-discovery/src/lib.rs, client/authority-discovery/src/tests.rs
Instead of `handle_dht_events` returning a `Result<(), Error>`, return
a `Poll<Error>` where `Poll::Pending` signals that there are no more
events to handle and `Poll::Ready(Error)` signals that a fatal error
occured. Non fatal errors are handled within `handle_dht_events`
directly, thus looping in `poll` is not necessary anymore.
Follow up to https://github.com/paritytech/substrate/pull/5608.
@bkchr what do you think? Is this easier to parse than the previous
error handling?
=> client/authority-discovery: Rework error handling

client/network/src/service.rs, client/rpc-api/src/system/mod.rs, client/rpc/src/system/mod.rs, client/rpc/src/system/tests.rs, client/service/src/lib.rs
cc #5541
Adds alternative methods to `system_networkState` to get the local `PeerId` and local addresses we're listening on.
=> Add alternative RPC methods to system_networkState

client/cli/src/params/network_params.rs
Instead of just listening on ipv4 by default, this enables listening on
ipv6 as well. While doing this, it also fixes a bug which lead to always
listen on all sockets, even if we specify listen addresses explicitly.
Partially fixes: https://github.com/paritytech/substrate/issues/5645
=> Listen on ipv6 addesses by default as well

Cargo.lock, frame/support/src/storage/migration.rs, frame/transaction-payment/Cargo.toml, frame/transaction-payment/src/lib.rs, primitives/arithmetic/src/fixed64.rs
The Transaction Payment pallet used to use `Fixed64` for the `NextFeeMultiplier`, but due to the upgrade of weights from u32 to u64, it now uses `Fixed128`.
This is some simple migration code to make that change, and a test to verify it works.
=> Migration for `pallet-transaction-payment` transitioning to u64 weights

.gitlab-ci.yml
Solves #5652 
This is my attempt to remove the CI job that published rustdocs to github.com/substrate-developer-hub/rustdocs . Now that Substrate is on crates.io, our docs are on docs.rs and we no longer need to host them ourselves.
This PR does **not** intend to remove the CI job that publishes the rustdocs for master branch to crates.parity.io . I'm not sure where that job lives though, so I'd appreciate if someone can confirm that I haven't messed it up.
=> remove rustdocs script

bin/node/runtime/src/lib.rs, frame/treasury/src/lib.rs, frame/treasury/src/tests.rs
TipClosed was never referenced in the code
=> emit TipClosed event on success tip payout

client/cli/src/commands/mod.rs, client/cli/src/config.rs, client/cli/src/params/network_params.rs, client/network/src/config.rs, client/network/src/service.rs, client/network/test/src/lib.rs, client/service/test/src/lib.rs, utils/browser/src/lib.rs
=> Make network_config_path an Option

client/cli/src/params/network_params.rs
It leads to the following errors:
```
2020-04-17 16:40:25 Libp2p listener ListenerId(1) closed
2020-04-17 16:40:25 Libp2p => ListenerClosed: Err(Custom { kind: Other, error: Custom { kind: Other, error: Other(A(A(A(B(Underlying(B(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))))))) } })
...
2020-04-17 16:43:13 Error on libp2p listener ListenerId(2): ::ffff:127.0.0.1 does not match any listen address
2020-04-17 16:43:13 Error on libp2p listener ListenerId(2): ::ffff:10.128.0.9 does not match any listen address
```
Let's revert this for the release of Polkadot 0.7.30 and open an issue instead.
=> Revert listening on IPv6 by default

bin/utils/subkey/README.adoc, bin/utils/subkey/src/main.rs
This PR adds a subcommand to subkey: `moduleid`. It can be used to display the public key and SS58 version of a moduleid, this can be used to compute the moduleid of the treasury or of a multisig for instance.
=> subkey: compute and inspect a moduleid

client/network/src/discovery.rs
Refactors a bit the log printing in `discovery.rs`.
We frequently call `addresses_of_peer` purely for debugging purposes, and it is thus wrong to emit a log message that says `"Requested dialing"`.
If the method is indeed called because we request dialing, there should be another line to indicate that.
Additionally, we now emit one line instead of two when no address is found.
=> Refactor misleading log in discovery

frame/collective/src/benchmarking.rs
This allows us to check an event fired at the end of a benchmark
=> Add checks for events

client/cli/src/commands/mod.rs, client/cli/src/commands/runcmd.rs, client/cli/src/config.rs, client/rpc-api/src/author/error.rs, client/rpc-api/src/lib.rs, client/rpc-api/src/offchain/error.rs, client/rpc-api/src/policy.rs, client/rpc-api/src/system/mod.rs, client/rpc/src/author/mod.rs, client/rpc/src/author/tests.rs, client/rpc/src/lib.rs, client/rpc/src/offchain/mod.rs, client/rpc/src/offchain/tests.rs, client/rpc/src/system/mod.rs, client/rpc/src/system/tests.rs, client/service/src/builder.rs, client/service/src/config.rs, client/service/src/lib.rs, client/service/test/src/lib.rs, utils/browser/src/lib.rs
Closes https://github.com/paritytech/substrate/issues/2303
Introduces machinery which allows us to deny/allow certain "unsafe" RPCs if we're exposing it to the network. The last bits (configuration) are fairly easy to add; in the meantime, I'd like to get some feedback on the initial implementation.
The aim is to provide a very simple filtering out-of-box and recommend using something like https://github.com/tomusdrw/jsonrpc-proxy for anything more complicated. We decided against a separate blacklist/whitelist with @tomusdrw since this would make things unnecessarily more scattered and harder to navigate.
Unresolved/To do:
=> Allow to expose a subset of unsafe RPCs

frame/staking/src/inflation.rs, frame/staking/src/lib.rs, frame/staking/src/mock.rs, frame/staking/src/tests.rs
Alternative to https://github.com/paritytech/substrate/issues/5696 since it currently affects Kusama, no era rewards remainders are received
- Adds the missing calc & pass from the previous version as found at https://github.com/paritytech/substrate/blob/870540b7243ed7557b83a7bb6e978351ed81ebee/frame/staking/src/lib.rs#L1428-L1432
- Always done on end_era, no depth delay before treasury has the funds
=> Pass max-total to RewardRemainder on end_era

client/network/src/config.rs, client/network/src/lib.rs, client/network/src/protocol.rs, client/network/src/service.rs, client/network/src/service/tests.rs
This is a purely internal change, to make the code a bit more readable. External APIs are untouched.
This PR moves the definitions of `ExHashT`, `TransactionPool`, `ReportHandle` and `NetworkStateInfo` out of the `service` module and directly where they are publicly re-exported.
=> Move around definitions in sc_network

Cargo.lock, Cargo.toml, client/tracing/src/lib.rs, client/transaction-pool/Cargo.toml, client/transaction-pool/src/api.rs, frame/executive/Cargo.toml, frame/executive/src/lib.rs, frame/support/Cargo.toml, frame/support/src/dispatch.rs, frame/support/src/lib.rs, primitives/runtime-interface/Cargo.toml, primitives/runtime-interface/proc-macro/src/runtime_interface/bare_function_interface.rs, primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs, primitives/runtime-interface/src/lib.rs, primitives/runtime-interface/test/Cargo.toml, primitives/runtime-interface/test/src/lib.rs, primitives/tracing/Cargo.toml, primitives/tracing/src/lib.rs
This pr improves the tracing functionality in Substrate.
1. It moves tracing macros to `sp-tracing`.
2. Moves all usages of tracing to the new tracing macros.
3. Adds tracing to runtime interfaces. It will trace the call to the native function and to the entry point of the host function that is exported to Wasm.
=> Improve tracing

frame/support/src/dispatch.rs, frame/support/src/error.rs, frame/support/src/lib.rs, frame/support/src/storage/generator/double_map.rs, frame/support/src/storage/generator/map.rs, frame/support/src/storage/generator/mod.rs, frame/support/src/storage/generator/value.rs, frame/support/src/storage/mod.rs
This adds the `try_mutate` API to Storage Value and Storage Double Map.
`try_mutate` allows you to execute a closure using the value of a storage item, and only update the value if the closure returns `Ok`.
Also includes a test!
=> Implement `try_mutate` for storage value and storage double map

primitives/core/src/crypto.rs
This PR adds a subkey ID for Polymath Network.
We took the first available ID which happened to be 12.
There are no follow-ups.
=> Added the Polymath subkey ID

client/network/src/behaviour.rs, client/network/src/lib.rs, client/network/src/protocol.rs, client/network/src/protocol/generic_proto/behaviour.rs, client/network/src/protocol/generic_proto/handler/group.rs
In the process of removing the legacy protocol, there is a problem: we need to report, in `sc_network::Event::NotificationsStreamOpened`, what the `Role` of the remote is.
This is normally why the notification protocols have a handshake. The idea is that you send your `Roles` during the substream opening handshake, which is then received by the remote, which can report it at the API layer.
However, for backwards-compatibility reason, the notification substreams are still tied to the legacy substream, and thus we directly pick the `Roles` that was sent through the legacy "status" message on the legacy substream. But we eventually want to untie them and directly determine the `Role` from the substream handshake.
This PR is the first step towards this. At the moment, the handshake is always …
=> Pass an encoded Roles as the notifications protocols handshakes

bin/node-template/node/src/command.rs, bin/node-template/node/src/service.rs
This PR moves the following line from `command.rs`, to the new_full_start!` macro where it is actually used. This makes the code more readable, prevents users from deleting that import thinking it is never used.
=> Move AuraPair import to new_full_start! macro in Node Template

client/authority-discovery/src/lib.rs
Expose the amount of addresses that are passed from the authority
discovery module down to the network peer set manager as a priority
group in order to connect to the corresponding nodes.
```
authority_discovery_priority_group_size 10
```
=> client/authority-discovery: Add metric exposing priority group size

frame/democracy/src/lib.rs, frame/offences/src/lib.rs, frame/society/src/lib.rs, frame/support/procedural/src/storage/parse.rs, frame/support/src/lib.rs
The `fn` token was already for quite some time as an optional parameter.
It was introduced to make these functions better findable. This pr makes
the `fn` token required.
=> Require `fn` token in `decl_storage` `get`

client/network/src/service/out_events.rs
The outer `Option` is set to `Some` when the sender is added to the collection.
Therefore, if the outer `Option` is still `None` when we receive an event, then something bad happened, and it should be reported with a warning.
However if the user passes `None` for the registry, then we will set the value to `Some(None)`, and that it is a perfectly normal situation.
=> Fix warning reported in out_events when Registry is None

client/cli/src/params/network_params.rs
This flag exists because we wanted to test this feature on our nodes.
Unfortunately it has never been actually enabled in practice.
In order to move things forward a bit, let's enable the option by default.
I'm running Polkadot with the flag on on my Google Cloud node today and will report if something bad/weird happens.
=> Enable yamux flow control by default

bin/node/executor/tests/basic.rs, frame/balances/src/tests.rs, frame/contracts/src/tests.rs, frame/evm/src/lib.rs, frame/example/src/lib.rs, frame/recovery/src/lib.rs, frame/scheduler/src/lib.rs, frame/sudo/src/lib.rs, frame/support/src/dispatch.rs, frame/support/src/weights.rs, frame/system/src/lib.rs, frame/transaction-payment/src/lib.rs, frame/utility/src/lib.rs
small follow up for https://github.com/paritytech/substrate/pull/5686
- `enum Pays` to be more clear with payment.
- expose maximum block weight and length as const so that UI can show them.
=> enum Pays for PaysFee

client/consensus/aura/src/lib.rs, client/consensus/babe/src/lib.rs, client/consensus/slots/src/lib.rs
In both Aura and BABE we have a mechanism for allowing more time for block production in case slots were skipped (presumably due to a heavy extrinsic). There were two bugs in this code:
- The final calculation of lenience time was done in seconds using millseconds as input, as a result we'd end up backing off for hours rather than seconds/minutes.
- In the exponential backoff we'd always apply one step of backoff even if no slots were skipped.
Moved this code into the `slots` crate and added tests.
=> slots: fix slot lenience methods

Cargo.lock, client/cli/src/params/network_params.rs, client/network/Cargo.toml, client/network/src/config.rs, client/network/src/discovery.rs, client/network/src/service.rs, client/network/test/src/lib.rs, client/service/test/src/lib.rs
Currently every address reported via libp2p-identify is inserted into the DHT which thus contains a multitude of unreachable addresses such as from 127.0.0.0/8 or 10.0.0.0/8.
Issue #5099 suggested a dedicated service over UDP to gauge the reachability of an address, which would however incur extra I/O costs and be of limited use.
As an alternative and simpler tactic, this PR only allows global IP addresses to be inserted into the DHT unless an explicit command-line flag `--allow-non-global-addresses-in-dht` is given or a node is started with `--dev`. This opt-in behaviour is meant to allow site-local networks to still make use of a DHT.
=> network: Only insert global addresses into the DHT.

Cargo.lock, client/api/Cargo.toml, client/api/src/notifications.rs, client/src/client.rs
When an rpc client connects to a node, it subscribes to a few keys to receive update when they change. Internally that is offloaded to `client.notification_stream`, which holds the actual logic to figure out if it matches and trigger an event on an `unbounded` channel if it does.
When the RPC disconnects all these subscriptions are discarded, the Receivers drop, which would mean the notification stream will also drop them on the next trigger that matches them – eventually cleaning it up internally.
Well, that's the theory. But because it only checks for the dropped ones whenever they match, rarely (or effectively _never_) changing keys are not included in the check. And one of those rarely changing keys is one the Polkadot JS App is very interested in: the runtime version. Thus, whenever …
=> Fix leak in stream notifications

client/finality-grandpa/src/justification.rs
The idea is to use that function in external crates to verify justification that came from untrusted source. Like:
1) someone calls `chain_getBlock` on Substrate node to get justification;
2) he then submits that justification to the Ethereum contract;
3) Ethereum contract needs a proof that justification is valid and finalizes block it needs.
We might also extract `GrandpaJustification` to separate crate, if you think it worth it (I would prefer not to do that **now**, though). Or probably expose some `fn verify_justification(Vec<u8>, ...) -> Result<(), Error>` instead of `GrandpaJustification::decode_and_verify_finalizes()` - we actually do not need `GrandpaJustification` itself, because it's opaque to external crates anyway.
=> Make GrandpaJustification::decode_and_verify_finalizes public

Cargo.lock, client/executor/src/integration_tests/mod.rs, client/executor/src/lib.rs, client/executor/src/native_executor.rs, frame/support/test/Cargo.toml, frame/support/test/tests/construct_runtime_ui.rs, frame/support/test/tests/reserved_keyword.rs, frame/system/src/lib.rs, primitives/core/src/traits.rs, primitives/io/src/lib.rs, primitives/runtime-interface/test/Cargo.toml, primitives/runtime-interface/test/src/lib.rs, primitives/state-machine/src/lib.rs
When upgrading a runtime, we check that the version of the new runtime
is incrementing the `spec_version` or the `spec_name` changes. To do
this, we need to initialize the runtime and call `Core_version`. When
initializing the runtime we check all imports and if we can fulfill
them. Up to now, we would fail when the node did not provide all the
required host functions. In Westend this lead to older nodes rejecting
the runtime upgrade, as the runtime version could not be extracted, but
newer nodes with these host functions succeeded and generated a
different state root. This pr allows missing host functions. A missing
host function is replaced by a stub that returns an error when being
called. As `Core_version` doesn't call any host function besides
`malloc` and `free`, this should make …
=> Allow missing functions when checking the new runtime's version

frame/staking/reward-curve/src/lib.rs, frame/staking/reward-curve/src/log.rs
A set of changes to the `log2` function in the `pallet-staking-reward-curve` module.
- Add 5 regression tests to check and verify the boundaries of the log2 function
- Readability changes:
- Pulled `taylor_term` closure out of the `log2` function
- Add a `pow2!` macro
- Add doc comments to clarify code intent
- This PR does not change log2 behaviour
=> Regression testing and readability additions for reward curve log2

primitives/core/src/crypto.rs
Add Rustdocs about identifiers for crypto keys, e.g. `aura`, `gran`, etc.
=> Document crypto key identifiers

docs/PULL_REQUEST_TEMPLATE.md
This entry in the PR template
> - [ ] Your PR adheres [the style guide](https://github.com/paritytech/polkadot/wiki/Style-Guide)
points to a moved page. This PR updates it to the new target https://wiki.parity.io/Substrate-Style-Guide
=> update Substrate style guide link in PR template

client/network/src/service.rs
I was using docker-compose files with old peer-id and got the following errors:
```
dave            | 2020-04-21 13:44:43 💔 Invalid peer ID from bootnode, expected `QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN` at address `/ip4/172.28.1.1/tcp/30333`.
bob             | 2020-04-21 13:44:43 💔 Invalid peer ID from bootnode, expected `QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN` at address `/ip4/172.28.1.1/tcp/30333`.
eve             | 2020-04-21 13:44:43 💔 Invalid peer ID from bootnode, expected `QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN` at address `/ip4/172.28.1.1/tcp/30333`.
dave            | 2020-04-21 13:44:43 💔 Invalid peer ID from bootnode, expected `QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN` at address `/ip4/172.28.1.1/tcp/30333`.
charlie         | 2020-04-21 13:44:43 💔 …
```
=> Fix error message when providing an incorrect peer-id

Cargo.lock, bin/node/cli/src/chain_spec.rs, bin/node/cli/src/factory_impl.rs, bin/node/cli/src/service.rs, bin/node/executor/tests/basic.rs, bin/node/runtime/src/lib.rs, bin/node/testing/src/genesis.rs, bin/node/testing/src/keyring.rs, bin/utils/subkey/src/main.rs, frame/contracts/Cargo.toml, frame/contracts/rpc/src/lib.rs, frame/contracts/src/exec.rs, frame/contracts/src/gas.rs, frame/contracts/src/lib.rs, frame/contracts/src/tests.rs, frame/contracts/src/wasm/code_cache.rs, frame/contracts/src/wasm/mod.rs, frame/contracts/src/wasm/runtime.rs, frame/support/src/lib.rs, frame/transaction-payment/src/lib.rs
#4147 This was a previous attempt which didn't had a working weight refund to build upon.
#5446 Ground work that rescaled the weights o a higher resolution so they can be used as gas without additional scaling
#5458 Allows our dispatchables to return the actual weight used in order to refund unspent gas.
This greatly simplifies the gas system in pallet_contracts by integrating it with Substrate's weight system. Additionally it makes contract execution contribute to the weight of a block which is not the case right now. It also fixes the problem of `ext_dispatch_call` calls not being billed based on their actual weight.
It effectively unifies gas and weight: `1 weight = 1 gas = 1 ps`. ps is one pico second of execution on our reference system. However, in order to reduce to code churn of …
=> Integrate pallet_contracts gas with the weight system

bin/node-template/runtime/src/lib.rs, bin/node/executor/tests/basic.rs, bin/node/executor/tests/fees.rs, bin/node/executor/tests/submit_transaction.rs, bin/node/runtime/src/lib.rs, frame/balances/src/tests_composite.rs, frame/balances/src/tests_local.rs, frame/executive/src/lib.rs, frame/transaction-payment/src/lib.rs
This is a pretty simple PR which replaces the notion of `TransactionBaseFee` with `ExtrinsicBaseWeight` * `WeightToFee`.
We should confirm that Transaction Byte length should still be handled independent of the Substrate weight system, as it is now.
=> Replace `TransactionBaseFee` with `ExtrinsicBaseWeight`

frame/staking/src/lib.rs
=> Make sure staking migration code runs only for `version = 2_0_0`

primitives/state-machine/src/ext.rs, primitives/state-machine/src/lib.rs
- `-trace` suffix is redundant
- all methods are called "storage"
=> Rename `state-trace` traces to `storage`

client/service/Cargo.toml, client/service/src/metrics.rs
cc https://github.com/paritytech/polkadot/issues/1027
As a general remark, I'm really not a fan of having platform-specific code, as it tends to derail over time into a clusterfuck of unmaintainable cfg guards. To me, metrics such as the CPU usage, threads, number of TCP connections, etc. should be reported by another process running on the side of the node.
Anyway. The point of this PR is to remove the dependency on `netstat2` for Android, since it fails to compile.
The metrics about the network statistics are already reported in cross-platform way by the `sc_network` crate, so someone who would like to monitor an Android node won't lose any information.
I've also slightly refactored the `cfg(target_os = "unknown")` guards, because assuming that `not(any(unix, windows))` is the same as …
=> Fix the cfg guards in service/metrics.rs

.maintain/github/check_gitlab_pipeline.sh
Current timeout for monitoring the tagged release pipeline is 130 minutes. Successful builds of this pipeline can sometimes take longer than that. Increase timeout to 3h.
ref https://github.com/paritytech/substrate/issues/5638
=> [ci] Increase check-gitlab-pipeline timeout

frame/session/src/lib.rs
~~updating formula for on_initialize requires new benchmarks, and maybe new API (or every cost of SessionHandler and ShouldEndSession will have to be documented)~~
EDIT: as suggested by shawn new_session take full block to make it easier, if in the future it is wanted we can improve on this.
=> Update weight formula for session (with new_session taking full block)

client/authority-discovery/src/lib.rs
Instead of logging value-found-event-handling failures or value-put
failures on error level, log them on debug level only additionally
recording them via Prometheus.
Motivation is that both events can happen in "normal" operations and
thus clutter the logs.
Fixes https://github.com/paritytech/substrate/issues/5719
=> client/authority-discovery: Reduce log level replaced by metrics

client/consensus/babe/src/authorship.rs
When doing the primary threshold calculation in BABE we default to returning `u128::max_value()` in case any error happens in intermediary computations. The computations should not fail and instead "proofs" are given in expects.
Fixes #5753.
=> babe: remove error fallback from threshold calculation

client/consensus/pow/src/lib.rs
This PR adds two parameters to `sc_consensus_pow::import_queue` to support justification import and finality proof import. The function does no custom processing on the two additional parameters, but passes them through to the underlying `BasicQueue`.
This is useful for hybrid consensus systems that use PoW for authoring, but still want deterministic finality.
A working example of using this feature is WIP at https://github.com/substrate-developer-hub/recipes/pull/227
=> Support Justification and FinalityProof import in pow import queue.

frame/support/src/dispatch.rs
Seems that currently dynamic weight might be computed multiple times. The PR materializes `weight` expression to a single variable and then just passes a reference to avoid that.
=> Compute weight only once.

bin/node/runtime/src/lib.rs, frame/identity/src/lib.rs
Found they where missing while investing why my set_identity call failed.
=> expose constants for identity pallet

frame/executive/src/lib.rs
This adds support for registering custom runtime upgrade logic that can
be implemented in the runtime directly instead of putting it into a module.
=> Add support for custom runtime upgrade logic

bin/node/runtime/src/lib.rs, primitives/arithmetic/src/fixed64.rs
both saturating_mul and saturating_pow were completely broken.
=> fix Fixed64

client/network/src/behaviour.rs, client/network/src/protocol/block_requests.rs
It's been reported in #5760 that timeouts aren't working properly, which indeed seems the case.
There's indeed a problematic situation caused by the fact that we handle timeouts by disconnecting: even if a request times out, we will only kill that specific connection, but a different connection with the same peer might have been opened in the meanwhile (which would also be a logic explanation for the timeout happening). When that happens, we don't actually report a disconnect to the sync/protocol state machine (hacks on top of hacks).
This PR changes that mechanism by explicitly emitting an event when a request times out, and also an event when a request has been cancelled.
I've had planned to do this exact change anyway in order to add proper metrics to block requests. This will be done …
=> Extra timeout handling in block_requests

Cargo.lock, client/db/Cargo.toml, client/db/src/lib.rs, client/db/src/parity_db.rs, client/db/src/utils.rs, client/state-db/src/lib.rs, client/state-db/src/noncanonical.rs, client/state-db/src/pruning.rs, primitives/state-machine/src/trie_backend.rs, primitives/state-machine/src/trie_backend_essence.rs, primitives/trie/src/lib.rs
This PR introduces optional support for state DB backends that have internal reference counting, such as ParityDb. This allows for some optimizations on the client backend side:
1. Trie node prefixing is not required.
2. Pruning overlay is not required to track references, reducing memory overhead.
=> Support reference-counting state backend.

client/service/src/builder.rs
This is a small change that will allow changing the default block announcer when building a service.
This PR is relevant for the issue: https://github.com/paritytech/cumulus/issues/7 as we need to set a custom default block announcer.
=> Add method with_default_block_announcer to ServiceBuilder

Cargo.lock, frame/system/src/lib.rs, primitives/externalities/Cargo.toml, primitives/externalities/src/lib.rs, primitives/io/src/lib.rs, primitives/state-machine/src/basic.rs, primitives/state-machine/src/ext.rs, primitives/state-machine/src/overlayed_changes.rs
polkadot companion: https://github.com/paritytech/polkadot/pull/1041
Either this or https://github.com/paritytech/substrate/pull/5740 (choosing one variant currently) is release critical @gnunicorn
=> Add append api and use it to deposit events

client/cli/src/commands/mod.rs, client/cli/src/config.rs
This got broken in one of the recent CLI refactors and the `--unsafe-pruning` flag would be ignored.
=> cli: fix unused unsafe-pruning flag

bin/node/runtime/Cargo.toml
Delete duplicates runtime-benchmarks.
`"pallet-collective/runtime-benchmarks"` is duplicates in runtime-benchmarks.
=> delete duplicates runtime-benchmarks

client/consensus/babe/src/lib.rs, primitives/consensus/babe/src/digests.rs
This changes `NextConfigDescriptor` to be by default versioned, making writing migration scripts like for #5788 easier.
=> Versioned NextConfigDescriptor for BABE

Cargo.lock, primitives/core/src/testing.rs, primitives/phragmen/Cargo.toml, primitives/phragmen/compact/src/assignment.rs, primitives/phragmen/compact/src/lib.rs, primitives/phragmen/src/helpers.rs, primitives/phragmen/src/lib.rs, primitives/phragmen/src/mock.rs, primitives/phragmen/src/node.rs, primitives/phragmen/src/reduce.rs, primitives/phragmen/src/tests.rs
=> Remove sp-runtime dependency from sp-phragmen

frame/vesting/src/lib.rs
This is a PR that updates the weights for the vesting pallet based on benchmarking data collected.
=> Update Weights for Vesting Pallet

bin/node/runtime/src/lib.rs, frame/support/src/inherent.rs, primitives/inherents/src/lib.rs
This adds an additional function `is_inherent_required` to `ProvideInherent` trait. If a module implement this, it indicates that based on its interpretation of `InherentData`, an inherent of this module call type must be present in the current block.
This is particularly useful for pallets like `anyupgrade` for deliberate runtime hard forks. In those cases, the `InherentData` checks for block numbers, and if the block number is the current block, it requires an inherent to be present so that the hard fork code can be enacted.
=> Add support for modules to require inherent to be present

client/service/src/builder.rs
This PR removes the field `background_tasks` in the ServiceBuilder.
Instead of adding those tasks to a Vector and then spawning the tasks that are in the vector, we now directly spawn those tasks without adding them to the vector.
The field we're removing in this PR is the vector that is now useless.
=> Remove background_tasks field in ServiceBuilder

frame/system/Cargo.toml
`cd frame/democracy/src && cargo test --features runtime-benchmarks` wasn't working
=> add missing features for runtime-benchmarks

primitives/state-machine/src/basic.rs, primitives/state-machine/src/ext.rs, primitives/state-machine/src/lib.rs, primitives/state-machine/src/overlayed_changes.rs
This PR changes the recent host append function to avoid removing content from committed layer (take on value_mut).
This is therefore consensus breaking from the previous implementation, but seems unavoidable to me (otherwhise fail extrinsic will clear previously committed data).
It also remove a copy and map access by appending on mutable pointer.
This lack testing but it seems rather important to me to have eyes on it sooner.
Note, that a safer implementation could just be to replace previous value_mut function by a 'storage' call and use memory copy to start.
=> Avoid changing overlay committed layer.

Cargo.lock, Cargo.toml, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs, frame/benchmarking/src/analysis.rs, frame/session/benchmarking/src/mock.rs, frame/system/benchmarking/Cargo.toml, frame/system/benchmarking/src/lib.rs, frame/system/benchmarking/src/mock.rs, frame/system/src/lib.rs
This PR adds a crate that benchmarks the various extrinsics in `frame_system`.
=> Frame System Benchmarking

client/finality-grandpa/src/voting_rule.rs
Corrects the docs for `sc_finality_grandpa::voting_rule::BeforeBestBlockBy`. The docs previously stated that the voting would lag behind the best block by exactly 1 block, but in reality the voting rule is parametric in the number of blocks to lag by.
=> Update docs for BeforeBestBlockBy

Cargo.lock, client/finality-grandpa/Cargo.toml, client/finality-grandpa/src/authorities.rs, client/finality-grandpa/src/aux_schema.rs, client/finality-grandpa/src/communication/gossip.rs, client/finality-grandpa/src/communication/mod.rs, client/finality-grandpa/src/communication/tests.rs, client/finality-grandpa/src/environment.rs, client/finality-grandpa/src/finality_proof.rs, client/finality-grandpa/src/lib.rs, client/finality-grandpa/src/observer.rs, client/finality-grandpa/src/tests.rs, client/finality-grandpa/src/until_imported.rs
Updates to (unreleased) finality-grandpa v0.12.0. The crate now guarantees some invariants regarding the authority set, namely that it is non-empty and that all weights are non-zero. I have updated the `AuthoritySet` to make sure that we also make these validations and that it is correct by construction, therefore these invariants are guaranteed when we need to convert from `Vec<(AuthorityId, u64)>` into `VoterSet`.
I could have updated the runtime module to also guarantee these invariants (`NonEmptyVec<(AuthorityId, NonZeroU64)>`), but this would probably require some further changes to guarantee backwards compatibility. Instead, the client validates the authority set changes emitted by the runtime and refuses anything that is malformed (e.g. if the runtime sets the authorities to an …
=> grandpa: update to finality-grandpa v0.12.0

bin/node-template/node/Cargo.toml
We need to keep the features enabled to have rocksdb enabled as db
backend.
Fixes: https://github.com/paritytech/substrate/issues/5858
=> Don't disable default-features of sc-service in node-template

bin/node-template/runtime/src/lib.rs, bin/node/executor/tests/basic.rs, bin/node/executor/tests/submit_transaction.rs, bin/node/runtime/src/lib.rs, frame/balances/src/lib.rs, frame/utility/src/lib.rs, frame/vesting/src/lib.rs
We are using a faster machine than before to re-calculate our weights, which results in a drop in weight values of around 2x - 3x.
This PR updates weights for:
* DbWeight
* Utility Pallet
* Vesting Pallet
* Balances Pallet
Current machine specifications:
<details>
<summary><code>lscpu - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (expand)</code></summary>
```
shawntabrizi@bm2:~$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1 …
```
=> New weights using i7 machine

primitives/state-machine/src/lib.rs
To be on the safe side with runtime upgrade, another test that reflects real state machine use case
when building block
1. initialize block (this kills storage and does `append` to it) 
2. push panicking (or too heavy) extrinsic (this does `append` that then rollbacks)
3. push ok extrinsic (this does `append` that then commits)
see that overlay is in correct state after
=> Another state machine test

primitives/api/proc-macro/src/impl_runtime_apis.rs, primitives/runtime/src/traits.rs
Fixes: https://github.com/paritytech/substrate/issues/5873
=> Fix clippy warnings in generated runtime api code

bin/node-template/runtime/src/lib.rs, bin/node/bench/src/import.rs, bin/node/bench/src/main.rs, bin/node/executor/tests/submit_transaction.rs, bin/node/runtime/src/lib.rs, bin/node/testing/src/bench.rs
This PR introduces a no-op variant of the block import benchmark.
This also introduces a `SizeType::Custom` variant which allows the user to input a custom number of transactions to try and place into a block through a `--transactions` input parameter.
Results using this branch on our i7 machine:
```
cargo run --release -p node-bench -- ::node::import::wasm::sr25519::noop::custom --transactions 10000
```
```
2020-05-01 20:37:37 imported block with 10001 tx, took: 1.241417064s
2020-05-01 20:37:37 usage info: caches: (3.67 MiB state, 0 bytes db overlay), state db: (168 bytes non-canonical, 0 bytes pruning, 44 bytes pinned), i/o: (0 tx, 0 write, 0 read, 0 avg tx, 40001/50033 key cache reads/total, 18897 trie nodes writes)
2020-05-01 20:37:37 Import benchmark (Noop(10000), Wasm): avg 1.26 s, …
```
=> `node-bench` no-op block import

client/service/src/task_manager.rs
Adds a second parameter named `kind` to the `tasks_ended_total` metric.
Its value is `normal`, `panic` or `interrupted` depending on how the task has ended.
The idea behind this PR is to be able to detect when a task panics.
This could be used in a Prometheus alerts or more generally to detect if weird behaviours are caused by panics.
=> Report tasks panics in metrics

client/db/src/lib.rs, client/service/src/client/client.rs, client/service/src/client/mod.rs, primitives/blockchain/src/header_metadata.rs
Currently each runtime call makes a header query to the database for the state root. This PR adds `state_root` to the header metadata cache so that it can be used for creating state objects.
Also fixed warnings in `client/service/client`
=> Use header cache when creating state.

bin/node-template/runtime/src/lib.rs, bin/node/executor/tests/basic.rs, bin/node/executor/tests/fees.rs, bin/node/executor/tests/submit_transaction.rs, bin/node/runtime/src/lib.rs, frame/balances/src/lib.rs, frame/support/src/weights.rs, frame/utility/src/lib.rs, frame/vesting/src/lib.rs
This PR moves some of the FRAME specific weight constants (DbWeight, ExtrinsicBaseWeight, BlockExecutionWeight) to the `frame-support` library. Since we already make heavy assumptions about how to derive these weights based on our specific setup of FRAME, it makes sense to move these thing into there.
Additionally, this updates some weight values across various extrinsic to make them even a bit more lightweight!
We found that we had double counted the overhead implied by a Heavy DB by testing our DB Trie stats with a full DB and also testing our runtime with a full chain spec. The full chain spec in the runtime was not needed since we assume now every DB read will be ~200K item (5 trie look ups) heavy.
As a result, we get some lower weights!
This updates:
* Balances
* Vesting
* Utility …
=> Refactor weight constants, Update to remove redundant overhead

frame/staking/src/lib.rs, frame/staking/src/mock.rs, frame/staking/src/offchain_election.rs, frame/staking/src/tests.rs, primitives/phragmen/src/lib.rs
Correct is that: we run seq-phragmen -> equalise -> reduce. 
Before it was mistakingly running reduce first. I am not sure what happens if you equalise a reduce-ed solution, will probably have no major effect or reverse the effects of reduce to an extent.
=> Fix Reduce Equalise order in offhchain phragmen

Cargo.lock, client/network/Cargo.toml
=> Remove BABE dependency in network

primitives/runtime/src/traits.rs
This is a minor fix to a doc comment. You can see the old version rendering incorrectly at https://crates.parity.io/sp_runtime/traits/trait.SignedExtension.html#method.identifier
=> Remove extra backtick in comments

.gitlab-ci.yml, frame/staking/Cargo.toml, frame/staking/fuzzer/src/submit_solution.rs, frame/staking/src/testing_utils.rs
Why do we have the staking test with `std` in the first place?
=> Fix staking fuzzer + make it check in ci.

.gitlab-ci.yml, client/finality-grandpa/rpc/Cargo.toml
[Releasing is broken again, because of missing metadata in a cargo.toml](https://gitlab.parity.io/parity/substrate/-/jobs/493356#L1863).
This fixes that.
Enabled `cargo unleash check` on the PR to check it works, will be reverted before merge.
=> Add repository metadata to grandpa-rpc-crate

client/finality-grandpa/src/finality_proof.rs, client/finality-grandpa/src/light_import.rs
It turned out that only in-memory storage has been updated => after restart we have always had initial set in the aux storage :/
=> Update GRANDPA authorities set in light storage when GRANDPA set changes

client/service/src/builder.rs
The name of this task is totally wrong. Its role is to propagate extrinsics and send a message to the telemetry.
It has nothing to do with blocks.
=> Fix wrong task name

primitives/arithmetic/src/traits.rs
One of the test of #5877 was failing because of this.
I guess it should work for negatives according to the docs. Other option may be to add a new `SignedSaturating` trait.
=> Fix saturating_mul for negatives

client/finality-grandpa/src/light_import.rs, frame/support/src/storage/mod.rs, frame/system/src/lib.rs, primitives/runtime/src/generic/digest.rs
This adds support for `StorageAppend` to `Digest`. Digest is just a
wrapper around a `Vec` and we abuse the fact that SCALE does not puts
any special marker into the encoding for structs. So, we can just append
to the encoded Digest. A test is added that ensures, if the `Digest`
format ever changes, we remove this optimization.
=> Make `Digest` support `StorageAppend`

primitives/state-machine/src/ext.rs
This is a really insubstantial PR that will make state-trace logs follow the same space-separated-value format so they can be easily parsed.
Basically the format is always:
```
ID: OPERATION KEY=MAYBE_VALUE
```
This small change fixes that, and anyone else who parses the state logs will thank us for this change.
=> Unify format of state-trace logs

client/db/src/cache/mod.rs, client/db/src/changes_tries_storage.rs, client/db/src/lib.rs, client/db/src/light.rs, primitives/blockchain/src/header_metadata.rs
This removes another DB query on each block import.
=> Use header cache for blockchain cache

Cargo.lock, utils/wasm-builder-runner/Cargo.toml, utils/wasm-builder/Cargo.toml
Fixes: https://github.com/paritytech/substrate/issues/5933
We are already using these versions since quite some time and I just had forgotten to release them.
=> Relase `wasm-builder` and `wasm-builder-runner`

client/network/src/behaviour.rs
Here is an example problematic situation:
- We have two active TCP connections to the same peer.
- The sync code starts a request. We pick one of the TCP connections and send it on it.
- That TCP connection closes. This makes the `blocks_request` code emit a `RequestCancelled` event. Because we still have the other TCP connections, the sync code doesn't get notified of the disconnect and still thinks that the request is in progress.
In my mind, a `RequestCancelled` event could only happen in case of a complete disconnect, which would also have notified the sync code, and I didn't take into account the situation where we have multiple connections.
This PR fixes that by treating a `RequestCancelled` the same way as a `RequestTimeout` and closing all the connections.
This is a hotfix, and a …
=> Disconnect node after sync request cancelled

client/cli/src/runner.rs
Fixes: https://github.com/paritytech/substrate/issues/5936
=> Make sure `config_mut` returns a mutable reference

Cargo.lock, client/executor/src/integration_tests/mod.rs, client/executor/wasmtime/Cargo.toml, client/executor/wasmtime/src/host.rs, client/executor/wasmtime/src/imports.rs, client/executor/wasmtime/src/instance_wrapper.rs, client/executor/wasmtime/src/instance_wrapper/globals_snapshot.rs, client/executor/wasmtime/src/runtime.rs
Brings back #5822 which should be safe to use now. 
`paritytech/wasmtime` is now up to date with upstream and the race in signatures registration is protected with a lock.
=> Bump wasmtime again

frame/system/src/lib.rs
This is useful to external users, using this info they can determine the maximum number of allowed blocks when constructing mortal eras. Currently this is either hardcoded or not checked at all in APIs, in either case this could mean that an invalid period is chosen for the mortal era.
=> Expose BlockHashCount on system metadata constants

bin/node/executor/tests/basic.rs, frame/identity/src/lib.rs, frame/timestamp/src/lib.rs
Make some weight adjustments to `pallet-identity` and `pallet-timestamp` based on recent benchmarking.
=> weight adjustments for identity and timestamp pallets

frame/staking/src/mock.rs, frame/staking/src/tests.rs
closes #5838
--- 
while doing this, I once more saw how confusing and bad some tests have become. Mostly because some tests are not well isolated, so numerous PRs from numerous people changed one tests case, and this naturally leads to a bad test. For example this one that I fixed here was first written by me and Shawn waaaaay back last year, then there are signs of it being changed with the reward PR and then the slashing PR, all in the same unit test. Some assertions (about rewards for example) made no sense anymore. 
I already have a few issues open about staking tests, but even without that, I will start an endeavour soon to read all of them A to the very damn Z and make sure they make sense.
=> Fix very wrong staking test

client/consensus/babe/rpc/src/lib.rs, client/consensus/babe/src/authorship.rs, client/consensus/babe/src/aux_schema.rs, client/consensus/babe/src/lib.rs
Expose a new function `claim_slot_using_keypairs` in Babe so that the `babe_epochAuthorship` RPC call can lookup authorship for all slots in the epoch without repeatedly looking up keys in the keystore.
Keep the old `claim_slot` but the behaviour is changed slightly in that there is only a single lookup for both claiming primary and secondary slot.
Time to run the `babe_epochAuthorship` RPC call goes from 7s to 25ms on a local dev chain on my
machine.
Resolves #5948
=> Don't repeatedly lookup keys in `babe_epochAuthorship` rpc function

.gitlab-ci.yml
Fixes a [bug](https://gitlab.parity.io/parity/substrate/-/jobs/502111#L84) in releasing the docker images.
=> hotfix Docker release

client/network/src/block_requests.rs
Report events immediately instead of en-queueing them and returning `Poll::Pending`.
This is only relevant to reporting to Prometheus how much time we took to answer requests, so it's not related to the current sync stalling issue.
=> Small fix to block response completion reporting

frame/example-offchain-worker/src/lib.rs, frame/system/src/offchain.rs
Signed-off-by: Jimmy Chu <jimmychu0807@gmail.com>
- In particular, mind the maximal line length.
Thank you!
- updated AppCrypto comment to the latest 
- Move package inclusion on top
=> Minor update on example-offchain-worker code and comment

frame/support/test/tests/reserved_keyword/on_initialize.stderr, primitives/api/test/tests/ui/empty_impl_runtime_apis_call.stderr, primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr, primitives/api/test/tests/ui/mock_only_one_error_type.stderr, primitives/api/test/tests/ui/mock_only_self_reference.stderr, primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr, primitives/runtime-interface/test/src/lib.rs, primitives/runtime-interface/tests/ui/pass_by_enum_with_struct.stderr, primitives/runtime-interface/tests/ui/pass_by_enum_with_value_variant.stderr, primitives/runtime-interface/tests/ui/pass_by_inner_with_two_fields.stderr
Should be merged after we have updated to rust `1.43.1`.
CC @TriplEight
=> Update initialize tests for latest rust stable

client/cli/src/commands/mod.rs, client/cli/src/config.rs, client/cli/src/params/shared_params.rs
Quality-of-life change. You can now do `./polkadot --log foo=debug --log bar=trace`.
The code will automatically put a `,` between the multiple values.
=> Allow passing multiple --log CLI options

frame/elections-phragmen/src/lib.rs, frame/staking/src/lib.rs, frame/support/src/storage/generator/double_map.rs, frame/support/src/storage/generator/map.rs, frame/support/src/storage/generator/value.rs, frame/support/src/storage/mod.rs, frame/support/test/tests/decl_storage.rs
Instead of reading the full storage value into the runtime, we only read
at maximum `5bytes` from the storage into the runtime. Furthermore this
drops any handling with regards to set default values in
`decl_storage!`. If the value does not exists or the decoding of the
length fails, it will return `None`. To prevent people from messing
stuff up, this feature relies on the `StorageDecodeLength` trait that is
sealed by `frame-support` (aka only implementable inside this crate).
=> Optimize `decode_len`

bin/node/runtime/src/impls.rs, frame/executive/src/lib.rs, frame/system/src/lib.rs
Closes https://github.com/paritytech/substrate/issues/5758
This PR splits operational and normal weight to be tracked separately.
This means that order of inclusion will not matter for operational and transactional weights. (see the tagged issue).
On top of this, we change the logic around when an operational transaction will be included in a block.
In the case where a block is completely full with non-operational transactions (either normal transaction, mandatory inherents, or on_initialize/on_finalize), we still allow an amount of operational transactions that would normally comprise a full block (1 - available block ratio).
This is to avoid any situations where users may be locked out of the chain due to full blocks.
=> Split Operational and Normal weight

client/finality-grandpa/src/until_imported.rs
An `UntilImported` stream wraps a `Stream` of incoming messages and
waits for blocks, that those messages are based on, before passing the messages
on.
The above `Stream` of incoming messages implements `Unpin`, thus there
is no need to use `pin_project` on the `UntilImported` struct. Instead
one only has to add the `Unpin` trait bound on the `I` trait parameter.
=> client/finality-granpda/until_imported: Rework pinning

Cargo.lock, client/finality-grandpa/Cargo.toml, client/finality-grandpa/rpc/Cargo.toml, frame/grandpa/Cargo.toml, primitives/finality-grandpa/Cargo.toml
Fixes an issue with background rounds leaking (https://github.com/paritytech/finality-grandpa/pull/122).
=> grandpa: update to finality-grandpa v0.12.3

bin/node/primitives/src/lib.rs, frame/grandpa/src/equivocation.rs, frame/grandpa/src/lib.rs, primitives/core/src/crypto.rs, primitives/finality-grandpa/src/lib.rs, primitives/session/src/lib.rs
Addresses the comments raised by @bkchr on https://github.com/paritytech/substrate/pull/3868.
polkadot companion: https://github.com/paritytech/polkadot/pull/1089
=> grandpa: missing equivocation reporting nits

Cargo.lock, bin/node/browser-testing/Cargo.toml
This should fix the test on CI.
=> Update and pin the node-browser-testing wasm-bindgen version

client/transaction-pool/graph/src/listener.rs, client/transaction-pool/graph/src/validated_pool.rs
closes #5973 
@seunlanlege I'm not sure if I've missed something. I assume that for every 'listened' transaction that has been included into some block, we have entry in `finality_watchers` under that block hash key, right? So we actually do not need to have hashes of all block transactions to notify these listeners. At least that's how `retracted` works. So I simply changed the code to notify only registered listeners. Please check if I'm not missing anything.
=> Do not fetch every block body from transaction pool

client/network/src/behaviour.rs, client/network/src/protocol.rs
The reputation penalty for timing out a block request was accidentally removed. This restores it.
This should hopefully prevent the PSM from connecting again to the same node we just had a timeout with.
=> Restore the reputation penalty for timeouts

client/network/src/discovery.rs, client/network/src/lib.rs
Substrate was previously running both a chain specific Kademlia DHT as
well as the `/ipfs/kad/1.0.0` Kademlia DHT for backwards compatibility.
(See 710722f for details.)
With the end of the transition period this commit removes the former
only leaving the latter and thus preventing the discovery of
incompatible nodes via Kademlia.
*Commit description should be a valid release note entry.*
=> client/network: Remove default Kademlia DHT in favor of per protocol DHT

client/network/src/protocol/generic_proto/behaviour.rs
This error is frequently triggered on our production nodes.
I've reviewed the code to make sure, and it's a totally normal situation that happens if we get an incoming connection but dropped it before the PSM refused it.
=> Turn an error! into a debug!

frame/im-online/src/lib.rs
I'm quite sure there's a misleading typo in `SomeOffline` event documentation.
It was stated as:
_At the end of the session, at least **once** validator was found to be offline._
It should be:
_At the end of the session, at least **one** validator was found to be offline._
I also fixed another minor typo `iff -> if`
That description was a bit confusing to me because I wanted to understand if there's a way to find out if a validator was online when a specific block was created. 
So I checked [when this event is published](https://github.com/paritytech/substrate/blob/9b23e35e677608bcab5972052e7ebb14b0cae097/frame/im-online/src/lib.rs#L660) and I understood that a this event is being sent if a validator did not create a block and did not send a heartbeat (which is sent once per session, …
=> Fix minor typos in im-online documentation

Cargo.lock, bin/node-template/runtime/src/lib.rs, bin/node/executor/tests/submit_transaction.rs, bin/node/runtime/src/lib.rs, test-utils/runtime/src/lib.rs
Makes [this change](https://github.com/paritytech/polkadot/pull/1086) in the Substrate Node and Node Template.
Not sure if `test-utils` is necessary.
=> Change BlockHashCount Parameter in Node/Node Template

.maintain/gitlab/check_line_width.sh
The gitlab line width check test is broken (it fails with some shell error). Nobody noticed because the script returns success.
The problem here was that it was checking the changes against `origin/master` which was never fetched by the CI. I added the necessary fetch command and also enabled shell strict mode in order to detect such errors in the future.
Example output of the broken script:
```
$ ./.maintain/gitlab/check_line_width.sh
00:00
fatal: ambiguous argument 'origin/master...8ec43ae8cc7dd5dd53bf66ece1a63e3337c7aa45': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Job succeeded
```
=> Fix gitlab line-width CI check

client/transaction-pool/src/lib.rs, client/transaction-pool/src/metrics.rs
Adds a Prometheus metric counting transactions rejected from the pool as invalid. Fixes https://github.com/paritytech/substrate/issues/5991
=> Monitor transactions rejected from the pool as invalid

primitives/application-crypto/src/lib.rs, primitives/application-crypto/src/traits.rs
This has already been done for `RuntimeAppPublic` previously in #5965  under the assumption it can be used in client/consensus crate. However, as this comment suggests: https://github.com/paritytech/substrate/pull/6008#discussion_r424350273 `AppKey` should be the trait used in consensus and therefore, this change is required.
=> Add CRYPTO_ID to AppKey

client/network/src/protocol/generic_proto/behaviour.rs, client/network/src/protocol/generic_proto/handler/legacy.rs
Adds some mitigations to the networking in case of state inconsistency:
- Instead of printing a warning after 5 seconds of not receiving an initial message from the behaviour, we wait for 20 seconds then kill the connection entirely.
- I've noticed that peers that are ultimately in an inconsistent state trigger `"Timeout when opening protocol"` errors. Normally this is sent to the behaviour, which respends by disconnecting the peer, but since there is a state inconsistency, it doesn't happen. I've change that to immediately close the connection from inside.
Additionally, checks a few more possible error situations regarding the list of open connections.
=> Add mitigation for the state inconsistency issue

client/finality-grandpa/rpc/src/error.rs, client/finality-grandpa/src/authorities.rs, client/finality-grandpa/src/aux_schema.rs, client/finality-grandpa/src/communication/gossip.rs, client/finality-grandpa/src/communication/mod.rs, client/finality-grandpa/src/communication/periodic.rs, client/finality-grandpa/src/environment.rs, client/finality-grandpa/src/finality_proof.rs, client/finality-grandpa/src/import.rs, client/finality-grandpa/src/justification.rs, client/finality-grandpa/src/lib.rs, client/finality-grandpa/src/light_import.rs, client/finality-grandpa/src/observer.rs, client/finality-grandpa/src/until_imported.rs
Fix a bunch of low hanging clippy lints in Grandpa
=> Fix minor clippy lints in grandpa

bin/node/cli/src/command.rs, client/cli/src/lib.rs
Instead of resetting `SIGPIPE` to the system default handler, we now
handle a clap error manually and ignore any error when writing to
`stdout`/`stderr`. In this way, the node does not silently stops when it
encounters a `SIGPIPE` in normal mode and we still support piping of the
cli output.
=> Handle clap errors manually and don't reset `SIGPIPE`

primitives/application-crypto/src/ed25519.rs, primitives/application-crypto/src/lib.rs, primitives/application-crypto/src/sr25519.rs, primitives/authority-discovery/src/lib.rs, primitives/core/src/crypto.rs, primitives/core/src/ecdsa.rs, primitives/core/src/ed25519.rs, primitives/core/src/sr25519.rs
This PR does 2 things:
1. Introduce `to_public_crypto_pair` to facilitate convering `sp_core::crypto::Public` to `CryptoTypePublicPair`
2. Implement `From<sp_app_crypto::Public> for CryptoTypePublicPair` so that application-specific keys can be converted easily into the target type required for signing.
This PR is a dependency for #6008
=> Convert `Public` to `CryptoTypePublicPair`

client/network/src/protocol/generic_proto/behaviour.rs
When multiple connections to the same peer are involved, the code in `behaviour.rs` works under the assumption that all the handlers are in the same state: either enabled or disabled.
This, however, isn't the case when the remote closes the substream on one of the two connections while the second one is in an enabled+closed state. When that happens, we switch that first connection to disabled, keep the other as enabled, and switch the entire peer state to disabled.
The problem is that this other connection, still enabled, will then open (or stay open) and can communicate with the sync/grandpa/etc. codes. Meanwhile, the behaviour sees the peer as disabled. Since disabled implies "is going to close soon", the behaviour ignores all disconnect requests sent by the sync code or others.
=> Fix potential state mismatch in behaviour.rs

utils/wasm-builder/src/lib.rs, utils/wasm-builder/src/wasm_project.rs
This correctly escapes the wasm file path.
=> Fix escaping of the wasm file path

.maintain/gitlab/check_polkadot_companion_build.sh
We need to fetch the whole tree otherwise the merge with master fails since it can't find the common ancestor.
=> ci: fix merge on polkadot companion job

.gitlab-ci.yml
When the edited scripts were made, I erroneously thought the 'only:' conditionals were logical ANDs, but they're ORs. Get rid of the pointless `- tags`.
Fixes #5910  - where the updating of the rolling `release` tag erroneously triggered a check_signed_tag job, and thus caused an error.
Also edits it to capture the `ci-release` tag since this is our 'dry run' tag pattern.
=> [CI] Fix a few issues with .gitlab-ci.yml

Cargo.lock, client/rpc/Cargo.toml, client/rpc/src/author/tests.rs, client/rpc/src/chain/tests.rs, client/rpc/src/lib.rs, client/rpc/src/state/tests.rs, client/rpc/src/testing.rs
This fixes the RPC tests on machines with a high number of cores e.g. a
3900x. Without this fix the tests are almost fail with `Too many files
open`. This problem is fixed by using one executor for all tests.
=> Fix RPC tests for machines with a high number of cores

client/cli/src/lib.rs
The `yamux` crate generates errors if the connection misbehaves, while Substrate in general assumes that errors represent internal errors within our code.
=> Don't log the yamux errors by default

frame/staking/src/benchmarking.rs, frame/staking/src/lib.rs, frame/staking/src/mock.rs, frame/staking/src/slashing.rs, frame/staking/src/tests.rs
This adds slashing spans to any situation where the account could be killed, and this storage needs to be cleaned up.
TODO:
=> Add Slashing Spans to Staking Benchmarks

.maintain/gitlab/check_polkadot_companion_build.sh, .maintain/gitlab/check_polkadot_companion_status.sh, .maintain/gitlab/skip_if_draft.sh
github api requests are currently done unauthenticated for pull requests which gives an api limit of 60 per hour per ip address which is at its limit. this pr will use an unprivileged token for that.
=> ci: github api use token for pull requests

Cargo.lock, bin/node/bench/Cargo.toml, bin/node/bench/src/tempdb.rs, client/api/Cargo.toml, client/db/Cargo.toml, primitives/database/Cargo.toml, utils/browser/Cargo.toml
updates kvdb:
- kvdb: 0.5 -> 0.6
- kvdb-rocksdb: 0.7 -> 0.8
- kvdb-memorydb: 0.5 -> 0.6
- kvdb-web: 0.5 -> 0.6
this version of KVDB updates to librocksdb 6.7.3 and updates to a new kvdb interface
=> bump kvdb-* versions

client/network/src/behaviour.rs, client/network/src/block_requests.rs, client/network/src/debug_info.rs, client/network/src/discovery.rs, client/network/src/light_client_handler.rs, client/network/src/on_demand_layer.rs, client/network/src/protocol.rs, client/network/src/protocol/generic_proto/behaviour.rs, client/network/src/protocol/generic_proto/handler/group.rs, client/network/src/protocol/generic_proto/upgrade/notifications.rs, client/network/src/protocol/sync.rs, client/network/src/protocol/sync/blocks.rs, client/network/src/protocol/sync/extra_requests.rs, client/network/src/service.rs
We do a lot of spurious cloning of `PeerId`s in `sc-network`. This cleans it up a bit, plus some other clean-ups.
Doesn't change any logic.
=> Fix lots of small nits in sc-network

README.md
I didn't do a good job at making the gif, but this is just a proposal. If accepted, I can make a better one or ask Max to help with it, and of course put the gif somewhere in our repo.
=> Put some graphics in the README? 

client/keystore/src/lib.rs, primitives/application-crypto/src/ecdsa.rs, primitives/application-crypto/src/lib.rs, primitives/application-crypto/test/src/ecdsa.rs, primitives/application-crypto/test/src/lib.rs, primitives/core/src/ecdsa.rs, primitives/core/src/testing.rs, primitives/core/src/traits.rs, primitives/io/src/batch_verifier.rs, primitives/io/src/lib.rs, test-utils/runtime/src/lib.rs
`RuntimePublic` implementation of ECDSA on `application-crypto`.
https://github.com/paritytech/substrate/tree/master/primitives/application-crypto/src
`client/keystore` and `primitves/sr_io` and `primitives/core/crypto/ecdsa` was changed.
=> Added RuntimePublic for ecdsa public key.

client/network/src/protocol.rs, client/network/src/protocol/sync.rs, client/network/src/service.rs, client/network/test/src/lib.rs, client/service/src/lib.rs
Import queue notifies about all imported blocks via `on_blocks_processed`. Client also notifies about the same blocks via `on_block_imported`, although it is only sent for recent blocks. This PR removes `on_block_imported` since it is mostly redundant and handling is merged with `on_blocks_processed`
Closes #6033
polkadot companion: https://github.com/paritytech/polkadot/pull/1100
=> Remove on_block_imported

client/consensus/aura/src/lib.rs
Closes #6052 
@bkchr tested locally and this works fine.
=> Aura fix: make sure the key exists locally

client/finality-grandpa/src/communication/gossip.rs
Moved the gossip round start instant to the `LocalView` type and fixed the round duration constant.
=> grandpa: minor cleanup for gossip round start instant

README.md
The current license badge is not identifiable by github
[![GitHub license](https://img.shields.io/github/license/paritytech/substrate)](LICENSE)
```
[![GitHub license](https://img.shields.io/github/license/paritytech/substrate)](LICENSE)
```
Updates a new one contains both `GPL3` and `Apache2`
[![GitHub license](https://img.shields.io/badge/license-GPL3%2FApache2-blue)](LICENSE)
```
[![GitHub license](https://img.shields.io/badge/license-GPL3%2FApache2-blue)](LICENSE)
```
✄ ----------------------------------------------------------------------------------------
Preview the modification at [clearloop/substrate:badge][0].
[0]: https://github.com/clearloop/substrate/tree/badge
=> Updates the license badge

bin/node/runtime/src/lib.rs, frame/evm/src/lib.rs
This makes reusing them slightly easier. Useful for `pallet-ethereum` in Frontier.
=> Refactor EVM operations to module functions

frame/support/procedural/src/storage/genesis_config/builder_def.rs, frame/support/procedural/src/storage/storage_struct.rs
As some user use clippy for their code, better to have decl_storage respecting clippy.
related to https://github.com/open-web3-stack/open-runtime-module-library/pull/162/files/2be2da8363c27c520e95c7cccf7b026bcf5cfecf..5175f0ee38b4b619cf44787fa32829a4b608acb4#r426129576
=> Make decl_storage generated code respect clippy

bin/node/runtime/src/lib.rs, frame/executive/src/lib.rs, frame/support/src/weights.rs, frame/system/src/lib.rs, primitives/runtime/src/generic/checked_extrinsic.rs, primitives/runtime/src/lib.rs, primitives/runtime/src/testing.rs, primitives/runtime/src/traits.rs
closes #6022 
When the post dispatch weight correction was introduced the `ExtrinsicSuccess` and `ExtrinsicFailed` events remained unchanged in that they still included the uncorrected pre dispatch maximum weight.
This PR fixes that by replacing the weight value with the actual weight keeping the existing event layout as is.
=> Include post dispatch corrected weight in extrinsic events

Cargo.lock, bin/node/browser-testing/Cargo.toml, bin/utils/subkey/Cargo.toml, client/authority-discovery/Cargo.toml, client/cli/src/params/network_params.rs, client/network-gossip/Cargo.toml, client/network/Cargo.toml, client/network/src/discovery.rs, client/network/src/service.rs, client/network/src/transport.rs, client/network/test/Cargo.toml, client/peerset/Cargo.toml, client/telemetry/Cargo.toml, primitives/consensus/common/Cargo.toml, utils/browser/Cargo.toml
Libp2p 0.19 isn't published yet, so this is only a draft and I've temporarily replaced the crates.io dependencies with git dependencies.
- The first commit just does the upgrade without any additional change. I've had to replace `KademliaBehaviour::discoveries` with `pending_events` in order to accommodate for `put_record` now returning a result.
- The second commit makes us listen on IPv6 by default. (#5691)
- The third commit increases the number of elements in bounded channels (#6009). While the numbers chosen are mostly a random guess, I would at least try see if it results in any difference on the CPU profile of our nodes and maybe continue adjusting later.
- The fourth commit adds support for the libp2p-specs-compliant Noise transport-level protocol while maintaining the former …
=> Upgrade to libp2p v0.19 - Changes the default PeerId representation

client/finality-grandpa/src/lib.rs
This PR makes the `GrandpaBlockImport` struct public in the `sc-finality-grandpa` crate.
I believe this change is correct because:
1. It makes `GrandpaBlockImport` consistent with `PowBlockImport`, `AuraBlockImport`, etc
2. The `service.rs` files in both the `bin/node` and the node template hold a reference to an instance of `GrandpaBlockImport`
quoting @tomaka from riot:
> It's always a bug in the code to have private types in your public API. Unfortunately Rust doesn't really enforce that. If GrandpaBlockImport wasn't marked pub at all, Rust would complain for this specific reason. But if it's marked pub and not publicly-visible where it should be (like is the case here), Rust can't detect that.
=> Make GrandpaBlockImport public

client/service/src/lib.rs
Detection of unsafe exposed addresses was incorrectly detecting the opposite (i.e. if the address is loopback then it's unsafe).
=> service: fix RPC unsafe exposed address detection

frame/aura/Cargo.toml, frame/authority-discovery/Cargo.toml, frame/authorship/Cargo.toml, frame/babe/Cargo.toml, frame/balances/Cargo.toml, frame/benchmarking/Cargo.toml, frame/executive/Cargo.toml, frame/offences/benchmarking/Cargo.toml, frame/session/Cargo.toml, frame/session/benchmarking/Cargo.toml, frame/society/Cargo.toml, frame/support/test/Cargo.toml, frame/system/Cargo.toml, frame/system/benchmarking/Cargo.toml, frame/vesting/Cargo.toml
We probably have a lot more but these were the clear ones that I found while working on some benchmarks.
=> Clean a number of imports in /frame

client/network/src/behaviour.rs, client/network/src/protocol.rs
Due to the way sending a request is now async between the sync state and the new block request protocol, the latter may send responses for requests that the former considers obsolete.
This brings back request IDs and matching for valid responses in the substrate protocol to detect such cases.
Closes https://github.com/paritytech/stakingops-issues/issues/23
Also fixes `num_active_peers`
=> Detect obsolete block responses

Cargo.lock, client/executor/wasmtime/Cargo.toml
Includes minor fix for windows build.
Closes #5957
=> Bump wasmtime version

client/network/src/protocol/generic_proto/behaviour.rs, client/network/src/protocol/generic_proto/handler/legacy.rs, client/network/src/protocol/generic_proto/handler/notif_in.rs, client/network/src/protocol/generic_proto/handler/notif_out.rs
Fixes some quadratic explosion if there's a large number of events.
If I'm not mistaken, there's no `Vec<Event>` or `SmallVec<[Event; _]>` after this PR anymore.
=> Turn a SmallVec into VecDeque for performances

bin/node/runtime/src/lib.rs, frame/evm/src/lib.rs
This adds the genesis config `accounts` that allows setting the full values of pre-defined accounts with code and storage.
=> evm: allow setting pre-defined accounts in genesis

.gitignore, client/cli/src/commands/build_spec_cmd.rs, client/cli/src/commands/export_state_cmd.rs
Fixes https://github.com/paritytech/polkadot/issues/1122
=> Handle piping error for commands that output to stdout

bin/node/runtime/src/lib.rs, frame/democracy/src/lib.rs, frame/democracy/src/tests.rs, frame/democracy/src/tests/preimage.rs
related to https://github.com/paritytech/substrate/issues/6040
polkadot companion: https://github.com/paritytech/polkadot/pull/1120
> Make sure we can save a blockchain with full blocks using only operational transactions.
In order to make a runtime upgrade in case on_initialize is taking full block we need have a way to do democracy::note_preimage using operational cost.
once we have this way the operational story for runtime upgrade is:
* one council member do CouncilCollective::propose
* other council members do CouncilCollective::vote
* one council member do CouncilCollective::close, this proposed is dispatched and do:
* Democracy::propose_external
* (TechnicalCollective can fasttrack, instant, veto and other stuff)
* note_imminent_preimage with operational transaction
* then runtime …
=> Allow operational recovery path if on_initialize use fullblock.

frame/transaction-payment/rpc/runtime-api/src/lib.rs, frame/transaction-payment/src/lib.rs
Change in docs to make it clear that `query_info` only returns the partial fee based on the current fee multiplier and cannot factor in tip. Also clarify the meaning of `partial_fee` and introduce "inclusion fee" as it is clearer.
Ideally, I would change `query_info` to `query_dispatch_info` and `partial_fee` to `inclusion_fee`, but don't want to break the API without input.
=> clarify docs on query_info and partial_fee

.maintain/monitoring/alerting-rules/alerting-rules.yaml
Create a place to collaborate on Prometheus alerting rules for
Substrate starting with a basic set of rules covering:
- Resource usage
- Block production
- Block finalization
- Transaction queue
- Networking
- ... Others
*Not my work, I am only the person aggregating these.*
---
Future steps:
- More rules
- Include validation via `promtool` in CI
- Include [Prometheus rule unit testing](https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/) in CI
- ...
- (Templating for e.g. metric names)
=> .maintain/monitoring: Add an initial set of Prometheus alerting rules

primitives/core/src/hasher.rs, primitives/core/src/lib.rs, primitives/io/src/lib.rs, primitives/runtime/src/traits.rs
Added Hasher trait to Keccak hash algorithm.
You can now select `type Hashing = Keccak;`.
Please let us know if you have any problems with adding tests or making this change.
=> Add Keccak hasher

Cargo.lock, client/cli/Cargo.toml, client/cli/src/error.rs
We already have `structopt` which re-exports `clap` in `client/cli`.
btw, is there any standard `rustfmt.toml` substrate has? I modified some `.rs` files last night, and my emacs just re-formatted every one of them...it's a hard day's night. #5456
=> chore(client): remove the unnecessary clap dep

bin/node/runtime/src/lib.rs, frame/membership/src/lib.rs
We would like to call those method directly from our integration test. I don't see why those dispatchable calls needs to be private.
=> Make pallet-membership dispatchables public

client/network/src/service.rs
This method has always been designed as a work-around before https://github.com/paritytech/substrate/issues/4587. I want to make it clear in the documentation that this is the case.
=> Add a note about the deprecation of register_notifications_protocol

frame/democracy/src/lib.rs
I forgot to put The maximum number of votes for an account in democracy into metadata.
@jacogr that also might interest you if you want to provide more informationto user.
If this max votes is exceeded any subsequent vote will fail with `MaxVotesReached` until some votes are removed with remove_vote.
=> Put democracy max votes into metadata

client/api/src/in_mem.rs, client/db/src/bench.rs, client/db/src/lib.rs, client/db/src/storage_cache.rs, client/service/src/client/light/backend.rs, primitives/state-machine/src/backend.rs, primitives/state-machine/src/basic.rs, primitives/state-machine/src/ext.rs, primitives/state-machine/src/overlayed_changes.rs, primitives/state-machine/src/proving_backend.rs, primitives/state-machine/src/trie_backend.rs, primitives/trie/src/lib.rs
Instead of cloning all the keys and values of the overlay when
calculating the storage root, we pass all the values by reference. This
should probably bring some performance improvements when calculating the
storage root.
=> Don't clone values when calculating storage root

Cargo.lock, client/cli/Cargo.toml, client/cli/src/config.rs
Default data dir on windows is set to use `author` field from Cargo.toml, which contains an e-mail and therefore does not really work as a directory name.
This PR switches from `app_dirs` to `directories` crate as it allows setting empty org name for windows. Paths for linux and mac stay the same, as these do not use organization name.
=> Fix default base path on windows

Cargo.lock, bin/node/bench/Cargo.toml, bin/node/bench/src/import.rs, bin/node/bench/src/main.rs, primitives/state-machine/src/lib.rs, primitives/state-machine/src/read_only.rs
this also introduce handy externalities for state inspection, so you can do:
```rust
context.client.state_at(&BlockId::number(1)).unwrap().inspect_with(|| { ... runtime read-only code .. });
```
=> Benchmarks sanity checks 

frame/staking/src/lib.rs, frame/staking/src/offchain_election.rs, frame/staking/src/tests.rs
Currently there is no way to trace the submission of a solution in staking other than `System::ExtrinsicSuccess` and matching the weight, or if you are lucky and we are running in native, tracing the logs. The former is cumbersome and the latter is unreliable. While I am an advocate of "don't sprinkle events in your pallet", unless if someone objects I want to add this handy event to staking to show all the new submissions. Since this is a very important operation I think it will be worthwhile to have. 
An example of where this can be used: https://github.com/paritytech/substrate/issues/6106
=> Events and better log for staking.

client/service/src/chain_ops.rs
Small fix to remove usage of `sleep` in the import_blocks function.
We are now using `Delay` instead of `thread::sleep`.
Closes #6115
=> Remove sleep in import blocks

Cargo.lock, bin/node/browser-testing/Cargo.toml, bin/utils/subkey/Cargo.toml, client/authority-discovery/Cargo.toml, client/network-gossip/Cargo.toml, client/network/Cargo.toml, client/network/test/Cargo.toml, client/peerset/Cargo.toml, client/telemetry/Cargo.toml, primitives/consensus/common/Cargo.toml, primitives/phragmen/fuzzer/Cargo.lock
https://github.com/libp2p/rust-libp2p/blob/master/CHANGELOG.md#version-0191-2020-05-25
Mostly pins the version of `async-std` to 1.5 because of https://github.com/libp2p/rust-libp2p/issues/1588
=> Bump to libp2p v0.19.1

docs/CHANGELOG.md
accidentially pushed the rc1 tag-change to master already :woman_facepalming: -- I hate Mondays.
However, [let's see if it passes](https://gitlab.parity.io/parity/substrate/pipelines/93926) and if it does, here is the corresponding changelog entry.
=> Add Changelog for rc1

primitives/arithmetic/src/fixed.rs
Allows the multiplication to be negative when `N` is unsigned.
=> Fix saturating_mul_acc

client/network/src/protocol/generic_proto/behaviour.rs
At the moment, every single call to `GenericProto::poll` leads to iterating every single peer we are connected to (including the ones for which we are connected only for Kademlia-related purposes).
This PR optimizes this a bit.
The only reason why we need to iterate is to query the various `Delay`s. After this PR, we would now duplicate all these `Delay`s and push these duplicates in a `FuturesUnordered`.
Polling a `FuturesUnordered` is `O(1)` over the number of elements that it contains because it tracks which child futures have woken up and which haven't.
By design, we never remove elements from `peers_check_after`, as the `FuturesUnordered` struct doesn't allow removing elements anyway. As such, these duplicate `Delay`s will trigger even when there's nothing to do. This should be …
=> Don't iterate over peers in generic_proto::behaviour::poll

Cargo.lock, utils/wasm-builder/Cargo.toml, utils/wasm-builder/src/wasm_project.rs
There was a bug which related in required files not being tracked of
being modified. This pr fixes this bug by making sure we ignore version
requirements for path dependencies and git dependencies. This also
ensures that we only track `.rs` or `.toml` files. Another improvement
is that we only include paths which don't contain a `Cargo.toml` if this
`Cargo.toml` does not belongs to the package being processed. This
prevents that sub-crates are added to the tracked files, while not being
part of the dependencies.
=> Fixes `wasm-builder` rerun if changed logic

client/cli/src/commands/run_cmd.rs, client/cli/src/params/shared_params.rs
If we are running `--dev` chain, we should forbid the `--chain`
argument. The `--dev` chain is always special by only having one
authority etc and some other chain spec is probably not setup for this
correctly. In the end `--dev` is just a shortcut for `--validator --alice`.
=> CLI: Make `--dev` conflict with `--chain`

bin/utils/subkey/src/main.rs
Close #5778
Adds an `inspect-node-key` command to `subkey` that prints the `PeerId` from the given node key file.
=> Add subkey inspect-node-key

bin/node-template/runtime/src/lib.rs, bin/node/runtime/src/lib.rs, bin/node/testing/src/genesis.rs, frame/democracy/src/tests.rs, frame/grandpa/src/mock.rs, frame/offences/benchmarking/src/mock.rs, frame/offences/src/mock.rs, frame/scheduler/src/lib.rs, frame/support/src/lib.rs, frame/system/src/lib.rs, primitives/arithmetic/src/per_things.rs
Currently the `const` token in `parameter_types` is not doing anything. Henceforth, if `const` token exists, it will implement a `get_const()` as well that can be used in const context, such as `const_assert!`.
In `per_thing` we defined one `fn one` on the trait and one `const fn one` on the `impl` and the compiler was smart enough to know which one is which. I cannot do the same, here, hence named `get_const()`.  
Related to https://github.com/paritytech/substrate/issues/5570 but not really solving it yet. I don't think this is a good approach to sprinkle some `const_asserts` here and copy them to polkadot and hope that they maintain in sync all the time. If an inter-pallet assertion must always hold, then `construct_runtime!` should somehow enforce them. 
polkadot-companion: …
=> Make Get<T> const friendly + Clean the runtime files a bit.

frame/transaction-payment/src/lib.rs
This adds a test which confirms that an account with zero balance, triggering a transaction with `Pays::No`, will not trigger any events such as `AccountKilled`
Closes: #6159
=> Add test for Transaction Payment on zero balance account

client/network/src/config.rs
cc #6044 
`PeerId`s that start with `Qm` are now deprecated. This prints a warning so that users are aware of this.
=> Add a warning when the user passes a legacy PeerId

client/network/src/discovery.rs, client/network/src/service.rs
Right now we print something at two different places, so I removed the reporting from `discovery.rs`. These messages have nothing to do with the discovery mechanism, and were there purely because it was the most convenient place to them at the time.
This also improves the log message itself.
=> Improve the log messages printed when a listener closes

frame/vesting/src/lib.rs
=> Update locks on upgrade

frame/support/src/weights.rs, frame/transaction-payment/src/lib.rs, primitives/arithmetic/src/lib.rs, primitives/runtime/src/lib.rs
Currently, the post dispatch fee refund is calculated as
```
refund = weight_to_fee(unspent_weight)
```
This means substrate calculates the actual_fee as
```
actual_fee = pre_dispatch_fee - weight_to_fee(unspent_weight)
```
Because of limited precision of the fixed point multiplication happening in `weight_to_fee` this is different from the desired :
```
actual_fee = weight_to_fee(actual_weight)
```
This PR fixes this disparity by calculating the refund in the following way:
```
refund = pre_dispatch_fee - weight_to_fee(actual_weight)
```
This problem became apparent when trying to [calculate the fee of an extrinsic off-chain](https://github.com/paritytech/substrate-api-sidecar/pull/50#pullrequestreview-419350084) as
```
fee = weight_to_fee(actual_weight)
```
=> Make post dispatch fee consistent with a direct calculation

frame/contracts/fixtures/set_empty_storage.wat, frame/contracts/src/account_db.rs, frame/contracts/src/lib.rs, frame/contracts/src/rent.rs, frame/contracts/src/tests.rs
This PR basically fixes two things:
This a long standing annoyance that `T::StorageOffsetSize` was assigned at a contract creation time. If we were to change this parameter it would have been a nightmare since we would have to alter each storage item. With this PR, the `storage_size` reflects the actual sum of all KV pairs and `T::StorageOffsetSize` is only accounted for during computing the fees for state rent.
Apart from that
Fixes #5107
=> pallet-contracts: State rent fixes

frame/collective/src/lib.rs
Closes #6160 
Given the new rules enacted by our weight system, there are a set of dispatchable calls which are simply not allowed by our system due to weight restrictions. One simple example is a "full block call" like `set_code`, but a more unique example may be some "fibonacci" extrinsic whose weight grows based on the input of the function. In our current weight system, such a function would in some cases be un-callable because it would alone trigger too much computation.
There is currently no mechanism to allow such a call to execute if the expected origin is something other than `Root`. Only `Root` calls are allowed to go past our weight limits through the use of the Scheduler.
The Collective pallet allows users to submit proposals. When approved, these proposals will be dispatched …
=> Allow over-weight collective proposals to be closed

utils/prometheus/Cargo.toml
The Prometheus endpoint doesn't work on Polkadot 0.8.1 because it got accidentally bumped. This prevents future regressions.
=> Pin async-std to <1.6

.maintain/monitoring/grafana-dashboards/substrate-networking.json
This is an export of the "Substrate networking" dashboard that has been crafted on Parity's internal Grafana server.
I made the dashboard generic so that one only has to configure the data source and the prefix of the metrics (e.g. "polkadot").
=> Add a Substrate networking Grafana dashboard template

bin/node/testing/src/bench.rs, client/cli/src/lib.rs, client/consensus/slots/src/lib.rs, frame/session/src/lib.rs, frame/staking/src/lib.rs, primitives/runtime/src/offchain/storage_lock.rs
Closes #6206
Note that there are still many warnings appearing, but they all emanate from the `async-std-1.5.0` dependency.
=> Fix Rustdoc Build

frame/aura/src/lib.rs
Users of the node template and other devhub products occasionally ask, "How can I reward the authority who authored a block?". (e.g. [here](https://github.com/substrate-developer-hub/substrate-node-template/issues/51))
The standard answer is to look a the [`FindAuthor` trait](https://crates.parity.io/frame_support/traits/trait.FindAuthor.html) and the [Authorship pallet](https://crates.parity.io/pallet_authorship/index.html). The only problem is that Aura (and Babe) only implement `FindAuthor<u32>` which returns a validator _index_ rather than an account id that can receive a token reward. In the `bin/node` this [gap is filled](https://github.com/paritytech/substrate/blob/4c29f1ce5b2ca0fe21f24e3dffe4763ced32cab5/bin/node/runtime/src/lib.rs#L271) by requesting the session pallet to convert …
=> impl FindAuthor<T::AuthorityId> for Aura

client/network/src/lib.rs
Nothing in Substrate and Polkadot uses this type, and we also don't create it anywhere, which means it's unusable anyway. It's both unusable and unused.
=> Remove ReportHandle

frame/balances/src/lib.rs, frame/balances/src/tests.rs, frame/balances/src/tests_composite.rs, frame/balances/src/tests_local.rs, frame/support/src/traits.rs, frame/system/src/lib.rs
Closes https://github.com/paritytech/substrate/issues/6184
https://github.com/paritytech/substrate/pull/4895 solves the account reuse issue when ED is zero.
I don't see any other reasons to require ED > 0.
TODO
=> Allow ExistentialDeposit = 0

bin/node/runtime/src/lib.rs, frame/grandpa/src/mock.rs, frame/offences/benchmarking/src/mock.rs, frame/session/benchmarking/src/mock.rs, frame/staking/fuzzer/src/mock.rs, frame/staking/src/lib.rs, frame/staking/src/mock.rs, primitives/arithmetic/src/lib.rs, primitives/arithmetic/src/per_things.rs, primitives/phragmen/fuzzer/src/common.rs, primitives/phragmen/fuzzer/src/equalize.rs, primitives/phragmen/src/lib.rs, primitives/phragmen/src/reduce.rs, primitives/phragmen/src/tests.rs
Closes https://github.com/paritytech/substrate/issues/6106
- companion: https://github.com/paritytech/polkadot/pull/1184
=> Accept new Phragmén solutions if they are epsilon better + Better pre-inclusion checks.

client/basic-authorship/src/basic_authorship.rs
follow up of #6067 
Problem when we're building block `B`:
1) there are transactions [`T1` <- `T2`] in pool;
2) `on_initialize` of block `B` exhausts all available block resources;
3) we're trying to include `TX1` into `B` and fail => `T1` is marked invalid;
4) then we proceed to `T2` and it is also invalid because nonce check fails;
5) both transactions are removed from the pool.
This PR fixes that by not invalidating first tx of block if it exhausts resources. So first and all other transactions are just skipped in this case.
=> Do not invalidate first tx of the block if initialization is too heavy

client/cli/src/lib.rs
`12:44:11.8` is actually `12:44:11.008` !
=> Fix ms display in log files

Cargo.toml
As the code explains it, this is a list of dependencies that we compile with `opt-level=3` when doing a plain `cargo build`.
=> Make dev profile faster by compiling deps with opt-level=3

Cargo.lock, Cargo.toml, bin/utils/subkey/Cargo.toml, client/authority-discovery/Cargo.toml, client/network-gossip/Cargo.toml, client/network/Cargo.toml, client/network/test/Cargo.toml, client/telemetry/Cargo.toml
Many of the feature requirements don't make any sense.
Additionally, `subkey` was activating all the default libp2p features, which added unnecessary dependencies.
=> Fix libp2p features

client/service/src/builder.rs
Instead of having the tx pool and offchain worker being feed from the
same import notification stream, this pr splits them to use two
different streams. The first advantage of this split is that the tx pool
will not be spawned anymore in another task and instead will directly
process the notification in the same task. This has the advantage of
being faster when the system is being under load, as the tx pool will
not be waiting for being scheduled to handle the notification.
Probably fixes: https://github.com/paritytech/substrate/issues/6218
=> Split tx pool and offchain notification handling

client/cli/src/runner.rs
This will solve https://github.com/paritytech/cumulus/issues/79
In some cases we don't want to allow the end user to choose to run a light node. It is the case, for example, on cumulus where the parachain needs to be a full node. These new methods in the CLI API will allow the developer to only support the full node if they need to.
=> Add run_full_node, run_light_node and print_node_infos to the API 

README.md
This is a super simple PR so I'm not going to check all the boxes. All I'd like to say is that this repo is currently trending on github so if you stumble onto it and click the getting started link and it leads to 404 then it's kind of not nice.
=> The link to getting-started was obsolete.

primitives/runtime/src/traits.rs
Currently, using this macro on a struct with public fields causes a missing\_docs warning.
=> impl_opaque_keys should allow doc comments

client/network/src/protocol.rs, client/network/src/protocol/sync.rs, client/network/src/service.rs, client/network/test/src/lib.rs, client/network/test/src/sync.rs
Instead of checking number of blocks processed by the import queue, which is racey, tests now simply check the number of downloaded blocks.
Only touches test code.
Closes #5518
=> Use number of downloaded blocks for test

client/network/src/service.rs
I'm totally lost in where we are in that, but here's a PR that adds sentry nodes and validator nodes as reserved. In other words `--sentry` and `--sentry-node` also imply `--reserved-node`.
=> Sentry nodes and validator nodes also imply reserved

bin/node/runtime/src/lib.rs, frame/democracy/src/benchmarking.rs, frame/proxy/Cargo.toml, frame/proxy/src/benchmarking.rs, frame/proxy/src/lib.rs, frame/proxy/src/tests.rs, frame/support/src/traits.rs
Feature in `proxy` module to create usable accounts that have no assicated secret key. Instead, they begin life with the creator (origin) account as a registered proxy for them. This can then be altered as desired. This open up a bunch of interesting use cases for proxies, in particular when combined with multisigs.
TODO:
=> Allow "anonymous" proxied accounts

client/api/src/in_mem.rs
This PR fixes possible deadlocks in client/api/src/in_mem.rs:
When comparing with itself, `fn equal_to(&self, other: &Self)` will have `self` and `other` point to the same `Blockchain`.
According to `parking_lot::RwLock`:
“readers trying to acquire the lock will block even if the lock is unlocked when there are writers waiting to acquire the lock.”
“attempts to recursively acquire a read lock within a single thread may result in a deadlock.”
So the two read locks (once interleaved by a write lock from another thread) may lead to deadlock.
`fn canon_equals_to()` has a similar issue.
The fix is to compare the two addresses and return early when they are equal.
=> client/api: fix possible deadlock when comparing with itself

frame/society/src/lib.rs
This is a temporary patch that makes society weights very heavy, but almost certainly completely safe for the Kusama runtime.
An important follow up here is to add real weights to this pallet so that we can reduce the economic burden on those that want to use it.
=> Temporary and Heavy Weights for Society Pallet

Cargo.lock, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs, frame/indices/Cargo.toml, frame/indices/src/benchmarking.rs, frame/indices/src/lib.rs, frame/multisig/src/benchmarking.rs, frame/multisig/src/tests.rs, frame/utility/src/benchmarking.rs
This adds benchmarks and weights to the Indices pallet.
There is an additional follow up to this PR where I should do simple benchmarking on the `lookup` and `unlookup` functions in the `StaticLookup` trait, but this is not critical for the network for the time-being.
Benchmark data here: https://www.shawntabrizi.com/substrate-graph-benchmarks/?p=indices&e=claim
This PR also patches some stuff in the Multisig/Utility benchmarks
=> Weights for Indices Pallet

client/db/src/parity_db.rs
=> Fix typo: eror -> error

client/network/src/protocol.rs, client/transaction-pool/src/lib.rs, client/transaction-pool/src/testing/pool.rs
- Network has too short memory of what peer has what transaction (needs to remember at least 2 full block of transactions).
- We should not resubmit transactions that are found both in enacted and retracted block since they are included in the chain despite being part of the retracted block.
=> Fix transaction pool & network issues

client/network/src/service/tests.rs
I wrote this test to check whether things were working fine if we are presented with a lot of incoming connections.
I didn't discover any problem, but we might as well put the test in the code base in case it detects a regression.
This branch creates only 256 nodes, but it works on my machine with 1024 as well. With 2048 I get errors due to the high number of threads (which is expected, since these are 2048 *full networking stacks*, not just 2048 connections).
=> Add a test for lots of nodes connecting at the same time

bin/node-template/node/src/lib.rs
So that subxt can use the node-template for it's unit tests the chain spec and service need to be exposed.
=> Expose chain_spec and service in node-template

client/network/src/service/tests.rs
Apparently the CI server doesn't like that we're spawning thousands of threads.
=> Reduce the lots_of_incoming_peers_works test load

primitives/core/src/crypto.rs
Fixes #6289 
I'm not sure what display should actually display so I just used the debug.... any idea @DemiMarie-parity
=> Impl Debug and Display for Ss58AddressFormat when compiled with std

bin/node-template/node/src/service.rs, bin/node/cli/src/service.rs, client/service/src/builder.rs, client/transaction-pool/src/api.rs, client/transaction-pool/src/lib.rs, primitives/transaction-pool/src/pool.rs
This PR adds a new trait `LocalTransactionPool` that exposes a method for sending local transactions in a blocking manner. This is only implemented for full nodes as we can call into the runtime locally to validate the transaction. This trait is then used to implement the offchain extension for transaction submission. I needed this as I was calling into an offchain runtime from a future context, otherwise I'd get a panic due to nested calls to `futures::block_on`.
I had to separate the `ServiceBuilder::build()` into full and light variants. There is more stuff that can be moved out of the light builder (e.g. we don't need offchain workers on the light client). Since there is a pending refactor of the service builder I made an effort to minimize changes there.
polkadot companion: …
=> transaction-pool: expose blocking api for tx submission

client/transaction-pool/src/lib.rs, client/transaction-pool/src/metrics.rs
residual would be actual chain growth (in number of transactions)
=> Pruned and resubmitted metrics in transaction pool

bin/node-template/node/Cargo.toml, bin/node-template/pallets/template/Cargo.toml
This adds the wasmtime feature flag to the node-template node so that you can run the node using `--wasm-execution=compiled`.
=> Enable wasmtime on node-template

frame/scheduler/src/lib.rs
=> Basic documentation for Scheduler pallet

.maintain/gitlab/check_line_width.sh
Currently, the check-line-width checks all lines in the PR that are different from the current master. However, this is a moving target and will include foreign lines when the PR is not up to date with the current master.
This changes this behavior so that the comparison is made against the original commit where the PR branched off of.
This uses an environment variable supplied by gitlab CI. This makes this script not usable locally. I am not sure if this is a requirement.
Edit: For some reason `$CI_COMMIT_BEFORE_SHA` contains `0000000000000000000000000000000000000000`. Is there something wrong with our gitlab @gabreal ?
=> Fix check-line-width CI script

client/transaction-pool/src/lib.rs, client/transaction-pool/src/testing/pool.rs
This pr fixes a bug with the transaction pool not sending certain events
like finalized and also fixes the order of events. The problem with the
finalized event was that we did not extracted pruned extrinsics if there
were not ready transactions in the pool. However this is wrong, if we
have a re-org, a tx is clearly not ready anymore and we still need to
send a pruned event for it because it is in a new block included. This
also lead to sending "ready" events and tx being re-validated. The
listener also only send the "finalized" event if it has seen a block as
being included, which did not happen before with the old code.
The second fix of the pr is the order of events. If we prune and retract the
same transaction in the same block, we first need to send the "retract"
event and after …
=> Fix transaction pool event sending

frame/contracts/src/lib.rs, frame/evm/src/lib.rs, frame/recovery/src/lib.rs, frame/scheduler/src/lib.rs, frame/sudo/src/lib.rs, frame/sudo/src/mock.rs, frame/support/src/weights.rs, frame/system/src/lib.rs, frame/utility/src/lib.rs
Closes #6104
This marks the `FunctionOf` struct used in weight annotations as deprecated and removes all users. Polkadot does not use it. So no companion necessary.
As it turns out we never really needed this struct as the `#[weight]` macro already makes the arguments of the function (with the exception of `origin`) available. Removing this macro makes the weight annotation much more easy on the eyes and removes the need for explicitly specifying the `class` and `pays` when their defaults are used.
* We should remove the struct with our next major release.
* Make origin available in the annotation: #6316  (wasn't available in `FunctionOf`)
=> Deprecate FunctionOf and remove its users

frame/balances/src/lib.rs, frame/balances/src/tests.rs, frame/staking/src/tests.rs, frame/support/src/traits.rs
Closes https://github.com/paritytech/substrate/issues/6329
Two things in particular I could use feedback on:
1. Are all the `clone`s OK? It didn't compile without them (or using references), but maybe there's a more elegant solution.
2. I put the `derive(...)` impls on `BalanceStatus` that copied other enums that emit in events. Again, maybe another way that's better.
=> Add events for balance reserve and unreserve functions

primitives/core/src/crypto.rs
Hi, in order to prevent the re-usage across networks, decreasing the value at risk if a private key is lost, and also to identify easily. We want to registry the Subkey Address Type as 20 for Stafi mainnet. If there are any concerns please kindly tell us.
Many thanks for your hard-working on Substrate.
=> adding a ss58 format for Stafi Network

primitives/runtime/src/offchain/storage_lock.rs
In some cases, such as doing iterations in offchain worker, the time to be consumed is hard to estimate
, and it's necessary to extend the deadline of the `StorageLock` after each successful next step during the whole iteration process.
So I add new function for `StorageLock` to support extending deadline of an active lock.
=> add extend_lock for StorageLock

Cargo.lock, client/cli/src/commands/mod.rs, client/cli/src/commands/run_cmd.rs, client/cli/src/config.rs, client/rpc-servers/Cargo.toml, client/rpc-servers/src/lib.rs, client/service/src/config.rs, client/service/src/lib.rs, client/service/test/src/lib.rs, utils/browser/src/lib.rs
This is useful for both security and performance reasons. IPC is faster
than TCP, and it is subject to OS access controls.
=> Add IPC support

frame/recovery/src/lib.rs
expose these constants in `pallet_recovery::Trait` for querying them
=> expose constants in pallet_recovery trait

.github/workflows/auto-label-prs.yml
If a new PR is created as a draft, gets auto-labeled with A3-inprogress.
If a new PR is created and is not a draft, gets auto-labeled with A0-pleasereview
If 'ready for review' is clicked, the A3-inprogress label is removed and A0-pleasereview is added.
=> [CI] Auto-label new PRs according to draft status

Cargo.lock, client/consensus/aura/src/lib.rs, client/consensus/babe/src/lib.rs, client/consensus/manual-seal/src/lib.rs, client/consensus/pow/src/lib.rs, client/informant/Cargo.toml, client/informant/src/lib.rs, client/offchain/src/lib.rs, client/service/src/builder.rs, client/service/src/lib.rs, client/service/src/metrics.rs, client/service/src/task_manager.rs, client/transaction-pool/src/lib.rs, primitives/consensus/common/src/import_queue/basic_queue.rs, primitives/core/src/testing.rs, primitives/core/src/traits.rs, primitives/utils/Cargo.toml, primitives/utils/src/lib.rs, primitives/utils/src/status_sinks.rs
This is an attempt at what @bkchr talks about here: https://github.com/paritytech/substrate/pull/6309#issuecomment-641911216. This makes the `ServiceBuilder::build_common` a lot simpler, and will make it (in the long run) a lot easier to get rid of.
=> Split the service initialisation up into seperate functions

.gitlab-ci.yml, .maintain/gitlab/check_labels.sh, .maintain/gitlab/lib.sh
* Ensures presence of one of the following labels:
* 'B0-silent'
* 'B3-apinoteworthy'
* 'B5-clientnoteworthy'
* 'B7-runtimenoteworthy'
* Ensures presence of one of the following labels:
* 'C1-low'
* 'C3-medium'
* 'C7-high'
* 'C9-critical'
=> [CI] Add label enforcement

client/authority-discovery/src/lib.rs, client/authority-discovery/src/tests.rs
In the scenario of a validator publishing the address of its sentry node
to the DHT, said sentry node should not add its own Multiaddr to the
peerset "authority" priority group.
Related to 70cfeff.
=> client/authority-discovery: Don't add own address to priority group

.gitlab-ci.yml
Add a CI stage to test the Prometheus alerting rules within
`.maintain/monitoring`.
=> .gitlab-ci.yml: Run promtool on Prometheus alerting rules

client/network/src/protocol.rs
This change has been extracted from #5938 
We no longer shut down all connections and ban the peer if more than one `Status` message has been received.
Relates to #2010 
At the moment, the network protocol defines that it is forbidden to send messages on notifications substreams as long as the `Status` messages haven't been exchanged on the legacy substream.
This is currently enforced by the "network worker" (i.e. the main networking task).
Additionally, if multiple TCP connections between the same two peers exist, we only send the `Status` message on one of them, and not both. If we were to send `Status` on both, the remote would instantly shut down all connections (because of the code that this PR removes).
Whenever a legacy substream is open, we therefore need to know whether we have …
=> Remove penalty on duplicate Status message

frame/support/src/dispatch.rs, frame/support/test/tests/decl_module_ui.rs, frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_integrity_test.rs, frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_integrity_test.stderr, frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_on_initialize.rs, frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_on_initialize.stderr
This prints a better error message on duplicated reserved keywords,
instead of complaining because of missing `origin`.
Fixes: https://github.com/paritytech/substrate/pull/6378
=> `decl_module!` print better error on duplicate reserved keyword

primitives/arithmetic/src/fixed_point.rs
`is_positive` fn of `FixedPointNumber` returns `true` for zero value. It's against the usual positive definition in math, and not consistent with [the API in Rust std lib](https://doc.rust-lang.org/std/primitive.i128.html#method.is_positive).
This PR includes:
- `is_positive` fix.
- Updated docstring of `is_positive` and `is_negative` to be the same with rust std lib(which I think is a bit more accurate).
- Added a unit test for `is_positive` and `is_negative` fn.
=> Fix FixedPointNumber: zero is not positive.

Cargo.lock, frame/executive/src/lib.rs, primitives/state-machine/Cargo.toml, primitives/state-machine/src/lib.rs, primitives/state-machine/src/testing.rs, primitives/trie/Cargo.toml, primitives/trie/src/lib.rs, test-utils/runtime/Cargo.toml
Closes #5986
State root changed in some tests because test externalities come with empty code and this affects the root. 
I've verified that this does not break consensus for polkadot and kusama so far.
@bkchr could you please confirm that `clear_storage` is called when runtime actually wishes to delete storage. E.g. drop a map.
=> Allow empty values in the storage

.maintain/flamingfir-deploy.sh
Required for automated pushes of substrate to flaming fir
=> Update s3 artifact url

client/network/src/service.rs
cc https://github.com/paritytech/substrate/issues/6009
After https://github.com/paritytech/substrate/pull/6064, it's pretty clear that the spikes in the network worker taking a long time are caused by the fact that the network worker is sleeping while waiting for a libp2p node task to empty the messages in its channel, and that during this sleep the events accumulate in the queues.
We still have spikes, so this PR increases these channel sizes even more, allowing for more parallelism between the network worker and the node tasks.
=> Increase network buffer sizes even more

frame/atomic-swap/Cargo.toml
[cargo unleash check](https://gitlab.parity.io/parity/substrate/-/jobs/559369#L575) shows there is dependency issue on the newly added `pallet-atomic-swap`: when removing the dev-dependencies, the parsing of the manifest fails because it is still referenced in the `std`-feature. Which means we can't release the crate after removing the dev-deps (what we always do to remove the internal cycles were are seeing).
This PR removes that reference and sets the default features to true on the dependency in dev. We are running our tests in `std`/native only anyways.
=> Fix cargo unleash check for the atomic-swap pallet

client/cli/src/params/network_params.rs, client/network/src/config.rs, client/network/src/protocol.rs, client/network/src/service.rs
The `--legacy-network-protocol` can be used to force sending block requests on the legacy substream instead of the new request-response protocol.
Despite all the problems that the new request-response protocol had to go through when it got introduced, we ended up never using this flag.
Now that the new protocol has been working fine for a little while, I think we can remove this mechanism.
=> Remove --legacy-network-protocol CLI flag

frame/staking/src/lib.rs
=> Scale and increase validator count

frame/proxy/src/lib.rs
This exposes the constants in the Proxy Pallet to the metadata.
=> Expose Constants from Proxy Pallet

.github/workflows/polkadot-companion-labels.yml
This PR will add a CI check that monitors the status of the `gitlab-check-polkadot-companion-build` job. If it fails, the PR gets labelled with `A7-needspolkadotpr`. If a subsequent check passes, the label will be removed.
Might be buggy in the case that the job on gitlab is just re-run, since it relies on Github's `synchronize` event for pull requests, which is only fired when the head branch is updated (i.e., more changes pushed).
=> [CI] Label PRs if polkadot companion build fails

frame/system/src/lib.rs
This prints the error that leads to bad mandatory.
=> Print bad mandatory error

client/informant/src/lib.rs
This implements tracking of the last seen blocks in informant display
to prevent printing the import message twice. In Cumulus we first import
blocks as part of the block building with `new_best == false` and set
the best block after we know which one was included by the relay chain.
This leads to printing the import messages two times. This pr solves the
problem by track the latest seen blocks to not print the message twice.
=> Track last blocks in informant display

client/consensus/babe/src/lib.rs, client/consensus/slots/src/lib.rs
This is a small check during the node creation that will ensure that the slot_duration is greater than 0.
During test, before:
> thread 'async-std/executor' panicked at 'attempt to calculate the remainder with a divisor of zero', /home/cecile/.cargo/git/checkouts/substrate-7e08433d4c370a21/65365aa/client/consensus/slots/src/slots.rs:66:49
During test, after:
> thread 'ensure_test_service_build_blocks' panicked at 'called `Result::unwrap()` on an `Err` value: Client(Msg("Invalid value for slot_duration: the value must be greater than 0."))', polkadot-test-service/tests/build-blocks.rs:30:21
On cli it should not panic but end the process properly.
=> More descriptive error message when invalid slot duration is used

frame/democracy/src/tests.rs, frame/scheduler/src/lib.rs, frame/support/src/origin.rs, frame/system/src/lib.rs
In sudo, democracy and scheduler we want to dispatch with origin root and without using BaseCallFilter.
To fix this I see two solution:
* we can do as we have done for sudo https://github.com/paritytech/substrate/pull/6375: use `dispatch_bypass_filter`.
* or do not use BaseCallFilter to create Root runtime origin.
This PR implement the second technique.
* frame-system build root origin with no filter
* tests added in democracy and scheduler to ensure they dispatch call filtered out by BaseCallFilter
* doc added in frame-system
CC @gavofyork
=> Root origin use no filter by default. Scheduler and Democracy dispatch without asserting BaseCallFilter

frame/support/src/dispatch.rs, frame/support/test/tests/system.rs
Fix https://github.com/paritytech/substrate/issues/6419
=> Allow decl-module to have a where clause with trailing comma

.gitlab-ci.yml
Follow up to https://github.com/paritytech/substrate/pull/6343#pullrequestreview-433351561.
> `/usr/local/bin/promtool` is now included within `paritytech/tools:latest`
=> .gitlab-ci.yml: Use promtool from paritytech/tools:latest image

client/network/src/protocol.rs, client/network/src/service.rs, client/service/src/lib.rs
Before we only updated the chain info of sync when we have imported
something using the import queue. However, if you import your own
blocks, this is not done using the import queue and so sync is not
updated. If we don't do this, it can lead to sync switching to "major
sync" mode because sync is not informed about new blocks. This
especially happens on Cumulus, where a collator is selected multiple
times to include its block into the relay chain and thus, sync switches
to major sync mode while the node is still building blocks.
=> Update sync chain info on own block import

client/authority-discovery/src/lib.rs
In order to tell whether an address is the local nodes address the
authority discovery module previously compared the Multihash within the
`p2p` Multiaddr protocol.
rust-libp2p recently switched to a new PeerId representation (see [1]).
Multihashes of the same PeerId in the new and the old format don't
equal.
Instead of comparing the Multihashes, this patch ensures the module
compares the PeerIds
[1] https://github.com/libp2p/rust-libp2p/issues/555
---
While this is not yet released, operators can just ensure that they specify network identities in the new format (`1[..]`) on the CLI. With this in mind, this is not a critical bug fix.
=> client/authority-discovery: Compare PeerIds and not Multihashes

client/consensus/babe/src/authorship.rs, client/keystore/src/lib.rs
We need to check that the public key of an authority exists in our
keystore before we can successfully claim a plain secondary slot.
=> Fix Babe secondary plain slots claiming

Cargo.lock, primitives/npos-elections/Cargo.toml, primitives/npos-elections/compact/src/assignment.rs, primitives/npos-elections/compact/src/lib.rs, primitives/npos-elections/src/tests.rs
This removes the `dev-dependency` onto `sp-npos-elections` from itself.
A crate should not depend on itself directly, especially not to make any
macros work.
=> sp-npos-elections should not depend on itself

client/network/src/protocol.rs, client/network/src/service.rs, client/service/src/builder.rs
Everything that travels across network should be called "transaction"
=> Change term "extrinsic" to "transaction" in network/service

bin/node-template/node/src/service.rs, bin/node/cli/src/service.rs, client/service/src/lib.rs, client/service/src/task_manager.rs
This PR adds a new task handler to the service for spawning essential tasks, it just wraps `SpawnTaskHandle` adding the logic for notifying the service on task failure. This allows us to spawn essential blocking tasks.
I updated the node service to spawn both the BABE authorship and the GRANDPA voter task to be spawned as blocking tasks. Both these tasks can perform non-trivial IO when doing block ancestry checks, these might take some seconds to finish proportional to any lag in finality and/or number of open forks.
I deprecated the `spawn_task/spawn_essential_task` methods on service since the same functionality can be achieved using the handles and additionally it allows to spawn blocking tasks.
polkadot companion: https://github.com/paritytech/polkadot/pull/1292
=> node: spawn block authoring and grandpa voter as blocking tasks

bin/node/runtime/src/lib.rs, frame/atomic-swap/src/lib.rs, frame/atomic-swap/src/tests.rs
This generalizes the swap action in pallet-atomic-swap, allowing not only sending balances, but also other assets (customized by runtime).
As an usage example -- a runtime that has contract module enabled can define a swap action that allows arbitrary contract calls. There are two contracts -- SubstrateKitties, and MyTokens. SubstrateKitties allows users to send cats to each other, and MyTokens is an asset stored on chain. If users A and B want to exchange a cat for some tokens, they can use the atomic swap to make it happen -- avoiding going through an exchange.
=> pallet-atomic-swap: generialized swap action

frame/system/src/lib.rs
- Adds a check to make sure that `Operational` transactions weight does not exceed the limit for such transactions (since `Operational` transactions are allowed to consume `Normal` transaction space, the limit is actually `MaximumBlockWeight`).
- Changes the priority of `Operational` transactions to `max_value / 2` to make sure things that alter priority (like `tip`) for instance can be used for replacement transactions.
=> Fix issues with `Operational` transactions validity and prioritization.

.github/workflows/polkadot-companion-labels.yml
Previously, when the Gitlab CI job `check-polkadot-companion-build` was cancelled (for instance, if a subsequent commit is pushed before the job completes), the 'error' state returned by Gitlab would cause this Github Action to label the PR with `A7-needspolkadotpr`. I.e., it didn't differentiate between 'error' and 'failure'. This fixes that.
=> [CI] Don't tag PRs on polkadot companion job cancels

frame/benchmarking/src/analysis.rs, frame/benchmarking/src/lib.rs, utils/frame/benchmarking-cli/src/command.rs
This is a small add-on PR to allow the benchmarking analysis tool to do its analysis on any piece of the `BenchmarkResults` data.
=> Add regression analysis to DB Tracking

client/network/src/service/out_events.rs
The trace in https://github.com/paritytech/substrate/issues/6443 seems to indicate that when a `Sender` is dropped after which a `Receiver` is polled again before being dropped, the `Drop` impl of the `Receiver` leads to a panic due to unconditionally calling `StreamExt::next()` on a closed stream. This PR is supposed to avoid that by checking whether the stream is terminated in the `Drop` impl of `Receiver`.
=> Avoid panic on dropping a `sc_network::service::out_events::Receiver`.

Cargo.lock, client/offchain/Cargo.toml, client/offchain/src/api.rs, client/offchain/src/api/http.rs, client/offchain/src/api/http_dummy.rs, client/offchain/src/lib.rs
This PR adds a field to the OffchainWorker struct to allow the re-use of the http_client, removing the need to call some CPU intensive hyper_rustls function each time we run an offchain worker on a block.
Bonus commits: fix a minor typo, use Self keyword in `AsyncApi::new()`
Closes #6304
=> Optimize offchain worker api by re-using http-client

primitives/api/proc-macro/src/impl_runtime_apis.rs, primitives/api/test/tests/runtime_calls.rs, test-utils/runtime/src/lib.rs
With the switch to `decode_all_with_depth_limit` we silently broken
support for functions with multiple arguments. The old generated code
tried to decode each parameter separately, which does not play well with
`decode_all`.
This pr adds a test to ensure that this does not happen again and fixes
the bug by decoding everything at once by wrapping it into tuples.
=> Fix `sp-api` handling of multiple arguments

frame/balances/src/lib.rs
Elevated trait never use those wrongly bonded associated type, though better to make stuff consistent.
only `frame_system::Trait::Event`, `Trait::Event` and `Trait::DustRemoval` are not part of Subtrait.
=> Bound some missing bound for elevated trait

frame/scheduler/src/lib.rs, frame/support/src/traits.rs
Fixes: https://github.com/paritytech/substrate/issues/6477
=> `pallet-scheduler`: Check that `when` is not in the past

.maintain/monitoring/grafana-dashboards/substrate-networking.json, client/network/src/service.rs
Two nodes can be interconnected via one or more connections. The first
of those connections is called the primary connection.
This commit adds another dimension to the
`sub_libp2p_connections_{closed,opened}_total` metrics to differentiate
primary and non-primary connections being opened / closed.
By intuition more than one connection between two nodes is rare.
Tracking the fact whether a connection is primary or not will help prove
or disprove this intuition.
```
$ curl localhost:9615/metrics | grep "primary"  
substrate_sub_libp2p_connections_closed_total{direction="out",reason="transport-error",was_primary="true"} 1
substrate_sub_libp2p_connections_opened_total{direction="in",is_primary="true"} 1
substrate_sub_libp2p_connections_opened_total{direction="out",is_primary="true"} 1
=> client/network/service: Add primary dimension to connection metrics

client/network/src/error.rs, client/network/src/service.rs, client/network/src/service/tests.rs
This PR improves the error message **AND** return early with a failure if the network configuration is inconsistent.
The only checks that are done are:
1. if the TransportConfig is MemoryOnly but a listening address is not Memory
2. if the TransportConfig is not MemoryOnly but a listening address is Memory
Example during test before:
> 2020-06-19 14:22:16 Can't listen on /memory/10872111545232357078 because: MultiaddrNotSupported("/memory/10872111545232357078")
(continue running the done)
Example during test after:
> thread 'ensure_test_service_build_blocks' panicked at 'called `Result::unwrap()` on an `Err` value: Network(The network address /memory/18303963195922760223 is invalid because the transport is not set on MemoryOnly)', polkadot-test-service/tests/build-blocks.rs:31:21
In cli …
=> Ensure the listen addresses are consistent with the transport

frame/benchmarking/src/lib.rs, frame/benchmarking/src/tests.rs
this doesn't break anything but allow the new syntax:
```rust
benchmarks!{
_ where <T as OtherTrait>::OtherEvent: Into<<T as Trait>::Event> {
// Define a common range for `b`.
let b in 1 .. 1000 => ();
}
...
```
Maybe we can put the where clause in a better place though, and not sure about doc.
* the where clause is automatically tested to be everywhere because otherwise it wouldn't compile, see https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fe4e3e09e03e7fdcebeb18634d2f6c36
Fix https://github.com/paritytech/substrate/issues/6432
=> Allow where clause in benchmarking

client/consensus/slots/src/lib.rs
Before:
```
2020-06-24 15:11:34 ⏱  Loaded block-time = BabeGenesisConfiguration { slot_duration: 3000, epoch_length: 200, c: (1, 4), genesis_authorities: [(Public(d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...)), 1)], randomness: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], allowed_slots: AllowedSlots::PrimaryAndSecondaryPlainSlots } milliseconds from genesis on first-launch
```
After:
```
2020-06-24 15:10:56 ⏱  Loaded block-time = 3000 milliseconds from genesis on first-launch
```
=> client: fix print of slot duration on startup

.maintain/sentry-node/docker-compose.yml, .maintain/sentry-node/prometheus/prometheus.yml
Context: `.maintain/sentry-nodes` spins up a simple environment with two validators, one sentry, Prometheus and Grafana (including all dashboards from `.maintain/monitoring`) for local development via `docker-compose -f .maintain/sentry-node/docker-compose.yml up`.
This patch contains:
- Remove burden on user to build polkadot-js apps Docker image locally in
order to get started.
- Update Prometheus config fixing target name.
=> .maintain/sentry-node: Remove UI and update Prometheus target

client/service/src/builder.rs
Include the genesis hash in the `system.connected` telemetry message, so that the telemetry server can differentiate between different networks with the same name. Required for: https://github.com/paritytech/substrate-telemetry/issues/263
=> Include genesis hash in system.connected

frame/identity/src/lib.rs, frame/membership/src/lib.rs, frame/nicks/src/lib.rs, frame/scored-pool/src/lib.rs, frame/staking/src/lib.rs, frame/treasury/src/lib.rs
Follow-up to #6237 , updated docstring to match changes.
=> Update stale docstring with 'EnsureOneOf' introduced.

.github/workflows/auto-label-issues.yml
Any new issues submitted will be labelled with `Z0-unconfirmed` if the author has 'author_association' of 'NONE' (i.e., has no association with this repository).
Due to a quirk with how the author_association field works, if the author of the issue has code in the repo, the issue will not be autolabelled (since they will be considered a CONTRIBUTOR).
Author_association is documented here: https://developer.github.com/v4/enum/commentauthorassociation/
was requested as part of https://github.com/paritytech/substrate/issues/6175 - if we no longer want this functionality, feel free to drop the PR.
=> Label new issues with Z0-unconfirmed

docs/CODEOWNERS
There is a lot of PRs that touch RPC somehow, but usually I'm not the necessary person to review them.
=> Remove /self from mandatory rpc reviews.

bin/node/runtime/src/lib.rs
When deploying smart contracts, the storage costs are too high and the contract gets evicted after a few Txs.
Changing the units enable a cheaper and more fluent interaction.
=> Change contracts fees to MILLICENTS

primitives/state-machine/src/ext.rs
This PR fixes runtime benchmarking which needs to commit the overlay to backend from the runtime which is something we generally disallow for production runtimes.
This still assumes that the client did not start any transactions before calling into runtime. This is the case for benchmarking as long as either `NativeWhenPossible` or `AlwaysWasm` execution strategy is chosen. Using any other will result in a panic. This is OK as the host functions which could lead to this are only available when the `runtime-benchmarks` feature is set.
=> benchmarking: Re-enter runtime after resetting overlay from runtime

client/cli/src/commands/run_cmd.rs, client/cli/src/error.rs
Fix #6497 
Without the `#[from(ignore)]`, the macro generates an `impl From<()> for Error`, which accidentally gets used because of the extra semicolon.
=> Fix an extra semi-colon yielding a wrong error

frame/proxy/src/tests.rs, frame/utility/src/benchmarking.rs, frame/utility/src/lib.rs, frame/utility/src/tests.rs
- `as_sub` is removed
- `as_sub_limited` becomes `as_derivative`
Polkadot companion: https://github.com/paritytech/polkadot/pull/1315
=> Refactor as_sub to make things clearer.

.github/workflows/polkadot-companion-labels.yml
Docs of Action were wrong. s/failedStates/failureStates/.
=> [CI] Fix warning in polkadot-companion-label action

docs/CODEOWNERS
I don't want to block an entire PR just for little changes in sc-cli
=> Remove @cecton from CODEOWNERS

bin/node/cli/src/service.rs, primitives/runtime/src/generic/unchecked_extrinsic.rs, primitives/runtime/src/lib.rs
I'm working currently on some test in cumulus and my runtime is using UncheckedExtrinsic but the allowed extrinsic type for PolkadotClient is OpaqueExtrinsic.
This is fine and it can be converted easily using this command:
```rust
builder.push(OpaqueExtrinsic::decode(&mut extrinsic.encode().as_slice()).unwrap()).unwrap()
```
But this is not what I did first. Since OpaqueExtrinsic exposes its inner type (Vec<u8>) I thought I would need to wrap my extrinsic in the OpaqueExtrinsic:
```rust
builder.push(OpaqueExtrinsic(&mut extrinsic.encode())).unwrap()
```
This felt more natural to me but it is not correct. When OpaqueExtrinsic will be encoded it will add 4 additional bytes in the beginning.
This is error prone and requires debugging to figure out what is wrong. But even with debugging, I …
=> Impl From<UncheckedExtrinsic> for OpaqueExtrinsic

client/cli/src/commands/run_cmd.rs, client/cli/src/config.rs
Increases the maximum telemetry name to 64 bytes.
Since there was a concern that it would break the UI, here's a screenshot of the telemetry on my standard 1900-something-by-something screen with a 63-characters-long node name:
cc @maciejhirsz  @TriplEight
=> Increase the limit for the maximum size of the telemetry name

frame/democracy/src/benchmarking.rs, frame/multisig/src/benchmarking.rs, frame/scheduler/src/benchmarking.rs
This PR fixes some benchmarks that have become broken due to small changes in the runtime.
@TriplEight I need your help to get CI working with these benchmarks so that further PRs do not get accepted that continue to break benchmarks.
=> Fix some broken benchmarks

Cargo.lock, bin/node/runtime/src/lib.rs, frame/treasury/Cargo.toml, frame/treasury/src/lib.rs, frame/treasury/src/tests.rs
This is a PR that allows the Tippers set to retract tips they open with `tip_new`.
To enable this we do a slight refactor to the `OpenTip` struct.
Before, there was a single item `finder` that was an `Option<(AccountId, Balance)>` representing the user who founded the tip and their deposit. In the case of a `Tipper` opening a tip, we set this value to None. This value being none also implied that the finders fee is not paid out.
In order to enable this feature, we need to always have a record of who opened the tip, so I have opted to split this object into two mandatory properties:
* `finder: AccountId`
* `deposit: Balance`
Finally, we need a new way to track whether we pay out a finders fee, so I have opted to simply add a new item to the struct which determines this:
* `finders_fee: …
=> Allow `retract_tip` on `tip_new`

primitives/api/proc-macro/src/impl_runtime_apis.rs
[`parity_scale_codec::DecodeLimit::decode_all_with_depth_limit`][1] doesn’t require the second argument to be a mutable reference.
[1]: https://docs.rs/parity-scale-codec/1.3.1/parity_scale_codec/trait.DecodeLimit.html#tymethod.decode_all_with_depth_limit
=> Remove unecessary &mut in call argument

primitives/core/src/crypto.rs
Previous PR was #5465. This PR has been created instead to request available ss58 prefixes 33, which has not already been reserved
* We would like to claim these ss58 prefixes:
* 33: DataHighway Mainnet
* We will be using Substrate's ss58 prefix of 42 for DataHighway Harbour Testnet
* [DataHighway](https://github.com/DataHighway-DHX/node) will be a parachain supported by the Polkadot network. The chain's repo requires an ss58 address format network identifier prefix, see associated [issue](https://github.com/DataHighway-DHX/node/issues/87).
=> Add ss58 address format network identifier prefix for DataHighway parachain

client/transaction-pool/graph/src/ready.rs, client/transaction-pool/src/revalidation.rs, client/transaction-pool/src/testing/pool.rs, test-utils/runtime/src/lib.rs, test-utils/runtime/transaction-pool/src/lib.rs
This fixes a bug that lead to returning the same transaction multiple
times when iterating the `ready` iterator. Internally the transaction
was kept in the `best` list and could be duplicated in that list be
re-inserting it again. This `best` list is using a `TransactionRef`
which internally uses a `insertion_id`. This `insertion_id` could lead
to the same transaction being inserted multiple times into the `best`
list.
Fixes: https://github.com/paritytech/substrate/issues/4924
=> Fix tx-pool returning the same transaction multiple times

client/finality-grandpa/src/communication/gossip.rs, client/finality-grandpa/src/communication/mod.rs, client/finality-grandpa/src/environment.rs, client/finality-grandpa/src/justification.rs, client/finality-grandpa/src/lib.rs, client/finality-grandpa/src/observer.rs, client/finality-grandpa/src/tests.rs, frame/grandpa/src/equivocation.rs, primitives/finality-grandpa/src/lib.rs
Reviewing commit-by-commit should make the changes more obvious.
=> grandpa: minor cleanups in communication module

frame/evm/src/backend.rs, frame/evm/src/lib.rs
This allows chain id in EVM to be customized. To revert to old behavior, simply set `ChainId = SystemChainId`.
=> pallet-evm: customizable chain id

client/executor/src/integration_tests/mod.rs, frame/example-offchain-worker/src/tests.rs, primitives/core/src/offchain/testing.rs
Fixes an issue with a function call in tests that performs more than one http request and waits for each to complete before proceeding. 
The `RequestId` comes from the length of the `requests` collection in the `OffchainState` and if a request is completed before the next one starts it will be removed and the "next expected" will be off by one. 
This PR tries to fix that by using a request counter that tracks how many requests have been performed so that we can `remove()` items from the `expected_requests` at the right index.
I suspect that this is a sub-optimal solution and perhaps requests and their mocks should live side by side in the same collection, e.g. in a tuple of `(PendingRequest, Option<ExpectedRequest>)`.
=> Fix mocking multiple http calls in the same function call

.github/workflows/auto-label-issues.yml
Statements in github actions cannot use ", must use '
=> [CI] Fix auto-label-issues.yml

.github/workflows/burnin-label-notification.yml
This is a temporary/preliminary Github action that will trigger a message in the #polkadot-devops Matrix channel whenever a PR is labelled with A1-needsburnin. The intention is to fully automate the deployment of PRs requiring burn-in, so this is a stand-in until that functionality has been developed.
=> [CI] Add Github Action to notify devops of PRs labelled with A1-needsburnin

client/cli/src/runner.rs
I commented [here](https://github.com/paritytech/substrate/pull/6352#discussion_r447733107) that this had no importance but I was wrong. The tokio runtime must be dropped before the task_manager. Otherwise the objects the task_manager keep alive are dropped before the tasks are finished.
=> Drop the tokio runtime before the task_manager

Cargo.lock, client/basic-authorship/src/basic_authorship.rs, client/block-builder/Cargo.toml, client/block-builder/src/lib.rs, frame/support/src/storage/mod.rs, primitives/api/proc-macro/src/impl_runtime_apis.rs, primitives/api/proc-macro/src/mock_impl_runtime_apis.rs, primitives/api/src/lib.rs, primitives/runtime/src/lib.rs
This moves the `create_inherents` call into the block-builder. This has
the advantage that `create_inherents` will be able to reuse the same
context that will be used when applying the extrinsics and we also save
one call to `on_initialize`. To make sure that `create_inherents` does
not modify any state, we execute it in a transaction that is
rolled-back after doing the runtime call.
=>  Move `create_inherents` into the block-builder

client/network/src/service.rs, client/network/test/src/lib.rs, client/service/src/lib.rs
`<NetworkWorker as Future>` never makes any use of the `Result` in its `type Output = Result<(), io::Error>;` associated type. This is likely from the `futures-0.1` days. This pull request removes the `Result`.
Follow up to https://github.com/paritytech/substrate/pull/6533#discussion_r448347931.
polkadot companion: https://github.com/paritytech/polkadot/pull/1338
=> client/network: Remove unused Result returned by NetworkWorker

.maintain/gitlab/check_polkadot_companion_build.sh
Even though it was nice it was also error prone as there were no indication whatsoever on the PR
that a polkadot companion branch exists.
=> Remove polkadot companion detection from branch name 

client/db/src/cache/list_cache.rs, client/db/src/cache/list_entry.rs, frame/finality-tracker/src/lib.rs, frame/grandpa/src/mock.rs, frame/grandpa/src/tests.rs, primitives/runtime/src/testing.rs
We have a custom `Header` type for testing but it doesn't seem to have any difference compared to `generic::Header`. This PR replaces that type with an alias to `generic::Header`.
=> primitives: use generic Header in testing runtime

docs/CONTRIBUTING.adoc
Even though it was nice it was also error prone as there were no indication whatsoever on the PR that a polkadot companion branch exists.
=>  Remove polkadot companion detection from branch name 

frame/multisig/src/lib.rs
Closes https://github.com/paritytech/substrate/issues/6544
cc @jacogr
=> Make the encoded-Call Vec<u8> explicitly so in metadata

frame/support/procedural/src/construct_runtime/mod.rs
This PR uses the `RuntimeDebug` derive implementation to implement `fmt::Debug` in both `std` and `no_std` environments.
=> Derive `RuntimeDebug` for `Runtime`

Cargo.lock, bin/node/bench/Cargo.toml, client/api/Cargo.toml, client/cli/Cargo.toml, client/db/Cargo.toml, client/informant/Cargo.toml, client/service/Cargo.toml, client/state-db/Cargo.toml, client/transaction-pool/Cargo.toml, client/transaction-pool/graph/Cargo.toml, frame/support/Cargo.toml, frame/transaction-payment/Cargo.toml, primitives/core/Cargo.toml, primitives/database/Cargo.toml, primitives/runtime/Cargo.toml, primitives/state-machine/Cargo.toml, primitives/test-primitives/Cargo.toml, primitives/trie/Cargo.toml, test-utils/runtime/Cargo.toml, utils/browser/Cargo.toml
The updates of `trie-db` and `memory-db` are important, as they fix the
non-deterministic build of Polkadot/Substrate.
polkadot-companion: https://github.com/paritytech/polkadot/pull/1373
=> Upgrade `kvdb-*`, `trie-db` and `memory-db`

client/network/src/protocol.rs, client/network/src/protocol/generic_proto/behaviour.rs, client/network/src/protocol/generic_proto/handler/group.rs, client/network/src/protocol/generic_proto/tests.rs, client/network/src/protocol/generic_proto/upgrade/legacy.rs
Changes extracted from https://github.com/paritytech/substrate/pull/5938
Let's summarize the situation again:
- When more than one legacy substreams is open, we only send the `Status` message on the first one, and only expect one `Status` message to be sent by the remote on all substreams combined.
- Since https://github.com/paritytech/substrate/pull/6377, it is no longer illegal to send multiple `Status` messages. This PR is deployed as part of Polkadot 0.8.11.
- https://github.com/paritytech/substrate/pull/5938 introduces two changes: it sends a `Status` message on all newly-opened legacy substreams, and also expects a `Status` message to be received on all newly-opened legacy substreams.
(I also invite you to look at the description of #6377 for more context)
Unfortunately #5938 is a …
=> Send Status message on all newly-opened legacy substreams

frame/evm/src/lib.rs
Exposes the EVM errors directly from the pallet_evm to make error handling easier in external pallets (Ex: frontier)
=> Make evm errors public

Cargo.lock, test-utils/client/Cargo.toml, test-utils/client/src/lib.rs
Follow up of #6555 
As suggested by @bkchr, it would have been nice to have:
1. [x] a Result for when the `send_transaction()` call failed
2. [x] a nice documented struct that describes what are the return values
=>  Improved send_transaction helper to return an error in case of error 

frame/system/src/extensions/check_mortality.rs
Fixes: https://github.com/paritytech/substrate/issues/6483
=> Rename `CheckEra` to `CheckMortality`

client/authority-discovery/src/addr_cache.rs, client/authority-discovery/src/lib.rs
The authority discovery reports to Prometheus the size of the priority group of the peerset. But since this is capped to 10, it always reports 10.
I would like to make sure that we discovery all or almost all validators. This adds a new metric for this purpose.
=> Add an authority_discovery_known_authorities_count metric

bin/node/bench/src/main.rs, client/cli/src/config.rs, client/cli/src/logger.rs
Instead of requiring the `LogRotationOpt`, it now requires an
`Option<LogRotationOpt>`. This makes it much more easy to use the
interface when someone isn't interested on the `LogRotationOpt`'s
polkadot-companion: https://github.com/paritytech/polkadot/pull/1386
=> Make `init_logging` more easily usable

client/service/Cargo.toml, client/service/src/metrics.rs
`sysinfo` and `netstat2` cause compilation problems on `ios` https://github.com/sunshine-protocol/sunshine-identity-ui/issues/1
so this PR adds `not(target_os = "ios")` in the places where the same is already done for `android`
=> add ios to cfg gates in client/service

primitives/core/src/crypto.rs
We are ChainX developers(https://github.com/chainx-org/ChainX) and we launch our mainnet at 05.25.2019. At that time, Substrate have not provide a way to set ss58 version for chain. Thus we just follow the docs about address version, and choose 44 as our mainnet ss58 version. We forked substrate to set 42 to 44 directly for our chain. 
Later,  at 01.29.2020, the pr https://github.com/paritytech/substrate/pull/4764 from the team SCS(https://github.com/scs/substraTEE-node) which have done a request to set 44 as their blockchain address type.
Now, we are developing ChainX to update to substrate 2.0, therefore we connect the SCS team to discuss whether they could allow us to use 44, and they change to another address type.
They agree this proposal, and choose 13 as their ss58 address type, so …
=> change ss58 format for SubstraTEE from 44 to 13 and add ChainX

client/service/src/lib.rs
After https://github.com/paritytech/substrate/pull/6533, this duration no longer represents how long it took to poll the networking worker, but the time it took to wait plus poll. In other words, this log entry is misleading.
The information about how much time it takes to poll tasks is already tracked in Prometheus, so this warning doesn't bring much anymore anyway.
=> Remove warning about networking taking a lot of time

primitives/core/src/crypto.rs
Allows cli tools built on top of substrate to directly parse accountIds, or conveniently use it with `structopt` that expects any type that has `FromStr`. Alternatively you can create a wrapper type.
=> Add FromStr for AccountId32

frame/assets/src/lib.rs, frame/atomic-swap/src/tests.rs, frame/benchmarking/src/tests.rs, frame/evm/src/tests.rs, frame/generic-asset/src/mock.rs, frame/identity/src/lib.rs, frame/membership/src/lib.rs, frame/nicks/src/lib.rs, frame/recovery/src/mock.rs, frame/scheduler/src/lib.rs, frame/scored-pool/src/mock.rs, frame/society/src/mock.rs, frame/sudo/src/mock.rs, frame/vesting/src/lib.rs
All traced back to pallets/example. 
I find them to be only noise, not really valuable, and making _actually relevant_ comments, if any, harder to spot.
=> Remove duplicate comments about testing setup.

frame/executive/src/lib.rs, primitives/io/src/batch_verifier.rs, primitives/io/src/lib.rs
It was a mistake to use the `*_verify` methods for signature batching.
This pr move the signature batching into their own functions. This is
required, because otherwise transaction signature verification infers
with other signature verifications.
This pr also temporarily disables signature batching. The functionality
stays, but we need to make sure that all nodes have the new runtime
interface, before we can bring back signature batching.
Fixes: #5554 https://github.com/paritytech/substrate/issues/6585
=> Make signature batching use specialized methods

client/chain-spec/derive/src/impls.rs, client/chain-spec/src/lib.rs
We should check that `serde` is present when using
`sc-chains-spec-derive`, because we require this for the generated
struct. This also switches the generated `derive` instruction to import
`Serialize`/`Deserialize` by path to not require the user to import
these derive macros.
=> Check that `serde` is present in `sc-chain-spec-derive`

.gitlab-ci.yml
a common set of prometheus alerting rules has been added to this repository. [they](https://github.com/paritytech/substrate/pull/6095) will be deployed by the ci with this pr on commits to master and changes on that file.
(old kubernetes deployments have been removed - they were not in use anymore for a long time)
ref https://github.com/paritytech/devops/issues/558
=> ci: add deployment of polkadot prometheus rules

client/network/src/protocol.rs, client/network/src/protocol/generic_proto/behaviour.rs, client/network/src/protocol/generic_proto/handler/group.rs, client/network/src/protocol/generic_proto/handler/legacy.rs, client/network/src/protocol/generic_proto/upgrade/legacy.rs
At the moment, if we send messages on the legacy substream at a faster rate than the remote can process, we generate a `Clogged` event containing the messages (as opaque bytes) that were pending in the buffer.
This `Clogged` event is propagated through the layers until `protocol.rs`, where the messages are decoded and logged for the purpose of understanding why the clogging happened.
Considering that these `Clogged` events have only ever been emitted for a very short period of time around one to two years ago, and considering that the legacy substream has now become almost unused, I'm proposing to remove this `Clogged` event in order to simplify the code.
If we indeed send messages on the legacy substream at a faster than that the remote can process (which is extremely unlikely to happen …
=> Remove legacy Clogged event

frame/babe/src/benchmarking.rs, primitives/finality-grandpa/src/lib.rs
* Unused import in no_std builds
* Global attribute in non-root of a crate
=> Fix two minor warnings

.maintain/gitlab/check_polkadot_companion_status.sh
Logic around checking for review approvals was faulty. This changes the logic such that:
- If there are any 'CHANGES_REQUESTED' reviews for the *most recent* commit to the companion PR, we fail
- After this, check for *any* approvals and fail if there are none
- Fall through to 'APPROVED' (no changes here)
=> [CI] Fix check_polkadot_companion_status.sh

Cargo.lock, client/offchain/Cargo.toml
To get rid off duplicate dependencies in polkadot:
```
Checking webpki-roots v0.19.0
Checking webpki-roots v0.18.0
Checking rustls v0.18.0
Checking rustls v0.17.0
```
=> sc-offchain: upgrade hyper-rustls to 0.18

frame/benchmarking/src/analysis.rs, frame/benchmarking/src/lib.rs, frame/benchmarking/src/tests.rs, utils/frame/benchmarking-cli/src/command.rs, utils/frame/benchmarking-cli/src/writer.rs
This PR updates the benchmark pipeline to support constant time benchmarks that do not have component values to iterate over.
To support this we basically needed to remove the components loop when running benchmarks or tests.
Then for analysis, we fallback to using a pure median value instead of median slopes analysis, and a pure mean value instead of least squares analysis.
Beyond these changes, I have also made the benchmarking pipeline a bit more robust to panics caused by accessing empty vecs.
=> Support Component-less Runtime Benchmarks

client/service/src/builder.rs, client/telemetry/src/lib.rs
While developing on cumulus we usually never use telemetry so it never failed before. But with the token-transfer parachain we are currently deploying we did try to enable telemetry for the parachain. This resulted in:
```
====================
Version: 0.1.0-unknown-commit-x86_64-linux-gnu
0: sp_panic_handler::set::{{closure}}
1: std::panicking::rust_panic_with_hook
at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:515
2: rust_begin_unwind
at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:419
3: core::panicking::panic_fmt
at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/panicking.rs:111
4: core::option::expect_failed
at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/option.rs:1260
5: …
```
=> The telemetry should not be initialized if no telemetry has been provided

frame/staking/src/lib.rs
`ErasStakersClipped` containes nominations, but not necessarily sorted. This fix the confusing comment
=> Staking: fix inline comment.

.maintain/monitoring/grafana-dashboards/substrate-networking.json
The changes are already on Parity's Grafana server. This PR just updates the dashboard in the repo.
A list of changes:
- Added the `Percentage of peers for which we have more than one connection open` and `Number of authorities discovered by authority-discovery` graphs.
- We're now hiding the legends when they only show the node name. It's not useful for the legend to indicate that for example node X is in blue when you have 10 other lines with the same blue colour. Hovering the line also shows the node name.
- Number of entries in Kademlia k-buckets now shown over time and for each individual node.
- Replace the average/min/max system for Kademlia records with a time frame and one line per node.
- Rather than number of ongoing queries, now showing the authority-discovery success rate …
=> Update the substrate-networking Grafana dashboard with latest changes

client/service/src/metrics.rs
Adjust system related metric HELP texts, most notably:
```diff
cpu_usage_percentage: register(Gauge::new(
-          "cpu_usage_percentage", "Node CPU usage",
+          "cpu_usage_percentage", "Process CPU usage, percentage per core summed over all cores",
)?, registry)?,
```
With the above in mind the [`HighCPUUsage`](https://github.com/paritytech/substrate/blob/master/.maintain/monitoring/alerting-rules/alerting-rules.yaml#L9) alert is useless as it does not include the number of cores the machine has. I will tackle that in a follow up pull-request.
=> client/service/metrics: Rework metric HELP texts

.maintain/monitoring/alerting-rules/alerting-rule-tests.yaml, .maintain/monitoring/alerting-rules/alerting-rules.yaml
The `HighCPUUsage` alert is based on the `cpu_usage_percentage` metric.
Instead of exposing the overall CPU usage in percent, the metric exposes
the per core usage summed over all cores.
This commit removes the alert for two reasons:
1. Substrate itself does not expose the core count and thus one can not
alert based on the `cpu_usage_percentage` metric.
2. Alerting based on CPU usage is generic and not specific to Substrate
or Blockchains. Thus any CPU usage alert suffice.
---
For example the following alerting rule leveraging the node exporter would
do. It considers the overall system usage which is fine in our case as
processes don't share hosts.
```yaml
alert: HostHighCpuLoad
expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
for: 5m
labels: …
```
=> .maintain/monitoring/alerting-rules: Remove HighCPUUsage alert

bin/node/runtime/src/lib.rs, frame/society/src/lib.rs, frame/support/src/traits.rs, frame/treasury/src/lib.rs, frame/treasury/src/tests.rs, primitives/arithmetic/src/per_things.rs
Also, Society is a imbalance handler.
Polkadot companion: https://github.com/paritytech/polkadot/pull/1421
=> Treasury burning can be directed

Cargo.lock, client/transaction-pool/graph/Cargo.toml, client/transaction-pool/graph/src/pool.rs, client/transaction-pool/graph/src/validated_pool.rs, primitives/transaction-pool/Cargo.toml, primitives/transaction-pool/src/pool.rs
This changes the txpool import notification stream from unbounded mpsc channel to bounded ones.
=> Switch to bounded mpsc for txpool import notification stream

Cargo.lock, bin/node-template/runtime/src/lib.rs, bin/node/cli/src/service.rs, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs, bin/node/testing/src/keyring.rs, bin/utils/subkey/src/main.rs, client/finality-grandpa/src/environment.rs, client/finality-grandpa/src/tests.rs, frame/grandpa/Cargo.toml, frame/grandpa/src/benchmarking.rs, frame/grandpa/src/equivocation.rs, frame/grandpa/src/lib.rs, frame/grandpa/src/mock.rs, frame/grandpa/src/tests.rs, frame/offences/benchmarking/src/lib.rs, primitives/finality-grandpa/src/lib.rs, test-utils/runtime/src/lib.rs
This PR changes the GRANDPA equivocation reporting code to instead report using unsigned extrinsics (similar to what was done in #6362). The extrinsics are not broadcast onto the network and are only available for inclusion locally by block authors. Validation of the equivocation report is no longer done in a signed extension and instead the full validation is performed as part of the runtime method (i.e. `report_equivocation`) which was updated with a proper weight. Additionally a `ValidateUnsigned` will check for and reject duplicate equivocation reports (common assuming most validators will observe equivocations).
The advantage of this approach is that we perform all validation on the runtime method and assign it a proper weight, while guaranteeing that equivocation reporting works out …
=> grandpa: report equivocations with unsigned extrinsics

bin/node/cli/tests/version.rs, utils/build-script-utils/src/version.rs
While building cumulus in a container I realized that if the .git is not available, unknown-commit is used but then the version is a bit weird if I wanted to parse it. The number of hypens should stay the same.
```
0.1.0-unknown-commit-x86_64-linux-gnu
```
Normally:
```
0.1.0-c7084b9-x86_64-linux-gnu
```
An underscore would be ok too but I think just "unkown" is fine.
=> Tiny change: change unknown-commit to unknown to make parsing easier

Cargo.lock, client/service/Cargo.toml
bumps sysinfo so it compiles on iOS (done by shekohex in this PR https://github.com/GuillaumeGomez/sysinfo/pull/343 s.t. lowest version supported is `0.14.11` -- I can bump it down to this but it compiles for me with the latest version `0.14.3`)
=> bump sysinfo for ios

frame/support/src/dispatch.rs, frame/transaction-payment/Cargo.toml, frame/transaction-payment/src/lib.rs
This integrity test was living in in the `node-runtime` tests, which does not make sense, because it will not be applied to any of the chains built with substrate. 
https://github.com/paritytech/substrate/blob/56cf04f289f9cd5e8bb96fe5bd23a923e21acf1c/bin/node/runtime/src/impls.rs#L139-L147
This is the first usage of `integrity_test`, And I really couldn't think of any other use case. I've made an issue (https://github.com/paritytech/substrate/issues/6632) about the limitations here. 
This test is quite important, so I prefer keeping it, but I still think this (creating TestExt inside the module) is quite unergonomic and could be improved later.
=> Fix tx-payment integrity-test

.maintain/gitlab/check_polkadot_companion_status.sh
https://gitlab.parity.io/parity/substrate/-/jobs/594134
=> fix check polkadot companion status check

Cargo.lock, primitives/core/Cargo.toml, primitives/core/src/ed25519.rs
`ed25519-dalek` v1.0.0-pre.3 and v1.0.0-pre.4 are incompatible with each other. Unfortunately, Cargo doesn't seem to respect the semver rules here and treats them as compatible. The most painless way to fix this is to just upgrade to `v1.0.0-pre.4`.
polkadot companion: https://github.com/paritytech/polkadot/pull/1427
=> Fix compilation problems due to ed25519-dalek 1.0.0-pre.4

Cargo.lock, bin/node/browser-testing/Cargo.toml, bin/utils/subkey/Cargo.toml, client/authority-discovery/Cargo.toml, client/network-gossip/Cargo.toml, client/network/Cargo.toml, client/network/test/Cargo.toml, client/peerset/Cargo.toml, client/telemetry/Cargo.toml, primitives/consensus/common/Cargo.toml
This libp2p upgrade begins the `libp2p-noise` upgrade process for spec-compliant handshake payloads (see https://github.com/libp2p/rust-libp2p/issues/1631). Other than the `libp2p-noise` upgrade (which comes with a `snow` upgrade), there are no noteworthy changes.
=> Update libp2p to 0.22.

frame/support/src/lib.rs, frame/support/src/storage/generator/double_map.rs, frame/support/src/storage/mod.rs
I was trying to use `try_mutate_exists` on a storage double map, but found it not supported.
The implementation shares same behavior with `try_mutate_exists` in `StorageMap`.
=> Add try_mutate_exists to StorageDoubleMap

client/network/src/protocol.rs
Since https://github.com/paritytech/substrate/pull/5760 (which was merged before the Polkadot release), nodes shouldn't emit any request on the legacy substream anymore, and since https://github.com/paritytech/substrate/pull/6411, the code to emit requests on the legacy substream has disappeared.
Consequently it should now be safe to remove the requests answering code as well.
But before doing so, I would like to make sure that we're not receiving requests anymore. If nodes were sending us requests and we stop answering them, we won't see anything wrong happening, and nodes will just redirect their request to a different node. If every node upgrades to a version that doesn't answer requests, then we're in a bad situation.
Therefore, here is a new metric Prometheus whose value I'd like to …
=> Add sync_legacy_requests_received metric

frame/staking/src/tests.rs, primitives/npos-elections/src/lib.rs, primitives/npos-elections/src/tests.rs
Major part of https://github.com/paritytech/substrate/issues/4593. See the comments I added there today; Staking and elections-phragmen both prevent duplicate candidate and voters, so we didn't need to treat them in the underlying npos-elections layer yet and the above issue is open to grab. Nonetheless, we totally ignored **duplicate votes**, which is totally valid and causes confusion in the npos-election algorithms. 
I haven't spent much time investigating the impact of the bug and immediately prepared the patch, nonetheless:
1. Luckily it seems like _it didn't break the offchain-phragmen pipeline in any way_, and all the submissions submitted to polkadot by validators have been valid.
2. This _does corrupt the election result_, so the results of the election, with this bug, are …
=> Properly filter out duplicate voters in elections.

frame/atomic-swap/src/lib.rs, frame/atomic-swap/src/tests.rs
Instead of requiring `T: Trait` in `BalanceSwapAction`, we directly
depend on `AccountId`. This fixes a compilation error on wasm, where
`Runtime` does not implement `Debug`, but `BalanceSwapAction` required it.
=> pallet-swap-action: Change `BalanceSwapAction` signature

frame/im-online/src/mock.rs, frame/support/src/metadata.rs, frame/support/src/origin.rs
Follow up of #6500 
We have some tests using `impl_outer_origin` directly and this prevents us from removing all `use frame_system as system;`
polkadot companion: https://github.com/paritytech/polkadot/pull/1444
=> make impl_outer_origin default to use frame_system

bin/node-template/README.md
Removing references to Playground staging resources per conversation with @jeluard.
=> Removing staging resources from node template README

Cargo.lock, client/service/Cargo.toml, client/service/src/metrics.rs
Following https://github.com/GuillaumeGomez/sysinfo/issues/352 , this upgrades to the freshly released version 0.14.15 . It also adds some smaller helpers to ensure we only fetch the system resources we need. This fixes https://github.com/paritytech/polkadot/issues/1434 
On Linux through `sysinfo::System` we are leaking file-handlers  to `/proc/[pid]/task/[t]/stats`. This hasn't been shown up previously because we had mostly long-living threads. This recently changed we have quite a few more short lived threads – unfortunately `sysinfo` isn't cleaning up the file handlers to their stats properly. The latest version of sysinfo fixes that bug.
=> Update to latest sysinfo prevents leaking fd-handlers

Cargo.lock, utils/browser/Cargo.toml
Fix https://github.com/paritytech/substrate/issues/6677
The fact that `clear_on_drop` has disappeared from the `Cargo.lock` is the proof that this was no longer useful.
=> Remove clear_on_drop from browser util crate

primitives/core/src/crypto.rs
Add 4 as address type of ss58 for Katal Chain
=> Add 4 as address type of ss58 for Katal Chain

frame/evm/src/backend.rs, frame/evm/src/lib.rs, frame/evm/src/tests.rs
Previously the EVM storage and Substrate storage must be separated. Balances are collected in a center EVM account holding, and then the EVM handles all inner workings by itself. This PR changes the design to use Substrate system storage for EVM nonce and balances.
The previous deposit/withdraw/call routines are now changed to a `EnsureAddressOrigin` based permissioned withdraw/call routine. Runtime can define their custom permissions for who is allowed to withdraw or issue calls on behalf of an EVM address.
* If the Substrate runtime directly uses `H160` as account id, then it can use `EnsureAddressSame` -- only allowing the same Substrate address to operate on an EVM address.
* If the Substrate runtime uses `AccountId32`, then it can use `EnsureAddressTruncated` -- allowing a particular …
=> Support using system storage directly for EVM balance and nonce

docs/CHANGELOG.md
Versions are already set properly, this only adds the changelog. Test going here, release tag going onto `master` after merge.
=> Prepping for release of rc5 – River Dolphin

client/finality-grandpa/src/authorities.rs, frame/grandpa/src/benchmarking.rs, frame/grandpa/src/lib.rs, frame/grandpa/src/mock.rs, frame/grandpa/src/tests.rs
This PR adds an extrinsic `note_stalled` to the GRANDPA pallet that will note to the module that the finality gadget has stalled at a given block. This will trigger a forced authority set change at the beginning of the next session which will be enacted after the given delay in number blocks (this is necessary to guarantee that it is deep enough not to be re-orged).
I re-read all the code related to forced changes (since it's never been used live) and fixed a bug in the client (related to pruning of forced changes after we finalize a standard change), and two on the grandpa pallet related to how we deal with scheduling changes on session rotation. Tested this on a local testnet and was successful, the plan is to run this on Westend to resurrect a stalled set (offline validators).
=> grandpa: allow noting that the set has stalled

.maintain/monitoring/grafana-dashboards/substrate-service-tasks.json
Exports the Grafana dashboard that we use to monitor the CPU-related concerns of the node.
Screenshots:
=> Add the Substrate Service Tasks dashboard

Cargo.lock, primitives/utils/Cargo.toml, utils/prometheus/Cargo.toml
This PR bumps prometheus to 0.9 and removes `protobuf` features used by default.
From https://github.com/tikv/rust-prometheus/issues/210:
> The protobuf crate is huge when compiled (a bit less than 400KB) and it bloats the binaries that are using rust-prometheus without the protobuf format.
> Prometheus > 2.0 does not support Protobuf at all anymore.
this feature is only useful for legacy versions of prometheus (< 2.0)
=> prometheus: don't use protobuf feature

bin/node-template/node/src/service.rs
See https://github.com/paritytech/substrate/pull/6557#issuecomment-663875214.
=> Revert change to which node-template Block type is used.

Cargo.lock, bin/node-template/README.md, bin/node-template/node/Cargo.toml, bin/node-template/runtime/Cargo.toml
Backport changes made by @c410-f3r
https://github.com/substrate-developer-hub/substrate-node-template/pull/66
=> Remove unused node template deps

client/network/src/service.rs
Rename `NetworkWorker::from_worker` to `NetworkWorker::from_service` as
it is a channel from the `NetworkService` to the `NetworkWorker`.
=> client/network: Adjust wording

client/authority-discovery/src/addr_cache.rs, client/network/src/protocol/generic_proto/upgrade/legacy.rs, frame/collective/src/lib.rs, frame/contracts/src/wasm/runtime.rs, frame/staking/src/lib.rs, frame/support/src/traits.rs, primitives/api/proc-macro/src/decl_runtime_apis.rs, primitives/arithmetic/src/lib.rs, primitives/npos-elections/src/lib.rs, primitives/npos-elections/src/mock.rs, primitives/state-machine/src/changes_trie/build.rs, primitives/trie/src/lib.rs
There's really no need to be using unstable sorts as Rust's default is actually pretty fast.
=> Cleanup our sort usage

Cargo.lock, bin/node-template/node/src/service.rs, bin/node/cli/src/service.rs, client/consensus/aura/src/lib.rs, client/consensus/babe/src/lib.rs, primitives/consensus/common/Cargo.toml, primitives/consensus/common/src/import_queue.rs, primitives/consensus/common/src/lib.rs
I noticed that `AuraImportQueue` and `BabeImportQueue` have the exact same type definition of `BasicQueue<Block, sp_api::TransactionFor<Client, Block>>`, and that `sc_consensus_manual_seal::import_queue` usually (always?) returns this type as well, so it made sense to have an alias for this and remove the implementation-specific aliases.
polkadot companion: https://github.com/paritytech/polkadot/pull/1499
=> Add a `DefaultQueue` type alias to remove the need to use `sp_api::TransactionFor`

client/network/src/service/tests.rs
cc https://github.com/paritytech/substrate/issues/6766
This does not make the problem go away, but it will make the CI happy.
The issue should stay open after this PR is merged.
=> Ignore flaky test

Cargo.lock, frame/evm/Cargo.toml, frame/evm/src/lib.rs, frame/evm/src/precompiles.rs
This adds builtin support for the four basic Ethereum precompiles -- ecrecover, identity, ripemd160 and sha256.
=> pallet-evm: add builtin support for the four basic Ethereum precompiles

client/cli/src/runner.rs
I just noticed this error while working on the task manager
=> Fix graceful shutdown skipped if future ends with error

client/network/src/lib.rs, client/network/src/protocol/generic_proto/handler/notif_in.rs, client/network/src/protocol/generic_proto/upgrade/notifications.rs
This PR slightly modifies the behaviour of notification substreams.
The current behaviour is:
- Node A opens a substream. Node A sends a handshake message.
- Node B either refuses the substream by immediately closing it, or accepts by sending back its own handshake message.
- After accepting the substream, node B closes its writing side.
- Node A can then send messages.
This PR removes step 3, where B closes its writing side.
The motivation behind this PR is that in the future nodes would signal that they no longer want a substream by closing their writing side.
In order for this to work, they should not immediately close it.
The mechanism where node A detects when node B closes its writing side and closes as well in return can't be implemented before we first deploy this PR, as otherwise …
=> Don't close inbound notifications substreams immediately

bin/node/rpc/src/lib.rs, bin/node/runtime/src/lib.rs, frame/transaction-payment/rpc/runtime-api/src/lib.rs, frame/transaction-payment/rpc/src/lib.rs
The transaction payment runtime api used its own extrinsic generic
parameter. This is wrong, because this resulted in using always the
native extrinsic. If there was a runtime upgrade that changed the
extrinsic in some way, it would result in the api breaking. The correct
way is to use the `Extrinsic` from the `Block` parameter. This is on the
node side the opaque extrinsic and on the runtime side the real extrinsic.
polkadot companion: https://github.com/paritytech/polkadot/pull/1519
=> Fix transaction payment runtime api

client/network/src/service.rs
The `sub_libp2p_kademlia_query_duration` metric only has the dimension
`type` not `protocol`.
=> client/network: Fix wrong metric help text

frame/contracts/fixtures/call_return_code.wat, frame/contracts/fixtures/caller_contract.wat, frame/contracts/fixtures/destroy_and_transfer.wat, frame/contracts/fixtures/drain.wat, frame/contracts/fixtures/instantiate_return_code.wat, frame/contracts/fixtures/ok_trap_revert.wat, frame/contracts/fixtures/self_destructing_constructor.wat, frame/contracts/fixtures/set_rent.wat, frame/contracts/fixtures/transfer_return_code.wat, frame/contracts/src/exec.rs, frame/contracts/src/gas.rs, frame/contracts/src/lib.rs, frame/contracts/src/storage.rs, frame/contracts/src/tests.rs, frame/contracts/src/wasm/mod.rs, frame/contracts/src/wasm/runtime.rs
This started out as a small PR that should only fix the problem of `ext_instantiate` and `ext_call` reporting `CalleeTrapped` for every error despite its docs saying that it should trap on most errors. However, after looking at the current state of error reporting I decided to to some improvement as I was touching these parts anyways.
We have no proper errors for the most common errors instead of just using `DispatchError::Other` which have its message stripped when displayed on polkadot js or block explorers.
In addition to that `ext_call` no longer allows calling plain accounts. Allowing this predates `ext_transfer`. Having `ext_call` silently not calling any code when calling plain accounts does not seem useful and rather dangerous.
`ext_tranfer` now can return codes again. Removing …
=> seal: Fix and improve error reporting

Cargo.lock, Process.json, frame/benchmarking/src/utils.rs, utils/frame/benchmarking-cli/Cargo.toml, utils/frame/benchmarking-cli/src/command.rs, utils/frame/benchmarking-cli/src/writer.rs
This PR updates the Benchmark Writer adding a number of features which should improve automation.
A benchmark may include components that do not end up effecting the weight of the function. We introduced "component-less" benchmarks, but in the case we want to keep the component in the benchmark to PROVE it does not need to be used, our benchmarking writer can now detect that the component is unused, and remove it from the function signature.
Example:
```
// WARNING! Some components were not used: ["z"]
fn as_multi_complete(s: u32, ) -> Weight {
(65230000 as Weight)
.saturating_add((70000 as Weight).saturating_mul(s as Weight))
.saturating_add(DbWeight::get().reads(3 as Weight))
.saturating_add(DbWeight::get().writes(3 as Weight))
}
```
There are times where a component has no effect on a …
=> Improve Benchmark Writer: Remove Unused Components, Remove Multiply by Zero, Files Split by Pallet

bin/node/bench/src/core.rs, bin/node/bench/src/txpool.rs, bin/node/browser-testing/src/lib.rs, client/proposer-metrics/src/lib.rs, client/service/test/src/client/light.rs, frame/contracts/src/benchmarking.rs, frame/staking/src/tests.rs, primitives/consensus/common/src/metrics.rs, primitives/core/src/sr25519.rs, primitives/runtime/src/offchain/storage_lock.rs, utils/fork-tree/src/lib.rs
Some spaces seem to have crept into the codebase, and for the sake of consistency it seemed like a good idea to convert them.
=> Convert rogue spaces to tabs

primitives/core/src/crypto.rs
This PR adds a new ss58 address `28` for [Subsocial network](http://subsocial.network/) in this file:
https://github.com/paritytech/substrate/blob/293bcd6059f1e4e3dd95aa64989dadef4234222d/primitives/core/src/crypto.rs#L414
=> Add ss58 address for Subsocial network

frame/support/src/lib.rs, frame/support/src/storage/generator/double_map.rs, frame/support/src/storage/mod.rs
Follow up of #6694 . Just noticed `mutate_exists` is not supported in `StorageDoubleMap` either.
=> Add mutate_exists to StorageDoubleMap.

bin/node/runtime/src/weights/pallet_proxy.rs, frame/proxy/src/benchmarking.rs, frame/proxy/src/default_weight.rs, frame/proxy/src/lib.rs
This PR updates the benchmarks and weights for delayed proxy in order to include announcements into the weight formula as a parameter
=> Update Benchmarks and Weights for Delayed Proxy

client/network/src/service.rs
Fix #6241 
At the moment, `set_priority_group` calls `parse_addr`, which in turn prints a warning on stderr if the `PeerId` is using the legacy `Qm...` format.
This PR "inlines" the body of `parse_addr` in `set_priority_group` to avoid this issue.
=> Fix warning being printed by authority-discovery

frame/balances/src/default_weight.rs, frame/balances/src/lib.rs
This sets the "default" balances weight to the weight we have measured when benchmarking the Substrate node using our benchmarking machine.
This means by default, if a user does not specify their own weights, they will use our weights which are safe in the context of how Substrate is configured by default.
This is basically backwards compatible with any existing substrate chains who already use our default weights by using our pallets.
This follows the pattern we will be using moving forward
=> Better default balances weights

frame/support/procedural/src/storage/genesis_config/mod.rs, frame/support/procedural/src/storage/instance_trait.rs, frame/support/procedural/src/storage/parse.rs, frame/support/procedural/src/storage/storage_struct.rs, frame/support/src/traits.rs, frame/support/test/tests/final_keys.rs, frame/support/test/tests/instance.rs
Because it is confusing and no longer necessary in any way, we can remove the declaration of instance trait in decl_storage.
DONE:
* decl_storage still generate Instance implementation for structs: Instance0, Instance1, ..., DefaultInstance and __InherentHiddenInstance.
* frame-support::traits::Instance is still reexported from inside the module: `pub use frame_support::traits::Instance as Instance;` to avoid any breaking change
* the Instance trait used in macro must be `Instance` (before it could be named whatever user wanted), this is to ensure people don't get confused about where it comes from. (if user use InstantiableThing for trait name, then an error message is returned).
Instance stuff are still not perfect but I hope it improves on the current situation.
To summarize the …
=> Remove generation of instance trait by decl_storage.

Cargo.lock, client/service/Cargo.toml, client/service/src/metrics.rs
Follow-up to #6805.
We will no longer be collecting system/process metrics, instead anyone that needs these metrics can collect them externally with software like: [node_exporter](https://github.com/prometheus/node_exporter), [process-exporter](https://github.com/ncabatoff/process-exporter) or [cadvisor](https://github.com/google/cadvisor). This makes our life easier as we don't have to deal with platform-specific code.
Closes #6806.
=> service: remove collection of system/process metrics

client/network/src/protocol/generic_proto/handler/group.rs
Fixes a regression introduced in https://github.com/paritytech/substrate/pull/6692
This `continue` was misplaced.
If a notifications substream isn't open, before this PR we would silently discard the message, while after this PR we're sending it on the legacy substream as intended.
This manifests itself in three situations:
- If a node doesn't support notifications substreams (unlikely nowadays).
- If the legacy substream is opened well in advance compared to the notifications substream.
- If two nodes connect before `register_notifications_protocol` has been called.
Points 2 and 3 typically happens only on a local testnet, and is how this issue got detected.
=> Fix legacy substream fallback not working

client/finality-grandpa/Cargo.toml, client/finality-grandpa/src/environment.rs, client/finality-grandpa/src/tests.rs
Guard against overwriting the GRANDPA voter state of a given current round. Given the invariants of the GRANDPA module this should be safe and never get overwritten (rounds are always started in-order) but we might as well be safe.
=> grandpa: never overwrite current rounds voter state

Cargo.lock, bin/node-template/node/Cargo.toml, bin/node-template/node/src/lib.rs, bin/node-template/node/src/main.rs, bin/node-template/node/src/rpc.rs, bin/node-template/node/src/service.rs, bin/node-template/runtime/Cargo.toml, bin/node-template/runtime/src/lib.rs
Allows for and gives a concrete example on how to implement custom RPCs (with its implementation in the template's service.rs file). I've tried to keep everything minimal, but since I don't understand everything I can almost guarantee that there's room for improvements- not sure if allowed but I added 2 TODO's stating where these can be added. Note that the builder is only implemented for the full client. I've fully tested this and it works, perhaps if needed- could somebody point me towards some documentation which shows me how to write test-cases for RPCs? Thanks and sorry if I made a mess.
=> Add RPC Builder to Substrate Node Template

bin/node-template/node/src/service.rs, bin/node/cli/src/service.rs, client/service/src/builder.rs, client/service/src/lib.rs
See the code comment in the diff and https://github.com/paritytech/substrate/issues/6827 for context.
This PR adds a new `NetworkStarter` struct, and the user must call `NetworkStarter::start_network` in order to complete initialization.
polkadot companion: https://github.com/paritytech/polkadot/pull/1547
=> Delay network startup to after complete initialization

bin/node-template/node/src/chain_spec.rs, bin/node-template/runtime/Cargo.toml, bin/node-template/runtime/src/lib.rs
This PR removes the alias `frame_system` -> `system` from the node template runtime.
see also: #3295, #6500
=> De-alias frame_system in node template runtime

client/service/src/task_manager/mod.rs, client/service/src/task_manager/tests.rs, docs/CHANGELOG.md
Register another TaskManager to terminate and gracefully shutdown when the parent terminates and gracefully shutdown. Also ends the parent `future()` if a child's essential task fails. 
This is related to https://github.com/paritytech/cumulus/issues/164
=> Allow task manager to have children

client/finality-grandpa/src/authorities.rs
This PR fixes an issue with GRANDPA forced authority set changes where changes with no delay would fail to be enacted.
=> grandpa: fix enacting forced changes with no delay

client/service/src/task_manager/mod.rs, client/service/src/task_manager/tests.rs
=> Renamed add_children to add_child since it adds only one child

test-utils/client/src/lib.rs
After checking the logs of the integration test on cumulus I realized that there was an issue but the block counting did manage to count nevertheless. This will fix that latter issue (and break the integration test as it should :grin: )
=> Fix `wait_for_blocks` counting blocks that didn't go through consensus

Cargo.lock, bin/node/browser-testing/Cargo.toml, bin/node/cli/browser-demo/README.md, bin/node/cli/browser-demo/build.sh
This PR updates the `wasm-bindgen` dependency in the browser demo. It also adds a note to the readme that a specific version is required.
Open question: Is it necessary to pin a version at all?
Solves #6859
=> Update pinned wasm-bindgen dependency

frame/staking/src/benchmarking.rs, frame/staking/src/lib.rs
This is just a relic of the testing days or even earlier. There is no reason to enforce 4 here; The default is 0, which is then translated to `.max(1)` in the code, meaning that the logical minimum is 1, which is much more sensible than just 4 for no apparent reason. 
Actually, both polkadot and kusama now have 4 in their storage for this value, which should also be fixed, but I want to do that as https://github.com/paritytech/substrate/issues/2494 which needs more research and consideration.
=> Remove minimum_validator_count stale const

Cargo.lock, bin/node/executor/tests/basic.rs, frame/contracts/COMPLEXITY.md, frame/contracts/Cargo.toml, frame/contracts/fixtures/call_return_code.wat, frame/contracts/fixtures/caller_contract.wat, frame/contracts/fixtures/check_default_rent_allowance.wat, frame/contracts/fixtures/crypto_hashes.wat, frame/contracts/fixtures/destroy_and_transfer.wat, frame/contracts/fixtures/drain.wat, frame/contracts/fixtures/instantiate_return_code.wat, frame/contracts/fixtures/ok_trap_revert.wat, frame/contracts/fixtures/restoration.wat, frame/contracts/fixtures/return_from_start_fn.wat, frame/contracts/fixtures/return_with_data.wat, frame/contracts/fixtures/self_destruct.wat, frame/contracts/fixtures/self_destructing_constructor.wat, frame/contracts/fixtures/set_empty_storage.wat, frame/contracts/fixtures/set_rent.wat, frame/contracts/fixtures/storage_size.wat, frame/contracts/fixtures/transfer_return_code.wat, frame/contracts/src/benchmarking.rs, frame/contracts/src/exec.rs, frame/contracts/src/lib.rs, frame/contracts/src/tests.rs, frame/contracts/src/wasm/env_def/macros.rs, frame/contracts/src/wasm/mod.rs, frame/contracts/src/wasm/prepare.rs, frame/contracts/src/wasm/runtime.rs
The word Ext is a overloaded term in the context of substrate. It usually is a trait which abstracts away access to external resources usually in order to mock them away for the purpose of tests. The contract module has its own `Ext` trait in addition the the substrate `Ext` which makes things even more confusing.
In order to differentiate the contract callable functions more clearly from this `Ext` concept we rename them to use the "seal_" prefix instead.
This should change no behaviour at all. This is a pure renaming commit. Contract generation (ink!, solang) need to apply this rename as well.
Currently, the wasm module name for all imported functions is the generic default value `env`. This commit changes this prefix to `seal0`. Later, that module name might be used for versioning. …
=> seal: Change prefix and module name from "ext_" to "seal_" for contract callable functions

client/finality-grandpa/src/communication/gossip.rs, client/finality-grandpa/src/import.rs
Running grandpa with trace logging generates a lot of data, mainly due to this: https://github.com/paritytech/finality-grandpa/blob/master/src/voter/voting_round.rs#L182
This PR changes some log statements, that are useful enough and don't happen that often, from `trace` to `debug`.
=> grandpa: change some logging from trace to debug

frame/staking/src/lib.rs
Closes https://github.com/paritytech/substrate/issues/4616
=> Fix wrong staking doc about transaction payment.

docs/CODE_OF_CONDUCT.md
The code of conduct needs to be in markdown in order to be recognized in the community page (https://github.com/paritytech/substrate/community).
I just copied it from polkadot which was already in markdown and is properly detected (https://github.com/paritytech/polkadot/community).
=> docs: convert code of conduct to markdown

primitives/core/src/crypto.rs
This is a trivial change. We reserve SS58 address id 30 for Phala Network.
=> Add Phala Network SS58 address type

primitives/consensus/common/src/import_queue/basic_queue.rs, primitives/consensus/common/src/import_queue/buffered_link.rs
cc https://github.com/paritytech/substrate/issues/6871
Avoids a panic if the executor decides to drop the task.
=> Fuse the import queue receiver

frame/evm/src/lib.rs, frame/evm/src/tests.rs
=> pallet-evm: fix wrong logic in mutate_account_basic

primitives/core/src/hexdisplay.rs, primitives/core/src/lib.rs
Actually I use this quite often when debugging some WASM bugs and there
is no harm in enabling it by default. Before I just always copied it
everytime I needed it.
=> Make `HexDisplay` useable in `no_std`

.maintain/gitlab/generate_changelog.sh
This PR appends PRs that include runtime migrations to a new category "Runtime Migrations" in the release notes.
related to #6482
=> add runtime migrations to release notes/changelog

Cargo.lock, frame/staking/src/lib.rs, frame/staking/src/mock.rs, frame/staking/src/tests.rs, primitives/npos-elections/compact/src/assignment.rs, primitives/npos-elections/compact/src/codec.rs, primitives/npos-elections/compact/src/lib.rs, primitives/npos-elections/src/mock.rs
Follow up of https://github.com/paritytech/substrate/pull/6720 of and another part of https://github.com/paritytech/substrate/issues/6242, only introduces more renamed away from `phragmen` keyword, because it is soon becoming obsolete. 
For example we called some error in staking `PhragemnWrongError` whereas this error pertains to the `OffchainElection` submission process, which may or may not be `phragmen`. 
Totally insubstantial in terms of logic.
=> More renaming to move away from phragmen.

frame/evm/src/backend.rs, frame/evm/src/lib.rs
This PR only adds debug logs for the EVM frame, providing some information for easier troubleshooting.
Example of output:
```
2020-06-27 13:10:03.088 tokio-blocking-driver DEBUG evm  Execution Succeed(Returned) [source: 0x6be02d1d3665660d22ff9624b7be0551ee1ac91b, value: 0, gas_limit: 1048576, used_gas: 890864, actual_fee: 0]
2020-06-27 13:10:03.088 tokio-blocking-driver DEBUG evm  Updating state of 0x6be02d1d3665660d22ff9624b7be0551ee1ac91b [value: 123456122109135999863044, nonce: 10]
2020-06-27 13:10:03.089 tokio-blocking-driver DEBUG evm  Updating state of 0xdc552396caec809752fed0c5e23fd3983766e758 [value: 0, nonce: 1]
2020-06-27 13:10:03.089 tokio-blocking-driver DEBUG evm  Inserting code (3642 bytes) at 0xdc552396caec809752fed0c5e23fd3983766e758
2020-06-27 13:10:03.089 …
```
=> Crystalin add evm log

Cargo.lock, bin/node/browser-testing/Cargo.toml, bin/utils/subkey/Cargo.toml, client/authority-discovery/Cargo.toml, client/informant/src/display.rs, client/network-gossip/Cargo.toml, client/network/Cargo.toml, client/network/src/lib.rs, client/network/src/network_state.rs, client/network/src/service.rs, client/network/src/transport.rs, client/network/test/Cargo.toml, client/peerset/Cargo.toml, client/rpc/src/system/tests.rs, client/service/src/lib.rs, client/service/src/metrics.rs, client/telemetry/Cargo.toml, primitives/consensus/common/Cargo.toml
This PR updates substrate to `libp2p-0.23`. The [main changes](https://github.com/libp2p/rust-libp2p/blob/master/CHANGELOG.md#version-0230-2020-08-03) are the second step in noise spec-compatibility upgrades and simplified bandwidth tracking in libp2p itself.
Regarding the noise upgrade, so far I did not enable the legacy mode here, assuming that the `libp2p-0.22` upgrade is already widely deployed. If we wish to be conservative, I can enable sending of the legacy handshake payloads. Please let me know.
Regarding the bandwidth tracking, I tried to incorporate roughly the same moving-average calculation for inbound and outbound network traffic that was previously in libp2p, i.e. to maintain the existing functionality and APIs of `sc-network`.
=> Update to libp2p-0.23.

client/authority-discovery/src/worker.rs
Revert the accidental query interval change from every one minute back
to every 10 minutes.
Introduced by me in https://github.com/paritytech/substrate/pull/6760.
=> client/authority-discovery: Revert query interval change

frame/system/src/lib.rs
It makes no sense that `can_set_code` takes the origin for checking it.
Everybody reusing this function is only interested in the other checks
that are done by this function. The origin should be checked by every
dispatchable individually.
=> Don't take the origin in `can_set_code`

client/network/Cargo.toml, client/network/src/gossip.rs, client/network/src/gossip/tests.rs, client/network/src/lib.rs, client/network/src/service.rs
Provides the primitive that will make it possible to tackle https://github.com/paritytech/polkadot/issues/1453
Adds a new `gossip` module in `sc-network`, containing `DirectedGossip`.
The way it works is what is described [here](https://github.com/paritytech/substrate/blob/6384b85d0b25a99e01cfb62a81a551d27aa5c74b/client/network/src/service.rs#L680-L688).
Here's how you would plug it into Polkadot, regarding https://github.com/paritytech/polkadot/issues/1453:
- When the network bridge learns about a new connection, it builds a new `DirectedGossipPrototype`. This type doesn't have any template parameter.
- The [`NetworkBridgeEvent::PeerConnected`](https://github.com/paritytech/polkadot/blob/cc2d7afd128b259791139359067aa519eadbf205/node/subsystem/src/messages.rs#L140) enum variant should …
=> Add a DirectedGossip struct

bin/node-template/node/src/service.rs, bin/node/cli/src/service.rs, client/consensus/aura/src/lib.rs, client/consensus/babe/src/lib.rs, client/consensus/babe/src/tests.rs, client/consensus/pow/src/lib.rs, primitives/consensus/common/src/lib.rs
Right now, we call `check_inherents` for all past blocks, regardless of runtime version and authoring version. This may not always work. `check_inherents` relies on clients to provide `InherentData`. Some items in `InherentData` may have its format changed between authoring versions, and some inherent data providers may be removed or added. All of those may cause `check_inherents` to fail and the whole block import to fail. The failure prevents the node to function, and is unnecessary, because past authoring version blocks are usually finalized already, and thus it's authenticity has already been proven.
polkadot companion: https://github.com/paritytech/polkadot/pull/1564
=> babe, aura, pow: only call check_inherents if authoring version is compatible

primitives/consensus/common/src/lib.rs
Derive Clone for those structs so that they can be used in places where Clone is required.
=> Derive Clone for AlwaysCanAuthor, NeverCanAuthor, CanAuthorWithNativeVersion

client/network/src/service.rs, utils/prometheus/src/lib.rs, utils/prometheus/src/sourced.rs
This is a little follow-up to the suggestion in https://github.com/paritytech/substrate/pull/6870 for [custom metric collectors](https://github.com/paritytech/substrate/pull/6870/files#r469152168). This PR introduces what I dubbed "sourced" counters or gauges via a custom collector.  A sourced counter or gauge is a metric that obtains its values from an existing source, i.e. not from a `prometheus`-crate metric. It thus allows feeding existing counters and gauges into prometheus without having to duplicate them as `prometheus`-crate counters or gauges and without having to declare counters as gauges or making extra gymnastics with the counter API (i.e. get() + compute diff + `inc_by()` or `reset()` + `inc_by()` for every update). The first use-case are the bandwidth counters from libp2p. …
=> Add support for sourced metrics.

frame/support/procedural/src/storage/mod.rs
Import `IterableStorageMap` and `IterableStorageDoubleMap` automatically
by `decl_storage!` as the other storage traits.
=> Import `IterableStorage*` traits by `decl_storage!`

client/network/src/service.rs
At the moment, it's been diagnosed that these two `loop`s, especially the second, sometimes take a long time to be processed, up to more than a minute. During this processing, the rest of the polling isn't reached. In particular, the Prometheus metrics aren't updated, which in turn causes alarms to ring.
This change looks a bit like a hack, but I do believe that it is a fundamentally correct change (if you exclude the fact that the number of iterations is completely arbitrary), as we are kind of emulating something similar to `select`.
I've actually been willing to make this change for a while now, but have always tried to avoid doing so because reducing the load of the network worker was the primary way to fix this. However, it is indeed possible, even when everything is working …
=> Distribute the network future polling time more evenly

client/cli/src/commands/mod.rs, client/cli/src/commands/run_cmd.rs, client/cli/src/config.rs, client/cli/src/lib.rs, client/cli/src/params/network_params.rs
This moves default values used in the Substrate code base when
initializing a service into a common trait. Currently this trait only
contains listen ports, but this could be extended in the future.
Essentially this will make overriding these values much easier for
Cumulus, where we have 2 nodes running in one binary.
I'm open for any ideas on how to improve the name of the trait, because it sounds awful.
=> Combine default values used at initialization in a trait

client/consensus/babe/src/lib.rs
When importing BABE blocks we check for equivocations (i.e. another block at this slot from the same authority) and report it to the runtime if appropriate. An error here should not prevent us from importing the block if it is valid.
=> babe: handle error when checking/reporting equivocations

Cargo.lock, bin/node/runtime/src/lib.rs, client/db/src/bench.rs, frame/balances/src/benchmarking.rs, frame/benchmarking/Cargo.toml, frame/benchmarking/src/lib.rs, frame/benchmarking/src/tests.rs, frame/benchmarking/src/utils.rs, frame/collective/src/benchmarking.rs, frame/indices/src/benchmarking.rs, frame/proxy/src/benchmarking.rs, frame/staking/src/benchmarking.rs, frame/system/benchmarking/src/lib.rs, frame/timestamp/src/benchmarking.rs, frame/treasury/src/benchmarking.rs, frame/utility/src/benchmarking.rs, frame/vesting/src/benchmarking.rs, primitives/externalities/src/lib.rs, primitives/runtime-interface/Cargo.toml, primitives/runtime-interface/src/impls.rs, primitives/state-machine/src/backend.rs, primitives/state-machine/src/basic.rs, primitives/state-machine/src/ext.rs, primitives/state-machine/src/read_only.rs, primitives/storage/Cargo.toml, primitives/storage/src/lib.rs
polkadot companion: https://github.com/paritytech/polkadot/pull/1612
This PR introduces a new `get_whitelist` host function. In combination with `set_whitelist`, we are able to create helper functions `add_whitelist` and `remove_whitelist` which can be called from a benchmark to dynamically introduce or remove items from the benchmarking whitelist.
Additionally, this PR updates the format of the whitelist to use a new struct `TrackedStorageKey`:
```rust
pub struct TrackedStorageKey {
pub key: Vec<u8>,
pub has_been_read: bool,
pub has_been_written: bool,
}
```
Which includes the storage key, and whether this storage key has been read from or written to. This allows us to whitelist a key for a read, write, or both.
Here are some explicit examples of how you would use this:
Let's say that …
=> Dynamic Benchmarking DB Whitelist

primitives/core/src/crypto.rs
Instead of using the `Debug` implementation inside the `Display`
implementation this pr changes it to display only the name of the format.
Fixes: https://github.com/paritytech/substrate/issues/6937
=> Make Ss58AddressFormat display less expressive

Cargo.lock, client/authority-discovery/Cargo.toml, client/authority-discovery/src/worker.rs, client/authority-discovery/src/worker/tests.rs
When collecting the addresses to be published for the local node,
`addresses_to_publish` adds the local nodes `PeerId` to each
`Multiaddr`. Before doing so, ensure the `Multiaddr` does not already
contain one.
Caught while discussing `Multiaddr` specification via the Substrate CLI
with @fgimenez.
=> client/authority-discovery: Append PeerId to Multiaddr at most once

frame/indices/src/lib.rs
Expose pallet-indices Deposit so it can be queried.
=> Expose pallet-indices Deposit to metadata

client/api/src/backend.rs, client/api/src/in_mem.rs, client/api/src/light.rs, client/db/src/lib.rs, client/db/src/light.rs, client/light/src/blockchain.rs, client/service/src/chain_ops/build_spec.rs, client/service/test/src/client/light.rs
Currently, CHT roots are only generated on a light client, but CHT roots also need to be generated on full clients so that proofs can be sent to light clients.
=> Dynamically generate CHT roots on a full client

bin/node/runtime/src/lib.rs, frame/balances/src/benchmarking.rs, frame/benchmarking/src/lib.rs, frame/benchmarking/src/tests.rs, frame/benchmarking/src/utils.rs, frame/staking/src/benchmarking.rs, utils/frame/benchmarking-cli/src/command.rs, utils/frame/benchmarking-cli/src/lib.rs
This PR enables verification logic to run when executing benchmarks. Before, verification logic was only used in the runtime tests, but this will allow users who execute benchmarks on their actual runtime to verify the end state of their benchmarks.
This feature will not effect the results of your benchmarks, but will increase the overall execution time of benchmarks by S * extrinsic where S is the number of steps used for running your benchmark.
To disable this feature, simply pass the `--no-verify` flag.
=> Enable verification logic when executing benchmarks

client/finality-grandpa/rpc/Cargo.toml, client/finality-grandpa/rpc/src/lib.rs, client/finality-grandpa/rpc/src/notification.rs, client/finality-grandpa/src/environment.rs, client/finality-grandpa/src/import.rs, client/finality-grandpa/src/notification.rs, client/finality-grandpa/src/observer.rs
In GRANDPA we don't persist justifications for every block we finalize, only for blocks that trigger an authority set change and periodically every 512 blocks. We expose an RPC pubsub method that is meant to receive justifications for all finalized blocks but currently it was still going through the same filtering logic as for persisting justifications. This PR fixes this and also changes the type of the notification from `Vec<u8>` to `Bytes` so that it's properly hex-encoded.
=> grandpa: always create and send justification if there are any subscribers

.maintain/monitoring/alerting-rules/alerting-rules.yaml
Alert on high file descriptor allocation.
This is not so much about the file descriptor limit itself, which is usually within the range of millions. Much rather this should show us when something suspicious is happening, e.g. https://github.com/paritytech/substrate/pull/6805 or high number of connections through https://github.com/libp2p/rust-libp2p/pull/1698.
Related to https://github.com/paritytech/polkadot/issues/1544.
=> .maintain/monitoring/alerting-rules: Add fd alert

client/db/src/bench.rs, primitives/state-machine/src/backend.rs, primitives/state-machine/src/ext.rs
This fix the issues related to count read and write in child tries:
* every write into a child trie will now be counted
* the same key read from different trie won't be counted as repeat
TODO:
=> Fix benchmark read/write key tracker for keys in child storages.

client/authority-discovery/src/worker.rs, client/authority-discovery/src/worker/tests.rs
While unlikely due to the global Kademlia record limit and the fact that validators are semi-trusted, I think it is still worth limiting the amount of addresses allowed per authority. `10` is chosen somewhat arbitrary here.
=> client/authority-discovery: Limit number of addresses per authority

Cargo.lock
the command `cargo +stable test -p frame-support-test` fails on master, updating tracing-attribute in cargo.lock fix the issue,
I'm not sure if this is the proper fix.
=> Update tracing attribute in cargo.lock

frame/benchmarking/src/lib.rs, frame/contracts/src/benchmarking.rs
This PR generally improves the benchmarking code to avoid unnecessary panics, and instead handle errors more gracefully.
Additionally it:
* Executes no code when `repeat == 0`, ensuring you are always able to list available benchmarks.
* Pass by reference w/ Vec.
* Pass component when running verification code with components.
=> Fix unwraps and other issues with benchmarks

frame/society/src/mock.rs, frame/support/src/traits.rs
Fixes: https://github.com/paritytech/substrate/issues/6452
=> Remove implementation of `Randomness for ()`

client/network/src/behaviour.rs, client/network/src/block_requests.rs, client/network/src/config.rs, client/network/src/discovery.rs, client/network/src/finality_requests.rs, client/network/src/gossip/tests.rs, client/network/src/light_client_handler.rs, client/network/src/protocol.rs, client/network/src/protocol/generic_proto/tests.rs, client/network/src/protocol/generic_proto/upgrade/legacy.rs, client/network/src/service.rs, client/network/src/service/tests.rs, client/network/test/src/lib.rs, client/service/src/builder.rs
The `ProtocolId` struct contains the identifier of the chain, such as `dot`, `ksmcc3`, or `fir8`.
It is stored as a string in the chain specs, but we convert it to a `Vec<u8>` at initialization.
When reporting network activity to Prometheus, the networking code then tries to convert the `Vec<u8>` back to a string, purely for metrics reporting purposes.
While I'm not totally sure, I think that `multistream-select` also has some issues with non-UTF8 protocol names.
Rather than going through this `Vec<u8>`, this PR just keeps the `ProtocolId` as a string all the time.
cc https://github.com/paritytech/substrate/issues/6660
=> Enforce that ProtocolId is a string

frame/offences/benchmarking/src/lib.rs, frame/staking/src/lib.rs, frame/staking/src/tests.rs
This is a small PR that allows a stash to specify any account as the reward destination for their payouts.
Right now we are allowing accounts to be created through payouts in this way.
Should require no storage migration as this simply extends an existing enum variant.
cc @wpank 
fixes https://github.com/paritytech/substrate/issues/3544
=> Support Staking Payout to Any Account

bin/node/runtime/src/lib.rs, frame/babe/src/lib.rs, frame/babe/src/tests.rs, frame/grandpa/src/lib.rs, frame/grandpa/src/tests.rs
This wasn't using the correct formula as extracted from the benchmarks model (was missing the components that scale with the number of validators).
=> babe: fix report_equivocation weight

client/finality-grandpa/src/communication/mod.rs, client/finality-grandpa/src/communication/tests.rs, client/network-gossip/src/bridge.rs, client/network-gossip/src/lib.rs, client/network-gossip/src/state_machine.rs, client/network/src/behaviour.rs, client/network/src/config.rs, client/network/src/gossip/tests.rs, client/network/src/protocol.rs, client/network/src/protocol/generic_proto/behaviour.rs, client/network/src/protocol/generic_proto/handler/group.rs, client/network/src/protocol/generic_proto/handler/notif_in.rs, client/network/src/protocol/generic_proto/handler/notif_out.rs, client/network/src/protocol/generic_proto/upgrade/notifications.rs, client/network/src/service.rs, client/network/src/service/tests.rs
Notification protocol names are in practice always valid utf8 strings.
Instead of treating them as such in the type system, thus far they were
casted to a [u8] at creation time.
With this commit protocol names are instead treated as valid utf8
strings throughout the codebase and passed as `Cow<'static, str>`
instead of `Cow<'static, [u8]>`. Among other things this eliminates the
need for string casting when logging.
Closes https://github.com/paritytech/substrate/issues/6660.
polkadot companion: https://github.com/paritytech/polkadot/pull/1655
=> client/*: Treat protocol name as str and not [u8]

Cargo.lock, bin/node/bench/Cargo.toml, client/db/Cargo.toml
* rocksdb 6.11.4 (compared to 6.7.4) contains some fixes that might have caused corruption issues like #6797.
* updated default rocksdb format_version to 5 (https://github.com/paritytech/parity-common/pull/395), this might bring some perf speedup for dbs synced from scratch
polkadot companion: https://github.com/paritytech/polkadot/pull/1647
=> update kvdb-rocksdb to 0.9.1 and rocksdb to 6.11.4

client/network/src/protocol/generic_proto/upgrade/notifications.rs
Using `read_exact` will return an error if the EOF happens before the expected handshake length, and is therefore more... exact.
=> Use AsyncReadExt::read_exact, not just read

Cargo.lock, client/cli/Cargo.toml, client/cli/src/config.rs, client/service/test/Cargo.toml
Substrate sets the soft file descriptor limit to the hard limit at
startup. In the case of the latter being low already (< 10_000) a
Substrate node under high demand might run into issues e.g. when opening
up new TCP connections or persisting data to the database.
With this commit a warn message is printed to stderr.
---
I am suggesting to only warn for now. In future releases we can still error
adding an optional `--ignore-fd-limit` flag to ignore the limit.
This is blocked on a new release of `fdlimit` that includes https://github.com/paritytech/fdlimit/pull/4.
=> client/cli/src/config: Warn on low file descriptor limit

Cargo.lock, primitives/core/Cargo.toml
This PR update substrate-bip39 version before closing https://github.com/paritytech/parity-common/issues/412 .
=> Update substrate bip39 version.

frame/nicks/src/lib.rs
Fixes #6988 by inverting set and changed events in the nicks pallet
=> Inverting events set and changed in nicks pallet

client/network/src/protocol.rs
This warning is supposed to indicate a critical problem in the node, but in practice it is frequently triggered in two situations:
- Light clients don't register the GrandPa protocol, as they are not interested in GrandPa messages, but still receive GrandPa notifications.
- More importantly: we're removed the old prototype of Polkadot-specific networking protocol, but older nodes still send notifications on this protocol.
As a consequence of the latter, anyone who runs a node right now is constantly spammed with this error.
This PR takes the pragmatic approach of silencing it.
=> Silence the error about non-registered protocols

frame/evm/Cargo.toml
Getting error when trying to add pallet-evm.
To reproduce:
```
cd frame/evm
cargo check --no-default-features --target=wasm32-unknown-unknown
```
=> fix pallet-evm features

.gitlab-ci.yml
the ci job for deploying prometheus alerting rules isn't triggered on changes to the file .maintain/monitoring/alerting-rules/alerting-rules.yaml as it should. gitlab doesn't understand variables in it's yaml syntax at that place.
=> ci: deploy alerting rules: fix run on changes

Cargo.lock, primitives/utils/Cargo.toml, utils/prometheus/Cargo.toml
We just pushed a new release candidate for the Prometheus crate: https://github.com/tikv/rust-prometheus/pull/340
Opening up this pull request to test the release candidate for now. Once it is promoted to a release we can proceed with this pull request.
=> *: Update to Prometheus v0.10.0

client/network/src/protocol/generic_proto/handler/group.rs, client/network/src/protocol/generic_proto/handler/notif_in.rs, client/network/src/protocol/generic_proto/upgrade/notifications.rs
I found this issue when debugging the test failure in https://github.com/paritytech/substrate/pull/6975
Since https://github.com/paritytech/substrate/pull/6821, when the legacy substream opens, the node switches to a state where it waits for all notification substreams opening to either succeed or fail.
Consequently, the node also intentionally stops polling the incoming notification substreams in order to not receive notifications in this state.
Unfortunately, incoming notification substreams also need to send a handshake, and this is being done in the implementation of `Stream::poll`. Not polling a incoming notification substream unfortunately has the side-effect that its handshake isn't being sent either. 
A typical buggy situation is: as the listening side of a connection, a node …
=> Ensure that handshake is sent back even in case of back-pressure

client/finality-grandpa/src/environment.rs
This adds a new prometheus and telemetry metric for every prevote/precommit that is cast by the local GRANDPA voter.
cc @mattrutherford
=> grandpa: report metrics on prevotes and precommits cast

primitives/npos-elections/compact/src/lib.rs
This edge count is used for weighing, and it is somewhat trivial to review and verify that the current implementation was ignoring `votes16` field of the struct. As reminder, the struct is like this: 
```rust
struct Compact {
votes1: ... ,
votes2: ..., 
...,
votes16: ...,
}
```
I already will fix this in https://github.com/paritytech/substrate/pull/7007, but since it might take a while, this one can go in asap and make it to the very next runtime.
I won't mark this as high priority because the weight function is not _terribly_ wrong, it is just a bit underestimated.
=> Fix compact npos solution edge count calculation

client/informant/src/lib.rs, client/network/src/network_state.rs, client/network/src/service.rs, client/network/src/service/metrics.rs, client/rpc/src/system/tests.rs, client/service/src/builder.rs, client/service/src/lib.rs, client/service/src/metrics.rs
This PR is supposed to address https://github.com/paritytech/substrate/issues/6093 alongside some refactoring. In particular
1. `sc-network` metrics are aggregated into the `service/metrics` submodule, introducing two more sourced metrics to avoid duplicate atomics (for "num connected peers" and "major syncing").
2. The periodic `sc-service` metric/telemetry updates have their own update interval, independent of the intervals at which network status and state information is requested, so that network-independent metrics are updated on every tick and network metrics whenever available.
3. Some disk I/O-related metrics that are no longer used by the telemetry have been removed (cf. https://github.com/paritytech/substrate-telemetry/issues/277).
4. `total_bytes_inbound`/`total_bytes_outbound` …
=> Refactor & detach network metrics.

bin/node-template/node/src/service.rs
This PR fixes the node template service to use the complete `aura -> grandpa -> client` block import pipeline for blocks that are authored locally. (The complete pipeline was already used for imported blocks.)
=> Node template complete import pipeline

bin/utils/subkey/src/lib.rs, client/cli/src/commands/generate_node_key.rs, client/cli/src/commands/key.rs
This pr makes the `--file` argument optional to `generate-node-key`.
If the argument is not given, the secret node key will be printed to
`stdout`. The public node key will always be printed to `stderr`.
Fixes: https://github.com/paritytech/substrate/issues/7022
=> Make `--file` optional for `generate-node-key`

Cargo.lock, bin/node/executor/Cargo.toml, bin/node/testing/Cargo.toml, client/executor/Cargo.toml, primitives/sandbox/Cargo.toml
superseeding #6928 – downgrading wabt to better be safe than sorry.
fixes #6945
=> Downgrade wabt = 0.9.1

frame/multisig/src/lib.rs
Small PR to allow calculating multisig operation deposits more easily offchain
=> Add metadata shadows to multisig pallet

frame/sudo/README.md
Reverts paritytech/substrate#7026
Doesn't fix anything that's actually broken and in any case should be a more general change if decided sensible.
=> Revert "Fix broken link to democracy pallet."

.maintain/monitoring/grafana-dashboards/substrate-service-tasks.json
Updates it for the removal of sysinfo (#6805)
Most importantly, the list of nodes was fetched from what the `cpu_percentage` metric reports, and would therefore show as empty.
As always, reading this JSON file is kind of complicated, and I'd expect anyone interested to instead actually import the dashboard to look at it and suggest changes.
=> Update the service tasks Grafana dashboard

frame/babe/src/lib.rs, frame/babe/src/tests.rs, frame/grandpa/src/lib.rs, frame/grandpa/src/tests.rs
Whenever a successful call to `report_equivocation` on either BABE or GRANDPA module is done, we will waive the fees as this is beneficial behavior for the network that we want to incentivize.
This isn't too important right now since the automatic equivocation reports performed by the node are done using the unsigned extrinsic (which doesn't pay fees).
=> babe, grandpa: waive fees on valid equivocation report

frame/nicks/src/lib.rs
Address Guillaume's comments from #6990.
=> Clarify Nicks docs

frame/evm/src/lib.rs
This PR allows using the EVM execution without verifying the gas price when doing a gas estimation.
It only verifies the gas price when the state after execution is supposed to be applied.
=> Improves EVM gas price check

Cargo.lock, bin/node/executor/Cargo.toml, bin/node/executor/tests/basic.rs, bin/node/testing/Cargo.toml, client/executor/Cargo.toml, client/executor/src/integration_tests/sandbox.rs, primitives/sandbox/Cargo.toml, primitives/sandbox/with_std.rs
Using wat is more desired since it should be more lightweight, faster to compile and most importantly doesn't depend on C toolchain.
=> Change wabt to wat

primitives/core/src/crypto.rs
Taking 21 and 22 for testnet and mainnet
Signed-off-by: lovesh <lovesh.bond@gmail.com>
=> Add Dock network id for address generation

frame/support/src/weights.rs, frame/system/src/extensions/check_nonce.rs, frame/system/src/extensions/check_weight.rs, frame/transaction-payment/src/lib.rs, primitives/npos-elections/compact/src/lib.rs
Partially fixing https://github.com/paritytech/substrate/issues/5672 and a recent audit comment about priorities being too eagerly correlated with fees. 
1. As suggested, the priority set by the `TransactionPayment` is now `fee / max(weight/maxWeigh, len/maxLen)`.
2. From other signed extensions, I removed the weight that was being set by `CheckNonce` as I think it was not needed. 
3. The weight set by `CheckWeight` is almost the same, I just made it a bit more expressive. Previously, the minimum for operational was `u64::max() / 2`, now it is `u64::max() * 3 / 4` plus whatever was the weight.
I am not super happy with this enum (`FrameTransactionPriority`) as it is. It is slightly better, but I had other intentions in mind when I first created it: A wrapper to make sure that if a …
=> Partial fix for transaction priority

Cargo.lock, bin/node/testing/Cargo.toml
In response to [this comment](https://github.com/paritytech/substrate/pull/7050#discussion_r485361639)
=> What happens if we remove wat?

frame/staking/src/lib.rs
Offchain Applications will often need to inspect this type because it is directly used in staking election, thus worthy of being `pub`. Rest of the slashing api can remain private, only this and the `fn last_non_zero_slash()` of `SlashingSpans` are of interest.
=> Make SlashingSpans Public

client/authority-discovery/src/service.rs
Minor change explaining `PeerId` distribution returned by authority discovery `Service`.
=> client/authority-discovery/src/service: Improve docs

.github/workflows/polkadot-companion-labels.yml
Hopefully this will mitigate the `API rate limit exceeded for installation ID 5177796.` errors. Examples of errors:
https://github.com/paritytech/substrate/actions/runs/246456201
https://github.com/paritytech/substrate/actions/runs/246444243
=> [CI] Increase poll interval in the 'Check Polkadot Companion and Label' workflow

frame/support/src/dispatch.rs, frame/support/test/src/lib.rs, frame/support/test/tests/construct_runtime.rs, frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_integrity_test.rs, frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_integrity_test.stderr, frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_on_initialize.rs, frame/support/test/tests/decl_module_ui/reserved_keyword_two_times_on_initialize.stderr, frame/support/test/tests/decl_storage.rs, frame/support/test/tests/decl_storage_ui/config_duplicate.rs, frame/support/test/tests/decl_storage_ui/config_get_duplicate.rs, frame/support/test/tests/decl_storage_ui/get_duplicate.rs, frame/support/test/tests/final_keys.rs, frame/support/test/tests/genesisconfig.rs, frame/support/test/tests/instance.rs, frame/support/test/tests/issue2219.rs, frame/support/test/tests/reserved_keyword/on_initialize.rs, frame/support/test/tests/storage_transaction.rs, frame/support/test/tests/system.rs, frame/system/src/lib.rs
`decl_module!` generates the `on_initialize`, `on_finalize`, and `offchain_worker` functions which depend on `T::BlockNumber`. However, if for some crazy reason, there is another `BlockNumber` associated type in a pallet that would interfere with this type definition, then a user would run into ambiguity errors.
This PR uses the already defined `system` identifier to disambiguate use of the `BlockNumber` type.
(A user should probably avoid creating a type named `BlockNumber`, but this seems like the right solution anyway)
=> Disambiguate `BlockNumber` type in `decl_module`

primitives/core/src/crypto.rs
Fixes: https://github.com/paritytech/substrate/issues/6993
=> Implement `FromStr` for `Ss58AddressFormat`

docs/README.adoc, utils/wasm-builder-runner/src/lib.rs, utils/wasm-builder/README.md, utils/wasm-builder/src/lib.rs
Because apparently I can not speak properly ;)
=> Rename `TRIGGER_WASM_BUILD` to `FORCE_WASM_BUILD`

primitives/arithmetic/src/per_things.rs
Fix https://github.com/paritytech/substrate/issues/5462
BREAKING CHANGE: more a fix than a breaking change: decoding a compact encoding of perthing will saturate the perthing to perthing::max instead of returning an invalid perthing variable when maximum overflowed.
by implementing CompactAs manually we can saturate the given inner type so it doesn't overflow perthing accuracy.
This means that any compact encoding of the perthing::Inner type are valid, just they will saturate when decoding them.
=> Make decoding of `compact<perthing>` saturating instead of invalid

client/cli/src/params/node_key_params.rs, client/network/src/config.rs
Adds support for reading a hex encoded secret key when being passed as
file via `--node-key`.
Fixes: https://github.com/paritytech/substrate/issues/7025
=> Support hex encoded secret key for `--node-key`

client/cli/src/commands/build_sync_spec_cmd.rs
=> Fix build sync spec

primitives/io/src/lib.rs, test-utils/runtime/src/lib.rs
It should return the length of the storage item after the given offset.
Before it returned always the length of the full storage item.
The regression was introduced in: https://github.com/paritytech/substrate/pull/3589
=> Fix `storage::read`

Cargo.lock, primitives/npos-elections/fuzzer/Cargo.toml, primitives/npos-elections/fuzzer/src/compact.rs
This commit adds a fuzzing harness for the custom compact encoding/decoding
introduced in PR #6720.
=> Add fuzzer for the compact custom codec implementation from PR #6720

frame/treasury/src/benchmarking.rs, frame/treasury/src/lib.rs, frame/treasury/src/tests.rs
With instantiable support, runtime could manage seperated funding pots with dedicated module id.
This enhancement uses DefaultInstance which no impact on current single instance using.
=> add instantiable support for treasury pallet

Cargo.lock, bin/node/cli/Cargo.toml, bin/node/cli/src/service.rs, bin/node/rpc/Cargo.toml, bin/node/rpc/src/lib.rs, client/finality-grandpa/rpc/src/lib.rs, client/service/src/builder.rs
Instead of having `sc-finality-grandpa-rpc` share subscription manager with the client, only share executors.
Based on the idea that less sharing is better.
Part of: #6066 
polkadot companion: https://github.com/paritytech/polkadot/pull/1687
=> grandpa-rpc don't share subscription manager, only executor

client/consensus/pow/src/lib.rs
This adds support for uniform tie breaking for PoW fork choice. A new trait method is added `PowAlgorithm::break_tie`. Given an own seal and a new seal of the same total difficulty, it returns which seal should be chosen. By default it's always own seal -- the current behavior. An implementer can customize this function to be deterministic to support uniform tie breaking.
=> pow: support uniform tie breaking in fork choice

client/network/src/behaviour.rs, client/network/src/discovery.rs, client/network/src/service.rs, client/network/src/service/metrics.rs
Extend `sub_libp2p_kbuckets_num_nodes` Prometheus metric to expose the
number of nodes per bucket per Kademlia instance instead of only per
Kademlia instance.
=> client/network: Expose number of entries per Kademlia bucket

primitives/core/src/crypto.rs
Hello,
This PR adds a new ss58 address 17 for Dark network.
Thanks you!
=> Add ss58 address for Dark network

frame/support/src/dispatch.rs, frame/support/src/storage/generator/double_map.rs, frame/support/src/storage/generator/map.rs, frame/support/src/storage/mod.rs
* StoragePrefixedMap::iter was stopping on the first value that fails to decode. This is changed to be consistent with IterableStorageMap::iter. Now it skip it with logging an error.
* StoragePrefixedMap::translate_values signature has been changed to be similar to what is IterableStorageMap::translate:
* no number of error returned, just logged key that fail to decode
* translate function returns `Option<Value>`
* IterableDoubleMap::translate has been changed to be similar to IterableStorageMap::transalte: i.e. it gives the key1 and key2 to the translation closure.
=> Frame-support storage: make iterations and translate consistent

.maintain/chaostest/package-lock.json
Bumping bl version from 4.0.2 to 4.0.3 based on npm audit report  <del>1 High severity</del>
Bumping lodash version from 4.17.15 to 4.17.0 based on npm audit report <del>23 Low severity</del>
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Remote Memory Exposure                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ bl                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @oclif/dev-cli [dev]                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @oclif/dev-cli > …
```
=> fix js dependancy alert, bumping bl version

frame/support/procedural/src/lib.rs, frame/support/procedural/src/transactional.rs, frame/support/procedural/tools/src/lib.rs
The old implementation expected that `frame-support` wasn't imported
under a different name. Besides that the pr removes some whitespaces.
=> Make `transactional` attribute less scope dependent

client/service/src/client/client.rs, client/service/test/src/client/mod.rs
This pr changes the behavior of sending import notifications. Before we
only send notifications when importing blocks on the tip of the chain or
on similar conditions. However we did not send a notification when we
for example being in a state where we import multiple blocks to catch
up. If we re-org in this process, systems like the transaction pool
would not be notified about this re-org. This means, that we would also
not resubmit transactions of these retracted blocks. This pr fixes this,
by always sending a notification on a re-org.
See
https://github.com/substrate-developer-hub/substrate-node-template/issues/82
for some context about the bug.
=> Send import notification always for re-orgs

Cargo.lock, bin/node-template/node/Cargo.toml, bin/node-template/node/src/cli.rs, bin/node-template/node/src/command.rs, bin/node-template/node/src/service.rs, bin/node-template/runtime/Cargo.toml, bin/node-template/runtime/src/lib.rs, bin/node/cli/src/command.rs
This is a PR which introduces the benchmarking pipeline to the node-template.
This is disabled by default, but can be enabled by building the node-template with `--features runtime-benchmarks`.
This will make it easier when people build their custom runtimes and nodes using the Substrate Node Template to do benchmarking.
=> Add benchmarking pipeline to node-template

bin/node/runtime/src/lib.rs, bin/node/runtime/src/weights/pallet_im_online.rs, frame/im-online/src/benchmarking.rs, frame/im-online/src/default_weight.rs, frame/im-online/src/lib.rs
This updates the ImOnline Pallet to use the automated benchmarks.
=> WeightInfo for ImOnline

bin/node/runtime/src/lib.rs, bin/node/runtime/src/weights/mod.rs, bin/node/runtime/src/weights/pallet_staking.rs
I just forgot to use the new weights in substrate node as well.
=> fix the new staking weight in substrate-node

client/network/src/config.rs
This warning is no longer relevant after #7077.
=> Remove warning about deprecated PeerIds

client/db/src/parity_db.rs, client/db/src/utils.rs
=> Fix db initialization for light client

bin/utils/subkey/src/lib.rs
=> Rename subkey's `inspect-key` to `inspect`

Cargo.lock, bin/node-template/node/Cargo.toml, bin/node/browser-testing/Cargo.toml, bin/node/rpc-client/Cargo.toml, bin/node/rpc/Cargo.toml, client/consensus/babe/rpc/Cargo.toml, client/consensus/manual-seal/Cargo.toml, client/finality-grandpa/rpc/Cargo.toml, client/rpc-api/Cargo.toml, client/rpc-api/src/chain/mod.rs, client/rpc-api/src/state/mod.rs, client/rpc-servers/Cargo.toml, client/rpc/Cargo.toml, client/service/Cargo.toml, frame/contracts/rpc/Cargo.toml, frame/transaction-payment/rpc/Cargo.toml, utils/frame/rpc/support/Cargo.toml, utils/frame/rpc/system/Cargo.toml
polkadot companion: https://github.com/paritytech/polkadot/pull/1737
=> Bump jsonrpc-* dependencies to v15

ss58-registry.json
Taking 39 and 40 for mathchain mainnet and testnet
Signed by: lei dongliang, dlleig@gmail.com
=> Add MathChain SS58 address type

primitives/runtime/src/lib.rs, primitives/std/with_std.rs, primitives/std/without_std.rs
Fixes: https://github.com/paritytech/stakingops-issues/issues/36
=> Do not panic while panicking

client/network/src/transport.rs
Instead of building a libp2p `Transport` via a chain of `and_then`,
leverage the `libp2p::core::upgrade::Builder` pattern for authentication
and multiplexing.
=> client/network/src/transport: Use libp2p upgrade builder

client/cli/src/commands/utils.rs, client/cli/src/commands/vanity.rs
Fixes: https://github.com/paritytech/substrate/issues/7177
=> Fix vanity command by taking the network into account

utils/wasm-builder-runner/src/lib.rs
`RUSTFLAGS='-D missing_docs' cargo build` doesn't work with anything that uses `substrate-wasm-builder-runner` because there isn't a top-level documentation for the auto-generated code and this PR only adds a placeholder to make the lint happy.
=> Add doc for auto-generated code

.gitlab-ci.yml
by adding the corresponding `--owner` flag to the ci job
=> Ensure that all new packages released with unleash have paritytech:core-devs as owners

primitives/core/src/ecdsa.rs
public.
`Public` and `Signature` tuple structs of ed25519 and sr25519 have the
internal member public already. This change makes the interface similar.
Signed-off-by: lovesh <lovesh.bond@gmail.com>
=> Make private member of ecdsa `Public` and `Signature` tuple structs as

client/network/src/transport.rs
Stop sending noise legacy handshake payloads, i.e. length-prefixed protobuf
payloads inside a length-prefixed noise frame. Receiving of such legacy
handshakes is still supported, thus backwards compatibility is given.
Fixes https://github.com/paritytech/substrate/issues/7175.
> Stop sending noise legacy handshake payloads, i.e. length-prefixed protobuf payloads inside a length-prefixed noise frame. Receiving of such legacy handshakes is still supported, thus backwards compatibility is given to all clients running with libp2p `>= v0.22.0`. Clients previously running with libp2p `< v0.22.0` should first update to previous Substrate versions, which support the new handshake format, before updating to this Substrate version.
=> client/network: Stop sending noise legacy handshake

client/network/src/service.rs
Despite #7077, I thought it might still be useful to see the legacy representation of the `PeerId`.
However, since `Borrow::borrow` no longer returns a hashed version of the `PeerId`, the log message touched in this PR ends up printing the same string twice.
Rather than going through complicated means to properly show the legacy `PeerId`, I propose to just remove it.
=> No longer display the legacy representation of the PeerId

frame/treasury/src/benchmarking.rs
The old setup code was not generic over all potential runtime configurations. For example then `BountyValueMinimum` is greater than 100x the existential deposit. This fixes that.
=> Fix Treasury Benchmark Setup

.maintain/monitoring/alerting-rules/alerting-rule-tests.yaml, .maintain/monitoring/alerting-rules/alerting-rules.yaml
- Start alert names with their component and end with the describing
adjective.
- Describe alert duration in `message` with `for more than` across all
alerts.
=> .maintain/monitoring: Normalize alerting rules

.gitlab-ci.yml, Cargo.lock
polkadot companion: https://github.com/paritytech/polkadot/pull/1769
- changes somewhat broken/deprecated `only` and `accept` keys to not very readable `rules`. The upside is without `only`, DAGs will be accessible.
- removes unused `DEPLOY_TAG`
- build binaries for substrate and subkey (both mac and linux) is now manually available in PRs
example of a pipeline for a regular PR https://gitlab.parity.io/parity/substrate/-/pipelines/109099
example of a pipeline with `[chaos:basic]` in commit text https://gitlab.parity.io/parity/substrate/-/pipelines/109101
=> WIP: remove deprecated only/except clauses

bin/node/runtime/src/lib.rs, frame/session/benchmarking/src/lib.rs, frame/staking/src/benchmarking.rs
This PR solves an issue I found when doing final weights on Polkadot around the payouts code.
https://github.com/paritytech/polkadot/pull/1761
The main issue was that the validator we set up to test was not being selected as the validator in the benchmark.
I have updated the test to add a bunch more assertion statements about the benchmark doing what we actually expect
and i have added an additional line in the benchmark to make sure to clean up old state.
I can confirm this fixes bad results I was finding in Polkadot, and should be one of the last things I need to merge my Polkadot weight update pr: https://github.com/paritytech/polkadot/pull/1761
Note the correct DB weight information below
```
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Trait> …
```
=> Improve Payout Benchmarks in Staking

frame/evm/src/backend.rs
The timestamp we received from `pallet-timestamp` is of milliseconds, but EVM specification requires the timestamp to be returned in seconds.
=> pallet-evm: fix backend timestamp

bin/node/runtime/src/lib.rs
It was pointed out that our Substrate Node configuration hardcoded how many members were needed to do things in treasury. This is a simple update to use proportions rather than strict values.
=> Update Treasury Config to use Propotion of Council Members

frame/multisig/src/lib.rs, frame/proxy/src/lib.rs, frame/recovery/src/lib.rs, frame/scheduler/src/lib.rs, frame/sudo/src/lib.rs, frame/utility/src/lib.rs
inner call with different origin expect their origin accountdata to be already read and write by transaction nonce update. Thus we have to take this into account when it is actually not the case
=> Fix weight for inner call with new origin

bin/node/runtime/src/lib.rs, frame/proxy/src/lib.rs
Closes #7139
Can't figure out a good way to remove the deposit requirement for `add_proxy` without introducing inconsistency so provide a way to check deposit requirement instead.
I don't like on the name of `add_proxy_delegate` and `remove_proxy_delegate` but can't think a better one.
=> expose add_proxy and remove_proxy

frame/treasury/src/lib.rs, frame/treasury/src/tests.rs
Treasury pallet will set initial balances to account ED, this will cause conflict if we want to set treasury initial funding in genesis, the change is to add a check before setting treasury balances to  ED (only when balance is lower than ED)
=> permit setting treasury pallet initial funding through genesis

frame/executive/src/lib.rs, frame/support/procedural/src/construct_runtime/mod.rs, primitives/runtime/src/testing.rs
the Applyable implementation of TestXT make no use of ValidateUnsigned, but frame-executive is testing for ValidateUnsigned with test `validate_unsigned`.
So the test is wrong as it is successful for any implementation of ValidateUnsigned.
So TestXT is now checking ValidateUnsigned implementation, also test is refactored to make use of construct_runtime, this is not needed, but is more future proof.
=> Fix executive test

client/network/src/protocol/generic_proto/behaviour.rs
See the comment of the removed code.
The very few nodes that still use Polkadot 0.8.10 and below look broken according to the telemetry anyway. We can drop compatibility with them.
=> Remove hack around secondary connections handshakes

client/cli/src/lib.rs
Should be `cranelift_wasm`, not `cranelife_wasm`.
=> Fix typo cranelift_wasm

Cargo.lock, client/cli/Cargo.toml, client/service/test/Cargo.toml
fdlimit 0.2.1 contains a small patch allowing compilation on platforms
where libc represents rlimits as u32.
See https://github.com/paritytech/fdlimit/pull/6 for details.
=> client/cli: Update to fdlimit 0.2.1

primitives/runtime/src/generic/unchecked_extrinsic.rs
This renames the constant `TRANSACTION_VERSION` to `EXTRINSIC_VERSION`
to reflect the real usage.
Fixes: https://github.com/paritytech/substrate/issues/7255
=> Rename `TRANSACTION_VERSION` to `EXTRINSIC_VERSION`

.maintain/monitoring/alerting-rules/alerting-rules.yaml
Through the `polkadot_tasks_ended_total` Prometheus metric one can tell
when a task ended. Use this metric to alert when specific
known-to-be-continuous tasks end on a node.
This would catch bugs like https://github.com/paritytech/substrate/pull/7000/#discussion_r498387783.
=> .maintain/monitoring: Add alert when continuous task ends

ss58-registry.json
Signed-off-by: lovesh <lovesh.bond@gmail.com>
=> Update ss58 registry for Dock network

bin/node/bench/src/import.rs, primitives/state-machine/src/read_only.rs
Reworks `InspectState` in two ways:
- Renames `inspect_with` to `inspect_state` to reflect the trait name.
- Make `inspect_state` return the result of the closure
=> Rework `InspectState`

client/cli/src/lib.rs
Improve log formatting so that it is more inline with the format before #6825 was introduced.
Examples:
- Before #6825: `2020-10-06 16:06:48.467 main INFO sc_cli::runner  Substrate Node`
- master: `Oct 06 16:06:48.467  INFO Substrate Node`
-  This PR: `2020-10-06 16:06:48.467   INFO main sc_cli::runner: Substrate Node`
Unfortunately I did not find a way to change the order of log level / target / thread name so it's not exactly the same format as before.
Additionally, we use a simplified formatting if no log filters for anything higher than info are enabled.
```
❯ ./target/debug/substrate --dev --tmp
2020-10-06 22:26:53  Running in --dev mode, RPC CORS has been disabled.
2020-10-06 22:26:53  Substrate Node
2020-10-06 22:26:53  ✌️  version 2.0.0-fb82769a2-x86_64-linux-gnu
```
```
❯ …
```
=> client: improve log formatting

primitives/core/src/crypto.rs, ss58-registry.json
This PR modifies the list of reserved SS58 IDs to include one for Nodle (37, we will keep 42 for Arcadia, our tesnet).
We'd then modify our node to include the reserved ID once this PR is merged.
After you've read this …
=> add ss58 id for nodle

Cargo.lock, bin/node-template/runtime/Cargo.toml, bin/node/runtime/Cargo.toml, client/executor/runtime-test/Cargo.toml, primitives/runtime-interface/test-wasm-deprecated/Cargo.toml, primitives/runtime-interface/test-wasm/Cargo.toml, test-utils/runtime/Cargo.toml, utils/wasm-builder-runner/Cargo.toml, utils/wasm-builder-runner/src/lib.rs
Besides the new version this merges `SKIP_WASM_BUILD` and
`BUILD_DUMMY_WASM_BINARY`, this means a file is generated with
`SKIP_WASM_BUILD` if no file existed before.
CC @xlc
=> Release new version of wasm-builder-runner

ss58-registry.json
Update token info about the Darwinia network.
=> Update ss58-registry.json about Darwinia Network

frame/scheduler/src/lib.rs
Right now, if a user puts `schedule_after(0, ...)`, the call will fail because there is a check that the scheduled block must be greater than the current block:
```
if when <= now {
return Err(Error::<T>::TargetBlockNumberInPast.into())
}
```
This PR simply adds one additional block to any `schedule_after` call. So `schedule_after(0, ...)` will be the block **after** the current block, `schedule_after(1, ...)` will be the block after that, etc... So after this PR, all `schedule_after` will happen one block later. This allows `schedule_after` to always pass this check with any `after` input.
This is just a quality of life improvement which should capture the intention of the caller.
cc @xlc
=> Allow `schedule_after(0, ...)` to work

Cargo.lock, bin/node-template/runtime/build.rs, bin/node/runtime/build.rs, client/executor/runtime-test/build.rs, primitives/runtime-interface/test-wasm-deprecated/build.rs, primitives/runtime-interface/test-wasm/build.rs, test-utils/runtime/build.rs, utils/wasm-builder/Cargo.toml, utils/wasm-builder/src/lib.rs, utils/wasm-builder/src/wasm_project.rs
There was a bug in wasm-builder which resulted in generating a
`Cargo.lock` in the project directory because of running `cargo
metadata`. This resulted in commands like `cargo publish` to fail (if
there was no `Cargo.lock` before building), because it checks that the
project directory isn't modified.
Fixes: https://github.com/paritytech/substrate/issues/7116
=> Fixes bug in wasm-builder with cargo publish

client/cli/src/lib.rs
Fix the regression from https://github.com/paritytech/substrate/pull/6825, which caused profiling output to be missed unless the `--tracing-target` was also added to the logging filter.
=> Add profiling targets to tracing_subscriber

client/rpc-api/src/system/helpers.rs, client/rpc-api/src/system/mod.rs, client/rpc/Cargo.toml, client/rpc/src/system/mod.rs, client/rpc/src/system/tests.rs, client/service/src/lib.rs
Fix #5727 
(I don't know who to ask for a review)
Example usage:
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"system_syncState","params":[],"id":1}' localhost:9933
{"jsonrpc":"2.0","result":{"currentBlock":2903,"highestBlock":173020,"startingBlock":2738},"id":1}
```
The `highestBlock` field will be missing for a short duration after the node starts.
=> Add an system_syncState RPC method

bin/node-template/node/src/command.rs, bin/node/cli/src/command.rs, client/cli/src/runner.rs
The function takes a closure that resolved before to a `TaskManager`,
now it resolves to a `Future` which output is a `TaskManager`. This is
required for node setups that are async.
polkadot companion: https://github.com/paritytech/polkadot/pull/1810
=> Make `run_node_until_exit` take a future

frame/support/src/error.rs, frame/support/test/tests/instance.rs
If a trait has some where clause then decl_error will fail to compile.
This PR solve it by allowing decl_error to specify some where clause.
=> Allow where clause in `decl_error!`

client/network/src/protocol/sync.rs
When performing block import we might refuse to import a block until some previous block justifications are imported (#7321). With the current implementation we will restart the sync process after getting a block import error. In this case, we will drop all in-flight sync requests and figure out new block requests for each peer. This leads to a situation where we are constantly restarting sync and are unable to download the justifications that would eventually fix the block import error. This PR changes the sync logic so that when restarting it peers that were doing any kind of finality related request (downloading justifications or finality proofs) keep their existing state.
=> sync: only restart peers not doing finality related requests

primitives/consensus/common/Cargo.toml, primitives/consensus/common/src/import_queue/basic_queue.rs
The import queue should prioritize finality work over block import since finality work is less common and lighter than block import (especially during major sync), and performing the finality work can then lead to faster block import (or rather it solves slowdowns caused by longer stretches of unfinalized blocks).
=> consensus: prioritize finality work over block import in queue

client/cli/src/commands/generate.rs, client/cli/src/commands/inspect_key.rs, client/cli/src/commands/key.rs, client/cli/src/commands/mod.rs, client/cli/src/commands/utils.rs, primitives/application-crypto/src/lib.rs, primitives/core/src/crypto.rs
This adds support for inspecting hex encoded public keys to subkey. The
command looks like:
`subkey inspect --public 0xPUBLICHEX`
Closes: https://github.com/paritytech/substrate/issues/7069
=> Adds support for inspecting a hex encoded public key

client/rpc-api/src/state/error.rs, client/rpc/src/state/mod.rs, client/rpc/src/state/tests.rs, client/service/src/builder.rs
The RPC calls can be rather expensive and can easily bring a RPC node in
some problems ;)
Fixes: https://github.com/paritytech/substrate/issues/7302
@jacogr as we spoke, that shouldn't be anything that is used actively by the UI?
=> Make `queryStorage` and `storagePairs` unsafe RPC functions

frame/example/src/lib.rs, frame/proxy/src/lib.rs, frame/staking/src/lib.rs, frame/support/src/dispatch.rs, frame/support/src/inherent.rs, frame/support/src/lib.rs, frame/support/src/traits.rs
This moves the `IsSubType` trait from dispatch.rs to traits.rs. It also
adds docs to make the trait better understandable.
polkadot companion: https://github.com/paritytech/polkadot/pull/1829
=> Move `IsSubType` and write some docs for the trait

utils/wasm-builder/src/lib.rs, utils/wasm-builder/src/prerequisites.rs, utils/wasm-builder/src/wasm_project.rs
This makes `wasm-builder` print the rustc version that is being used to
compile the project. This is rather useful, because people can check
faster if the used rustc version is maybe known for being broken with
Substrate.
=> Make `wasm-builder` print the rustc version

client/finality-grandpa/src/environment.rs, client/finality-grandpa/src/lib.rs
We had two methods for fetching the local authority id, i.e. check if we have any keys available in the keystore for the current authority set. Additionally I also changed the name of the function that does this to make it more obvious.
=> grandpa: remove duplicate function to fetch local authority id

client/cli/src/params/network_params.rs, client/network/src/config.rs, client/network/src/service.rs, client/network/src/transport.rs, client/service/test/src/lib.rs, utils/browser/src/lib.rs
With the `OnRead` flow control option yamux "send[s] window updates only
when data is read on the receiving end" and not as soon as "a Stream's
receive window drops to 0".
Yamux flow control has proven itself. This commit removes the feature
flag. Yamux flow control is now always enabled.
> Remove option to disable yamux flow control via the `--no-yamux-flow-control` feature flag. Yamux flow control is now always enabled.
=> client/network: Remove option to disable yamux flow control

Cargo.lock, client/network-gossip/Cargo.toml, client/network/Cargo.toml, client/network/src/gossip.rs, client/network/src/gossip/tests.rs, client/service/Cargo.toml, utils/prometheus/Cargo.toml
Prevent users from using v1.6.4 which faces issues receiving incoming
TCP connections. See https://github.com/async-rs/async-std/issues/888
for details.
//CC @JoshOrndorff
> Methods on `sc_network::gossip::QueuedSender` take `&mut self` instead of `self`.
=> *: Bump async-std to v1.6.5

Cargo.lock, frame/support/Cargo.toml, frame/support/src/debug.rs, primitives/tracing/src/lib.rs, test-utils/runtime/src/lib.rs
When using `RuntimeLogger` to log something from the runtime, we didn't
set any logging level. So, we actually did not log anything from the
runtime as logging is disabled by default. This pr fixes that by setting
the logging level to `TRACE`. It also adds a test to ensure this does
not break again ;)
=> Fix logging from inside the WASM runtime

client/cli/src/params/network_params.rs, client/network/src/config.rs, client/network/src/discovery.rs, client/network/src/service.rs
The Rust libp2p-kad implementation can require iterative queries to use
disjoint paths for increased resiliency in the presence of potentially
adversarial nodes.
Allow Substrate users to enable this feature via the
`--kademlia-disjoint-query-paths` flag.
> Allow configuring Kademlia via the `--kademlia-disjoint-query-paths` flag  to require iterative DHT queries to use disjoint paths for increased resiliency in the presence of potentially adversarial nodes.
=> client/network: Allow configuring Kademlia's disjoint query paths

client/network/src/behaviour.rs, client/network/src/block_requests.rs
The `original_request` field of each `block_request::Event` variant is
not used. With that in mind, this commit removes the field.
=> client/network: Remove original_request in block request events

primitives/api/proc-macro/src/decl_runtime_apis.rs, primitives/api/test/tests/ui/no_default_implementation.rs, primitives/api/test/tests/ui/no_default_implementation.stderr
Runtime api functions are not allowed to have default implementations.
This fixes this by throwing an error when we detect such a function.
Fixes: https://github.com/paritytech/substrate/issues/7360
=> Make `decl_runtime_apis!` fail on methods with default implementation

Cargo.lock, client/authority-discovery/Cargo.toml, client/authority-discovery/src/worker.rs, client/authority-discovery/src/worker/tests.rs, client/network/src/service.rs
As done with `NetworkService::{add_to,remove_from}_priority_group`, make
`NetworkService::set_priority_group` async as well. This future-proofs
the API should we ever decide to use a bounded channel between
`NetworkService` and `NetworkWorker`.
See https://github.com/paritytech/substrate/pull/7247#discussion_r502263451 for past discussion.
> Make `NetworkService::set_priority_group` `async`. Doing so for all methods would eventually allow to use a bounded channel between `NetworkService` and `NetworkWorker`.
=> client/network: Make NetworkService::set_priority_group async

primitives/api/proc-macro/src/mock_impl_runtime_apis.rs, primitives/api/src/lib.rs, primitives/api/test/tests/decl_and_impl.rs, primitives/api/test/tests/ui/mock_advanced_block_id_by_value.rs, primitives/api/test/tests/ui/mock_advanced_block_id_by_value.stderr, primitives/api/test/tests/ui/mock_advanced_missing_blockid.rs, primitives/api/test/tests/ui/mock_advanced_missing_blockid.stderr, primitives/api/test/tests/ui/mock_only_one_error_type.stderr, primitives/core/src/lib.rs
This adds a new attribute for functions being implemented in the
`mock_impl_runtime_apis!` macro, the `advanced` attribute. When this
attribute is given the user gets access to the `at` parameter and is
able to return a `Result`, instead of letting the macro generate this
stuff.
=> Improve `mock_impl_runtime_apis!`

shell.nix
Adds a nix shell definition with everything required to build substrate. I'm OK with this not getting merged but I think it's a nice-to-have for any potential nix users that might clone our repo.
=> build: add nix shell

frame/elections-phragmen/src/lib.rs
This was a very unfortunate oversight from my end; The outgoing calculation seem to have been wrong because the inputs are simply not sorted. This can then cause accounts to be immaturely deemed loser, and subject to `slash_reserved()`.
This should be merged and deployed asap. Furthermore, I will lead an investigation over polkadot's state to make sure we can obtain a list of all accounts affected and properly reimburse them through governance.
=> Fix wrong outgoing calculation in election

bin/node/cli/src/service.rs, client/authority-discovery/src/lib.rs, client/authority-discovery/src/service.rs, client/authority-discovery/src/tests.rs, client/authority-discovery/src/worker.rs, client/authority-discovery/src/worker/tests.rs
The notion of sentry nodes has been deprecated (see [1] for details).
This commit removes support for sentry nodes in the
`client/authority-discovery` module.
While removing `Role::Sentry` this commit also introduces
`Role::Discover`, allowing a node to discover addresses of authorities
without publishing ones own addresses. This will be needed in Polkadot
for collator nodes (//CC @ordian).
polkadot companion: https://github.com/paritytech/polkadot/pull/1835
[1] https://github.com/paritytech/substrate/issues/6845
> Remove support for sentry nodes in `sc-authority-discovery`. Validator nodes running the authority discovery module will publish their own addresses on the DHT, not the addresses of their sentry nodes as done before.
=> client/authority-discovery: Remove sentry node logic

frame/balances/src/benchmarking.rs, frame/contracts/src/benchmarking/mod.rs, frame/democracy/src/benchmarking.rs, frame/identity/src/benchmarking.rs, frame/treasury/src/benchmarking.rs, frame/vesting/src/benchmarking.rs
#7381 missed the benchmarking code. This rectifies that. I just needed to sprinkle some `u32` everywhere.
=> Make benchmarks compile with latest nightly

client/finality-grandpa/src/authorities.rs
In GRANDPA there are two mechanisms for switching the authority set:
- Regular authority set changes - these are announced at a block N and enacted when that block is **finalized**. This is what should happen if GRANDPA is working properly.
- Forced authority set changes - these are announced at a block N (with some delay) and they are enacted when the block after the given delay is **imported**. Forced changes should only be triggered if the current GRANDPA authority set is not finalizing.
While syncing the chain if we encounter a block that triggers a regular authority set change we need to have a justification for it so that we can finalize it. We support having multiple pending regular authority set changes, so that we can keep importing blocks while in the background we try to sync …
=> grandpa: fix early enactment of forced changes

client/finality-grandpa/src/environment.rs, client/finality-grandpa/src/tests.rs
There's no need to send equivocation reports for keys that we control:
- If the equivocation went to the network then someone else will report it;
- Otherwise there was no harm done so the slash is unnecessary.
This can happen (and has happened) when node operators restore the database from a backup and lose the GRANDPA voter state. They might end up equivocating on an old round for which no one in the network is listening anymore (and therefore the equivocation is harmless and would go unreported), but they end up reporting themselves and getting slashed.
=> grandpa: don't send equivocation reports for local identities

bin/node/runtime/src/weights/pallet_elections_phragmen.rs, frame/elections-phragmen/src/lib.rs
A small follow up to https://github.com/paritytech/substrate/pull/7384, this is not a bug per se but the general slashing attitude of the module was still a bit too aggressive. A members who is now downgraded to a runner-up should not yet be slashed. Instead, only those that are entirely ejected (no longer member + no longer runner-up) should be slashed. 
This could also cause members who bounced back and forth between being a member and runner to lose their `CandidacyBond`.
=> Don't slash all outgoing members.

frame/support/src/traits.rs
the default implementation and its usage in substrate doesn't follow the doc.
So I replace the doc, hopefully other user don't rely on the wrong spec but just on the function name.
=> Fix doc for ChangeMember trait

client/service/Cargo.toml
Typo in the toml. The fact that tests did not fail probably means this dependency is not even used?
=> Fix typo in toml

frame/treasury/src/lib.rs
`set_pot` and `configure` do not exist in code.
=> pallet-treasury: remove non-existing dispatchables in docs

primitives/core/src/crypto.rs, ss58-registry.json
This pull request adds the ss58 prefix (14) for the Totem Live Accounting second test network (Totem Lego) which will go live shortly. It will also be used for Totem Live Accounting MainNet, and so does not make the distinction.
It changes the two files associated with config for the prefixes, and should not conflict with any other known changes at this time.
It is related to #7439 
Please review.
=> Add Totem ss58 address

client/network/src/service.rs
Adding this, as it would have detected a problem with the Polkadot testing.
=> Print an error if an unregistered notifications protocol is used

primitives/core/src/crypto.rs
This helps declaring some well known account ids as const in tests without resorting to `lazy_static` or `OnceCell`.
=> Add constant constructor to AccountId32

frame/contracts/rpc/src/lib.rs, primitives/runtime/src/lib.rs
This changes the `contracts_call` RPC so that more information is returned. The following changes are made:
* `gas_consumed` is returned in any case and not only on success.
* On error the `DispatchError` is returned instead of nothing. Can be used by the UI to pre-run a contract call and show the user what is going wrong.
*  A `debug_message` is introduced that can be used to return dynamic information. In the future, the plan is to use the field to allow outputting more precise error messages and to support println debugging. Those messages will only be collected when called by RPC and will introduce no overhead when executed as transaction. This is currently unused and will return an empty string.
This will need changes in polkadot.js API @jacogr 
Also I needed to derive `Deserialize` …
=> contracts: Rework contracts_call RPC

frame/staking/src/benchmarking.rs, frame/staking/src/testing_utils.rs
On Polkadot, the Session Benchmarks are failing because the validator we create in the benchmark isn't selected in the validator set.
This problem is caused because the Session benchmarking uses the `create_validator_with_nominators` function from Staking, but does not first clean up the existing list of validators from storage.
This PR simply moves the Validator cleanup logic into the `create_validator_with_nominators` function so anyone that uses it gets the expected outcome.
Confirmed this fix locally.
=> Fix Session Benchmarks

frame/executive/src/lib.rs
This fixes a bug in `frame_executive`/`frame_system` where the weight of runtime upgrade logic was not represented in the block.
The issue arises from the following steps:
* Perform `on_runtime_upgrade` logic (which updates weight)
* Initialize block (which clears weight)
* Process extrinsics and other stuff (starting from weight 0)
This both fixes the bug and optimizes the code such that the weight is locally tracked during the entirety of the `initialize_block_impl`, and only one storage write is used to update that weight at the end of the function.
This also takes into account the weight of `frame_system` `on_initialize` weight, which does not exist right now, but could later.
A test has been added that verifies all weights being tracked in the `initialize_block_impl` are being …
=> Fix `on_runtime_upgrade` weight recording

primitives/tracing/src/lib.rs
In `in within_span` and `enter_span`, there was a parameter `$lvl:expr`, but it was not being used in macro implementation part, in implementation all is filled `TRACE `level.
As a part of this pull request, I have modified both macros to start using `$lvl` parameter in the implementation.
Fixes #7348
=> Made correction in sp-tracing macros to use level parameter #7348

primitives/core/src/crypto.rs, ss58-registry.json
Adding new ss58 prefix for synesthesia network
=> add synesthesia network

.maintain/monitoring/alerting-rules/alerting-rules.yaml
https://github.com/paritytech/substrate/pull/7328 introduced a new task named `basic-authorship-proposer`.
This task is spawned whenever a slot is ready for the node to create a slot, and ends once the block has been created.
Unfortunately in https://github.com/paritytech/substrate/pull/7250 we made the assumption that a task that starts once, then ends once, then doesn't start again for 10 minutes, was actually probably supposed either to not end or to start again, and thus we raise an alert.
This means that if more than 10 minutes pass between the first time a node has a slot available to it and the second time a node has a slot available to it, an alert will be triggered.
In this PR I propose to special-case `basic-authorship-proposer` as a task that doesn't trigger this alert.
=> Exclude basic-authorship-proposer from the continuous tasks alert

client/finality-grandpa/src/environment.rs, client/finality-grandpa/src/tests.rs, primitives/finality-grandpa/src/lib.rs
The GRANDPA voter environment is responsible for updating (and persisting) the voter state whenever an action is performed by the voter (e.g. starting a new round, prevoting, precommitting, completing a round). In order to update the voter state it is required to figure out what is the current local authority id that is being used for voting, if none is available (i.e. we are not an active voter) then we don't need to update the voter state. Currently we always check from the keystore whenever we want to figure out what is the local authority id but this could lead to internal inconsistencies if the keystore state changes during the round, for example if a key is removed during the round we might not update the voter state after prevoting since there's no local authority id.
This PR adds …
=> grandpa: store the authority id that is used for voting per round

frame/contracts/Cargo.toml, frame/contracts/common/Cargo.toml, frame/contracts/rpc/Cargo.toml, frame/contracts/rpc/runtime-api/Cargo.toml
For the same reasons as stated in #7494 we want to hold off publishing new version of pallet_contracts until we are done with breaking changes and are ready for `3.0.0-rcX`.
=> Prevent publishing of pallet_contracts for now

client/basic-authorship/src/basic_authorship.rs, primitives/consensus/common/src/evaluation.rs, primitives/consensus/common/src/lib.rs
This pr makes the maximum block size configurable. The maximum block
size is used after proposing a new block to check if the new block is
not exceeding the maximum.
Closes: https://github.com/paritytech/substrate/issues/7492
=> Make the maximum block size configurable

frame/evm/README.md, frame/evm/src/lib.rs
I wanted to read pallet_evm source code but there was no README so I described pallet_evm README.
I put a link for the Rust documentation and wrote description according to [this page](https://substrate.dev/docs/en/knowledgebase/smart-contracts/evm-pallet).
=> Write pallet_evm README

frame/balances/src/lib.rs
Fix https://github.com/paritytech/substrate/issues/2052
Fix https://github.com/paritytech/substrate/issues/5122
Removing subtrait and elevatedtrait seems to compiles everything fine. I don't know when pallet-balances has refactored to make it so, but I can't see any usage that needs subtrait/elevatedtrait anymore. I guess it can be so since we introduced transaction-payment pallet.
Do I miss something ?
cc @gavofyork 
(This PR is needed to me as `PalletInfo::name<Module<ElevatedTrait<T, I>, I>>()` returns None. And we wan't to make storages use pallet info in the next macros. So I need either this PR or another refactor)
=> Remove pallet balances subtrait/elevatedtrait as not needed

frame/indices/src/lib.rs
Arguments for IndexAssigned and IndexFrozen were inverted in comments.
=> Fix comments of indices pallet events

client/consensus/babe/src/lib.rs
The genesis header doesn't have the BABE pre-digest and we insert `0` as
slot number. The slot lenience calculation will return the maximum in
this situation. Besides returning the maximum which is not bad at all,
it also prints some a debug message that can be confusing in the first
moment. To prevent printing this debug message, we now just return early
when we see that the parent block is the genesis block.
=> Skip slot lenience on first block in BABE

client/cli/src/params/shared_params.rs
=> Update doc for the --chain flag

frame/contracts/src/schedule.rs
This fixes a regression introduced by #7361  where most wasm blobs couldn't be put on the chain anymore. Reported by @jacogr .
=> contracts: Add missing instruction to the `Schedule`

Cargo.lock, client/cli/Cargo.toml, client/cli/src/lib.rs, client/cli/src/logging.rs, client/informant/Cargo.toml, client/informant/src/lib.rs
This fixes a regression that was introduced by the switch to tracing.
Before we killed all colors before writing to a tty, this pr brings the
behaviour back.
Fixes: https://github.com/paritytech/substrate/issues/7521
=> Don't log with colors when we are writing to a tty

client/executor/wasmtime/src/host.rs
I think it's a typo.
The `memory_new` function uses a `u32` everywhere except here, and passing a `MemoryId` for what I assume is the maximum memory size doesn't really make sense to me.
Since `MemoryId` is an alias of `u32`, this doesn't change anything.
=> MemoryId -> u32

client/cli/src/params/network_params.rs
This pr changes when to add local addresses to DHT. Instead of only
checking if `--discover-local` and `--dev` are present, we now also
check if the chain type is `Local` or `Development`.
=> Enable local addresses in DHT when chain type == `Local` | `Development`

Cargo.lock, primitives/core/Cargo.toml
It improves secret zeroization due to https://github.com/maciejhirsz/tiny-bip39/pull/22.
`tiny-bip39` v0.8 also gets rid of `failure` dependency (we still rely on it from other places in our dependency graph), since it is [deprecated](https://github.com/rust-lang-nursery/failure/pull/347).
=> Update tiny-bip39 to v0.8

frame/executive/src/lib.rs
We call `offchain_worker` with the state of the imported block and pass
the header of this block. However in the runtime we call all
`offchain_worker` functions with the number of the parent block. Besides
that we also pass all digests and not only the pre runtime digests. In
the context where the offchain worker is executed we have all digests, so
there is no real reason to only pass pre runtime digests. Another fix is
that we also insert the hash of the current header into the block hash map.
=> Fix some weirdness in `offchain_worker`

client/service/src/lib.rs
I didn't realize when making #7528 that one of the arguments to `new` was private as well 😅
=> Make ClientConfig Public

Cargo.lock, client/basic-authorship/Cargo.toml
=> sc-basic-authorship: remove useless dependencies

frame/elections-phragmen/src/lib.rs
As an aftermath of https://github.com/paritytech/substrate/pull/7384, it is sensible and very useful to exactly deposit events for slashing. This is an important event, and should not happen too often anymore. In the past there was no event so we had to rely on `Treasury::deposit` to guess which slashings happened.
=> Add slashing events to elections-phragmen.

Cargo.lock, client/cli/Cargo.toml
=> sc-cli: replace bip39 with tiny-bip39

frame/support/src/traits.rs
During some internal discussions it turned out it's unclear that `on_initialize` is called before all extrinsics (including inherent extrinsics), this PR attempts to add some extra docs to emphasize that.
Note there is already a doc on the trait level, but I chose to add it on the function level as well.
=> Add extra docs to on_initialize

Cargo.lock, client/network/Cargo.toml, client/network/src/protocol/generic_proto/handler.rs
update some dependencies to prune some duplicated dependencies in dep graph.
It seems that dependabot can't detect duplicate dependencies?
=> sc-network: update some dependencies

.gitlab-ci.yml
- build docs after test and build are successful
- remove `allow_failure` from build docs
=> Publish docs each time test and build are successful on master

bin/node-template/node/src/service.rs
When building the import pipeline for the light client we were not using the `AuraBlockImport` which meant that some aura-specific block validation logic was not being run.
=> node-template: add aura to light block import pipeline

client/network/src/protocol/generic_proto/handler.rs
In the `poll` function of `handler.rs`, we first call `Sink::poll_flush` on all the outbound substreams, then only call `Sink::start_send`. This means that the actual flushing is only done the next time `poll` is called, which is in no way guaranteed to happen soon.
While this little fix might seem like a hack, and it would be preferable to change the order of operations in `poll`, doing so is a bit tricky to me because of having to handle state transitions when the substream errors. Since this code is undergoing another rewrite in #7374, I went for the easy solution.
=> Fix notifications sometimes not being sent

frame/support/src/lib.rs
This PR removes feature checking for std environments for some assert macros in `frame_support` as there does not seem to be a strong reason to limit them to `std` and they are useful for checks in runtime benchmarking.
~~Also removes an outdated doc line about only using the `parameter_types` macro in std code.~~
Moves the comment into the list item.
=> remove std feature flags for assert macros

client/rpc-servers/src/middleware.rs, client/service/src/builder.rs, client/service/src/lib.rs
The metrics was returning an error when prometheus was not given. This
was a really weird setup, especially when compared to all other metrics
that just do nothing if there is no registry.
=> Remove `RpcMetrics` weirdness

Cargo.lock, bin/node/browser-testing/Cargo.toml, client/authority-discovery/Cargo.toml, client/authority-discovery/src/error.rs, client/authority-discovery/src/worker.rs, client/authority-discovery/src/worker/addr_cache.rs, client/cli/Cargo.toml, client/network-gossip/Cargo.toml, client/network/Cargo.toml, client/network/src/discovery.rs, client/network/src/lib.rs, client/network/src/light_client_handler.rs, client/network/src/peer_info.rs, client/network/src/protocol.rs, client/network/src/request_responses.rs, client/network/src/service.rs, client/network/src/transport.rs, client/network/test/Cargo.toml, client/peerset/Cargo.toml, client/telemetry/Cargo.toml, frame/support/procedural/tools/Cargo.toml, primitives/consensus/common/Cargo.toml, utils/browser/Cargo.toml
This PR upgrades substrate to `libp2p-0.31`. Highlights:
* Multihash upgrade.
* Fixed `ls` response encoding for `multistream-select`. This will eventually be followed-up by https://github.com/libp2p/rust-libp2p/issues/1847.
* More control over the scores and thus retention and ordering of external (e.g. observed) addresses, including the ability to add external addresses to a `Swarm` with an "infinite" retention. Thereby closes https://github.com/paritytech/substrate/issues/7518.
* Limited initial buffer allocation when decoding multi-addresses (https://github.com/libp2p/rust-libp2p/pull/1833).
* The `V1Lazy` multistream-select negotiation variant is now interoperable with `V1` on the wire and configured to be used exclusively in substrate with this PR, both for transport and substream …
=> Upgrade to libp2p-0.31.

bin/node-template/node/src/cli.rs, bin/node-template/node/src/command.rs
as it says on the tin. Our node-template didn't have this integrated yet, which I found out when trying to use it. No reason to not just quickly add it (just copy-pasted).
=> Add Key Subcommand to node-template

client/consensus/manual-seal/src/lib.rs, client/consensus/manual-seal/src/seal_block.rs
This prevents nodes from executing the same block 2 times.
=> Forward storage changes in manual seal

client/network/src/protocol.rs
There are 2 situations where we send out block announcements:
- after importing a block
- after voting on a block in GRANDPA
Currently we are always force-sending the block announcement even if the peer already knows this block, which can lead to duplicating block announcements in the following situations:
- multiple GRANDPA votes on the same block (on prevote and precommit but also potentially across different rounds)
- we import a block from a peer and then re-announce it again to it
I think we can relax the force-sending of announcements. The only worry would be missing some fork that is needed to process some GRANDPA votes, but we already have the reverse mechanism where peers will actively try to sync these forks.
=> network: don't force send block announcements

client/network/src/protocol/generic_proto/behaviour.rs, client/network/src/protocol/generic_proto/handler.rs, client/network/src/service.rs
The incoming notifications are properly logged, but not the outgoing notifications. This fixes the situation.
Additionally now also prints the size of the notifications in the logs.
=> sc-network: Log outgoing notifications too

frame/sudo/src/lib.rs, frame/sudo/src/tests.rs
This is a super tiny PR which has the `SudoAsDone` event from the `sudo_as` extrinsic return a `Result` with the dispatch error rather than a bool.
The Result allows people to actually see what went wrong! (and is consistent with the more used `sudo` call.
=> `sudo_as` Returns a Result

client/network/src/protocol/generic_proto/handler.rs
Fixes a potential state inconsistency.
=> Fix wrong value put for pending_opening

Cargo.lock, client/consensus/slots/src/lib.rs, client/executor/common/src/error.rs, client/executor/src/integration_tests/mod.rs, client/executor/src/native_executor.rs, client/transaction-pool/graph/src/error.rs, primitives/allocator/Cargo.toml, primitives/allocator/src/error.rs
=> resolve unresolved error nits of #7617

client/network/src/protocol/generic_proto/behaviour.rs
In the `DisabledPendingEnable` state, the peerset thinks we have already have a substream with the remote, but it is not actually the case.
If a `OpenDesiredByRemote` event is then received, we shouldn't ask the peerset whether the peer is allowed or not, since the peerset thinks it's already in a connected state.
Instead, we should immediately accept the remote's request and transition the peer to the `Enabled` state.
=> Fix bad state transition with DisabledPendingEnable+OpenDesiredByRemote

frame/assets/README.md, frame/atomic-swap/README.md, frame/aura/README.md, frame/balances/README.md, frame/contracts/README.md, frame/democracy/README.md, frame/elections-phragmen/README.md, frame/example-offchain-worker/README.md, frame/example/README.md, frame/identity/README.md, frame/im-online/README.md, frame/multisig/README.md, frame/nicks/README.md, frame/proxy/README.md, frame/recovery/README.md, frame/scheduler/README.md, frame/scored-pool/README.md, frame/session/README.md, frame/society/README.md, frame/staking/README.md, frame/sudo/README.md, frame/system/README.md, frame/timestamp/README.md, frame/treasury/README.md, frame/utility/README.md, frame/vesting/README.md
=> Fix CI Link Check

client/peerset/src/lib.rs, client/peerset/src/peersstate.rs, client/peerset/tests/fuzz.rs, primitives/utils/src/mpsc.rs, primitives/utils/src/status_sinks.rs
Fix cargo clippy warning in peerset, except the `mutable_key_type`. this needs the PeerId change to be merged https://github.com/libp2p/rust-libp2p/pull/1865.
Now, run cargo clippy --all-targets -- -A clippy::mutable_key_type  in peerset, not warning raise.
=> Fix cargo clippy warning in peerset.

client/finality-grandpa/src/authorities.rs, utils/fork-tree/src/lib.rs
We want to keep the fork tree nodes sorted by subtree depth, this is an heuristic since the deepest subtree will most likely translate to the longest chain, in which case any query on the tree will most likely want to target the longest branch. To this end, after inserting a new node in the tree we make sure it is rebalanced. Currently we were only triggering the rebalancing when the new node being inserted was a new root, and not when it was a leaf node part of an already existing subtree.
I also fixed the initial state of the tree iterator which would mess up the ordering.
=> fork-tree: fix tree rebalancing

client/peerset/src/lib.rs
All reputation changes are printed except these ones.
This reduces the confusion.
=> Show reputation changes when dropping peer

Cargo.lock, client/authority-discovery/Cargo.toml, client/cli/Cargo.toml, client/network-gossip/Cargo.toml, client/network/Cargo.toml, client/network/test/Cargo.toml, client/peerset/Cargo.toml, client/telemetry/Cargo.toml, primitives/consensus/common/Cargo.toml
Update libp2p to `v0.31.2` to include https://github.com/libp2p/rust-libp2p/pull/1871 which fixes https://github.com/paritytech/substrate/pull/7478#issuecomment-736803765.
=> *: Update to libp2p v0.31.2

frame/support/src/storage/types/double_map.rs, frame/support/src/storage/types/map.rs, frame/support/src/storage/types/value.rs, frame/support/src/traits.rs
`StorageInstance` is introduced to be used alongside storage types. It was meant to be implemented by macro, thus I tried to make it as straightforward as possible to implement from the macro (just some associated type and constant). But this is a rather ugly trait and it is less usable then.
Thus this PR refactors it to make it more usable and idiomatic.
=> Refactor `StorageInstance` trait to be usable more easily

.maintain/frame-weight-template.hbs, utils/frame/benchmarking-cli/src/template.hbs, utils/frame/benchmarking-cli/src/writer.rs
Fixes https://github.com/paritytech/substrate/issues/7648
This PR extracts the Standard Error from the regression model in the Weight analysis and places that as a comment in the weight files.
=> Add Standard Error to Weight Template

client/network/src/protocol/generic_proto/behaviour.rs
We've noticed on Rococo some errors about peers being in a `Poisoned` state.
I reviewed `behaviour.rs` for all places where we potentially leave a poisoned state, and found these two.
=> Fix two potential connection poisonings

primitives/core/Cargo.toml
On behalf of dependabot, because we use 1.4.x somewhere in cli and it clashes with this.
=> Bump regex dep

primitives/rpc/src/number.rs
Fix https://github.com/paritytech/substrate/issues/7674
Implement more convertion trait on `NumberOrHex` and refactor others
=> Implement more convertion trait on `NumberOrHex`

.github/allowed-actions.js, .github/workflows/md-link-check.yml, .github/workflows/mlc_config.json
- pins the md link checker's version to the previous release as the current version, to mitigate [this](https://github.com/tcort/markdown-link-check/issues/142) issue
- introduces a whitelist with pinned versions, [as done](https://github.com/github/docs/blob/main/.github/allowed-actions.js) by github
=> Pin md link checker's version

frame/session/src/lib.rs, frame/session/src/mock.rs, frame/session/src/tests.rs
We need this for Polkadot - we'll be adding new "approvals" and "assignments" keys to the Kusama and Polkadot runtimes in advance of launching parachains.
The plan is to prepare an `on_runtime_upgrade` for each of those runtimes that invokes this method. Then we will issue a call to action for the validator communities to rotate their keys. We will only deploy once a vast majority of validators have updated their session keys.
=> add an upgrade_keys method for pallet-session

frame/benchmarking/src/analysis.rs, frame/benchmarking/src/lib.rs, utils/frame/benchmarking-cli/src/writer.rs
cc @athei @s3krit 
When a benchmark has no components, a model is not formed, and the unwrap results in a panic.
This solves that problem by generating an iterator of 0s in that case.
Fix: https://github.com/paritytech/polkadot/issues/2091
=> Fix panic in case of a missing model

Cargo.lock, bin/node/browser-testing/Cargo.toml, client/authority-discovery/Cargo.toml, client/cli/Cargo.toml, client/network-gossip/Cargo.toml, client/network/Cargo.toml, client/network/test/Cargo.toml, client/peerset/Cargo.toml, client/telemetry/Cargo.toml, primitives/consensus/common/Cargo.toml
Version v0.32.2 pins async-tls to the semver compliant v0.11.0 instead
of the yanked async-tls v0.10.2.
=> *: Update to libp2p v0.32.2

frame/support/src/debug.rs
Most pallets have `sp_io` anyhow, but still better to not depend on it being in scope directly.
=> Allow runtime_debug! where sp_io is not there

frame/system/benchmarking/src/lib.rs
Closes https://github.com/paritytech/polkadot/issues/2103
The code before #6629 was using `MaximumBlockLength` not weight. I don't really understand why the benchmarks worked just fine in the substrate repo, @shawntabrizi ?
CC @s3krit
=> Fix polkadot benchmarks for remark.

frame/staking/src/lib.rs, frame/staking/src/mock.rs, frame/staking/src/tests.rs
Current staking system allowed dust accounts to be created as such: 
1. Bond 1 DOTs
2. Unbond 1 DOTs
3. Bond-extra a tiny amount. 
Reported by @joepetrowski, example [here](https://polkadot.subscan.io/account/13SA1F2dEd7o45wQJZhPUwccFjWRtD2BaTVF3MSnRYNMtSd7), similarly, you could do the same with `rebond`.
I think the current logic is sane because we allow the `ledger.active` to either be `0`, in which case when you `withdraw` your funds your account gets deleted, or be greater than ED. As a safety measure I also change the condition here: if while `withdraw` your `ledger.active` is less than ED, then bye bye 👋🏻.  
An interesting migration-like task is to go and sweep the chain with remote-externalities and see if we have any dust accounts. In essence, I think no account should have …
=> Prevent dust in staking by disallowing cheap bond_extra

client/network/src/protocol.rs, client/network/src/protocol/sync.rs, primitives/consensus/common/src/block_validation.rs
If we are using the default block announce validator and receive
additional data alongside the block announcement, we should disconnect
this peer.
=> Default block announce validation should reject additional data

bin/node/cli/src/chain_spec.rs, frame/balances/src/lib.rs, frame/balances/src/tests.rs
as reported by https://github.com/paritytech/substrate/issues/7713, almost insubstantial.
=> remove duplicate accounts in chain-spec.

frame/executive/src/lib.rs, frame/system/src/lib.rs
This change leaves some header related data in chain after block finalization, notably the block number.
During working on Polkadot it's been discovered that removing this data eagerly leads to `System::block_number()` to return 0 if called in the context of a runtime API based on an in-chain block. 
This PR solves that by leaving in in-chain until the next call to `on_initialize` where it gets overwritten. While I was at it I also changed that for other header related data.
=> Leave some header related info for inspection

primitives/runtime/src/transaction_validity.rs
The `AncientBirthBlock` transaction validity error is a bit nuanced and the current doc comment relies on a rather cyclical explanation. 
I think giving the reader starting points for clarifying what constitutes a birth block and what makes one ancient is a cheap way to improve the debugging experience for transaction creators. I attempt to do that in this PR while keeping it concise.
I based these off of the [docs here](https://docs.rs/sp-runtime/2.0.0/sp_runtime/generic/enum.Era.html#variant.Mortal) and the [logic here](https://github.com/paritytech/substrate/blob/237874bb15bbac174b6cb8d594053b5512f32ca2/frame/system/src/extensions/check_mortality.rs#L59-L82)
cc @dvdplm, @joepetrowski
=> Improve `InvalidTransaction::AncientBirthBlock` doc comment

Cargo.lock, frame/support/test/Cargo.toml, primitives/api/test/Cargo.toml, primitives/runtime-interface/Cargo.toml, test-utils/Cargo.toml
My fix was merged on upstream and this release contains it. So, no
more reason to keep the git dependency.
=> Switch back to the crates.io release of trybuild

primitives/core/src/crypto.rs, ss58-registry.json
Adding a key prefix(35) for the Valiu Liquidity Network mainnet.
=> Add account prefix for Valiu

bin/node/runtime/src/lib.rs, frame/babe/src/lib.rs, primitives/consensus/babe/src/lib.rs, test-utils/runtime/src/lib.rs
I wasn't sure exactly which release level or 'B' label to tag this with. I set the 'C' label to medium but I could see it being low as well. We just need to add this runtime API in a runtime upgrade before we enable the approvals protocol.
We either need this or something that lets us inspect the internal state of BABE much better for Polkadot's approval voting protocol which does self-assignment based on randomness derived from the VRF outputs in the header-chain. For that, we need to reconstruct the transcript that the VRF is produced with, which includes the epoch index, authority public key, and epoch randomness.  This API seemed generally useful anyway, and much easier to do than the alternative.
polkadot companion: https://github.com/paritytech/polkadot/pull/2170
=> add a `current_epoch` to BabeApi

frame/staking/src/tests.rs
Fix testing for number of slashing spans.
Thank you!
=> Fix testing for number of slashing spans.

client/consensus/babe/src/lib.rs
Will be used in approval-voting in Polkadot
=> add a slot-duration getter to babe config

bin/node-template/node/src/chain_spec.rs
This PR updates the node template's `chain_spec.rs` file to comply with Clippy's `or_fun_call` lint. Althoug hSubstrate itself does not enforce Clippy, many projects that start from the node template may, and this is a reasonable change in any case.
According to https://rust-lang.github.io/rust-clippy/master/index.html,
=> Lazily evaluate error string

frame/contracts/rpc/src/lib.rs
This allows the `contracts_call` RPC to handle `Balance` as a hex input by using `NumberOrHex`. It follows the same pattern as the `gas_limit` which already allows for non-number values to be supplied.
Closes https://github.com/paritytech/substrate/issues/7806
=> Hex Balance deserialize for contracts_call RPC

frame/proxy/src/lib.rs, frame/proxy/src/tests.rs
Fixes https://github.com/paritytech/substrate/issues/7799
AFAIK there is no scenario where it makes sense to make yourself a proxy of your own account... so let's throw an error to avoid people and UIs getting confused.
=> Don't allow Self Proxies

frame/benchmarking/src/lib.rs
This is a insignificant change to the `add_benchmark!` macro where we expect a `path` instead of an `ident` for the name of the crate.
This allows us to use a name like: `runtime_common::claims` where the pallet we are interested in benchmarking is actually a submodule of a crate like `runtime_common`. This allows most automation pipeline to continue to work without needing to fork extra logic, particularly on Polkadot where specific pallets aren't their own crate.
This has a small unfortunate effect that to run a benchmark, you must reference the crate as `runtime_common::claims`, but not much can be done about that I think.
=> Use Path instead of Ident for Benchmarking `add_benchmark!`

frame/transaction-payment/rpc/src/lib.rs, frame/transaction-payment/src/lib.rs
T doesn't need to implement Sync and Send in order to TransactionPayment to implement Sync and Send. Thus I removed these bounds.
=> Remove some unecessary bound in transaction-payment

primitives/core/src/ecdsa.rs
There was a bug that could make other ss58 tests fail when being
executed with this one in parallel. This test changes the default ss58
version and if other tests are run at the time the default version is
changed, they would fail. To fix this problem, we now run the actual
test as a new process.
=> Fix ss58check test when executed with other tests

frame/support/procedural/src/storage/print_pallet_upgrade.rs
In the last iteration of pallet macro we made the macro declare `Module` type alias to be used by construct_runtime (instead of changing construct_runtime).
Thus the helper provided by decl_storage is wrong.
=> Fix the upgrade helper provided by decl_storage

frame/contracts/src/schedule.rs, frame/contracts/src/wasm/runtime.rs
Fixes #5379
This fixes a possibly exploitable issues with regard to the memory allocator:
When reading from contract memory a buffer to hold this memory inside the runtime was pre-allocated with a size supplied by the untrusted contract. While the gas for allocating such a buffer is charged before allocatting it is still possible that the sender is able to pay for a buffer that is larger than the maximum allowed allocation size (16MiB) which will in turn panic the runtime opening up a DoS vector.
=> contracts: Prevent contracts from allocating a too large buffer

Cargo.lock, frame/support/procedural/Cargo.toml, frame/support/procedural/src/pallet/expand/call.rs, frame/support/procedural/src/pallet/expand/constants.rs, frame/support/procedural/src/pallet/expand/error.rs, frame/support/procedural/src/pallet/expand/event.rs, frame/support/procedural/src/pallet/expand/genesis_build.rs, frame/support/procedural/src/pallet/expand/hooks.rs, frame/support/procedural/src/pallet/expand/pallet_struct.rs, frame/support/procedural/src/pallet/expand/storage.rs, frame/support/procedural/src/pallet/expand/store_trait.rs, frame/support/procedural/src/pallet/expand/type_value.rs, frame/support/procedural/src/pallet/parse/call.rs, frame/support/procedural/src/pallet/parse/config.rs, frame/support/procedural/src/pallet/parse/error.rs, frame/support/procedural/src/pallet/parse/event.rs, frame/support/procedural/src/pallet/parse/genesis_build.rs, frame/support/procedural/src/pallet/parse/hooks.rs, frame/support/procedural/src/pallet/parse/mod.rs, frame/support/procedural/src/pallet/parse/pallet_struct.rs, frame/support/procedural/src/pallet/parse/storage.rs, frame/support/procedural/src/pallet/parse/type_value.rs, frame/support/src/lib.rs, frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr, frame/support/test/tests/pallet_ui/store_trait_leak_private.stderr, frame/support/test/tests/pallet_ui/type_value_forgotten_where_clause.rs, frame/support/test/tests/pallet_ui/type_value_forgotten_where_clause.stderr
This PR does 2 things:
1 - Improve spans of most code generations: all code generated are span from the attribute which generates them. (note: the generated code should be correct when the user rust code is correct. Thus if it is failing the first error should generally be in the user code, not in the expansion, an exception to that is the trait store, if the trait store is public and some storages are private then the rust error will point to generated code, but this is in ui tests and error is good I think).
2 - Improve error message of type_value: before we were removing the user code and generating the struct and implement get on the struct. Now we keep the user code, change the function name to an internal name and generate the struct and impl get by calling the function written by …
=> Improve spans of pallet macro

bin/node/runtime/src/lib.rs, frame/babe/src/lib.rs, frame/babe/src/mock.rs, frame/babe/src/tests.rs, primitives/consensus/babe/src/lib.rs, test-utils/runtime/src/lib.rs
In BABE next epoch data is announced one epoch in advance, i.e. when we start epoch N we announce the details for epoch N+1. Currently the information about the upcoming epoch is not exposed from the runtime, this PR adds a runtime API to be able to query this data. This will be useful for warp sync clients that will rely on finality to warp to the latest block (i.e. GRANDPA) and will thus be able to fetch all epoch data necessary to validate subsequent BABE blocks from the runtime (rather than having to fetch this data from past block headers).
polkadot companion: https://github.com/paritytech/polkadot/pull/2200
=> babe: expose next epoch data
