Cargo.lock
client/chain-spec/derive/Cargo.toml
client/cli/proc-macro/Cargo.toml
client/executor/Cargo.toml
client/executor/src/integration_tests/mod.rs
client/executor/src/integration_tests/sandbox.rs
frame/staking/reward-curve/Cargo.toml
frame/support/procedural/Cargo.toml
frame/support/procedural/src/storage/parse.rs
frame/support/procedural/tools/Cargo.toml
frame/support/procedural/tools/derive/Cargo.toml
primitives/api/proc-macro/Cargo.toml
primitives/debug-derive/Cargo.toml
primitives/npos-elections/compact/Cargo.toml
primitives/runtime-interface/proc-macro/Cargo.toml
test-utils/derive/Cargo.toml

Instead of using `syn::exports` we should import the trait from the
quote crate directly.
Fixes: https://github.com/paritytech/substrate/issues/7836

Fix incorrect use of syn::exports

---

Cargo.lock
bin/utils/subkey/Cargo.toml
bin/utils/subkey/src/lib.rs
bin/utils/subkey/src/main.rs

There is no reason for subkey to import the default Substrate node to
support a feature that would only be usable for the Substrate node.
Subkey itself should be more the default key management binary for
Substrate related chains. If certain chains require some special
functionality, they can easily stick together their own "my-chain-key".

Subkey should not import the entire world.

---

Cargo.lock

To include this change https://github.com/debris/fs-swap/pull/10
One less issue when building on M1. The only other one is rust-rocksdb.

bump fs-swap

---

primitives/core/src/crypto.rs
ss58-registry.json

Hello,
This PR adds a new ss58 address 38 for UniArts network.
Thank you!

UniArts reserve SS58 address id 38

---

Cargo.lock
bin/node/browser-testing/Cargo.toml
bin/node/cli/Cargo.toml
client/authority-discovery/Cargo.toml
client/basic-authorship/Cargo.toml
client/cli/Cargo.toml
client/consensus/aura/Cargo.toml
client/consensus/babe/Cargo.toml
client/consensus/manual-seal/Cargo.toml
client/consensus/slots/Cargo.toml
client/finality-grandpa/Cargo.toml
client/informant/Cargo.toml
client/keystore/Cargo.toml
client/network-gossip/Cargo.toml
client/network/Cargo.toml
client/network/test/Cargo.toml
client/offchain/Cargo.toml
client/offchain/src/api/timestamp.rs
client/peerset/Cargo.toml
client/telemetry/Cargo.toml
client/transaction-pool/graph/Cargo.toml
primitives/blockchain/Cargo.toml
primitives/consensus/common/Cargo.toml
primitives/utils/Cargo.toml
test-utils/client/Cargo.toml
test-utils/runtime/client/Cargo.toml

I'm opening this PR mostly for that one line change in `sc-offchain`.
Without this little change, Substrate doesn't compile with futures 0.3.9.

Update to futures 0.3.9

---

frame/multisig/src/lib.rs
frame/recovery/src/lib.rs
frame/sudo/src/lib.rs
frame/utility/src/lib.rs

The weight functions for some extrinsics were not very efficient in that they called the `dispatch_info()` function for the same call multiple times.
This PR optimizes that behavior so that this function is only ever called once, then stored in a local variable which can be reused.
closes https://github.com/paritytech/srlabs_findings/issues/34

Store dispatch info of calls locally in weight calculation

---

client/network/src/light_client_handler.rs

Unit tests in `light_client_handler.rs`  were disabled in https://github.com/paritytech/substrate/pull/7700. This pull request re-enables them.

client/network: Re-enable light_client_handler.rs unit tests

---

ss58-registry.json

Uniarts network missed a `network` key in `ss58-registry.json`, this PR fixes that.
Fixes #7651

Fix missing network for uniarts

---

.gitlab-ci.yml

[The release has major improvements](https://github.com/paritytech/cargo-unleash/releases/tag/v1.0.0-alpha.11), not the last of them being a terms-of-service-compliant index-fetching.
Note: Because alpha.10 is doing the index fetching in a pretty bad way and apparently, unleash is used more and more, the sysadmins of crates.io consider banning it.

Bump cargo-unleash to latest alpha release

---

.maintain/monitoring/alerting-rules/alerting-rules.yaml

Fix #7856 
I have successfully tested the alerting rule (with a smaller constant).
For what it's worth, the second rule (more than 5000 items) would have been triggered once in the past week, as a channel contained 18000 items for a brief moment.
As usual with Prometheus rules, we should make sure, after merging this PR, that the deployment through CI properly works.

Add Prometheus alerts if unbounded channels are too large

---

frame/babe/src/lib.rs
frame/babe/src/tests.rs

https://github.com/paritytech/substrate/pull/7829 introduced a method to fetch the next epoch data. When starting the chain the first and second epoch use the same data, i.e. same authorities and randomness. This PR fixes genesis initialization of `NextAuthorities` storage entry.

babe: initialize next authorities on genesis

---

Cargo.lock

There was an incompatibility between `serde` and `parity-multiaddr`.
It appears that our CI on master somehow doesn't use our Cargo.lock, which triggers this.

Update serde and parity-multiaddr, to fix master CI

---

Cargo.lock
client/finality-grandpa/src/communication/mod.rs
client/network-gossip/Cargo.toml
client/network-gossip/src/bridge.rs
client/network-gossip/src/state_machine.rs

This is useful to debug if any gossip validator might be leaking messages (i.e. by not expiring them).
Additionally this PR also increases the known messages cache size of network-gossip. This is to accommodate the increasing number of kusama validators. ~800 validators -> ~1600 GRANDPA messages per round -> we keep track of the last 2 completed rounds plus the current one -> ~4800 messages.
Setting this cache to 8192 should use about 256KB of memory (8192 * 32 bytes per block hash).

network-gossip: add metric for number of local messages

---

client/network/src/protocol.rs
client/network/src/protocol/message.rs

This PR does some straight-forward clean ups of `protocol.rs`.
Can be reviewed commit by commit if necessary.
The statistics system removed in the first commit is something that existed before Prometheus was introduced and is now completely obsolete.

Clean-up pass in network/src/protocol.rs

---

.gitlab-ci.yml

- `test-prometheus-alerting-rules:` is now on check phase and starts if only mentioned files are edited, on any branch
- `deploy-prometheus-alerting-rules:` now starts right away after the test is green, but only on `master` AND if those files are changed.
- `*kubernetes-build` jobs actually do not require a special environment since they are not the deployments, this was an unnecessary complication
- some chore

CI: test and deploy prometheus alerts streamlined

---

frame/contracts/src/exec.rs
frame/contracts/src/lib.rs
frame/contracts/src/storage.rs
frame/contracts/src/wasm/mod.rs
frame/contracts/src/wasm/runtime.rs

Fixes #2672
For the reasons explained in the linked issue we replace unchecked and saturating math by checked math. Every contract call that tries to accumulate more storage than can be hold by the `u32` type will be trapped.
It is extremely unlikely that such a large contract will be economically feasible.

contracts: Fix possible overflow in storage size calculation

---

frame/contracts/src/benchmarking/mod.rs
frame/contracts/src/lib.rs
frame/contracts/src/rent.rs
frame/contracts/src/storage.rs
frame/contracts/src/tests.rs

Contracts which are no longer able to pay their rent need to be removed from the chain in order to reclaim the space they occupy. In order to do so a `claim_surcharge` dispatchable can be submitted which in case of success rewards some newly minted balance to the sender (`SurchargeReward`).
Depending on the value of `SurchargeReward` and the current weight price it is possible that a situation may arise where the costs of creating a minimal contract is lower than the `SurchargeReward` gained when removing this contract. This would incentivise to create contracts for the sole reason to remove them and make a profit.
This PR  thwarts this unwanted behaviour by recording the rent a contract payed over its lifetime and cap the `SurchargeReward` by this amount.
Additionally, we make any …

contracts: Cap the surcharge reward by the amount of rent that way payed by a contract

---

client/tracing/src/logging.rs

As requested, this moves the target before the prefix to have consistent
logging between logs with and without a prefix.

Log target before prefix for more consistent logging

---

frame/contracts/src/benchmarking/mod.rs

The logic of this `assert!` was flawed. It slipped though the cracks because it was the result of two PRs that were merged at roughly the same time.

contracts: Fix failing benchmark test

---

Cargo.lock
bin/node/browser-testing/Cargo.toml
client/authority-discovery/Cargo.toml
client/cli/Cargo.toml
client/network-gossip/Cargo.toml
client/network/Cargo.toml
client/network/src/protocol/generic_proto/upgrade/legacy.rs
client/network/src/protocol/generic_proto/upgrade/notifications.rs
client/network/test/Cargo.toml
client/peerset/Cargo.toml
client/telemetry/Cargo.toml
primitives/consensus/common/Cargo.toml
utils/browser/Cargo.toml

Most notable changes with `libp2p` `v0.34.0` relevant for Substrate:
- `libp2p-tcp`: Use just `async-io` instead of `async-std` (which under the hood would use `async-io`). Watch for interface changes when using `async-io`, still poll for interface changes on an interval when using `tokio`. See https://github.com/libp2p/rust-libp2p/pull/1887.
- `libp2p-websocket`: Switch `async-tls` to `futures-tls` and thus update `rustls` to `v0.19`. See https://github.com/libp2p/rust-libp2p/pull/1889.
To keep dependencies in sync this pull request also updates
- `bytes` to `v1.0` in `client/network`
- `prost` to `v0.7`
-  `unsigned-varint` to `v0.6`
- Switch from `futures-codec` to `asynchronous-codec`. See https://github.com/libp2p/rust-libp2p/pull/1908.

*: Update to libp2p v0.34.0

---

frame/support/procedural/src/storage/print_pallet_upgrade.rs

just the template wasn't renamed when we decided to change interface to hooks.
thanks @ascjones

Fix decl_storage provided template to migrate to `pallet!`

---

client/network/src/protocol/generic_proto/behaviour.rs

Context: we replace the current state of a peer with `Poisoned` with the intention of later putting back the proper state.
In that specific situation where a substream on a secondary connection gets closed, we didn't put back the proper state.
I've tried to figure out why it is this way (is it some missing code instead?), and I can't find any explanation other than a mistake.
I've also reviewed again the rest of the state machine, and can't find any place where we leave a `Poisoned` state.

Fix not restoring non-poisoned state

---

frame/benchmarking/src/lib.rs
frame/benchmarking/src/tests.rs

This is a test that shows an example of how you can use an expression for a lower_bound of a benchmark.
I tried to add:
```
// mutation arm to look for an expression for param_from.
(
{ $( $instance:ident )? }
$name:ident
{ $( $where_clause:tt )* }
{ $( $parsed:tt )* }
{ $eval:block }
{
let $param:ident in $param_from:expr .. $param_to:expr => $param_instancer:expr ;
$( $rest:tt )*
}
$postcode:block
) => {
$crate::benchmark_backend! {
{ $( $instance)? }
$name
{ $( $where_clause )* }
{ $( $parsed )* }
{ $eval }
{
let $param in ( $param_from ) .. $param_to => $param_instancer;
$( $rest )*
}
$postcode
}
};
```
But got the error:
```
error: `$param_from:expr` is followed by `..`, which is not allowed for `expr` fragments
--> frame/benchmarking/src/lib.rs:480:41
|
480 |             let …
```

Add Test for Variable Components in Benchmarking

---

bin/node-template/pallets/template/src/lib.rs

Common projects use cargo fmt
original cargo fmt
decl_event!(
pub enum Event<T>
where
AccountId = <T as frame_system::Trait>::AccountId,
{
/// Event documentation should end with an array that provides descriptive names for event
/// parameters. [something, who]
SomethingStored(u32, AccountId),
}
);
now cargo fmt
decl_event! {
pub enum Event<T> where AccountId = <T as frame_system::Trait>::AccountId {
/// Event documentation should end with an array that provides descriptive names for event
/// parameters. [something, who]
SomethingStored(u32, AccountId),
}
}

fix cargo fmt

---

primitives/core/src/crypto.rs
ss58-registry.json

Adding a key prefix(26/27) for the Jupiter testnet/Patract mainnet.

Add ss58 version prefix for Patract/Jupiter (from PatractHubs)

---

client/cli/src/params/network_params.rs
client/network/src/config.rs
client/network/src/service.rs
client/network/src/transport.rs

See the code comment for details.
Context: Polkadot at the moment tries to send large (3.5MiB) collations through a notifications protocol, with a one second timeout. This can't work right now. See https://github.com/libp2p/rust-libp2p/issues/1849.
In the long term we would like Polkadot to use a request-response protocol for collations, which alongside with https://github.com/libp2p/rust-libp2p/issues/1849, would allow acceptable transfer rates.
The intention with this PR is to set this value to something large in Polkadot, in order to permit large collations to be sent for as long as everything isn't properly implemented.

Allow configuring Yamux window size

---

Cargo.lock
Cargo.toml
frame/staking/src/benchmarking.rs
frame/staking/src/lib.rs
frame/staking/src/mock.rs
frame/staking/src/offchain_election.rs
frame/staking/src/testing_utils.rs
primitives/election-providers/Cargo.toml
primitives/election-providers/src/lib.rs
primitives/election-providers/src/onchain.rs
primitives/npos-elections/Cargo.toml
primitives/npos-elections/benches/phragmen.rs
primitives/npos-elections/compact/src/assignment.rs
primitives/npos-elections/compact/src/lib.rs
primitives/npos-elections/fuzzer/src/phragmen_balancing.rs
primitives/npos-elections/fuzzer/src/phragmms_balancing.rs
primitives/npos-elections/fuzzer/src/reduce.rs
primitives/npos-elections/src/helpers.rs
primitives/npos-elections/src/lib.rs
primitives/npos-elections/src/mock.rs
primitives/npos-elections/src/phragmen.rs
primitives/npos-elections/src/phragmms.rs
primitives/npos-elections/src/tests.rs

Attempt to break down  #7319.  Part 1
Part 2: https://github.com/paritytech/substrate/pull/7909
Part 3: https://github.com/paritytech/substrate/pull/7910
Only contains the support traits.

Decouple Stkaing and Election - Part1: Support traits

---

frame/bounties/src/lib.rs

Expose BountyUpdatePeriod constant in the Bounty Pallet.
We're developing UI for Bounties and thought it would be cool to show the Curator additional context when initiating the `extend_bounty_expiry` action. With this constant exposed, the Curator would see for how long (or up until when) is he extending the duration before confirming the action in UI.

Expose BountyUpdatePeriod.

---

primitives/core/src/crypto.rs
ss58-registry.json

Adding a key prefix(31) for the Litentry Network.

Add ss58 version prefix for Litentry Network

---

client/finality-grandpa/src/lib.rs
client/network/src/config.rs
client/network/src/gossip/tests.rs
client/network/src/protocol.rs
client/network/src/protocol/generic_proto/behaviour.rs
client/network/src/protocol/generic_proto/handler.rs
client/network/src/protocol/generic_proto/tests.rs
client/network/src/protocol/generic_proto/upgrade/notifications.rs
client/network/src/service.rs
client/network/src/service/tests.rs
client/network/src/transport.rs
client/network/test/src/lib.rs

polkadot companion: https://github.com/paritytech/polkadot/pull/2287
From an API point of view, this PR adds a new field to `NonDefaultSetConfig`, `max_notification_size`, which sets the maximum allowed limit of notifications using that notifications protocol.
Before this PR, the maximum size of notifications is in theory 128MiB, coming from `UviBytes::default()`. In practice, however, it was actually 1MiB because Yamux will refuse to buffer more than 1MiB.
This PR also thus configures the Yamux buffer size limit to automatically match the maximum frame size of all network protocols that we use.

Add explicit limits to notifications sizes and adjust yamux buffer size

---

.maintain/monitoring/alerting-rules/alerting-rules.yaml

5000 seems to trigger false alarms. Let's increase this enough to be sure that it's not accidentally triggered.
Note that we have another alert that triggers if it stays over 200 for 5 minutes, which should detect leaks even if they're slow.
This 5000/15000 threshold is more here to detect peaks.

Increase UnboundedChannelVeryLarge threshold from 5k to 15k

---

client/db/src/parity_db.rs

This enable filesystem flush on each commit, which should prevent DB corruption on system power loss or VM crash.
Has minor effect on performance.

Enable sync mode for parity-db

---

frame/support/procedural/src/pallet/parse/helper.rs

`Item::__Nonexhaustive` from `syn` crate is not supposed to be public, and using it may lead to unintentional API break when `syn` updates. This PR changes it to use non-exhaustive matching with `_`.
Alternatively, `syn` supports using the `__TestExhaustive` idiom for exhaustive matching (https://docs.rs/syn/1.0.60/src/syn/item.rs.html#74):
```
match expr {
#[cfg(test)]
Item::__TestExhaustive(_) => unimplemented!(),
#[cfg(not(test))]
_ => { /* some sane fallback */ }
}
```
I slightly prefer we continue to use non-exhaustive matching because it's already sufficient.

Remove hidden item `__NonExhaustive` in syn crate

---

frame/assets/Cargo.toml
frame/assets/src/lib.rs
frame/collective/src/lib.rs
frame/elections-phragmen/src/lib.rs
frame/elections/src/mock.rs
frame/offences/benchmarking/src/mock.rs
frame/support/procedural/src/lib.rs
frame/support/src/inherent.rs
frame/support/test/tests/construct_runtime.rs
frame/support/test/tests/instance.rs
frame/support/test/tests/issue2219.rs
frame/support/test/tests/pallet.rs
frame/support/test/tests/pallet_compatibility.rs
frame/support/test/tests/pallet_compatibility_instance.rs
frame/support/test/tests/pallet_instance.rs
frame/support/test/tests/pallet_version.rs
frame/support/test/tests/pallet_with_name_trait_is_valid.rs
frame/system/src/lib.rs
frame/system/src/mocking.rs

Related to https://github.com/paritytech/substrate/issues/7949
This PR introduce a few types, and make pallet-assets use construct_runtime.

Make pallets use construct_runtime

---

Cargo.lock
frame/atomic-swap/src/tests.rs
frame/aura/src/mock.rs
frame/authority-discovery/src/lib.rs
frame/authorship/Cargo.toml
frame/authorship/src/lib.rs

related https://github.com/paritytech/substrate/issues/7949
this make tests for aura, atomic-swap, authority-discovery and authorship making use of construct_runtime runtime

Use construct_runtime for some more pallet

---

client/network-gossip/src/lib.rs

The `add_set_reserved` and `remove_set_reserved` trait methods are supposed to add/remove nodes from the reserved nodes, to guarantee that a substream will be opened and closed.
They were mistakenly only adding/removing the peer from the list of nodes of the set. This means that `add_set_reserved` didn't guarantee that a substream was opened. 
Fix #7983

Fix Network trait implementation not doing what it's supposed to do

---

Cargo.lock
frame/randomness-collective-flip/Cargo.toml
frame/randomness-collective-flip/src/lib.rs
frame/recovery/src/mock.rs
frame/scheduler/src/lib.rs
frame/scored-pool/src/mock.rs
frame/session/src/mock.rs
frame/society/src/mock.rs
frame/staking/src/mock.rs
frame/staking/src/tests.rs
frame/sudo/src/mock.rs
frame/sudo/src/tests.rs
frame/timestamp/src/lib.rs
frame/tips/src/tests.rs
frame/transaction-payment/src/lib.rs
frame/treasury/src/tests.rs
frame/utility/src/tests.rs
frame/vesting/src/lib.rs

I make changes for pallets randomness-collective-flip, recovery, scheduler, scored-pool, session, society, staking, sudo, timestamp, tips, transaction-payment, treasury, utility, vesting.
the reason some pallet needs to import serde is because when macro_rules macro are using `$crate::serde` I think it can result is errors somehow.
There is an attribute that can be given to serde to resolve this https://serde.rs/container-attrs.html#crate but it is difficult to do this in this macro_rules macro. IMO it should be solved later when those are rewritten in procedural macro.

Make pallet use construct_runtime in tests instead of impl_*

---

frame/support/test/tests/pallet.rs
frame/support/test/tests/storage_transaction.rs

actually I'm not sure it is needed to test for it as transactional macro is independant from frame v2, but anyway having it in the test might be better to show usage
cc @apopiak 
EDIT: this comes from my missunderstood of Apopiak message, sorry

Ensure transactional with ? works in frame v2

---

client/network/src/protocol.rs
client/network/src/service.rs

https://github.com/paritytech/substrate/pull/7925 reduced the maximum notification sizes for transactions to 1MiB.
I didn't realize that, since we're sending runtime upgrades through transactions, 1MiB isn't enough.
This PR bumps this to 16MiB.

Increase maximum size of transaction notifications

---

Cargo.lock
bin/node-template/pallets/template/Cargo.toml
bin/node-template/pallets/template/src/mock.rs

Use construct_runtime for the mock in pallet-template as suggest by @thiolliere in #7981

Let mock in pallet-template use construct_runtime

---

client/network/src/protocol/generic_proto/behaviour.rs
client/peerset/src/lib.rs
client/peerset/tests/fuzz.rs

This PR attempts to solve the following problem:
The peerset asks to open a substream with a node. The node refuses it. The PSM immediately tries again. Repeat ad vitam eternam.
We do have a reputation decrease when a node refuses a substream, but, since reputations regress towards 0 over time, it takes an infinite amount of attempts to reach the banning threshold. Plus, we don't actually want to reach the banning threshold, as this peer might have other substreams currently open and in use.
After this PR, after a node has refused a substream, it simply removed from the set of "discovered nodes" according to the peerset, meaning that no connection attempt will be tried again until the node is later re-discovered (which will happen sooner or later).
This should only affect the block …

Introduce sc_peerset::DropReason

---

.gitlab-ci.yml
.maintain/flamingfir-deploy.sh

Returns the `flaming-fir` deployment as it was except without manual jobs, it's no need in them.

CI: return flaming fir deployment

---

Cargo.lock
client/service/Cargo.toml
client/service/src/task_manager/mod.rs
client/service/src/task_manager/tests.rs

There is a bug that tracing spans are not forwarded to spawned task. The
problem was that only the telemetry span was forwarded. The solution to
this is to use the tracing provided `in_current_span` to capture the
current active span and pass the telemetry span explictely. We will now
always enter the span when the future is polled. This is essentially the
same strategy as tracing is doing with its `Instrumented`, but now
extended for our use case with having multiple spans active.

Fix tracing spans are not being forwarded to spawned task

---

frame/support/procedural/src/construct_runtime/mod.rs

Make the generated `AllModules` and `AllModuleWithSystem` types public so crates depending on FRAME runtimes can access them. (Useful for e.g. testing.)

make AllModules public

---

frame/support/src/storage/generator/double_map.rs
frame/support/src/storage/generator/map.rs
frame/support/src/storage/mod.rs
frame/support/src/storage/types/double_map.rs
frame/support/src/storage/types/map.rs

Relax the type constraints for `translate` to `FnMut` to allow passing closures to `translate` that mutate captured variables.
Useful for migrations where you want to e.g. count the amount of values that were migrated.

relax translate closure to FnMut

---

frame/contracts/src/exec.rs
frame/contracts/src/lib.rs
frame/contracts/src/rent.rs
frame/contracts/src/tests.rs

When the `seal_terminate` API was introduced no event was added. This adds the appropriate event and also removes the now redundant `tombstone` argument from the `ContractEvicted` event as it was always true.
Some renames and doc improvements where done as a drive-by.

contracts: Emit event on contract termination

---

client/tracing/src/lib.rs
client/tracing/src/logging/mod.rs

The tests were not working properly.
1. Some test was setting a global subscriber, this could lead to racy
conditions with other tests.
2. A logging test called `process::exit` which is completly wrong.

Fix tracing tests

---

primitives/debug-derive/src/lib.rs

This PR changes the whitespace in a doc comment. Clippy was complaining about this as follows:
```
error: using tabs in doc comments is not recommended
--> /home/joshy/.cargo/git/checkouts/substrate-7e08433d4c370a21/f977fb8/primitives/debug-derive/src/lib.rs:30:4
|
30 | //!    struct MyStruct;
|    ^^^^ help: consider using four spaces per tab
|
= note: `-D clippy::tabs-in-doc-comments` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#tabs_in_doc_comments
error: using tabs in doc comments is not recommended
--> /home/joshy/.cargo/git/checkouts/substrate-7e08433d4c370a21/f977fb8/primitives/debug-derive/src/lib.rs:32:4
|
32 | //!    assert_eq!(format!("{:?}", MyStruct), "MyStruct");
|    ^^^^ help: consider using four …
```

Better formatting for doc comments

---

client/network/src/behaviour.rs
client/network/src/request_responses.rs
client/network/src/service.rs

This function differs from the already provided `request` method in two ways.
1. It allows sending of messages to currently disconnected peers, which is required for my first go at request based availability distribution.
2. Instead of creating a sender/receiver pair and awaiting the receiver, it takes a sender as argument. This suits our use in Polkadot better, where the subsystem will hold the corresponding receiver.
This PR changes the signature of some apparently only internally used `send_request` functions to accept an additional boolean parameter.

Add a send_request function to NetworkService

---

client/network/src/lib.rs

Forgot to actually export `IfDisconnected` in public `lib` module.
Sorry to bother you again: @romanb and @tomaka  :-S

Export `IfDisconnected` in public module.

---

frame/system/src/lib.rs

Update `Index` type bound: `MaybeSerialize` => `MaybeSerializeDeserialize`. So that it could be used in genesis config with new pallet macro.

frame-system: Index type 'MaybeSerializeDeserialize' bound.

---

frame/contracts/src/chain_extension.rs
frame/contracts/src/lib.rs
frame/contracts/src/tests.rs

This PR changes the `ChainExtensions` trait to be defined as `ChainExtension<C: pallet_contracts::Config>`. This is necessary because the `ChainExtension::call` method has a parameter that is generic over the pallet's configuration. This trait however, only is bound by `: frame_system::Config` with no way for the `ChainExtension` implementer to add additional bounds. Therefore calling into any pallet that is not system or contracts would not work because of the missing bounds on that trait. 
This PR changes this by giving the implementer the tools to call all runtime functions. A implementation would look like this:
```rust
// We assume we are a direct child of the runtime module here
use super::Runtime;
struct TestExtension;
impl ChainExtension<Runtime> for TestExtension {
fn …
```

contracts: Make ChainExtension trait generic over the runtime

---

Cargo.lock
bin/node-template/runtime/src/lib.rs
frame/aura/Cargo.toml
frame/aura/src/lib.rs
frame/aura/src/migrations.rs
frame/aura/src/mock.rs
frame/aura/src/tests.rs
primitives/consensus/aura/src/inherents.rs
primitives/consensus/aura/src/lib.rs

This switches AURA to use `CurrentSlot` instead of `LastTimestamp`.
Based on: https://github.com/paritytech/substrate/pull/8020 (so only the last commit is important at the moment)

AURA: Switch to `CurrentSlot` instead of `LastTimestamp`

---

bin/node/runtime/src/lib.rs
frame/babe/src/equivocation.rs
frame/babe/src/tests.rs
frame/grandpa/src/equivocation.rs
frame/grandpa/src/tests.rs

Check for equivocation report staleness on `validate_unsigned` as well.

babe, grandpa: cleanup stale equivocation reports

---

Cargo.lock
frame/example-offchain-worker/src/tests.rs
frame/identity/src/tests.rs
frame/im-online/src/mock.rs
frame/lottery/Cargo.toml
frame/lottery/src/mock.rs
frame/membership/src/lib.rs
frame/merkle-mountain-range/src/mock.rs
frame/multisig/src/tests.rs
frame/nicks/src/lib.rs
frame/node-authorization/src/lib.rs
frame/offences/src/mock.rs
frame/offences/src/tests.rs
frame/proxy/src/tests.rs

related https://github.com/paritytech/substrate/issues/7949
simply use construct_runtime in tests, nothing substantial here.

move some pallet test to use construct_runtime

---

frame/example/src/lib.rs

Minor fix solving and outdated reference to `CheckRuntime` signed extension in pallet example. Updated to `CheckSpecVersion` + link to system documentation.
Closes #8000

CheckSpecVersion reference fix

---

client/finality-grandpa/src/lib.rs
client/network/src/protocol.rs

Fix https://github.com/paritytech/substrate/issues/7852
After this PR, Polkadot 0.8.26 and below will be unable to open the transactions and GrandPa substreams with clients that have this PR in.
It is a noticable breakage, because so far even old versions of Polkadot (even maybe 0.8.0) were capable of connecting to recent versions. Only the other way around (recent connecting to older) was known to be broken.
In Polkadot 0.8.26 and below, we consider that either all substreams (block announces, transactions, and GrandPa) are open with a given peer, or none. As long as the block announces substream (i.e. the "main" one) is open, we silently ignore situations where the transactions and/or GrandPa has failed to open. If the rest of the client tries to send a transaction or a GrandPa message …

Remove backwards-compatibility networking hack

---

frame/collective/src/lib.rs
frame/elections-phragmen/src/lib.rs
frame/elections/src/mock.rs
frame/offences/benchmarking/src/mock.rs
frame/society/src/mock.rs
frame/support/src/dispatch.rs
frame/support/src/event.rs
frame/support/src/lib.rs
frame/support/src/metadata.rs
frame/support/src/storage/generator/mod.rs
frame/support/src/traits.rs
frame/support/src/weights.rs
frame/support/test/src/lib.rs
frame/support/test/tests/decl_storage.rs
frame/support/test/tests/genesisconfig.rs
frame/support/test/tests/instance.rs
frame/support/test/tests/issue2219.rs
frame/support/test/tests/pallet_with_name_trait_is_valid.rs
frame/support/test/tests/storage_transaction.rs
frame/transaction-payment/src/lib.rs
frame/utility/src/tests.rs
test-utils/runtime/src/lib.rs

related https://github.com/paritytech/substrate/issues/7949

Replace last usages of `<() as PalletInfo>` in substrate

---

frame/support/src/traits.rs

Fixes https://github.com/paritytech/substrate/issues/7949
polkadot companion: paritytech/polkadot#2409

Remove PalletInfo impl for ()

---

client/executor/src/integration_tests/mod.rs
client/executor/src/lib.rs
client/executor/src/native_executor.rs
client/executor/src/wasm_runtime.rs
client/executor/wasmtime/src/runtime.rs
primitives/runtime-interface/test/src/lib.rs

This PR allows to specify a cache directory when creating a `WasmExecutor`. If specified and wasmtime executor is used, we configure wasmtime to use it to put its compiled artifacts cache there.
This change is motivated by the polkadot validation function which has to execute many different wasm blobs as quickly as possible. Right now, the lack of caching leads to severe stalls.
polkadot companion: https://github.com/paritytech/polkadot/pull/2387

WasmExecutor takes a cache directory

---

client/network/Cargo.toml

currently `sc-network` doesn't build if separated from the rest of workspace (see https://github.com/libp2p/rust-libp2p/issues/1952). This fix flips the dependency switch around: activates the libp2p default features and excludes some for wasm-builds.

sc-network: switch on default features for libp2p on non-wasm-builds

---

bin/node-template/pallets/template/src/lib.rs
frame/assets/src/lib.rs
frame/support/procedural/src/pallet/expand/pallet_struct.rs
frame/support/src/lib.rs
frame/support/test/tests/pallet.rs
frame/support/test/tests/pallet_compatibility.rs
frame/support/test/tests/pallet_ui/hooks_invalid_item.rs
frame/support/test/tests/pallet_ui/type_value_error_in_block.rs
frame/support/test/tests/pallet_ui/type_value_forgotten_where_clause.rs
frame/support/test/tests/pallet_ui/type_value_invalid_item.rs
frame/support/test/tests/pallet_ui/type_value_no_return.rs
frame/support/test/tests/pallet_version.rs
frame/system/src/lib.rs

This PR makes the declaration of pallet placeholder less boilerplatey.
now user can just write:
```rust
#[pallet::pallet]
pub struct Pallet<T>(_);
```
And the macro will replace `_` with the expected PhantomData.
Note that this macro doesn't forbid to write it explicitly like:
```rust
#[pallet::pallet]
pub struct Pallet<T>(sp_std::maker::PhantomData<T>);
```
If this PR gets into before substrate 3.0 I guess we can forbid any other syntax than `_`. otherwise I guess better to let user choose.

pallet macro: easier syntax for `#[pallet::pallet]` with `struct Pallet<T>(_)`

---

frame/support/src/lib.rs

Fixed some apparent mistakes and typos in pallet attribute macro migrate guidelines.

Pallet attribute macro migrate guidelines minor fixes

---

.maintain/gitlab/check_polkadot_companion_build.sh

This switch to the new `diener patch` command to patch all Substrate
crates in Polkadot. This should remove the requirement to manually merge
Substrate master to make the companion build, as we now would use the
already with master merged code from this build job local checkout.

Switch to use `diener patch` for companion build

---

bin/node/runtime/src/lib.rs
frame/babe/src/equivocation.rs
frame/babe/src/mock.rs
frame/babe/src/tests.rs
frame/grandpa/src/equivocation.rs
frame/grandpa/src/mock.rs
frame/grandpa/src/tests.rs

Currently the equivocation report transactions never expire, they will only be pruned from the queue if they are included in a block. Any equivocation report is only useful for the period that the given offender is bonded. This PR makes it so that any equivocation report transaction has longevity equal to the bonding duration in blocks.
polkadot companion: https://github.com/paritytech/polkadot/pull/2404

babe, grandpa: set longevity for equivocation report transactions

---

frame/timestamp/src/benchmarking.rs
frame/timestamp/src/lib.rs

Part of #7882.
Converts the `Timestamp` pallet to the new pallet attribute macro introduced in #6877.
So users of the `Timestamp` pallet must be careful about the name they used in `construct_runtime!`. Hence the `runtime-migration` label, which might not be …

Migrate pallet-timestamp to pallet attribute macro.

---

client/telemetry/src/lib.rs

Please beware that if you do `-loff,telemetry=trace` it still fails!
```
./target/debug/substrate --dev --tmp --telemetry-url "ws://127.0.0.1:1337 10" -loff,telemetry=trace
2021-02-10 12:55:03.801  ERROR main telemetry: Could not initialize telemetry: the span could not be entered    
2021-02-10 12:55:03.807  ERROR tokio-runtime-worker telemetry: Received connection notifier for unknown node (/ip4/127.0.0.1/tcp/1337/ws). This is a bug.    
```
It just doesn't fail anymore for -lerror and -lwarn
Fixes: https://github.com/paritytech/substrate/issues/8093

Use log level error to report telemetry

---

.github/workflows/check-labels.yml
.gitlab-ci.yml
.maintain/common/lib.sh
.maintain/github/check_labels.sh
.maintain/gitlab/check_labels.sh
.maintain/gitlab/check_signed.sh
.maintain/gitlab/generate_changelog.sh
.maintain/gitlab/publish_draft_release.sh

Basically same change as https://github.com/paritytech/polkadot/pull/2415/ - allows the job to re-run when labels are changed, saving the dev the effort of having to manually retrigger the job.
@TriplEight if you have access to admin functions on this repo, can you do the same as the polkadot repo please? :)

[CI] Move check_labels to github actions

---

frame/system/src/limits.rs

This PR simply updates the diagrams in the documentation of Frame System Limits so they are rendered well when generated into Rust Docs:
https://crates.parity.io/frame_system/limits/struct.BlockWeights.html

Fix Diagram Formatting in Frame System Limits

---

.gitlab-ci.yml

- temporarily allow `cargo-deny` to fail.
We are aware of the current problems and have them checked in the release checklist.

CI: temporarily allow cargo deny to fail

---

frame/balances/src/lib.rs
frame/balances/src/tests_reentrancy.rs

Testcases to validate #8087 |  Move dust collection hook to outside of account mutate
[#8087](https://github.com/paritytech/substrate/pull/8087)

dust removal reentrancy test case integration

---

frame/executive/src/lib.rs
frame/staking/reward-curve/src/lib.rs
primitives/core/src/crypto.rs
primitives/core/src/hashing.rs
primitives/inherents/src/lib.rs

due to https://github.com/rust-lang/rust/pull/81645 panic now seems to requrie a string literal as first argument, thus the fix.

fix deprecated usage of panic

---

client/cli/src/arg_enums.rs
client/cli/src/params/database_params.rs

Sadly this is a breaking change for the CLI.
Fixes: https://github.com/paritytech/substrate/issues/8145
Migration: Everyone that uses `--database paritydb` needs to change to `--database parity-experimental`.

Make it clear in CLI that paritydb is experimental

---

client/network/src/behaviour.rs
client/network/src/config.rs
client/network/src/gossip/tests.rs
client/network/src/lib.rs
client/network/src/protocol.rs
client/network/src/service.rs
client/network/src/service/tests.rs
client/network/src/transactions.rs
client/network/test/src/lib.rs
client/service/src/builder.rs

Cleans up `protocol.rs` by extracting all the transactions-related code to a new `transactions.rs` module.
In this PR, I've done the minimal amount of changes to make sure to not break anything. Later PRs can add more changes, such as switching from `write_notification` to some properly-back-pressured alternative.
Before this PR, the various layers go like this: `(outside) <-> service.rs <-> behaviour.rs <-> protocol.rs <-> generic_proto.rs`
This PR moves the transaction handling from `protocol.rs` to `(outside)`. It is now a background task that interacts with the `NetworkService` in `service.rs`.
A new `transactions_handler_executor` field has been added to the network parameters. It is used to spawn that task.
This background task is spawned by `service.rs` after the service creation. …

Extract transactions handling from protocol.rs

---

client/consensus/slots/src/lib.rs

Currently we always use a boxed future everywhere anyway. This also
enables us to use a boxed `SlotWorker` (which is required for Cumulus).

Remove `OnSlot` associated type

---

bin/node-template/node/src/service.rs
bin/node/cli/src/service.rs
client/consensus/aura/src/lib.rs
client/consensus/babe/src/lib.rs
client/consensus/manual-seal/src/lib.rs
client/consensus/pow/src/lib.rs
client/service/src/task_manager/mod.rs
primitives/consensus/common/src/import_queue/basic_queue.rs
primitives/core/src/testing.rs
primitives/core/src/traits.rs

This pr ensures that we spawn the block import worker as an essential
task. This is quite important as we need to bring down the node when the
block import is done. Besides that it adds some debug output to the
block import worker.
polkadot companion: https://github.com/paritytech/polkadot/pull/2478

Ensure we spawn the block import worker as an essential task

---

bin/node/executor/tests/basic.rs
bin/node/runtime/src/lib.rs
frame/contracts/src/benchmarking/mod.rs
frame/contracts/src/chain_extension.rs
frame/contracts/src/exec.rs
frame/contracts/src/gas.rs
frame/contracts/src/lib.rs
frame/contracts/src/rent.rs
frame/contracts/src/storage.rs
frame/contracts/src/tests.rs
frame/contracts/src/wasm/code_cache.rs
frame/contracts/src/wasm/env_def/macros.rs
frame/contracts/src/wasm/env_def/mod.rs
frame/contracts/src/wasm/mod.rs
frame/contracts/src/wasm/runtime.rs

Metadata diff:
```diff
diff --git a/old.json b/new.json
index 2201706..0467169 100644
--- a/old.json
+++ b/new.json
@@ -744,7 +744,7 @@
"name": "DeletionQueue",
"modifier": "Default",
"ty": {
-          "Plain": "Vec<storage::DeletedContract>"
+          "Plain": "Vec<DeletedContract>"
},
"default": [
0
@@ -786,7 +786,7 @@
},
{
"name": "gas_limit",
-          "ty": "Compact<Gas>"
+          "ty": "Compact<Weight>"
},
{
"name": "data",
@@ -812,7 +812,7 @@
},
{
"name": "gas_limit",
-          "ty": "Compact<Gas>"
+          "ty": "Compact<Weight>"
},
{
"name": "code",
@@ -860,7 +860,7 @@
},
{
"name": "gas_limit",
-          "ty": "Compact<Gas>"
+          "ty": "Compact<Weight>"
},
{
"name": "code_hash",
@@ -1206,8 +1206,7 @@
0
],
"documentation": [
-        " The maximum nesting level of a …
```

contracts: Convert to framev2 macros

---

frame/staking/reward-curve/src/lib.rs
frame/staking/src/lib.rs
frame/staking/src/tests.rs
test-utils/src/lib.rs

Currently when a stash ledger has active == ED.
And call `withdraw_unbonded` then the stash got reaped and the ed is lost.
looking at `unbond` which unbond all active balance if goes below ED. I think this is a misstake.

Fix: stash account reaped when ledger.active == ED

---

Cargo.lock

Fixes memory leaks when TLS objects are dropped

Bump thread_local

---

primitives/core/src/crypto.rs
ss58-registry.json

This reserves ss58 prefix 48 for Neatcoin (a network where I plan on experimenting something related to the Move smart contract platform).

Reserve ss58 prefix 48 for Neatcoin

---

client/consensus/aura/src/lib.rs
client/consensus/slots/src/lib.rs
primitives/consensus/common/src/block_import.rs

Before this pr `on_slot` returned the pre block. However this is wrong,
because adding some post digest changes the hash of the header. Thus,
we need to make sure to return the correct block that uses the post
header.

Make `on_slot` return the block with the post header

---

frame/multisig/src/lib.rs
frame/multisig/src/tests.rs

I am uncertain if anyone watches for this error by name, a perfunctory search through https://github.com/LocalCoinSwap/substrate-multisig-reference shows no reference to the error and if they don't have it hardcoded anywhere, I don't imagine many others do, so this is probably insubstantial.

[multisig, insubstantial] WeightTooLow -> MaxWeightTooLow 

---

frame/election-provider-multi-phase/src/lib.rs

Turns out the polkadot bot assumes that this guys is exported from the root of the pallet.

Re-export weights for eleciton.

---

client/finality-grandpa-warp-sync/src/proof.rs

This means that we end up doing 1 less warp sync request. I was considering using `proofs.len() < MAX_CHANGES_PER_WARP_SYNC_PROOF` for `is_finished`, but that would make an extra request in the case that there are exactly `MAX_CHANGES_PER_WARP_SYNC_PROOF` fragments to send. Already tested in smoldot with https://github.com/paritytech/smoldot/pull/565.

Add an is_finished boolean to the grandpa warp sync response

---

client/network/src/protocol/generic_proto/behaviour.rs

It turns out that it's only the `debug_assert!`s that are wrong. I had not taken into account the fact that `Closing` can mean "already closed, but a second closed message is waiting to be acknowledged", as documented at the top of the file.

Fix networking debug_asserts

---

frame/balances/src/benchmarking.rs
frame/benchmarking/src/lib.rs

Currently instantiable pallet define with pallet macro cannot use benchmarks_instance because it bounds `I: Instance`.
Instead this PR introduce a new macro: `benchmarks_instance_pallet`
Also this PR make use of this macro for pallet-balances. Currently the benchmark only works for the default instance of pallet balance.

pallet macro broke `benchmarks_instance`, fix by introducing  `benchmarks_instance_pallet`

---

Cargo.lock
bin/node/cli/Cargo.toml
bin/node/executor/Cargo.toml
bin/node/rpc/Cargo.toml
bin/node/runtime/Cargo.toml
bin/node/testing/Cargo.toml
frame/benchmarking/Cargo.toml
frame/contracts/CHANGELOG.md
frame/contracts/Cargo.toml
frame/contracts/README.md
frame/contracts/common/Cargo.toml
frame/contracts/proc-macro/Cargo.toml
frame/contracts/rpc/Cargo.toml
frame/contracts/rpc/runtime-api/Cargo.toml
frame/contracts/src/lib.rs
frame/contracts/src/rent.rs
frame/contracts/src/storage.rs
frame/contracts/src/tests.rs

Preparing pallet_contracts for release. It seems that [this PR](https://github.com/paritytech/substrate/pull/8104) requires the release of a `frame-benchmarks v3.1.0` before releasing contracts.
- Update README.md
- Add a CHANGELOG.md
- Bump version numbers and allow publishing.
- Add a `_reserved` field to `ContractInfoOf` for future proofing.

contracts: Release as v3.0.0 and add reserved field to `ContractInfoOf`

---

client/network/src/transactions.rs

We wouldn't propagate transactions to nodes whose `ObservedRole` is `Authorities`.

Fix transactions not being propagated to authorities

---

frame/benchmarking/src/lib.rs

Currently if a benchmark fails and return error (instead of panicking) then the test ignores it.
That might worth a frame-benchmarking 3.1.1 release.

Fix ignored error in benchmark tests

---

frame/contracts/src/wasm/runtime.rs

A contract can emit events with custom topics. Those topics are not allowed to be duplicates which is enforced by the supervisor. In order to do so those topics are sorted. This sort unnecessarily used a stable sorting algorithm. This PR replaces it by an unstable one which is faster and does not use additional memory.

contracts: Use unstable sort for topics

---

Cargo.lock
bin/node-template/pallets/template/Cargo.toml
bin/node-template/pallets/template/src/benchmarking.rs
bin/node-template/pallets/template/src/lib.rs
bin/node-template/runtime/Cargo.toml
bin/node-template/runtime/src/lib.rs
frame/benchmarking/src/lib.rs
frame/merkle-mountain-range/src/benchmarking.rs
frame/timestamp/src/benchmarking.rs

This adds a basic benchmarks to the `pallet-template` found in the `node-template`.
Fixes an issue where `sp_std` was being depended on in multiple ways without being exported by the `benchmarking` crate.

Add benchmark to node-template pallet-template

---

frame/elections-phragmen/src/lib.rs

If I do:
```rust
assert!(matches!(
unwrapped_error.post_info.actual_weight,
Some(x) if x < <Test as frame_system::Config>::BlockWeights::get().max_block
));
```
if fails, thus I just assert that there is some refund.

Fix tests in phragmen election pallet

---

frame/support/src/storage/migration.rs

when migrating from decl_storage to frame v2, some pallet needs to migrate their storage too.
This is some helper to move some specific storage in case the pallet prefix is shared by multiple pallets (e.g. treasury and bounty) or to move all pallet.
This can be useful for
https://github.com/paritytech/substrate/pull/8193
https://github.com/paritytech/substrate/pull/8196
https://github.com/paritytech/substrate/pull/8044

Add some migration helper to help migrating pallet changing pallet prefix

---

client/consensus/aura/src/lib.rs
primitives/consensus/aura/src/digests.rs
primitives/consensus/aura/src/lib.rs
primitives/consensus/babe/src/digests.rs
primitives/runtime/src/generic/digest.rs

This makes the digest stuff usable from inside the runtime ;)

Move AuRa digest from client to primitives

---

Cargo.lock
bin/node-template/runtime/src/lib.rs
bin/node/runtime/src/lib.rs
frame/executive/README.md
frame/executive/src/lib.rs
frame/support/src/traits.rs
test-utils/runtime/Cargo.toml
test-utils/runtime/src/lib.rs
test-utils/runtime/src/system.rs

This pr changes the `ExecuteBlock` trait to return the final header that
results from executing the given block.
polkadot companion: https://github.com/paritytech/polkadot/pull/2548

Make `ExecuteBlock::execute_block` return the final block header

---

frame/support/procedural/src/pallet/parse/call.rs
frame/support/procedural/src/pallet/parse/helper.rs
frame/support/src/lib.rs
frame/support/test/tests/pallet.rs
frame/support/test/tests/pallet_ui/call_invalid_return.rs
frame/support/test/tests/pallet_ui/call_invalid_return.stderr

This PR allows calls in `#[pallet::call]` to return a `DispatchResult`.

Allow pallet::call to return `DispatchResult`

---

frame/support/procedural/src/pallet/expand/hooks.rs
frame/support/procedural/src/pallet/parse/hooks.rs
frame/support/src/dispatch.rs

Missing from https://github.com/paritytech/substrate/pull/8123/files

Add migration logs to pallet v2

---

frame/executive/src/lib.rs
frame/support/src/traits.rs
test-utils/runtime/src/system.rs

That was actually a bad idea by me, because it should essentially be the
same as block.header.
Ty @kianenigma

Do not return the `Header` from `execute_block`

---

Cargo.lock

This PR update:
nb-connect` from v1.0.2 to v1.0.3: https://github.com/smol-rs/nb-connect/blob/master/CHANGELOG.md
pin-project-lite from v0.1.11 to v0.1.12 https://github.com/taiki-e/pin-project-lite/blob/master/CHANGELOG.md
pin-project-lite from v0.2.4 to v0.2.5 https://github.com/taiki-e/pin-project-lite/blob/master/CHANGELOG.md
rand_core from v0.6.1 to v0.6.2 https://github.com/rust-random/rand/blob/master/rand_core/CHANGELOG.md

Update minor yanked dependencies

---

client/service/test/src/client/light.rs
client/service/test/src/client/mod.rs
client/tracing/src/logging/mod.rs
frame/democracy/src/tests.rs
frame/election-provider-multi-phase/src/lib.rs
frame/offences/benchmarking/src/lib.rs

We were using the wrong syntax and that will be dropped with Rust 2021.
The compiler already starts to hint the wrong syntax with warnings. So,
we fix this here.

Fix warnings related to panic and assert

---

bin/node-template/node/src/service.rs
client/consensus/aura/src/import_queue.rs
client/consensus/aura/src/lib.rs

Hot and fresh AuRa improvements. This pr does the following:
- Move code belonging to the import queue etc to import_queue.rs
- Introduce `ImportQueueParams` and `StartAuraParams` structs to make
it more easier to understand what parameters we pass to AuRa.
- Introduce `CheckForEquivocation` to tell AuRa if it should check for
equivocation on block import. This is required for parachains, because
they are allowed to equivocate when they build two blocks for the same
slot, but for different relay chain parents.

AuRa improvements

---

frame/support/procedural/src/pallet/expand/call.rs
frame/support/procedural/src/pallet/expand/config.rs
frame/support/procedural/src/pallet/expand/error.rs
frame/support/procedural/src/pallet/expand/event.rs
frame/support/procedural/src/pallet/expand/genesis_config.rs
frame/support/procedural/src/pallet/expand/mod.rs
frame/support/procedural/src/pallet/expand/pallet_struct.rs
frame/support/procedural/src/pallet/parse/call.rs

Having types in the reference documentation without a rust doc creates a low quality impression. That said, many types emitted or augmented by the pallet macro don't need custom docs because those are well known types like `Call` and `Config` which pretty much can get a stock documentation pointing users to the relevant knowledge base article.
This PR emits such a stock documentation for the well known types in case no own documentation is specified.
* Emit default docs for: `mod pallet`, `Config`, `GenesisConfig`, `Pallet`, `Call`, `Error`, `Event`
* Emit documentation for the `Call` variants (copied from the pallet impl)
Please also review and improve the actual docs emitted.

pallet macros: Improve emitted rustdoc

---

bin/node/runtime/src/lib.rs
frame/gilt/src/lib.rs
frame/gilt/src/mock.rs
frame/gilt/src/tests.rs

IgnoredIssuance allows for excuding some balance from total_issuance for determining the degree to which the taken base has been inflated/deflated. This is expected to be used to exclude the treasury account.

Introduce IgnoredIssuance into Gilts

---

frame/support/procedural/src/pallet/expand/genesis_config.rs

This is a fixup for #8276. I copy and pasted the doc comment from the contracts module.

Fix typo in generated docs

---

bin/node-template/node/src/service.rs
bin/node/cli/src/service.rs
client/consensus/aura/src/lib.rs
client/consensus/babe/src/lib.rs
client/consensus/babe/src/tests.rs
client/consensus/slots/src/lib.rs
client/consensus/slots/src/slots.rs

Currently when building a block we actually give the proposer all of the
time in the slot, while this is wrong. The slot is actually split in at
least two phases proposing and propagation or in the polkadot case into
three phases validating pov's, proposing and propagation. As we don't
want to bring that much polkadot concepts into Substrate, we only
support splitting the slot into proposing and propagation. The portion
can now be passed as parameter to AuRa and BABE to configure this value.
However, this slot portion for propagation doesn't mean that the
proposer can not go over this limit. When we miss slots we still apply
the lenience factor to increase the proposing time, so that we have
enough time to build a heavy block.
Besides all what was said above, this is especially required …

Introduce new concept of "slot portion for proposing"

---

client/network/src/block_request_handler.rs
client/network/src/gossip/tests.rs
client/network/src/service/tests.rs
client/network/test/src/lib.rs
client/service/src/builder.rs

This reverts commit 7e5c30709d0d6bae01e1eb9412d17cdf1620af7d.
As it breaks rococo due to a bug in sync code.

Revert "Decrease the peer reputation on invalid block requests (#8260)"

---

.gitlab-ci.yml

- run docs generation on PRs temporarily (until https://github.com/paritytech/substrate/pull/7670 is resolved) allowing them to fail 
- publish successful docs on master updates

CI: return docs jobs

---

frame/support/test/src/lib.rs

Fix `cargo doc`. 
`Randomness` not in scope.

Fix doc build

---

frame/staking/src/lib.rs

It can happen in some contexts that a validator/nominator might want to carry out the functionality of validating/nominating, but does not want to receive any rewards (either permanently or temporarily). This PR adds a simple `None` reward destination for this use case.

pallet-staking: add RewardDestination::None for explictly not receiving rewards

---

Cargo.lock
client/consensus/aura/src/lib.rs
client/consensus/babe/src/lib.rs
client/consensus/manual-seal/src/consensus/babe.rs
client/consensus/pow/src/lib.rs
frame/aura/Cargo.toml
frame/aura/src/lib.rs
frame/babe/Cargo.toml
frame/babe/src/lib.rs
frame/support/src/traits.rs
frame/timestamp/src/lib.rs
primitives/consensus/aura/src/inherents.rs
primitives/consensus/babe/src/inherents.rs
primitives/std/with_std.rs
primitives/std/without_std.rs
primitives/timestamp/Cargo.toml
primitives/timestamp/src/lib.rs

The timestamp inherent type was up to now just a simple `u64`. This
worked, but doesn't give you that much guarantees at compile time about
the type. This pr changes that by converting this type to a unit type
wrapper, similar to what we have done for `Slot`.
This is required for some future pr that touches quite a lot of the
inherents stuff :)
Besides this unit wrapper type, this pr also moves the `OnTimestampSet`
trait to `frame_support::traits`.

Convert timestamp to unit type wrapper

---

frame/system/src/lib.rs

Another step toward cleaning the runtime logs.

Don't log to debug for every failed extrinsic. 

---

utils/frame/benchmarking-cli/src/lib.rs

Make it possbible to use the pallet's path name, with `-` separator or crate name with `_` separator.
fixes #8226
Thank you!

Add more relaxed pallet-name parsing

---

frame/election-provider-multi-phase/src/lib.rs
frame/staking/src/lib.rs

Not so pretty on the code, but these logs are polluting other commands as well that build the genesis spec. For example, running benchmarking before would give you:
```
Running `target/release/substrate benchmark --chain=dev --steps=5 --repeat=5 --pallet=pallet_election_provider_multi_phase --extrinsic=elect_queued --execution=native --wasm-execution=compiled --heap-pages=4096 --output=.`
2021-03-12 12:50:16.591  TRACE main runtime::staking: 💸 [0] planning new_session(0)
2021-03-12 12:50:16.591   INFO main runtime::staking: 💸 new validator set of size 1 has been elected via ElectionCompute::OnChain for staring era 0
2021-03-12 12:50:16.591   WARN main runtime::election-provider: 🗳 Failed to finalize election round. reason NoFallbackConfigured
2021-03-12 12:50:16.591  DEBUG main …
```

Don't log so many stkaing events on genesis block

---

primitives/npos-elections/fuzzer/src/phragmen_pjr.rs
primitives/npos-elections/src/pjr.rs

Builds on #8160.
- Updates the PJR check to return a counterexample if one exists
- Adds functions to cheaply check counterexamples
This is in support of off-chain PJR challenges: if a miner discovers
that an accepted election solution does not satisfy PJR, it will be
eligible for substantial rewards. This helps ensure that validator
elections have an absolute quality floor, so even if someone manages
to censor well-behaved solutions to give themselves unfair representation,
we can catch them in the act and penalize them.

NPoS Challenge Mode

---

.maintain/monitoring/alerting-rules/alerting-rules.yaml

When using the `-` operators and specifying matching labels with the `on` keyword all other labels are being dropped. This breaks some custom alert routing where additional labels are made use of.
This can be prevented with adding the generic `group_left()` parameter which basically defines which label set to take from as a base.
ref: https://prometheus.io/docs/prometheus/latest/querying/operators/

alerting-rules: ContinuousTaskEnded alert shouldn't drop unspecified labels

---

.maintain/gitlab/check_polkadot_companion_build.sh
Cargo.lock
bin/node/browser-testing/Cargo.toml

Diener will be updated in the CI image to make it possible to have
companions that add new crates from Substrate.
Besides that the wasm-bindgen is updated, because `0.2.70` is not
available anymore on crates.io.

Update diener to enable polkadot companions that use new crates

---

.github/workflows/check-labels.yml
.maintain/common/lib.sh
.maintain/github/check_labels.sh
.maintain/gitlab/check_runtime.sh

As of this PR, any changes to the runtime must be labelled with one of the following labels in order to pass CI:
* 'D1-audited👍'
* 'D5-nicetohaveaudit⚠️ '
* 'D9-needsaudit👮'

[CI] Require D*-audit labels for any runtime changes

---

.github/workflows/check-labels.yml
.gitlab-ci.yml
.maintain/common/lib.sh
.maintain/github/check_labels.sh
.maintain/gitlab/check_runtime.sh
Cargo.lock
frame/contracts/src/wasm/prepare.rs
frame/node-authorization/Cargo.toml
ss58-registry.json

Closes: paritytech/ci_cd/issues/110

CI: run cargo deny nightly

---

primitives/npos-elections/compact/src/assignment.rs
primitives/npos-elections/compact/src/codec.rs
primitives/npos-elections/compact/src/lib.rs
primitives/npos-elections/src/lib.rs

Original implementation was O(n**2). Current impl is O(n log n).
Avoided the original proposed mitigation because it does not retain
the de-duplicating property present in the original implementation.
This implementation does a little more work, but retains that property.
Mitigates https://github.com/paritytech/srlabs_findings/issues/58.

Improve complexity of CompactAssignments::unique_targets

---

.github/workflows/check-labels.yml

Fixes a bug where check-labels CI check wouldn't work on forked repositories.

[CI] Fix check-labels.yml

---

.maintain/github/check_labels.sh

For labeling changes to the runtime directories that do not require an audit (e.g., updating docs, what have you)

Add D1-trivial label

---

frame/election-provider-multi-phase/src/benchmarking.rs
frame/election-provider-multi-phase/src/helpers.rs
frame/election-provider-multi-phase/src/unsigned.rs
frame/staking/src/offchain_election.rs

Addresses https://github.com/paritytech/srlabs_findings/issues/63.
Marked as "nice to have audit" instead of "audit needed" because it directly and trivially implements the mitigation suggestions from a previous audit report.

Fast CompactAssignment search

---

Cargo.lock
client/network-gossip/Cargo.toml
client/network-gossip/src/state_machine.rs

This adds some more information to the logging output to get a better
understanding when something fails.
Should help with: https://github.com/paritytech/substrate/issues/8366

Improve logging in network gossip

---

frame/session/src/lib.rs

There is an assert that checks that an account exists, after setting a
key. However, this assert isn't very self-descriptive.

Better description for assert in frame-session genesis

---

Cargo.lock
Cargo.toml
frame/staking/reward-fn/Cargo.toml
frame/staking/reward-fn/src/lib.rs
frame/staking/reward-fn/tests/test.rs

Related: https://github.com/paritytech/substrate/issues/6469
Intruduce a new crate which expose: `compute_inflation` allowing to compute yearly inflation directly using `current_stake_rate`, `ideal_stake_rate` and `falloff`.
NOTE: we don't support falloff lower than 0.01, if we want to support it I think we can. If falloff is less than 0.01 the curve fall down very very fast, and we should probably return inflation = 0 and not compute taylor serie when stake is a bit far form ideal_stake.

Compute yearly inflation on-chain allowing to change x_ideal according to number of slots.

---

primitives/runtime/src/lib.rs

Ignores `message` field of `Module` variant in equality comparison.
Closes #8400

Implement PartialEq for DispatchError.

---

.gitlab-ci.yml

to properly trigger Simnet.
Also, add `TRIGGERER` for more grained pipelines there.

CI: address the bug with .env

---

client/peerset/src/lib.rs
client/peerset/src/peersstate.rs

Calling `highest_not_connected_peer` iterates over every single entry in the peerset (so, like, thousands of elements) to find the one with the highest reputation.
This PR does two things:
- Only try to allocate peers to slots for sets where there might be a slot by adding a `SetId` parameter to `alloc_slots`.
- Ensure that there is a slot available before calling `highest_not_connected_peer`. Right now, this check is performed in `try_outgoing`, which is after the potential peer has been selected.

Optimize the peerset a bit

---

client/network/src/protocol/notifications/handler.rs

Better version of https://github.com/paritytech/substrate/pull/8405 (and https://github.com/paritytech/substrate/pull/8410)
Now that the legacy substream is gone, this cleans up the hack introduced in https://github.com/paritytech/substrate/pull/7594
This PR does two things:
- Ensure that all messages are properly sent before we potentially generate `Poll::Ready`, and not the other way around.
- Avoids a lot of spurious wake ups when sending by removing the hack-y `cx.waker().wake_by_ref()` and by only calling `Sink::poll_ready()` on the substream only if there is actually something to send in the channel, and not all the time.

Refactor NotifsHandler::poll

---

frame/contracts/src/rent.rs

contracts: Update `deduct_block` when a contract is exempted from paying rent

---

client/finality-grandpa/src/tests.rs
client/finality-grandpa/src/until_imported.rs
client/network/test/src/lib.rs

The nodes in the GRANDPA test net were added without the authority role, which makes it so that the GRANDPA gossip layer will take longer to propagate the messages. This PR changes the testnet code to add nodes as authorities in order to make gossiping messages faster and speed up the tests.
Before: `test result: ok. 75 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 184.97s`
After: `test result: ok. 75 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 20.02s`

grandpa: speed up tests

---

frame/assets/src/lib.rs

The check is now required when transfering to unexisting accounts.
This is probably inherited from previous architecture. Anyway the code always handled this case.

Remove outdated comment in pallet asset

---

frame/vesting/src/benchmarking.rs
frame/vesting/src/lib.rs

Part of #7882.
Converts the `Vesting` pallet to the new pallet attribute macro introduced in #6877.
So users of the `Vesting` pallet must be careful about the name they used in `construct_runtime!`. Hence the `runtime-migration` label, which might not be needed …

Migrate pallet-vesting to pallet attribute macro.

---

frame/balances/src/lib.rs
frame/balances/src/tests.rs
frame/bounties/src/lib.rs
frame/democracy/src/lib.rs
frame/identity/src/lib.rs
frame/lottery/src/lib.rs
frame/multisig/src/lib.rs
frame/nicks/src/lib.rs
frame/society/src/lib.rs
frame/support/src/storage/generator/mod.rs
frame/tips/src/lib.rs
frame/treasury/src/lib.rs
frame/vesting/src/lib.rs

fixes some of #8106
Thank you!

Check `unreserve` and `transfer` returnvalues in debug code

---

Cargo.lock
bin/node/browser-testing/Cargo.toml
bin/node/cli/Cargo.toml
client/authority-discovery/Cargo.toml
client/cli/Cargo.toml
client/network-gossip/Cargo.toml
client/network/Cargo.toml
client/network/src/discovery.rs
client/network/src/transport.rs
client/network/test/Cargo.toml
client/peerset/Cargo.toml
client/telemetry/Cargo.toml
client/telemetry/src/transport.rs
primitives/consensus/common/Cargo.toml
utils/browser/Cargo.toml

This PR updates `libp2p` to `0.36`. The full changelog compared to `0.35.1` [can be seen here](https://github.com/libp2p/rust-libp2p/compare/v0.35.1...v0.36.0). The highlights are:
* "Parallel negotiation" is re-enabled for `multistream-select` (https://github.com/libp2p/rust-libp2p/pull/1934) and takes effect when the dialer has 3 or more alternative protocols for a particular upgrade. I don't think this case actually ever happens in substrate though, so there should be no surprises.
* `libp2p-mdns` has undergone a larger refactoring and sends queries much less aggressively (https://github.com/libp2p/rust-libp2p/pull/1977), which should be compensated for by queries sent whenever a multicast group is joined on a network interface. If there should be unforeseen issues, the query interval …

Update to libp2p-0.36

---

client/network/src/protocol.rs

This message is important enough to use DEBUG instead of TRACE.

Use Debug for genesis mismatch message

---

frame/support/procedural/src/pallet/expand/call.rs
frame/support/src/dispatch.rs

The code generated to compute weight use local variables which names can conflict with dispatchable arguments.
In the past if a call has an argument `weight: bool` the name `weight` would conflict with the local variable.

Fix local variable names conflict in pallet call expansion

---

Cargo.lock
test-utils/test-runner/Cargo.toml

Should fix CI check `test-linux-stable` failing  with `the lock file /builds/parity/substrate/Cargo.lock needs to be updated but --locked was passed to prevent this`. https://gitlab.parity.io/parity/substrate/-/jobs/866870#L63

Remove redundant libp2p dependency from test runner

---

frame/atomic-swap/src/lib.rs

Converts the atomic swap pallet to the new pallet attribute macro
Part of #7882.
[Upgrade guidelines used](https://crates.parity.io/frame_support/attr.pallet.html#upgrade-guidelines).
> storages now use PalletInfo for module_prefix instead of the one given to `decl_storage`: use of this pallet in `construct_runtime!` needs careful updating of the name in order to not break storage or to upgrade storage (moreover for instantiable pallet). If pallet is published, make sure to warn about this breaking change.
So users of the atomic swap pallet must be careful about the name they used in `construct_runtime!`. Hence the `runtime-migration` label, which might not be needed depending on the configuration of …

Upgrade pallet atomic swap

---

.maintain/gitlab/check_polkadot_companion_status.sh

Apparently if the pr isn't approved it counts as not mergable. However,
this is rahter confusing. To fix this, we just change the order.

Change companion check order

---

.maintain/gitlab/check_polkadot_companion_status.sh

Fix: https://github.com/paritytech/substrate/pull/8460

Fix companion check

---

client/network/src/service.rs

This functionality exists but wasn't exposed in the API of `NetworkService`.

Add NetworkService::add_known_address

---

Cargo.lock
client/consensus/aura/src/lib.rs
client/consensus/babe/src/lib.rs
client/consensus/slots/Cargo.toml
client/consensus/slots/src/lib.rs
client/consensus/slots/src/slots.rs

This makes the code a little bit easier to read and also expresses that
there can always only be one call at a time to `on_slot`.

Use `async_trait` in sc-consensus-slots

---

Cargo.lock
bin/node/runtime/src/lib.rs
frame/election-provider-multi-phase/src/mock.rs
frame/staking/src/lib.rs
primitives/npos-elections/compact/Cargo.toml
primitives/npos-elections/compact/src/lib.rs
primitives/npos-elections/compact/tests/ui/fail/missing_accuracy.rs
primitives/npos-elections/compact/tests/ui/fail/missing_accuracy.stderr
primitives/npos-elections/compact/tests/ui/fail/missing_target.rs
primitives/npos-elections/compact/tests/ui/fail/missing_target.stderr
primitives/npos-elections/compact/tests/ui/fail/missing_voter.rs
primitives/npos-elections/compact/tests/ui/fail/missing_voter.stderr
primitives/npos-elections/compact/tests/ui/fail/no_annotations.rs
primitives/npos-elections/compact/tests/ui/fail/no_annotations.stderr
primitives/npos-elections/compact/tests/ui/fail/swap_voter_target.rs
primitives/npos-elections/compact/tests/ui/fail/swap_voter_target.stderr
primitives/npos-elections/fuzzer/src/compact.rs
primitives/npos-elections/src/tests.rs

Closes #8444.
polkadot companion: https://github.com/paritytech/polkadot/pull/2707
Just changes the parsing logic for that macro; does not change any
emitted code. The associated types associated with the macro now
require explicit, keyword-style declaration.
**Note**: while the new syntax looks like keyword arguments from a language such as Python,
unlike real keyword arguments, the order still matters. Checks in the syntax parser ensure that 
the right arguments appear in the right order. 
**Old**:
```rust
sp_npos_elections::generate_solution_type!(
#[compact]
pub struct TestCompact::<VoterIndex, TargetIndex, PerU16>(16)
);
```
**New**:
```rust
sp_npos_elections::generate_solution_type!(
#[compact]
pub struct TestCompact::<VoterIndex = VoterIndex, CandidateIndex = TargetIndex, Accuracy …
```

make types within `generate_solution_type` macro explicit

---

frame/election-provider-multi-phase/src/lib.rs
frame/election-provider-multi-phase/src/unsigned.rs
frame/elections-phragmen/src/lib.rs
frame/staking/src/lib.rs
frame/staking/src/tests.rs

I accidentally removed this in #8113

Bring back the on_finalize weight of staking.

---

Cargo.lock
utils/frame/remote-externalities/src/lib.rs
utils/frame/try-runtime/cli/src/lib.rs

Changes remote-externalities to use a `PathBuf` internally instead of a directory and file name and changes the cli sub-command try-runtime to take a single 'PathBuf' as well.
This is a follow-up to #8397.

Use pathbuf for remote externalities

---

client/db/src/lib.rs
client/db/src/upgrade.rs

Justifications were double-encoded previously, we forgot to decode the justification we get from the database when migrating.
Nodes that had already run this migration will need to resync as it would be necessary to detect which justifications are in which format and that was dangerous and not worth it for something that was not released.

client: fix justifications migration

---

client/network/src/protocol/sync.rs

Fixes https://github.com/paritytech/cumulus/issues/382#
See linked issue for details

Fix sync restart for peers that provide block justifications

---

client/tracing/src/logging/event_format.rs
client/tracing/src/logging/mod.rs

When logging to a file with additional logging targets set, it is useful to see basic progress and errors in the console. Substrate used to have this feature, but it was lost in a recent logging system refactoring. This PR restores it.

Duplicate logging to stdout

---

client/network/src/protocol/message.rs
client/network/src/protocol/sync.rs
client/network/test/src/lib.rs
client/network/test/src/sync.rs

In rare cases a block announcement would be ignored if a peers that sends has an outstanding block request. This PR fixes this by adding all announcement to fork targets.

Fixed sync skipping some block announcements

---

frame/session/src/lib.rs

Allows other pallets to look up validator ID by the session key.

Expose pallet_session::key_owner()

---

frame/support/src/storage/migration.rs
frame/support/src/storage/mod.rs
frame/tips/src/lib.rs

Fixes #8462.
This is my first substrate PR and I'm not sure if I've implemented everything correctly, reviewers please let me know of any changes I need to make. Thanks!

Add ChildTriePrefixIterator and methods

---

frame/assets/src/tests.rs

A few tests for assets pallet relates to #8470 :).

tests for assets pallet

---

client/finality-grandpa-warp-sync/src/lib.rs
client/finality-grandpa-warp-sync/src/proof.rs

Another pull request on top of https://github.com/paritytech/substrate/pull/8392
Changes:
- Adds a check in `verify` that the verification targets the header that comes with it, otherwise someone could send a different header where the authorities set change isn't the same.
- Adds to the proof the header corresponding to the latest finalized. It was notoriously missing, which would have forced us to do an additional network request just for this header.
- Removes `WarpSyncFinished`. I don't understand why we needed to special-case the latest justification. It is now part of the proof, which is IMO more simple.

Another tweak to GrandPa warp sync

---

client/db/src/lib.rs
client/db/src/storage_cache.rs

There was a caching issue with `storage_hash` that resulted in not
reverting cached storage hashes when required. In Cumulus this resulted
in nodes failing to import new blocks after a runtime upgrade, because
they were using the old runtime version.
Besides that, this pr optimizes for the Cumulus use case. In particular
that we always import blocks first as non-best blocks and enact them
later. In current version of the caching that would mean we would always
throw away the complete cache of the latest imported block. Now, we
always update the cache for the first block of a new block height. This
enables us to use the cache if this block will enacted as best block
later. If there is a fork and that is enacted as best, we revert all the
changes to the cache.

Fixes `storage_hash` caching issue and enables better caching for Cumulus

---

Cargo.lock
utils/frame/remote-externalities/Cargo.toml

When updating dependencies, Cargo brings the latest `0.2.0-alpha.4` version of jsonrpsee which contains breaking changes and a hard `tokio 1.0` dependency (https://github.com/paritytech/jsonrpsee/blob/2f6c8e9e859d52948ab065012db32652673cda23/utils/Cargo.toml#L21).

Pin jsonrpsee

---

frame/lottery/src/lib.rs
frame/membership/src/lib.rs
frame/tips/src/lib.rs

Properly declare errors in pallets that use decl_module

---

client/state-db/src/lib.rs
client/state-db/src/noncanonical.rs

Currently when a block `N` is canonicalized, all discarded branches are removed from the canonicalization overlay immediately (unless pinned). They are also removed from the DB. The may lead to a situation, when out of two journals, for block `N+1` and `N+1'`, the former is discarded and the latter remains in the DB. 
On startup the journals are loaded by trying DB keys for each block number, increasing the journal sub-index starting from 0. So if sub-index 0 is missing and sub-index 1 is there, it won't be loaded. 
On kusama/polkadot this has low chance of happening, because forks of more than 1 block in length are rare and the node needs to be stopped/restarted on such a fork for the issue to happen. On rococo forks are more likely due to increased finality window and there are a lot of …

Fixed restoring state-db journals on startup

---

frame/election-provider-multi-phase/src/unsigned.rs
frame/system/src/extensions/check_weight.rs
primitives/runtime/src/lib.rs

To make the life of people easier ;)

Use `log::error!` for bad mandatory

---

bin/node/cli/src/chain_spec.rs
bin/node/runtime/src/lib.rs
bin/utils/chain-spec-builder/src/main.rs

For certain reasons I am interested in building chain-specs that have a handful of authorities (validators) and lots and lots of nominators (testing election stuff).

Add nominators option to chain-spec-builder

---

client/network/src/light_client_requests/handler.rs
client/network/src/protocol.rs
client/network/src/protocol/notifications/behaviour.rs
client/network/src/service.rs
client/network/src/transactions.rs

I reviewed most of the `debug!` and `trace!` lines in `sc_network`.
After this PR, `debug` will actually mean "useful information about what happens, and abnormal situations" and `trace` will mean "log everything in case we're actively debugging something".

Clean up log levels in sc_network

---

primitives/runtime/src/curve.rs
primitives/runtime/src/generic/digest.rs
primitives/runtime/src/generic/era.rs
primitives/runtime/src/generic/header.rs
primitives/runtime/src/generic/unchecked_extrinsic.rs
primitives/runtime/src/lib.rs
primitives/runtime/src/multiaddress.rs
primitives/runtime/src/offchain/storage_lock.rs
primitives/runtime/src/traits.rs
primitives/runtime/src/transaction_validity.rs

All changes in this PR are all trivial improvements to reduce some linter warnings when exploring the code:
-  Use `Self` instead of the type's name.
- Use `matches!`.
- Remove some extra empty lines.
- Impl `From` instead of `Into`.

Add some trivial improvements to primitives runtime

---

bin/node-template/runtime/src/lib.rs
bin/node/runtime/src/constants.rs
bin/node/runtime/src/lib.rs

Teams have [been surprised](https://github.com/paritytech/substrate/issues/7458#issuecomment-809711582) by epoch duration not being changeable, so this PR adds the note in more places so that people are more likely to see it.
@andresilva Would also be cool to add a quick "Why?" to the original doc comment.

add more notes on changing epoch duration

---

client/network/src/service.rs

After discussion with Roman and Max a while ago, these errors are benign.

Don't report confusing unsupported protocol errors

---

frame/session/src/lib.rs
frame/session/src/tests.rs

closes https://github.com/paritytech/substrate/issues/8536

Fix account ref-counting in session

---

.github/workflows/monthly-tag.yml
.maintain/gitlab/generate_changelog.sh

Sets git fetch depth to 0 (i.e., all branches and tags). Also fixes issue with the GITHUB_TOKEN (no need for casting it to GITHUB_DEPLOY_TOKEN, since lib.sh will happily just accept it as-is). Also updated a label.

Fix monthly tags

---

client/network/src/protocol.rs
client/network/src/protocol/sync.rs

Two issues fixed here:
1. After #7733 peers may enter common block/ancestry search mode when common block is detected to be too far behind. However this should not be happening when major sync is in progress. I've added a check for that.
2. Peers starting common block search in the middle of the major sync resulted in common block being a bit behind of the import queue, which leads to duplicate requests and bans.
3. Since we only drain downloaded blocks on new block data, a canceled duplicate request at the front of the download range may result in stalemate situation, where we don't issue new download requests because the block container is already full and we don't drain the block container because there are no incoming blocks. To fix that I've added a check for blocks that may be …

Drain blocks on peer disconnect

---

frame/support/procedural/src/lib.rs
frame/support/procedural/src/pallet/expand/instances.rs
frame/support/procedural/src/storage/instance_trait.rs
frame/support/src/instances.rs
frame/support/src/traits/storage.rs

This PR introduces a simple `const INDEX: u8;` to the Instance trait used for Pallets.
This is useful for getting a minimal unique identifier for different instances, for example using it as a seed to some unique account generation.
The `DefaultInstance` uses `index == 0`, so we deprecate `Instance0` (which wasn't used anywhere) and instead use instances `1 ..= 16`.

Add an INDEX to the Instance trait

---

client/db/src/bench.rs
frame/benchmarking/src/analysis.rs
frame/benchmarking/src/lib.rs
frame/benchmarking/src/utils.rs
primitives/externalities/src/lib.rs
primitives/state-machine/src/backend.rs
primitives/state-machine/src/ext.rs
utils/frame/benchmarking-cli/src/command.rs
utils/frame/benchmarking-cli/src/lib.rs
utils/frame/benchmarking-cli/src/writer.rs

This PR introduces the PoV Tracking / Proof Recorder into the Runtime Benchmarking Pipeline.
In summary, when a parachain presents a new block for the relay chain to validate, it must also provide a minimal PoV block which contains all the necessary storage items which can be used to prove the validity of the state transition.
This means if you are trying to transfer a balance between two accounts on a parachain, you need to provide some subsection of the full state trie to the relay chain which contains those two account balances.
Due to the base-16 Patricia-Merkle trie used in Substrate, this can end up being a lot of extra data. We need to not only confirm that a block of extrinsics would execute in time, but also that the PoV block needed for all those extrinsics would fit within the …

Add PoV Tracking to Benchmarking Pipeline

---

.maintain/gitlab/check_polkadot_companion_build.sh

https://github.com/paritytech/polkadot/pull/2834 removes this feature, so we don't need it in Substrate anymore

remove real-overseer from polkadot compilation flags

---

client/authority-discovery/src/lib.rs
client/authority-discovery/src/worker.rs
client/authority-discovery/src/worker/tests.rs

The code of the authority-discovery worker at the moment does something like:
```
loop {
publish(load_from_keystore());
wait(one hour);
}
```
This PR adds another piece of code that does:
```
loop {
publish_if_changed(load_from_keystore());
wait(one minute);
}
```
We still unconditionally publish on the DHT every hour (as this is important), but we also check every minute if the keys in the keystore have changed.
The way this is implemented, the one hour timer does not reset to one hour if we detect a change in the keystore, while one can argue that theoretically it should. This is at the level of bikeshedding, and since the keystore changing keys is expected to be uncommon, this really doesn't mater.

Check every minute whether authority-discovery key has changed

---

.gitlab-ci.yml

Resolves paritytech/ci_cd#11 via itself and [`node-bench-regression-guard`](https://github.com/paritytech/scripts/tree/master/dockerfiles/node-bench-regression-guard) tool. 
This PR makes following changes to the project's pipeline:
* adds relevant `node-bench-regression-guard` job
* changes logic of `cargo-check-benches` job
* adds `cargo-check-benches-merged` job, which does the same thing as `cargo-check-benches`, but with PR's source branch already merged into `master`
* adds `verify` stage. `needs` is [unable](https://gitlab.com/gitlab-org/gitlab/-/issues/30632) to calculate the dependency graph when referring to the jobs in the same stage
* adds relevant YAML anchors
`git fetch` with plus sign is used here for `cargo-check-benches-merged` to forcefully change needed refspecs to the …

Introduce `node-bench-regression-guard` to Substrate's pipeline

---

frame/support/src/origin.rs
frame/support/src/traits/dispatch.rs

Without these changes, it's difficult/impossible to not lose any filters when making fine-grained matches against origin.

Allow lossless matching for Origin

---

.gitlab-ci.yml

This PR accompanies paritytech/substrate#8519 and makes following changes:
* remove `allow_failure` directive from `node-bench-regression-guard` job as described [here](https://github.com/paritytech/substrate/pull/8519#issue-608012386)

Disallow failure for `node-bench-regression-guard` job

---

frame/collective/src/lib.rs
frame/support/src/traits.rs
frame/support/src/traits/misc.rs

Small types an an integration into Collective pallet for them. This allows XCM to interpret Collective origins without needing to be exposed to the pallet. It also allows other n-of-m origins in the future to be automatically supported by XCM.

Backing/GetBacking: Abstraction over pluralistic origins for XCM.

---

Cargo.lock
bin/node/runtime/src/impls.rs
frame/contracts/proc-macro/src/lib.rs
primitives/arithmetic/Cargo.toml
primitives/arithmetic/src/biguint.rs
primitives/arithmetic/src/fixed_point.rs

Closes https://github.com/paritytech/substrate/issues/8364

clean arithmetic and unify names with the new api

---

client/finality-grandpa-warp-sync/src/lib.rs
client/finality-grandpa-warp-sync/src/proof.rs

The proof we get for Kusama turns out to be larger than what the networking protocol allows.
This does it properly.

Cap the warp sync proof by size, not by fragments

---

frame/support/src/lib.rs

Make it work with different kinds of parameter types when
`static` is one of them.
Fixes: https://github.com/paritytech/substrate/issues/8592

Fix `parameter_types!` macro

---

frame/example-offchain-worker/src/lib.rs

Also made the code a bit more idiomatic by leveraging the use of `?`.
The problem with the previous algorithm was that the iterator for `"USD"` is not reset back to the starting position in subsequent iterations of the `find` function, i.e. imagine we have the following JSON:
```json
{
"UAH": 214,
"USD": 342
}
```
The original code would first see that the "UAH" string matches the first character, and it would continue to match the next one (matching `'A'` with `'S'`), but doesn't find a match, _then it will stay at the `'S'` position when looping to the next key_. This means it will erroneously refuse to match against the second key (`"USD"`) in this example.
Though it's impossible to get a JSON that has more than 1 entry in the OCW example, I feel like it's best to get this algorithm …

Fix buggy string comparison in OCW pallet example

---

utils/wasm-builder/src/wasm_project.rs

This is an update to the WASM build process and requires review - related to Issue #8597.
Although this is not specifically a bug in Substrate when using it alone, there is an impact when referencing Substrate-based runtime/pallets when cross-compiling with Cumulus (current Master). 
The scenario would be that a team is attempting to include their pallets and runtime via a git path to their Substrate-based chain.
A compile error is seen in these circumstances but can be resolved by this update. In any case the `-Zfeatures=build_dep` is no longer required due to features resolver 2 being stable it should be replaced. 
```shell
error: failed to run custom build command for `cumulus-test-runtime v0.1.0 (/Users/chris/gitlab/totem-cumulus/test/runtime)`
Caused by:
process didn't exit …
```

#8597 Update features resolver wasm build

---

frame/support/src/traits/tokens/misc.rs

Fixes #8586 
It is part of the previous re-orgs of the files related to new token functionality implement by @shawntabrizi @gavofyork @bkchr - so could be reviewed by them.
There are no known breaking consequences to this change as the code that would break this is not implemented. However it restricts enhancements.
**Issue comments reproduced here for convenience:**
Using `i8` would produce an literal overflow error for values such as `0b10000000`. 
The error can be reproduced by attempting to compile with a test value:
```rust
bitflags::bitflags! {
/// Reasons for moving funds out of an account.
#[derive(Encode, Decode)]
pub struct WithdrawReasons: i8 {
/// In order to pay for (system) transaction costs.
const TRANSACTION_PAYMENT = 0b00000001;
/// In order to transfer ownership.
const …
```

Fix for #8586 WithdrawReasons type change from i8 to u8

---

frame/contracts/src/exec.rs
frame/democracy/src/benchmarking.rs
frame/democracy/src/tests/decoders.rs
frame/democracy/src/tests/external_proposing.rs
frame/democracy/src/tests/public_proposals.rs
frame/democracy/src/tests/voting.rs
frame/election-provider-multi-phase/src/unsigned.rs
frame/executive/src/lib.rs
frame/grandpa/src/tests.rs
frame/system/src/extensions/check_nonce.rs
frame/system/src/extensions/check_weight.rs
frame/system/src/tests.rs
frame/transaction-payment/src/lib.rs

Change assert(is_err()) to assert_noop to check state consistency on errors

---

frame/timestamp/src/lib.rs

So we can use it in runtime benchmarks, which compiles to wasm.

expose set_timestamp for runtime benchmarks

---

client/cli/src/config.rs
client/cli/src/params/network_params.rs

cc https://github.com/paritytech/substrate/issues/7467
The peer-to-peer endpoint of the client supports two modes: plain TCP connections, and WebSockets.
Multiaddresses that look like `/ip4/<ip>/tcp/<port>` use plain TCP connections, while multiaddresses that look like `/ip4/<ip>/tcp/<port>/ws` use WebSockets.
When using WebSockets, the Noise and Yamux protocols are applied on top of each WebSocket connection, like they are on plain TCP connections. The WebSockets "layer" is not a replacement for anything, but is inserted in the middle of the protocols stack.
The reason why WebSockets are supported in the first place is: light clients in browsers. It is part of the Web3 vision to directly connect to the network, without using an untrusted JSON-RPC endpoint, and for user-friendliness …

Make non-validators listen on /ws by default

---

client/authority-discovery/src/worker/addr_cache.rs

The `debug_assertion` in `addr_cache.rs` line 95 was found to panic on our canary node.
This assertion seems to assume that there must always be a consistency between the two mappings (authority->peerids and peerid->authority). This isn't the case right now: if an authority changes `PeerId`, or if a `PeerId` is found to also be associated to another authority, there might be entries in one of the maps that aren't present in the other.
In addition, this makes me realize another problem: when an authority changes `PeerId`, the former entry in the peerid->authority map will never be removed. This is a very slow memory leak.
There are two ways to fix that: either add a guarantee of consistency between the two maps, or keep the code as is but remove the `debug_assert!`. I went for the first …

Fix debug_assertion failing in authority discovery

---

frame/assets/src/benchmarking.rs
frame/assets/src/extra_mutator.rs
frame/assets/src/functions.rs
frame/assets/src/impl_fungibles.rs
frame/assets/src/impl_stored_map.rs
frame/assets/src/lib.rs
frame/assets/src/types.rs

As mentioned in https://github.com/paritytech/substrate/issues/8453#issuecomment-809272236, making the assets pallet instantiable allows one to better group sets of assets that share something in common instead of putting everything in a single big group that might require some sort of filtering on the pallets that depend on some fungibles.

Make pallet Assets instantiable

---

.gitlab-ci.yml
.maintain/gitlab/trigger_pipeline.sh

- optimize bench jobs
- add bench to triggered job
- no need in manual builds
- when build, we publish, it's not changed
- more logs to the trigger job

CI updates

---

Cargo.lock
bin/node/browser-testing/Cargo.toml
bin/node/cli/Cargo.toml
client/authority-discovery/Cargo.toml
client/cli/Cargo.toml
client/network-gossip/Cargo.toml
client/network/Cargo.toml
client/network/src/discovery.rs
client/network/src/peer_info.rs
client/network/src/protocol.rs
client/network/src/protocol/notifications/tests.rs
client/network/src/request_responses.rs
client/network/src/service.rs
client/network/src/utils.rs
client/network/test/Cargo.toml
client/peerset/Cargo.toml
client/telemetry/Cargo.toml
primitives/consensus/common/Cargo.toml
utils/browser/Cargo.toml

The biggest PRs are:
- https://github.com/libp2p/rust-libp2p/pull/1995 (all the `behaviour_mut()` changes)
- https://github.com/libp2p/rust-libp2p/pull/2011 (the `inject_` changes)
- https://github.com/libp2p/rust-libp2p/pull/1999 for the changes related to identify.
None of the changes touch anything related to connections or existing protocols, so I don't think a burn-in is necessary.
polkadot companion: https://github.com/paritytech/polkadot/pull/2894

Update to libp2p 0.37

---

Cargo.lock
frame/contracts/Cargo.toml
frame/contracts/common/Cargo.toml
frame/contracts/rpc/Cargo.toml
frame/contracts/rpc/runtime-api/Cargo.toml
frame/contracts/src/benchmarking/code.rs
frame/contracts/src/tests.rs
frame/contracts/src/wasm/env_def/macros.rs
frame/contracts/src/wasm/prepare.rs

The contracts pallet depended on rather old versions of `pwasm-utils` and `parity-wasm`. This PR updates those to the newest version. While at it the `Cargo.toml` files got a cleanup, too. Additionally, two other dependencies `rand` and `pretty_assertions` are also bumped to the newest semver.

Update dependencies of pallet_contracts

---

client/consensus/slots/src/lib.rs

Was showing up like this:
```
2021-04-19 20:49:42  ⏱  Loaded block-time = 6s milliseconds from genesis on first-launch
```

client: remove time unit from block time loaded message

---

client/cli/src/params/network_params.rs

The `--no-private-ipv4` option is now enabled by default for "live" chains such as Westend, Rococo, Kusama, and Polkadot.
Consequently, I've added a new `--allow-private-ipv4` option, which forces the opposite.
Concretely speaking, this means that nodes will no longer connect to any IP address that is considered as private (such as `10.0.0.1`).

Enable --no-private-ipv4 by default for live chains

---

Cargo.lock
bin/node/cli/src/service.rs
client/authority-discovery/Cargo.toml
client/authority-discovery/src/lib.rs
client/authority-discovery/src/worker.rs

The authority discover no longer publishes non-global IP addresses on the DHT, unless the user is running a local/dev chain or if `--discover-local` is passed.
polkadot companion: https://github.com/paritytech/polkadot/pull/2908

Authority-discovery no longer publishes non-global IP addresses

---

client/network/src/protocol/notifications/handler.rs
client/network/src/protocol/notifications/upgrade/notifications.rs

Reverts https://github.com/paritytech/substrate/pull/8534
I tried fixing the code in https://github.com/paritytech/substrate/pull/8645, but it's only the tip of the iceberg.
It is really way too complicated, so let's revert in order to make it work.
Close #8645

Revert "Properly close notification substreams (#8534)"

---

Cargo.lock
utils/frame/remote-externalities/Cargo.toml
utils/frame/remote-externalities/src/lib.rs

To get rid of the annoying manual dependency  `jsonrpsee-types`

[frame util/remote ext]: update jsonrpsee to 0.2.0-alpha.5

---

frame/contracts/src/wasm/prepare.rs

#8637 disallowed the legacy `() -> (i32)` signature for contract entry points. The returned value of a contract was never evaluated since the overhaul of the API. In order to return a non zero status code `seal_return` **must** be used.
That said, ink! seems to make use of this signature and therefore we revert this change for compatibility reasons. Contract languages should move away from this deprecated entry point and use `() -> ()`.
cc @Robbepop @seanyoung

contracts: Allow () -> (i32) for backwards compatibility

---

client/cli/src/params/offchain_worker_params.rs
client/db/src/lib.rs

Currently the `--enable-offchain-indexing` CLI option would be taken into consideration iff off-chain workers are enabled as well.
This is incorrect, these two features serve different purposes and are designed to work separately, so it's not necessary to run off-chain workers for anything at all.

Off-chain indexing is independent from workers

---

Cargo.lock
bin/node/executor/tests/fees.rs
bin/node/runtime/src/impls.rs
frame/transaction-payment/src/lib.rs
primitives/arithmetic/src/fixed_point.rs

useful for some generic code
polkadot companion: paritytech/polkadot#2922

impl Zero and One for fixed point numbers

---

primitives/core/src/lib.rs
primitives/io/src/lib.rs
primitives/runtime/src/runtime_logger.rs
test-utils/runtime/src/lib.rs

This should fix performance problems introduced by logging under certain
circumstances. Before we always called into the host and the host was
doing the log filtering, now as the correct max log level is set, we
don't call into the host for every log line to check if it should be
logged. However, we would still call into the host to determine if
something should be logged when `something=trace` is given as we don't
forward the log targets that are enabled.
Fixes: https://github.com/paritytech/substrate/issues/8611

Use host max log level when initializing the `RuntimeLogger`

---

Cargo.lock
utils/wasm-builder/Cargo.toml
utils/wasm-builder/src/wasm_project.rs

I ran into a strange panic in this crate when syncing `canvas-node` to Substrate. Upgrading this dependency seems to fix it.
The notable thing is that `crate_metadata.workspace_root` is a `Utf8PathBuf` now.

Upgrade `cargo_metadata` to 0.13.1

---

Cargo.lock
bin/utils/subkey/Cargo.toml
bin/utils/subkey/README.adoc
bin/utils/subkey/src/lib.rs

this will allow for installing subkey  with cargo as described here https://substrate.dev/docs/en/knowledgebase/integrate/subkey much easier.
This does not need to be published on crates.io, but it could be. Happy to open an issue if this would be simple to maintain.

[Companion] Update Cargo.toml subkey version, readme to reflect new output

---

client/network/src/peer_info.rs
client/network/src/service.rs

Fix reliance on non-empty NodeInfo::endpoints

---

Cargo.lock
bin/utils/subkey/Cargo.toml
bin/utils/subkey/README.adoc
bin/utils/subkey/src/lib.rs
client/cli/src/commands/utils.rs

In case of sr25519 and ed25519 crypto, the account id matches public key, hence SS58 encoded account-id address is the same as SS58 public key encoding.
In case of ECDSA, we blake2 the public key to get the address (due to size difference 33 vs 32 bytes), so the SS58 encoding was different.
Why is SS58 encoding of public key necessary at all?
Default Ser/De implementation for public keys is using SS58 encoding, hence every time we use public keys in encoded form we are going to need it's SS58 encoding. A notable case is chain spec JSON file and encoding of session keys (most importantly BEEFY).
This PR adds display of SS58 encoding of raw public key to make it easy to add BEEFY keys to chain spec json file.
CC @NukeManDan

subkey: display SS58 encoding of public key

---

client/transaction-pool/graph/src/validated_pool.rs

Currently we can read the `ready` queue and the `status` from the validated pool, but there is no way of reading future transactions.
This PR proposes allowing to do so by adding a public method that reads the pool and collects a vector of transaction hashes and extrinsic data.
The motivation for this is to be able to:
- Enable testing of future transactions in Frontier, so we can verify that this is correctly handled in the case of `pallet-ethereum`'s unchecked extrinsics.
- Implement commonly used ethereum RPC extensions like [geth's txpool](https://geth.ethereum.org/docs/rpc/ns-txpool).

Add future transactions accessor to `ValidatedPool`

---

docs/Upgrading-2.0-to-3.0.md

I'm terrible at spelling so I have a spellchecker in my vscode setup and it picked up a few things.

Fixed typos in upgrade readme.

---

frame/executive/src/lib.rs

Fix https://github.com/paritytech/substrate/issues/8683
All pallets runtime upgrade is now executed after the custom runtime upgrade provided to `Executive`.
(instead before, frame system pallet runtime upgrade was executed first).
This doesn't deprecated the runtime upgrade of pallets (though I'm also in favor of deprecating them). This can be done in another PR, easiest implementation is just to rename `on_runtime_upgrade` to `deprecated_on_runtime_upgrade` for pallet on runtime upgrade hook.

Make custom on runtime upgrade prior to pallet ones

---

client/network/src/protocol.rs
client/network/src/protocol/notifications/behaviour.rs
client/network/src/service.rs
client/peerset/src/lib.rs
client/rpc-api/src/system/mod.rs
client/rpc/src/system/mod.rs
client/rpc/src/system/tests.rs
client/service/src/lib.rs

Fixes https://github.com/paritytech/substrate/issues/8147
Adds a `reservedPeers` rpc call to return peers added/removed through `addReservedPeer` and `removeReservedPeer`.
> Is there something left for follow-up PRs?
Yes. The work is in progress

Add a JSON-RPC layer for reserved nodes

---

client/network/src/protocol/notifications/behaviour.rs

Fix #8715 
If we have two active connections, one being closed, and one where the remote has tried re-opening a substream, then this will currently produce an error, even though this is a completely correct state.
Fixed that.
As to why there is no test: as always, it's super hard to test this because, since this is an internal state machine, it's hard to actually figure out which states are correct and which are not, as hard as actually reading/writing the code.
#7678 should eventually help with testing.

Fix too generous error detection in behaviour.rs

---

client/network/src/config.rs

This needs to go in before we can merge https://github.com/paritytech/substrate/pull/8682
The Polkadot companion check in the CI of https://github.com/paritytech/substrate/pull/8682 fails because the `grandpa-bridge-gadget` library [manually creates a `NonDefaultSetConfig`](https://github.com/paritytech/grandpa-bridge-gadget/blob/4c7248ef67824cc2000d51a947f147bafe19f0aa/beefy-gadget/src/lib.rs#L48), while https://github.com/paritytech/substrate/pull/8682 modifies the definition of this struct.
In order to solve that, the idea is:
- Merge this PR (this one that you're reading right now)
- Modify `grandpa-beefy-gadget` to use the new API introduced in this PR.
- Merge https://github.com/paritytech/substrate/pull/8682 afterwards.

Add some builder functions for NonDefaultSetConfig

---

frame/support/src/storage/bounded_vec.rs

This adds some useful APIs for making the conversion from `Vec` to `BoundedVec` more seamless.

Improve `BoundedVec` API

---

bin/node-template/runtime/src/lib.rs
bin/node/runtime/src/lib.rs
client/rpc/src/state/tests.rs
primitives/block-builder/src/lib.rs
test-utils/runtime/src/lib.rs

The `BlockBuilder` API has a method `random_seed` which is unused and unsafe to use. Users that need randomness from the runtime should instead use the `Randomness` API. 
polkadot companion: https://github.com/paritytech/polkadot/pull/2968

primitives: remove random_seed from BlockBuilder API

---

bin/node/cli/src/cli.rs
bin/node/inspect/src/cli.rs
bin/node/inspect/src/command.rs
bin/utils/subkey/src/lib.rs
client/cli/src/commands/inspect_key.rs
client/cli/src/commands/key.rs
client/cli/src/commands/mod.rs

For consistency between the two tools, the subcommand for `<node bin> key inspect-key` is changed to match `subkey` syntax ( `subkey inspect`)
This _may_ need modification of downstream dependencies in Polkadot and other code bases. I do not see this is the case, bu would be good to have a double-check on that and a companion PR made if so.
Alternatively to this PR, changing the subkey `inspect` command to `inspect-key` would have the same (but more verbose) effect.
Compliments/Related to #8674

Change to use the same subcommand syntax as subkey

---

frame/support/src/storage/bounded_vec.rs

Builds on https://github.com/paritytech/substrate/issues/8719. After that PR is merged, the merge base of this PR should be adjusted to `master`.

impl BoundedEncodedLen for BoundedVec

---

client/rpc/src/system/tests.rs
client/tracing/src/logging/directives.rs
client/tracing/src/logging/mod.rs

Before this pr changing the log directives would not change the max log
level. This means that if the node was started with `info` logging and
some `trace` logging was enabled, this `trace` wouldn't be logged. To
fix this we also need to update the max log level. This max log level is
used by the log macros to early return.

Set max log level when changing the log directives via RPC

---

frame/support/src/storage/bounded_vec.rs
frame/support/src/traits.rs
frame/support/src/traits/bounded_encoded_length.rs
frame/support/src/traits/max_encoded_len.rs

Work moved from https://github.com/paritytech/parity-scale-codec/pull/267
In support of https://github.com/paritytech/substrate/issues/8719

implement BoundedEncodedLen

---

frame/system/src/lib.rs

Can we make all migrations public in the future? I don't see why this wouldn't be the default.

Makes system migrations public

---

client/cli/src/commands/build_spec_cmd.rs
client/cli/src/commands/check_block_cmd.rs
client/cli/src/commands/export_blocks_cmd.rs
client/cli/src/commands/export_state_cmd.rs
client/cli/src/commands/generate.rs
client/cli/src/commands/insert_key.rs
client/cli/src/commands/purge_chain_cmd.rs
client/cli/src/commands/run_cmd.rs
client/cli/src/commands/sign.rs
client/cli/src/commands/vanity.rs
client/cli/src/commands/verify.rs
client/cli/src/params/database_params.rs
client/cli/src/params/import_params.rs
client/cli/src/params/keystore_params.rs
client/cli/src/params/mod.rs
client/cli/src/params/network_params.rs
client/cli/src/params/node_key_params.rs
client/cli/src/params/offchain_worker_params.rs
client/cli/src/params/pruning_params.rs
client/cli/src/params/shared_params.rs
client/cli/src/params/transaction_pool_params.rs

Sprinkle some `Clone` onto the cli commands.

Let the clone wars begin!

---

frame/im-online/src/benchmarking.rs
frame/im-online/src/lib.rs
frame/im-online/src/tests.rs
frame/offences/benchmarking/src/lib.rs

Part of #7882.
Converts the `ImOnline` pallet to the new pallet attribute macro introduced in #6877.
So users of the `ImOnline` pallet must be careful about the name they used in `construct_runtime!`. Hence the `runtime-migration` label, which might not be needed …

Migrate pallet-im-online to pallet attribute macro.

---

primitives/core/src/crypto.rs
ss58-registry.json

This pr is used for removing ss58version for patract, which is not used anymore. We release this ss58version now.

remove patract ss58version for it's useless now

---

frame/nicks/src/lib.rs

Part of #7882.
Converts the `Nicks` pallet to the new pallet attribute macro introduced in #6877.
So users of the `Nicks` pallet must be careful about the name they used in `construct_runtime!`. Hence the `runtime-migration` label, which might not be needed …

Migrate pallet-nicks to pallet attribute macro.

---

primitives/utils/README.md
primitives/utils/src/lib.rs

This PR adds a readme about feature `metered` for `sp-utils`.

Add a readme about feature metered for sp-utils

---

frame/support/src/storage/bounded_vec.rs

@shawntabrizi pointed out that the max encoded length of a bounded struct can be limited by the encoded size of the bound, not the max possible value for the bound's type.

BoundedVec MaxEncodedLen microoptimization

---

frame/support/src/storage/bounded_btree_map.rs
frame/support/src/storage/bounded_vec.rs
frame/support/src/storage/mod.rs

Part of https://github.com/paritytech/substrate/issues/8719.
Tests ~~forthcoming~~ implemented.

Add `BoundedBTreeMap` to `frame_support::storage`

---

client/finality-grandpa/src/communication/tests.rs
client/finality-grandpa/src/lib.rs
client/network-gossip/src/bridge.rs
client/network/src/behaviour.rs
client/network/src/config.rs
client/network/src/gossip/tests.rs
client/network/src/protocol.rs
client/network/src/protocol/event.rs
client/network/src/protocol/notifications.rs
client/network/src/protocol/notifications/behaviour.rs
client/network/src/protocol/notifications/handler.rs
client/network/src/protocol/notifications/tests.rs
client/network/src/protocol/notifications/upgrade.rs
client/network/src/protocol/notifications/upgrade/notifications.rs
client/network/src/service.rs
client/network/src/service/tests.rs
client/network/src/transactions.rs
client/network/test/src/lib.rs

Close https://github.com/paritytech/substrate/issues/6605
There are some protocols in the networking stack that we would like to rename.
In order to do so while maintaining backwards compatibility, this PR introduces the possibility to pass a list of fallback names when configuring a protocol.
When the substream actually gets opened, a new `negotiated_fallback` field indicates which names has actually been used during the negotiation.
Most of the changes in this PR are small refactorings. Before this PR, we would pass information as a tuple of three elements. Adding a fourth element would be a bit too much, so I turned them into structs.
Important note: the `negotiated_fallback` field indicates the protocol used to negotiate the outbound substream. The one used for the inbound substream …

Allow fallback names for protocols

---

frame/support/procedural/src/lib.rs
frame/support/procedural/src/max_encoded_len.rs
frame/support/src/traits.rs
frame/support/test/tests/max_encoded_len.rs
frame/support/test/tests/max_encoded_len_ui.rs
frame/support/test/tests/max_encoded_len_ui/not_encode.rs
frame/support/test/tests/max_encoded_len_ui/not_encode.stderr
frame/support/test/tests/max_encoded_len_ui/not_mel.rs
frame/support/test/tests/max_encoded_len_ui/not_mel.stderr
frame/support/test/tests/max_encoded_len_ui/union.rs
frame/support/test/tests/max_encoded_len_ui/union.stderr
frame/support/test/tests/max_encoded_len_ui/unsupported_variant.rs
frame/support/test/tests/max_encoded_len_ui/unsupported_variant.stderr

Part of https://github.com/paritytech/substrate/issues/8719.

`#[derive(MaxEncodedLen)]`

---

frame/support/src/lib.rs
frame/support/src/storage/bounded_vec.rs
frame/support/src/storage/mod.rs
frame/support/src/storage/types/double_map.rs
frame/support/src/storage/types/map.rs
frame/support/src/storage/types/value.rs

A normal `Vec<T>` can do many things without any particular trait
bounds on `T`. This PR relaxes the bounds on `BoundedVec<T, S>`
to give it similar capabilities.

Relax `BoundedVec` trait restrictions

---

primitives/api/proc-macro/src/impl_runtime_apis.rs
test-utils/runtime/client/src/block_builder_ext.rs
test-utils/runtime/client/src/lib.rs
test-utils/runtime/client/src/trait_tests.rs

Before we required these trait bounds because of some bug in rustc, but
now as this bug is fixed they can be removed.

Remove unneeded trait bounds

---

client/authority-discovery/src/worker/addr_cache.rs

Two bugfixes:
- When `addresses` is empty, we shouldn't just return at the beginning, as we need to erase the previous addresses. `insert` is really `insert_or_replace`, similar to what `HashMap::insert` does. Inserting `Vec::new()` should remove the previous value.
- When an authority says it has a certain `PeerId`, we remove that `PeerId` from any previous authority. If this previous authority had multiple addresses (with the same `PeerId`) we will call `self.peer_id_to_authority_id.remove(&peer_id)` multiple times with the same value in `peer_id`. This is fine, but the debug assert just below (`debug_assert!(_old_auth.is_some());`) is wrong, as it will fail the second time.
Fix https://github.com/paritytech/polkadot/issues/2998

Two bugfixes to authority-discovery

---

frame/support/src/storage/bounded_btree_set.rs
frame/support/src/storage/mod.rs

Part of https://github.com/paritytech/substrate/issues/8719

Add `BoundedBTreeSet`

---

client/network/src/discovery.rs

Fix #2997
When we detect a new external IP address, we print a message saying "Discovered new external IP address for our node".
This external IP address is kept in a list internally within rust-libp2p, where a small minigame keeps the addresses that are the most reported and kicks out addresses that haven't been reported for a long time.
Because of this small minigame, addresses constantly kick each other out.
In order to avoid re-printing the message over and over again, we actually maintain a separate cache, in Substrate, of the addresses that have been reported to the user. This is the `known_external_addresses` field.
This variable exists just to not spam the users with the same IP multiple times.
However, it seems that users are still getting spammed, so this PR increases the size …

Increase the number of external IPs in cache

---

client/network/src/discovery.rs
client/network/src/utils.rs

This does https://github.com/paritytech/substrate/pull/8771 but differently.
I realized after merging https://github.com/paritytech/substrate/pull/8771 that it wasn't the correct fix.
The problem is that we remove entries from `known_external_addresses` when an address is considered expired. Addresses can become "expired" if they are replaced with another address.

Don't remove addresses from known_external_addresses

---

bin/node/cli/src/cli.rs
bin/node/inspect/src/cli.rs
bin/node/inspect/src/command.rs

#8678 introduced an error renaming a struct to `InspectKeyCmd` incorrectly, this brings it back to `InspectCmd`
The struct is internal only, so no version bump or release notes are needed (I think?) 
This introduced [an issue](https://github.com/paritytech/parity-bridges-common/pull/958#discussion_r626059296) upstream that this PR will correct.
> So we'll need a Substrate PR to revert the changes, and then a PR which bumps Substrate in this repo (and in that PR changes the name back)

Revert Changes: InspectKeyCmd back to InspectCmd where appropriate

---

frame/assets/src/benchmarking.rs
frame/assets/src/tests.rs
frame/balances/src/tests.rs
frame/balances/src/tests_reentrancy.rs
frame/bounties/src/benchmarking.rs
frame/collective/src/benchmarking.rs
frame/democracy/src/benchmarking.rs
frame/elections-phragmen/src/lib.rs
frame/identity/src/benchmarking.rs
frame/multisig/src/tests.rs
frame/proxy/src/benchmarking.rs
frame/proxy/src/tests.rs
frame/sudo/src/tests.rs
frame/system/src/lib.rs
frame/system/src/tests.rs
frame/transaction-payment/src/lib.rs
frame/utility/src/benchmarking.rs
frame/utility/src/tests.rs

Add two functions for frame system events assertion, to make it easier to check expected events in unit tests and benchmarking.
- `assert_has_event` asserts the given `event` exists.
- `assert_last_event` asserts the last event is equal to the given one.

frame system: add event util functions for tests.

---

frame/grandpa/src/lib.rs
frame/grandpa/src/tests.rs

Fixes https://github.com/paritytech/substrate/issues/1614.
Motivated by https://github.com/paritytech/substrate/pull/8615#discussion_r613253178, putting as a separate PR for easy review.

Remove grandpa `StoredPendingChange` shim

---

client/chain-spec/src/extension.rs

> What does it do?
Fixes warnings like:
```
warning: trait objects without an explicit `dyn` are deprecated
--> client/chain-spec/src/extension.rs:236:35
|
236 |             x if x == TypeId::of::<E>() => Any::downcast_ref(&self.base),
|                                            ^^^ help: use `dyn`: `<dyn Any>`
|
```

Fix warning: trait objects without an explicit dyn are deprecated

---

client/rpc/src/state/mod.rs
client/service/src/builder.rs

jsonrpsee ws server doesn't expose `CORS`yet let's allow for testing and so on.

[rpc]: enable all unsafe calls

---

frame/session/benchmarking/Cargo.toml

The `pallet-session-benchmarking` is used only for runtime benchmarks (?), but with no default features: https://github.com/paritytech/substrate/blob/8d02bb0bfc6136f6a3c805db19f51e43090a7cd4/bin/node/runtime/Cargo.toml#L76.
`frame-election-provider-support` has `std` enabled by default.
I've heard this was causing troubles with cargo unleash: https://gitlab.parity.io/parity/substrate/-/jobs/927455, which tries to strip all dev-dependencies.

frame/session/benchmarking: fix invalid feature declaration

---

client/offchain/src/lib.rs

When we're stumbling upon a situation where some specific thread(s) panic or use a lot of CPU, it's useful for threads to be named.
This is what this PR does.
Note that a proper situation would be to use the "spawner" system in the service, but this would be a way bigger change.

Add names to offchain worker threads

---

frame/assets/src/lib.rs
frame/assets/src/types.rs
frame/support/src/storage/types/key.rs

Use StorageNMap for Approvals in assets pallet

---

client/rpc-api/src/child_state/mod.rs
client/rpc/src/state/mod.rs
client/rpc/src/state/state_full.rs
client/rpc/src/state/state_light.rs

The following changes integrate the existing `read_child_proof` from the `ProofProvider` trait into the `ChildStateBackend`. 
To allow the generation of read proofs via RPCs on full nodes, the `ChildStateApi`
is extended with `read_child_proof`.
At the moment, especially useful for parachains who want to retrieve proof of contribution for crowdloan participants.

Extends ChildStateBackend and ChildStateAPI with ReadProofs

---

primitives/core/benches/bench.rs
primitives/core/src/changes_trie.rs
primitives/core/src/crypto.rs
primitives/core/src/ecdsa.rs
primitives/core/src/ed25519.rs
primitives/core/src/lib.rs
primitives/core/src/offchain/mod.rs
primitives/core/src/offchain/storage.rs
primitives/core/src/offchain/testing.rs
primitives/core/src/sr25519.rs
primitives/core/src/testing.rs
primitives/core/src/traits.rs

Fix `clippy` issues for crate `sp-core`.  Running 
```
cargo +nightly clippy --all-targets -- -D warnings --no-deps
```
for the crate no longer produces any errors. 
I did allow some clippy checks, where a change would have impacted the function/method signature.

[clippy] Fix clippy issues for crate sp-core

---

frame/scheduler/src/benchmarking.rs
frame/scheduler/src/lib.rs

Part of #7882.
Converts the `Scheduler` pallet to the new pallet attribute macro introduced in #6877.
⚠️ Breaking Change ⚠️
> From https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines
> 

Migrate pallet-scheduler to pallet attribute macro 

---

primitives/api/proc-macro/src/impl_runtime_apis.rs
primitives/version/proc-macro/src/decl_runtime_version.rs
primitives/version/src/lib.rs

A follow-up for #8688 
This PR limits emitting the runtime version sections only to when the runtime is compiled to wasm.

Emit wasm sections only when compiling to wasm

---

bin/node/cli/src/chain_spec.rs
frame/election-provider-multi-phase/Cargo.toml
frame/election-provider-multi-phase/src/lib.rs
frame/election-provider-multi-phase/src/unsigned.rs
primitives/runtime/src/offchain/storage_lock.rs

+ make sure we only recompute if
1. no solution was cached
2. the cached solution was not feasible. 
The most common scenario is that we have a cached solution, and it has a worse score. In this case, we do nothing from now on.

Ensure election offchain workers don't overlap

---

client/keystore/src/local.rs
primitives/core/src/ecdsa.rs
primitives/keystore/src/lib.rs
primitives/keystore/src/testing.rs

Addresses: [Allow hasher configuration before signing with app-crypto](https://github.com/paritytech/grandpa-bridge-gadget/issues/82)
- add `ecdsa::Pair::sign_prehashed()`
- add `CryptoStore::ecdsa_sign_prehashed()`
- impl for `LocalKeystore`
- tests

Add CryptoStore::ecdsa_sign_prehashed()

---

primitives/runtime/src/traits.rs

The macro should assume less about the scope where it is being used in.
In this case it is about not assuming that the crate where the macro is
called in provides a `std` feature.

Improve `impl_opaque_keys!`

---

frame/support/Cargo.toml
frame/support/procedural/src/pallet/expand/call.rs
frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr

By deriving codec on the Call enum without any bound, we can have better span for when some type doesn't implement codec. see the error message change.
Note that Call enum must implement codec in order to be usable by the runtime, thus implementing codec conditionally (as it is before this PR) shouldn't be of any use.

Improve pallet macro error message by deriving codec with no bound for `Call` enum

---

frame/transaction-payment/src/lib.rs
frame/transaction-payment/src/payment.rs

Fix https://github.com/paritytech/substrate/issues/8854
contrary to the doc, the on unbalanced handler is given the tip first and then the fee. This PR fix it, and test it.

Fix transaction payment fee/tip unbalanceds

---

.gitlab-ci.yml

add trigger for monitoring job in cloud-infra repository to apply substrate prometheus rules for all ci enabled projects.
https://github.com/paritytech/devops/issues/882

add trigger for monitoring job in cloud-infra repository

---

frame/contracts/src/wasm/env_def/macros.rs

Followup for #8780 . Fixes one bug that went unnoticed.
- The comparison was against the wrong `module` variable
- The comparison was needlessly duplicated

contracts: Fix `__unstable__` feature

---

frame/support/src/lib.rs
frame/support/src/storage/bounded_btree_map.rs
frame/support/src/storage/bounded_btree_set.rs
frame/support/src/storage/bounded_vec.rs
frame/support/src/storage/mod.rs
frame/support/src/storage/types/double_map.rs
frame/support/src/storage/types/map.rs
frame/support/src/storage/types/value.rs
frame/support/src/storage/weak_bounded_vec.rs
frame/treasury/src/lib.rs

Fix https://github.com/paritytech/substrate/issues/8839
This PR does:
* introduce `WeakBoundedVec`: it is exactly same as BoundedVec previous to this PR, i.e. the lenght is not enforced by `force_from` nor `decode`, but it warns when exceeded.
* improve `BoundedVec` API: `force_from` is removed and `decode` only accept vec with correct size.
* introduce `StorageTryAppend`: allow to specify that a storage value have a maximum bound. It is used to implement try_append on storage value, storage map and storage double map now.
Previous to this PR, try_append was only implemented for `BoundedVec` explicitly. The `StorageTryAppend` allow to implement `try_append` on various types, such as `BoundedVec` and `WeakBoundedVec`.

Introduce WeakBoundedVec, StorageTryAppend, and improve BoundedVec API

---

client/finality-grandpa-warp-sync/src/lib.rs
client/finality-grandpa-warp-sync/src/proof.rs
client/finality-grandpa/src/authorities.rs

https://github.com/paritytech/substrate/pull/7339 introduced a new client-side auxiliary mapping from `set_id -> block_number`, this mapping is used when generating warp sync proofs. Since this code was added recently, nodes that didn't sync from scratch don't have it fully populated, in which case we need to detect it and avoid generating a warp sync proof when we have missing data.

grandpa: fix warp sync proof on missing data

---

client/network/src/protocol/notifications/behaviour.rs

Right now, when node A has node B as reserved, node A will try *really hard* to open a substream to node B.
Even if node B refuses the substream, node A will almost immediately try again. This results in a spam of substream open attempts, which unnecessarily uses bandwidth and CPU.
If we have a lot of reserved nodes, for example because of the collation and validation substreams in Polkadot, and most of them refuse the substream, this spam can be considerable. They're not supposed to refuse the substream in normal situations, but with our recent revert to 0.8.30, they do in practice.
This PR adds a 10 seconds "ban" during which we don't try to re-open a substream after it has failed to open, even if the node is reserved.

Make sure nodes don't hammer each other even when reserved

---

bin/node/testing/src/client.rs
client/chain-spec/src/chain_spec.rs
client/chain-spec/src/lib.rs
client/service/src/builder.rs
client/service/src/client/call_executor.rs
client/service/src/client/client.rs
client/service/src/client/light.rs
client/service/src/client/mod.rs
client/service/src/client/wasm_substitutes.rs
client/service/test/src/client/mod.rs
test-utils/client/src/lib.rs
test-utils/runtime/client/src/lib.rs

This introduces a new field `code_substitute` into the chain spec. This
can be used to substitute the on-chain wasm starting from a given block
until there is another wasm on chain (determined through the
`spec_version`). This can be used to fix broken on chain wasm runtimes.
polkadot companion: https://github.com/paritytech/polkadot/pull/3093

Introduce `code_substitute`

---

Cargo.lock
utils/frame/remote-externalities/Cargo.toml
utils/frame/remote-externalities/src/lib.rs
utils/frame/try-runtime/cli/src/lib.rs

switches remote-externalities to use the safe rpcs via ws, instead of unsafe RPCs and http. 
cc @joao-paulo-parity 
polkadot companion: https://github.com/paritytech/polkadot/pull/3096

make remote-ext work with ws and safe RPCs

---

client/db/src/bench.rs
client/db/src/lib.rs
client/db/src/storage_cache.rs
client/light/src/backend.rs
client/service/src/client/call_executor.rs
client/service/test/src/client/mod.rs
primitives/state-machine/src/backend.rs
primitives/state-machine/src/ext.rs
primitives/state-machine/src/proving_backend.rs
primitives/state-machine/src/trie_backend.rs

I think this is solely cosmetic but I stumbled upon this impl and thought it is a bit misleading.
This removes a from my perspective unnecessary implementation
for `&T` which implements `Backend`.
The current implementation exists (again from my perspective) solely
to satisfy a methods `&mut self` parameters (i.e. allows to satisfy
this for an & reference via using `&mut &Backend`).
As all implementors use a `RefCell` with `borrow_mut()` where actually
calling the mentioned &mut self method and then forward to the
`{}` implementation of either `TrieBackend` or `ProvingBackend`, the
current &mut self seems to be not needed.
**NOTE:**
It might be possible to remove the `RefCell`s from the client/db section now.

Removes unnecessary blank impl for Backend

---

frame/contracts/CHANGELOG.md
frame/contracts/src/benchmarking/mod.rs
frame/contracts/src/exec.rs
frame/contracts/src/lib.rs
frame/contracts/src/rent.rs
frame/contracts/src/storage.rs
frame/contracts/src/tests.rs
frame/contracts/src/wasm/runtime.rs

- An error message was wrongly outputted on the node console when instantiating in some cases (using an endowment below the subsistence threshold)
- Break down `NotCallable` into more fine grained an useful error types
- Fixed returning the wrong code size when the initial transfer failed

contracts: Fix some minor bugs around instantiation

---

frame/support/src/origin.rs

This is a small fix to make clippy happy with the latest nightly.
An alternative is to just add an `#[allow(...)]`, but I like this better.

Convert Into to From to make clippy happy

---

frame/support/test/tests/derive_no_bound_ui/eq.stderr
primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
primitives/api/test/tests/ui/mock_only_self_reference.stderr
primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr

Reverts paritytech/substrate#8904
Had to roll back the previously updated latest nightly as `cargo-check-benches` was failing.

Revert "Fix stderr in new Rust nightly"

---

primitives/core/src/crypto.rs
ss58-registry.json

Add Manta Network (https://manta.network/) and Manta's canary network (Calamari)'s ss58 address prefix:
-  update `crypto.rs`
-  update `ss58-registry.json`

Manta Network ss58 address registration

---

bin/node/executor/benches/bench.rs
client/executor/src/wasm_runtime.rs
frame/merkle-mountain-range/src/lib.rs
frame/support/src/lib.rs
frame/utility/src/tests.rs
primitives/api/test/tests/decl_and_impl.rs
primitives/core/benches/bench.rs

This simply fixes some compiler warnings that arose from the latest rustc

Fix Compiler Warnings (new rustc)

---

.gitlab-ci.yml
.maintain/gitlab/trigger_pipeline.sh

Triggers the pinned `simnet` version on every master pipeline

CI: fix simnet trigger

---

client/api/src/execution_extensions.rs
client/service/src/config.rs

This PR simply reexports some of the code units that `sc_service::Configuration` depends on internally. As of now, it is not possible to construct the `sc_service::Configuration` using just the `sc-service` crate, but I wanted to do this and figured it would be convenient to apply some changes that I needed as a patch.
This PR does not change any fundamental rules about the code structure, it only adheres to existing ones and solves current issues with them, so I assume it won't be difficult to merge.

More sc-service config reexports

---

.maintain/gitlab/check_runtime.sh
frame/contracts/src/lib.rs

The `check-runtime` fails for all PRs. I suspect the reason to be that the `git diff` used in the script requires that a merge base between the two commits do exist and subsequently fails when it does not. I think what we really want to express is "difference between A and B".
Also applied a change to the `frame` directory in order to trigger the relevant code in the script.

Fix check runtime CI

---

frame/assets/src/lib.rs

Replaces https://github.com/paritytech/substrate/pull/8878 as minimum change for Statemint. Will handle function rename in https://github.com/paritytech/substrate/pull/8476
These events get emitted by the internal calls to `do_mint` and `do_burn`.

Remove duplicate `Issued`/`Burned` events in Assets pallet

---

frame/contracts/src/lib.rs
frame/contracts/src/schedule.rs

Fixes #8433
Initially, we thought we could avoid doing major version bumps left and right by making all fields of the `Schedule` private in #8359. However, it turns out that the public `WeightInfo` trait would mandate a major version bump when adding a new contract callable function. Getting around this would require some trickery and do more harm than good.
I came to the conclusion that we just accept the fact that we will have a new major version when adding new functionality and expect runtimes to bump the version and re-run benchmarks. Most of the time that will be everything that is to it.
cc @atenjin

Make `Schedule` fields public to allow for customization

---

frame/scored-pool/src/lib.rs
frame/scored-pool/src/mock.rs
frame/scored-pool/src/tests.rs

Part of #7882.
Converts the `ScoredPool` pallet to the new pallet attribute macro introduced in #6877.
So users of the `ScoredPool` pallet must be careful about the name they used in `construct_runtime!`. Hence the `runtime-migration` label, which might not be …

Migrate pallet-scored-pool to pallet attribute macro

---

client/network/src/block_request_handler.rs

I refactored the code a little bit inside client/network/src/block_request_handler.rs

Refactor BlockRequestHandler

---

primitives/state-machine/src/ext.rs
primitives/state-machine/src/overlayed_changes/changeset.rs
primitives/state-machine/src/overlayed_changes/mod.rs

- Do not rely on recursion
- Use an iterator over the overlay to not always call the same method
Fixes: https://github.com/paritytech/substrate/issues/8950

Optimize `next_storage_key`

---

primitives/runtime/src/transaction_validity.rs

needed for https://github.com/paritytech/polkadot/pull/3141/files
This type is used in our PRCs (dry_run), but was not `serde::deserialize` and thus could not be used.

Add deserialize for TransactionValidityError in std.

---

client/authority-discovery/src/worker.rs
client/basic-authorship/src/basic_authorship.rs
client/consensus/common/src/shared_data.rs
client/consensus/slots/src/lib.rs
client/network/src/config.rs
client/network/src/light_client_requests/sender.rs
client/network/src/service.rs
frame/contracts/rpc/src/lib.rs
primitives/npos-elections/compact/src/lib.rs

Fixes some of the cargo doc warnings. *No code changes*

Reduce cargo doc warnings

---

client/rpc-api/src/child_state/mod.rs
client/service/src/builder.rs
client/service/src/config.rs
client/telemetry/src/lib.rs
client/transaction-pool/graph/src/ready.rs
client/transaction-pool/graph/src/validated_pool.rs
client/transaction-pool/src/lib.rs
client/transaction-pool/src/testing/pool.rs
docs/CHANGELOG.md
docs/Upgrading-2.0-to-3.0.md

My spelling is poor so I roll with a spell checker and it picked up a few things.

Spellling corrections (no code changes)

---

frame/system/src/offchain.rs
utils/frame/remote-externalities/src/lib.rs

Needed for https://github.com/paritytech/polkadot/pull/3141/files
Allows adding custom hashed prefixes to the remote-ext. Helps us command it to download not the entire pallet, but certain maps from it.

Inject hashed prefix for remote-ext

---

client/executor/wasmtime/src/instance_wrapper.rs

Now that #8913 has landed we are able to use some new APIs. Particularly in this PR we leverage the `TypedFunc` type. It is the same as `Func` but with types checked once.
This PR is an optimization and does not carry any logic change.

Do not spend time on verifying the signatures before calling Runtime

---

frame/support/src/storage/weak_bounded_vec.rs

Makes `WeakBoundedVec::remove` and `WeakBoundedVec::swap_remove` return the removed element as in the original Vec implementation.

Update WeakBoundedVec's remove and swap_remove

---

frame/support/procedural/src/construct_runtime/expand/origin.rs
frame/support/src/origin.rs

An addition to #8900. There was another instance of an `Into` impl there.
UPD: found two more instances.
This time I checked the branch, and am sure the linter is happy.

Convert another instance of Into impl to From in the macros

---

frame/support/src/storage/bounded_vec.rs

See: https://github.com/paritytech/substrate/pull/8985/files

Also fix `BoundedVec` remove API

---

client/consensus/manual-seal/src/lib.rs
client/transaction-pool/src/lib.rs

`ready_at` returns when we have processed the requested block. However,
on startup we already have processed the best block and there
are no transactions in the pool on startup anyway. So, we can set `updated_at`
to the best block on startup.
Besides that `ready_at` now returns early when there are no ready nor
any future transactions in the pool.

Transactionpool: Make `ready_at` return earlier

---

client/network/src/protocol.rs

When the notifications network behaviour opens a substream, it includes a handshake. The outer layer then tries to decode that handshake. If it fails, the peer is asynchronously disconnected, but in the meanwhile it is added to a list of `bad_handshake_substreams` and all events related to this substream are silently discarded.
This PR fixes the fact that this wasn't taken into account for `Notifications` events.

Discard notifications if we have failed to parse handshake

---

primitives/core/src/ecdsa.rs

Add `ecdsa::Pair::verify_prehashed()` and test.

Add ecdsa::Pair::verify_prehashed()

---

frame/support/src/lib.rs
frame/support/src/storage/bounded_vec.rs
frame/support/src/traits/tokens.rs
frame/support/src/traits/tokens/nonfungible.rs
frame/support/src/traits/tokens/nonfungibles.rs
frame/uniques/src/functions.rs
frame/uniques/src/impl_nonfungibles.rs
frame/uniques/src/lib.rs
frame/uniques/src/types.rs
primitives/runtime/src/lib.rs

More for https://github.com/paritytech/substrate/issues/8453.
The corresponding traits for non-fungible tokens and their implementations for Uniques pallet.

Non-fungible token traits

---

Cargo.lock
bin/node/runtime/Cargo.toml
bin/node/runtime/src/lib.rs
frame/babe/src/mock.rs
frame/election-provider-multi-phase/src/lib.rs
frame/grandpa/src/mock.rs
frame/offences/benchmarking/src/mock.rs
frame/session/Cargo.toml
frame/session/benchmarking/src/mock.rs
frame/session/src/historical/mod.rs
frame/session/src/lib.rs
frame/staking/src/benchmarking.rs
frame/staking/src/lib.rs
frame/staking/src/mock.rs

Should go on top of https://github.com/paritytech/substrate/pull/8912

genesis election provider

---

client/finality-grandpa/src/import.rs

Could've saved some debugging time.

afg: more useful error message

---

bin/node/runtime/src/lib.rs
frame/system/src/lib.rs

Since we've run out of ss58 the prefix size was increased to u16 but Substrate didn't account for this yet. This PR should address this. I have a couple of questions regarding this:
1. Do I need to increase spec_version of Substrate (Polkadot,Westend...)? The type changed from u8 to u16 it's stored as a constant, is that something that is actually stored in the genesis or is it provided by the node / runtime itself? If it's stored in genesis do we need to do a migration?
2. Do we need companion to Polkadot?
3. Do we change all the types in tests? (u8 fits into u16 but it might be nicer to have it synced?)

update ss58 type to u16

---

Cargo.lock
bin/node/bench/Cargo.toml
client/db/Cargo.toml

Bump `parity-db` to `v0.2.4` so that downstream projects can use `clippy` again.

Bump parity-db

---

primitives/arithmetic/src/per_things.rs

https://en.m.wikipedia.org/wiki/Exponentiation_by_squaring#Basic_method

arithmetic: fix PerThing pow

---

frame/staking/src/lib.rs

This can only happen if all the targets get filtered due to slashing events.

Don't include nominators that back no one in the snapshot.

---

client/peerset/src/lib.rs

The `alloc_slots` function attributes nodes to sets. It is currently called whenever a substream is closed, a node is added to a set, or a node switches between reserved and non-reserved.
`alloc_slots` will ignore nodes whose reputation is too low, as these nodes are "banned".
Reputations go towards 0 over time, meaning that banned peers will at some point in time become unbanned.
The problem is that the peerset completely ignores that situation.
If a peer is banned, and then its reputation goes above the ban threshold again, it will never be attributed a slot ever again, unless another node disconnects, or a node is added to the set or switches between reserved and non-reserved.
We have most likely never noticed it, because on sync/transactions and grandpa it happens extremely frequently …

Periodically call `Peerset::alloc_slots` on all sets

---

client/service/src/metrics.rs

(We send network information to prometheus)
(At some later point we can remove the network_state reciever from telemetry backend.)
Fixes: #8999 
(Not sure if it's noteworthy or not as we say that we don't support this call. The rpc call is still available and have confirmed still works.)

Stop sending network_state to telemetry

---

.gitlab-ci.yml
.maintain/gitlab/trigger_pipeline.sh

This PR updates simnet tests to v5 version.
After discussion with @TriplEight  I edited this PR to update to simnet v5.
trigger_pipeline.sh was copied  from  https://github.com/paritytech/polkadot/blob/master/scripts/gitlab/trigger_pipeline.sh
and adapted.
We reviewed together https://github.com/paritytech/polkadot/blob/master/scripts/gitlab/trigger_pipeline.sh
last week 
Pipeline is green.
https://gitlab.parity.io/parity/substrate/-/pipelines/141040

READY Update simnet tests to v5

---

client/finality-grandpa/src/import.rs

BEEFY is already producing justifications but we don't have any infrastructure in-place to properly validate them yet. As it stands, on networks with BEEFY enabled (e.g. rococo) the sync code might get a block with multiple justifications (i.e. one for GRANDPA and one for BEEFY) and the import queue will pass along the BEEFY justification to `GrandpaBlockImport`.

grandpa: ignore justifications from other consensus engines

---

client/peerset/src/lib.rs

This PR is an alternative to https://github.com/paritytech/substrate/pull/9003. We should either merge this one or https://github.com/paritytech/substrate/pull/9003, but not both.
This PR changes `alloc_slots` to not open substreams with reserved nodes if they are banned.
Since reputations apply globally, this would mean that for example the sync code can ban a node due to an anomaly, and it would close the collation and validation substreams as well.
It also makes sure that `alloc_slots` is immediately called if a node gets disconnected because it is banned, which we didn't do before. This change is also in https://github.com/paritytech/substrate/pull/9003

Don't connect to reserved nodes if they're banned

---

frame/support/test/Cargo.toml
frame/support/test/tests/derive_no_bound_ui/eq.stderr
primitives/api/proc-macro/Cargo.toml
primitives/api/test/Cargo.toml
primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
primitives/api/test/tests/ui/mock_only_self_reference.stderr
primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr
primitives/npos-elections/compact/Cargo.toml
primitives/runtime-interface/Cargo.toml
test-utils/Cargo.toml

polkadot companion: https://github.com/paritytech/polkadot/pull/3208

Try fix ui tests

---

Cargo.lock
bin/node-template/node/src/service.rs
bin/node/cli/src/service.rs
client/transaction-pool/Cargo.toml
client/transaction-pool/src/api.rs
client/transaction-pool/src/lib.rs
client/transaction-pool/src/testing/pool.rs
test-utils/test-runner/src/node.rs

This pr removes `futures-diagnose` as this isn't used anymore. Besides
that the pr also removes the thread pool that was used to validate the
transactions in the background. Instead of this thread pool we now spawn
two separate long running tasks that we use to validate the
transactions. All tasks of the transaction pool are now also spawned as
essential tasks. This means, if any of these tasks is stopping, the node
will stop as well.
polkadot companion: https://github.com/paritytech/polkadot/pull/3204

Transaction pool: Remove futures-diagnose and thread pool

---

Cargo.lock
primitives/core/Cargo.toml
primitives/keystore/Cargo.toml
primitives/keystore/src/vrf.rs

Doesn't seem to be used in polkadot or in substrate. FYI this is a semver-breaking change.
Closes #9072.

disable unused schnorrkel feature

---

frame/babe/src/lib.rs
frame/babe/src/tests.rs
frame/im-online/src/lib.rs
frame/im-online/src/mock.rs
frame/im-online/src/tests.rs
frame/session/src/lib.rs
frame/session/src/tests.rs
frame/support/src/traits/validation.rs

Currently after the session is halfway through the offchain worker will send a heartbeat to notify the validator as being online. This is currently deterministic and makes it so that at the mid-session block all validators push a tx causing a temporary spike. This PR changes the im-online logic so that there's some randomization regarding the block at which the heartbeat will be sent.

im-online: send heartbeats at a random period

---

primitives/core/src/crypto.rs
ss58-registry.json

This adds the Moonbeam (1284) and Moonriver (1285) SS58 prefix,
It will be used to generate the session keys, as the main account format is ECDSA(Keccak256) which is not supported by default on substrate.
(As a follow-up we might add ECDSA/Keccak256 support)

Adds moonbeam, moonriver to ss58 registry

---

client/executor/common/src/runtime_blob/runtime_blob.rs

This PR adds a small helper function that enables testing whether a specific function name is exported in the RuntimeBlob. Since the raw_module is private, it is not possible to test whether a specific blob exports a function.
This is particularly useful when validating PVF WASM blobs which are assumed to export the "validate-block" function.

Add function to test whether function is exported in wasm blob

---

frame/proxy/src/lib.rs

export `pallet_proxy::find_prox` and `ProxyDefinition`.

Make find_proxy public.

---

frame/support/procedural/src/lib.rs

- Mention when the pallet definition parts are needed
- Rename "module" to "pallet"

Improve construct_runtime doc

---

frame/staking/src/lib.rs

Improve variable name

---

frame/support/procedural/src/construct_runtime/mod.rs

Instead of executing integrity_test for all pallet but system pallet we execute for pallet and system pallet.
one test environment wasn't correctly set in polkadot, so there is a need for this companion: https://github.com/paritytech/polkadot/pull/3240

Execute system integrity_test

---

utils/wasm-builder/src/prerequisites.rs

Fixes #9113
See #9113 for details on what issue this PR attempts to solve.
This is my first PR on this project :sweat_smile: so any reviews pointing out anything I may have got wrong would be greatly appreciated.

fix: CARGO_TARGET_DIR_freeze

---

frame/support/test/tests/pallet_ui.rs
frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.rs
frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr

Fix https://github.com/paritytech/substrate/issues/9120
CI run test for frame-support-test with the feature conditional-storage and without.
For UI test this is not necessary, also we can't feature-gate the output of the UI test.
This PR prevent running UI test when conditional-compilation feature is activated.

Do not run pallet_ui test with conditional-storage feature

---

Cargo.lock
Cargo.toml
client/finality-grandpa-warp-sync/Cargo.toml
client/finality-grandpa-warp-sync/src/lib.rs
client/finality-grandpa/Cargo.toml
client/finality-grandpa/rpc/Cargo.toml
client/finality-grandpa/src/communication/mod.rs
client/finality-grandpa/src/environment.rs
client/finality-grandpa/src/finality_proof.rs
client/finality-grandpa/src/import.rs
client/finality-grandpa/src/lib.rs
client/finality-grandpa/src/observer.rs
client/finality-grandpa/src/tests.rs
client/finality-grandpa/src/until_imported.rs
client/finality-grandpa/src/voting_rule.rs
frame/grandpa/Cargo.toml
primitives/finality-grandpa/Cargo.toml

Upgrade to finality-grandpa 0.14.1 and remove sync bounds that don't play well with async/await code.
polkadot companion: https://github.com/paritytech/polkadot/pull/3266

grandpa: cleanup sync bounds

---

frame/elections/src/lib.rs
frame/elections/src/mock.rs

Part of #7882.
Converts the `Elections` pallet to the new pallet attribute macro introduced in #6877.
So users of the `Elections` pallet must be careful about the name they used in `construct_runtime!`. Hence the `runtime-migration` label, which might not be …

Migrate pallet-elections to pallet attribute macro

---

frame/staking/src/lib.rs
frame/staking/src/mock.rs
frame/staking/src/testing_utils.rs
frame/staking/src/tests.rs

This PR simply updates the names for the new Validator and Nominator counter storage items so they will be backwards compatible with the `CountedMap` we will migrate these storage to.
https://github.com/paritytech/substrate/pull/9125/files

Make New Staking Counter Backwards Compatible with CountedMap

---

.gitlab-ci.yml
frame/support/test/Cargo.toml
frame/support/test/tests/pallet_ui.rs

This PR makes CI execute only the pallet test with conditional-storage.
In case some other test takes some times this is more efficient. Otherwise we can simply ignore all UI test and execute all other test 2 times.

Avoid running some test 2 times when unneeded

---

client/consensus/aura/src/import_queue.rs
client/consensus/aura/src/lib.rs
primitives/consensus/aura/src/lib.rs

This instructs the Aura runtime api to skip initialize block, when
requesting the authorities. This is important, as we don't want to use
the new authorities that should be used from the next block on.
Besides that, it removes the caching stuff. The cache is not available
on full nodes anyway. In the future we should store the authorities
probably in the aux store.

Aura: Skip initialize block & remove cache

---

primitives/allocator/src/freeing_bump.rs

This is a burn-in request for a potential patch to the current, rather inefficient, staking system. 
Of the first bottlenecks that we might hit is reaching the 16MiB allocator limit when we dump all nominators into a single vector (see [here](https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L2692)). This PRs examines how the system will work if we double this limit to buy us more time. 
I've had a discussion with @pepyakin and he noted that there are some potential performance penalties in this. We are basically adding a 21's bucket to the allocator. There are two potential caveats to this: 
1. @pepyakin explained it best: 
> That means the following. Assume you allocate 16 MiB chunks up to the heap <s>element</s> limit. Then you deallocate them all at once so …

double the allocator limit

---

client/finality-grandpa/src/communication/gossip.rs
client/finality-grandpa/src/environment.rs
client/network-gossip/src/state_machine.rs

This PR updates the GRANDPA gossip validator to make it more restrictive. Currently there is a lot of duplicate messages being exchanged. Additionally this should also make gossip more fair as we were heavily favoring gossiping to authorities to the point that full nodes cannot keep up with the latest rounds (they were mostly keeping up with finality through commits and catch-up requests).
We already deployed this on all of the rococo validators and the traffic went down by about 3x without introducing any delay in finality.

grandpa: restrict grandpa gossip

---

bin/node-template/node/src/service.rs
bin/node/cli/src/service.rs
client/consensus/aura/src/lib.rs
client/consensus/babe/src/lib.rs
client/consensus/babe/src/tests.rs
client/consensus/slots/src/lib.rs

The slot lenience calculation was being done on the original slot duration without accounting for the block proposal portion. This PR fixes that and additionally adds a `max_block_proposal_slot_portion` so that the block proposal duration is never exceeded regardless of the slot lenience. 
polkadot companion: https://github.com/paritytech/polkadot/pull/3294

slots: slot lenience must take into account block proposal portion

---

Cargo.lock
client/consensus/babe/rpc/src/lib.rs
client/consensus/babe/src/lib.rs
client/consensus/common/Cargo.toml
client/consensus/common/src/longest_chain.rs
client/consensus/manual-seal/src/seal_block.rs
client/consensus/pow/src/lib.rs
client/consensus/slots/src/slots.rs
client/finality-grandpa/src/environment.rs
client/finality-grandpa/src/import.rs
client/network/test/src/lib.rs
client/service/src/lib.rs
client/service/test/src/client/mod.rs
primitives/api/test/Cargo.toml
primitives/api/test/tests/runtime_calls.rs
primitives/consensus/common/src/block_import.rs
primitives/consensus/common/src/import_queue/basic_queue.rs
primitives/consensus/common/src/select_chain.rs

This will be required for Polkadot as we'll need a custom `SelectChain` that queries some subsystems (asynchronously). Also made `JustificationImport` async in the process.
polkadot companion: https://github.com/paritytech/polkadot/pull/3268

make SelectChain async

---

frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr
frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr
frame/support/test/tests/pallet_ui/event_field_not_member.stderr
frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
max-encoded-len/tests/max_encoded_len_ui/union.stderr
primitives/api/test/tests/ui/impl_incorrect_method_signature.stderr
primitives/api/test/tests/ui/mock_only_self_reference.stderr
primitives/api/test/tests/ui/type_reference_in_impl_runtime_apis_call.stderr

Right now these are failing on `master`: https://gitlab.parity.io/parity/substrate/-/jobs/977367

fix some failing ui tests

---

utils/frame/try-runtime/cli/src/lib.rs

Simplifies access patterns. Merge target: https://github.com/paritytech/substrate/pull/9077.

add helper for block_at

---

primitives/allocator/src/freeing_bump.rs

Addresses https://github.com/paritytech/substrate/pull/9102/files#r655901183

Fix allocator waste assessment in docs

---

.maintain/monitoring/alerting-rules/alerting-rules.yaml

This task is obviously not continuous, so it's not worth alerting about.
Normally the alert rule is loose enough that this kind of task doesn't trigger the alert, but we apparently have some validators that trigger it, most likely because of a script querying information from the node.

Add `substrate-rpc-subscription` to exceptions in alert

---

client/finality-grandpa/src/authorities.rs
client/finality-grandpa/src/import.rs
client/finality-grandpa/src/lib.rs

Broken in https://github.com/paritytech/substrate/pull/8143.

grandpa: fix broken line breaks in logging

---

bin/node-template/runtime/src/lib.rs

This type is an artifact of the past, and is not used in the node template anymore.

Remove Unused `AccountIndex`

---

frame/election-provider-multi-phase/src/unsigned.rs
frame/example-offchain-worker/src/lib.rs
frame/im-online/src/lib.rs
frame/session/src/historical/offchain.rs
primitives/runtime/src/offchain/storage.rs
primitives/runtime/src/offchain/storage_lock.rs
primitives/trie/Cargo.toml

Meme driven development: You are using a three state enum rather than Option<Option<>> right? right???
Edit: No, we're going to use Result<Option<>>

Result<Option<>> rather than Option<Option<>>

---

client/network/src/protocol/sync.rs
client/network/src/state_request_handler.rs
client/peerset/src/lib.rs
client/peerset/tests/fuzz.rs
primitives/arithmetic/src/fixed_point.rs
primitives/arithmetic/src/lib.rs
primitives/runtime-interface/test-wasm/src/lib.rs

Companion PR to https://github.com/paritytech/substrate/pull/9189
min_value() is deprecared.

Use MIN associated const

---

Cargo.lock
client/rpc-servers/Cargo.toml
client/rpc-servers/src/lib.rs
client/service/src/builder.rs
client/service/src/lib.rs

Add functionality for stopping the servers, note the `WsServer` won't terminate the current background task for the connection which we should fix in jsonrpsee but this more or less follows the previous design except that initializing is done inside of async methods.

add functionality to stop the jsonrpc servers

---

frame/balances/README.md

I updated the balance reference link according to updating 3.0.0.

change balance pallet reference link

---

frame/support/procedural/src/storage/storage_struct.rs
frame/support/src/hash.rs
frame/support/src/lib.rs
frame/support/src/storage/bounded_btree_map.rs
frame/support/src/storage/bounded_btree_set.rs
frame/support/src/storage/bounded_vec.rs
frame/support/src/storage/types/double_map.rs
frame/support/src/storage/types/key.rs
frame/support/src/storage/types/map.rs
frame/support/src/storage/types/nmap.rs
frame/support/src/storage/types/value.rs
frame/support/src/storage/weak_bounded_vec.rs
frame/support/src/traits.rs
frame/support/src/traits/tokens/currency.rs
frame/system/src/lib.rs

Built on top of https://github.com/paritytech/substrate/pull/9163
this remove the reexport of MaxEncodedLen in frame_support::traits

Reorganize max encoded len import

---

frame/election-provider-multi-phase/src/lib.rs

This should prevent extrinsic indexing reordering issues, which were introduced accidentally during a merge.
Adopts the polkadot companion which used to belong to #7910.
polkadot companion: paritytech/polkadot#2793

move set_emergency_election_result before submit

---

frame/transaction-payment/src/lib.rs

This PR adds a public accessor function to the `ChargeTransactionPayment` struct. This is useful in chains using https://github.com/paritytech/frontier/ to be able to properly prioritize "normal" FRAME transactions alongside ethereum transactions.

Add public accessor for tip amount

---

client/consensus/manual-seal/src/lib.rs
client/consensus/manual-seal/src/seal_block.rs
client/service/src/config.rs
client/service/src/lib.rs
client/transaction-pool/src/lib.rs
client/transaction-pool/src/testing/pool.rs

Remove `txpool` as an export of `sc_transaction_pool`, exporting the used components instead.

---

frame/election-provider-multi-phase/src/lib.rs
frame/system/src/lib.rs

small tweaks needed for https://github.com/paritytech/polkadot/pull/3141/files

Make a few things for staking miner

---

client/cli/src/lib.rs

Since it's already there, why not give it a chance :P
Before:
After:

Enable colored help in CLI

---

frame/election-provider-multi-phase/src/lib.rs
frame/election-provider-multi-phase/src/signed.rs

another one like https://github.com/paritytech/substrate/pull/9241

Display Reward amount

---

frame/support/src/storage/generator/double_map.rs
frame/support/src/storage/generator/map.rs
frame/support/src/storage/generator/nmap.rs
frame/support/src/storage/mod.rs
frame/support/src/storage/types/double_map.rs
frame/support/src/storage/types/map.rs
frame/support/src/storage/types/nmap.rs

Implement `iter_keys` function for all types of storage maps

---

simnet_tests/README.md
simnet_tests/configs/default_local_testnet.toml
simnet_tests/configs/local_testnet_with_logs.toml
simnet_tests/run_tests.sh
simnet_tests/tests/long/002-loadtest.feature
simnet_tests/tests/quick/001-smoketest.feature

This PR adds directory which will hold high level integration tests that will run with the simnet set of tools.
At the moment those kind of tests are maintained by the simnet team in simnet repo which is hosted just on gitlab.
This was done in this manner while we developed working version of tools to spawn a simulation network based on a docker image and run tests against this network.
There will be a follow up PR to edit the Ci file of this project, but I need those files hosted in this repo before.
We are still developing simnet and we are thinking how to make it simpler to use.
By moving simnet tests into this repository, the expectations are that developers would be able to maintain and create new tests.
Off course simnet team will help explaining how things work and how to use …

add simnet tests

---

utils/prometheus/src/lib.rs

A prometheus "server" typically refers to the prometheus process running
on a central server which connects to various prometheus "exporters" and
collects metrics. What is implemented here in substrate is a prometheus
exporter.
This patch fixes the associated log message to avoid confusion for new
users.
Thank you!
✄ …

fix prometheus log message terminology

---

frame/offences/benchmarking/src/lib.rs
frame/staking/src/lib.rs

closes #9242
This PR adds a `Chilled(stash_account)` event to `chill_stash` which is the underlying call used by the `chill` and `chill_other` extrinsic.

Add `Chilled` event to staking chill extrinsics

---

client/transaction-pool/graph/src/base_pool.rs

Less duplication makes it clear what's important in each test.

Less duplication in test code

---

Cargo.lock
frame/benchmarking/Cargo.toml

https://rustsec.org/advisories/RUSTSEC-2021-0070
Here is the `cargo deny` failure:
```
= Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0070
= The `Deserialize` implementation for `VecStorage` did not maintain the invariant that the number of elements must equal `nrows * ncols`. Deserialization of specially crafted inputs could allow memory access beyond allocation of the vector.
This flaw was introduced in v0.11.0 ([`086e6e`](https://github.com/dimforge/nalgebra/commit/086e6e719f53fecba6dadad2e953a487976387f5)) due to the addition of an automatically derived implementation of `Deserialize` for `MatrixVec`. `MatrixVec` was later renamed to `VecStorage` in v0.16.13 ([`0f66403`](https://github.com/dimforge/nalgebra/commit/0f66403cbbe9eeac15cedd8a906c0d6a3d8841f2)) and continued to …
```

Bump linregress due to security vulnerability

---

Cargo.lock
bin/node/bench/Cargo.toml
bin/node/browser-testing/Cargo.toml
bin/node/browser-testing/src/lib.rs
bin/node/cli/src/browser.rs
client/api/Cargo.toml
client/db/Cargo.toml
client/informant/Cargo.toml
client/service/Cargo.toml
client/state-db/Cargo.toml
client/transaction-pool/Cargo.toml
client/transaction-pool/graph/Cargo.toml
frame/support/Cargo.toml
max-encoded-len/Cargo.toml
primitives/arithmetic/Cargo.toml
primitives/arithmetic/fuzzer/Cargo.toml
primitives/core/Cargo.toml
primitives/database/Cargo.toml
primitives/runtime-interface/Cargo.toml
primitives/runtime/Cargo.toml
primitives/state-machine/Cargo.toml
primitives/test-primitives/Cargo.toml
primitives/trie/Cargo.toml
test-utils/runtime/Cargo.toml
utils/browser/Cargo.toml
utils/browser/src/lib.rs

I'm not sure if db in utils/browser is needed at all, but did a minimal change. `kvdb-web` is decommissioned now.
polkadot companion: https://github.com/paritytech/polkadot/pull/3402

bump a bunch of deps in parity-common

---

frame/support/procedural/src/storage/storage_info.rs
frame/support/test/tests/decl_storage.rs

`decl_storage` still doesn't generate storage info (in case of partial storage info).
I missed to remove the early return in the macro in https://github.com/paritytech/substrate/pull/9246
This fix it and test it is correct.

Fix storage info for decl_storage

---

frame/staking/src/lib.rs

When bumping the staking pallet storage from v6 to v7, the genesis version didn't get changed.
This fixes that. New runtimes using the pallet for the first time will have the latest storage version, which is v7.0.0

Fix Staking Version in Genesis

---

client/state-db/src/noncanonical.rs

This removes an assertion that pending state can't be pinned. There's a race that allows for such states to be accessed indeed. Since in-memory changes to state-db are applied after the blockchain metadata changes. Pinning such states is a no-op anyway, since all pins are short-lived and by the time metadata changes are applied it is guaranteed that the state won't be reverted.
See https://github.com/paritytech/polkadot/issues/3414 for context.

Remove incorrect debug assertion in state-db

---

frame/election-provider-multi-phase/src/lib.rs

This PR fixes the issue on #9204 
As @kianenigma said the score and compute parameters are byes of the transaction.
So as suggested I altered the function to only receive the supports, hardcoded the score and made a new Emergency compute variant.

Removed score and compute from set_emergency_election_result

---

Cargo.lock
client/executor/Cargo.toml
client/executor/src/wasm_runtime.rs
primitives/version/Cargo.toml
primitives/version/src/embed.rs
primitives/version/src/lib.rs

This function can be used to add the custom section to a wasm blob with
the runtime version in it.

Add function for embedding the runtime version in a wasm blob

---

shell.nix

Fix some deprecated stuff and update rust toolchain.

build: fix nix shell

---

frame/assets/README.md
frame/assets/src/lib.rs
frame/aura/README.md
frame/system/README.md

I changed the rust docs reference according to the latest update.
Please confirm.
Thank you.

change reference module to pallet

---

client/transaction-pool/README.md
client/transaction-pool/graph/src/ready.rs
client/transaction-pool/graph/src/watcher.rs
primitives/transaction-storage-proof/README.md
primitives/transaction-storage-proof/src/lib.rs

Made it a bit clearer that tags are exclusive + fixed a few typos.

Docs only changes

---

primitives/core/src/crypto.rs
ss58-registry.json

Hi, This is registration for SS58.
prefix 110 for Heiko network.
prefix 172 for Parallel network.

Add heiko, parallel to ss58 registry

---

frame/staking/src/lib.rs

reported by an external user, don't recall their name but kudos to them for pointing out. 
I also got rid of some of the superfluous weight comments. With https://github.com/paritytech/substrate/pull/9090 we can remove almost all of them, actually.

clean up staking docs, remove EraElectionStatus references

---

Cargo.lock
client/allocator/Cargo.toml
client/allocator/src/error.rs
client/allocator/src/freeing_bump.rs
client/executor/runtime-test/Cargo.toml

Closes: https://github.com/paritytech/substrate/issues/9292

Clean up sc-allocator

---

frame/babe/src/lib.rs
frame/babe/src/tests.rs

Instead of killing it at the end of the block, it stays in the block for
inspection. This is required by parachains to get access to this
randomness of the relay chain.
Required for: https://github.com/paritytech/cumulus/issues/463

Keep current block randomness in state

---

frame/collective/src/lib.rs
frame/membership/src/lib.rs

closes #9268
This PR adds a check in the genesis build of pallet-membership and pallet-collective for duplicate members.

Check for duplicate members in genesis of pallet-membership & pallet-collective 

---

client/consensus/slots/src/lib.rs

Currently, the inherent data provider only supports up to 4 entries due to the limit of
`InherentDataProviderExt`. This patch simply implements `InherentDataProviderExt` for more tuples as a chain can certainly have more than 4 inherent data providers.

Impl InherentDataProviderExt for more tuples

---

client/db/src/lib.rs
client/db/src/storage_cache.rs

Closes #9312
This only helps when most requests are cache misses. I.e. when requesting historical data.
Cache hits still require `write` access to a shared lock to update the LRU map. See #9320

Reduce shared state cache contention

---

frame/contracts/src/benchmarking/code.rs

For some reason I confused the `count` field with an initializer.

contracts: Fix benchmarks generating too many locals

---

client/db/src/lib.rs

Produce proper error when trying to canonicalize block with missing parents.
See https://github.com/PureStake/moonbeam/issues/541

Replace DB assertion with error

---

ss58-registry.json

Changes the `ss58-registry.json` so that moonbeam networks use secp256k1
closes https://github.com/paritytech/substrate/issues/9318

change moonbeam to secp256k1

---

frame/assets/src/impl_stored_map.rs
frame/assets/src/lib.rs
frame/balances/src/lib.rs
frame/support/src/traits/misc.rs
frame/support/src/traits/stored_map.rs
frame/system/src/lib.rs
frame/system/src/tests.rs
primitives/runtime/src/lib.rs
primitives/runtime/src/traits.rs

All of them are a subset of `DispatchError` anyway, no need to have
special errors IMHO.
Fixes: https://github.com/paritytech/substrate/issues/8709

Remove `IncRefError`, `DecRefError` and `StoredMapError`

---

frame/executive/src/lib.rs

Following  #9394, I pulled down master and ran `cargo +nightly fmt`, resulting in these changes. 
Additionally, when I run `cargo +nightly fmt` on my open PRs I get this same change. I am not certain whether these changes are somehow specific to my build env, but if they are not I think they should be merged in.

Run cargo +nightly fmt

---

bin/node/runtime/voter-bags/src/main.rs
frame/election-provider-multi-phase/src/lib.rs
frame/election-provider-multi-phase/src/mock.rs
frame/staking/src/lib.rs
frame/staking/src/tests.rs
frame/staking/src/voter_bags.rs
primitives/arithmetic/src/traits.rs
primitives/npos-elections/src/lib.rs

Target PR: `prgn-nominator-unsorted-bags`
@emostov please have a look and merge if satisfactory.

Glue the new staking bags to the election snapshot

---

frame/support/procedural/src/lib.rs

Reading the docs just above think these types might want to be the other way around?

example typo

---

client/cli/src/commands/run_cmd.rs

The 'data source' term does not represent a Prometheus concept. What we are exposing here is an exporter.
This is simliar to #9256

Clarify Prometheus exporter options

---

client/network/src/request_responses.rs
frame/proxy/src/lib.rs
frame/staking/src/lib.rs

I didn't find any functions which really needs a PostInfo.
also autoformatting two unrelated files
fixes #9421

Don't return misleading result with PostInfo in proxy-pallet

---

shell.nix

We want things to be as easy as possible for people to get started hacking at substrate. 
If we include `rust-src` then once people `clone` and run `nix-shell`, rust analyzer and intellirust will just work from that shell.

nix: IDEs like rust-src

---

Cargo.lock
frame/support/test/Cargo.toml
frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
primitives/api/test/Cargo.toml
primitives/npos-elections/compact/Cargo.toml
primitives/runtime-interface/Cargo.toml
test-utils/Cargo.toml

The old `trybuild` version didn't normalized cargo registry paths, but
this is now done :)

Update trybuild to get better normalization

---

frame/identity/src/types.rs

Derivation of Encode/Decode for codec encodes the variant into a u8. But here the variant discriminant is u64.
Also the type doesn't needs to implement Encode/Decode.
The PR simply removes the implementation

Remove invalid and unneeded codec implementation.

---

client/api/src/call_executor.rs
client/light/src/call_executor.rs
client/light/src/fetcher.rs
client/light/src/lib.rs
client/service/src/client/call_executor.rs
client/service/src/client/client.rs
client/service/test/src/client/light.rs
primitives/state-machine/src/ext.rs
primitives/state-machine/src/lib.rs

The logging before wasn't that uniform and not that great to read/parse.
Now we are using a uniform format for all the logs. Besides these
changes, there are some minor changes around the code that calls the
state machine.

Improve `state` related logs to use a more uniform format

---

frame/contracts/src/exec.rs
frame/offences/benchmarking/src/lib.rs
frame/staking/src/pallet/impls.rs
frame/staking/src/pallet/mod.rs
frame/staking/src/slashing.rs
frame/staking/src/tests.rs
frame/utility/src/lib.rs

Allow events from batched items to be separated. Also ensure the validator stash and era index from which the rewards are derived is always recorded. Also rename the events which do not respect the past-participle naming convention.

Add some important events to batch & staking to ensure ease of analysis

---

.gitlab-ci.yml

- stop publishing to crates.io until unleash is fixed
- allow k8s runners auto-restart on system failures.
CC: https://github.com/paritytech/cargo-unleash/issues/50 https://github.com/paritytech/substrate/pull/9373
@s3krit just FYI about releasing to crates.io

CI: stop publishing to crates.io until unleash is fixed

---

README.md

This is a fun addition for connecting users to our dedicated Substrate chat & to visualize the number of members there.
```
[![Matrix](https://img.shields.io/matrix/substrate-technical:matrix.org)](https://matrix.to/#/#substrate-technical:matrix.org)
```
https://img.shields.io/matrix/substrate-technical:matrix.org can be viewed directly to see the count before merging the PR here.

Add a matrix chat badge to the README

---

bin/node-template/runtime/src/lib.rs
bin/node/runtime/src/lib.rs
frame/aura/src/lib.rs
frame/aura/src/mock.rs
frame/aura/src/tests.rs
frame/babe/src/lib.rs
frame/babe/src/mock.rs
frame/babe/src/tests.rs
frame/session/src/lib.rs
frame/support/src/traits.rs
frame/support/src/traits/validation.rs
test-utils/runtime/src/lib.rs

Partial fix for #8004.
As part of module initialization we check whether the given validator has been disabled and if so we panic to make sure it is not able to author blocks. The reason that this is implemented in the runtime and not on the client-side is because implementing this on the client-side would require us to be fork-aware (one validator might have been disabled on a given fork but not another one).
polkadot companion: https://github.com/paritytech/polkadot/pull/3524

aura, babe: don't allow disabled validators to build blocks

---

client/consensus/aura/src/import_queue.rs
client/consensus/babe/src/lib.rs
client/consensus/pow/src/lib.rs
client/service/src/client/client.rs
primitives/consensus/common/Cargo.toml
primitives/consensus/common/src/lib.rs

Before we used the `other` context, while we are actually either in the
import or sync context.

Use correct `ExecutionContext` for `check_inherents`

---

primitives/runtime/src/generic/header.rs

currenctly codec is manually implemented, but the derive macro implement it just fine.
This PR add a regression test which test that the encoding has not changed. the test has been executed before and after the codec change.

Refactor codec implementation for header

---

frame/support/procedural/tools/Cargo.toml

This doesn't compile on its own as it needs `Debug` and that's
in the extra-traits syn feature.

crate missing dependency when compiled on its own with std

---

frame/babe/src/benchmarking.rs
frame/benchmarking/src/lib.rs
frame/benchmarking/src/tests.rs
frame/benchmarking/src/tests_instance.rs
frame/grandpa/src/benchmarking.rs

The macros `frame_benchmarking::benchmark`, `frame_benchmarking::benchmark_instance`, `frame_benchmarking::benchmark_instance_pallet`, now generate the test function as method on the Pallet struct instead of a regular function.
So to write test instead of writing benchmark test like:
```rust
#[test]
fn test_benchmarks() {
new_test_ext().execute_with(|| {
assert_ok!(test_benchmark_dummy::<Test>());
}
}
```
you must write:
```rust
#[test]
fn test_benchmarks() {
new_test_ext().execute_with(|| {
assert_ok!(Pallet::<Test>::test_benchmark_dummy());
}
}
```
But best is to use the test macro `impl_benchmark_test_suite`.
Currently the benchmark macro doesn't fully support where clause for pallet with instances.
This should fix it.
You can read the first commit to see a minimal diff, the second …

Fix benchmarking macro for pallet with instance and where clause

---

.maintain/gitlab/check_polkadot_companion_build.sh

To catch problems like #9485 breaking build w/o requiring a companion.

companion_build: enable runtime-benchmarks feature

---

client/rpc-api/src/lib.rs

So that the third party can reuse it in their own RPCs.

Expose UnsafeRpcError

---

bin/node/test-runner-example/src/lib.rs
test-utils/test-runner/src/node.rs

polkadot companion: paritytech/polkadot#3589
- Support test-runner to submit unsigned_extrinsic.
- Add `pool` to return a reference to the pool.

Support test-runner to submit unsigned_extrinsic

---

.github/dependabot.yml

It seems that we are not going to upgrade this dependency but rather wait for `jsonrpsee`. In the meantime the PRs raised by dependabot are somewhat annoying. This disables them.

Ignore `jsonrpc-*` in dependabot

---

frame/staking/src/pallet/mod.rs

This PR updates the weight refund for pallet-staking's rebond. The rebond benchmark is variant over the number of unlocking chunks iterated over; so in this PR we calculate the max amount of "relocked" chunks and pass that too `WeightInfo::rebond` to get the actual weight.

Fix staking `rebond` weight refund

---

frame/support/src/lib.rs

This small change produces much nicer generated code. Here's a diff between the `cargo expand` of the node runtime before and after:
```diff
...
impl<I: From<BlockLength>> ::frame_support::traits::Get<I> for RuntimeBlockLength {
fn get() -> I {
-        I::from(BlockLength::max_with_normal_ratio(
-            5 * 1024 * 1024,
-            NORMAL_DISPATCH_RATIO,
-        ))
+        I::from(Self::get())
}
}
pub struct RuntimeBlockWeights;
impl RuntimeBlockWeights {
/// Returns the value of this parameter type.
-    #[allow(unused)]
pub fn get() -> BlockWeights {
BlockWeights::builder()
.base_block(BlockExecutionWeight::get())
@@ -247,36 +242,19 @@
}
impl<I: From<BlockWeights>> ::frame_support::traits::Get<I> for RuntimeBlockWeights {
fn get() -> I {
-        I::from(
- …
```

Consistently use `I::from(Self::get())` in `parameter_types!`

---

Cargo.lock
client/consensus/babe/Cargo.toml

This dependency is no longer used so should be safe to drop

Remove unused pdqselect dependency from `sc-consensus-babe`

---

bin/node/executor/benches/bench.rs
client/api/src/call_executor.rs
client/executor/src/lib.rs
client/executor/src/native_executor.rs
client/light/src/call_executor.rs
client/service/src/builder.rs
client/service/src/client/call_executor.rs
client/service/src/client/client.rs
client/service/src/client/light.rs
client/service/src/client/wasm_override.rs
client/service/src/client/wasm_substitutes.rs
client/service/test/src/client/light.rs
primitives/consensus/common/src/lib.rs
primitives/version/src/lib.rs

Refactor `sc_executor::RuntimeInfo` trait into 2 parts

---

primitives/runtime/src/generic/mod.rs
primitives/runtime/src/generic/unchecked_extrinsic.rs

Actually this will cost us another allocation, but before this wasn't
really safe. Assuming that we only need `size_of` bytes for the encoding
of the tx could have ended with an invalid encoding.

Make `UncheckedExtrinsic` encode more readable

---

Cargo.lock
primitives/consensus/common/Cargo.toml

This PR follows #9319 and removes a dependency that is no longer required.

Remove dependency on substrate-prometheus-endpoint that is no longer required

---

frame/contracts/CHANGELOG.md
frame/contracts/fixtures/debug_message_invalid_utf8.wat
frame/contracts/fixtures/debug_message_logging_disabled.wat
frame/contracts/fixtures/debug_message_works.wat
frame/contracts/src/benchmarking/mod.rs
frame/contracts/src/tests.rs
frame/contracts/src/wasm/mod.rs
frame/contracts/src/wasm/runtime.rs
frame/election-provider-multi-phase/src/lib.rs
frame/support/src/storage/migration.rs
primitives/npos-elections/solution-type/src/lib.rs

Stabilize without changes as introduced in #8773. It is implemented in ink! and works as intended.

Stabilize `seal_debug_message`

---

client/transaction-pool/src/api.rs

The validate_transaction Runtime API was modified in https://github.com/paritytech/substrate/pull/8953/commits/fe3b52de422129a8ba53135265f679d23bfc8bea, with the addition of the block hash as 3rd argument.
The transaction pool api implementation for Full client was modified in order to add the 3rd argument to the remote call. However, the same was not done for the Light client implementation.
This is causing runtime panics in Full clients as seen in the following tracing log:
```
2021-08-12 17:43:00.044 TRACE tokio-runtime-worker sc_network::light_client_requests::handler: Remote call request from 12D3KooWMdQfHYMzUJcQ6Cqvz5opUUWzdWDbUZCDAXc5aqjbUZZN (TaggedTransactionQueue_validate_transaction at [21, 132, 2, 224, 102, 20, 232, 48, 8, 119, 125, 155, 201, 233, 120, 99, 67, 46, 144, 133, …
```

Fix issue with Light client remote call of validate_transaction

---

Cargo.lock
Cargo.toml
bin/node/browser-testing/Cargo.toml
bin/node/cli/Cargo.toml
client/authority-discovery/Cargo.toml
client/cli/Cargo.toml
client/consensus/common/Cargo.toml
client/executor/Cargo.toml
client/network-gossip/Cargo.toml
client/network/Cargo.toml
client/network/src/bitswap.rs
client/network/src/discovery.rs
client/network/src/peer_info.rs
client/network/src/protocol.rs
client/network/src/protocol/notifications/tests.rs
client/network/src/protocol/notifications/upgrade/notifications.rs
client/network/src/request_responses.rs
client/network/src/service.rs
client/network/test/Cargo.toml
client/peerset/Cargo.toml
client/telemetry/Cargo.toml
primitives/core/Cargo.toml
primitives/core/src/ecdsa.rs
primitives/io/Cargo.toml
primitives/io/src/lib.rs
test-utils/test-runner/src/host_functions.rs
utils/browser/Cargo.toml

libsecp256k1 allows overflowing signatures
https://rustsec.org/advisories/RUSTSEC-2021-0076
Changes were made to conform to libsecp256k1 version differences.
Closes #9356

RUSTSEC-2021-0076 bump libsecp256k1

---

bin/node-template/node/src/service.rs
bin/node/executor/src/lib.rs
bin/node/executor/tests/common.rs
bin/node/test-runner-example/src/lib.rs
client/executor/src/native_executor.rs
client/service/test/src/client/mod.rs
test-utils/runtime/client/src/lib.rs
test-utils/runtime/src/system.rs
test-utils/test-runner/src/lib.rs

Polkadot companion: https://github.com/paritytech/polkadot/pull/3643
Part of the `sc-executor` refactor. As the previous `NativeExecutionDispatch::dispatch(ext, method, data)` function was only used once, it was be inlined.

Simplify `NativeExecutionDispatch` and remove the `native_executor_instance!` macro

---

frame/support/src/traits/members.rs

Having `()` is rather confusing. Users should directly use `Nothing` or `Everything`.
polkadot companion: https://github.com/paritytech/polkadot/pull/3665

Do not implement () for Contains

---

utils/frame/benchmarking-cli/src/command.rs
utils/frame/benchmarking-cli/src/lib.rs
utils/frame/benchmarking-cli/src/writer.rs

This is useful to see the storage items touched by running a single benchmark, without needing to use a file output. 
example: 
```
Pallet: "pallet_election_provider_multi_phase", Extrinsic: "submit", Lowest values: [], Highest values: [], Steps: 5, Repeat: 3
Raw Storage Info
========
Storage: ElectionProviderMultiPhase SignedSubmissionIndices (r:1 w:1)
Storage: ElectionProviderMultiPhase CurrentPhase (r:1 w:0)
Storage: ElectionProviderMultiPhase SnapshotMetadata (r:1 w:0)
Storage: TransactionPayment NextFeeMultiplier (r:1 w:0)
Storage: ElectionProviderMultiPhase SignedSubmissionNextIndex (r:1 w:1)
Storage: ElectionProviderMultiPhase SignedSubmissionsMap (r:0 w:1)
Median Slopes Analysis
========
-- Extrinsic Time --
Model:
Time ~=     25.8
+ c    0.115
µs
Reads = 5 + (0 * c)
Writes = 3 + …
```

Show storage info in the raw benchmark output.

---

client/network/src/discovery.rs

> What does it do?
There is a request from Basti:
>2021-08-20 11:21:19 [//Bob] Libp2p => Unhandled Kademlia event: InboundRequestServed { request: FindNode { num_closer_peers: 3 } }    
2021-08-20 11:21:19 [//Eve (relay chain)] Libp2p => Unhandled Kademlia event: InboundRequestServed { request: FindNode { num_closer_peers: 3 } }    
2021-08-20 11:21:19 [//Charlie (relay chain)] Libp2p => Unhandled Kademlia event: InboundRequestServed { request: FindNode { num_closer_peers: 3 } }    
2021-08-20 11:21:19 [//Charlie (relay chain)] Libp2p => Unhandled Kademlia event: InboundRequestServed { request: PutRecord }
These are new events from libp2p we don't handle at the moment. They spam too much so we turn them from warning events into debug.

Change unhandled Kademlia events from warn to debug

---

Cargo.lock
utils/frame/remote-externalities/Cargo.toml
utils/frame/remote-externalities/src/rpc_api.rs
utils/frame/try-runtime/cli/src/lib.rs

Fixes https://github.com/paritytech/substrate/issues/9576
Note that we don't want to abort execution if there is a mismatch. For example, in substrate we want to only execute the migrations of one pallet over the state of polkadot. In this case, it is totally expected that the spec_names don't match. 
Example: 
```
2021-08-20 09:31:12.390  WARN main try_runtime_cli: version mismatch: remote spec name: kusama, expected (local chain spec, aka. `--chain`): development
```

Display warning on try-runtime spec_name mismatch

---

client/service/src/builder.rs

Fix https://github.com/paritytech/polkadot/issues/3688
See my comment in the issue.
This debug assertion can legitimately trigger if an error happens at initialization.

Remove spurious debug_assert!

---

client/executor/common/src/util.rs

This is a refactoring artifact introduced in #5920. It was taking a borrow of a `()` expression which does not have any effect.

Remove useless borrow

---

client/api/src/cht.rs
client/db/src/bench.rs
client/db/src/lib.rs
client/db/src/storage_cache.rs
client/light/src/backend.rs
client/service/src/client/call_executor.rs
primitives/state-machine/src/backend.rs
primitives/state-machine/src/in_memory_backend.rs
primitives/state-machine/src/lib.rs
primitives/state-machine/src/proving_backend.rs
primitives/state-machine/src/trie_backend.rs

Before we fetched the runtime code from the `TrieBackend` and this lead
to not using the storage cache. Thus, we recalculated the storage hash
for the runtime code on every call into the runtime and this killed the
performance on parachains block authoring. The solution is to fetch the
runtime code from the storage cache, to make sure we use the cached
storage cache.

Fetch runtime code from storage cache when using proofing backend

---

client/rpc/src/state/state_full.rs

The old implementation was listening for storage changes and every time
a block changed the `CODE` storage field, it checked if the runtime
version changed. It used the best block to compare against the latest
known runtime version. It could happen that you processed the storage
notification of block Y and checked the runtime version of block X (the
current best block). This is also what happened on parachains.
Parachains import blocks and set the new best block in a later step.
This means we imported the block that changed the code, got notified and
checked the runtime version of the current best block (which would still
be the parent of the block that changed the runtime). As the parent did
not changed the runtime, the runtime version also did not changed and we
never notified the …

Fix `state_subscribeRuntimeVersion` for parachains

---

primitives/runtime/src/generic/unchecked_extrinsic.rs

Without this patch, decode malicious input could take forever.
I don't think this is currently a DOS issue because OpaqueExtrinsic will ensure the length prefix must be valid.
However, I am experimenting some more custom transaction format and passing user supplied data to UncheckedExtrinsic, and some my of unit tests are taking forever to complete.

improve decode for UncheckedExtrinsic

---

client/rpc-api/src/state/mod.rs
client/rpc/src/state/mod.rs
client/rpc/src/state/state_full.rs
client/rpc/src/state/state_light.rs
client/tracing/src/block/mod.rs
primitives/rpc/src/tracing.rs

Add `methods` param for RPC `state_traceBlock` to fetch all changed storages for a given block.
Close #9632
```
curl \
-H "Content-Type: application/json" \
-d '{"id":1, "jsonrpc":"2.0", "method": "state_traceBlock", "params": ["0x0268dff7aa545d493e4640871bcdbb43a09240e5fb3efb91d9900782cabaed35", "f0c365c3cf59d671eb72da0e7a4113c4", "Put"]}' \
http://localhost:9933
```
```json
{
"jsonrpc": "2.0",
"result": {
"blockTrace": {
"blockHash": "08cba31b585b97feb68357fe1b6ca11de2335c346b41abfcbfb6a2667fbfd696",
"events": [
{
"data": {
"stringValues": {
"ext_id": "d515",
"key": "f0c365c3cf59d671eb72da0e7a4113c49f1f0515f462cdcf84e0f1d6045dfcbb",
"method": "Put",
"value": "Some(003b9e8b7b010000)",
"value_encoded": "01003b9e8b7b010000"
}
},
"parentId": …
```

Add methods param for RPC `state_traceBlock`

---

frame/contracts/Cargo.toml

Running `cargo check --features runtime-benchmarks` led to a compilation error when executed inside the pallet contracts directory. This was due to missing propagation of the `std` feature in some cases. This PR fixes that.
credits to @thiolliere for figuring that out

Fix compilation issue of `pallet_contracts`

---

primitives/api/proc-macro/src/decl_runtime_apis.rs

This fixes following clippy warnings appearing in other projects due to code generation:
```
error: the function `<R as
self::sp_api_hidden_includes_DECL_RUNTIME_APIS::sp_api::DecodeLimit>::decode_with_depth_limit` doesn't need a mutable reference
--> crates/sp-consensus-poc/src/lib.rs:248:1
|
248 | / sp_api::decl_runtime_apis! {
249 | |     /// API necessary for block authorship with PoC.
250 | |     pub trait PoCApi {
251 | |         /// Return the genesis configuration for PoC. The configuration is only read on genesis.
...   |
285 | |     }
286 | | }
| |_^
```
```
error: this function has too many arguments (8/7)
--> crates/sp-consensus-poc/src/lib.rs:248:1
|
248 | / sp_api::decl_runtime_apis! {
249 | |     /// API necessary for block authorship with PoC.
250 | |     pub trait PoCApi …
```

Fix clippy warnings

---

frame/election-provider-multi-phase/src/lib.rs

pallet election provider multi phase provide an origin but doesn't associated any logic anywhere.
What is it used for ?

Remove unused origin

---

Cargo.lock
client/authority-discovery/Cargo.toml
client/finality-grandpa-warp-sync/Cargo.toml
client/network/Cargo.toml

We were mixing `0.7.0` and `0.8.0` versions of the `prost` and `prost-build` crates.
Version `0.7.0` is causing some `clippy` CI trouble downstream.
**No code changes**

Use coherent `prost` crate  versions

---

bin/node/runtime/src/lib.rs
frame/democracy/src/lib.rs
frame/democracy/src/tests.rs
frame/democracy/src/tests/lock_voting.rs

Closes #9630 
polkadot companion: paritytech/polkadot#3734

Add VoteLocking config

---

bin/node-template/node/src/command.rs
bin/node-template/node/src/lib.rs

I recently used the `node-template` and those two things stood out to me:
* The file [`node-template/node/src/lib.rs`](https://github.com/paritytech/substrate/blob/master/bin/node-template/node/src/lib.rs) seems to be an old artifact. I don't see it referenced anywhere and can run the node without it.
* [`node-template/node/src/command.rs`](https://github.com/paritytech/substrate/blob/master/bin/node-template/node/src/command.rs#L1-L16) contains an Apache license header, but the `node-template` is unlicensed [here](https://github.com/paritytech/substrate/blob/master/bin/node-template/LICENSE).

Clean up `node-template`

---

client/network/src/block_request_handler.rs
client/network/src/protocol.rs
client/network/src/protocol/sync.rs
client/network/src/protocol/sync/blocks.rs
client/network/test/src/sync.rs

When computing block response size, the code was incorrectly counting extrinsics rather than bytes.
Also decreased `MAX_BLOCKS_TO_REQUEST` so that the nodes can sync without waiting for others to upgrade and tweaked timeout value.
Fixes https://github.com/paritytech/polkadot/issues/3778

Fixed block response limit check

---

.gitlab-ci.yml
client/utils/src/metrics.rs

In my opinion allowing failure for this CI check fails to accomplish what it is useful for: Allowing everyone to run `cargo fmt` without reformatting unrelated code. Code that is not properly formatted by `rustfmt` should be annotated to be skipped rather than failing the CI.

Don't allow failure for cargo fmt

---

primitives/state-machine/src/in_memory_backend.rs
primitives/state-machine/src/lib.rs
primitives/state-machine/src/trie_backend.rs
primitives/state-machine/src/trie_backend_essence.rs

Very small pr to reset root cache when building state (in some other branch my tests did fail due to the root caching when using test externalities).

reset cache when storage possibly change (fix init of tests).

---

.gitlab-ci.yml

This is a sort of a temporary change, needs to be merged and used until containers/buildah#3500 is fixed and released.
Discovered by @rcny
RH folks are already on it.

Fix buildah issue 3500

---

Cargo.lock
bin/node/cli/Cargo.toml
bin/node/cli/tests/check_block_works.rs
bin/node/cli/tests/common.rs
bin/node/cli/tests/database_role_subdir_migration.rs
bin/node/cli/tests/export_import_flow.rs
bin/node/cli/tests/inspect_works.rs
bin/node/cli/tests/purge_chain_works.rs
client/cli/src/config.rs
client/db/src/lib.rs
client/db/src/upgrade.rs
client/db/src/utils.rs

This is a cleaned up version of #8658 fixing #6880
polkadot companion: paritytech/polkadot#2923

Store the database in a role specific subdirectory

---

primitives/state-machine/Cargo.toml
primitives/state-machine/src/lib.rs
primitives/trie/src/trie_codec.rs

Found this while searching for possible issues for https://github.com/paritytech/cumulus/issues/598.
Not sure if it is the actual issue, but it is one.
The case where other child root is included in proof was incorrectly handled when the last child root included was not accessed.

Fix compact proof decoding unaccessed last child trie. 

---

.gitlab-ci.yml

[This line](https://github.com/paritytech/substrate/blob/47ee91efb1326df09ea8c8e50d444d48f2df84e2/.gitlab-ci.yml#L379) for `cargo unleash check ${CARGO_UNLEASH_PKG_DEF}` is failing consistently. The last time the status passed on master was on [2021-08-02](https://github.com/paritytech/substrate/commits/master?after=d3b4830728ec6e458654265db5372b0c583ba642+1&branch=master) and it had been intermittently failing even before that. I suggested to @TriplEight that the check should be disabled until it's taken care of.
cc @gnunicorn 
[skip ci]

Disable unleash-check

---

client/transaction-pool/src/lib.rs

With https://github.com/paritytech/substrate/pull/9228 `ChainApi` trait is only available in the `test_helpers` module - which's name is misleading when importing it as a dependency in a project.
This PR just reexports `ChainApi` and `Pool` - previously publicly available in `sc_transaction_graph` crate.

`graph::ChainApi` and `graph::Pool` reexport

---

primitives/state-machine/Cargo.toml
primitives/state-machine/src/lib.rs
primitives/trie/src/trie_codec.rs

This PR backports #9715 into the `polkadot-v0.9.10` branch.
* fix no child proof attached but root included.
* small stress test for proof of child tries.
* rust fmt

Fix compact proof decoding unaccessed last child trie.  (#9715)

---

primitives/runtime/src/traits.rs

This PR adds a setter for BlockNumberProvider if compiling with runtime-benchmarks features. This allows to write benchmarking that is independent to the BlockProvider used, as it allows to set the desired mocked block number.
This is a problem we have encountered in https://github.com/PureStake/crowdloan-rewards/pull/44 (cc @JoshOrndorff), where we want to write benchmark code that is agnostic of the block provider. But to benchmark correctly one of the extrinsics, we need to specifically set the block number in the block provider.

Add setter configurable only for benchmarking or tests

---

frame/benchmarking/src/lib.rs
frame/benchmarking/src/tests.rs
frame/benchmarking/src/utils.rs
frame/bounties/src/benchmarking.rs
frame/collective/Cargo.toml
frame/contracts/src/benchmarking/mod.rs
frame/election-provider-multi-phase/src/benchmarking.rs
frame/im-online/src/benchmarking.rs
frame/indices/Cargo.toml
frame/multisig/Cargo.toml

This PR fixes an issue where the benchmarking pipeline was converting a `BenchmarkError` into a string too early, and thus losing some of the information that could be propagated upward.
This simple change fixes that.

Dont Convert Benchmark Error Too Early

---

primitives/state-machine/Cargo.toml
primitives/state-machine/src/lib.rs

* the features `small_rng` for rand in dev dependency is misswritten and never used (or is the feature about configuring a faster rng for tests ?)
* some unneeded borrow of unit type was done (the type is `&()`).

Remove unused in state machine

---

Cargo.lock
client/cli/Cargo.toml

This PR updates the `names` crate that was depedending on a very old version of `rand`.

Update crate names and rand deps

---

client/network/src/request_responses.rs

Currently the exact cause of a network error is not shown in logs, which is quite cumbersome for debugging.

More descriptive errors.

---

frame/utility/src/tests.rs

pallet-utility: use new pallet attribute macro for tests

---

utils/frame/benchmarking-cli/src/template.hbs

Spellchecker keeps complaining that pallet name isn't a real word. This puts that text in a code block.

Fix Spellcheck for Benchmarking Template

---

client/network/src/transport.rs

> What does it do?
Previously the resulting type of transport was `OrTransport<OptionalTransport<EitherTransport<A,B>>, OptionalTransport<C>>`. Now it is `EitherTransport<EitherTransport<A,B>, OptionalTransport<C>>`.
The semantics is unchanged but the code is simplified a little bit.

Reduce the number of types in build_transport for transport

---

frame/system/src/extensions/check_nonce.rs

We would like to access this value from runtime for some custom tx signature verification.

make nonce public

---

bin/node/runtime/src/lib.rs
frame/im-online/src/benchmarking.rs
frame/im-online/src/lib.rs
frame/im-online/src/mock.rs
frame/offences/benchmarking/src/mock.rs
frame/session/src/lib.rs
frame/support/src/traits.rs
frame/support/src/traits/misc.rs
frame/support/src/traits/validation.rs
primitives/runtime/src/testing.rs

Fixes part of #8629
Refactor Im Online to use WeakBoundedVec instead of Vec, and generate storage info for that pallet.
polkadot companion: paritytech/polkadot#3744
@shawntabrizi @KiChjang @thiolliere

Generate storage info for pallet im_online

---

.gitlab-ci.yml
frame/support/test/Cargo.toml
frame/support/test/tests/construct_runtime_ui.rs
frame/support/test/tests/decl_module_ui.rs
frame/support/test/tests/decl_storage_ui.rs
frame/support/test/tests/derive_no_bound_ui.rs
frame/support/test/tests/pallet_ui.rs

Fix https://github.com/paritytech/substrate/issues/9799
Add feature "disable-ui-test" and use it for wasmer-sandbox ci

Add feature "disable-ui-test" and use it for wasmer-sandbox ci

---

frame/support/test/tests/pallet.rs

Currently if frame-system adds use a new type in some new storage or constant etc... then the test in frame-support-test needs to be updated and give the correct metadata to the system pallet to check.
Instead in this PR I remove the system pallet from the metadata and check the 2 example pallets.

Improve test in frame-support-test

---

.gitlab-ci.yml

This PR fixes the gitlab command error in the publish-docs CI job failure [as seen here](https://gitlab.parity.io/parity/substrate/-/jobs/1135813).
Would @TriplEight @rcny kindly this. Thanks.

Fix gitlab command

---

Cargo.lock
primitives/io/Cargo.toml

This dependency is unused and brings in the very heavy `zstd` along with it.

Remove unused `sp-maybe-compressed-blob` from `sp-io`

---

frame/babe/src/mock.rs

Cleaning up a left over variable after #9760

Removing a trailing `MaxSegmentLength`

---

frame/staking/src/lib.rs
frame/staking/src/pallet/mod.rs
frame/staking/src/tests.rs

Closes: https://github.com/paritytech/substrate/issues/9840

Fix amount emitted in rebonded event

---

shell.nix

Update nix shell. ( due to wasm32's unreachable not being an unsafe fn anymore  #9637 )

Point to nightly that can compile the code.

---

frame/support/src/traits/misc.rs

the type_name is generally used as a hint for generic type of a type. Here the `compact<u32>` is not generic for WrapperOpaque, thus we should just give no name:
https://github.com/paritytech/substrate/pull/9881#discussion_r718293534

Remove unidiomatic implementation

---

bin/utils/subkey/README.md

Closes #9874
Instructions are more detailed on devhub, ported minimal info to the README.
Docs: https://github.com/substrate-developer-hub/substrate-docs/blob/main/v3/docs/06-tools/a-subkey/index.mdx

subkey readme update on install

---

frame/contracts/src/exec.rs
frame/contracts/src/lib.rs
frame/contracts/src/tests.rs
frame/contracts/src/wasm/code_cache.rs

Use struct variants with field names for `Event`, instead of unnamed tuple variants. This will be automatically reflected (via the `TypeInfo` derive) in the metadata with variant fields having names attached.
Motivated by my having wasted a lot of time when I mixed up these fields `Instantiated(T::AccountId, T::AccountId)`
If this is acceptable then we can convert other pallet `Event`s to this style.

contracts: Add event field names

---

client/basic-authorship/src/basic_authorship.rs

The test is flaky because sometimes we hit the 9 seconds deadline when
the CI was probably on high load. To "solve" this we just use an huge
deadline that should never be triggered. The deadline isn't required anyway.

Fix basic authorship flaky test

---

bin/utils/subkey/README.md

adds the use from a container. I'd prefer to suggest using `podman` over `docker` though.

doc: subkey usage

---

frame/assets/src/impl_fungibles.rs
frame/support/src/traits/tokens/fungibles.rs

This introduces a very simple trait to inspect the metadata of an asset.
Closes: https://github.com/paritytech/substrate/issues/9877

Simple Trait to Inspect Metadata

---

frame/election-provider-multi-phase/src/unsigned.rs

target branch: kiz-improve-ocw-resubmit
target pr: https://github.com/paritytech/substrate/pull/9898
Prior to #9898, the election OCW cleared its cached solution whenever it saw events from `do_elect`. Now, the election OCW only clears its solution when run on the first block of the unsigned phase. In this PR the relevant test is updated to try and document the change.

Fix test for Substrate#9898 

---

primitives/core/src/crypto.rs
ss58-registry.json

Add SS58 prefix for Automata Mainnet and ContextFree Testnet
```
Mainnet => 2349
ContextFree => 11820
```

Add SS58 prefix for Automata

---

frame/support/src/storage/bounded_vec.rs

Implements core::fmt::Debug for BoundedVec by using sp_std instead of std. 
Fixes #9911

Implement core::fmt::Debug for BoundedVec

---

frame/im-online/src/lib.rs

Tiny quotes fix that snuck in lately (something I picked up elsewhere in document generation)

Small quoting comment fix for heartbeat storage

---

utils/wasm-builder/src/prerequisites.rs

I usually export `RUSTFLAGS` with an alternative linker ([mold](https://github.com/rui314/mold)) to speed up the compilation for development builds; unfortunately the check for the WASM toolchain fails when you do this as it then tries to use this linker for `wasm32-unknown-unknown` which obviously doesn't work. This PR fixes this issue by simply clearing RUSTFLAGS beforehand.

Do not propagate host RUSTFLAGS when checking for WASM toolchain

---

client/cli/src/commands/insert_key.rs

We should not "guess" the scheme as this can depend on the
implementation of the runtime etc.
Fixes: https://github.com/paritytech/substrate/issues/9888

Require crypto scheme for `insert-key`

---

frame/election-provider-multi-phase/src/lib.rs
frame/election-provider-multi-phase/src/unsigned.rs

No need to read events anymore, we can just remove the old cache in a different way.

don't read events in elections anymore.

---

client/chain-spec/src/chain_spec.rs

Previous error message was: `Error: Input("Error opening spec file: No such file or directory (os error 2)")`
Now we say which file we were looking for. (Also the two error messages are not exactly the same now so that they are unique.)

Improved file not found error message

---

docs/CONTRIBUTING.adoc

I read the instructions and got it wrong, so another attempt at simplifying the instructions.

Contributor doc tweak

---

Cargo.lock
client/tracing/Cargo.toml
client/tracing/benches/bench.rs
client/tracing/src/logging/directives.rs
client/tracing/src/logging/event_format.rs
client/tracing/src/logging/fast_local_time.rs
client/tracing/src/logging/mod.rs

This PR speeds up how we generate timestamps when logging; instead of regenerating them from scratch all the time we now cache part of the timestamp in TLS.
Here's the performance of the original implementation as measured on my machine:
```
chrono_local            time:   [871.11 ns 872.19 ns 873.30 ns] 
```
And here's the performance of the new one:
```
fast_local_time         time:   [35.994 ns 36.011 ns 36.030 ns]
```
So the overhead was cut down to less than 10%.
This will *not* help in normal cases where we're not logging much, but anytime someone turns on a spammy trace log (which does happen on our staking ops' nodes) the costs of logging starts to balloon. Yes, we shouldn't be logging this much. But if we do then it shouldn't bog down the CPU as much as it does.
Even though this …

Speed up timestamp generation when logging

---

frame/gilt/src/lib.rs

This value is not really meant to be "constant".
Part of the fix for: https://github.com/paritytech/polkadot/issues/4015

Remove `IgnoredIssuance` from metadata constants

---

client/cli/src/commands/run_cmd.rs

This changes `--dev` to imply `--tmp` when no explicit `--base-path` is provided.

`--dev` implies `--tmp`

---

Cargo.lock
bin/node/cli/Cargo.toml
frame/contracts/Cargo.toml
frame/support/Cargo.toml
frame/support/test/Cargo.toml
primitives/state-machine/Cargo.toml

This consolidates two versions of `pretty_assertions` to the 1.0 version as well as removing references to the unmaintained `difference` crate.

remove dep on unmaintained difference crate

---

frame/utility/src/lib.rs

The `batched_calls_limit` constant value includes the `size_of` of the runtime `Call`. As we compile
the runtime for native/wasm, we need to align the call size to ensure that it is the same on
wasm/native. This also solves the problem of different metadata outputs for the same runtime.
Progress on: https://github.com/paritytech/polkadot/issues/4015
CC @Slesarew

pallet-utility: Fix possible mismatch between native/wasm

---

frame/transaction-payment/src/lib.rs

related to https://github.com/paritytech/substrate/pull/9791
unsigned extrinsics do not pay fee in transaction-payment pallet, therefore `query_info` and `query_fee_details` should return no fee for unsigned extrinsics.
@JoshOrndorff @crystalin

Fix query_info and query_fee_details functions for unsigned extrinsics

---

Cargo.lock
client/api/src/execution_extensions.rs
client/offchain/Cargo.toml
client/offchain/src/api.rs
client/offchain/src/api/http.rs
client/offchain/src/lib.rs
primitives/core/Cargo.toml
primitives/core/src/lib.rs
primitives/core/src/offchain/mod.rs

If a chain doesn't require http support in its offchain workers, this pr enables them to disable the
http support.
Closes: https://github.com/paritytech/substrate/issues/9984

Offchain-worker: Make it possible to disable http support

---

Cargo.lock
client/chain-spec/Cargo.toml
client/chain-spec/src/chain_spec.rs

We export our chainspec to `fork.json` by `export-state` of substrate sub cmd, 
The `fork.json` is a 1.5GB json file.
In `ChainSpec::from_json_file`, 
First `use serde_json::from_file`, load `fork.json`, takes `~15 minutes`.
While using `serde_json::from_slice`, only takes `~2 s`, 
See https://github.com/serde-rs/json/issues/160

Speed up big chainspec json(~1.5 GB) load

---

frame/vesting/src/lib.rs

When testing a runtime upgrade using the `try-runtime` utility the vesting pallet panics because it's already migrated on our chain. This prevents us from testing our next runtime upgrade without messing around with the vesting pallet.
Could this get cherry-picked to the `polkadot-0.9.12` branch?

don't panic if already migrated

---

frame/contracts/src/exec.rs
frame/multisig/src/tests.rs
frame/proxy/src/tests.rs
frame/support/procedural/src/construct_runtime/expand/call.rs
frame/support/procedural/src/construct_runtime/expand/origin.rs
frame/support/procedural/src/construct_runtime/mod.rs
frame/support/test/tests/system.rs
frame/system/src/lib.rs
frame/utility/src/tests.rs

Fix https://github.com/paritytech/substrate/issues/9951
The error returned when the filter in the origin prevent the call to be dispatched was `BadOrigin`, it is now `frame_system::Error::CallFiltered`.
Currently when a call fail to be dispatched because the origin filter prevents it, then the error returned is BadOrigin.
This is lots of people confused, thinking it is the origin caller which is wrong, but it is actually the origin filter. (I understand that saying that the origin is made of 2 part the caller and the filter is maybe already a bad naming from my side).
Anyhow this PR will do that we return a new variant `CallFiltered` which have a corresponding description in the metadata:
```
/// The call has a bad origin, the origin filter prevent the call to be dispatched.
```
We can …

Better error for when origin filter prevent the call to be dispatched

---

frame/bags-list/remote-tests/Cargo.toml

adds missing crate versions to https://github.com/paritytech/substrate/pull/10036, which I think might be causing the merge failures in https://github.com/paritytech/polkadot/pull/4065

add missing version to dependencies

---

client/chain-spec/src/chain_spec.rs
client/chain-spec/src/extension.rs

Right now, chain specs can look like this:
```json
"genesis": {
"runtime": { }
}
```
Or like this:
```json
"genesis": {
"raw": { }
}
```
This PR adds a third variant:
```json
"genesis": {
"trie_root_hash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```
Substrate isn't capable of loading chain specs with this `trie_root_hash` variant and will probably not be capable in the near future, but I'm adding this variant anyway because the `chain_spec.rs` file of Substrate is kind of the reference of the format of the chain specs.
I would like to add support for this variant in smoldot (https://github.com/paritytech/smoldot/issues/1566), and this PR will provide a nice error message for people trying to load "smoldot chain specs" into Substrate.
EDIT: changed …

Add a `trie_root_hash` variant for chain specs genesis

---

frame/support/procedural/src/pallet/expand/type_value.rs
frame/support/procedural/src/pallet/parse/type_value.rs
frame/support/test/tests/pallet.rs

Fix https://github.com/paritytech/substrate/issues/10131#event-5545192992
Before doc attribute on the type_value item was unsupported, now it is handled, and doc are written on the generated struct.

Handle doc on type_value item in pallet macro

---

bin/node-template/node/src/chain_spec.rs
bin/node-template/runtime/src/lib.rs

Per #9681, the `construct_runtime!` section can now just specify the pallets, and no need to concretely set the generics they need for the template. 
~~I will create a new tag for this for the downstream template (`monthly-2021-11+1`)~~ 
~~I would like to **move the pre-release tag** (as the build was broken for the tag as it is now) to include it in updating it for the monthly release https://github.com/substrate-developer-hub/substrate-node-template/issues/258~~
No need to change tags, it will just be included in the template downstream :heavy_check_mark:

Update node-template  `construct_runtime!` syntax

---

primitives/runtime-interface/src/impls.rs

Saw this pop up when profiling; probably doesn't actually matter in practice, but it is an easy enough fix nevertheless.

Remove unnecessary allocations when crossing WASM FFI boundary

---

client/basic-authorship/src/basic_authorship.rs

This provides useful information to measure block production time (specially for parachain) without having to enable detailed logs for millisecond resolution.

Adds block production time in logs

---

client/service/src/chain_ops/import_blocks.rs

With block queue size of 1024 and 2 second poll time for the queue, the import speed is effectively limited to ~500 blocks/sec.

Speedup block import command

---

primitives/core/src/offchain/mod.rs

Accessing time related functionality is clearly not related to HTTP. So, this pr introduces a `TIME` capability.
Fixes: https://github.com/paritytech/polkadot/issues/4238

Offchain-worker: Accessing time is not HTTP

---

frame/assets/src/lib.rs
frame/assets/src/types.rs
frame/gilt/src/lib.rs
frame/support/src/lib.rs

frame_support::pallet_prelude: Add scale_info::TypeInfo

---

Cargo.lock
utils/frame/remote-externalities/Cargo.toml
utils/frame/remote-externalities/src/lib.rs

An easy and simple one, will just help in certain test scenarios.

new remote-ext mode `OfflineOrElseOnline`

---

bin/utils/subkey/README.md
client/cli/src/commands/run_cmd.rs
primitives/core/src/crypto.rs

Wiki context on SS58 page in:
https://github.com/substrate-developer-hub/substrate-docs/pull/466

Move SS58 wiki -> docs links

---

Cargo.lock
primitives/core/Cargo.toml

(also includes explicitly being a no_std crate when std feature not enabled).

upgrade ss58-registry with additional networks.

---

bin/node/cli/src/command.rs
bin/node/cli/src/service.rs

This exposes `rpc_handlers`, which is needed to use this in SubXt integration tests (https://github.com/paritytech/subxt/pull/318)

expose substrate-cli service

---

frame/collective/src/lib.rs

Currently the pallet collective allows other pallet to manage the member set through the implementation of `ChangeMembers` but also directly with `set_members` root call.
But both are quite incompatible. Or at least they must stay in sync.
Like currently on kusama if we call `set_members` without modifying the storage of pallet-membership they would get out of sync.
And the next call to `change_members` from pallet-membership will be inaccurate in regards to who are the member in pallet-collective.
I think this call is a bit error prone.

Warn about usage of pallet collective set members call.

---

bin/node-template/node/src/service.rs
bin/node/test-runner-example/src/lib.rs
client/rpc/src/testing.rs
client/service/src/builder.rs
client/service/src/lib.rs
frame/bags-list/remote-tests/src/sanity_check.rs
test-utils/test-runner/src/client.rs
test-utils/test-runner/src/node.rs

To match behavior on substrate master

jsonrpsee: add `rpc handlers` back

---

client/executor/common/Cargo.toml

Even though the Cargo.lock has 0.18.2, we update the required version of pwasm-utils Cargo.toml for sc-executor-common. See [this](https://github.com/paritytech/polkadot/pull/4267) for the reason.

Update requirement for pwasm-utils

---

Cargo.lock
bin/node/runtime/Cargo.toml

This fixes an issue where the `wasmer-sandbox` feature wasn't properly forwarded to `sp-sandbox`. The effect was that even though `sc-executor` was providing a wasmer sandbox (instead of a wasmi one), it wasn't used because `sp-sandbox` was using the embedded executor (as it should in production use cases to not rely on the sandboxing host functions). The reason why we need this forwarding is because `sp-sandbox` is part of the runtime and features supplied on the CLI are only applied when piped through the `node-runtime` crate.
You can see the effects from it in [this PR](https://github.com/paritytech/substrate/pull/9600) where there is no difference in weight.  The bug was introduced by: https://github.com/paritytech/substrate/pull/9592.
I reran the end-to-end benchmarks on Linux with …

Forward wasmer-sandbox feature to sp-sandbox

---

client/cli/src/config.rs
client/cli/src/params/shared_params.rs
client/tracing/src/logging/mod.rs

If this CLI flag is given, detailed log output will be enabled. This includes the log level, log
target ad the thread name. Before this was only enabled when a log level higher than `info` should
be logged.

Cli: Introduce `--detailed-log-output` flag

---

frame/vesting/src/migrations.rs

As the vesting migration could already have been done, people could already have started to merge schedules.
CC @koushiro 
Fixes: https://github.com/paritytech/substrate/issues/10275

Vesting: Fix `post_migration` check

---

frame/staking/src/pallet/mod.rs

As many people are unbonding, I've had to explain this to a handful of people recently. This improves the error message a bit and puts it in the error description, so that it is shown in the front page of all explorers if `unbond` fails, hopefully making it clear.

Update staking `InsufficientBond` erorr doc.

---

primitives/core/src/offchain/testing.rs
primitives/runtime/src/offchain/http.rs

Closes: https://github.com/paritytech/substrate/issues/10292

Offchain testing: Fix reading response

---

client/chain-spec/res/chain_spec.json
client/chain-spec/res/chain_spec2.json
client/chain-spec/src/chain_spec.rs

The `consensusEngine` field of chain specs hasn't been used in years. Let's no longer generate it, and allow decoding chain specs that don't have this field.

Don't generate the consensusEngine field in chain specs

---

Cargo.lock
client/offchain/Cargo.toml
client/offchain/src/api.rs
client/offchain/src/api/http.rs
client/offchain/src/lib.rs

Apparently some webpages now return http2 by default and that silently breaks the offchain http
extension. The solution to this is to enable the `http2` feature of hyper. Besides that, this pr
improves the logging to make it easier to debug such errors.
Closes: https://github.com/paritytech/substrate/issues/10299

Offchain worker: Enable http2 and improve logging

---

client/cli/src/runner.rs
client/service/src/task_manager/mod.rs
client/service/src/task_manager/tests.rs
test-utils/test-runner/src/node.rs

There is no reason for this function, tokio already blocks automatically until all tasks are ended.
Another reason to remove this feature is `mpsc_background_tasks` unbounded channel. Recently this
channel was reporting too many unprocessed elements. We assume that this was a result of a lot of
very shot lived tasks that somehow flooded this channel.
polkadot companion: https://github.com/paritytech/polkadot/pull/4336
skip check-dependent-cumulus

Taskmanager: Remove `clean_shutdown`

---

client/executor/wasmtime/build.rs
client/executor/wasmtime/src/host.rs
client/executor/wasmtime/src/imports.rs
client/executor/wasmtime/src/instance_wrapper.rs
client/executor/wasmtime/src/runtime.rs
client/executor/wasmtime/src/tests.rs
client/executor/wasmtime/src/util.rs

The current codepath for the WASM executor *without* instance reuse is broken. We're constantly reusing the same `Store`, which according to the [`wasmtime` docs](https://docs.rs/wasmtime/0.31.0/wasmtime/struct.Store.html) we're not supposed to do:
> A Store is intended to be a short-lived object in a program. No form of GC is implemented at this time so once an instance is created within a Store it will not be deallocated until the Store itself is dropped. This makes Store unsuitable for creating an unbounded number of instances in it because Store will never release this memory.
This results in a memory leak, and after 10k calls into the runtime the executor will get permabricked and will panic on each call since it won't be able to spawn any new instances anymore. (Fortunately this is …

Fix WASM executor without instance reuse; cleanups and refactoring

---

frame/benchmarking/src/analysis.rs

Fixes: https://github.com/paritytech/substrate/issues/9985

frame-benchmarking: Fix `min-square` for `--steps=1`

---

client/chain-spec/src/chain_spec.rs

Continuation of https://github.com/paritytech/substrate/pull/10303#issuecomment-975760198
Substrate will now accept when the field is missing, but still generate chain specs with this field.
We'll remove the field in a later version.

Put back consensus_engine, only accept its absence

---

.gitlab-ci.yml

Using ssh key is more secure because it has less scope of permissions
paritytech/ci_cd#259

[ci] Add ssh token for publishing gh-pages

---

frame/support/src/traits/metadata.rs

Derive `Debug` for `StorageVersion` so that logs on runtime migration are informative.
**Motivation:**
It is important to be able to verify that runtime migrations ran correctly, but the nature of runtime migrations makes it difficult to run with native execution, so types marked with `RuntimeDebug` will be stripped. This makes it difficult to verify the storage versions for the involved migrations from the logs.
This PR also derives `Debug` for `CrateVersion` as I see it having similar importance (though not for the motivating example for this PR).
related to #10351

Derive Debug for CrateVersion and StorageVersion

---

.gitlab-ci.yml

Removed `- rm -rf /tmp/*` from .gitlab-ci.yml (in `publish-rustdocs` job) because it breaks ssh-agent. Also it's not needed because /tmp is empty when container initialised.

[ci] Fix publish-rustdoc

---

frame/contracts/src/wasm/mod.rs
frame/contracts/src/wasm/runtime.rs

This stabilizes the new version of `seal_call` which is implemented in ink! now.

Stabilize "seal1" `seal_call`

---

client/network/src/protocol/notifications/handler.rs

Right now, if the channel is full, we'll just send `ForceClose` over and over again.
This code is not the greatest, but this channel is clearly meant to be removed and we'll never change our mind about this removal.

Don't send ForceClose repeatedly in send_sync_notification

---

frame/benchmarking/src/analysis.rs

This reverts commit fe7c02941122bbe4a7956aff53739b62f575240d.
And actually fixes the underlying issue. Basically, when there are only two or less data points for min squares, we fallback to median value.

REAL fix for `min-square` for `--steps=1 --repeats=1` (#10323)

---

client/network/src/block_request_handler.rs
client/network/src/light_client_requests/handler.rs
client/network/src/service.rs
client/network/src/state_request_handler.rs
client/service/src/client/mod.rs
utils/frame/try-runtime/cli/src/lib.rs

here are the doc which must be fixed: (some seems to link to removed items, some are linking to private items, and some others link to unreachable items) once this PR is merged I'll open an issue with the following items so we can track them and fix them later.
* https://github.com/paritytech/substrate/blob/4de8ee2dee389f4246f3156667fc3d6df7047e4f/client/network/src/block_request_handler.rs#L18
* https://github.com/paritytech/substrate/blob/4de8ee2dee389f4246f3156667fc3d6df7047e4f/client/network/src/light_client_requests/handler.rs#L22
* https://github.com/paritytech/substrate/blob/4de8ee2dee389f4246f3156667fc3d6df7047e4f/client/network/src/service.rs#L713
* https://github.com/paritytech/substrate/blob/4de8ee2dee389f4246f3156667fc3d6df7047e4f/client/network/src/service.rs#L778
* …

Remove invalid link without fixing them

---

frame/bounties/src/benchmarking.rs
frame/bounties/src/lib.rs
frame/tips/src/benchmarking.rs
frame/tips/src/lib.rs

Use the generic config traits in benchmarking instead of hard-coded constants so any runtime configuration can benchmark `pallet_tips` and `pallet bounties`

Tips Benchmarking to be Runtime Agnostic

---

bin/node-template/pallets/template/Cargo.toml
bin/node-template/runtime/Cargo.toml
frame/transaction-payment/asset-tx-payment/Cargo.toml

1. use double quotes instead of single quotes(For better matching when replacing batches)
2. upgrade 2021

Format cargo.toml & upgrade 2021

---

Cargo.lock
Cargo.toml
client/rpc-servers/src/lib.rs
client/rpc-servers/src/middleware.rs
client/service/src/lib.rs

Integrate jsonrpsee metrics

---

client/transaction-pool/src/graph/base_pool.rs
client/transaction-pool/src/graph/pool.rs

This extends logic used when enforcing limits on transaction pool by not only accounting for when transaction was inserted, but also what priority it has.
The logic here is that if transaction has higher priority (let's say equivocation report that has highest possible priority configured in BABE), it must not be possible to kick it out of transaction pool with transactions that have lower priority.
Polkadot address: 1vSxzbyz2cJREAuVWjhXUT1ds8vBzoxn2w4asNpusQKwjJd
skip check-dependent-cumulus

Account for transaction priority when enforcing limits

---

client/service/src/client/call_executor.rs
client/service/src/client/wasm_override.rs
primitives/runtime/src/runtime_string.rs

This adds support to the wasm-override feature to compare the spec_name. If the spec_name doesn't
match, a warning will be printed and the override will be ignored.
Closes: https://github.com/paritytech/substrate/issues/9685

wasm-override: Support checking `spec_name`

---

.gitlab-ci.yml

The fix is here https://github.com/paritytech/pipeline-scripts/pull/12

Fix cumulus companion checks

---

client/service/src/client/client.rs

So I'm opening this PR very naively. I don't really understand the design of the code of the client, but if I'm not mistaken this should remove the fact that right now `:code` and `:heappages` are included in every execution proof.
This was the case because the Substrate light client is incapable of caching the runtime code. Smoldot, however, is completely capable of doing that. Now that the Substrate light client is dead, there's no reason to keep that behavior.
This should reduce by a few megabytes the size of execution proofs.
Close https://github.com/paritytech/substrate/issues/5047

No longer include :code and :heappages in execution proofs

---

frame/session/src/lib.rs
frame/staking/src/lib.rs
frame/staking/src/pallet/impls.rs
primitives/npos-elections/src/lib.rs
primitives/npos-elections/src/reduce.rs
primitives/npos-elections/src/tests.rs

- makes sure that all staking/npos pallets compile (`check` and `test`)
- makes `reduce.rs` play a bit nicer with non-default account id types. 
ref: https://github.com/paritytech/substrate/pull/10403

make npos crates accept non-default account

---

frame/transaction-payment/src/lib.rs

Previously tip value of 1 is same as zero. Now it actually makes difference.
Not important at all so feel free to close this one if you think the previous behavior is ok.

allow tip value of 1

---

client/finality-grandpa/src/lib.rs
client/finality-grandpa/src/warp_proof.rs

This PR extends the GRANDPA authority set hard fork functionality to allow defining the changes as forced, i.e. enacted instantly instead of waiting for finality.
polkadot companion: https://github.com/paritytech/polkadot/pull/4486

grandpa: allow authority set hard forks to be forced

---

frame/system/src/lib.rs
frame/system/src/migrations/mod.rs

The previous behaviour made it impossible for any chain not already upgraded to dual reference counting to upgrade the runtime.
This proposed change is minimal, but attempts to fix [this logical issue](https://github.com/paritytech/substrate/issues/10336) for runtime upgrades. Currently, migrations from single or u8 reference counting do not seem to be possible even with custom migrations, due to an enforced behaviour of the pallet migration. I tried to detail examples in the issue.
fixes https://github.com/paritytech/substrate/issues/10336

Fixed logic of the storage migration to triple reference counting.

---

frame/assets/src/types.rs

Fix https://github.com/paritytech/substrate/issues/10391
For the doc of `frozen_balance` I actually can't really understand the doc, I tried to do what I think is the current implementation and in regards to what is discussed in the issue https://github.com/paritytech/substrate/issues/10391
For the doc of `died` I think we can improve the implementation in order not to have this error prone API. But I just documented the current behavior.

Improve pallet asset doc

---

frame/bounties/src/lib.rs
frame/bounties/src/tests.rs

Fixes https://github.com/paritytech/substrate/issues/10442
In the bounties pallet, in the unassign_curator extrinsic, under the arm where the sender is the curator themself, the bounty deposit is not reset to zero.
In other arms, this is being done as part of a utility function is used for slashing the deposit. But in this case, because we don't use this function, we should do this explicitly.
skip check-dependent-cumulus

Bounties - reset curator deposit when curator unassigns themself.

---

frame/contracts/src/benchmarking/code.rs
frame/contracts/src/benchmarking/mod.rs
frame/contracts/src/tests.rs
frame/contracts/src/wasm/code_cache.rs
frame/contracts/src/weights.rs

It turns out that https://github.com/paritytech/substrate/pull/10146 wasn't fixing the thing as I intended because I had the wrong assumptions. The weight for `instantiate_with_code` is actually correct to be that big because it includes the weight for loading the code into the sandbox which `call` forgoes.
👮‍♀️👮‍♀️👮‍♀️ So the actual bug is that the weight of `instantiate` and `call` is too low 👮‍♀️👮‍♀️👮‍♀️
After fixing this the weight of `instantiate_with_code` shouldn't look so high anymore in comparison because it saves the weight for loading the code into the sandbox which is now charged dynamically from the weight meter when  loading an existing code from storage (which does not happen in case of `instantiate_with_code`).

Fix contract instantiation weight

---

frame/system/src/weights.rs

This dispatchable was removed, so we don't need it anymore.
Closes: https://github.com/paritytech/substrate/issues/10458
polkadot companion: https://github.com/paritytech/polkadot/pull/4515
skip check-dependent-cumulus

frame-system weights: Remove `set_changes_trie_config`.

---

.gitlab-ci.yml
Cargo.lock
frame/support/test/Cargo.toml
frame/support/test/tests/derive_no_bound_ui/clone.stderr
frame/support/test/tests/derive_no_bound_ui/eq.stderr
frame/support/test/tests/pallet_ui/call_argument_invalid_bound.stderr
frame/support/test/tests/pallet_ui/call_argument_invalid_bound_2.stderr
frame/support/test/tests/pallet_ui/call_argument_invalid_bound_3.stderr
frame/support/test/tests/pallet_ui/event_field_not_member.stderr
frame/support/test/tests/pallet_ui/storage_info_unsatisfied_nmap.stderr
frame/support/test/tests/reserved_keyword/on_initialize.stderr
primitives/api/test/Cargo.toml
primitives/npos-elections/solution-type/Cargo.toml
primitives/runtime-interface/Cargo.toml
test-utils/Cargo.toml

Closes: https://github.com/paritytech/substrate/issues/10411
@TriplEight @alvicsam we need a new image with rust 1.57 and then we need to test that with this branch.

Prepare code for rust 1.57

---

client/consensus/aura/src/lib.rs
client/consensus/babe/src/lib.rs
client/consensus/slots/src/lib.rs

This allows block import params to do some async work.
In our protocol slot challenges are solved by an external app connected over RPC (which is why previously I needed `on_slot` to become async) and when solution is found block header needs to be signed by the same app (only that external app controls keypair and public key is already a part of the solution). In order to not block executor along the way, `block_import_params` needs to also become async.
I'm not happy about the complexity of the return type either :disappointed:

Async block import params

---

docs/CODEOWNERS

I haven't been maintaining offchain workers for a while, hence removing myself as a codeowner. CC @gnunicorn @dvdplm

Remove offchain workers ownership.

---

Cargo.lock
bin/node/cli/src/service.rs
client/consensus/aura/src/lib.rs
client/consensus/babe/rpc/src/lib.rs
client/consensus/babe/src/lib.rs
client/consensus/babe/src/tests.rs
client/consensus/manual-seal/src/consensus/babe.rs
client/consensus/slots/Cargo.toml
client/consensus/slots/src/lib.rs
primitives/consensus/aura/src/lib.rs
primitives/consensus/babe/src/lib.rs
primitives/consensus/common/src/lib.rs
test-utils/test-runner/src/client.rs
test-utils/test-runner/src/lib.rs

The slot duration should always be fetched from the runtime instead of being cached in the db. The
slot duration is only fetched on startup of the node, so the performance isn't that important. This
is especially helpful for the case when the slot duration of a chain should be changed through a
runtime upgrade (there be dragons, so take care).
polkadot companion: https://github.com/paritytech/polkadot/pull/4556
cumulus companion: https://github.com/paritytech/cumulus/pull/864

SlotDuration: Always fetch the slot duration from the runtime

---

frame/contracts/common/src/lib.rs

As per other `Balance` fields in RPC return types, for correctly serializing `u128`.

contracts: serialize `CodeUploadReturnValue` deposit as hex

---

frame/support/src/storage/child.rs

`frame_support::storage::child::exists` was using the `read` host function when the `exists` host function is the better fit.
Please note that this should not yield any substantial performance benefit because the substrate client does read the complete contents of the stored value from storage in both cases.

Use `exists` host function for child tries

---

bin/node/runtime/src/lib.rs
frame/contracts/src/lib.rs
frame/contracts/src/tests.rs

We are using the pallet-contracts to implement phala's smart contract. We constructed a minimal substrate runtime which include only pallet-contracts and it's dependencies. The runtime then can runs on multiple seperate storage instance. The problem is that contracts instantiated in different storage instance can have the same address, and we want the address to be unique in global.
To solve the problem, this PR adds a type parameter to generate ink addresses. The DefaultAddressGenerator keeps the original formula. And users can customize the address generation formula by implement a custom AddressGenerator.

Customizable ink address

---

client/chain-spec/src/chain_spec.rs
client/chain-spec/src/lib.rs

This switches the chain spec to use `BTreeMap` internally instead of `HashMap`. This ensures that
reading and writing the same chain spec always results in the same file.

chain-spec: Make chain spec writing deterministic

---

primitives/core/src/crypto.rs
primitives/core/src/ecdsa.rs
primitives/core/src/ed25519.rs
primitives/core/src/sr25519.rs

This improves the SS58 error, especially when it comes to parsing public keys with unknown SS58
address formats.

Improve SS58 related errors

---

.gitlab-ci.yml

Make `check-dependent-*` jobs only be executed in PRs instead of both PRs and master.
Reason 1: The companion is not merged at the same time as the parent PR ([1](https://github.com/paritytech/parity-processbot/issues/347#issuecomment-994729950)), therefore the pipeline will fail on master since the companion PR is not yet merged in the other repository. This scenario is demonstrated by the pipeline of https://github.com/paritytech/substrate/commit/82cc3746450ae9722a249f4ddf83b8de59ba6e0d.
Reason 2: The job can still fail on master due to a new commit on the companion PR's repository which was merged after `bot merge` happened, as demonstrated by the following scheme:
1. Parent PR is merged
2. Companion PR is updated and set to merge in the future
3. In the meantime a new commit is merged …

Make check-dependent-* jobs only be executed in PRs

---

frame/nicks/src/lib.rs

Pulling out the duplication which seemed to make it a bit more readable to me (and reinforces the 'Of' pattern).

Tweak to pallet-nicks

---

bin/node-template/README.md

This PR introduces a minor change adding some more detail in how to run a development chain with a persistent db.

node-template README persistent db

---

frame/uniques/src/functions.rs
frame/uniques/src/types.rs

We@Basilisk are planning to use our custom pallet-nft which is basically wrapped pallet-uniques with some customizations and extended permission functionality.
In order to use pallet-uniques' helper methods do\__method_ we need to make them pub. Also need to make DestroyWitness fields pub to use them - e.g. need to prevent destroying classes which contain instances.

Expose Uniques helper functions and DestroyWitness fields

---

client/service/src/client/call_executor.rs
primitives/state-machine/src/backend.rs

This will enable parachains to re-import a block without re-executing it.
Fixes: https://github.com/paritytech/substrate/issues/4455

Use storage transaction when running with proof recorder

---

client/finality-grandpa/src/environment.rs

At least for Polkadot, this should not result in spam and a warning will
very likely indicate some serious issue.

Warn on chain selection error.

---

.git-blame-ignore-revs

You can now easily exclude big automated code changes by running
`git config blame.ignoreRevsFile .git-blame-ignore-revs`
in your local repository. It will work also in IDE integrations.
You should add new commit hashes to this file when you create or find such big automated refactorings while reading code history. If you only know the short hash, use `git rev-parse eeccbf39` to expand it to the full hash needed in this file.
On versions of Git 2.20 and later comments (#), empty lines, and any leading and trailing whitespace is ignored. Everything but a SHA-1 per line will error out on older versions.

Exclude big changes from file annotations

---

frame/support/src/storage/child.rs
frame/support/src/storage/unhashed.rs

`runtime_print!` is printed by default using `debug`, aka not being visible. With `log::error!` it
will be printed directly to the user. Production networks like Polkadot disable logging, but for
them we run special nodes that have logging enabled.

frame-support: Use logging for printing corrupted state

---

frame/support/src/storage/mod.rs
frame/support/src/storage/types/counted_map.rs

Small refactor, add `into` function which conveerts `PrefixIterator<T, O1>` into another `PrefixIterator<T, O2>`

add into function for PrefixIterator

---

client/consensus/manual-seal/src/lib.rs
client/consensus/manual-seal/src/seal_block.rs

This PR fixes manual seal so that the block hash it returns to the RPC caller is the same hash that can later be used to look the block up in the database.
Previously manual seal was returning the hash of the block as was returned from the `Producer`. That is to say before any signature or other kind of seal was added.
This bug was caught by Moonbeam's CI, which also shows that this changes fixes it.
cc @seunlanlege

Manual Seal: Calculate the block's post hash

---

utils/frame/benchmarking-cli/src/command.rs

- Fix the progress log of benchmarks by adding spaces. `\t` seems to be ignored by the logger :man_shrugging:  
- Let the counter indices in the progress start at `1` instead of `0`. 
**Old output:**
```pre
Benchmark:frame_benchmarkinghashing5/500/1
```
**New output:**
```pre
Running Benchmark: frame_benchmarking.hashing 20/20 1/1
```

frame/bench-cli: fix log formatting

---

frame/aura/src/tests.rs
frame/authorship/src/lib.rs
frame/babe/src/mock.rs
frame/babe/src/tests.rs
frame/contracts/src/tests.rs
frame/executive/src/lib.rs
frame/grandpa/src/mock.rs
frame/merkle-mountain-range/src/tests.rs
frame/randomness-collective-flip/src/lib.rs
frame/system/src/lib.rs
frame/system/src/tests.rs

closes #10603
polkadot companion: https://github.com/paritytech/polkadot/pull/4696
cumulus companion: https://github.com/paritytech/cumulus/pull/894

reset events before apply runtime upgrade

---

.gitlab-ci.yml

Removes ssh installation in the `publish-rustdocs` job because the `node:16` image already has ssh client
Closes https://github.com/paritytech/ci_cd/issues/274

[ci] pipeline chores

---

frame/elections-phragmen/src/lib.rs

When looking at the maximum value a user can vote in Phragmen Elections, we should use the `free_balance` rather than the `total_balance`, else the pallet can create locks larger than the user has available balance, and will be in constant debt to the lock even when transferring more funds.
This update ensures we only allow voting up to the `free_balance` of the user, after any reserves have been placed for voting in the first place.

Use free balance rather than total balance for elections phragmen

---

primitives/runtime-interface/proc-macro/src/runtime_interface/bare_function_interface.rs
primitives/runtime-interface/proc-macro/src/runtime_interface/host_function_interface.rs
primitives/runtime-interface/proc-macro/src/utils.rs
primitives/runtime-interface/src/lib.rs
primitives/runtime-interface/test-wasm/src/lib.rs
primitives/runtime-interface/test/src/lib.rs

The runtime interface supports versioning of functions. Currently, if you add a new function it will
be used by the runtime automatically. This results in requiring all nodes of a network to upgrade
before the runtime is upgraded, otherwise they will fail to instantiate the new runtime because of
missing host functions. This pr introduces `register_only` functions. This can be used when a new
runtime interface function should be introduced, but the actual usage can be deferred. This means
that nodes will have the host function for this, but the runtime will still use the old version of
the function when being compiled for wasm. However, when a runtime is enacted that uses the new host
function, the "old nodes" will already have the host function and will continue to work.

runtime-interface: Implement `register_only` functions

---

primitives/api/proc-macro/src/decl_runtime_apis.rs
primitives/api/test/tests/runtime_calls.rs
test-utils/runtime/src/lib.rs
test-utils/runtime/src/system.rs
test-utils/runtime/transaction-pool/src/lib.rs

These are trivial tweaks I found while upgrading to latest master. This also restores one suppression in macro-generated code unnecessarily removed in #10570 and causing extra warnings in downstream projects.

Minor tweaks suggested by clippy

---

bin/node/runtime/src/lib.rs
frame/babe/src/mock.rs
frame/grandpa/src/mock.rs
frame/staking/src/lib.rs
frame/staking/src/pallet/impls.rs
frame/staking/src/pallet/mod.rs
frame/staking/src/slashing.rs
primitives/staking/src/lib.rs

This is needed for the upcoming pools pallet. There is zero logic change.
polkadot companion: https://github.com/paritytech/polkadot/pull/4728

Move `EraIndex` to sp-staking

---

frame/support/src/storage/bounded_vec.rs

This PR improves the `BoundedVec` API, porting some existing features of the standard `Vec` and adding some new features such as `force_push`, `slide`, etc... (see code for details)
Trying to simplify the diff in #10195, original author is @gavofyork

Improve BoundedVec API (extracted from #10195)

---

bin/node/primitives/src/lib.rs
primitives/core/src/crypto.rs

I searched `::report` and `REPORTING` in the codebase and found nothing, I guess this mod may no longer used, so remove it.
`::report` was add in https://github.com/paritytech/substrate/pull/3868 and removed in https://github.com/paritytech/substrate/pull/6656

the report mod and REPORTING keyType is no longer used

---

Cargo.lock
bin/node/cli/Cargo.toml
bin/node/executor/Cargo.toml
bin/node/runtime/Cargo.toml
bin/node/testing/Cargo.toml
client/cli/Cargo.toml
client/consensus/aura/Cargo.toml
client/consensus/babe/rpc/Cargo.toml
client/finality-grandpa/Cargo.toml
client/finality-grandpa/rpc/Cargo.toml
frame/grandpa/Cargo.toml
frame/indices/Cargo.toml
primitives/keyring/Cargo.toml
test-utils/client/Cargo.toml
test-utils/runtime/Cargo.toml

Not too long ago `sp-core`/`sp-runtime`/`sp-version` from Substrate were published to crates.io at 4.0.0, to make it possible to also publish `subxt`, which relies on them.
However, `subxt` also wants to use `sp-keyring` as a dev dependency, which was not published at that point. The result is that for local dev, `sp-keyring` pulls in a different version of `sp-core` than the 4.0.0 also requested, leading to duplocate trait issues and such.
Fortunately, at the tag `publish-sp-version-v4.0.0` on Substrate, `sp-keyring` is relying on 4.0.0 crates only, and so if it had been published as well at that point things would have been perfect.
This PR bumps `sp-keyring` to `4.1.0-dev` to allow us to retrospectively publish `sp-keyring 4.0.0` to crates.io at the Substrate tag …

Bump sp-keyring to 4.1.0-dev so that we can publish 4.0.0 in the past

---

Cargo.lock
client/executor/wasmtime/Cargo.toml
client/executor/wasmtime/src/runtime.rs
client/executor/wasmtime/src/tests.rs
primitives/wasm-interface/Cargo.toml

From [release notes](https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md) besides various fixes, there is SIMD support enabled by default.
The primary reason to upgrade was to make Substrate compile on latest nightly, see https://github.com/bytecodealliance/rustix/issues/142 for details.

Update wasmtime to 0.33.0

---

Cargo.lock
client/executor/common/Cargo.toml
client/executor/common/src/runtime_blob/data_segments_snapshot.rs
client/executor/common/src/runtime_blob/runtime_blob.rs
frame/contracts/Cargo.toml
frame/contracts/src/benchmarking/code.rs
frame/contracts/src/benchmarking/mod.rs
frame/contracts/src/schedule.rs
frame/contracts/src/wasm/env_def/macros.rs
frame/contracts/src/wasm/env_def/mod.rs
frame/contracts/src/wasm/prepare.rs
frame/contracts/src/wasm/runtime.rs

The crate `pwasm-utils` contains a lot of unused code and us largely unmaintained. The only parts of it that are in production use (by parity) is the stack height metering and gas instrumentation. All the "optimization" parts and CLI utils are provided by `binaryen`.
For that reason I created [a new repository](https://github.com/paritytech/wasm-instrument) where I removed all the unused functionality and cleaned up the documentation. [The old repository](https://github.com/paritytech/wasm-utils) should be archived after we made the switch with substrate.
This PR switches to the new crate `wasm-instrument`. No functionality changes where made when cleaning up the code.

Switch from `pwasm-utils` to `wasm-instrument`

---

utils/frame/benchmarking-cli/src/command.rs

make extrinsic argument contain list of comma separated extrinsic names as described in this issue #10665
Polkadot address: 12ZNas89oEagaxLVNbpqmvfMxdrGrqN7gJKSpwthTUPZsrku

bench/cli: extend --extrinsic name filtering

---

client/cli/src/params/network_params.rs
client/network/src/config.rs
client/network/src/protocol.rs
client/network/src/protocol/sync.rs
client/service/src/builder.rs

Close https://github.com/paritytech/substrate/issues/8610
This PR adds a new CLI option `--in-peers-light` whose value defaults to 100.
The "existing slots" (`--out-peers` and `--in-peers`) are now reserved only for full nodes, and these 100 new additional slots are reserved for light clients.
Note that this concerns only the syncing, transactions, and GrandPa/Beefy protocols/peer sets. The parachains-related code and any other user-added protocol isn't concerned.
The problem that this PR solves is that, currently, all the "in peers" of all nodes are always full. Since there is an equal number of "out peers" and "in peers", each full node on the network brings as many slots as it consumes.
Because some nodes are unfortunately behind a NAT, there are actually fewer available "in peers" …

Split peer slots between full and light nodes

---

bin/node/runtime/src/lib.rs
docs/Upgrading-2.0-to-3.0.md
frame/bounties/src/tests.rs
frame/child-bounties/src/tests.rs
frame/tips/src/tests.rs
frame/treasury/src/lib.rs
frame/treasury/src/tests.rs

Polkadot companion: https://github.com/paritytech/polkadot/pull/4739
Allow the treasury to have an upper limit to the size of bond required for proposals.

Allow the treasury to have a maximum bound on the bond

---

frame/support/src/storage/bounded_vec.rs

This small change improves the `force_insert_keep_left` API by first truncating the Vec, and then inserting the element, rather than inserting and then truncating. This prevents a potential memory allocation which may be needed to accept an additional element into the vector.

Improve Force Insert Keep Left for BoundedVec

---

utils/wasm-builder/src/lib.rs
utils/wasm-builder/src/wasm_project.rs

When building a wasm binary from a different repo inside a local workspace, we did not used the
correct `Cargo.toml` to find the correct patches and features. The solution to this is to just walk
up from the target directory until we find the workspace we are currently compiling. If this
heuristic isn't working, we print a warning and let the user set an env variable
`WASM_BUILD_WORKSPACE_HINT` to tell the `wasm-builder` where the actual workspace is.

wasm-builder: Improve workspace handling

---

frame/support/test/tests/pallet.rs
primitives/arithmetic/src/per_things.rs

- Add `MaxEncodeLen` to `implement_per_thing!`
- Test that Percent et.al. can be used in Storage. :point_right: I'm open to have a better way to test this.
Closes #10712

Add `MaxEncodeLen` to `implement_per_thing!`

---

frame/collective/src/lib.rs
primitives/core/src/crypto.rs

As we removed `Default` of account id, we have overseen some last bits. This pr removes these last
bits.
polkadot companion: https://github.com/paritytech/polkadot/pull/4765

Remove some last `AccountId32::default()` leftovers

---

utils/wasm-builder/src/wasm_project.rs

This is required for projects like Cumulus that have dependencies on `westend-runtime`, but this
runtime is only added when the `runtime-benchmarks` feature is enabled. By having all features
"enabled" in `cargo metadata` we ensure that all crates can be found.

wasm-builder: Enable all features when running `cargo metadata`

---

client/network/src/protocol.rs

cc https://github.com/paritytech/substrate/pull/10688
So apparently I'm failing at basic logic.
This properly implements the check:
`if current_connected_light_clients >= num_light_clients_allowed { reject }`

Fix #10688 being misimplemented

---

.gitlab-ci.yml
.maintain/rustdocs-release.sh

Signed-off-by: Jimmy Chu <jimmychu0807@gmail.com>
Followup PR of #10604 of changing the depending node package to be under **@substrate** namespace.
cc @TriplEight @alvicsam

Changing the node package to be under @substrate namespace

---

bin/node-template/runtime/src/lib.rs

https://github.com/paritytech/substrate/pull/10413 did not add the `CheckNonZeroSender` extension to the node template.
This PR remedies that.

add CheckNonZeroSender in node-template-runtime

---

Cargo.lock
bin/node-template/README.md
bin/node-template/docs/rust-setup.md
bin/node-template/node/Cargo.toml
bin/node-template/pallets/template/Cargo.toml
bin/node-template/runtime/Cargo.toml

Update Node Template README.md and rust install instructions from docs
`4.0.0-dev` version for templates
downstream: https://github.com/substrate-developer-hub/substrate-node-template/pull/300

Update Node Template

---

Cargo.lock
utils/frame/remote-externalities/Cargo.toml
utils/frame/remote-externalities/src/lib.rs
utils/frame/remote-externalities/src/rpc_api.rs

Introduced an `enum Transport` to decide whether to use a `existing connection` or `create a new connection URI`
The logic should be kept but after the ws connection is established the `URI` shouldn't be needed AFAIU, thus the enum.

remote ext: make it possible to use an existing ws connection

---

client/chain-spec/src/chain_spec.rs

cc https://github.com/paritytech/substrate/pull/10463
The overwhelming majority of the time the `fork_id` will be empty, so let's not include the field in chain specs if that's the case.

Add attributes and documentation to fork_id

---

Cargo.lock
frame/contracts/src/benchmarking/mod.rs
frame/contracts/src/tests.rs

Fix for the stack height metering. It increases the size of the dummy contract used in some `pallet-contracts` tests. This is why some changes there were necessary.

Bump `wasm-instrument` 0.1.0 -> 0.1.1

---

bin/node/cli/src/chain_spec.rs
bin/node/testing/src/genesis.rs
frame/democracy/src/tests.rs
frame/scheduler/src/lib.rs
frame/scheduler/src/tests.rs

V2 already supported origins, so we need to move them over instead of setting it to `Root`. Besides
that it also removes the custom `Releases` enum and moves it over to `StorageVersion`.
Fixes: https://github.com/paritytech/substrate/issues/10754

pallet-scheduler: Fix migrations V2 to V3

---

primitives/core/src/ecdsa.rs
primitives/core/src/ed25519.rs
primitives/core/src/sr25519.rs
primitives/runtime/src/lib.rs

Upgrading our project to 0.9.16 require us to derive **MaxEncodedLen** for all the storage persisted types. Which include a type embedding a `MultiSignature` for which **MaxEncodedLen** is not derived.
fixes https://github.com/paritytech/substrate/issues/10764

derive MaxEncodedLen for `MultiSignature`

---

primitives/arithmetic/src/fixed_point.rs

- Add `MaxEncodedLen` to `implement_fixed!`
- Test that the `Fixed*` types implement `MaxEncodedLen`
Closes #10766

Add `MaxEncodedLen` to `implement_fixed!`

---

frame/conviction-voting/src/benchmarking.rs
frame/conviction-voting/src/conviction.rs
frame/conviction-voting/src/lib.rs
frame/conviction-voting/src/types.rs
frame/conviction-voting/src/vote.rs
frame/referenda/src/branch.rs
frame/referenda/src/lib.rs

https://github.com/paritytech/substrate/pull/10195
in progress

More Referenda Patches

---

client/network/src/protocol/sync.rs
client/network/test/src/lib.rs
client/network/test/src/sync.rs

Currently sync won't download forks ahead of the best chain announced with `is_best=false` This PR removes this limitation as long as the fork is not too long.

Enable download of future forks

---

utils/wasm-builder/src/wasm_project.rs

Recent changes to `wasm-builder` made it error out when a custom profile is used that is not `production`. This breaks the polkadot build which defines the `testnet` profile. We fix this by falling back to `release` for unknown profiles and outputting a warning.

wasm-builder: Fall back to `release` profile for unknown profiles

---

.maintain/monitoring/alerting-rules/alerting-rule-tests.yaml
.maintain/monitoring/alerting-rules/alerting-rules.yaml
.maintain/monitoring/grafana-dashboards/substrate-networking.json
.maintain/monitoring/grafana-dashboards/substrate-service-tasks.json

Following #9543, metrics are now prefixed with `polkadot_` instead of `substrate`.
This PR update grafana dashboards and prometheus alert rules accordingly.

Substrate alerts rules update

---

Cargo.lock
frame/benchmarking/Cargo.toml
frame/benchmarking/src/utils.rs
utils/frame/benchmarking-cli/Cargo.toml
utils/frame/benchmarking-cli/src/command.rs
utils/frame/benchmarking-cli/src/lib.rs

The current output of the benchmarking-cli uses a mix of human-readable text and csv.  
This MR updates it JSON to make it machine readable. Maybe needs the "breaking change" label, not sure.
- Add `--json` to the benchmarking-cli: Print the raw data as json to stdout
- Add `--json-file=path`: Write the raw data into a json file
- Remove the `--raw` option
Example [balances.json.txt](https://github.com/paritytech/substrate/files/7985847/balances.json.txt)

bench-cli: Support `JSON` output

---

Cargo.lock
bin/node/cli/Cargo.toml
bin/node/executor/Cargo.toml
bin/node/runtime/Cargo.toml
bin/node/testing/Cargo.toml
client/cli/Cargo.toml
client/consensus/aura/Cargo.toml
client/consensus/babe/rpc/Cargo.toml
client/finality-grandpa/Cargo.toml
client/finality-grandpa/rpc/Cargo.toml
frame/grandpa/Cargo.toml
frame/indices/Cargo.toml
primitives/keyring/Cargo.toml
test-utils/client/Cargo.toml
test-utils/runtime/Cargo.toml

Version `5.0`, following on from #10772 which released `sp-core` and `sp-runtime` `5.0`, upon which `sp-keyring` depends.
Required for updating `subxt` to use these new `5.0` releases.

Release `sp-keyring`

---

frame/assets/src/functions.rs

Adds _maybe_total_supply_ to to pallet-assets functions. The previous _total_supply_ function does not allow us to distinguish between an assetId that does not exist or an assetId that exists but for which no tokens were minted.
The new _maybe_total_supply_  allows us to receive, similar to _maybe_balance_, an Option value. This would return None for a non-existent assetId.

maybe_total_supply in pallet-assets

---

client/executor/wasmtime/src/instance_wrapper.rs

Implements more efficient clearing of WASM instance memory on MacOS, similar to linux. 
This improves block import performance by a factor of 5 for empty blocks.

More efficient WASM instance memory decommit on macos

---

frame/identity/src/types.rs

In `pallet_identity`, `IdentityFields` is a wrapper around `BitFlags` that implement `Codec`. However, the inner field is `pub(crate)`, which prevents (de)constructing it, which is changed to `pub` in this PR.

make inner field of pallet_identity::IdentityFields pub

---

frame/nicks/src/lib.rs

- Fixed a small error in the inline docs. Probably a regression, the variable is called `target` and now `who` (anymore).

fixed regression in inline docs

---

utils/frame/try-runtime/cli/src/lib.rs

This PR adds doc about:
- A necessary flag for the expensive RPC queries that try-runtime requires
- A note reminder pre/post hook authors to be mindful about mutating the storage that is mean to be migrated (ref: https://github.com/paritytech/polkadot/pull/4772#discussion_r801150766)

try-runtime-cli: Add to docs

---

client/cli/src/commands/export_blocks_cmd.rs
client/cli/src/commands/export_state_cmd.rs

Add db params for export-state CLI command

---

frame/balances/src/lib.rs
frame/balances/src/tests.rs

The `set_balance` extrinsic could lead to an unexpected state change when trying to kill an account that cannot be killed. 
This resolves that issue, and adds a test to verify the behavior is working as expected.

Allow `SetBalance` to handle error when trying to kill acount with reference counter.

---

client/cli/src/commands/utils.rs

The `Network ID` printing format of `subkey` was missing due to refactoring somehow. 
This is the original PR #5457
This PR makes the network ID show again.

Show Network ID when creating and inspecting

---

client/network/src/service/out_events.rs

The `format!`s here were using 3.2% of the CPU; this should cut it down to roughly ~0.1%.

Reduce overhead of generating network event metrics

---

primitives/std/src/lib.rs

Allow trailing comma in map macro, and added some documentation

Allow trailing comma in map macro

---

utils/build-script-utils/src/version.rs

This is useful for build environments where the .git folder is not available. This is the case in nix since bundling a .git folder can lead to reproducibility issues.

build-script-utils: allow reading the git commit hash from env var

---

client/db/src/lib.rs

After the warp sync we don't want to create leaves in the database when importing ancient block history. Otherwise GRANDPA might request a path from each leaf to the last finalised block, which may potentially be huge.

Don't create DB leaves when syncing historic blocks

---

bin/utils/subkey/src/lib.rs

Fixes: https://github.com/paritytech/substrate/issues/10852

subkey: Support `--version` cli command

---

Cargo.lock
bin/node/runtime/Cargo.toml
primitives/keyring/Cargo.toml
utils/wasm-builder/src/wasm_project.rs

With latest nightly, aka rust version 1.60+ namespaced features are added. This changes the handling
of optional dependencies. We currently have features that enable optional dependencies when `std` is
enabled. This was before no problem, but now the wasm-builder detects them as enabled. To support
the transition period until 1.60 is released as stable, this pr adds an heuristic to not enable these
optional crates in the wasm build when they are enabled in the `std` feature. This heuristic fails
when someones enables these optional dependencies from the outside as well as via the `std` feature,
however we hope that no one is doing this at the moment. When namespaced features are enabled, these
dependencies needs to be enabled using `dep:dependency-name` to solve this properly. …

wasm-builder: Support latest nightly

---

bin/node/cli/Cargo.toml
client/cli/Cargo.toml
client/rpc-servers/Cargo.toml
client/service/Cargo.toml
utils/prometheus/Cargo.toml

This reduces the CPU usage by few percent. (It's hard to estimate the exact figure since the effects of this are not localized to a single place; eyeballing it it should be at least 3~4% less CPU.)

Enable the `parking_lot` feature for `tokio`

---

frame/beefy-mmr/src/mock.rs
frame/beefy-mmr/src/tests.rs
frame/beefy/src/mock.rs

Compressed ECDSA keys requires to have a valid first byte (0x02 || 0x03) in order to allow public key recovery.
Nevertheless the test was working because of the `unwrap_or_default()` at the end of the [conversion method](https://github.com/paritytech/substrate/blob/2d8b02af1852d51b7d6a15d6d98b41b76bac614a/frame/beefy-mmr/src/lib.rs#L78-L89) (i.e. the invalid keys were converted to an empty vector).

Fix beefy mock ecdsa keys

---

Cargo.lock
client/finality-grandpa/Cargo.toml
client/finality-grandpa/src/communication/gossip.rs
client/network-gossip/Cargo.toml
client/network-gossip/src/state_machine.rs

This reduces the CPU usage by ~3.8%.
This was achieved by strategically replacing Rust's standard hash function with the one from the [`ahash` crate](https://crates.io/crates/ahash). I've only done this where it matters, that is - I haven't replaced it everywhere, just in places where it makes a measurable real world impact.
`ahash` should also be DoS-resistant, so this should essentially be free performance.

Reduce CPU overhead of gossip

---

client/consensus/babe/src/lib.rs
client/transaction-pool/src/graph/validated_pool.rs

Recent std contains a feature-gated implementaion of `retain_mut`. To avoid ambiguity, this PR uses qualified syntax to explicitly call `RetainMut::retain_mut`.
Please review carefully, since the PR touches consensus code.

Use qualified syntax for `retain_mut`

---

frame/election-provider-multi-phase/src/benchmarking.rs
frame/election-provider-multi-phase/src/lib.rs
frame/election-provider-multi-phase/src/signed.rs
frame/election-provider-multi-phase/src/unsigned.rs
primitives/arithmetic/src/lib.rs
primitives/npos-elections/fuzzer/src/phragmen_balancing.rs
primitives/npos-elections/fuzzer/src/phragmms_balancing.rs
primitives/npos-elections/src/lib.rs
primitives/npos-elections/src/tests.rs

This PR refactors the old `ElectionScore` from being an `[u128; 3]` to a struct with named fields, and deprecated the old `is_score_better` function that's quite un-ergonomic. The entire logic around this function should have remained unchanged. 
The only new piece of logic added is the new `Ord` implementation, which has associated tests, and is not really used anywhere in production.   
polkadot companion: https://github.com/paritytech/polkadot/pull/4927

refactor election score

---

Cargo.lock
client/executor/Cargo.toml
client/executor/src/native_executor.rs
client/executor/src/wasm_runtime.rs

Improves the logging by switching to `tracing` for a better log output. Besides that, it also adds a
trace for the function being executed.

sc-executor: Improve logging

---

client/network/src/protocol/sync.rs

Alternative to https://github.com/paritytech/substrate/pull/10842

Track allowed requests for state/warp sync

---

client/consensus/slots/src/lib.rs

Parachains have currently a total proposing time of 500ms, so it this
currently always prints `0`. While actually the value is not `0` ;)

Slots: Log total proposing duration as milliseconds

---

frame/staking/src/lib.rs

Clarifies how the pro rata distribution of rewards is calculated.

staking: Clarify reward calc docs

---

primitives/tracing/src/lib.rs

This function is useful for tests. It will enable `TRACE` logging and also uses the libtest aware writer.

tracing: Adds `init_for_tests`

---

frame/election-provider-multi-phase/src/lib.rs

To make it simpler to use the `EPM pallet`, useful for instance in the staking miner.
FYI, I'm not aware of the rationale why this was not public in the first place but I hope this is ok.

[EPM pallet]: make submissions types public

---

Cargo.lock
bin/node-template/node/src/service.rs
bin/node/cli/src/service.rs
client/consensus/aura/src/lib.rs
client/consensus/babe/rpc/src/lib.rs
client/consensus/babe/src/lib.rs
client/consensus/babe/src/tests.rs
client/consensus/manual-seal/src/consensus/aura.rs
client/consensus/manual-seal/src/consensus/babe.rs
client/consensus/manual-seal/src/consensus/timestamp.rs
client/consensus/slots/src/lib.rs
primitives/consensus/aura/src/inherents.rs
primitives/consensus/aura/src/lib.rs
primitives/consensus/babe/src/inherents.rs
primitives/consensus/babe/src/lib.rs
primitives/consensus/common/src/lib.rs
primitives/consensus/slots/Cargo.toml
primitives/consensus/slots/src/lib.rs
primitives/timestamp/src/lib.rs

The slot duration was defined in a weird way in that it wrapped some generic config object which was used e.g. to hold the `BabeGenesisConfiguration`. This was unnecessarily complicated for no reason (why should the slot worker care about some inner config?). This PR introduces a new primitive type `SlotDuration`, that just wraps a `u64` representing a duration in milliseconds, which is used throughout the code that interacts with slots (aura and babe).
polkadot companion: https://github.com/paritytech/polkadot/pull/4940
cumulus companion: https://github.com/paritytech/cumulus/pull/993

consensus-slots: cleanup SlotDuration config

---

Cargo.lock
Cargo.toml
frame/beefy-mmr/Cargo.toml
frame/beefy-mmr/src/lib.rs
frame/contracts/Cargo.toml
frame/contracts/src/benchmarking/mod.rs
frame/contracts/src/tests.rs

This PR affects a very circumscribed section of two FRAME pallets:
- `beefy-mmr` ECDSA public key to ETH id conversion
- `contracts` benchmarking 
Motivations are mostly related to performance. Refer to [benches](https://github.com/davxy/crypto-benches) for details.
This PR somehow relates to https://github.com/paritytech/substrate/pull/10798 where `libsecp256k1` has been replaced with `secp256` for `sp-io` and `sp-core` crates.
In the future, when the performance gap is less important, the plan is to port everything to `k256` pure rust implementation.

Replace libsecp256k1 with k256 in FRAME related code

---

client/cli/src/arg_enums.rs
client/cli/src/params/network_params.rs
client/cli/src/params/shared_params.rs
client/network/src/config.rs

Before switching to clap3 we support cli options like `--reserved-nodes A B` and after you needed to
pass `--reserved-nodes` cli option multiple times `--reserved-nodes A --reserved-nodes B`. This is
fixed by setting `multiple_occurrences(true)` option. This also done for all the other `Vec` cli
options in `sc-cli`. Besides that `--sync` wasn't supporting case insensitive parsing of the value.
This is now also supported. For both regressions a test is added. Besides that the pr removes all
the `rename_all = PascalCase` attributes, because they are not needed. All other `ArgEnum`s were
checked and all are already using `ignore_case(true)`.

sc-cli: Fix bugs after switching to clap3

---

Cargo.lock
bin/node-template/node/Cargo.toml
bin/node-template/node/src/cli.rs
bin/node-template/node/src/command.rs
bin/node-template/runtime/Cargo.toml
bin/node-template/runtime/src/lib.rs

Integrated try-runtime into the node template as requested in https://github.com/paritytech/substrate/issues/10892
Fixes #10892 
@kianenigma Please help review to see if this correctly addresses #10892

Integrate try-runtime into substrate node template

---

frame/staking/src/pallet/mod.rs

accidentally removed in https://github.com/paritytech/substrate/pull/10601.

Bring back MaxNominations as a metadata constant

---

frame/transaction-payment/src/lib.rs
frame/vesting/src/lib.rs

**Description:**
This PR is a follow-up PR for cleaning up leftovers renaming todos for macro `extra_constnat`.
Related: #8826

Clean up todo items for `extra_constant` renaming.

---

frame/whitelist/Cargo.toml

#10937 was force merged minutes after https://github.com/paritytech/substrate/pull/10159 which added a new pallet. So the versions need updating

Update new whitelist pallet to new primitive versions

---

frame/support/src/weights.rs
frame/support/src/weights/block_weights.rs
frame/support/src/weights/extrinsic_weights.rs

No logic change:  
- Move the block and extrinsic weights into their own module to allow for easier automatic generation in the future. 
Preparation for https://github.com/paritytech/substrate/issues/10921

Move weight constants to own mod

---

frame/system/src/lib.rs
primitives/arithmetic/src/per_things.rs

not sure if a good idea, I needed them for some testing, and figured it might be good to have around. The code block is a bit ugly though.

add block usage logs to system pallet

---

bin/node/runtime/src/lib.rs
frame/bags-list/remote-tests/src/lib.rs
frame/bags-list/src/benchmarks.rs
frame/bags-list/src/lib.rs
frame/bags-list/src/list/mod.rs
frame/bags-list/src/list/tests.rs
frame/bags-list/src/mock.rs
frame/bags-list/src/tests.rs
frame/election-provider-support/Cargo.toml
frame/election-provider-support/src/lib.rs
frame/staking/src/benchmarking.rs
frame/staking/src/mock.rs
frame/staking/src/pallet/impls.rs
frame/staking/src/pallet/mod.rs

polkadot companion: https://github.com/paritytech/polkadot/pull/5065
This is a breaking change to some public APIs, but contains zero logic changes.
While this doesn't change any logic, it technically is a breaking change for the `SortedListProvider,` `pallet-bags_list::Config`, and `VoteWeightProvider` which gets renamed too `ScoreProvider`. All through of the aforementioned get a new associated type, `Score`, which replaces the concrete type `VoteWeight`. For those who need to migrate to the new APIs, simply set `Score = VoteWeight`. Check out the polkadot companion for examples

Make bags-list generic over node value and instantiable

---

client/finality-grandpa/src/lib.rs

sc-finality-grandpa: use the #[from] attriute to remove boilerplate code

---

client/cli/src/arg_enums.rs
primitives/core/Cargo.toml
primitives/core/src/ecdsa.rs

This pr changes the feature set of `secp256k1` to not use `global-context` when only the
`full_crypto` is enabled. It will be slower when the `std` feature is not enabled as the context
always needs to be recreated, but that is fine.
Closes: https://github.com/paritytech/substrate/issues/11005

sp-core: `full_crypto` doesn't imply `std`

---

primitives/api/proc-macro/src/impl_runtime_apis.rs
primitives/state-machine/src/ext.rs
primitives/state-machine/src/overlayed_changes/mod.rs
primitives/state-machine/src/testing.rs
utils/frame/try-runtime/cli/src/commands/follow_chain.rs

Ref https://github.com/paritytech/substrate/pull/10922#issuecomment-1064258443
CC @cheme

Remove unused `parent_hash` in `OverlayedChanges::into_storage_changes`

---

primitives/api/proc-macro/src/decl_runtime_apis.rs
primitives/api/proc-macro/src/impl_runtime_apis.rs

Ensure that the sp api macros don't use functions without providing the full path to the function.
This hygiene ensures that we don't actually try to call a method of an imported trait for example.

sp-api: Don't be dirty

---

Cargo.lock
bin/node-template/node/Cargo.toml
bin/node/bench/Cargo.toml
bin/node/cli/Cargo.toml
bin/node/cli/build.rs
bin/node/inspect/Cargo.toml
bin/utils/chain-spec-builder/Cargo.toml
bin/utils/subkey/Cargo.toml
client/cli/Cargo.toml
client/cli/src/arg_enums.rs
client/cli/src/lib.rs
client/cli/src/params/import_params.rs
primitives/npos-elections/fuzzer/Cargo.toml
utils/frame/benchmarking-cli/Cargo.toml
utils/frame/benchmarking-cli/src/lib.rs
utils/frame/frame-utilities-cli/Cargo.toml
utils/frame/generate-bags/node-runtime/Cargo.toml
utils/frame/try-runtime/cli/Cargo.toml
utils/frame/try-runtime/cli/src/lib.rs

Besides that it also removes some `structopt` leftovers from some docs.

Update clap to the latest version

---

frame/nomination-pools/benchmarking/src/lib.rs
frame/nomination-pools/benchmarking/src/mock.rs
frame/nomination-pools/src/lib.rs

target branch: zeke-staking-pools

nomination-pools: update benches for new account format

---

utils/frame/benchmarking-cli/src/lib.rs
utils/frame/benchmarking-cli/src/storage/cmd.rs
utils/frame/benchmarking-cli/src/storage/read.rs
utils/frame/benchmarking-cli/src/storage/record.rs
utils/frame/benchmarking-cli/src/storage/template.rs
utils/frame/benchmarking-cli/src/storage/weights.hbs
utils/frame/benchmarking-cli/src/storage/write.rs

Fixes #10929.
In this PR additional convenience flags are added to `benchmark-storage`.
- `--json-read-path` and `json-write-path`, each of which produces output at the specified location for their respective operations, defaulting to _no_ JSON output if neither are specified. If a directory is specified, default names are used.
- A custom handlebars template can now be specified with `--template-path`
Additionally,
- The block ID is added to the `weights.hbs` handlebars template and produces the following output:
```
...
//! DATABASE: `RocksDb`, RUNTIME: `Development`
//! BLOCK-ID: `BlockId::Number(0)`
//! SKIP-WRITE: `false`, SKIP-READ: `false`, WARMUPS: `1`
...
```
- The warmup rounds are extended to include `write` benchmarks. 
- I'm not sure how to test this one and just mirrored the …

Additional `benchmark-storage` flags

---

Cargo.lock
frame/contracts/fixtures/delegate_call.wat
frame/contracts/src/benchmarking/mod.rs
frame/contracts/src/tests.rs
frame/contracts/src/wasm/mod.rs
frame/contracts/src/wasm/runtime.rs

There is a working ink waterfall test. We can stabilize.

contracts: Stabilize `seal_delegate_call`
